### ISSUE TITLE
not supported type SYB-MSDATETIME2

### ISSUE THREAD

**Issue by hesampour** [dimitri/pgloader#1018]
I want to convert mssql to postgre sql. but I get this error for datetime2 conversion

not supported type SYB-MSDATETIME2

**Comment by hesampour** [comment]
Is there any way to exclude datetime2 type?

**Comment by andnig** [comment]
Hey guys, I'm experiencing the same issue at the moment.
Any ideas for a workaround?

**Comment by semenmiroshnichenko** [comment]
Yes, I forgot to mention it: with my PR you still need to cast datatime2 explicitly. We did it by 
`cast type datetime2 to timestamptz`, and it works.

**Comment by efnineio** [comment]
Interesting, when i tried that i get the error as such:

"ERROR Database error 22007: invalid input syntax for type timestamp with time zone: "Jun  3 2019 11:27:09:0700000AM""

i'm wondering why the datetime2 is coming out in that format, rather than the typical "yyyy-mm-dd" format.   Maybe a server side setting for default date format?

**Comment by semenmiroshnichenko** [comment]
But was you able to build pgloader with our patch from PR above or you fixed it only by adding cast?

**Comment by gjvoosten** [comment]
> Interesting, when i tried that i get the error as such:
> 
> "ERROR Database error 22007: invalid input syntax for type timestamp with time zone: "Jun 3 2019 11:27:09:0700000AM""
> 
> i'm wondering why the datetime2 is coming out in that format, rather than the typical "yyyy-mm-dd" format. Maybe a server side setting for default date format?

@efnineio The date format can be changed in FreeTDS' `locales.conf`; e.g. for me I had to change the default (note that for FreeTDS, `%z` means something different from strftime, see https://www.freetds.org/userguide/locales.htm ):
```
[default]
        #date format = %b %e %Y %I:%M:%S:%z%p
        date format = %Y-%m-%d %H:%M:%S.%z
```
Then, with both the patch ( https://github.com/dimitri/pgloader/pull/1036 ) and the cast, it worked for me.

**Comment by efnineio** [comment]
Ah yes, i didn't think about freetds settings.  
Worked for me! (on a modified docker image from this 
To sum up 3 steps made this 
1) add the ":syb-msdatetime2" to the mssql.lisp file per the pull request above
2) explicitly cast the type "cast type datetime2 to timestamptz"  in the command file
3) add a file /etc/freetds/locales.conf with the lines
[default]
        date format = %Y-%m-%d %H:%M:%S.%z

That got it to work for me.  thank you!

**Comment by ekeric13** [comment]
I was having a lot of trouble with even following all the suggestions.

What finally solved it for me was that I realized that when you run `apt-get install pgloader` it installs version 3.6.1 and not 3.6.3.

When I downloaded the latest version, currently 3.6.3, I was able to get passed this error.
