### ISSUE TITLE
Speed is  as slow as 1.5Mps Using pgloader (docker) under OSX Mojova

### ISSUE THREAD

**Issue by hdanet** [dimitri/pgloader#1019]
environment :OSX ,
SSD,
pgloader(docker),
postgresql11.5,
tables without index,
files without error data.
when I use pgloader to import data into database, it is very slow, say speed is only 1.5MPS or lower.I expect that using SSD the speed maybe at 100MPS. why so slow ?Would you please share your opinion?Thank you.

https://github.com/dimitri/pgloader/issues/251 enlight me but no better performance.

**Comment by dimitri** [comment]
Did you try and analyse the performance of your system when pgloader is running? Do you want to try and contribute to make it faster? What kind of source are you using? etc etc
