### ISSUE TITLE
Heap exhausted during allocation:122028032 bytes available,241810896 requested.

### ISSUE THREAD

**Issue by hdanet** [dimitri/pgloader#1020]
Heap exhausted during allocation: frequently popup.
what can I do to avoid it?
when it happens, what should I do?wait? or kill it?
what happened to database?dirty data?for example, when import 1.0g data ,how about the rest data? what should I do to make data consistent?
Thank you very much .

WARNING: Couldn't re-execute SBCL with proper personality flags (/proc isn't mounted? setuid?)
Trying to continue anyway.
2019-09-04T21:54:50.066000Z LOG pgloader version "3.6.2-devel"
Heap exhausted during allocation:122028032 bytes available,241810896 requested.
Gen StaPg UbSta LaSta LUbSt Boxed Unboxed LB LUB Imove Alloc Waste Trig MP GCs Mem-age
0:000610000032768 10737418 000.00001:000011 292 023772 11482 788185952 703648 798923370 5 2 0.00002:0000000000010737418 000.00000000000000010737418 000.00004:0000000000010737418 000.00005:0000173 743 39 047 30978992 314448 41716410 153 316 0.00006:00001890 1222 000101974016 02000000 1786 00.0000
Total bytes allocated =921138960
Dynamic-space-size bytes=1073741824
GC control variables:
* GC-INHIBIT*= false
* GC-PENDING*= true
* STOP-FOR-GC-PENDING*= false debugger invoked on a SB-KERNEL:: HEAP-EXHAUSTED-ERROR in thread
#<THREAD "lparalle1"RUNNING {100619B1B3}>: Heap exhausted(no more space for allocation).
122028032 bytes available,241810896 requested.
PROCEED WITH CAUTION.

**Comment by hdanet** [comment]
You can also try to limit the amount of memory that's used by pgloader by tweaking the batch size parameters, starting with prefetch rows = 10000 (it defaults to 100 000 which is a lot of rows if you have a table with either lots of columns or maybe very large values). See https://pgloader.readthedocs.io/en/latest/pgloader.html#batch-behaviour-options.

failed.


Looks like 8192 is out of range but i tried 3500 and that brought me to the terminal. Do you know if there is a way to verify this now?

I'll also try the migration to see if it gets me past this error for now to see if that helps.

I was able to get past this error. Basically at first i was specifying DYNSIZE=8192, and this got me the error above. As a test i upped the DYNSIZE=20000 and it got me past my error.

how? 

I use docker to run pgloader.

**Comment by hdanet** [comment]
And I have no idea what happened to my database ,dirty data ?

**Comment by asherbar** [comment]
Using WITH prefetch rows = 10000 solved it for me.
