### ISSUE TITLE
Importing from SQLite fails 

### ISSUE THREAD

**Issue by corpse82** [dimitri/pgloader#1021]
Hi Dimitri,
I tried converting an sqlite database using this command below.

```
 ./pgloader --debug --verbose  /home/db.db postgresql:///data with data only
```
and got error:
```
pgloader version 3.6.1
compiled with SBCL 1.4.0-1.el7
sb-impl::*default-external-format* :UTF-8
tmpdir: #P"/tmp/pgloader/"
KABOOM!
2019-09-07T14:47:41.009000+03:00 NOTICE Starting pgloader, log system is ready.
FATAL error: :UTF-8 stream decoding error on #<SB-SYS:FD-STREAM for "file /home/db.db" {10056B30E3}>: the octet sequence #(154) cannot be decoded.
Date/time: 2019-09-07-14:47!
An unhandled error condition has been signalled: :UTF-8 stream decoding error on #<SB-SYS:FD-STREAM for "file /home/db.db" {10056B30E3}>: the octet sequence #(154) cannot be decoded.
```

But, I tried converting an sqlite database not using "with data only", not errors.

**Comment by dimitri** [comment]
I think your file is not encoded in UTF-8. You can use `file` to discover the encoding for you, if you don't know it. Other than that, the command line you pasted here is not supposed to be working, so I'm not sure what to tell you.

Please re-open this issue with more information if you still need help.
