### ISSUE TITLE
Copying data from One MySQL Table to Multiple Tables in PostGres

### ISSUE THREAD

**Issue by BegoneRaven** [dimitri/pgloader#1024]
- [ ] pgloader --version
  
    ```
    "3.6.2~devel"
    ```
This is more of a "how to" question than an issue. :)
Source DB = MySQL
Destination DB = Postgres

Lets assume that in MySQL we have a badly designed Users table is as follows:

Users
-----
user_name : varchar (PK)
user_details_a: varchar
user_details_b: varchar
user_details_c: varchar

In Postgres, the database is pre-designed as follows with the User's table split into two tables.

Users
------
user_id      : integer(PK)
user_name : varchar 

UserDetails
-----------
user_id      : integer(PK)
user_details_a: varchar
user_details_b: varchar
user_details_c: varchar

I was wondering what can I write in the load file, so that the data from  **one** table in MySQL gets split & goes to **two** tables in postgres, that too with user_ids autogenerated in the Users table & the corresponding one, being referred correctly in the UserDetails table also.

As of now, I am doing it in two steps
1)
I am manually running some sql commands in MySQL to create an equivalent of the postgres Users table in the MySQL DB, so that the user_id gets autogenerated (incrementing number)
Now I run pgloader to copy from the temporary Users table from MysQL to the Users table in Postgres
2) 
To fill the UserDetails table, I use Materialized views option of pgloader.
I am creating a view that joins the temporary MySQL Users table that I created earlier with the original badly designed MySQL Users table, so that it looks just like the UserDetails table in postgres. Pgloader then copies it.

I am relatively new to databases & just wondering if there could be a better approach to solve this problem.

**Comment by dimitri** [comment]
Using the Materalized Views clause of pgloader is the right approach here.
