### ISSUE TITLE
AsText() removed from MySQL 8.x

### ISSUE THREAD

**Issue by crabel99** [dimitri/pgloader#1029]
- [ ] pgloader --version
  
    ```
    <3.6.1>
    ```
  
  - [ ] did you test a fresh compile from the source tree?
    YES

    Compiling pgloader from sources is documented in the
    [README](https://github.com/dimitri/pgloader#build-from-sources), it's
    easy to do, and if patches are to be made to fix your bug, you're going
    to have to build from sources to get the fix anyway…
    
  - [ ] did you search for other similar issues?
    YES
  - [ ] how can I reproduce the bug?
Install MYSQL and try and import a geometry indexed table (where the native wkb is converted to text)

The function AsText() was deprecated in versions of MySQL <8.0 (e.g. 5.7) and is now fully removed in 8.0+ it has been replaced by ST_AsText() having the same input and output structure.

**Comment by dimitri** [comment]
From which version of MySQL is the `ST_AsText()` function available? Can you send a pull request to fix this issue? have a look at https://github.com/dimitri/pgloader/blob/master/src/sources/mysql/mysql-schema.lisp#L196 which is where to change the code.
