### ISSUE TITLE
junk data displayed post migration 

### ISSUE THREAD

**Issue by soujith** [dimitri/pgloader#1032]
Hi ,

i have successfully migrated from mysql to postgres. but one of the table displays junk data.

```
9 | \x726e646d64633430332d6a6f622e323031392d30312d31305f32312e30302e30305f3138       | \x726e646d64633430332d6a6f62       | \x42 | \x49
```

can you help

**Comment by soujith** [comment]
Below is the table descrption from postgres & mysql.

Postgres:
    Column      |           Type           |                      Modifiers                      | Storage  | Stats target | Description
-----------------+--------------------------+-----------------------------------------------------+----------+--------------+-------------
 jobid           | bigint                   | not null default nextval('job_jobid_seq'::regclass) | plain    |              |
 job             | bytea                    | not null                                            | extended |              |
 name            | bytea                    | not null                                            | extended |              |
 type            | bytea                    | not null                                            | extended |              |
 level           | bytea                    | not null                                            | extended |              |
 clientid        | bigint                   | default 0::bigint                                   | plain    |              |
 jobstatus       | bytea                    | not null                                            | extended |              |
 schedtime       | timestamp with time zone |                                                     | plain    |              |
 starttime       | timestamp with time zone |                                                     | plain    |              |

mysql: 

-----------------+---------------------+------+-----+---------+----------------+
| Field           | Type                | Null | Key | Default | Extra          |
+-----------------+---------------------+------+-----+---------+----------------+
| JobId           | int(10) unsigned    | NO   | PRI | NULL    | auto_increment |
| Job             | tinyblob            | NO   |     | NULL    |                |
| Name            | tinyblob            | NO   | MUL | NULL    |                |
| Type            | binary(1)           | NO   |     | NULL    |                |
| Level           | binary(1)           | NO   |     | NULL    |                |
| ClientId        | int(11)             | YES  |     | 0       |                |
| JobStatus       | binary(1)           | NO   |     | NULL    |                |
| SchedTime       | datetime            | YES  |     | NULL    |                |
| StartTime       | datetime            | YES  |     | NULL    |                |

**Comment by soujith** [comment]
Job, name, type, level, clientid, jobstatus are the columns which have this data.

**Comment by dimitri** [comment]
If job status is not `bytea` (binary blob) then you need to use a CAST expression to target the proper data type in Postgres. Seeing that it's a `binary(1)` I suppose you want a boolean, and here's the CAST rule to use, I think. See https://pgloader.readthedocs.io/en/latest/ref/mysql.html#default-mysql-casting-rules.

```
 cast column table name.jobstatus to boolean drop typemod using bits-to-boolean
```
