### ISSUE TITLE
sqlite to postgresql

### ISSUE THREAD

**Issue by karippery** [dimitri/pgloader#1040]
my task is migrate sqlite db to postgresql and i have problem using pgloader.
when i using Pgloader for migration **pgloader delete all my sequences** in database structure 

**step to do for migration**  

>first i created a copy of backupdb.sqlite
>second I created a empty database in pgsql 
>then I edit database.yml file (see below)
>then I use **rake db:migrate** and **rake db:setup** (until here everything is fine I got exact same datastucture from sqlite  55 tables and 55 sequences )
>on the next step I use pgloader for import data to postgresql database 
there is no error all data in imported **but there is no sequences in my database**.

because of this problem i can't open my application 

could you please explain why data structure is change after i use pgloader

**Comment by dimitri** [comment]
If you want someone to help you, you need to provide concrete information. Your pgloader load file, a sample sqlite database file, a Postgres dump of the target schema before migration, and the full logs of the operation when you run pgloader.

Closing the issue for triaging purposes, please re-open with more information if you still need help here.

**Comment by karippery** [comment]
i found solution for this issue..
it because of  rake migrate is using different datatype. (bigint - integer) 

**Solution** 

drop your database you were create 

```
SELECT pg_terminate_backend (pg_stat_activity.pid) FROM pg_stat_activity WHERE pg_stat_activity.datname = 'database_name';
drop database database_name;
```
create database using "rake"

`rake db:create`

install gem "sequel" 

`gem install sequel`

create data structure using  sequel

`sequel -C sqlite:/tmp/backupdb.sqlite3 postgres://database_user:"password"@localhost/database_name`

after successful now you can use pgloader. this will take a while. 

` pgloader --with "data only"  /tmp/backupdb.sqlite3  postgresql://postgres:"Password"@localhost/database_name`

last step you want to restart your apache service

`service apache2 restart `

I hope this will help you all. 
thank you
