### ISSUE TITLE
fatal error encountered in SBCL pid 13644(tid 0x7ffff5187700)

### ISSUE THREAD

**Issue by Danielss89** [dimitri/pgloader#1045]
I'm getting this error.
Gen  Boxed Unboxed   LgBox LgUnbox  Pin       Alloc     Waste        Trig      WP GCs Mem-age
fatal error encountered in SBCL pid 13644(tid 0x7ffff5187700):
GC invariant lost, file "gencgc.c", line 461

I've compiled from source on ubuntu using: make DYNSIZE=8192 pgloader

i'm running this command: ./build/bin/pgloader -vd -D ~ mysql://pgsql:foo@host/dbname postgresql:///dbname

**Comment by phoe** [comment]
Which SBCL version are you using? Does the issue still persist at SBCL 2.0.2 (current)?

(Please use https://github.com/dimitri/pgloader/tree/bug-1090 for building pgloader until #1090 is resolved.)

**Comment by hekep** [comment]
Gen  Boxed Unboxed   LgBox LgUnbox  Pin       Alloc     Waste        Trig      WP GCs Mem-age
fatal error encountered in SBCL pid 31037(tid 0x7ff934b3f700):
GC invariant lost, file "gencgc.c", line 474
