### ISSUE TITLE
pgloader Triggers and functions migrations

### ISSUE THREAD

**Issue by Fastersush** [dimitri/pgloader#1050]
Please provide the following information:

  - [x] pgloader --version
   pgloader version "3.6.1"

  - [x] did you test a fresh compile from the source tree?
    
    Compiling pgloader from sources is documented in the
    [README](https://github.com/dimitri/pgloader#build-from-sources), it's
    easy to do, and if patches are to be made to fix your bug, you're going
    to have to build from sources to get the fix anyway…
    
  - [ ] did you search for other similar issues?
    Yes
  - [ ] how can I reproduce the bug?
   you can try to migrate a DB from mysql to postgres having triggers and functions created in mysql db
  
--
-- EDIT THIS FILE TO MATCH YOUR BUG REPORT
--

LOAD CSV
LOAD DATABASE
     FROM    mysql://username:passwd@<host>/<dbname>
     INTO postgresql://username:passwd@<host>/<dbname1>

 WITH include drop, create tables

ALTER SCHEMA '<dbname>' RENAME TO 'public'

**Comment by dimitri** [comment]
Please provide enough information so that it's possible to reproduce the issue you are seeing. A minimal MySQL schema definition would be good, for example.
