### ISSUE TITLE
Migrating a mysql DB to a postgres DB that contains an hyphen in the name causes error. (ERROR PostgreSQL Database error 42601: syntax error at or near "-")

### ISSUE THREAD

**Issue by sobiodarlington** [dimitri/pgloader#1061]
Migrating a mysql DB to a postgres DB that contains an hyphen in the name causes error.

**Pgloader version:**
```
pgloader version "3.6.1"
compiled with SBCL 1.3.1.debian
```

**Command:**
Notice the hyphen in the postgres dbname
```
pgloader -v mysql://user:pass@localhost/mysql-db pgsql://user:pass@remote-db/postgres-db

```
  
The DBname in the ALTER query below is not **quoted** which causes the error.
This only happens when migrating to a **hyphenated** postgres database.

**Error:**
```
2019-12-17T07:29:00.524000+01:00 NOTICE ALTER DATABASE postgres-db SET search_path TO public, "postgres-db";
2019-12-17T07:29:00.525000+01:00 ERROR PostgreSQL Database error 42601: syntax error at or near "-"
```

**Comment by dimitri** [comment]
The current code at https://github.com/dimitri/pgloader/blob/master/src/pgsql/pgsql-create-schema.lisp#L98 is using the template ~s for the database name, which implies double-quoting. Please build from sources and check: your bug should be fixed.

```
                         "ALTER DATABASE ~s SET search_path TO ~{~a~^, ~};"
```
