### ISSUE TITLE
Binary Stream conversion from MSSQL to Postgresql

### ISSUE THREAD

**Issue by sagarkolli** [dimitri/pgloader#1064]
I am able to migrate DB from MSSQL to Postgresql but i see below issue after migration. I tried migrating with below command. My Source DB contains blobs. Can you suggest me a solution here.

pgloader --type mssql --encoding UTF-8 --with "prefetch rows=1000" --debug mssql://username:password@sourceserver/db postgresql://username:password@targetserver/db

Truncated binary stream encountered; expected decompressed size of 29851, but actually got 8436

**Comment by dimitri** [comment]
I need more information to be able to help you, or a test case I can connect to and reproduce the error.
