### ISSUE TITLE
FATAL: Failed to start the monitor thread.  error in FORMAT: No more arguments

### ISSUE THREAD

**Issue by iwarford** [dimitri/pgloader#1067]
## Error

This error is happening intermittently while loading:

```
FATAL: Failed to start the monitor thread.

error in FORMAT: No more arguments
  send-batch[~a] ~a ~d row~:p [~a] in ~6$s~@[ [oversized]~]
                  ^
while processing indirect format string:
  ~{~}
   ^
```

## Requested Details

  - [ ] pgloader --version
  
    ```
    pgloader --version
    pgloader version "3.6.1"
    compiled with SBCL 1.4.12
    ```
  
  - [ ] did you test a fresh compile from the source tree?
    
    I used the most recent 3.6.1 release, as HEAD was not building.
    
    Furthermore, it had the SQL patch discussed here, as we are
    running against PG12, and 3.6.1 does not work correctly against
    PG12: https://github.com/dimitri/pgloader/issues/1034
    
    Furtherfurthermore, it was built on an updated SBCL, as the one
    configured in the centos 6 script does not build it, see:
    https://github.com/dimitri/pgloader/issues/834
        
  - [ ] did you search for other similar issues?
    
    Yes, I only found one reference to this error message at :
    https://github.com/dimitri/pgloader/issues/602 which was not
    illuminating.
    
  - [ ] how can I reproduce the bug?

    I can't, it's intermettent.  Attached is the control file that
    causes it, which is fed by a process from STDIN, however it
    doesn't happen every time.  It only appears to happen certain
    times, and it appears related to logging the send-batch command. 

  - [ ] pgloader output you obtain
  
    Both the control file and the output file are attached, although
    they are not very illuminating.

[pgloader-output-log.txt](https://github.com/dimitri/pgloader/files/4017716/pgloader-output-log.txt)
[pgloader-control-file-failed.txt](https://github.com/dimitri/pgloader/files/4017717/pgloader-control-file-failed.txt)

## Workaround

Currently I have worked around this by commenting out the statement
that logs information about the call to send-batch, as the error
message is about a format string failure there, and that appears to
have been causing the issue.  Whether it's the root issue or a
symptom, I don't know, however this fixes it for us for the time
being:

```
*** orig/pgloader-3.6.1/src/pg-copy/copy-rows-in-batch.lisp     2019-01-21 14:02:39.000000000 +0000
--- pgloader-3.6.1/src/pg-copy/copy-rows-in-batch.lisp  2020-01-02 20:48:51.252478571 +0000
***************
*** 97,110 ****
      ;; now log about having send a batch, and update our stats with the
      ;; time that took
      (let ((seconds (elapsed-time-since batch-start-time)))
!       (log-message :debug
!                    "send-batch[~a] ~a ~d row~:p [~a] in ~6$s~@[ [oversized]~]"
!                    (lp:kernel-worker-index)
!                    (format-table-name table)
!                    (batch-count batch)
!                    (pretty-print-bytes (batch-bytes batch))
!                    seconds
!                    (batch-oversized-p batch))
        (update-stats :data table
                      :rows (batch-count batch)
                      :bytes (batch-bytes batch))
--- 97,110 ----
      ;; now log about having send a batch, and update our stats with the
      ;; time that took
      (let ((seconds (elapsed-time-since batch-start-time)))
! ;;      (log-message :debug
! ;;                   "send-batch[~a] ~a ~d row~:p [~a] in ~6$s~@[ [oversized]~]"
! ;;                   (lp:kernel-worker-index)
! ;;                   (format-table-name table)
! ;;                   (batch-count batch)
! ;;                   (pretty-print-bytes (batch-bytes batch))
! ;;                   seconds
! ;;                   (batch-oversized-p batch))
        (update-stats :data table
                      :rows (batch-count batch)
                      :bytes (batch-bytes batch))
```

Obviously this isn't a long-term solution, however we need this
working, so this makes it work for us.

**Comment by dimitri** [comment]
It's hard for me to form a theory on why that would happen. I was thinking that maybe if we receive this message too soon in the start of the monitor thread, before it's ready, that could explain; but now that seems far fetched at best.

Closing for issue triaging. Please open again with more information if you can have them. You can continue with your patch meanwhile, there's no impact from it other than reduced ability to debug some advanced cases.

**Comment by dataf3l** [comment]
I'm having the same issue:
2020-05-22T03:27:59.691000Z DEBUG start jobs2_beta2.job          631

debugger invoked on a SB-FORMAT:FORMAT-ERROR in thread
#<THREAD "lparallel" RUNNING {10090D5ED3}>:
  error in FORMAT: no more arguments
  copy-batch[~a] ~a ~d row~:p [~a] in ~6$s~@[ [oversized]~]
                  ^
while processing indirect format string:
  ~{~}
   ^

**Comment by bamboomy** [comment]
I had the same issue with the vanilla pgloader from ubuntu.

(this error showed up and pgloader continued to:
- process data (the target db kept growing)
- spawn processes (top showed pgloader and postgress processes (some with high cpu)))

...but in the end no significant process was running and the target db didn't grew anymore
(pgloader didn't return either).

Building pgloader from sources solved the issue.

@dimitri: man, you are a hero!!!
I cannot imagine what it takes to cramp the complexity of migrating db's into a single command line statement...
I've seen loads of bug reports (which is normal with a task as complex as this)
and I cannot imagine the time and effort you've put into getting this right!!!
kudo's²²²

Keep doing magic!!!
