### ISSUE TITLE
MS SQL - tinyint interpreted as signed?

### ISSUE THREAD

**Issue by wwwald** [dimitri/pgloader#1072]
I'm migrating an MS SQL Server database to Postgres, using Pgloader 3.6.1, compiled SBCL 1.4.16.debian. Actually, i'm using the slightly modified "3.6.1.1" version available in @Bonn93's fork, [available here](https://github.com/Bonn93/pgloader), because of issue #1068.
I built the Docker image and am using that to perform the conversion.

Now, I have a few tables with a `tinyint` type field as the primary key (IDENTITY type column). `tinyint` is a 2-byte integer ranging from 0 to 255. After data migration, the column in PostgreSQL (type `smallint`) shows the values correctly up to 127 and then resumes at -128 to -1.

So it seems that the unsigned integer of MS SQL gets read as a signed 2-byte integer, resulting in the integer overflow.

Is there a way to circumvent this or fix this?

**Comment by dimitri** [comment]
Closing because fixed in #1068 by using FreeTDS protocol version 8.0. Consider opening again if you still need help.
