### ISSUE TITLE
Better aproach to rename columns ?

### ISSUE THREAD

**Issue by titoshadow** [dimitri/pgloader#1076]
- [ ] pgloader --version
  (Installed from yum at CentOS 7.7.1908)
    
```
pgloader -V
pgloader version "3.6.1"
compiled with SBCL 1.4.0-1.el7
```
    
  - [ ] did you search for other similar issues?

```
Yes, with no luck :( apologies in advance if its an issue treated before.
```

  - [ ] pgloader output you obtain
  
```
The output is perfect, with the exception that I don't know the better approach on how to rename 'index' MySQL columns to my 'id' name convention (primary keys columns)
```

**Comment by dimitri** [comment]
Renaming columns is not supported directly, you could use a AFTER LOAD clause to change them using SQL commands in the resulting Postgres database.
