### ISSUE TITLE
Symbol "*IXF-STREAM*" not found in the IXF package

### ISSUE THREAD

**Issue by mark-ellul** [dimitri/pgloader#1078]
ENVIRONMENT SETUP
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

sbcl --version
SBCL 1.3.21

I have tried sbcl versions....
sbcl-1.3.3-x86-64-linux 
sbcl-1.4.14-x86-64-linux
sbcl-1.4.16-x86-64-linux
sbcl-2.0.1-x86-64-linux

I am having issues building pgloader from source.

The error that is logged below for every version....

Symbol "*IXF-STREAM*" not found in the IXF package.
;   
;       Line: 61, Column: 25, File-Position: 2071
;   
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/infrastructure/pgloader/src/sources/ixf/ixf-schema.lisp" {10019D68E3}>

I have tried updating the local-projects as per the following comment
https://github.com/dimitri/pgloader/issues/296#issuecomment-141161910

I tried the bootstrap-debian.sh 

And I always keep on hitting the same error

**Comment by dimitri** [comment]
Please try to `make clean` then build again. I think you have a very old version of the cl-ixf sources around, possibly you can `git pull` in the `build/quicklisp/local-projects` directory, or just build from scratch again.
