### ISSUE TITLE
pgLoader  lowercase column name when I try to convert mysql to psql

### ISSUE THREAD

**Issue by Hoangpnse62077** [dimitri/pgloader#1079]
This is my script:
LOAD DATABASE
     FROM      mysql://root:root@127.0.0.1/wallet
     INTO pgsql://bstar:bstar@127.0.0.1/wallet

 WITH include drop, create tables

ALTER SCHEMA 'wallet' RENAME TO 'public'
;

Everything worked well except column name changed to lowercase format instead of orginal.
Please help me to force keeping orginal column name

**Comment by Khd007** [comment]
That's the default behaviour of pgloader converts all table names and field names to lowercase. But if you want to retain the case you need to add `quote identifiers` in line 
```WITH include drop, create tables, quote identifiers```
Access quoted fields e.g;
```psql> select "$quoted_field" from $table```
