### ISSUE TITLE
Pgloader compatibility with Postgres 12

### ISSUE THREAD

**Issue by Shubhamgarg25** [dimitri/pgloader#1080]
While Loading csv to PostgreSQL 12.1 through Pgloader , Received error def.adsrc is not column which is already deprecated in PostgreSQL latest release.

when we can have compatibility of Pgloader with latest PostgreSQL 12 ?

**Comment by dimitri** [comment]
Fixed in https://github.com/dimitri/pgloader/commit/8a13c02561fe030301045f9f50d94f523dd61b2c.
