### ISSUE TITLE
No data imported , No errors

### ISSUE THREAD

**Issue by ravindra9278** [dimitri/pgloader#1086]
`ubuntu@ip-123-31-13-119:/applications$ pgloader pgload.load`

pgloader Response:
```
2020-02-22T06:28:27.676000Z LOG report summary reset
             table name       read   imported     errors      total time
-----------------------  ---------  ---------  ---------  --------------
            before load          3          3          0          0.015s
        fetch meta data          0          0          0          0.287s
         Create Schemas          0          0          0          0.006s
       Create SQL Types          0          0          0          0.008s
          Create tables          0          0          0          0.000s
         Set Table OIDs          0          0          0          0.000s
-----------------------  ---------  ---------  ---------  --------------
-----------------------  ---------  ---------  ---------  --------------
COPY Threads Completion          8          8          0          0.000s
 Index Build Completion          0          0          0          0.000s
        Reset Sequences          0          0          0          0.030s
           Primary Keys          0          0          0          0.000s
    Create Foreign Keys          0          0          0          0.000s
        Create Triggers          0          0          0          0.001s
       Install Comments          0          0          0          0.000s

```
When I checked into the database it's showing nothing
```
MD247_development=# select * from users;
ERROR:  relation "users" does not exist
LINE 1: select * from users;
                      ^
MD247_development=#
```

Here is the LOAD file:
```
LOAD DATABASE
     FROM mysql://ubuntu:secure@localhost/MD247_development
     INTO postgresql://ubuntu:secure2020@localhost/MD247_development

 WITH include drop, create tables, create indexes, reset sequences,
      workers = 8, concurrency = 1,
      multiple readers per thread, rows per range = 50000,
      prefetch rows = 10000

  SET PostgreSQL PARAMETERS
      maintenance_work_mem to '1024MB',
      work_mem to '1024',
      search_path to 'md247_development, public, "$user"'

  SET MySQL PARAMETERS
      net_read_timeout  = '220',
      net_write_timeout = '220'
  
  including only table names matching 'users,user_requests,search_queries,addresses'
  
  ALTER SCHEMA 'md247_development' RENAME TO 'pagila'

  BEFORE LOAD DO
   $$ create schema if not exists pagila; $$,
   $$ create schema if not exists mv;     $$,
   $$ alter database MD247_development set search_path to pagila, mv, public; $$;
```

I am not sure where is the issue.

**Comment by digitalronin** [comment]
I'm seeing this behaviour, migrating a rails database from mysql to postgres.

In my case, the data migration works if I run the pgloader command targeting a completely new postgres database. i.e. just create the database, but don't create any of the tables.

When I do that, I get my mysql data loaded in postgres.

**Comment by dimitri** [comment]
In both cases we will need the output in `--verbose` or even `--debug` mode to have enough information about what's happening. At the moment this issue is content free, there's nothing that we can use to help you guys.

**Comment by digitalronin** [comment]
Here is a minimal reproduction of this bug, along with the `--debug` output for both cases (i.e. one where data is transferred, and one where it isn't).

https://gist.github.com/digitalronin/a24f7dcd27921eb73b49ff774845217a

**Comment by dimitri** [comment]
Thanks for the detailed test-case! Your data is loaded in the target table `pgloader_test.sample`, and your Postgres query is `SELECT * FROM sample` which relies on the `search_path` to be positioned correctly. In both cases I see `ALTER DATABASE "pgloader_test" SET search_path TO public, pgloader_test;` but is it possible that there's still a problem with the search_path? Can you query explicitly `SELECT * FROM pgloader_test.sample` in both instances?

**Comment by digitalronin** [comment]
Ah, right. When I do that, I see that the data has been migrated, in both cases.

So, if I create the sample table before running pgloader, then for some reason the select statement executes against the wrong schema? (I'm not so familiar with all the postgres data entities)

Is that expected behaviour? I'm not sure I understand whether there is a bug here or not!

**Comment by dimitri** [comment]
So the Postgres `search_path` acts a lot like the shell environment variable PATH on Unix (or Windows). Which means that if you have the same table name in both the `public` and `pgloader_test` schemas, and `public` is first in the `search_path`, then `SELECT * FROM sample` applies to the table in the `public` schema. By the way you can write this last query `TABLE sample`.

See https://www.postgresql.org/docs/current/ddl-schemas.html#DDL-SCHEMAS-PATH for more information about the `search_path`.

In pgloader you can also target the public schema if that's what you prefer, by adding an `ALTER SCHEMA pgloader_test RENAME TO public` clause to your load file.
