### ISSUE TITLE
Append new rows to an existing table without erase older rows

### ISSUE THREAD

**Issue by eurekastein** [dimitri/pgloader#1096]
I'm trying to do append new data to an older version. But when i do it woth pgloader it drop the original data and add the new. How can i add new rows instead of replacing it?

**Comment by meglio** [comment]
This would be useful for my case as well - i.e. to let pgload function in the "ala-append" mode.

**Comment by jasonab** [comment]
I was considering going this route for my migration, and was planning on creating views with a LIMIT query, and telling pgloader to not truncate the table or change the schema. I didn't end up trying this workaround, but it seems like it could work in certain circumstances.

**Comment by dimitri** [comment]
I think you just have to tell pgloader not to truncate the table, either omitting the `truncate` option or using the `no truncate` option.

**Comment by david-bouyssie** [comment]
In this context, is pgloader able to retrieve generated IDs from the Pg sequence and update foreign keys of external data?
