### ISSUE TITLE
data corruption in zero-dates-to-null

### ISSUE THREAD

**Issue by t-8ch** [dimitri/pgloader#1098]
Background:

After migrating data from mysql to postgres with pgloader 3.6.1 we noticed missing data in the target DB.
It turned out that the default transform for mysql datetime fields `zero-dates-to-null` incorrectly recognized the values as being "0000-00-00" and transformed them to "NULL".

Reproduction case:

```lisp
;; lifted from pgloader, looks the same on 3.6.1 and current master
(defun zero-dates-to-null (date-string)
  "MySQL accepts '0000-00-00' as a date, we want NIL (SQL NULL) instead."
  (cond
    ((null date-string) nil)
    ((string= date-string "") nil)
    ;; day is 00
    ((string= date-string "0000-00-00" :start1 8 :end1 10 :start2 8 ) nil)
    ;; month is 00
    ((string= date-string "0000-00-00" :start1 5 :end1 7 :start2 5 :end2 7) nil)
    ;; year is 0000
    ((string= date-string "0000-00-00" :start1 0 :end1 3 :start2 0 :end2 3) nil)
    (t date-string)))

(print "these should be nil")
(print (zero-dates-to-null ""))
(print (zero-dates-to-null "0000-00-00 00:00:00"))

(print "these should *NOT* be nil")
;; real-world-example
(print (zero-dates-to-null "0009-12-04 00:00:00"))

;; synthetic test cases
(print (zero-dates-to-null "0011-00-00 00:00:00"))
(print (zero-dates-to-null "0001-00-00 00:00:00"))
(print (zero-dates-to-null "0000-01-00 00:00:00"))
(print (zero-dates-to-null "0000-00-01 00:00:00"))
(print (zero-dates-to-null "0000-00-00 01:00:00"))
(print (zero-dates-to-null "0000-00-00 00:01:00"))
(print (zero-dates-to-null "0000-00-00 00:00:01"))
(print (zero-dates-to-null "0001-01-01 01:01:01"))
(print (zero-dates-to-null "0011-01-01 01:01:01"))
```

I think there are multiple bugs in this function:
* It completely ignores the time portion of datetime values
* It looks at each value group in separation. Effectively using a "logical or" instead of a "logical and"
* The end indizes in `string=` are used as if they are inclusive, while at least my sbcl implements them as exclusive ones. This leads to the last digit of each group not being compared, which triggered the real world example in the testcase above.

**Comment by t-8ch** [comment]
This seems to work better:
```lisp
(defun zero-dates-to-null (date-string)
  "MySQL accepts '0000-00-00' as a date, we want NIL (SQL NULL) instead."
  (if (string= date-string "0000-00-00 00:00:00" :end2 (length date-string)) nil date-string))
```
(I am not a lisp programmer, though)

**Comment by dimitri** [comment]
Hi @t-8ch ; thanks for opening an issue here and taking some time to read and understand the lisp code. The idea is that Postgres will (rightfully) refuse a date where only the day is zero, or only the month is zero, or only the year is zero, or any combination thereof, because none of those exist in our calendar system.

What happens is that I got the bounds check wrong in the code, it's now fixed in the mentioned patch.

**Comment by t-8ch** [comment]
Hi @dimitri , thanks for fixing it!
Wouldn't it still be better to pass through irrepresentable values (that are not exactly `0000-00-00`) to postgres so the users see the error and can write their own transformation (or fix it in the source DB) function instead of silently dropping the value?

**Comment by dimitri** [comment]
You can try that already by adding your own user-defined casting rule to your load command. You will see lots of errors in the migration, and none of the erroneous data in your target PostgreSQL database.
