### ISSUE TITLE
Lisp expressions to access the other column values of the row being transformed

### ISSUE THREAD

**Issue by meglio** [dimitri/pgloader#1104]
In lisp functions, is there any way to get the `row context`, so that I can "read" the values from the other row columns and use them in calculations?

Example usage:

```lisp
(in-package :pgloader.transforms)

(defun my-func (value, row)
  (empty-string-to-null (right-trim value)))
```

And then:

`using my-func(row)`

Possibly make a few aliases available to pass in:

- row.before_transformations
- row.after_transformations

... or just accept any column values, so that we can call like this:

`using my-func(col1, col2)`

... where col1, col2 is any column name of the current row, possibly the target row being transformed.

Would any of these work, or is this just an unneeded complication?

**Comment by dimitri** [comment]
You can already pass more than one argument to the processing function, and pass in as many columns as you need. See the example in the tests at https://github.com/dimitri/pgloader/blob/master/test/archive.load#L39 for a use case doing exactly that, using two columns as the input for the transformation function.

With respect to parsing rows it's more complex that it looks: before parsing we don't know that a physical line is going to be a whole row, to begin with...
