### ISSUE TITLE
Sqlite -> postgres don't have Options for changing Downcase identifiers?

### ISSUE THREAD

**Issue by ev0A** [dimitri/pgloader#1105]
I want to Migrating a SQLite database to PostgreSQL, but my app is Case sensitive,  
In my original Sqlite file table and column contain uppercase and downcase char，so i want pgloader don not converts table names and field names to lowercase.

In document and other issue, i know i need to add " --with quote identifiers" , but it's seem only useful for mysql -> postgres. and sqlite -> postgres don't have this options

Did I make a mistake？ Is there any other way？
![image](https://user-images.githubusercontent.com/48745108/77095460-e3c8d200-6a48-11ea-9bb0-dee13e4abea3.png)

**Comment by dimitri** [comment]
I can't reproduce. Works for me with the following example:

```
$ pgloader --with "quote identifiers" ./test/sqlite/storage.sqlite pgsql:///pgloader
```

Please re-open this issue with more information if you still need help.
