### ISSUE TITLE
Cleanup pgloader.lisp

### ISSUE THREAD

**Issue by phoe** [dimitri/pgloader#1115]
**EDIT**: @dimitri suggested that we should remove this file altogether, since it is not used nowadays.

---------

https://github.com/dimitri/pgloader/blob/bab6aaf8905f2c8f96bab50896f25ec16d2a6892/pgloader.lisp#L18-L19

`WITH-OUTPUT-TO-STRING` unnecessarily buffers all of the Quicklisp output into a string before ultimately discarding it.

Replace with `(with-open-stream (*standard-output* (make-broadcast-stream)) ...)`

**Comment by dimitri** [comment]
Maybe we could also dispose of this file. It was meant to be used as a “script” at times when building the binary image was complex. I think it is now easy enough to build pgloader and we should just get rid of this old approach, which might not even work at all anymore.

**Comment by phoe** [comment]
So it's dead code, too. OK - I'll modify the issue.

**Comment by df7cb** [comment]
Fwiw, the file was indeed covered by the Debian package regression tests, and cl-pgloader was a whole .deb of its own.
I'll rip out these parts.
