### ISSUE TITLE
Update pgloader.spec for release 3.6.2

### ISSUE THREAD

**Issue by phoe** [dimitri/pgloader#1116]
https://github.com/dimitri/pgloader/blob/bab6aaf8905f2c8f96bab50896f25ec16d2a6892/pgloader.spec#L51-L53

I have no idea what the spec file is, but it seems to need an update for the most recent 3.6.2 release.

**Comment by dimitri** [comment]
The spec file allows to build an RPM for pgloader. The main RPM distribution for pgloader though is maintained by @devrimgunduz on the https://yum.postgresql.org repositories. This file here is meant as a service for people who want to build an RPM from sources themselves, or maybe pre-dates the PGDG inclusion?

Anyway, would be good to update too I guess.
