### ISSUE TITLE
setting default schema from public to another

### ISSUE THREAD

**Issue by xdat** [dimitri/pgloader#1121]
hi.
load database
        from mysql://localhost/beyaz
        into postgresql://user@passdowd/beyaz;

with this. it transfers the data from mysqls:beyaz int to public schema of database beyaz of postgresql.

is thre any way to change the defualt schema public to another.?

**Comment by phoe** [comment]
https://github.com/dimitri/pgloader/issues/645 has a solution at the end:

```
load database
   from mysql://user@host/dbname
   into pgsql://user@host/dbname
   alter schema 'dbname' rename to 'public';
```

Does that work for you?

**Comment by xdat** [comment]
i'm getting this..

An unhandled error condition has been signalled: At

  	from mysql://localhost/beyaz
  	into postgresql://user@10.0.1.45/beyaz
  
                                         ^ (Line 3, Column 39, Position 83)

In context COMMAND:

While parsing COMMAND. Expected:

     the character Tab
  or the character Newline
  or the character Space
  or the string "--"
  or the string "/*"
  or the character ; (SEMICOLON)
  or the string "after"
  or the string "before"
  or the string "cast"
  or the string "decoding"
  or the string "excluding"
  or the string "including"
  or the string "materialize"
  or the string "set"
  or the string "with"

; 
; compilation unit aborted
;   caught 1 fatal ERROR condition

**Comment by phoe** [comment]
OK, seems like that comment was misleading and that I misunderstood the syntax. Let's try @dimitri's answer from earlier in that post then:

```
load database
   from mysql://user@host/dbname
   into pgsql://user@host/dbname
  with create no schema
  alter schema 'dbname' rename to 'public';
```

**Comment by xdat** [comment]
my load.laod file is :

load database
        from mysql://localhost/beyaz
        into postgresql://user@10.0.1.45/beyaz
        with create no schema
        alter schema 'beyaz' rename to 'public'
;
 and i'm gettin

An unhandled error condition has been signalled: At

  	into postgresql://user@10.0.1.45/beyaz
  	with create no schema
  
                  ^ (Line 4, Column 16, Position 100)

In context MYSQL-OPTION:

While parsing MYSQL-OPTION. Expected:

     the character Tab
  or the character Newline
  or the character Space
  or the string "--"
  or the string "/*"
  or the string "indexes"
  or the string "tables"

; 
; compilation unit aborted
;   caught 1 fatal ERROR condition
root@byztest:~# nano load.load
root@byztest:~# pgloader load.load
An unhandled error condition has been signalled: At

  	into postgresql://user@10.0.1.45/beyaz
  	with create no schema
  
                  ^ (Line 4, Column 16, Position 100)

In context MYSQL-OPTION:

While parsing MYSQL-OPTION. Expected:

     the character Tab
  or the character Newline
  or the character Space
  or the string "--"
  or the string "/*"
  or the string "indexes"
  or the string "tables"

; 
; compilation unit aborted
;   caught 1 fatal ERROR condition

**Comment by phoe** [comment]
OK - I'm stuck. We'll need @dimitri's support on that one.

**Comment by svantevonerichsen6906** [comment]
It seems that there is no option "create no schema" or "create schema" in mysql-option, see parsers/command-mysql.lisp.  Command-mssql does seem to have "create (no) schemas".  Maybe adding the option rule is enough, and core migration functionality will just pick it up, I'm not sure, though.  What I don't understand is why this is a `mysql-option` and not some general migration option.

**Comment by xdat** [comment]
i was installed pgloader with apt-get

and i got 3.2.2 version.

now i pulled the project from here. and build it. its version is 3.6.7b47c00
with load.load 

load database
   from mysql://localhost/beyaz
   into pgsql://kirkbes/beyaz
alter schema 'beyaz rename to 'siyah'
;

it worked

thahks for your interest.

**Comment by dimitri** [comment]
Note that you can invoke the command parser easily enough. This returns the Common Lisp code that has to run to execute the command:

```
(pgloader::parse-commands "load database
   from mysql://user@host/dbname
   into pgsql://user@host/dbname
   alter schema 'dbname' rename to 'public';")
```
