### ISSUE TITLE
Migration from MySQL not working as expected given default casts

### ISSUE THREAD

**Issue by eox-dev** [dimitri/pgloader#1123]
- [x] pgloader --version
  
    ```
    pgloader version "3.6.1"
    compiled with SBCL 1.4.0-1.el7
    ```
I noticed `auto_increments` were not coming over as expected (`SERIAL`) into Postgres. I'm just using the following command to do the migration:
```
./pgloader mysql://<db_user>:'<database_password>'@localhost/<db_name> postgres://<db_user>:'<database_password>'@localhost/<db_name>`
```
I might have `<db_user>` and `<db_name>` reversed, but anyway...
Looking at the field in question in MySQL shows:

![image](https://user-images.githubusercontent.com/59094233/78274231-bb1eee80-74c4-11ea-8a28-98681755f497.png)

But ends up in Postgres as:

![image](https://user-images.githubusercontent.com/59094233/78274277-cffb8200-74c4-11ea-851a-adc52d66533d.png)

Thought it was a bug until I started reading the documentation and the default casts:

```
type int with extra auto_increment to serial when (< precision 10)
type int with extra auto_increment to bigserial when (<= 10 precision)
type int to int       when  (< precision 10)
type int to bigint    when  (>= 10 precision)
```
Based on this, that it came into Postgres as `bigint` makes sense, since it meets the `(>=10 precision)` criteria.

However, looking at this one:
```
type int with extra auto_increment to bigserial when (<= 10 precision)
```
Should it actually be:
```
type int with extra auto_increment to bigserial when (>= 10 precision)
```
It seems like the only criteria for `bigserial` would just be when `int(10)` and anything over that would just come over as `bigint`.

Is my thinking wrong on this?

**Comment by phoe** [comment]
```
type int to int       when  (< precision 10)
type int to bigint    when  (>= 10 precision)
```

IMO that is an obvious bug in the docstring. `(>= 10 precision)` == `(<= precision 10)`, which is partially covered by the `int to int` case.

**Comment by eox-dev** [comment]
I'm seeing now that there is a foreign key constraint on the field in question. Could this prevent it from coming over correctly and is there a way with `pgloader` to have it update foreign key constraints to a new type?

**Comment by eox-dev** [comment]
Ok, more confused now.

I ran the following query in MySQL to find out what tables had `AI` and `int(n)` specified, so I could get rid of the `int(n)` to hopefully clear the issue up:

```
select TABLE_NAME, COLUMN_NAME, DATA_TYPE, NUMERIC_PRECISION, NUMERIC_SCALE, COLUMN_TYPE, EXTRA from information_schema.columns
where table_schema = 'test_db' AND extra LIKE '%increment%'
order by table_name,ordinal_position
```
It returned the following:

![image](https://user-images.githubusercontent.com/59094233/78376661-7a39df00-7583-11ea-95b6-0b224cc5e3bc.png)

- So are the default casts, casts in general, looking at `DATA_TYPE`, `NUMERIC_PRECISION`, and `EXTRA` fields here? 
- Not the `COLUMN_TYPE` like I assumed? 
- The `(n)` in `int(n)`, really `COLUMN_TYPE`, is basically just being ignored?
- So going through and changing the `int(n)` will effectively do nothing to fix my issue?

If that is the case, I don't see any reason why the default casts are not working because these fields fit the criteria to come over as `BIGSERIAL`, but yet they are not.

Any suggestions as to what is going on here?

**Comment by dimitri** [comment]
Hi @eox-dev ; thanks for using pgloader. I have fixed the typo in the documentation.

Now, your screenshot from the Postgres schema lacks information. Please instead paste the table definition statement in SQL, as obtained by pg_dump or the “DDL” view from a graphical tool (such as OmniDB or DBeaver or one of the many others). You can also consider copy-pasting the result of the `\dt users` command in `psql`.
