### ISSUE TITLE
Migrating data fails when the order of fields is not the same in MS SQL and PostgreSQL

### ISSUE THREAD

**Issue by manestream** [dimitri/pgloader#1124]
Hi dimitri,
first of all thanks for this great migration tool.

I am currently trying to migrate from ms sql  to postgres.  i have a fairly simple `pgloader.conf`

```
load database
     from mssql://<user>:<password>@<db>
     into postgres://<user>:<password>@<db>

set mssql parameters textsize to '104857600' <--- needed to transfer large blobs
alter schema 'dbo' rename to 'public'
with data only;
```

I am running into the same issue when the order of columns in source and target table differ that someone had with a mysql source (#132)

```
2020-04-03T08:20:23.498000+01:00 ERROR Database error 22P02: invalid input syntax for type numeric: "FORECAST"
CONTEXT: COPY budget_spend_type_amount, line 1, column amount: "FORECAST"
```

any idea how i can solve this problem? thanks a lot in advance for helping me.

all the best
kai

**Comment by dimitri** [comment]
Hi @manestream ; thanks for opening an issue and using pgloader. In your case we need more information before we can help you. For starters, the schemas of the table in MS SQL and Postgres, and some details about why those schemas are not the same with the same order of columns.

I guess from your bug report that all we have to do is add the following method to `src/sources/mssql/mssql.lisp` like we did in the MySQL support . You could patch the code yourself and then build it and then see if it fixes your problem:

```
(defmethod copy-column-list ((mssql copy-mssql))
  "We are sending the data in the MS SQL columns ordering here."
  (mapcar #'apply-identifier-case (mapcar #'mssql-column-name (fields mssql))))
```

**Comment by manestream** [comment]
Hi @dimitri thanks for the quick reply, i will try your proposed change and will get back to you with the test result

**Comment by dimitri** [comment]
Thanks @manestream for compiling from sources with the change. This change is now part of the main branch and will be in the next release.
