### ISSUE TITLE
Build, and publish versioned / tagged Docker images

### ISSUE THREAD

**Issue by MrSaints** [dimitri/pgloader#1129]
At the time of writing, there doesn't appear to be any versioned  / tagged Docker images apart from `latest` and `ccl.latest`. There was recently a breaking change in `master`, and I was unable to go back to an older version. Thus, I think it would be a good idea to build, and publish versioned / tagged Docker images so that people can pin their use of it. I have attached an image below on how you can potentially configure Docker Hub to work:

<img width="1170" alt="Screenshot 2020-04-07 at 02 01 32" src="https://user-images.githubusercontent.com/68859/78619059-1ad61a80-7874-11ea-8b9c-815d24de078e.png">

Let me know what your thoughts are.

**Comment by dimitri** [comment]
Hi @MrSaints I think it's a good idea to have docker hub build the stable tags, but in an adminitely quick lookup I failed to find where to enable that on my account / project properties...

**Comment by MrSaints** [comment]
Hey @dimitri, I'm assuming you're already using Docker Hub automated builds. If so, you can configure it at:

https://hub.docker.com/repository/docker/dimitri/pgloader/builds/edit

Scroll down to `BUILD RULES`.

**Comment by dimitri** [comment]
Thanks! I think the setup is now ready to build all the git tagged releases!

**Comment by MrSaints** [comment]
Awesome! Thank you so much for this, and everything you've done for this project 🎉
