### ISSUE TITLE
When running command line, how do I force the destination schema to be public?

### ISSUE THREAD

**Issue by atrauzzi** [dimitri/pgloader#1132]
I would like the schema that pgloader pushes my data into to be different from the MySQL database it originates from.

My current command is:

```
pgloader \
    --cast "TYPE DATE TO DATE USING ZERO-DATES-TO-NULL" \
    "mysql://root:zxczxc123@127.0.0.1/my-global" \
    "postgresql://postgres:zxczxc123@127.0.0.1:5432/my-global"
```

I was trying to add something like `--cast "ALTER SCHEMA 'my-global' RENAME TO 'public'" \`, but I'm probably off in the wrong direction. :sweat_smile:

**Comment by dimitri** [comment]
For advanced setup, you need to use the pgloader command mini-language rather than the command line switches.
