### ISSUE TITLE
Postgres truncating identifiers longer than 63 characters, migrating from SQLite to Postgres.

### ISSUE THREAD

**Issue by tanjyeyee** [dimitri/pgloader#1138]
I defined my identifiers to be 8-character, but somehow during migration these identifiers get prefixed and suffixed with extra strings, e.g.:

> 2020-04-29T01:54:35.390000Z WARNING PostgreSQL warning: identifier "idx_21446_blog_postpage_categories_postpage_id_blogcategory_id_43bb5125_uniq" will be truncated to "idx_21446_blog_postpage_categories_postpage_id_blogcategory_id_"

When in actuality only "43bb5125" is the identifier.

How can I prevent this?

**Comment by svantevonerichsen6906** [comment]
That identifier is not for the table itself but for an index on it.  It seems likely that it is a combined index of the columns mentioned in the name.  Such index names are automatically created from the table and column names involved, I guess by SQLite.

You usually do not see these names unless you are investigating deep in the database, and then these long names help in directly seeing which index you are looking at.  Their uniqueness is already ensured by the first part (`idx_21446`).

So, I'd say it is not anything to worry about.  You could rename the indexes prior to migration to prevent the warning.

**Comment by tanjyeyee** [comment]
> So, I'd say it is not anything to worry about. You could rename the indexes prior to migration to prevent the warning.

How can I do that? All I have is the .sqlite3 file.

**Comment by dimitri** [comment]
You can rename the index after it has been created by using Postgres command `ALTER INDEX name RENAME TO new_name` as documented at https://www.postgresql.org/docs/current/sql-alterindex.html.
