### ISSUE TITLE
django.db.utils.IntegrityError: null value in column "id" violates not-null constraint

### ISSUE THREAD

**Issue by tanjyeyee** [dimitri/pgloader#1141]
So I'm migrating from SQLite3 to Postgres. All good.

READ seems to be fine -- all data is transferred over, and fast too (hooray).

The problem comes with WRITE (whenever I create a new data), I get this error:

`django.db.utils.IntegrityError: null value in column "id" violates not-null constraint`

For some reason, the pk/id field is null even though I've programmed it to have a unique 8-character identifier.

How can I fix this?

**Comment by Harleqin** [comment]
It seems to me that this is an error that Django produces.  I can do little but guess: maybe Django has some conventions or configurations regarding the index names?

**Comment by tanjyeyee** [comment]
> It seems to me that this is an error that Django produces. I can do little but guess: maybe Django has some conventions or configurations regarding the index names?

I googled further, seems like it's a version incompatibility issue, meaning it happens when one dumps from Postgres 9.x and tries to restore to Postgres 10.

Is there a way I can install Postgres 9.x on Ubuntu 18.04, or is there a compatibility option in pgloader?

**Comment by dimitri** [comment]
The not null constraint violation should not be linked to the index name truncation. Is it possible that SQLite accepts NULL in a column that is declared NOT NULL, and your application depended on that and now that fails when using Postgres?

**Comment by tanjyeyee** [comment]
> The not null constraint violation should not be linked to the index name truncation. Is it possible that SQLite accepts NULL in a column that is declared NOT NULL, and your application depended on that and now that fails when using Postgres?

Hey Dmitri, not likely as it's an id/pk field that's failing with NOT NULL.
SQLite will never accept a NULL id as it's by definition NOT NULL.

It's the exact same problem this guy was having: https://stackoverflow.com/questions/47744721/integrityerror-null-value-in-column-id-for-all-models-fields-with-foreignkey/47824894/.

The answer points towards the issue of "identity columns" in Postgres 10: https://www.2ndquadrant.com/en/blog/postgresql-10-identity-columns/.

Is there a way I can solve this while still using pgloader?

**Comment by tanjyeyee** [comment]
Nevermind, I solved this issue by using Pgloader 3.4.1 + PostgreSQL 12.

It seems to be the only combination that works.

I don't know why, but 3.5.2 gave me compatibility issues.

Thank you, Dmitri!

**Comment by tanjyeyee** [comment]
> The not null constraint violation should not be linked to the index name truncation. Is it possible that SQLite accepts NULL in a column that is declared NOT NULL, and your application depended on that and now that fails when using Postgres?

https://www.sqlitetutorial.net/sqlite-not-null-constraint/

"_Based on the SQL standard, PRIMARY KEY should always imply NOT NULL. However, SQLite allows NULL values in the PRIMARY KEY column except that a column is INTEGER PRIMARY KEY column or the table is a WITHOUT ROWID table or the column is defined as a NOT NULL column._"

I think you're right, though it beats me that I can't find a solution for it code-wise.

Is it possible to build this into pgloader and account for this?

**Comment by dimitri** [comment]
The classic solution would be to delete the rows where the pk is NULL on SQLite before the migration with pgloader. Another way to do it would be to find values to replace NULL entries, but's that more like inventing things after the fact.
