### ISSUE TITLE
Error migrating Sqlite DB to Postgres with "quote identifiers" option

### ISSUE THREAD

**Issue by pravatk** [dimitri/pgloader#1142]
I am trying to migrate my sqlite db to postgres12 using pgloader. The details are furnished below:

**Pgloader version**
pgloader version "3.6.2"
compiled with SBCL 2.0.4

**Command Executed**
pgloader chinook.db postgresql:///test --with "quote identifiers"

**DB Used**
Sqlite
[chinook.zip](https://github.com/dimitri/pgloader/files/4587476/chinook.zip)

**Error from Console**
```
pgloader chinook.db postgresql:///test --with "quote identifiers"
KABOOM!
FATAL error: :UTF-8 stream decoding error on #<SB-SYS:FD-STREAM for "file /Users/pravat/Downloads/chinook.db" {10050CF4E3}>: the octet sequence #(226 30 5) cannot be decoded.
An unhandled error condition has been signalled: :UTF-8 stream decoding error on #<SB-SYS:FD-STREAM for "file /Users/pravat/Downloads/chinook.db" {10050CF4E3}>: the octet sequence #(226 30 5) cannot be decoded.



2020-05-06T20:11:10.010000+05:30 LOG pgloader version "3.6.2"
2020-05-06T20:11:10.011000+05:30 LOG Data errors in '/private/tmp/pgloader/'
2020-05-06T20:11:10.011000+05:30 LOG Parsing commands from file #P"/Users/pravat/Downloads/chinook.db"

What I am doing here?

:UTF-8 stream decoding error on
#<SB-SYS:FD-STREAM for "file /Users/pravat/Downloads/chinook.db" {10050CF4E3}>:
  the octet sequence #(226 30 5) cannot be decoded.
```
**Additional Information**
When ran `pgloader chinook.db postgresql:///test` the DB was migrated successfully to postgres with all lowercase field names.

Do let me know if you need additional information.

FYI, the attached db is a sample Sqlite DB from the web.

**Comment by phoe** [comment]
Thanks for the ticket.

Please try running pgloader with the `-d` or `--debug` option - a backtrace will be helpful.

**Comment by pravatk** [comment]
After running with -d or --debug I didn't see any difference in the command output. But attaching here for reference.
```
pgloader chinook.db postgresql:///test --with "quote identifiers" --debug
KABOOM!
FATAL error: :UTF-8 stream decoding error on #<SB-SYS:FD-STREAM for "file /Users/pravat/Downloads/chinook.db" {1005066B33}>: the octet sequence #(226 30 5) cannot be decoded.
An unhandled error condition has been signalled: :UTF-8 stream decoding error on #<SB-SYS:FD-STREAM for "file /Users/pravat/Downloads/chinook.db" {1005066B33}>: the octet sequence #(226 30 5) cannot be decoded.



2020-05-06T20:35:21.010000+05:30 LOG pgloader version "3.6.2"
2020-05-06T20:35:21.012000+05:30 LOG Data errors in '/private/tmp/pgloader/'
2020-05-06T20:35:21.012000+05:30 LOG Parsing commands from file #P"/Users/pravat/Downloads/chinook.db"

What I am doing here?

:UTF-8 stream decoding error on
#<SB-SYS:FD-STREAM for "file /Users/pravat/Downloads/chinook.db" {1005066B33}>:
  the octet sequence #(226 30 5) cannot be decoded.
```

**Comment by dimitri** [comment]
Hi @pravatk ; the problem lies with the library we are using to parse the command line arguments. Contrary to GNU getopt and many others, it is unable to re-order command line options in the argument list. So adding `--with ...` at the *end* of the command line is tripping our code over, and then it things it has to deal with a list of command file. 

Your SQLite database is read as a pgloader command file.

Please try `pgloader --with ... source.db PostgreSQL:///test` and it should work.
