### ISSUE TITLE
Type cast from varchar(1) to boolean

### ISSUE THREAD

**Issue by dsilvam** [dimitri/pgloader#115]
Hello Dimitri, 

Let me first say you have an awesome tool.

Maybe this is not the right place to ask this, but can't find any other. 

I am trying to do a cast from varchar(1) to boolean, but the resulting sql puts boolean(1) instead of boolean. Is there a way to achieve that? 

I am currently using: type varchar when (= precision 1) to boolean

Thanks

**Comment by pnomolos** [comment]
For those coming in the future, those rules (as of January 2020) now live at [DEFAULT MySQL CASTING RULES](https://pgloader.readthedocs.io/en/latest/ref/mysql.html#default-mysql-casting-rules)
