### ISSUE TITLE
Question - Is it possible a selective migration

### ISSUE THREAD

**Issue by edubon** [dimitri/pgloader#1154]
Is it possible to do a selective migration with select clauses? I have a row_ts column in my MSSQL tables with the moment on which the row was written. I want to migrate to Postgres just the rows added past year and not the older ones.
Is it possible with pgLoader?

**Comment by dimitri** [comment]
Yes. See our MATERIALIZE VIEWS support for MS SQL at https://pgloader.readthedocs.io/en/latest/ref/mssql.html#ms-sql-views-support.
