### ISSUE TITLE
sysdate as a default value for a table column

### ISSUE THREAD

**Issue by suchik19** [dimitri/pgloader#1155]
- [ ] pgloader --version
 pgloader-3.6.1-
  
Could you please let us know how we  can use current_date(current_timestamp) ,sequence as  default values for the table columns.I tried with the below syntax but it is not working

```
LOAD csv
     FROM 'testload.csv' (cola)
     INTO postgresql://pgloader?testload
(
cola,
colb using (datetime)
colc using nextval('seq1')
 )
 WITH 
           skip header = 1,
          fields optionally enclosed by '"',
          fields escaped by double-quote,
          fields terminated by ';'
  SET client_encoding to 'latin1',
          work_mem to '12MB',
          standard_conforming_strings to 'on;
```

 load.csv

```
cola
a
b
c
```

Please let us know how we can achieve the default values for columns

**Comment by dimitri** [comment]
If you omit the columns from the pgloader target list, Postgres will provide the DEFAULT values for you automatically. You are working too hard ;-)

The following should work, from a quick adaptation of your current command:

```
LOAD csv
     FROM 'testload.csv' (cola)
     INTO postgresql://pgloader?testload ( cola )
 WITH 
           skip header = 1,
          fields optionally enclosed by '"',
          fields escaped by double-quote,
          fields terminated by ';'
  SET client_encoding to 'latin1',
          work_mem to '12MB',
          standard_conforming_strings to 'on;
```
