### ISSUE TITLE
ERROR Database error 22008: date/time field value out of range: "20180406034959"

### ISSUE THREAD

**Issue by edubon** [dimitri/pgloader#1157]
I'm getting this error trying to migrate MSSQL to Postgres

ERROR Database error 22008: date/time field value out of range: "20180406034959"
HINT: Perhaps you need a different "datestyle" setting.
CONTEXT: COPY voldlayer, line 1, column lyr_crt_utc_time: "20180406034959"

The origin table is: 
```
CREATE TABLE VOLDLAYER
(
    MD_REP_SID        NUMERIC(3)      NOT NULL,
    SRV_SID           NUMERIC(5)      NOT NULL,
    VSC_SID           NUMERIC(6)      NOT NULL,
    SITE_SID          NUMERIC(4)      NOT NULL,
    LYR_SID           NUMERIC(6)      NOT NULL,
    LYR_REFID         VARCHAR(255)    NOT NULL,
    LYR_GUID          CHAR(40)        NOT NULL,
    LYR_NAME          VARCHAR(255)    NOT NULL,
    LYR_CRT_TS        NUMERIC(14)     NOT NULL,
    LYR_CRT_DAY_ID    NUMERIC(8)      NOT NULL,
    LYR_CRT_MINUTE_ID NUMERIC(4)      NOT NULL,
    LYR_CRT_UTC_TIME  DATETIME        NOT NULL,
    LYR_MOD_TS        NUMERIC(14)     NOT NULL,
    LYR_MOD_DAY_ID    NUMERIC(8)      NOT NULL,
    LYR_MOD_MINUTE_ID NUMERIC(4)      NOT NULL,
    LYR_MOD_UTC_TIME  DATETIME        NOT NULL,
    LYR_OWN_ACC_GUID  CHAR(40)        NOT NULL,
    LYR_MOD_ACC_GUID  CHAR(40)        NOT NULL,
    LYR_TYPE_ID       NUMERIC(2)      NOT NULL,
    LYR_LOG_STATUS    NUMERIC(1)      NOT NULL,
    NO_LAYERS         NUMERIC(1)      NOT NULL,
    ROW_TS            DATETIME        DEFAULT GETDATE() NOT NULL,
  CONSTRAINT VOLDLAYER_PK PRIMARY KEY (MD_REP_SID, SRV_SID, VSC_SID, SITE_SID, LYR_SID)
);
```

The destination table is (Is not created by pgloader, was already created):

```
CREATE TABLE VOLDLAYER
(
    MD_REP_SID        NUMERIC(3)      NOT NULL,
    SRV_SID           NUMERIC(5)      NOT NULL,
    VSC_SID           NUMERIC(6)      NOT NULL,
    SITE_SID          NUMERIC(4)      NOT NULL,
    LYR_SID           NUMERIC(6)      NOT NULL,
    LYR_REFID         VARCHAR(255)    NOT NULL,
    LYR_GUID          CHAR(40)        NOT NULL,
    LYR_NAME          VARCHAR(255)    NOT NULL,
    LYR_CRT_TS        NUMERIC(14)     NOT NULL,
    LYR_CRT_DAY_ID    NUMERIC(8)      NOT NULL,
    LYR_CRT_MINUTE_ID NUMERIC(4)      NOT NULL,
    LYR_CRT_UTC_TIME  TIMESTAMP       NOT NULL,
    LYR_MOD_TS        NUMERIC(14)     NOT NULL,
    LYR_MOD_DAY_ID    NUMERIC(8)      NOT NULL,
    LYR_MOD_MINUTE_ID NUMERIC(4)      NOT NULL,
    LYR_MOD_UTC_TIME  TIMESTAMP       NOT NULL,
    LYR_OWN_ACC_GUID  CHAR(40)        NOT NULL,
    LYR_MOD_ACC_GUID  CHAR(40)        NOT NULL,
    LYR_TYPE_ID       NUMERIC(2)      NOT NULL,
    LYR_LOG_STATUS    NUMERIC(1)      NOT NULL,
    NO_LAYERS         NUMERIC(1)      NOT NULL,
    ROW_TS            TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT VOLDLAYER_PK PRIMARY KEY (MD_REP_SID, SRV_SID, VSC_SID, SITE_SID, LYR_SID)
);
```

The load file is:

```
load database
     from {{DBPATH}}
     into postgresql://postgres:postgres@localhost:5432/postgres_test_pgloader
WITH
    include no drop,
    create no tables
cast
   type DATETIME to TIMESTAMP
including only table names like 'VOLDLAYER' in schema 'dbo'
BEFORE LOAD EXECUTE LDCreate.sql;
```
The problem is that this value ( lyr_crt_utc_time: "20180406034959") is not in this column in the origin table in in LYR_MOD_TS which have NUMERIC(14)  value, not in LYR_CRT_UTC_TIME.
LYR_MOD_TS=20180406034959
LYR_CRT_UTC_TIME=2018-04-06 03:49:59.000
As a result of the error the complete table is not migrated.

**Comment by edubon** [comment]
I have just found that is the order of the columns, they were not the same in the origin table and destination table. Is there any way to migrate the data by column name and not by position?

**Comment by edubon** [comment]
In any case if I change the position of the columns in my table creation script the error disappear. But it going to be a nightmare check all the places. Because of that if it would be any way on not rely in the order it would be great.

**Comment by dimitri** [comment]
It should already work: pgloader is sending the columns data in the order specified by the COPY command, and we list the columns we send with the column names from MS SQL:

  https://github.com/dimitri/pgloader/blob/master/src/sources/mssql/mssql.lisp#L44

Which version of pgloader are you using? See https://github.com/dimitri/pgloader/commit/86b6a5cb807321b9c0b742049b1974e0393962b7#diff-5d239283f673f799a8e2b4266528cf88 where we fix that, it might be that you don't have the fix yet.

**Comment by edubon** [comment]
I was using version 3.6.2 but now I'm trying to use the docker instance for dev.

**Comment by edubon** [comment]
Is it fixed in a released version?
