### ISSUE TITLE
Where does pgloader looks for pg_hba.conf?

### ISSUE THREAD

**Issue by SCI-sksaha** [dimitri/pgloader#1159]
pgloader on EC2 accessing AWS Aurora PostgreSQL. EC2 has both psql and pgloader installed. I use .pgpass file to keep my passwords. Both psql and pgloader worked for last few weeks. But suddenly pgloader stopped working. Something might have changed, but don't know.

psql continues to work. I can use different variables like PGPASSWORD and that works also.

pgloader keeps looking for a pg_hba.conf file entry. Is there a way to find out where it is looking for the pg_hba.conf? The .load file has all info user,pass,host,dbname.

Please find below --debug run output:

KABOOM!
FATAL error: Failed to connect to pgsql at "ivr-obms-prod-east-1-db.vpc.verizon.com" (port 5432) as user "app_ms_w": Database error 28000: no pg_hba.conf entry for host "144.70.3.158", user "app_ms_w", database "obdialerapp", SSL off
Date/time: 2020-05-29-15:36!
An unhandled error condition has been signalled:
   Failed to connect to pgsql at "ivr-obms-prod-east-1-db.vpc.verizon.com" (port 5432) as user "app_ms_w": Database error 28000: no pg_hba.conf entry for host "144.70.3.158", user "app_ms_w", database "obdialerapp", SSL off

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1006B3E963}>
0: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE-TO-STREAM #<SB-IMPL::STRING-OUTPUT-STREAM {1009AA0563}>)
1: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE #<PGLOADER.CONNECTION:DB-CONNECTION-ERROR {1009AA03D3}> :OUTPUT NIL :IF-EXISTS :APPEND :VERBOSE NIL)
2: ((FLET "H0" :IN PGLOADER::MAIN) #<PGLOADER.CONNECTION:DB-CONNECTION-ERROR {1009AA03D3}>)
3: (SB-KERNEL::%SIGNAL #<PGLOADER.CONNECTION:DB-CONNECTION-ERROR {1009AA03D3}>)
4: (ERROR PGLOADER.CONNECTION:DB-CONNECTION-ERROR :MESG #<SIMPLE-BASE-STRING "Database error 28000: no pg_hba.conf entry for hos..." (len=116) {1009AA000F}> :TYPE "pgsql" :HOST "ivr-obms-prod-east-1-db.vpc.verizon.com" :PORT 5432 :USER "app_ms_w")
5: (PGLOADER.PGSQL:LIST-RESERVED-KEYWORDS #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://app_ms_w@ivr-obms-prod-east-1-db.vpc.verizon.com:5432/obdialerapp {10093B3303}>)
6: ((LAMBDA ()))
7: (PGLOADER:RUN-COMMANDS #P"/apps/opt/cfs-scripts/PG_LOADER_CACS_EAST.load" :START-LOGGER NIL :FLUSH-SUMMARY T :SUMMARY NIL :LOG-FILENAME NIL :LOG-MIN-MESSAGES NIL :CLIENT-MIN-MESSAGES NIL)
8: (PGLOADER::PROCESS-COMMAND-FILE ("/apps/opt/cfs-scripts/PG_LOADER_CACS_EAST.load") :FLUSH-SUMMARY T)
9: (PGLOADER.MONITOR::CALL-WITH-MONITOR #<CLOSURE (LAMBDA NIL :IN PGLOADER::MAIN) {1006B6FF5B}>)
10: (PGLOADER::MAIN ("pgloader" "--debug" "/apps/opt/cfs-scripts/PG_LOADER_CACS_EAST.load"))
11: ((LAMBDA NIL :IN "/apps/opt/downloads/pgloader-3.6.2/dumper-2SKVI5f7.lisp"))
12: ((FLET "WITHOUT-INTERRUPTS-BODY-35" :IN SAVE-LISP-AND-DIE))
13: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))

2020-05-29T15:36:18.234000-04:00 INFO Stopping monitor

What I am doing here?

Failed to connect to pgsql at "ivr-obms-prod-east-1-db.vpc.verizon.com" (port 5432) as user "app_ms_w": Database error 28000: no pg_hba.conf entry for host "144.70.3.158", user "app_ms_w", database "obdialerapp", SSL off

**Comment by dimitri** [comment]
Postgres is handling authentication and authorisation in its HBA file, this error message comes from Postgres, not from pgloader. Please review your authentication settings in Postgres.

**Comment by brudel** [comment]
@dimitri hey, I have the same error. Both psql cli and my program with libpq can connect to the db from the same computer, only pgloader can't.
The server is of amazon, Heroku service.

**Comment by iatif91** [comment]
Hi @dimitri, I'm having the same problem too. I'm using a managed PostgreSQL DB in IBM Cloud and accessing it from a Kubernetes cluster. Access from PgAdmin and the application are OK, but not the pgloader. Of course the three are running on the same cluster. Any hints on what this can be? Thank you for your help.
