### ISSUE TITLE
question

### ISSUE THREAD

**Issue by dataf3l** [dimitri/pgloader#1160]
was this:

https://github.com/dimitri/pgloader/tree/pgloader-v2

abandoned?

**Comment by phoe** [comment]
> This branch is 152 commits ahead, 1578 commits behind master. 

That's an interesting question; I wasn't even aware of this branch. Given that pgloader is now at version 3.6.x and the recent commits there mention 2.2.3, I guess so, yes.

**Comment by dimitri** [comment]
The first version of pgloader ever was written in TCL. When I took over the project I found myself unable to implement the features I needed in TCL and rewrote it in Python. That's 15 years ago I think.

In the middle of Python 2 to 3 migration I had some problems with pgloader, and in parallel realised that users where using bigger and bigger data set and thus performance was getting a problem with our Python implementation. I had already discovered Common Lisp then, and rewrote pgloader in Common Lisp and added database migration facilities.

The Python version is still available in that branch, from years ago.
