### ISSUE TITLE
Provide docker images for stable releases

### ISSUE THREAD

**Issue by bratekarate** [dimitri/pgloader#1162]
Images on dockerhub do not provide a pgloader release version but are rather development versions.
```
$ docker run dimitri/pgloader:latest pgloader --version
pgloader version "3.6.3~devel"
compiled with SBCL 1.4.16.debian
```
This is unexpected, as one could assume `latest` refers to the latest release. However, it seems that it is built from the current development/master branch. 

As I spent an entire day trying to debug #889 (different version than OP but same error, other posts also use `3.6.3~devel`), just to find out that the issue disappears when building the docker image from source `>=v3.6.1`, I propose handling the docker images the following way:
  1. Only build `latest` for new release versions
  2. Retag older versions with their respective version numbers instead of overwriting them
  3. If 1. is not implemented, make it clear in the description that the container contains only a development version

**Comment by dimitri** [comment]
Hi @bratekarate ; do you know how to implement your proposal? do you have time to do it, and which kind of access would you need to achieve that? Also, it might be nice to use GitHub docker packaging facilities nowadays and have both the current HEAD build and also stable tags.

**Comment by bratekarate** [comment]
Thanks for your quick reply @dimitri. 
Some parts of this proposal I know how to implement, but some not, or at least I don't know if I know how to do it :)

I know how to pull the `latest` image, retag it with a version number and push it back to the hub. Or, alternatively, I know how to build a new release image, tag it as `latest` as well as `<VERSION> and push it to the hub.

However, I have never used githubs CI capabilities. In my projects I usually use gitlab with my own gitlab shell runner that executes the docker commands I want. I would need to see how the CI is configured right now and how the automatic build is triggered to see what needs to be changed. 

As for the new github docker packaging facilities, I don't know much about them.

**Comment by jeffreyvdhondel** [comment]
@dimitri Maybe i could help you with this. Not familiar with the github package. But i have experience with docker + ci/cd.
Can we get in touch somehow?

**Comment by jeffreyvdhondel** [comment]
Created a workflow @dimitri you have to add the secret so that this workflow can work.
If this works for the current releases we need to generate and tag the older version also.

**Comment by pierot** [comment]
@dimitri Any news on this?

**Comment by dimitri** [comment]
Hi @pierot ; yeah it's been integrated now, see also https://pgloader.readthedocs.io/en/latest/install.html#docker-images.

**Comment by pierot** [comment]
@dimitri Maybe I'm missing something, but if I go to https://hub.docker.com/r/dimitri/pgloader/tags I dont' see 3.6.8 tagged and the last push is 2 months ago.
