### ISSUE TITLE
Feature Request: load from MongoDB

### ISSUE THREAD

**Issue by wobh** [dimitri/pgloader#117]
There's a couple CL drivers for MongoDB

- https://github.com/archimag/mongo-cl-driver
- https://github.com/fons/cl-mongo

There's also a project to bring BSON into postgres

- https://github.com/maciekgajewski/postgresbson

With these in mind, how feasible would be to add a feature to copy data from a MongoDB source into Postgres? What would it take to implement a reasonable way of transforming schemaless source data into something more structured?

I'm asking because it seems like finding solutions for this could help a lot of people and projects out there that started out in something like Mongo but now really need Postgres.

Thanks!

**Comment by dimitri** [comment]
To load data from MongoDB to PostgreSQL, see http://www.8kdata.com/torodb/

**Comment by xeoshow** [comment]
> To load data from MongoDB to PostgreSQL, see http://www.8kdata.com/torodb/

looks like this website is invalid, for now does pgloader support MongoDB ? Thanks
