### ISSUE TITLE
How do I convert a Sqlite timestamp to Postgres

### ISSUE THREAD

**Issue by PeL123** [dimitri/pgloader#1177]
Hi Dimitri,

 I hope you can help, I'm not sure if you'd consider it a bug or not, but Pgloader seems to have trouble with the Sqlite datatype of **timestamp: "DATETIME('now', 'localtime')"** and cannot convert it

Thanks, Perry

**Version:**
pgloader version: 3.6.1
installed using "apt-get install pgloader" on Debian 10 (Buster)

**Command file:**
```
root@devqa-cloud4:/home/perry.chandler# cat command-file
load database
        from sqlite:///home/perry.chandler/trimmed_sqlite.backup
        into pgsql://pgloader_role:pgloader_role@localhost:5433/taxdb

with include drop, create tables, create indexes, reset sequences

cast type datetime    to timestamptz using sqlite-timestamp-to-timestamp
cast type timestamp   to timestamptz using sqlite-timestamp-to-timestamp
cast type timestamptz to timestamptz using sqlite-timestamp-to-timestamp

set work_mem to '16MB', maintenance_work_mem to '512 MB';
```

(I have tried all cast commands individually)

**Output:**

```
root@devqa-cloud4:/home/perry.chandler# pgloader command-file
2020-07-02T15:29:30.040000Z LOG pgloader version "3.6.1"
2020-07-02T15:29:30.157000Z LOG Migrating from #<SQLITE-CONNECTION sqlite:///home/perry.chandler/trimmed_sqlite.backup {10069253D3}>
2020-07-02T15:29:30.157000Z LOG Migrating into #<PGSQL-CONNECTION pgsql://pgloader_role@localhost:5433/taxdb {1006926C13}>
2020-07-02T15:29:31.037000Z ERROR Database error 22007: invalid input syntax for type timestamp: "DATETIME('now', 'localtime')"
QUERY: CREATE TABLE databaseversion
(
  id                 bigserial,
  databaseversion    bigint,
  comments           text,
  datelastupdate     timestamp default 'DATETIME(''now'', ''localtime'')',
  lastupdatebyuserid bigint,
  createdbydb        text default 'local'
);
2020-07-02T15:29:31.038000Z FATAL Failed to create the schema, see above.
2020-07-02T15:29:31.047000Z LOG report summary reset
       table name     errors       rows      bytes      total time
-----------------  ---------  ---------  ---------  --------------
            fetch          0          0                     0.000s
  fetch meta data          0        903                     0.642s
   Create Schemas          0          0                     0.000s
 Create SQL Types          0          0                     0.014s
    Create tables          0          0                     0.000s
-----------------  ---------  ---------  ---------  --------------
-----------------  ---------  ---------  ---------  --------------

```

**Comment by dimitri** [comment]
Please build from fresh sources, your SQLite spelling of CURRENT_TIMESTAMP should now be parsed by pgloader.

**Comment by PeL123** [comment]
Hi Dimitri,
 Thanks for the response to my issue, unfortunately even installing from the latest 3.6.2 tarball bundle didn't work (https://github.com/dimitri/pgloader/releases)

root@devqa-cloud4:/var/pgloader/pgloader-bundle-3.6.2/bin# ./pgloader /home/perry.chandler/command-file
2020-07-06T13:50:42.041000Z LOG pgloader version "3.6.2"
2020-07-06T13:50:42.166000Z LOG Migrating from #<SQLITE-CONNECTION sqlite:///home/perry.chandler/trimmed_sqlite.backup {10068126F3}>
2020-07-06T13:50:42.167000Z LOG Migrating into #<PGSQL-CONNECTION pgsql://pgloader_role@localhost:5433/taxcalc {1006814093}>
2020-07-06T13:50:43.016000Z ERROR Database error 22007: invalid input syntax for type timestamp: "DATETIME('now', 'localtime')"
QUERY: CREATE TABLE databaseversion
(
  id                 bigserial,
  databaseversion    bigint,
  comments           text,
  datelastupdate     timestamp default 'DATETIME(''now'', ''localtime'')',
  lastupdatebyuserid bigint,
  createdbydb        text default 'local'
);
2020-07-06T13:50:43.017000Z FATAL Failed to create the schema, see above.
2020-07-06T13:50:43.026000Z LOG report summary reset
       table name     errors       rows      bytes      total time
-----------------  ---------  ---------  ---------  --------------
            fetch          0          0                     0.000s
  fetch meta data          0       1351                     0.614s
   Create Schemas          0          0                     0.001s
 Create SQL Types          0          0                     0.013s
    Create tables          0          0                     0.000s
-----------------  ---------  ---------  ---------  --------------
-----------------  ---------  ---------  ---------  --------------
root@devqa-cloud4:/var/pgloader/pgloader-bundle-3.6.2/bin#

----------------------------------------------------------------------------------------------------------------------------

Are the 3 date casting rules shown in the documentation the only ones available?

https://pgloader.readthedocs.io/en/latest/ref/sqlite.html#
type datetime    to timestamptz using sqlite-timestamp-to-timestamp
type timestamp   to timestamptz using sqlite-timestamp-to-timestamp
type timestamptz to timestamptz using sqlite-timestamp-to-timestamp 

Thanks, Perry.

**Comment by dimitri** [comment]
You need to build from sources to get the bug fix. There was no release made after this bug has been fixed upstream.

**Comment by tikkanek** [comment]
I'm getting an almost identical error, the difference here is that my datetime column is declared as 
` "createdAt" datetime NOT NULL DEFAULT (datetime('now'),` without the localtime as in the case above.

```
pgloader version "3.6.48d8ed0"
Migrating from #<SQLITE-CONNECTION sqlite:///
Migrating into #<PGSQL-CONNECTION pgsql://postgres@localhost:5432/newdb >
ERROR Database error 22007: invalid input syntax for type timestamp with time zone: "datetime('now')"
QUERY: CREATE TABLE tile 
(
  id                        text,
  createdat                 timestamptz default 'datetime(''now'')',
```

**Comment by PeL123** [comment]
Hey Tikkanek,

 Dmitri's last suggestion worked for me - I had to build from the latest source code. I didn't get that error afterwards.

Perry.

**Comment by AruMoon** [comment]
Build from the latest source code. Still having this issue
