### ISSUE TITLE
Decode, TO_DATE and nested transformation function

### ISSUE THREAD

**Issue by esoni** [dimitri/pgloader#1181]
Hi All,
1) is there an equivalent trasnformation function to DECODE ORACLE ?
For example, in my ctl of sql loader i had  the following function

 "DECODE(:FIELD_1, 'X','ND','C2')",

2) is there equivalent transformer function to Oracle TO_DATE ?

3)Another question. With sql loader you can use nested transformation function,
for .ie

NVL(TO_DATE(...), ..)

is it possible  to use nestend transformation function in pg loader ?

Thanks a lot

**Comment by esoni** [comment]
UPDATE:
i found a solution for point 2).
For example TO_DATE(:BIRTDATE, 'YYYYMMDD') => BIRTHDATE [date format 'YYYYMMDD']
Is not clear all the operators available in pgadmin to transform the field during an import

**Comment by esoni** [comment]
Hi @dimitri ,
it is not clare what operators i can use inside using expression.  is lisp code ? or operators developed internally in pgloader ?
Thanks

**Comment by dimitri** [comment]
Hi @esoni ; pgloader is written in Common Lisp and the transformations we can do on the fly are implemented in Common Lisp too. Some basic and common features are available directly in the command language itself (such as `[date format ...]`), the generic approach is to use Common Lisp code indeed. 

See `--load-lisp-file` on the command line and take inspiration from the included transformation functions in https://github.com/dimitri/pgloader/blob/master/src/utils/transforms.lisp.
