### ISSUE TITLE
customize filename e file location of rejected file dat and log 

### ISSUE THREAD

**Issue by esoni** [dimitri/pgloader#1184]
Hi all,
if i  try to import a csv in the table DUMMY, pg loader save the rejected rows  and  logs in a subfolder named dummy with inside :

- dummy.dat: contains the rejected rows
- dummy.log: contains the import error logs

is there a way to customize location and filename of .dat and.log file ?
Thanks,
Dario

**Comment by dimitri** [comment]
You can use `--root-dir` to have those files created where you want. See the docs at https://pgloader.readthedocs.io/en/latest/ for all the details.
