### ISSUE TITLE
mapping a csv column in  more cols of table

### ISSUE THREAD

**Issue by esoni** [dimitri/pgloader#1185]
Hi All,
i dont know how can map a csv col in more table cols. 
```
LOAD CSV
     FROM './dummy.csv'
     HAVING FIELDS
      (
         A,B,IGNORE
      )     
     INTO {{DBPATH}}
     TARGET TABLE DUMMY
        (
          "A",
           "B"
           "C" using "A"
        )    
```
In the above example  i have a file with three cols. I have also a table DUMMY2 with three cols A,B,C.
I want to map in this way:

- csv col A into col A and col C of table DUMMY
- csv col B into col B of table DUMMY

How can also map DB col C with CSV col A ?  "C" using "A"  is not works
Thanks
Dario

**Comment by dimitri** [comment]
The expression `"C" using a` should work. The field name is available as a variable in the expression. You can have a look at https://github.com/dimitri/pgloader/blob/master/test/udc.load and other test cases for inspiration, and read the docs too.
