### ISSUE TITLE
Connection issue: 10 fell through ECASE expression. Wanted one of (0 2 3 4 5 6 7 8)

### ISSUE THREAD

**Issue by audax-shreyaspurohit** [dimitri/pgloader#1199]
*  pgloader version  
    ```
    pgloader version "3.6.2"
    compiled with SBCL 1.4.5.debian
    ```
  
*  psql version
   ```
   psql (12.4 (Ubuntu 12.4-1.pgdg18.04+1))
    ```
* Connection works fine with the psql command
```
psql "postgresql://postgres:postgres@172.27.240.1:5432/app"
```
* The command for pgloader
```
load database
  from sqlite:///mnt/f/Projects/Go/db/app.db
  into postgresql://postgres:postgres@172.27.240.1:5432/app?sslmode=disable
with include drop, create tables, create indexes, reset sequences, workers=2
set work_mem to '16MB', maintenance_work_mem to '512 MB';
```
* Command and output in debug mode using pgloader:
```
 pgloader --debug ./sqllite-to-pg.load
pgloader version 3.6.2
compiled with SBCL 1.4.5.debian
sb-impl::*default-external-format* :UTF-8
tmpdir: #P"/tmp/pgloader/"
2020-08-26T08:28:07.008000Z NOTICE Starting pgloader, log system is ready.
2020-08-26T08:28:07.019000Z INFO Starting monitor
2020-08-26T08:28:07.047000Z INFO Parsed command:
load database
  from sqlite:///mnt/f/Projects/Go/db/app.db
  into postgresql://postgres:postgres@172.27.240.1:5432/app?sslmode=disable
with include drop, create tables, create indexes, reset sequences, workers=2
set work_mem to '16MB', maintenance_work_mem to '512 MB';


KABOOM!
FATAL error: Failed to connect to pgsql at "172.27.240.1" (port 5432) as user "postgres": 10 fell through ECASE expression. Wanted one of (0 2 3 4 5 6 7 8).
Date/time: 2020-08-26-01:28An unhandled error condition has been signalled:
                              Failed to connect to pgsql at "172.27.240.1" (port 5432) as user "postgres": 10 fell through ECASE expression. Wanted one of (0 2 3 4 5 6 7 8).


Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10006505B3}>
0: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE-TO-STREAM #<SB-IMPL::STRING-OUTPUT-STREAM {1006B9B583}>)
1: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE #<PGLOADER.CONNECTION:DB-CONNECTION-ERROR {1006B9B3F3}> :OUTPUT NIL :IF-EXISTS :APPEND :VERBOSE NIL)
2: ((FLET "H0" :IN PGLOADER::MAIN) #<PGLOADER.CONNECTION:DB-CONNECTION-ERROR {1006B9B3F3}>)
3: (SB-KERNEL::%SIGNAL #<PGLOADER.CONNECTION:DB-CONNECTION-ERROR {1006B9B3F3}>)
4: (ERROR PGLOADER.CONNECTION:DB-CONNECTION-ERROR :MESG "10 fell through ECASE expression. Wanted one of (0 2 3 4 5 6 7 8)." :TYPE "pgsql" :HOST "172.27.240.1" :PORT 5432 :USER "postgres")
5: (PGLOADER.PGSQL:LIST-RESERVED-KEYWORDS #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://postgres@172.27.240.1:5432/app {10065C5303}>)
6: ((LAMBDA ()))
7: (PGLOADER:RUN-COMMANDS #P"/mnt/f/Projects/Go/db/sqllite-to-pg.load" :START-LOGGER NIL :FLUSH-SUMMARY T :SUMMARY NIL :LOG-FILENAME NIL :LOG-MIN-MESSAGES NIL :CLIENT-MIN-MESSAGES NIL)
8: (PGLOADER::PROCESS-COMMAND-FILE ("./sqllite-to-pg.load") :FLUSH-SUMMARY T)
9: (PGLOADER.MONITOR::CALL-WITH-MONITOR #<CLOSURE (LAMBDA NIL :IN PGLOADER::MAIN) {10055AD67B}>)
10: (PGLOADER::MAIN ("pgloader" "--debug" "./sqllite-to-pg.load"))
11: ((LAMBDA NIL :IN "/build/pgloader-fXgEi1/pgloader-3.6.2/dumper-2SKVI5f7.lisp"))
12: ((FLET SB-UNIX::BODY :IN SAVE-LISP-AND-DIE))
13: ((FLET "WITHOUT-INTERRUPTS-BODY-36" :IN SAVE-LISP-AND-DIE))
14: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))



2020-08-26T08:28:07.128000Z INFO Stopping monitor

What I am doing here?

Failed to connect to pgsql at "172.27.240.1" (port 5432) as user "postgres": 10 fell through ECASE expression. Wanted one of (0 2 3 4 5 6 7 8).
```    

Please let me know if anyone has any pointers on what might be going wrong with the connection? 

Thanks a lot for any help.

**Comment by phoe** [comment]
Seems like a duplicate of https://github.com/dimitri/pgloader/issues/1183

**Comment by audax-shreyaspurohit** [comment]
@phoe thanks for the quick reply, I saw that but the password I have is postgres and there is no special char in it. May be I should try without a password.

**Comment by audax-shreyaspurohit** [comment]
so, password is the problem. I removed the password and set "trust" as the auth mode in pg_hba.conf and it magically worked. Closing this issue as I have an alternative.

**Comment by erickertz** [comment]
I'm on an ARM mac and trying to run this with CCL on an ubuntu image, many problems and this was one of them so i needed to run an older version of pgloader and pgloader simply wont build on --platform=linux/amd64 ubuntu:18.04 . I'm going from mssql -> postgres. Heres what I got so far and hope it helps someone:


docker-compose.yml:

`services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - MSSQL_SA_PASSWORD=Pa55w0rd
      - ACCEPT_EULA=Y
#    volumes:
#      - "./mssql/data:/var/opt/mssql/data"
#      - "./mssql/log:/var/opt/mssql/log"
#      - "./mssql/secrets:/var/opt/mssql/secrets"
    ports:
      - "1433:1433"
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      # POSTGRES_HOST_AUTH_METHOD=trust IS FOR LOCAL DEV ONLY AND IS A WORKAROUND FOR A PGLOADER BUG!!!!
      # https://github.com/dimitri/pgloader/issues/1199
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=Pa55w0rd
      - POSTGRES_USER=SA
      - POSTGRES_DB=test
  pgloader:
    depends_on:
      - "mssql"
      - "postgres"
    build:
      dockerfile: Dockerfile
#    environment:
#      - DOCKER_DEFAULT_PLATFORM=linux/amd64`

Dockerfile:

`FROM --platform=linux/amd64 ubuntu:18.04
LABEL authors="erickertz"

RUN apt update

# Install dependancies
RUN apt install -y gnupg wget apt-transport-https libssl1.0.0 libssl-dev freetds-dev

# Add pgloader-ccl keys
RUN  wget -qO- https://dl.packager.io/srv/opf/pgloader-ccl/key | apt-key add -

# Add pgloader-ccl repo
RUN wget -O /etc/apt/sources.list.d/pgloader-ccl.list \
  https://dl.packager.io/srv/opf/pgloader-ccl/master/installer/ubuntu/18.04.repo

# Install pgloader-ccl
RUN apt update
RUN apt install -y pgloader-ccl

# Add pgloader "alias"
RUN cp /usr/bin/pgloader-ccl /usr/bin/pgloader
RUN cp /etc/default/pgloader-ccl /etc/default/pgloader

# NOTE: we need to do a simple wait here or do something slick to check for both DB's to be up, running, and restored
# RUN pgloader mssql://SA:Pa55w0rd@mssql/navu-dev-test pgsql://SA@postgres/navu-dev-test

# Just keep the container running for now for sh debugging
ENTRYPOINT ["tail", "-f", "/dev/null"]`
