### ISSUE TITLE
How to write the commands that include keywords like `load`?

### ISSUE THREAD

**Issue by kebab-mai-haddi** [dimitri/pgloader#1210]
https://stackoverflow.com/questions/63998338/how-to-run-load-database-command-of-pgloader-in-a-terminal-while-migrating-data

**Comment by dimitri** [comment]
Have you tried reading the docs? did you try `pgloader file.load`? Actually, wait, I don't know, what did you actually try? Do I have to guess to be able to help you?

**Comment by kebab-mai-haddi** [comment]
If by guessing you mean clicking on the link, then yes.
