### ISSUE TITLE
Is on-the-fly data transformation possible? E.g. if field = X then make it Y?

### ISSUE THREAD

**Issue by dhilowitz** [dimitri/pgloader#1212]
Hi!

I'm copying data from a mysql table to a pre-existing postgreSQL table as follows:

```
LOAD database
    from mysql://<source-url>
    into pgsql://<target-url>
    with include no drop,
        create no tables,
        create no indexes,
        downcase identifiers,
        quote identifiers,
        data only
    CAST type datetime to timestamp drop default drop not null using zero-dates-to-null,
    column case_notes.status to varchar
    INCLUDING ONLY TABLE NAMES MATCHING 'case_notes';
```

This would work fine except that the target field `status` has a check on it which requires that it not be blank, and the source table has bad data such that sometimes it is blank even though it shouldn't be (blank as in empty string: ''). Is there a way to transform the data such that if `case_notes.status` is '', I can assign it the default value for the field on the fly?

**Comment by dimitri** [comment]
Hi @dhilowitz ; it is possible to implement what you're asking by using the [MATERIALIZE VIEWS](https://pgloader.readthedocs.io/en/latest/ref/mysql.html#materialize-views) support of pgloader. Write a view in SQL for MySQL in your source database, transform anything as you want to, using the full power of SQL. And then pgloader can migrate the output from this VIEW into Postgres.
