### ISSUE TITLE
Verbosity versus performance?

### ISSUE THREAD

**Issue by Keerthikan** [dimitri/pgloader#1214]
I seem to struggle to understand how this tool is able to load data into a database, and still provide a row by row error log, on what went wrong. 

I understand that doing a batch insertion is faster than doing row by row insertion, but when an error is encountered within the 25000 rows, how does this (pgLoader) then, in a efficient way provide information about which row failed? 

I mean, you cannot avoid doing row by row insertion, to pick out the exact row causing an incorrect insertion?
which then makes the insertion itself performance heavy? , especially since you don't know whether you encounter 1 or 3 errors within the same batch?

Do you have an smart way of deducing where the error is located? or is just pure brute force row by row insertion, and thereby deducing the erroneous row?

The reason why I am asking, is because I am trying to make similar implementation for asp.net, but seem to struggle with this, 
doing one giant insertion can be fast, but not provide the best verbosity and vice versa, but somehow you seem to have found some sort of balance here?

**Comment by dimitri** [comment]
Hi @Keerthikan ;

Have you tried reading the source code yet? You will find all the answers at https://github.com/dimitri/pgloader/blob/master/src/pg-copy/copy-retry-batch.lisp where we implement retrying.

What we used to do in pgloader for the longest time was dichotomy: when a batch is refused, split it in two batches and continue recursively until you have a batch of one row. It's not very efficient, but it's kind of the best we could do.

Until Postgres added the line number in the COPY error message, and we took advantage of that. Now that in pgloader we have an array of pre-processes rows that we send to Postgres, we can re-send a batch in two parts, before the error index, skip the row at the error index, then send the rest of the rows all together.

When you have many rows with errors, it's not very efficient. But one or two rows in a batch of 25 thousands? that's still pretty good.
