### ISSUE TITLE
help on cast to bigint

### ISSUE THREAD

**Issue by jacks33** [dimitri/pgloader#1215]
Salut Dimitri,

I have this CSV to load 

N_PERIMETRE|@|L_LIBELLE_PERIM
1,00000000000000000E+00|@|L
3,00000000000000000E+00|@|A
0,00000000000000000E+00|@|R
2,00000000000000000E+00|@|G

in a UTF8 database and the first column is an integer int the DB.

Thanks to yout help i switch the comma to point using : 
https://github.com/dimitri/pgloader/issues/835

but I still have to cast N_PERIMETRE::numeric::bigint
this works fine in postgres, but how can you do it on pgloader ?
Above the config of pgloader

Merci

Tiago ANASTACIO

**Comment by dimitri** [comment]
Given the following thanks to the `parse-number` lib, you should be able to write a transformation function that you can then use in your pgloader setup:

``` lisp
(parse-number:parse-real-number "00000000000000000E+00")
```
