### ISSUE TITLE
Building pgloader on Windows fails with libsqlite3 sqlite3 error

### ISSUE THREAD

**Issue by to2016** [dimitri/pgloader#1223]
Hello,

I tried to build the pgloader on Windows.

Used environment:
MSyS2 and Cygwin64 (the same error on both plattforms)
SBCL 2.0.0 (as Lisp Environment)

The command following command fails, blaming on missing libsqlite library. sqlite3 sqlite3 dev package and freetds is installed and available:

`sbcl.exe --noinform --no-sysinit --no-userinit --load save.lisp`

The error is:
;;; Computing Hangul syllable namesWhile evaluating the form starting at line 10, column 0
  of #P"C:/temp/src/save.lisp":

debugger invoked on a LOAD-FOREIGN-LIBRARY-ERROR in thread
#<THREAD "main thread" RUNNING {10010B0523}>:
  Unable to load any of the alternatives:
   ((:DEFAULT "libsqlite3") (:DEFAULT "sqlite3"))

Using make throw the following error:
;; loading system "mssql"
Fatal LOAD-FOREIGN-LIBRARY-ERROR:
  Unable to load foreign library (SYBDB).
  Error opening shared object "sybdb.dll":

Any ideas/suggestions how to fix the problem? 
Or can someone, who has managed to build pgloader send me a pgloader.exe binary?

  - [x] pgloader --version
  
    ```
    <3.6.2>
    ```
  
  - [x] did you test a fresh compile from the source tree?
    
  - [x] did you search for other similar issues?
    
  - [ ] how can I reproduce the bug?

**Comment by phoe** [comment]
You seem to have no sqlite DLL available on your path. Could you echo your `PATH` variable and verify that `libsqlite3.dll` or `sqlite3.dll` are available there and in the proper architecture?

**Comment by to2016** [comment]
I have already checked the availability of the libsqlite3.dll and the sqlite3.dll
```
whereis libsqlite3.dll 
whereis sqlite3.dll 
```
give me back the right path

**Comment by phoe** [comment]
Is your SBCL and DLL both 32-bit or both 64-bit? (They cannot be of mixed architecture.)

**Comment by to2016** [comment]
The Environment is like that:

SBCL (Steel Bank Common Lisp 2.0.0) X86-64
MSYS2 Mingw-w64 64 bit Shell

```
objdump.exe -f /usr/lib/libsqlite3.a
In archive C:/msys64/usr/lib/libsqlite3.a:

sqlite3.o:     file format pe-x86-64
architecture: i386:x86-64, flags 0x00000039:
HAS_RELOC, HAS_DEBUG, HAS_SYMS, HAS_LOCALS
start address 0x0000000000000000

```

I think the architecture maps, and there should be no problem.

**Comment by phoe** [comment]
Wait a second - why do you have an `.a` file there? Shouldn't you objectdump `.dll` files since you are on Windows?

**Comment by to2016** [comment]
Because I'm inside of the MSys in the bash.

**Comment by phoe** [comment]
Where are the DLL files, then? pgloader requires DLLs to dynamically link against on Windows, not object files.

**Comment by to2016** [comment]
OK the sqlite3.dll is getting used now for compilation.

Seems to compiling successfull but than there is an error with compressed core:

```
#<THREAD "main thread" RUNNING {10010B0523}>:
  Unable to save compressed core: this runtime was not built with zlib support

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.
```

**Comment by to2016** [comment]
I haved the line :compression t in the lisp file. Build succeeded
Thank you for your assistance

**Comment by phoe** [comment]
For core compression, grab a SBCL binary that was built with core compression/zlib support - e.g. https://github.com/roswell/sbcl_bin has those in its releases section. Note that then your binary will also depend on `zlib1.dll` (which should be bundled with the roswell version).
