### ISSUE TITLE
Support for comments

### ISSUE THREAD

**Issue by ianbytchek** [dimitri/pgloader#126]
@dimitri, a massive thanks for putting up the pgloader. I'm trying to migrate from MySql to Postgres, your project really helped after a lot of troubles with other tools.

One thing that I found missing were comments for columns. I assume this is not the top-priority feature, but probably would be useful to have.

**Comment by dimitri** [comment]
It took some time before I got to it, but somehow felt a good way to spend the evening today, so here it is ;-) please report any findings.

**Comment by trtrtr95** [comment]
Hello @dimitri ! 
Do you plan to add comment support also for MSSQL's table columns in feature version of pgloader? 
Thanks in advance for your reply and thanks for the pgloader :)

**Comment by dimitri** [comment]
Hi @trtrtr95 ; this looks like a very good “First Contribution” to pgloader. Please open a specific issue for your question and get working on a PR. In your specific issue, or in your draft PR, you can ask as many questions as needed, I will help you get there!

**Comment by RobertoTassistroLeonardo** [comment]
hi, i try to use mysql comments flow to provide same functionality to mssql: the sqls:
list-all-column-comments.sql
`SELECT 
    -- 'public' AS schema_name, -- Rename schema to public
    LOWER(so.name) AS table_name, -- Convert table names to lowercase
    LOWER(sc.name) AS column_name, -- Convert column names to lowercase
    CAST(ep.value AS NVARCHAR(MAX)) AS column_comment
FROM 
    sys.extended_properties ep
JOIN 
    sys.objects so ON ep.major_id = so.object_id
LEFT JOIN 
    sys.columns sc ON so.object_id = sc.object_id AND ep.minor_id = sc.column_id
WHERE 
         c.table_schema = '~a'
         and t.table_type = 'BASE TABLE'
         and ep.name = 'MS_Description'
         and ep.value != ''         
         ~:[~*~;and (~{table_name ~a~^ or ~})~]
         ~:[~*~;and (~{table_name ~a~^ and ~})~]
order by table_name; -- , ordinal_position;`

list-all-table-comments.sql
`SELECT 
    -- 'public' AS schema_name, -- Rename schema to public
    LOWER(so.name) AS table_name, -- Convert table names to lowercase
    CAST(ep.value AS NVARCHAR(MAX)) AS table_comment
FROM 
    sys.extended_properties ep
JOIN 
    sys.objects so ON ep.major_id = so.object_id
WHERE 
    table_schema = '~a'
    and table_type = 'BASE TABLE'
    and ep.name = 'MS_Description'
    and ep.minor_id = 0
    and ep.value != ''
         ~:[~*~;and (~{table_name ~a~^ or ~})~]
         ~:[~*~;and (~{table_name ~a~^ and ~})~];
`
code for mssql-schema.lisp excerpt
`(defun add-comments-to-postgresql (catalog &key including excluding)
  "Add table and column comments to PostgreSQL."
  (loop
     :for (table-name comment) :in (list-table-comments :including including :excluding excluding)
     :do (let ((pg-table (find-table (catalog->pg catalog) table-name)))
           (when pg-table
             (execute (format nil "COMMENT ON TABLE ~a IS '~a';"
                              (escape-identifier (table-name pg-table))
                              (escape-string comment))))))
  (loop
     :for (table-name column-name comment) :in (list-columns-comments :including including :excluding excluding)
     :do (let* ((pg-table (find-table (catalog->pg catalog) table-name))
                (pg-column (find-column pg-table column-name)))
           (when (and pg-table pg-column)
             (execute (format nil "COMMENT ON COLUMN ~a.~a IS '~a';"
                              (escape-identifier (table-name pg-table))
                              (escape-identifier (column-name pg-column))
                              (escape-string comment))))))
)


(defun list-table-comments (&key including excluding)
  "Return comments on MSSQL tables."
  (loop
     :for (table-name comment)
     :in (mssql-query (sql "/mssql/list-all-table-comments.sql"
                           (db-name *connection*)
                           including
                           including
                           excluding
                           excluding))
     :when (and comment (not (string= comment "")))
     :collect (list table-name comment)))


(defun list-columns-comments (&key including excluding)
  "Return comments on MSSQL columns."
  (loop
     :for (table-name column-name comment)
     :in (mssql-query (sql "/mssql/list-all-column-comments.sql"
                           (db-name *connection*)
                           including
                           including
                           excluding
                           excluding))
     :when (and comment (not (string= comment "")))
     :collect (list table-name column-name comment)))


(defun escape-identifier (identifier)
  "Escape SQL identifiers to handle special characters properly."
  (format nil "\"~a\"" identifier))

(defun escape-string (string)
  "Escape SQL strings to handle special characters properly."
  (replace-regexp-in-string "'" "''" string))`
  
excerpt for mssql.lisp
`
      ;; Add comments to tables and columns in PostgreSQL 
      (add-comments-to-postgresql catalog
                                 :including including
                                 :excluding excluding)`

I need to verify if it right and why i have trouble with mssql connection: please your comments can be helpful thank you
