### ISSUE TITLE
Migrating From MSSQLSERVER to POSTGRESQL with pgloader

### ISSUE THREAD

**Issue by andrebaraacho** [dimitri/pgloader#1276]
I'm using pgloader to migrate the structure and data from sql server to postgresql and I got one error when I was using pgloader with compile sbcl of Heap exhausted during garbage collection. So, after that I changed the compile to CCL 
compiled with Clozure Common Lisp Version 1.11-r16635  (LinuxX8664)  the heap exhausted was fixed. Now, I'm with error below:

 (7F7E57A5B270) : 0 (PRINT-CALL-HISTORY :CONTEXT NIL :PROCESS NIL :ORIGIN NIL :DETAILED-P NIL :COUNT 1152921504606846975 :START-FRAME-NUMBER 0 :STREAM #<STRING-OUTPUT-STREAM  #x30201C3ECABD> :PRINT-LEVEL 2 :PRINT-LENGTH 5 :SHOW-INTERNAL-FRAMES NIL :FORMAT :TRADITIONAL) 853
 (7F7E57A5B3D8) : 1 (PRINT-BACKTRACE-TO-STREAM #<STRING-OUTPUT-STREAM  #x30201C3ECABD>) 85
 (7F7E57A5B408) : 2 (PRINT-BACKTRACE #<TYPE-ERROR #x30201C3ECEFD> :OUTPUT NIL :IF-EXISTS :APPEND :VERBOSE NIL) 797
 (7F7E57A5B4A0) : 3 (FUNCALL #'#<(:INTERNAL (PGLOADER.LOAD:COPY-FROM (PGLOADER.SOURCES:COPY)))> #<TYPE-ERROR #x30201C3ECEFD>) 197
 (7F7E57A5B4C8) : 4 (CONDITION-HANDLER #<TYPE-ERROR #x30201C3ECEFD>) 493
 (7F7E57A5B540) : 5 (SIGNAL #<TYPE-ERROR #x30201C3ECEFD>) 989
 (7F7E57A5B598) : 6 (%ERROR #<TYPE-ERROR #x30201C3ECEFD> NIL 17522576635576) 117
 (7F7E57A5B5C0) : 7 (%AREF1 #<A Foreign Pointer #x7F7E4C029D00> 158) 565
 (7F7E57A5B5E8) : 8 (FUNCALL #'#<(:INTERNAL (PGLOADER.SOURCES:MAP-ROWS (PGLOADER.SOURCE.MSSQL:COPY-MSSQL)))> #<BABEL-ENCODINGS:INVALID-UTF8-CONTINUATION-BYTE #x30201C3ED33D>) 245
 (7F7E57A5B618) : 9 (SIGNAL #<BABEL-ENCODINGS:INVALID-UTF8-CONTINUATION-BYTE #x30201C3ED33D>) 989
 (7F7E57A5B670) : 10 (%ERROR #<BABEL-ENCODINGS:INVALID-UTF8-CONTINUATION-BYTE #x30201C3ED33D> (:OCTETS #(231) :ENCODING :UTF-8 :BUFFER ...) 17522576635603) 117
 (7F7E57A5B698) : 11 (FUNCALL #'#<BABEL-ENCODINGS::UTF-8-DECODER> #<A Foreign Pointer #x7F7E4C029D00> 0 227 "Carl Walker, Inc. is a parking consulting firm specializing in parking planning, design, operations and restoration.  We also have specialized expertise in fa^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@" 0) 1173
 (7F7E57A5B740) : 12 (FOREIGN-STRING-TO-LISP #<A Foreign Pointer #x7F7E4C029D00> :OFFSET 0 :COUNT 227 :MAX-CHARS 72057594037927935 :ENCODING :UTF-8) 1197

--pgloader version

pgloader version "3.6.3~devel"
compiled with Clozure Common Lisp Version 1.11-r16635  (LinuxX8664)

database collation Sql Server: SQL_Latin1_General_CP1_CI_AS
databae encoding Postgresql: UTF8.

**Comment by svantevonerichsen6906** [comment]
Line 10 of the backtrace shows an UTF-8 encoding error.  The offending octet is 231 (binary 11100111), which is in Latin1 encoding a "ç" (LATIN_SMALL_LETTER_C_WITH_CEDILLA).  In UTF-8 it is the start of a three-byte encoded character code, so the next byte would have to be a continuation byte, which seems to be not the case.  If you look at the string which is shown in the next line, it shows the point where it couldn't continue decoding the string.  One might imagine that the "fa" there, when continuing with "ç", is the word "façade", which indicates that this is actually a latin1 encoded string, not some other corruption.  You also provided the information that, yes, the MS SQL server itself is set up with latin1 encoding.

Going into the documentation, I found the following with regards to the encoding setup:

https://pgloader.readthedocs.io/en/latest/ref/mssql.html#ms-sql-driver-setup-and-encoding

which shows how you should configure the FreeTDS driver to send UTF-8.

Hope this helps.

**Comment by andrebaraacho** [comment]
Thanks @svantevonerichsen6906 it works fine.
