### ISSUE TITLE
invalid byte sequence for encoding "UTF8": 0x00

### ISSUE THREAD

**Issue by t12nslookup** [dimitri/pgloader#1283]
While I'm aware that this might be an issue with the existence of "String Null" characters within the SQL Server database, which cannot be translated into PostgreSQL, it is causing my database transfer to fail to import data on over 50 tables.

  - [x] pgloader --version
  
    ```
    pgloader version "3.6.2"
    compiled with SBCL 2.0.1.debian
    ```
  
  - [x] how can I reproduce the bug?
  my db.load file:
    ```
    load database
     from mssql://jon.adams:ed2bromZ@192.168.0.18/v6_DEV
     into postgresql://jadams:t12look4@localhost/v6_dev
    cast
    type text to varchar,
    type memo to text,
    type number to float8,
    type integer to int4,
    type datetime to timestamp
    
    including only table names like 'lims_notes' in schema 'dbo'
    
    set work_mem to '16MB', maintenance_work_mem to '512 MB'

    before load do $$ drop schema if exists dbo cascade; $$
    ```
  - [x] pgloader output you obtain
  
```
2021-05-11T09:10:32.013000Z LOG pgloader version "3.6.2"
2021-05-11T09:10:32.101000Z LOG Migrating from #<MSSQL-CONNECTION mssql://jon.adams@192.168.0.18:1433/v6_DEV {10061C1373
}>
2021-05-11T09:10:32.101000Z LOG Migrating into #<PGSQL-CONNECTION pgsql://jadams@localhost:5432/v6_dev {10061C2C13}>
Max connections reached, increase value of TDS_MAX_CONN
Max connections reached, increase value of TDS_MAX_CONN
2021-05-11T09:10:32.331000Z ERROR Database error 22021: invalid byte sequence for encoding "UTF8": 0x00
CONTEXT: COPY lims_notes, line 1
2021-05-11T09:10:32.383000Z LOG report summary reset
             table name     errors       rows      bytes      total time
-----------------------  ---------  ---------  ---------  --------------
            before load          0          1                     0.008s
        fetch meta data          0          2                     0.097s
         Create Schemas          0          0                     0.001s
       Create SQL Types          0          0                     0.007s
          Create tables          0          2                     0.027s
         Set Table OIDs          0          1                     0.005s
-----------------------  ---------  ---------  ---------  --------------
      lwlims.lims_notes          1          0                     0.016s
-----------------------  ---------  ---------  ---------  --------------
COPY Threads Completion          0          4                     0.016s
 Index Build Completion          0          1                     0.010s
         Create Indexes          0          1                     0.003s
        Reset Sequences          0          0                     0.014s
           Primary Keys          0          1                     0.001s
    Create Foreign Keys          0          0                     0.000s
        Create Triggers          0          0                     0.000s
       Install Comments          0          0                     0.000s
-----------------------  ---------  ---------  ---------  --------------
      Total import time          1          0                     0.044s
```

  - [ ] data that is being loaded, if relevant
  
I will attach a CSV export that appears to include NUL characters in it.  I have not confirmed that the CSV export itself fails to import, but it may suffer from the same fault.

  - [x] How the data is different from what you expected, if relevant
    No data is imported for the table, although the table structure is created successfully.

**Comment by wblaszczyk** [comment]
You can cast column with remove-null-characters modifier
`cast column LIMS_NOTES.NOTE_CONTENTS to text drop typemod using remove-null-characters`

**Comment by t12nslookup** [comment]
that works, now I just need to re-identify all the columns and tables that need overriding.

**Comment by wblaszczyk** [comment]
You can also cast type e.g.
`cast type nvarchar to text drop typemod using remove-null-characters`

**Comment by t12nslookup** [comment]
I'm actually fighting the "drop typemod" at the moment (Access connecting to the converted database is freaking out) but I think I might do as you suggest as it'll make the load script much easier to understand.  I should never need null characters in strings.

It's running now with:
```
cast
type char to varchar keep typemod using remove-null-characters,
type nchar to varchar keep typemod using remove-null-characters,
type varchar to varchar keep typemod using remove-null-characters,
type nvarchar to varchar keep typemod using remove-null-characters,
type xml to varchar keep typemod using remove-null-characters,
type text to varchar keep typemod using remove-null-characters,
type memo to text keep typemod using remove-null-characters,
type number to float8,
type integer to int4,
type datetime to timestamp
```

**Comment by wblaszczyk** [comment]
If you want to keep the length of the string fields, just omit the "drop typemod" clause and cast to varchar. 
`cast type char to varchar using remove-null-characters, etc.`
Keeping typemod is the default behavior. "Drop typemod" is needed when casting to type text because PostgreSQL does not support to specify the max length of the type text (as well as null bytes in strings).

**Comment by t12nslookup** [comment]
https://pgloader.readthedocs.io/en/latest/ref/mssql.html#default-ms-sql-casting-rules says otherwise for an MS SQL database ... In any case, it works with the "keep" and "fails" without

**Comment by t12nslookup** [comment]
I have an issue that the type conversion is truncating the string to 4096 characters.  Do you know if would this be due to the "remove-null-characters" routine, or the column types at either end?

**Comment by t12nslookup** [comment]
ignore me, it's related to the freetds.conf setup

**Comment by mlee-yb** [comment]
Ran into this issue when trying to migrate a mySQL table that contained columns defined with BIT(1).  pgloader will cast type BIT to BOOLEAN and that throws the same error.  Resolution was to override the default cast type and use BIT(1) instead of BOOLEAN

`type bit when (= 1 precision) to boolean drop typemod using bits-to-boolean`
