### ISSUE TITLE
Migrate data from databases in Docker containers results as Postgres connection error

### ISSUE THREAD

**Issue by nowiko** [dimitri/pgloader#1308]
Hello, I have faced with problem, that I am unable to convert MySQL database from one container, to PostgreSQL database in other Docker container. 

If I am trying to connect to those containers from my host, everything works:
```bash
mysql -h 127.0.0.1 -P 3307 -uuser -ppassword
# and following works as expected, I am connected to databases in containers
psql -h 127.0.0.1 -p 5433 -d database -U user
```

But when I am trying to perform migration:
```bash
docker run --rm --name pgloader dimitri/pgloader:latest pgloader mysql://user:password@127.0.0.1:3307/database postgresql://user:password@127.0.0.1:5433/database
```
I am getting
```
FATAL error: Failed to connect to pgsql at "127.0.0.1" (port 5433) as user "user": Database error: Socket error in "connect": ECONNREFUSED (Connection refused)
```
Probably I missed something? Or am I doing something wrong? (Sorry, I am new to Docker concept)

pgloader version  - "3.6.3~devel"

**Comment by Merff** [comment]
Try like this on MacOS
```docker run --rm dimitri/pgloader:latest pgloader mysql://user:passwor@host.docker.internal/db_name pgsql://user:passwor@host.docker.internal/db_name```

**Comment by jhult** [comment]
I needed to add an extra host to my run command:

`docker run --rm --add-host host.docker.internal:host-gateway dimitri/pgloader:latest pgloader mysql://user:passwor@host.docker.internal/db_name pgsql://user:passwor@host.docker.internal/db_name`

https://echorand.me/posts/docker-extra-hosts/

I also had to change my MySQL database from listening on `localhost` to listening on `0.0.0.0`.

**Comment by jhult** [comment]
Related issue: #736

**Comment by nowiko** [comment]
Thanks for the help, I mark this issue as closed.

**Comment by aleimu** [comment]
docker run --rm -it --network=host ghcr.io/dimitri/pgloader:latest pgloader --verbose --debug
