### ISSUE TITLE
sqlite to postgresql: datetime to timestamp does not work and behaves very strange

### ISSUE THREAD

**Issue by rowild** [dimitri/pgloader#1314]
1. show what you did,

To convert from sqlite to postgresql, i call `pgloader commad` with this script in the command file:

```
load database
    from 'data.db'
    into postgresql:///poddb

WITH
  include drop, create tables, create indexes, reset sequences

cast
  type datetime to timestamp

set
  work_mem to '160MB', maintenance_work_mem to '5012 MB';
```

2. show the result you got,

Beginning of output:

```
2021-08-31T23:12:22.007360+01:00 LOG pgloader version "3.6.2"
2021-08-31T23:12:22.008864+01:00 LOG Data errors in '/private/tmp/pgloader/'
2021-08-31T23:12:22.008907+01:00 LOG Parsing commands from file #P"/Volumes/_III_/Z_WWW/_ZZZ PoD/strapi-pod/.tmp/commands.load"
2021-08-31T23:12:22.080834+01:00 LOG Migrating from #<SQLITE-CONNECTION sqlite:///Volumes/_III_/Z_WWW/_ZZZ PoD/strapi-pod/.tmp/data.db {1005AD56C3}>
2021-08-31T23:12:22.081007+01:00 LOG Migrating into #<PGSQL-CONNECTION pgsql://rowild@127.0.0.1:5432/poddb {1005AD5CD3}>
2021-08-31T23:12:22.449769+01:00 ERROR Database error 22008: date/time field value out of range: "1627303906122-01-01"
CONTEXT: COPY strapi_role, line 1, column created_at: "1627303906122-01-01"
```

3. explain how the result is not what you expected.

I expect a simple copying process of the datetime value, since sqlite's datetime as well as postgresql's timestamp both use the UNIX timestamp format.

It works, when I change the "cast" section of the command script to this:

```
cast
  type datetime to text
```

which is, however, not a correct table field in the end.

  - [ ] pgloader --version
  
    ```
    pgloader version "3.6.2"
   compiled with SBCL 2.0.11
    ```
  
  - [ ] did you test a fresh compile from the source tree?
    
    Compiling pgloader from sources is documented in the
    [README](https://github.com/dimitri/pgloader#build-from-sources), it's
    easy to do, and if patches are to be made to fix your bug, you're going
    to have to build from sources to get the fix anyway…
    
  - [x] did you search for other similar issues?
    
  - [x] how can I reproduce the bug?

    Incude a self-contained pgloader command file. (given above, it is short)

    If you're loading from a database, consider attaching a database dump to
    your issue. For MySQL, use `mysqldump`. For SQLite, just send over your
    source file, that's easy. Maybe be the one with your production data, of
    course, the one with just the sample of data that allows me to reproduce
    your bug.
    (sqlite file included as zip)

[data.db.zip](https://github.com/dimitri/pgloader/files/7087085/data.db.zip)

**Comment by rowild** [comment]
And 5 minutes after posting this issue (after having tried to solve the problem for the whole day) I find the solution:

```
cast
  type datetime
    to timestamptz
    using (lambda (x)
      (unix-timestamp-to-timestamptz x )
    )
```

**Comment by huy-lv** [comment]
@rowild are you trying to migrate strapi's database? I'm also stuck while migrating data from sqlite to Postgres, please help, how to achieve this?

**Comment by rowild** [comment]
I'm sorry, but that's long ago, I don't know anymore what was going on. But from what is posted here I assume you have to run this pgloader command:

```sql
load database
    from 'data.db'
    into postgresql:///poddb

WITH
  include drop, create tables, create indexes, reset sequences

cast
  type datetime
    to timestamptz
    using (lambda (x)
      (unix-timestamp-to-timestamptz x )
    )

set
  work_mem to '160MB', maintenance_work_mem to '5012 MB';
```

I don't know where, though...

**Comment by huy-lv** [comment]
It ran without error but when I start the project:
```
error: select distinct "t0".*, "t0"."id" from "public"."admin_permissions" as "t0" left join "public"."admin_permissions_role_links" as "t1" on "t0"."id" = "t1"."permission_id" left join "public"."admin_roles" as "t2" on "t1"."role_id" = "t2"."id" where ("t2"."id" = $1) - could not identify an equality operator for type json
```
<img width="670" alt="image" src="https://github.com/dimitri/pgloader/assets/7688070/d8cf2fd8-68f5-485d-9651-53d25f459ba9">
