### ISSUE TITLE
Problems loading data from column varchar(max) from SqlServer - The data from column is truncated

### ISSUE THREAD

**Issue by hermeswaldemarin** [dimitri/pgloader#1323]
Hello. 

I'm working in a database loading from SqlServer o Postgres and I'm facing a issue. 

I'm my sqlserver table I have a column as VARCHAR(MAX). 

The problem is that the column in sqlserver has a data with 80009 characters and pgloader process truncate the field data length to 64512 chars and I can find why this is happening.  I have no error, but the data in target table is truncated.

I'm not a LISP developer but I'm tried to do some debugs in the code. 

The data that is passed to this method in object src/monkey/mssql.lisp is arriving already with len = 64512. 

(defun sysdb-data-to-lisp (%dbproc data type len)

I tried to print (foreign-string-to-lisp data :count 64513 )  but when I force the len I got an error in character encoding probably because the byte sequence has 64512 bytes and not  64513. 

This method is invocated by the following section of the code bellow in method 
(defun map-query-results (query &key row-fn (connection *database*))

(sysdb-data-to-lisp %dbproc
                                                  (%dbdata %dbproc i)
                                                  (%dbcoltype %dbproc i)
                                                  (%dbdatlen %dbproc i))

I need help to undestand how to load the full data from this column to postgres.

**Comment by hermeswaldemarin** [comment]
I already tried to do casts from varchar to text in load config file and the data is truncated too.

**Comment by Saumya-NebCodes** [comment]
I am facing the same issue did you able to solve it? I am migrating MSSQL to PSQL everything is working fine except for 1 column where of type nvarchar with almost 10000 bytes of data and after migration it always get truncated after 1989 bytes.

**Comment by svantevonerichsen6906** [comment]
Those functions starting with a `%` in their name are foreign functions from the freetds library.  It seems that the connection is reporting a wrong data length.  This might be connected to this or a similar issue: https://github.com/FreeTDS/freetds/issues/392

**Comment by 0xc0dec0ffee** [comment]
If you are using Podman to run pgloader and Postgres, don’t forget to set **FREETDSCONF=/etc/freetds.conf**

This is required for **text size = 2147483647** to take effect.


```
podman run --rm -it \
  -v "<your local pgloader load file>:/pgloader/ms.load" \
  -v "<your local freetds.conf>:/etc/freetds.conf" \
  -e FREETDSCONF=/etc/freetds.conf \
  dimitri/pgloader:latest \
  pgloader /pgloader/ms.load
```

// freetds.conf
```
[global]
tds version = auto
text size = 2147483647
client charset = UTF-8
```

// ms.load
```
LOAD DATABASE
     FROM mssql://<mssql username>:<mssql password>@<mssql ip>:1433/<mssql db name>
     INTO postgres://<pg username>:<pg password>@host.containers.internal:5432/<pg db name>;

```
