### ISSUE TITLE
Failed to connect to pgsql at "postgres" (port 5432) as user "dbuser": 10 fell through ECASE expression

### ISSUE THREAD

**Issue by NilakshaPerera** [dimitri/pgloader#1332]
Thanks for contributing to [pgloader](https://pgloader.io) by reporting an
issue! Reporting an issue is the only way we can solve problems, fix bugs,
and improve both the software and its user experience in general.

The best bug reports follow those 3 simple steps:

  1. show what you did,
  2. show the result you got,
  3. explain how the result is not what you expected.

  - [x] pgloader --version
  
    ```
    3.6.2
    ```
  
  - [x] did you test a fresh compile from the source tree?
    
    No
    
  - [x] did you search for other similar issues?
  - Yes

load database
        from pgsql://dbuser:dbpass1@postgres:5432/source_db
        into pgsql://dbuser:dbpass1@postgres:5432/dest_db;

  -- including only table names matching ~/contacts/ in schema 'public';
```

  - [ ] pgloader output you obtain

  
```
PS D:\xampp\htdocs\postgre-docker> docker-compose exec postgres pgloader pgscript.load
2021-10-22T05:27:23.007000Z LOG pgloader version "3.6.2"
KABOOM!
FATAL error: Failed to connect to pgsql at "postgres" (port 5432) as user "dbuser": 10 fell through ECASE expression. Wanted one of (0 2 3 4 5 6 7 8).
An unhandled error condition has been signalled:
   Failed to connect to pgsql at "postgres" (port 5432) as user "dbuser": 10 fell through ECASE expression. Wanted one of (0 2 3 4 5 6 7 8).

What I am doing here?

Failed to connect to pgsql at "postgres" (port 5432) as user "dbuser": 10 fell through ECASE expression. Wanted one of (0 2 3 4 5 6 7 8).
```

**Comment by df7cb** [comment]
That is caused by a cl-postmodern (<= 2018.something) version that doesn't know about scram-sha-256 authentication yet.

**Comment by ethereal-engineer** [comment]
> That is caused by a cl-postmodern (<= 2018.something) version that doesn't know about scram-sha-256 authentication yet.

Is there any way to work around this easily?

**Comment by df7cb** [comment]
Update cl-postmodern (needs cl-uax and some other new package as well), or simply use md5 auth. Or build pgloader on a machine that has the newer cl-postmodern, and copy the binary over, that should usually work.

**Comment by robbash** [comment]
FYI I built pgloader from source on Alpine, if someone wants to quickly use it.

Docker image: https://hub.docker.com/r/robbash/pgloader
Github repo: https://github.com/robbash/pgloader
