### ISSUE TITLE
Migrate data from MySQL to Postgres with pgloader fails

### ISSUE THREAD

**Issue by mccannm1** [dimitri/pgloader#1336]
Hello

I am trying to migrate data from a MySQL database on a specific server to a postgres database using pgloader.
Can you tell me if this is a bug in the pgloader product?  or is there an upgrade required? or modificaiton
to server specs, e.g. memory?

Thanks
/Martin

Steps:
Use pgloader to migrate the data from JIRASDDB database (MySQL database) on server noxe1211 to 
a created database (empty) on postgres01, the server from which the command is being issued. 

Problem:   Result shows promise but fails with *Heap exhausted during garbage collection*  
This is the issue!

root@postgres01:~# pgloader mysql://root:'PASSWORD'@noxe1211.devlab.ibm.com/JIRASDDB postgresql://jirauser:JIRAPASSWORD@localhost/jirasddb
2021-11-09T15:57:16.039000Z LOG pgloader version "3.6.2"
2021-11-09T15:57:16.088000Z LOG Migrating from #<MYSQL-CONNECTION mysql://root@noxe1211.devlab.ibm.com:3306/JIRASDDB {10074B6353}>
2021-11-09T15:57:16.089000Z LOG Migrating into #<PGSQL-CONNECTION pgsql://jirasddbuser@localhost:5432/jirasddb {10075F95A3}>
Heap exhausted during garbage collection: 128 bytes available, 208 requested.
Gen  Boxed   Code    Raw  LgBox LgCode  LgRaw  Pin       Alloc     Waste        Trig      WP GCs Mem-age
 1     198      0  34950      0      0      0    9   912017536 239712128    42949672   35148   0  1.0493
 2     688      0  72440   3600      0    105  194  2019494704 498169040     2000000   76833   0  0.7109
 3       0      0      0      0      0      0    0           0         0     2000000       0   0  0.0000
 4       0      0      0      0      0      0    0           0         0     2000000       0   0  0.0000
 5       0      0      0      0      0      0    0           0         0     2000000       0   0  0.0000
 6    1665      7   1527    287      0    142    0   116427072   2455232     2000000    3628   0  0.0000
 7     118      0  15345      0      0      0    0   386848224 119843360     2000000   15463   0  0.0000
           Total bytes allocated    =    3434787536
           Dynamic-space-size bytes =    4294967296
GC control variables:
   *GC-INHIBIT* = true
   *GC-PENDING* = true
   *STOP-FOR-GC-PENDING* = false
fatal error encountered in SBCL pid 648303(tid 0x7f8c2340f700):
Heap exhausted, game over.

Welcome to LDB, a low-level debugger for the Lisp runtime environment.
ldb> quit
Really quit? [y] y
root@postgres01:~#

===

Memory on server postgre01:

root@postgres01:~# cat /proc/meminfo | more
MemTotal:       32888356 kB
MemFree:        27604656 kB
MemAvailable:   31763412 kB
Buffers:          350824 kB
Cached:          4077884 kB
:

  
  - Did you test a fresh compile from the source tree?   No, installed pgloader and dependencies as instructed in Github
    
  - Did you search for other similar issues?    Yes, seen similar issue in [327](https://github.com/dimitri/pgloader/issues/327) but didn't appear to show resolution
    
  - How can I reproduce the bug?   Fault is reproducible with command above

Note: Alternatively I could import an SQL dump file of the database. Can this be done with pgloader? 
I have a file generated as follows:
/usr/bin/mysqldump -u 'root' -p JIRASDDB > /root/JIRA_DEVELOPMENT_JIRASDDB_`date +\%Y\_\%m\_\%d\_\%H\%M\%S`.sql

Attached file: 

I tried this using psql....with it failed with syntax errors 
postgres=# psql -h localhost -U postgres -d jirasddb -f /root/JIRA_DEVELOPMENT_JIRASDDB_2021_11_08_073102.sql
     
Please assist, Thanks
/Martin

**Comment by mccannm1** [comment]
Same error results when I try this step:   [import-mysql-dump-to-postgresql-database](https://stackoverflow.com/questions/5417386/import-mysql-dump-to-postgresql-database/44719416)

**Comment by filinvadim** [comment]
WITH --prefetch-rows 10000 helps

**Comment by mccannm1** [comment]
Hi @filinvadim 
I ran the command with --prefetch-rows 10000  from the postgres server. Thanks
I see output attached.

When I check corresponding tables e.g. Project, jiraissue.... they are of course populated in the MySQL database
but have zero rows in postgres database..

Q. Does the output show the migration should have executed successfully? (see attachment) It seems different from that I see at this link
    [Migrating MySQL databases to a Managed Database for PostgreSQL using pgLoader](https://www.scaleway.com/en/docs/tutorials/migrate-mysql-databases-postgresql-pgloader/) where there are _read_ and _imported_ columns in the output
    
Q. 
prefetch rows = 10000 , is the number of rows  that pgloader  is  allowed to read in memory in each reader thread. 
It doesnt impose any restriction on the amount of data that can be migrated in any way?  
Thanks
/Martin

**Comment by mccannm1** [comment]
[pgloader_to_migrate.txt](https://github.com/dimitri/pgloader/files/7512852/pgloader_to_migrate.txt)

**Comment by mccannm1** [comment]
Ok I see the problem, the data does appear to be migrated..

postgres=# \c jirasddb;
You are now connected to database "jirasddb" as user "postgres".
jirasddb=#
jirasddb=# select id,pname,projecttype from project;
 id | pname | projecttype
----+-------+-------------
(0 rows)

**must use a qualified name, or fully qualified name**

must use     SELECT * FROM source_db.sample_table;
                   OR SELECT * FROM new_db.source_db.sample_table;

jirasddb=# select id,pname,projecttype from JIRASDDB.project;
  id       |             pname                            | projecttype
-------+-------------------------------+--------------
 10600 | JSD-BETA                                  | service_desk
 10601  | Emptoris                                     | service_desk
 :
 etc
 :
(14 rows)

This is the way pgloader works..  according to step 5 [at this link](https://www.digitalocean.com/community/tutorials/how-to-migrate-mysql-database-to-postgres-using-pgloader) 

I followed step 6 using a load file and this resolves it
This uses a load file to instruct pgLoader to change the table’s 
schema to public once it’s done loading data..   
still need prefetch rows = 10000 or it fails with previous heap space error

LOAD DATABASE
     FROM      mysql://root:password@sqlserver/JIRASDDB?useSSL=false
     INTO     pgsql://postgres:pgpassword@localhost/jirasmgmt

 WITH include drop, create tables, prefetch rows = 10000
 
 The above worked. 
 Thank you @filinvadim 
 We can close , I am done..


When I use

**Comment by filinvadim** [comment]
@dimitri should be `prefetch rows = 10000` default value?

**Comment by mccannm1** [comment]
HI 
Was --prefetch-rows = 10000    what you had recommened in the earlier post?
I thought I had used that value... 
Is default  100000  ?
[Pgloader Reference Manual](https://pgloader.readthedocs.io/en/latest/pgloader.html)
