### ISSUE TITLE
MSSQL to PgSQL - data from nvarchar(max) truncates to 2048 characters

### ISSUE THREAD

**Issue by udit47** [dimitri/pgloader#1351]
Pgloader Version : 3.6.3~devel
PgSql - 14.1
Sql Server - 2019

There is one table with multiple nvarchar(max) columns in a table in SQL Server.
On the postgres side, Same table is created with text data type, I have also checked with varchar data type.

Migration between these two tables run without any errors. But string data is truncated to 2048 chars in postgresql.

sample.load 
```
load database
     from mssql://migration:migration@mssql-db-01/sample
     into postgresql://postgres@pg-db-01:5432/sample

with
    quote identifiers,
    preserve index names,
    data only

CAST type datetime to timestamp,
     type datetime2 to timestamp,
     type smalldatetime to timestamp,
     type tinyint to smallint,
     type uniqueidentifier to uuid using sql-server-uniqueidentifier-to-uuid

set work_mem to '16MB', maintenance_work_mem to '512 MB';
```
Please help.

**Comment by himanish-k** [comment]
Any updates on this @udit47 ? It's probably not related to this repository but I too am facing this issue when using the Sequel gem to fetch values from nvarchar(max) columns in SQL Server. The fetched strings are truncated to 2048 characters.

**Comment by udit47** [comment]
Yes. Use below in .load file. This worked for me in varbinary columns as well as (n)varchar(max) columns.

set mssql parameters textsize to '104857600'

Closing this as it is not the issue.

**Comment by reddogaw** [comment]
While I couldn't get the `SET` command to work in my load file like mentioned above... What did work was explicitly setting/increasing the `text size` property for my connection in the freeTDS conf file per #1323 

```
[global]
    tds version = 7.4
    client charset = UTF-8
    text size = 15000000
```

**Comment by 0xc0dec0ffee** [comment]
If you are using Podman to run pgloader and Postgres, don’t forget to set **FREETDSCONF=/etc/freetds.conf**

This is required for **text size = 2147483647** to take effect.


```
podman run --rm -it \
  -v "<your local pgloader load file>:/pgloader/ms.load" \
  -v "<your local freetds.conf>:/etc/freetds.conf" \
  -e FREETDSCONF=/etc/freetds.conf \
  dimitri/pgloader:latest \
  pgloader /pgloader/ms.load
```

// freetds.conf
```
[global]
tds version = auto
text size = 2147483647
client charset = UTF-8
```

// ms.load
```
LOAD DATABASE
     FROM mssql://<mssql username>:<mssql password>@<mssql ip>:1433/<mssql db name>
     INTO postgres://<pg username>:<pg password>@host.containers.internal:5432/<pg db name>;

```
