### ISSUE TITLE
[Solved] : [BUG on pgloader version <= 3.6.2] --cast "type date to date using zero-dates-to-null"     not working

### ISSUE THREAD

**Issue by DarkRed777** [dimitri/pgloader#1352]
Hello Folks!

Using:

# pgloader --version
pgloader version "3.6.2"
compiled with SBCL 2.0.1-4.el8

on:

OS: Almalinux 8.5 (Arctic Sphynx)

Problem: AFAIK pgloader should accept the following syntax (with casting)

pgloader --cast "type date to date using zero-dates-to-null" mysql://root:'PASSHERE'@localhost/DBNAME postgresql://USER:'PASSHERE'@localhost/MYDBNAME

*but it isn't for unkonwn reason.*

What's wrong here and any solution please?

BTW, If i remove --cast "type date to date drop not null using zero-dates-to-null"   from command line pgloader works but fails with error saying:

date/time field value out of range: "0000-00-00 00:00:00"

**Comment by yveshield** [comment]
type datetime when default "0000-00-00 00:00:00" 
  to timestamptz drop not null drop default
      using zero-dates-to-null

**Comment by DarkRed777** [comment]
> type datetime when default "0000-00-00 00:00:00" to timestamptz drop not null drop default using zero-dates-to-null

Thank you very much Mate. Will try A.S.A.P

**Comment by DarkRed777** [comment]
Solution: Builded  pgloader version "3.6.a94a0a3" and everything works smoothly now!

Seems it was a bug on: <3.6.2
