### ISSUE TITLE
MSSQL to Postgres "is not defined as a value for enum type"

### ISSUE THREAD

**Issue by Terti-te** [dimitri/pgloader#1373]
Hello!

When transferring data from MSSQL to Postgres, I find an error

`ERROR A thread failed with error: -1 is not defined as a value for enum type #<CFFI::FOREIGN-ENUM MSSQL::%SYB-VALUE-TYPE>`

There are no fields with enum type in mssql database, what may be the problem?

Similar problem  https://github.com/dimitri/pgloader/issues/1277

pgloader version "3.6.1"
compiled with SBCL 1.4.0-1.el7

**Comment by aleksandersumowski** [comment]
what w the problem?

**Comment by Zyqsempai** [comment]
@Terti-te Any insights, how you fixed the issue? 
@dimitri Although issue is closed, I still encounter it, any thoughts on what could be the source of issue?

**Comment by harshagarwal001** [comment]
I am stuck in the same problem @Terti-te @dimitri @Zyqsempai 
in case you guys solved it

**Comment by jahangiranwari** [comment]
@harshagarwal001 in our case were able to fix it with below tweaks for FreeTDS config:

```
[global]
        tds version = 7.2
        client charset = UTF-8
        tds_max_conn = 300
        use utf-16 = no
```

**Comment by Mrmantou** [comment]
I solved it by add 'use utf-16 = no' as @jahangiranwari mentioned above.
