### ISSUE TITLE
SQLite -> PostgreSQL wrong timestamp values

### ISSUE THREAD

**Issue by beugene-orcher** [dimitri/pgloader#1381]
Hi mates,

I'm stuck with an issue of migrating data from SQLite to PostgreSQL.

**General info:**

`
$ pgloader --version
`
`
pgloader version "3.6.a94a0a3"
compiled with SBCL 2.0.1.debian
`

command file script:
`load database`
`    from sqlite://conn_url`
`    into postgresql://conn_url`
`set work_mem to '16MB', maintenance_work_mem to '512 MB'`
`cast type datetime to timestamptz using (lambda (x) (unix-timestamp-to-timestamptz x));`

**Results**
The migration is completed without errors and all data is migrated successfully. But values of timestamptz fields are incorrect.
For example:
SQLite:
field            | type        | value
created_at | datetime | 1647950409737

PostgreSQL:
field            | type               | value
created_at | timestamptz | "+54191-06-21T02:42:17"

Right value must be "2022-03-22T12:00:09".

Honestly, I don't know how the lambda function 'unix-timestamp-to-timestamptz' works because of found this solution here. What's wrong and how to fix it?

Thanks for advance!

### UPDATE

Solution:
- just modify the cast by the way: ```type datetime to timestamptz using (lambda (x) (unix-timestamp-to-timestamptz (if x (floor x 1000)))```

**Comment by beugene-orcher** [comment]
added UPDATE section with the solution

**Comment by pxuanbach** [comment]
Thank you so much!
