### ISSUE TITLE
PGLoader tries to connect to SQLite even though I am using mssql:// in the connection string

### ISSUE THREAD

**Issue by kibebr** [dimitri/pgloader#1399]
Thanks for contributing to [pgloader](https://pgloader.io) by reporting an
issue! Reporting an issue is the only way we can solve problems, fix bugs,
and improve both the software and its user experience in general.

The best bug reports follow those 3 simple steps:

  1. show what you did,
  2. show the result you got,
  3. explain how the result is not what you expected.

In the case of pgloader, here's the information I will need to read in your
bug report. Having all of this is a big help, and often means the bug you
reported can be fixed very efficiently as soon as I get to it.

Please provide the following information:

  - [ ] pgloader --version
  
    ```
    pgloader version "3.6.3~devel"
    compiled with SBCL 2.1.5
    ```
  
  - [ ] did you test a fresh compile from the source tree?
    
Yes
    
  - [ ] did you search for other similar issues?

Yes
    
  - [ ] how can I reproduce the bug?

    Include a self-contained pgloader command file.

```
--
-- EDIT THIS FILE TO MATCH YOUR BUG REPORT
--

load database
        from mssql://SA:Pass@word@10.1.0.238:1433/master
        into postgresql://postgres:postgres@10.1.0.238:5433/nw
including only table names like 'staff' in schema 'dbo'

set work_mem to '16MB', maintenance_work_mem to '512 MB'

before load do $$ drop schema if exists dbo cascade;
 $$;

```

  - [ ] pgloader output you obtain
  
```
2022-06-24T13:38:01.020000Z LOG pgloader version "3.6.3~devel"
2022-06-24T13:38:01.243999Z LOG Migrating from #<SQLITE-CONNECTION sqlite:///pgloader-3.6.3/build/bin/mssql:/SA:Pass@word@10.1.0.238:1433/dbo.load {10077FCE13}>
2022-06-24T13:38:01.243999Z LOG Migrating into #<PGSQL-CONNECTION pgsql://postgres@10.1.0.238:4422/postgres {10077FD973}>
2022-06-24T13:38:01.271998Z ERROR sqlite: Failed to open sqlite file #P"/pgloader-3.6.3/build/bin/mssql:/SA:Pass@word@10.1.0.238:1433/dbo.load": Could not open sqlite3 database /pgloader-3.6.3/build/bin/mssql:/SA:Pass@word@10.1.0.238:1433/dbo.load
Code CANTOPEN: no message.
2022-06-24T13:38:01.271998Z LOG report summary reset
       table name     errors       rows      bytes      total time
-----------------  ---------  ---------  ---------  --------------
            fetch          0          0                     0.000s
      before load          0          1                     0.064s
  fetch meta data          0          0                     0.000s
-----------------  ---------  ---------  ---------  --------------
-----------------  ---------  ---------  ---------  --------------
```

Why that could be?

**Comment by dimitri** [comment]
It happens that the SQLite connection string is the default and when pgloader fails to parse other source kinds it ends up trying to parse the SQLite kind, which might work because everything and anything looks enough like a Unix filename, which is a byte array, basically.

So your problem seems to be that you need to escape the @ in the password field. Read the docs and then use @@ to include an indivual @ sign in there.
