### ISSUE TITLE
Issue with pgloader installation (lisp v.) on ubuntu server

### ISSUE THREAD

**Issue by zupan** [dimitri/pgloader#14]
After installing `sbcl`, `libmysqlclient-dev`, `libsqlite3-dev`, `quicklist` as stated in Readme.md file I came across error while trying to install pgloader using `make pgloader`.

Error from installation:

```
 make pgloader
sbcl --load ~/quicklisp/setup.lisp                             \
             --eval '(ql:quickload "pgloader")'                        \
             --eval '(quit)'
This is SBCL 1.0.55.0.debian, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
To load "pgloader":
  Load 1 ASDF system:
    pgloader
; Loading "pgloader"
........................
debugger invoked on a TYPE-ERROR in thread
#<THREAD "initial thread" RUNNING {1002999483}>:
  The value NIL is not of type STRING.

Type HELP for debugger help, or (SB-EXT:QUIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [TRY-RECOMPILING] Recompile params and try loading it again
  1: [RETRY          ] Retry
                       loading FASL for #<CL-SOURCE-FILE "pgloader" "src" "params">.
  2: [ACCEPT         ] Continue, treating
                       loading FASL for #<CL-SOURCE-FILE "pgloader" "src" "params">
                       as having been successful.
  3: [ABORT          ] Give up on "pgloader"
  4: [CONTINUE       ] Ignore runtime option --eval "(ql:quickload \"pgloader\")".
  5:                   Skip rest of --eval and --load options.
  6:                   Skip to toplevel READ/EVAL/PRINT loop.
  7: [QUIT           ] Quit SBCL (calling #'QUIT, killing the process).

(PARSE-INTEGER NIL)[:OPTIONAL]
0] 2
.
touch build/libs.stamp
touch: cannot touch `build/libs.stamp': No such file or directory
make: *** [build/libs.stamp] Error 1
```

Hope this helps in anyway.

**Comment by spaceblock** [comment]
not working

`Memory fault at (nil) (pc=0x901b337, sp=0xb75cfa90)
The integrity of this image is possibly compromised.
Continuing with fingers crossed.
CORRUPTION WARNING in SBCL pid 4710(tid 0xb7ca6700):
Memory fault at (nil) (pc=0x901b337, sp=0xb75cf450)
The integrity of this image is possibly compromised.
Continuing with fingers crossed.
CORRUPTION WARNING in SBCL pid 4710(tid 0xb7ca6700):
Memory fault at (nil) (pc=0x901b337, sp=0xb75cee10)
The integrity of this image is possibly compromised.
Continuing with fingers crossed.
fatal error encountered in SBCL pid 4710(tid 0xb7ca6700):
maximum interrupt nesting depth (1024) exceeded


Welcome to LDB, a low-level debugger for the Lisp runtime environment.
ldb> q
Really quit? [y]
Makefile:103: recipe for target 'build/libs.stamp' failed
make: *** [build/libs.stamp] Error 1`

I remove from Makefile option --compress-core
