### ISSUE TITLE
Provide alpine / apk packages

### ISSUE THREAD

**Issue by jflambert** [dimitri/pgloader#1401]
I would love to see `pgloader` available as an [Alpine Linux package](https://pkgs.alpinelinux.org/packages)

Currently we have to build it from source, which adds significant time to our pipeline.

I might look into [doing it myself](https://wiki.alpinelinux.org/wiki/Alpine_Linux:Contribute) down the line if the pgloader maintainers are not interested/available for this.

**Comment by dimitri** [comment]
It's best if the person that maintain the package for a specific distribution actually uses at least the distribution, or even better said package within the distribution. You seem to be the best candidate for that role! cheers

**Comment by jflambert** [comment]
It looks like there was an attempt to [provide pgloader as an alpine package](https://gitlab.alpinelinux.org/alpine/aports/-/issues/9560), but they might have given up on it due to some platform compatibility issues.

I'll deal with a couple minutes of build time for now...
