### ISSUE TITLE
Foreign key clauses (RESTRICT, CASCADE, etc) are not migrated from MySQL to Postgres

### ISSUE THREAD

**Issue by mtyson01** [dimitri/pgloader#141]
So when migrating a database from MySQL to Postgres I noticed that while foreign keys are being migrated, it looks like just a plain default key is created.  Any clauses such as 'ON DELETE CASCADE' are not migrated.

The following query demonstrates how to find the FK rules from the MySQL information_schema table.

    SELECT rc.table_name,rc.referenced_table_name, constraint_name,
        delete_rule, update_rule,
        GROUP_CONCAT(kcu.column_name SEPARATOR ', ') AS key_cols       
    FROM information_schema.referential_constraints rc
        JOIN information_schema.key_column_usage kcu
        USING(constraint_catalog, constraint_schema, constraint_name)
    WHERE rc.constraint_schema = 'database-name'
        AND rc.table_name = 'table-name'
    GROUP BY rc.constraint_catalog, rc.constraint_schema, rc.constraint_name

I've noticed that  the list-all-fkeys function in mysql-schema.lisp doesn't query the referential_constraints, so I'm guessing that pgloader doesn't attempt to fetch this information from MySQL?

**Comment by dimitri** [comment]
Thanks for providing the query, it made it much easier to integrate into the existing query I'm using for foreign keys, which is now getting on the complex side. I'm adding it here in case you would have an informed opinion as I lack that entirely when it comes to properly using MySQL:

```sql
    SELECT tc.table_name, tc.constraint_name, k.referenced_table_name ft,

           group_concat(         k.column_name
                        order by k.ordinal_position) as cols,

           group_concat(         k.referenced_column_name
                        order by k.position_in_unique_constraint) as fcols,

           rc.update_rule, rc.delete_rule

      FROM information_schema.table_constraints tc

           JOIN information_schema.referential_constraints rc
             ON rc.constraint_schema = tc.table_schema
            AND rc.constraint_name = tc.constraint_name
            AND rc.table_name = tc.table_name

      LEFT JOIN information_schema.key_column_usage k
             ON k.table_schema = tc.table_schema
            AND k.table_name = tc.table_name
            AND k.constraint_name = tc.constraint_name

    WHERE     tc.table_schema = '~a'
          AND k.referenced_table_schema = '~a'
          AND tc.constraint_type = 'FOREIGN KEY'
         ~:[~*~;and tc.table_name in (~{'~a'~^,~})~]
         ~:[~*~;and (~{tc.table_name ~a~^ or ~})~]
         ~:[~*~;and (~{tc.table_name ~a~^ and ~})~]

 GROUP BY tc.table_name, tc.constraint_name, ft
```

**Comment by mtyson01** [comment]
Thank you for adding this feature, Key migration is now working.

I'm not an expert when it comes to the INFORMATION_SCHEMA tables,  I mostly muddle around in there when I need to, but I don't have any special knowledge of it.

**Comment by klippx** [comment]
@dimitri Is there an option to turn this behaviour off?

```diff
ALTER TABLE bromma.transactions
  ADD CONSTRAINT transactions_account_id_fk FOREIGN KEY (account_id)
      REFERENCES bromma.accounts (id) MATCH SIMPLE
      REFERENCES bromma.accounts (id) MATCH SIMPLE
-      ON UPDATE RESTRICT ON DELETE RESTRICT;
+      ON UPDATE NO ACTION ON DELETE NO ACTION;
```

**Comment by dimitri** [comment]
Easiest way with current pgloader is to add the necessary SQL commands in an `AFTER LOAD` section, or using `--after` command line switch...

**Comment by klippx** [comment]
@dimitri Good idea, thank you very much!

**Comment by haisamido** [comment]
@dimitri I can't find instructions on how to use this fix,  i.e. FK CASCADING effects.  Where do I add it to the below loader configuration?

load database
     from      mysql://root:root@localhost:8889/FOO
     into postgresql://postgres:postgres@localhost:5432/FOO

 WITH include drop, create tables, no truncate,
      create indexes, reset sequences, foreign keys

 SET maintenance_work_mem to '128MB', work_mem to '12MB'

 CAST type datetime to timestamptz
                drop default drop not null using zero-dates-to-null,
      type date drop not null drop default using zero-dates-to-null;

**Comment by dimitri** [comment]
The `WITH` option you want here is `WITH foreign keys`, which is the default. Also note that the `CAST` rules you're listing here are now the default. I recommend you try again without a load command at all:

    pgloader --verbose mysql://root:root@localhost:8889/FOO postgresql://postgres:postgres@localhost:5432/FOO

And it should be caring about your foreign keys. You can try also with either `--debug` or `--client-min-messages info` so that you have the full information about what pgloader is doing, it might be that your MySQL source database doesn't list the foreign keys?

**Comment by haisamido** [comment]
@dimitri thank you for your reply

1) On mac os x I'm using pgloader (I downloaded) version "3.0.99" compiled with SBCL 1.1.17:

Foreign keys are created but without on UPDATE or on DELETE

2) On Centos 7 I compiled and using: pgloader version "3.3.64ab4d2" compiled with SBCL 1.2.8-1.el7:

Foreign keys are NOT created due to a mismatch between numeric and bigint.  It looks like my MySQL bigint is not always being mapped to bigint on psql.  Example is below

2016-01-29T15:44:50.561000Z ERROR Database error 42804: foreign key constraint "leap_times.leap_time_types.fk" cannot be implemented
DETAIL: Key columns "leap_time_type_id" and "leap_time_type_id" are of incompatible types: numeric and bigint.

**Comment by dimitri** [comment]
So, 3.0.99 is too old a version to consider.

About the bigint and numeric mismatch, that's because `bigint(20)` doesn't fit into a PostgreSQL `bigint` field (signed vs. unsigned, 20 digits are more than we can host in a signed 64 bits integer). Consider adding a cast rule for that:

    --cast "type bigint when (= 20 precision) to bigint"

**Comment by haisamido** [comment]
Thank you, but strangely, when I do:

`pgloader --verbose  --cast "type bigint when (= 20 precision) to bigint" mysql://root@localhost:3306/FOO postgresql://postgres:postgres@localhost:5432/FOO`

```
2016-02-02T16:43:54.428000Z ERROR Database error 42601: syntax error at or near "("
QUERY: CREATE TABLE astro_leap_times 
(
  start_date             varchar(20) not null,
  leap_time              float not null,
  leap_time_type_id      bigint(20) not null,
  leap_time_unit         varchar(64) default 's',
  inserted_date_time     timestamptz default CURRENT_TIMESTAMP,
  comments               text
);
```

**Comment by haisamido** [comment]
Silly me. This works. :-)

`pgloader --verbose --cast "type bigint(2) to bigint" mysql://root@localhost:3306/FOO postgresql://postgres:postgres@localhost:5432/FOO`

**Comment by haisamido** [comment]
Thank you @dimitri , but strangely, when I do:

`pgloader --verbose  --cast "type bigint when (= 20 precision) to bigint" mysql://root@localhost:3306/FOO postgresql://postgres:postgres@localhost:5432/FOO`

```
2016-02-02T16:43:54.428000Z ERROR Database error 42601: syntax error at or near "("
QUERY: CREATE TABLE astro_leap_times 
(
  start_date             varchar(20) not null,
  leap_time              float not null,
  leap_time_type_id      bigint(20) not null,
  leap_time_unit         varchar(64) default 's',
  inserted_date_time     timestamptz default CURRENT_TIMESTAMP,
  comments               text
);
```

**Comment by dimitri** [comment]
My fault, sorry about that, you need to tell pgloader that you don't want to keep the typemod in the new type definition:

    --cast "type bigint when (= 20 precision) to bigint drop typed"

**Comment by haisamido** [comment]
Thank you that worked with respect to bigint(20) and FK CASCADING effects; however, none of the auto-increments which were bigint(20) were transformed to SEQUENCE in psql!

**Comment by dimitri** [comment]
I guess the user provided `CAST` is shadowing the default ones. Could you give me an easy to reproduce example so that I see about fixing it?

**Comment by haisamido** [comment]
Sure. Here's a sample.

```
-- -----------------------------------------------------
-- Table `DAT`.`astro_leap_time_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DAT`.`astro_leap_time_types` (
  `leap_time_type_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '\n',
  `leap_time_type` VARCHAR(64) NOT NULL,
  `comments` TEXT NULL,
  PRIMARY KEY (`leap_time_type_id`),
  UNIQUE INDEX `type_UNIQUE` (`leap_time_type` ASC))
ENGINE = InnoDB
COMMENT = 'http://stjarnhimlen.se/comp/time.html';


-- -----------------------------------------------------
-- Table `DAT`.`astro_leap_times`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DAT`.`astro_leap_times` (
  `start_date` VARCHAR(20) NOT NULL COMMENT 'effective date of leap time in yyyy-mm-dd format\n',
  `leap_time` FLOAT NOT NULL COMMENT 'leap-time at startime',
  `leap_time_type_id` BIGINT NOT NULL,
  `leap_time_unit` VARCHAR(64) NULL DEFAULT 's' COMMENT 'unit of leap time, generally seconds (s). total leap time for leap_time and not only that year’s leap time',
  `inserted_date_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `comments` TEXT NULL,
  INDEX `fk.leap_times.leap_time_types.idx` (`leap_time_type_id` ASC),
  CONSTRAINT `leap_times.leap_time_types.fk`
    FOREIGN KEY (`leap_time_type_id`)
    REFERENCES `DAT`.`astro_leap_time_types` (`leap_time_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'http://stjarnhimlen.se/comp/time.html';
```

**Comment by dimitri** [comment]
I used exactly your self-contained test case (thanks!) here and failed to have any problem with it, given the following load file:

```
load database
  from mysql://root@localhost/astro
  into pgsql:///pgloader

  set search_path to 'astro'

 cast type bigint when (= 20 precision) to bigint drop typemod

 before load do
   $$ create schema if not exists astro; $$;
```

I then have the following PostgreSQL definitions:

```
\d astro.*
\d astro.*
          Table "astro.astro_leap_time_types"
      Column       |         Type          | Modifiers 
-------------------+-----------------------+-----------
 leap_time_type_id | bigint                | not null
 leap_time_type    | character varying(64) | not null
 comments          | text                  | 
Indexes:
    "idx_1413779_primary" PRIMARY KEY, btree (leap_time_type_id)
    "idx_1413779_type_unique" UNIQUE, btree (leap_time_type)
Referenced by:
    TABLE "astro.astro_leap_times" CONSTRAINT "leap_times.leap_time_types.fk" FOREIGN KEY (leap_time_type_id) REFERENCES astro.astro_leap_time_types(leap_time_type_id)

                         Table "astro.astro_leap_times"
       Column       |           Type           |           Modifiers            
--------------------+--------------------------+--------------------------------
 start_date         | character varying(20)    | not null
 leap_time          | double precision         | not null
 leap_time_type_id  | bigint                   | not null
 leap_time_unit     | character varying(64)    | default 's'::character varying
 inserted_date_time | timestamp with time zone | default now()
 comments           | text                     | 
Indexes:
    "idx_1413771_fk.leap_times.leap_time_types.idx" btree (leap_time_type_id)
Foreign-key constraints:
    "leap_times.leap_time_types.fk" FOREIGN KEY (leap_time_type_id) REFERENCES astro.astro_leap_time_types(leap_time_type_id)

Index "astro.idx_1413771_fk.leap_times.leap_time_types.idx"
      Column       |  Type  |    Definition     
-------------------+--------+-------------------
 leap_time_type_id | bigint | leap_time_type_id
btree, for table "astro.astro_leap_times"

       Index "astro.idx_1413779_primary"
      Column       |  Type  |    Definition     
-------------------+--------+-------------------
 leap_time_type_id | bigint | leap_time_type_id
primary key, btree, for table "astro.astro_leap_time_types"

          Index "astro.idx_1413779_type_unique"
     Column     |         Type          |   Definition   
----------------+-----------------------+----------------
 leap_time_type | character varying(64) | leap_time_type
unique, btree, for table "astro.astro_leap_time_types"
```

Can you see about your pgloader version and try with the current master's version?

**Comment by dimitri** [comment]
I could make it work with the following cast rules:

```
load database
  from mysql://root@localhost/astro
  into pgsql:///pgloader

  set search_path to 'astro'

 cast type bigint with extra auto_increment to bigserial drop typemod,
      type bigint when (= 20 precision) to bigint drop typemod

 before load do
   $$ create schema if not exists astro; $$;
```

Which gives:

```
# \d astro.astro_leap_time_types
                                                 Table "astro.astro_leap_time_types"
      Column       |         Type          |                                        Modifiers                                        
-------------------+-----------------------+-----------------------------------------------------------------------------------------
 leap_time_type_id | bigint                | not null default nextval('astro.astro_leap_time_types_leap_time_type_id_seq'::regclass)
 leap_time_type    | character varying(64) | not null
 comments          | text                  | 
Indexes:
    "idx_1413807_primary" PRIMARY KEY, btree (leap_time_type_id)
    "idx_1413807_type_unique" UNIQUE, btree (leap_time_type)
Referenced by:
    TABLE "astro.astro_leap_times" CONSTRAINT "leap_times.leap_time_types.fk" FOREIGN KEY (leap_time_type_id) REFERENCES astro.astro_leap_time_types(leap_time_type_id)

# \d astro.astro_leap_times
                         Table "astro.astro_leap_times"
       Column       |           Type           |           Modifiers            
--------------------+--------------------------+--------------------------------
 start_date         | character varying(20)    | not null
 leap_time          | double precision         | not null
 leap_time_type_id  | bigint                   | not null
 leap_time_unit     | character varying(64)    | default 's'::character varying
 inserted_date_time | timestamp with time zone | default now()
 comments           | text                     | 
Indexes:
    "idx_1413797_fk.leap_times.leap_time_types.idx" btree (leap_time_type_id)
Foreign-key constraints:
    "leap_times.leap_time_types.fk" FOREIGN KEY (leap_time_type_id) REFERENCES astro.astro_leap_time_types(leap_time_type_id)
```

**Comment by dimitri** [comment]
You should be good with just the one extra cast rule, that I still hesitate to provide as default because you could lose data (MySQL `bigint(20)` range does not fit into PostgreSQL `bigint` range).

**Comment by haisamido** [comment]
That worked! Thank you so much @dimitri .  Only thing that didn't get loaded are the views, which I didn't have before until now.  Do I need to provide any special arguments to pgloader to do that?  Should I start a new issue for that question?

I downloaded the latest pgloader code and compiled on CentOS 7.  So I have this version:

```
pgloader version "3.3.765bbb7"
compiled with SBCL 1.2.8-1.el7
```

and ran it with only this cast:

`--cast "type bigint when (= 20 precision) to bigint drop typemod"`

**Comment by dimitri** [comment]
Thanks for the feedback ;-) and yes, please open another issue for the view question.
