### ISSUE TITLE
Windows wordaround for FATAL error: URL "/pgsql/query-table-schema.sql" not found!

### ISSUE THREAD

**Issue by edgephart** [dimitri/pgloader#1418]
I used Cygwin64 on Windows 11 to build pgloader. When running it, pgloader reported:
FATAL error: URL "/pgsql/query-table-schema.sql" not found!

In src/util/queries.lisp I added a line to (defun sql (url)

(maphash #'(lambda (k v) (format t "~a => ~a~%" k v)) *fs*)

to display what was being put in the hash table that internally stores the .sql files in the binary. The result (for just the query-table-schema.sql but is the same for all of them) is:
/pgsql\sql\query-table-schema.sql => -- params: table-name (contents of the file omitted)

As you can see, the "key" contains backslashes (and also a sql node). When pgsql-schema.lisp looks for it, it uses:
 (sql "/pgsql/query-table-schema.sql")

In queries.lisp in pathname-to-url, changing "(uiop:native-namestring" to "(uiop:unix-namestring" works for me in the Windows environment. The same change from native-namestring to unix-namestring also appears to work in Linux.

I'm not sure what else might be affected by this change so I am asking what negative side-effects could result from this change.

  - [x] pgloader --version
C:\test>pgloader --version
pgloader version "3.6.1"
compiled with SBCL 2.2.3
    
  - [x] did you test a fresh compile from the source tree? Yes
    
  - [x] did you search for other similar issues? Yes, and found a few that ended with the "not found!" error.
    
  - [x] how can I reproduce the bug? Compile for Windows and execute pgloader (I used a small load file and command file).

**Comment by dimitri** [comment]
Hi @edgephart ; thanks for this analysis. I believe we should use unix-namestring as you're saying, because then we hard code the key of the hashtable to look like a unix namestring.
