### ISSUE TITLE
feature request:add build option for support different type of data source 

### ISSUE THREAD

**Issue by amutu** [dimitri/pgloader#142]
I recent compile pgloader on git head,the binary produced is 120MB,and I must install freetds,and unixODBC as compile and runtime depend etc.My production environment do not have connection to the outside world，so I must install the dependences manually.
I only load csv file using pgloader,so I think if pgloader can complie with only csv data source support,so the binary can be smaller,and there is fewer denpendences.

**Comment by dimitri** [comment]
It's a fair request. The binary can be compressed down to 20MB, and I will see how to make the external dependencies optional for when you don't need them.

**Comment by dimitri** [comment]
It should be ok now, without any need for build time options, it's all dynamic at run-time. Please test and report!
