### ISSUE TITLE
feature request:flag to make the format of summary machine readable

### ISSUE THREAD

**Issue by amutu** [dimitri/pgloader#144]
Now the output of the summary is like this：
                    table name       read   imported     errors            time
------------------------------  ---------  ---------  ---------  --------------
                         fetch          0          0          0          0.012s
------------------------------  ---------  ---------  ---------  --------------
       postgres_log_p_20150101        168        168          0          0.436s
------------------------------  ---------  ---------  ---------  --------------
             Total import time        168        168          0          0.448s

the format is nice for human,but not friendly for machine.For example,I want to import this summary info to database,I need parse this output.If the format change someday,I will change the parse program.

**Comment by dimitri** [comment]
We could have an option to output the summary in e.g. JSON, would that solve your problem here?

**Comment by amutu** [comment]
Yes,it will.

**Comment by dimitri** [comment]
It just occurred to me that machine readable could also mean create a summary table for the migration and insert summary lines there in a PostgreSQL table. Then surely you can machine process it anyway you want ;-)

**Comment by amutu** [comment]
I'd like to leave the summary to the sumary file,the reasons are:
1.Make pgloader simple.One tool do just work,I'd like pgloader load data fast and realiable ,this is the Unix philosophy.
2.pgloader do not know how user use the summary,and how to insert it to database.For example,in my env,I have many machine deploy pgloader,when insert the sumary to table,I will add hostname,load timestamp,target cvs file name etc.So it is difficult for make pgloader know all the use case and do all thing suitable.
3.insert direct to table may be failed,then the sumary info may be lost.

**Comment by dimitri** [comment]
Then best output format might actually be CSV or PostgreSQL COPY format, one that pgloader will have no problem processing. You will be able to add "static" columns in the pgloader command if you need, or just  process it anyway you want.

**Comment by amutu** [comment]
CSV,TSV,json...all ok for me.

**Comment by dimitri** [comment]
I couldn't decide, so I included several of them ;-)
