### ISSUE TITLE
If pgloader support global nullif?

### ISSUE THREAD

**Issue by amutu** [dimitri/pgloader#145]
I copy out a file from pg using:

```
\copy table_name to 'xx'
```

Then I use pgloader to load it,I find no doc about setting the null for the configure global.
From the doc,I find nullif can only be applied to a column.So if I have a table with many column,but I can't be sure which columns have null,then I need add nullif to all the columns?

the conf looks like this:

```
LOAD CSV
        from '/data/pgxc/xx/data/data_aa'
into postgresql://localhost:30004/foo?tb_ba_subscription_new
   WITH
        fields optionally enclosed by '"',
        fields terminated by '\t',
        fields escaped by double-quote
        fields null if '\N'------------this will be nice
```

**Comment by dimitri** [comment]
By default the PostgreSQL `\copy` format is not CSV unless you ask for it with the `WITH CSV` syntax. The best here would be to add a new format to pgloade, that would be names COPY. The good news is that the parsing is quite easy to do, and already done too: https://github.com/dimitri/pgloader/blob/master/src/pgsql/copy-format.lisp

It's just not *plugged-in* in the main command parser and known formats yet...

**Comment by amutu** [comment]
I think CSV in pgloader means TEXT in fact,so I use it load the copy data.
The full name of CSV is  Comma Separated Value,which fields terminated by ',',but in pgloader ,the LOAD CSV command can specifie separator ohter than comma. 
I will see the copy-format.
Thanks for your work! The pgloader is powerful.

**Comment by dimitri** [comment]
Well, CSV has quite a rich history, as related on wikipedia: http://en.wikipedia.org/wiki/Comma-separated_values reads *A comma-separated values (CSV) (also sometimes called character-separated values, because the separator character does not have to be a comma)*.

Anyhow, will add the `COPY` format support.

**Comment by dimitri** [comment]
Please try recompiling pgloader from current head and then with the following command:

```
LOAD COPY
        from '/data/pgxc/xx/data/data_aa'
into postgresql://localhost:30004/foo?tb_ba_subscription_new
```

Or even the following command line:

    ./build/bin/pgloader copy:///data/pgxc/xx/data/data_aa postgresql://localhost:30004/foo?tb_ba_subscription_new
