### ISSUE TITLE
Could not parse LOAD File Definition

### ISSUE THREAD

**Issue by alixaxel** [dimitri/pgloader#146]
I've a very simple trimmed-down load file definition:

```
LOAD DATABASE
	FROM sqlite:///var/www/localhost/app/database/sqlite.db
	INTO postgresql://root@localhost/postgres/
```

Running `pgloader sqlite.load` yields the following parse error:

```
$ pgloader sqlite.load
An unhandled error condition has been signalled:
   Could not parse subexpression ";" when parsing

 Expression PGLOADER.PARSER::COMMANDS
    Subexpression (+ PGLOADER.PARSER::COMMAND)
    Subexpression PGLOADER.PARSER::COMMAND
    Subexpression (AND
                   (OR PGLOADER.PARSER::LOAD-ARCHIVE
                       PGLOADER.PARSER::LOAD-CSV-FILE
                       PGLOADER.PARSER::LOAD-FIXED-COLS-FILE
                       PGLOADER.PARSER::LOAD-DBF-FILE
                       PGLOADER.PARSER::LOAD-IXF-FILE
                       PGLOADER.PARSER::LOAD-MYSQL-DATABASE
                       PGLOADER.PARSER::LOAD-SQLITE-DATABASE
                       PGLOADER.PARSER::LOAD-SYSLOG-MESSAGES)
                   PGLOADER.PARSER::END-OF-COMMAND)
    Subexpression PGLOADER.PARSER::END-OF-COMMAND
    Subexpression (AND PGLOADER.PARSER::IGNORE-WHITESPACE #\;
                       PGLOADER.PARSER::IGNORE-WHITESPACE)
    Subexpression ";"

  Encountered at:
    LOAD DATABASE
	FROM sqli
    ^ (Line 1, Column 0, Position 0)
```

I'm running the last precompiled binary for Linux 64. Anyone has any idea what's happening?

**Comment by dimitri** [comment]
Yeah, you're missing the ending semi-colon. It's needed because pgloader would accept several commands in the same .load file.

Now, if you want to compile from master's branch of wait until some time later when the next release is published, then you could do it all in a simple command line with no load file involved:

    pgloader sqlite:///var/www/localhost/app/database/sqlite.db postgresql://root@localhost/postgres/

**Comment by alixaxel** [comment]
@dimitri Yes, I also tried with the ending semicolon - just tried it again and I get the exact same parsing error. I also tried the verbatim [example on the website](http://pgloader.io/howto/sqlite.html) and I tried switching from `FROM DATABASE` to `FROM SQLite`, nothing seems to work. I was just wondering if I was doing something wrong.

Thanks for the tip, I will follow your suggestion when I get off work. :+1:

**Comment by dimitri** [comment]
Ah yes sorry went to fast in reading the sample text and the error message, you have a slash too many in your PostgreSQL connection string. Here's the proper format:

```
LOAD DATABASE
    FROM sqlite:///var/www/localhost/app/database/sqlite.db
    INTO postgresql://root@localhost/postgres;
```

**Comment by el3ment** [comment]
just an FYI -- i also came across the same (slightly misleading) error message, also caused by the same additional slash.

**Comment by shanereddy** [comment]
This worked for me, thank you.
