### ISSUE TITLE
MSSql Money Type - Value is not correct

### ISSUE THREAD

**Issue by drauber** [dimitri/pgloader#1494]
Hello!

Anyone can help me about how i can migrate from Microsoft Sql Server to Postgresql database columns of type money?

I have few rows with round problem.

SqlServer says:
7082761.6900
2951150.7100
1770690.4200

But, Postgresql 
  7082761.5
  2951150.8
  1770690.4

I have run 
`docker run --rm dimitri/pgloader:latest pgloader mssql://sa:xfdares@192.168.2.221/database postgresql://postgres:xfdares@172.19.45.191/teste_douglas`

I have tried with load file, and `cast
type money to "double precision" drop typemod;`

but, the result is the same.

**Comment by drauber** [comment]
Now it works

`docker run --rm  -v /home/douglas:/data dimitri/pgloader:latest pgloader --load-lisp-file /data/custom.lisp /data/pgloader.load `

[files.zip](https://github.com/dimitri/pgloader/files/11559925/files.zip)

Attached files.

**Comment by felipegouveiae** [comment]
@drauber you're a life saver. Thx so much.
