### ISSUE TITLE
Convert Timezone while migrating data from mysql to postgresql

### ISSUE THREAD

**Issue by nikitsaraf** [dimitri/pgloader#150]
I have the datetime columns in mysql database with an offset timezone of +05:30. When I am trying to transfer data to postgresql, the datetime gets converted to the GMT time i.e without the timezone.

Here is the relevant portion of the Load script :-
```
CAST type datetime to timestamptz  
                drop default drop not null using zero-dates-to-null,  
      type date drop not null drop default using zero-dates-to-null
```

How can I reformat the data to store the correct time with correct timezone in postgresl ?

**Comment by dimitri** [comment]
Can you show me some of the datetime entries as they get out from MySQL? It could just be that the parser is doing something wrong? A quick reading of the source code shows that the timestamp string being processed by pgloader typically won't have a TZ parts, in which case consider just adding:

    SET client_timezone TO '+05:30'

in your load command, that should be all you need if it applies uniformly to all your database timestamps.

**Comment by nikitsaraf** [comment]
Thanks @dimitri again !
Adding the SET statement in the load command worked !
