### ISSUE TITLE
continue mode

### ISSUE THREAD

**Issue by areski** [dimitri/pgloader#157]
This is a question not an issue, please close if it's not appropriate, thanks!

I was wondering if pgloader could be used several time over the same database (for instance SQlite) and reimport only the new records introduced since the last run.

To give a user case: I have several SQlite databases for analytic data and we try to aggregate all the data to a centralized PG for reporting.

**Comment by dimitri** [comment]
The more usual way to do that is to import into a "new" schema each time, and as soon as the data is available merge it thanks to SQL statements. In PostgreSQL the SQL to use in simplest cases is just `WITH new AS (DELETE FROM new RETUNING *) INSERT INTO target SELECT * FROM new`.

**Comment by rattrayalex** [comment]
Asking as someone who doesn't know very much about SQL, how fast/reliable would that one-liner be in copying over... everything? (assuming there are no schema changes between `new` and `target`, of course). 

My concern is about when it comes time to "flip the switch" from the old MSSQL db to the new PGSQL db, and not wanting to lose data / cause downtime when flipping from "the MSSQL codebase" to "the Postgres codebase". What would be the right plan of attack?

Would this sound reasonable?

1. Test that importing, new code, etc works on staging. 
1. Saturday night, run pgloader into pgdb A. Wait... how long for 150GB db?
1. The second it's complete, scramble to press the "deploy" button on the new code that reads from Postgres db. 
1. Run pgloader again, this time into pgdb B. 
1. Run the SQL statement you wrote above (or similar) to copy any missing rows from pgdb B to pgdb A. 
1. pgdb A should now have all data from the MSSQL db, plus any & all writes that occurred after it came live. 

The riskiness of this, I guess, depends on how long it takes for the code change to propagate (so writes to MSSQL stop immediately). Anything written between [pgloader stops running] and [postgres-interacting code comes live] would be lost. I guess what I'm really asking is, how can I mitigate that risk?

Sorry if this isn't the right forum for this sort of question... I imagine it's a common usecase for a tool like this, though, so if you have a good answer it might be worth sharing in the docs.

**Comment by dimitri** [comment]
I would rather just swallow a service unavailability just after a single pgloader run rather that the more complex scenario you're describing. Chances of anything going wrong raise exponentially with the number of steps in my experience...

**Comment by rattrayalex** [comment]
That's very sane advice =) probably what we'll do. Thanks Dmitri!
