### ISSUE TITLE
Unnable to use MSSQL as a source : 

### ISSUE THREAD

**Issue by loicdesguin** [dimitri/pgloader#1571]
Hello,

I try to use pgloader to migrate data from mssql to postgresql but I'm facing an issue with the configuration of the source

ERROR mssql: Failed to connect to mssql at "localhost" (port 59256) as user "sa": Connection to the database failed for an unknown reason.

There is not a lot of details in the log or in the console despite --debug and --verbose option.

from mssql://sa:password@localhost:59256/test

So my question, how to retrieve details about the error ?

Best Regards

Loïc

**Comment by ByZhouhang** [comment]
> Hello,
> 
> I try to use pgloader to migrate data from mssql to postgresql but I'm facing an issue with the configuration of the source
> 
> ERROR mssql: Failed to connect to mssql at "localhost" (port 59256) as user "sa": Connection to the database failed for an unknown reason.
> 
> There is not a lot of details in the log or in the console despite --debug and --verbose option.
> 
> from mssql://sa:password@localhost:59256/test
> 
> So my question, how to retrieve details about the error ?
> 
> Best Regards
> 
> Loïc

iI'm having the same issue, did you find a way to fix it?

**Comment by loicdesguin** [comment]
Hello, I had to define a source database in the /etc/freetds/freetds.conf file : I was not able to define the full configuration on the .load file.

**Comment by davidkeaveny** [comment]
> Hello, I had to define a source database in the /etc/freetds/freetds.conf file : I was not able to define the full configuration on the .load file.

Are you able to give a few more specifics how you were able to achieve that? e.g. what did you add to your `freetds.conf`
