### ISSUE TITLE
Error: There is no applicable method for the generic function

### ISSUE THREAD

**Issue by AdamFerguson** [dimitri/pgloader#158]
Thanks, looks like a great tool. I'm trying to export an mssql database over to postgres using this .load script:

```
load database
     from mssql://user:pass@host/db
     into postgresql://user@localhost:5433/db

set work_mem to '16MB', maintenance_work_mem to '512 MB'

before load do $$ drop schema if exists dbo cascade; $$;
```

Part of the way through the load it throws the following error:

```
   There is no applicable method for the generic function
     #<STANDARD-GENERIC-FUNCTION PGLOADER.PGSQL:FORMAT-PGSQL-CREATE-FKEY (1)>
   when called with arguments
     (("FK_dbo.Label_dbo.Label_ParentLabelId"
       . #S(PGLOADER.PGSQL::PGSQL-FKEY
            :NAME "FK_dbo.Label_dbo.Label_ParentLabelId"
            :TABLE-NAME "dbo.label"
            :COLUMNS ("ParentLabelId")
            :FOREIGN-TABLE "dbo.label"
            :FOREIGN-COLUMNS ("Id")
            :UPDATE-RULE NIL
            :DELETE-RULE NIL))).
```

The only thing that jumps out at me about this error is that it seems to be occurring when trying to create a foreign key for a table that references itself. That is `dbo.label` has a column `ParentLabelId` that is a foreign key to `dbo.label`. Could be there's a problem with that?

**Comment by dimitri** [comment]
Yeah apparently there's a bug in the way the foreign key internal API is being used from the MS SQL code parts. Will fix as soon as possible. Meanwhile, you may add `with no foreign keys` to bypass that step entirely, if you need to play with the data already.

**Comment by dimitri** [comment]
My MS SQL mini test case doesn't seem to involve actually working on fkeys and I'm too lazy to run the full test this evening. Still it looks like the very simple fix I just pushed should be what's needed here, please re-open the issue if it doesn't work for you.

**Comment by AdamFerguson** [comment]
Thanks for the quick fix! I confirmed it went through successfully with what's on master. Looking at the database that was created, I'm not sure the foreign keys were created (I didn't add `with no foreign keys` to the load file). That might be something else on my end though. The tables were created and the data was loaded which is all I need. Thanks! Great tool.

**Comment by AdamFerguson** [comment]
@dimitri Thought I should give you some more details on the foreign keys not being created. The postgres logs have a bunch of errors like this:

```
STATEMENT:  ALTER TABLE dbo.track ADD CONSTRAINT fk_dbo.track_dbo.artist_artistid FOREIGN KEY(artistid) REFERENCES dbo.artist(id)
ERROR:  syntax error at or near "." at character 59
```

**Comment by dimitri** [comment]
The problem seems to be all about keeping the MS SQL name for the FK constraint, which isn't compatible with PostgreSQL identifier spelling rules (because of dots usage, looks like a catalog.schema.name thing).

Do you know if the FK name was auto-generated that way by MS SQL or if you did name it against your own rules here? I will need to install a hack to "normalize" the contraint names, I'm thinking of splitting by dots and only keeping the last part.

**Comment by dimitri** [comment]
A (no that) quick search reveals nothing in matters of default contraint naming in SQL Server, let's just replace dots with underscores and see what happens. If possible for you, please confirm that given the latest referenced patch this issue is solved!

**Comment by AdamFerguson** [comment]
@dimitri Thanks again for the quick turnaround. Can I let you know on Monday? The sql server database is only accessible on the work network and I don't have VPN setup over there yet. 

I think the foreign keys were generated by Entity Framework, could be that's a naming convention with Entity Framework?

**Comment by dimitri** [comment]
Thanks for the extra information, let's see about that on Monday then ;-)

**Comment by AdamFerguson** [comment]
@dimitri I just ran a load again with what's on master. Didn't get the syntax error but it doesn't look like foreign keys were applied and when I look at the logs I see a lot of errors like this:

```
ERROR:  there is no unique constraint matching given keys for referenced table "publisher"
STATEMENT:  ALTER TABLE dbo.publisher ADD CONSTRAINT fk_dbo_publisher_dbo_publisher_parentpublisherid FOREIGN KEY(parentpublisherid) REFERENCES dbo.publisher(id)
```

Checking the schema that was created, it looks like the primary key on the tables (`dbo.publisher(id)` in this case) isn't being marked as the primary key in postgres. I confirmed it is marked as the primary key in SQL Server so seems like that information is being lost somewhere.

In case it's helpful, the DDL for that table in SQL Server ends up looking like this:

```SQL
-- ----------------------------
--  Table structure for Publisher
-- ----------------------------
IF EXISTS (SELECT * FROM sys.all_objects WHERE object_id = OBJECT_ID('[dbo].[Publisher]') AND type IN ('U'))
	DROP TABLE [dbo].[Publisher]
GO
CREATE TABLE [dbo].[Publisher] (
	[Id] int IDENTITY(1,1) NOT NULL,
	[Name] nvarchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ParentPublisherId] int NULL,
	[PerformanceRightsOrganizationId] int NULL,
	[Created] datetime NOT NULL,
	[CreatedById] int NOT NULL,
	[Updated] datetime NOT NULL,
	[UpdatedById] int NOT NULL
)
ON [PRIMARY]
GO


-- ----------------------------
--  Primary key structure for table Publisher
-- ----------------------------
ALTER TABLE [dbo].[Publisher] ADD
	CONSTRAINT [PK_dbo.Publisher] PRIMARY KEY CLUSTERED ([Id]) 
	WITH (PAD_INDEX = OFF,
		IGNORE_DUP_KEY = OFF,
		ALLOW_ROW_LOCKS = ON,
		ALLOW_PAGE_LOCKS = ON)
	ON [default]
GO

-- ----------------------------
--  Indexes structure for table Publisher
-- ----------------------------
CREATE NONCLUSTERED INDEX [IX_ParentPublisherId]
ON [dbo].[Publisher] ([ParentPublisherId] ASC)
WITH (PAD_INDEX = OFF,
	IGNORE_DUP_KEY = OFF,
	STATISTICS_NORECOMPUTE = OFF,
	SORT_IN_TEMPDB = OFF,
	ONLINE = OFF,
	ALLOW_ROW_LOCKS = ON,
	ALLOW_PAGE_LOCKS = ON)
ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_PerformanceRightsOrganizationId]
ON [dbo].[Publisher] ([PerformanceRightsOrganizationId] ASC)
WITH (PAD_INDEX = OFF,
	IGNORE_DUP_KEY = OFF,
	STATISTICS_NORECOMPUTE = OFF,
	SORT_IN_TEMPDB = OFF,
	ONLINE = OFF,
	ALLOW_ROW_LOCKS = ON,
	ALLOW_PAGE_LOCKS = ON)
ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_Publisher_Name]
ON [dbo].[Publisher] ([Name] ASC)
WITH (PAD_INDEX = OFF,
	IGNORE_DUP_KEY = OFF,
	STATISTICS_NORECOMPUTE = OFF,
	SORT_IN_TEMPDB = OFF,
	ONLINE = OFF,
	ALLOW_ROW_LOCKS = ON,
	ALLOW_PAGE_LOCKS = ON)
ON [PRIMARY]
GO

-- ----------------------------
--  Foreign keys structure for table Publisher
-- ----------------------------
ALTER TABLE [dbo].[Publisher] ADD
	CONSTRAINT [FK_dbo.Publisher_dbo.Publisher_ParentPublisherId] FOREIGN KEY ([ParentPublisherId]) REFERENCES [dbo].[Publisher] ([Id]) ON DELETE NO ACTION ON UPDATE NO ACTION,
	CONSTRAINT [FK_dbo.Publisher_dbo.PerformanceRightsOrganization_PerformanceRightsOrganizationId] FOREIGN KEY ([PerformanceRightsOrganizationId]) REFERENCES [dbo].[PerformanceRightsOrganization] ([Id]) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

-- ----------------------------
--  Options for table Publisher
-- ----------------------------
ALTER TABLE [dbo].[Publisher] SET (LOCK_ESCALATION = TABLE)
GO
DBCC CHECKIDENT ('[dbo].[Publisher]', RESEED, 100)
GO
```

**Comment by dimitri** [comment]
Here's the query used by pgloader to find about the primary keys. Can you try it on your schema a report your findings, in particular if the is_primary_key column is reported as the number `1` when the index is supporting a primary key?

```sql
    select schema_name(schema_id) as SchemaName,
           o.name as TableName,
           i.name as IndexName,
           co.[name] as ColumnName,
           i.is_unique,
           i.is_primary_key

    from sys.indexes i
         join sys.objects o on i.object_id = o.object_id
         join sys.index_columns ic on ic.object_id = i.object_id
             and ic.index_id = i.index_id
         join sys.columns co on co.object_id = i.object_id
             and co.column_id = ic.column_id

   where schema_name(schema_id) not in ('dto', 'sys')

order by SchemaName,
         o.[name],
         i.[name],
         ic.is_included_column,
         ic.key_ordinal
```

When the index is primary, then pgloader runs the following two statements with placeholders taken care of:

    "CREATE UNIQUE INDEX ~a ON ~a (~{~a~^, ~});"
    "ALTER TABLE ~a ADD PRIMARY KEY USING INDEX ~a;"

The first statement are run in parallel to benefit from the `synchronize_seqscans` feature of PostgreSQL, and the second statement are run in series because `ALTER TABLE` prevents any parallelism here anyway. Only once that is done are the FKEY created. So something is fishy in your case I guess, either the SQL used against MS SQL or some parts of the logic I've just explained here...

**Comment by AdamFerguson** [comment]
Here are the results of that query when restricting `o.name = 'Publisher'`. The bottom row contains the primary key information. Just out of curiosity: the fact that the tables/columns in Sql Server contain capital letters that are lost during the conversion to postgresql wouldn't have an impact, would it?

Thanks for taking the time to look at this. The foreign key/primary key information isn't really important for my use case but I'll gladly continue reporting info if it's helpful for you.

```
SchemaName TableName IndexName ColumnName is_unique is_primary_key
dbo	Publisher	IX_ParentPublisherId	ParentPublisherId	0	0
dbo	Publisher	IX_PerformanceRightsOrganizationId	PerformanceRightsOrganizationId	0	0
dbo	Publisher	IX_Publisher_Name	Name	1	0
dbo	Publisher	PK_dbo.Publisher	Id	1	1
```

**Comment by dimitri** [comment]
I'd rather get down the bugs here while you're available if that's ok with you ;-)

So, let me guess, don't you have an error reported on the PostgreSQL side at the CREATE INDEX command for the `PK_dbo.Publisher` index name? I guess we need to replace dots with underscores in the index names too...

**Comment by AdamFerguson** [comment]
Ah, you're right! That was a little higher up in the logs:

```
ERROR:  syntax error at or near "." at character 71
STATEMENT:  ALTER TABLE dbo.publisher ADD PRIMARY KEY USING INDEX idx_32898_PK_dbo.Publisher;
```

**Comment by dimitri** [comment]
Once again it only got a quick test case, you know the drill...

**Comment by AdamFerguson** [comment]
Success! Both the primary and foreign keys were moved over. Thanks so much!

**Comment by dimitri** [comment]
Awesome, another bug report closed ;-) Thanks for your help testing all that.
