### ISSUE TITLE
Default values on bit fields in MS Sql Server

### ISSUE THREAD

**Issue by AdamFerguson** [dimitri/pgloader#162]
When loading from sql server, bit fields are converted to boolean values. But, it errors out if there are default values set for the bit fields. As an example, the following table has several default values of `((0))` (which is the way sql server formats default values for bit fields):

```
CREATE TABLE [dbo].[Track] (
	[Id] int IDENTITY(1,1) NOT NULL,
	[Title] nvarchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[IsQualityChecked] bit NOT NULL DEFAULT ((0)),
	[IsInstrumental] bit NOT NULL DEFAULT ((0)),
	[IsRemaster] bit NOT NULL DEFAULT ((0)),
	[Created] datetime NOT NULL,
	[CreatedById] int NOT NULL,
	[Updated] datetime NOT NULL,
	[UpdatedById] int NOT NULL,
	[AvailableToMgp] bit NOT NULL DEFAULT ((0)),
	[AvailableToWell] bit NOT NULL DEFAULT ((0)),
	[AvailableToStudio] bit NOT NULL DEFAULT ((0))
)
```

**Comment by dimitri** [comment]
I can't seem to be able to create the table with this definition of it, neither with the `((0))`` replace by `0` or `'0'`. Baring that, I could try a blind fix if you give me detailed error messages of the failure.

**Comment by AdamFerguson** [comment]
Apologies for the delay. Below is the error message I'm seeing when trying to run the load. I've looked at the table design in a few different sql server clients and it does seem that's how sql server saves and reports the default value '((0))' for bit fields.

```
2015-02-02T13:41:41.503000-05:00 WARNING Postgres warning: table "release" does not exist, skipping
2015-02-02T13:41:41.504000-05:00 ERROR Database error 22P02: invalid input syntax for type boolean: "((0))"
QUERY: CREATE TABLE release
(
  id                     bigserial not null,
  title                  text not null,
  displaytitle           text,
  artistid               int,
  created                timestamptz not null,
  createdbyid            int not null,
  updated                timestamptz not null,
  updatedbyid            int not null,
  isrerelease            boolean not null default '((0))'
);
2015-02-02T13:41:41.504000-05:00 FATAL Failed to create the schema, see above.
```

**Comment by dimitri** [comment]
Still failed to create a local test-case, please try the attached blind-patch and report. In case of any problem, please give me logs output at the `data` level (using `--verbose` and  `--debug` command line switches).

**Comment by AdamFerguson** [comment]
Sorry for the delay. Just tried a sample run and confirmed the fix worked as expected. Thanks!
