### ISSUE TITLE
Can't load into table named after reserved word

### ISSUE THREAD

**Issue by talos** [dimitri/pgloader#163]
There should be some sort of quoting done on the table load.  If you try to load into a table named "references", for example, you will receive the error:

```
ERROR:  syntax error at or near "references" at character 7
```

This was received using a `pgloader.load` that looked like this:

```
LOAD CSV FROM stdin
    INTO postgresql://postgres@localhost/postgres?references
    WITH skip header = 1,
         fields terminated by ',';
```

Perhaps there's a way to escape the tablename in the `INTO` that I'm not aware of?

**Comment by dimitri** [comment]
Thanks for the report, it failed to think about that use case when importing from files, although it's already taken care of when auto-discovering a schema from a database connection source. Should be ok now if you build pgloader with the fix, using that input file:

```
LOAD CSV FROM stdin
    INTO postgresql://postgres@localhost/postgres?"references"
    WITH skip header = 1,
         fields terminated by ',';
```

**Comment by talos** [comment]
:+1: Thanks for the quick response! Great project.

**Comment by nikbora** [comment]
Hey guys, I still get this error when using 'group' as table name:

```
LOAD CSV
  FROM './groups.csv'
  INTO postgresql:///pgloader?"group"

WITH csv header, fields terminated by ',';
```

```
ERROR Database error 42601: syntax error at or near "group"
ERROR Database error 42601: syntax error at or near "group"
```
Any suggestions?

**Comment by dimitri** [comment]
Can you please provide more logs (see `--debug` option)?

**Comment by nikbora** [comment]
Hey @dimitri, attached below. Thanks for helping.

```
WARNING Target table "group" has 3 indexes defined against it.
WARNING That could impact loading performance badly.
WARNING Consider the option 'drop indexes'.
INFO COPY "group"
DEBUG Reader started for group
DEBUG Transformer in action for group!
INFO Open #P"..."
DEBUG Parsed header columns (...)
DEBUG CONNECTED TO #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://... {1008ABFBE3}>
INFO pgsql:copy-from-queue[3]: group ("updated" ...)
DEBUG CONNECTED TO #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://... {1008ACC893}>
INFO pgsql:copy-from-queue[0]: group ("updated" ...)
DEBUG finish-current-batch[1] 1256 rows in 0.045000s
INFO Reader for group is done in 0.045000s
DEBUG format-data-to-copy[2] 1256 row in 0.010000s
INFO Transformer for group is done in 0.083000s
DEBUG Writer[3] for group is done in 0.000000s
DEBUG BEGIN
ERROR Database error 42601: syntax error at or near "group"
ERROR Database error 42601: syntax error at or near "group"
```

**Comment by dimitri** [comment]
That regression was quite more subtle and insidious that I would like to admit, but I think I got to the bottom of it in the referenced patch. Please compile and test again, and consider reporting success or failure, thanks!

**Comment by nikbora** [comment]
Hey @dimitri, I can confirm your fix works with latest change. Many thanks and a thousand kudos going your way :) (I should really learn some Lisp to do this myself next time!)
