### ISSUE TITLE
Building on W7 64

### ISSUE THREAD

**Issue by juancentro** [dimitri/pgloader#164]
Hi, I'm on Windows 7 64 bits, using 64 bits Postgre 9.3.2. I don't see a installer for Windows 32 bits. I can of course run the 32 bits version, but will it play nicely with my 64 bits Postgre? Or should I build for 64?

**Comment by dimitri** [comment]
It should play well with your 64 bits PostgreSQL as it's only using it from a normal client connection, and you can connect from a 32 bits client to a 64 bits server. Also pgloader is currently using the PostgreSQL TEXT protocol, not the binary one.

Please report your findings!

**Comment by dimitri** [comment]
Closing the issue for lack of feedback, if you have any news please open again.
