### ISSUE TITLE
Add an options to choose which tables to copy first

### ISSUE THREAD

**Issue by daltonmatos** [dimitri/pgloader#167]
Hello,

Recently I migrated a Django app from MySQL to PgSQL and one of the problems that I had was with tables that have foreign keys constraints and are imported in the wrong order. I think this happens because the import process follows an alphabetical order, maybe.

My specific problem was with two tables: ``auth_user`` and ``auth_permission``. ``auth_permission`` is imported first, but depends on data that must exist in ``auth_user``. So What I did was to first import ``auth_user`` (using ``INCLUDING ONLY TABLE NAMES MATCHING``) an then I imported ``auth_permission`` (using ``EXCLUDING TABLE NAMES MATCHING 'auth_user'``).

Does it make sense to add such an option? Or did I miss some part of the documentation?

Thanks for the great tool! =D

**Comment by dimitri** [comment]
The right way to address that problem usually is to split the schema definitions into pre- and post- data sections, and only install the indexes and constraints (including fkeys) in the post- section. That's what pgloader does in the normal case.

My guess is that you let the django app create the PostgreSQL schema for you then used pgloader with the *data only* option, in which case the fkey order might have to be taken into considerations yes. I will see about that.

**Comment by daltonmatos** [comment]
Indeed I tried the ``data only`` option.

When I let django create the tables (and it creates some data also) I had a duplicate key problem, which is expected. After this problem with the ``data only`` options and the duplicate keys I created a empty database and let pgloader create all tables an data for me. That's was when it worked, only with the "table order problem".

Here is the command file that I used:

````
load database  
     from      mysql://<user>:<pwd>@<host>/<db>
     into      postgresql://<user>:<pwd>@<host>/<db>
 
 WITH include no drop, create tables, no truncate,  
      create indexes, reset sequences, foreign keys
 
  SET maintenance_work_mem to '128MB', work_mem to '12MB'
 
 CAST type datetime to timestamptz  
                drop default drop not null using zero-dates-to-null,  
      type date drop not null drop default using zero-dates-to-null  

 -- INCLUDING ONLY TABLE NAMES MATCHING 'auth_user', 'auth_permission'
 -- INCLUDING ONLY TABLE NAMES MATCHING 'django_content_type'
 -- EXCLUDING TABLE NAMES MATCHING 'auth_user', 'django_content_type', 'auth_permission'
; 
````

First I imported ``django_content_type``, then ``auth_user`` and ``auth_permission`` and then all the rest (using the ``EXCLUDE`` option). Does this command file would make pgloader behave doing the pre-/post- schema splitting solution?

**Comment by dimitri** [comment]
Can you paste the two tables definitions including the fkey constraints? My current guesses are that either the target database wasn't actually empty when you used pgloader against it, or that the foreign keys definition themselves should obey some ordering that I didn't pay attention to.

**Comment by daltonmatos** [comment]
Looking at the create tables, now I see that the dependency is on ``django_content_type`` and not ``auth_user``.

I just restored a mysql backup from Feb/02 and did the migration again (locally) and it worked. I think you are right, at somepoint when I was still experimenting with pgloader I may have left some data on the destination database.

but if you think that this "table order" option makes sense, would be great to have it included. Also I have another database do migrate soon and I will pay more attention to this, and if this migration goes well there's also another one (our main production dabatase) to be migrated.

Anyway, thanks a lot for your attention and for this great tool!

Here are the create tables:
````sql
CREATE TABLE `django_content_type` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `app_label` varchar(100) NOT NULL,
  `model` varchar(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `django_content_type_app_label_45f3b1d93ec8c61c_uniq` (`app_label`,`model`)
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=latin1


CREATE TABLE `auth_user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `password` varchar(128) NOT NULL,
  `last_login` datetime NOT NULL,
  `is_superuser` tinyint(1) NOT NULL,
  `username` varchar(30) NOT NULL,
  `first_name` varchar(30) NOT NULL,
  `last_name` varchar(30) NOT NULL,
  `email` varchar(75) NOT NULL,
  `is_staff` tinyint(1) NOT NULL,
  `is_active` tinyint(1) NOT NULL,
  `date_joined` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=latin1




CREATE TABLE `auth_permission` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `content_type_id` int(11) NOT NULL,
  `codename` varchar(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `content_type_id` (`content_type_id`,`codename`),
  KEY `auth_permission_417f1b1c` (`content_type_id`),
  CONSTRAINT `auth__content_type_id_508cf46651277a81_fk_django_content_type_id` FOREIGN KEY (`content_type_id`) REFERENCES `django_content_type` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=55 DEFAULT CHARSET=latin1
````

**Comment by dimitri** [comment]
Loading the data in the right order in case of *data only* migrations make sense in as so much as you don't have a choice of splitting the schema into pre and post data sections, which might be the case with your usual ORM, I don't know enough about that to make the cut here. Will look at how complex that would be, I don't believe it's hard at all baring cyclic dependencies in which case data *has* to be loaded without the contraint holding.

Saying that, the other way to do it is to disable the triggers while the load takes place and enable them again at the end of the load, maybe offering automated validation of fkeys too.

**Comment by dimitri** [comment]
Please consider trying the new option `disable triggers` with your use case and reporting back. It should just work, at the cost of not validating the foreign key constraints for existing data.
