### ISSUE TITLE
Can not connect to MySQL if there is a dot in the user name

### ISSUE THREAD

**Issue by pinaraf** [dimitri/pgloader#168]
Hi

I'm trying to connect as user firstname.lastname to a mysql database, but pgloader does not recognize the mysql connection string and try to parse it as a sqlite file path :

   Failed to open sqlite file #P"/home/pinaraf/mysql:/firstname.lastname:XXYYXXYY@1.2.3.4:5678 paiement.load": Could not open sqlite3 database /home/pinaraf/mysql:/firstname.lastname:XXYYXXYY@1.2.3.4:5678/paiement.load

It seems to be a regression from previous older pgloader3 releases where this was not crashing.
I've fixed the issue, pushing a merge request in a few secs…

**Comment by dimitri** [comment]
Closing, should be good now.
