### ISSUE TITLE
Windows domain for mssql 

### ISSUE THREAD

**Issue by svennek** [dimitri/pgloader#171]
When using MSSQL, it is sometimes necessary to enter "windows domain".

Usual ways are either DOMAIN\\USERNAME  (double backslash notation) or USERNAME@DOMAIN (at-notation - both in the username part), neither seems to work with pgloader. 

Some systems (JDBC based) have it as an extra option out of band (in relation to the username).

Being able to enter a domain is critical.

**Comment by dimitri** [comment]
Did you try doubling the @ sign to escape it?

**Comment by svennek** [comment]
I just did :)

Doubling the @-sign doesn't work... and the backslash notation doesn't work either (tested with 1-6 backslashes in a row)

**Comment by dimitri** [comment]
It should work now, please build and try again either with a backslash or a doubled at-sign.

**Comment by dimitri** [comment]
Did you have the opportunity to try the patch?
