### ISSUE TITLE
Unhandled Memory fault at #x0

### ISSUE THREAD

**Issue by robins** [dimitri/pgloader#172]
- Am trying to copy a set of tables from MSSQL->PG
- Was unable to find this error in issues so raising one. Feel free to redirect.
- Just compiled SBCL (tar downloaded from sf) & gloader from Git
- This is a CentOS 6.6 running within a VMPlayer (6.0.0 build-1295980).
- Was able to run "SELECT 1;" from tsql (but with password, not sure if that could cause this)
- Am able to login to pg via psql as well (but with -U)
- When compiling SBCL, had run its test-suite (sh ./run-tests.sh) and it was successful.

Have tried to provide all that I think could help you in isolating this issue, but feel free to recommend if I need to try anything else, I could get back tomorrow my-time. Thanks

```
[robins@localhost pgloader]$ ./src/build/bin/pgloader --version
pgloader version "3.2.3c1f18f"
compiled with SBCL 1.2.8
```

```
[robins@localhost pgloader]$ ./src/build/bin/pgloader fmpdata.load 
2015-02-10T19:32:14.047000+05:30 LOG Main logs in '/tmp/pgloader/pgloader.log'
2015-02-10T19:32:14.051000+05:30 LOG Data errors in '/tmp/pgloader/'
2015-02-10T19:32:14.051000+05:30 LOG Parsing commands from file #P"/home/robins/projects/pgloader/fmpdata.load"
CORRUPTION WARNING in SBCL pid 36141(tid 140737354065664):
Memory fault at (nil) (pc=0x333c73357f, sp=0x7fffe1d0ec18)
The integrity of this image is possibly compromised.
Continuing with fingers crossed.
An unhandled error condition has been signalled:
   Failed to connect to mssql at "FMPDataIndia" (port 1433) as user "FMPDataUser": Unhandled memory fault at #x0.
```

```   
[robins@localhost pgloader]$ psql -h 192.168.112.92 -U rms
psql (9.3.6, server 9.2.9)
Type "help" for help.

rms=# \q
```

```
[robins@localhost pgloader]$ tsql -S FMPDataIndia -U FMPDataUser
Password: 
locale is "en_US.UTF-8"
locale charset is "UTF-8"
using default charset "UTF-8"
1> select 1;
2> go

1
(1 row affected)
1> ^C
[robins@localhost pgloader]$ 
```

```
[robins@localhost pgloader]$ cat fmpdata.load 
load database  
     from      mssql://FMPDataUser@FMPDataIndia/FMPData  
     into postgresql://rms@192.168.112.92/rt_testing
 
 WITH include drop, create tables, no truncate,  
      create indexes, reset sequences, foreign keys  

  SET maintenance_work_mem to '128MB', work_mem to '12MB';
 
[robins@localhost pgloader]$ 
```

**Comment by dimitri** [comment]
Can you try to run it with `--debug` so that we get maximum detail of information from the logs?

**Comment by robins** [comment]
[robins@localhost pgloader]$ ./src/build/bin/pgloader --debug fmpdata.load 
sb-impl::*default-external-format* :UTF-8
tmpdir: #P"/tmp/pgloader/"
2015-02-10T22:47:31.060000+05:30 NOTICE Starting pgloader, log system is ready.
2015-02-10T22:47:31.085000+05:30 INFO Starting monitor
2015-02-10T22:47:31.088000+05:30 LOG Main logs in '/tmp/pgloader/pgloader.log'
2015-02-10T22:47:31.088000+05:30 LOG Data errors in '/tmp/pgloader/'
2015-02-10T22:47:31.088000+05:30 LOG Parsing commands from file #P"/home/robins/projects/pgloader/fmpdata.load"
2015-02-10T22:47:31.089000+05:30 DEBUG CONNECT #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://rms@192.168.112.92:5432/rt_testing {1007B204A3}>
2015-02-10T22:47:31.089000+05:30 DEBUG SET maintenance_work_mem TO '128MB'
CORRUPTION WARNING in SBCL pid 36886(tid 140737354065664):
Memory fault at (nil) (pc=0x333c73357f, sp=0x7fffe1d0ec18)
The integrity of this image is possibly compromised.
Continuing with fingers crossed.
An unhandled error condition has been signalled:
   Failed to connect to mssql at "FMPDataIndia" (port 1433) as user "FMPDataUser": Unhandled memory fault at #x0.

Date/time: 2015-02-10-22:47An unhandled error condition has been signalled:
                              Failed to connect to mssql at "FMPDataIndia" (port 1433) as user "FMPDataUser": Unhandled memory fault at #x0.


Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {100773EC63}>
0: ((LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX))
1: (SB-IMPL::CALL-WITH-SANE-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX) {10088AFC8B}>)
2: (SB-IMPL::%WITH-STANDARD-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX) {10088AFC5B}>)
3: (PRINT-BACKTRACE :STREAM #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDOUT* {100027F203}> :START 0 :FROM :DEBUGGER-FRAME :COUNT 4611686018427387903 :PRINT-THREAD T :PRINT-FRAME-SOURCE NIL :METHOD-FRAME-STYLE NIL)
4: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE-TO-STREAM #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDOUT* {100027F203}>)
5: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE #<PGLOADER.CONNECTION:DB-CONNECTION-ERROR {10088A8FE3}> :OUTPUT #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDOUT* {100027F203}> :IF-EXISTS :APPEND :VERBOSE T)
6: (SIGNAL #<PGLOADER.CONNECTION:DB-CONNECTION-ERROR {10088A8FE3}>)
7: (ERROR PGLOADER.CONNECTION:DB-CONNECTION-ERROR :MESG "Unhandled memory fault at #x0." :TYPE "mssql" :HOST "FMPDataIndia" :PORT 1433 :USER "FMPDataUser")
8: (PGLOADER.MSSQL::FETCH-MSSQL-METADATA #<PGLOADER.MSSQL:COPY-MSSQL {1008728193}> :STATE #S(PGLOADER.UTILS::PGSTATE :TABLES #<HASH-TABLE :TEST EQUAL :COUNT 1 {1007C147E3}> :TABNAMES ("fetch meta data") :READ 0 :ROWS 0 :ERRS 0 :SECS 0.0) :INCLUDING NIL :EXCLUDING NIL)
9: ((:METHOD PGLOADER.SOURCES:COPY-DATABASE (PGLOADER.MSSQL:COPY-MSSQL)) #<PGLOADER.MSSQL:COPY-MSSQL {1008728193}> :STATE-BEFORE #S(PGLOADER.UTILS::PGSTATE :TABLES #<HASH-TABLE :TEST EQUAL :COUNT 1 {1007C147E3}> :TABNAMES ("fetch meta data") :READ 0 :ROWS 0 :ERRS 0 :SECS 0.0) :STATE-AFTER #S(PGLOADER.UTILS::PGSTATE :TABLES #<HASH-TABLE :TEST EQUAL :COUNT 0 {1007C15563}> :TABNAMES NIL :READ 0 :ROWS 0 :ERRS 0 :SECS 0.0) :STATE-INDEXES #S(PGLOADER.UTILS::PGSTATE :TABLES #<HASH-TABLE :TEST EQUAL :COUNT 0 {1007C150E3}> :TABNAMES NIL :READ 0 :ROWS 0 :ERRS 0 :SECS 0.0) :TRUNCATE NIL :DATA-ONLY NIL :SCHEMA-ONLY NIL :CREATE-TABLES T :INCLUDE-DROP T :CREATE-INDEXES T :RESET-SEQUENCES T :FOREIGN-KEYS T :ENCODING :UTF-8 :INCLUDING NIL :EXCLUDING NIL) [fast-method]
10: ((LAMBDA ()))
11: (PGLOADER:RUN-COMMANDS #P"/home/robins/projects/pgloader/fmpdata.load" :START-LOGGER NIL :SUMMARY NIL :LOG-FILENAME NIL :LOG-MIN-MESSAGES NIL :CLIENT-MIN-MESSAGES NIL)
12: (PGLOADER::PROCESS-COMMAND-FILE "fmpdata.load")
13: ((FLET #:CLEANUP-FUN-294 :IN PGLOADER::MAIN)) [cleanup]
14: (PGLOADER::MAIN ("./src/build/bin/pgloader" "--debug" "fmpdata.load"))
15: ((LAMBDA NIL :IN "/home/robins/projects/pgloader/src/dumper-2SKVI5f7.lisp"))
16: ((FLET #:WITHOUT-INTERRUPTS-BODY-87 :IN SAVE-LISP-AND-DIE))
17: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))


debugger invoked on a PGLOADER.CONNECTION:DB-CONNECTION-ERROR in thread
#<THREAD "main thread" RUNNING {100773EC63}>:
  Failed to connect to mssql at "FMPDataIndia" (port 1433) as user "FMPDataUser": Unhandled memory fault at #x0.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit application


debugger invoked on a TYPE-ERROR in thread
#<THREAD "main thread" RUNNING {100773EC63}>:
  The value INVOKE-DEBUGGER is not of type SB-DI:FRAME.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit application

(SB-DEBUG::FRAME-CALL INVOKE-DEBUGGER :METHOD-FRAME-STYLE :NORMAL :REPLACE-DYNAMIC-EXTENT-OBJECTS NIL)
0[2] 2015-02-10T22:47:32.014000+05:30 DEBUG SET work_mem TO '12MB'
2015-02-10T22:47:32.015000+05:30 FATAL We have a situation here.
0
[robins@localhost pgloader]$

**Comment by dimitri** [comment]
Looks like a problem with the freetds driver.

**Comment by robins** [comment]
First, thanks for looking into this promptly!

(Tried logging into office network from home, but am currently failing so can't revert with much at this point... but) Anything I could do to isolate / triage this for sure?

I mean as far as I remember, freetds has been on this vm (but probably unused) for a while, and the Freetds-devel install was a pure "yum install freetds-devel" with no errors, so I am not sure what could be wrong there... 

In the meanwhile, will try to reinstall freetds / freetds-devel but can't think of anything else right now.

**Comment by robins** [comment]
nothing much.
uninstalled / reinstalled both freetds and freetds-devel... didn't help.

**Comment by robins** [comment]
Spawned a completely segregated Ubuntu 64bit with a similar setup and encountering the same error. So I am in the black about what could be done.

A few other projects (for e.g. lparallel) have had such an error and then I doubt if this is a SBCL related issue (and not FreeTDS):

* https://github.com/lmj/lparallel/issues/2
* https://bugs.launchpad.net/sbcl/+bug/601576
* https://trac.macports.org/ticket/44228

**Comment by dimitri** [comment]
Could you try an older SBCL version?

**Comment by robins** [comment]
Sorry for the delay.

I tried with both 1.2.7 (one minor release back) and 1.1.18 (one major release back) and both failed with the same issue.

I have a fear that I might be doing something stupid (that I don't know) but looking at the LParallel issue URL above, is it possible that SBCL is basically bombing on an uncaught exception (i.e. if this is an induced error that just gets triggered in my scenario?)

Any more ideas are welcome. Thanks again.


[robins@localhost pgloader]$ src/build/bin/pgloader --version
pgloader version "3.2.48f451b"
compiled with SBCL 1.1.18
[robins@localhost pgloader]$ src/build/bin/pgloader fmpdata.load 
2015-02-20T10:18:36.047000+05:30 LOG Main logs in '/tmp/pgloader/pgloader.log'
2015-02-20T10:18:36.051000+05:30 LOG Data errors in '/tmp/pgloader/'
2015-02-20T10:18:36.051000+05:30 LOG Parsing commands from file #P"/home/robins/projects/pgloader/fmpdata.load"
CORRUPTION WARNING in SBCL pid 14322(tid 140737354061568):
Memory fault at 0 (pc=0x333c73357f, sp=0x7ffff1d0eff8)
The integrity of this image is possibly compromised.
Continuing with fingers crossed.
An unhandled error condition has been signalled:
   Failed to connect to mssql at "FMPDataIndia" (port 1433) as user "FMPDataUser": Unhandled memory fault at #x0.

[robins@localhost pgloader]$ cat /etc/redhat-release 
CentOS release 6.6 (Final)
[robins@localhost pgloader]$ uname -a
Linux localhost.localdomain 2.6.32-504.8.1.el6.x86_64 #1 SMP Wed Jan 28 21:11:36 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux



------


[robins@localhost pgloader]$ ./src/build/bin/pgloader fmpdata.load 
2015-02-20T10:00:32.048000+05:30 LOG Main logs in '/tmp/pgloader/pgloader.log'
2015-02-20T10:00:32.055000+05:30 LOG Data errors in '/tmp/pgloader/'
2015-02-20T10:00:32.055000+05:30 LOG Parsing commands from file #P"/home/robins/projects/pgloader/fmpdata.load"
CORRUPTION WARNING in SBCL pid 11559(tid 140737354061568):
Memory fault at (nil) (pc=0x333c73357f, sp=0x7fff71d0ecf8)
The integrity of this image is possibly compromised.
Continuing with fingers crossed.
An unhandled error condition has been signalled:
   Failed to connect to mssql at "FMPDataIndia" (port 1433) as user "FMPDataUser": Unhandled memory fault at #x0.

[robins@localhost pgloader]$ sbcl --version
SBCL 1.2.7
[robins@localhost pgloader]$ ./src/build/bin/pgloader --version
pgloader version "3.2.48f451b"
compiled with SBCL 1.2.7
[robins@localhost pgloader]$

**Comment by dimitri** [comment]
Closing this issue to clean-up the trail, and because lots have changed in the MS SQL support. Please try again with current pgloader sources if that issue is still relevant to you, and feel free to re-open as necessary.
