### ISSUE TITLE
Default auto_increment to SERIAL casting rules accidentally overridden.

### ISSUE THREAD

**Issue by mtyson01** [dimitri/pgloader#173]
I'm not sure if this is considered a bug as such, but it did confuse me so I thought I would get your opinion.   Essentially if I want to promote MySQL MEDIUMINT types to postgres INTEGER types, it runs the risk of overwriting the internal auto_increment to SERIAL cast rule.

Consider this MySQL table:

    +------------+--------------+------+-----+---------+----------------+
    | Field      | Type         | Null | Key | Default | Extra          |
    +------------+--------------+------+-----+---------+----------------+
    | id         | mediumint(9) | NO   | PRI | NULL    | auto_increment |
    | mediumdata | mediumint(9) | YES  |     | NULL    |                |
    +------------+--------------+------+-----+---------+----------------+

With the following pgloader config

    LOAD DATABASE
    FROM mysql://root@localhost/increment_test
    INTO postgresql://bugs@localhost/increment_test
    WITH include drop, create tables, no truncate,
         create indexes, reset sequences, foreign keys
    CAST
        type mediumint to integer drop typemod keep default keep not null;

Will result in this postgres table

          Table "public.medinc"
       Column   |  Type   | Modifiers 
    ------------+---------+-----------
     id         | integer | not null
     mediumdata | integer | 

Notice that the auto increment qualifier has been lost.  I'm assuming that since the casting rule specified in the config matches the auto increment column, then it is applied first and the internal 'cast to SERIAL' casting rule never fires.

However this casting rule gives the desired result.

    LOAD DATABASE
    FROM mysql://root@localhost/increment_test
    INTO postgresql://bugs@localhost/increment_test
    WITH include drop, create tables, no truncate,
         create indexes, reset sequences, foreign keys
    CAST
        type mediumint with extra auto_increment to serial drop typemod keep default keep not null
        type mediumint to integer drop typemod keep default keep not null;

       Column   |  Type   |                      Modifiers                      
    ------------+---------+-----------------------------------------------------
     id         | integer | not null default nextval('medinc_id_seq'::regclass)
     mediumdata | integer | 

I guess my question is, should the internal auto increment casting rules be so easy to overwrite?

I think this is a minor issue as it can be worked around, but it did surprise me.

**Comment by dimitri** [comment]
The current casting rules mechanism make it so that if a casting rule doesn't provide the `with extra auto_increment` matching, it matches both source data types with and without that *extra*. I think we should improve documentation about how the rules matching work in details, and maybe review this default behavior around the MySQL *extra* bit that is `auto_increment`.

Note that the default casting rules as described at https://github.com/dimitri/pgloader/blob/master/pgloader.1.md#default-mysql-casting-rules are doing exactly what you want here, I think. Did you have a problem with the default? Maybe we're missing the `drop typemod` in https://github.com/dimitri/pgloader/blob/master/src/sources/mysql/mysql-cast-rules.lisp#L60 as we have it in https://github.com/dimitri/pgloader/blob/master/src/sources/mysql/mysql-cast-rules.lisp#L75, right?

**Comment by mtyson01** [comment]
What I'm asking is if there's a way to promote MySQL MEDIUMINT to Postgres INTEGER without clobbering the built in auto_increment default rule.  (Unless I'm reading the docs wrong, I don't think there is)  This was more of a point of confusion rather than a serious issue.

EG, this is what I mean:

    type mediumint **without** extra auto_increment to serial

Maybe adding a caveat to the documentation about this would help.

Regarding the drop typemod, I've added that the rules as imports to failed without it, that might be a separate issue though.

**Comment by dimitri** [comment]
The default rules are what you're asking here:

```
    (:source (:type "mediumint" :auto-increment t) :target (:type "serial"))
    (:source (:type "mediumint") :target (:type "integer"  :drop-typemod t))
```

Did you try with no specific casting rules, only the default, and did it work for you?

My understanding now is that all we have here is a documentation problem, around the default cast rules and the matching machinery for providing your own when necessary.

**Comment by mtyson01** [comment]
Ah rats.

Sorry, I've gotten my wires crossed.
MySQL TINYINT and SMALLINT is (mostly) what I'm talking about.

I have a number of those in the MySQL database with auto incrementing primary keys.

With default casting rules, they appear in the postgres schema as SMALLINT types.

I want to promote everything that is less than an INTEGER to an INTEGER as the disk space saving for smaller types is insignificant compared to the extra schema complexity.

The MEDIUMINT losing its auto incrementing key is what I noticed first (They are common in my DB), but that also holds true for TINYINT and SMALLINT auto_increment types as well.

This is my full cast rule.  I cut it down for the sake of brevity, but I think I just caused confusion.

    CAST
    type datetime to timestamp drop default keep not null using zero-dates-to-null,
    type tinyint   with extra auto_increment to serial drop typemod keep default keep not null,
    type smallint  with extra auto_increment to serial drop typemod keep default keep not null,
    type mediumint with extra auto_increment to serial drop typemod keep default keep not null,
    type tinyint   to integer drop typemod keep default keep not null,
    type smallint  to integer drop typemod keep default keep not null,
    type mediumint to integer drop typemod keep default keep not null

The MEDIUMINT rules could be dropped as the default rules cover those cases.

Anyway,  As you say a documentation fix would be sufficient. Maybe a warning that if you cast TINYINT and SMALLINT to integers you need to consider if you have any auto_increment versions of those types.

Sorry for the confusion
Regards,
Matt.

**Comment by dimitri** [comment]
Thanks for that added level of details which makes it clear, documentation fixed.
