### ISSUE TITLE
possible to have restkey,restval like behaviour

### ISSUE THREAD

**Issue by moshir** [dimitri/pgloader#174]
Hi,

I'm getting trouble loading csv files, not because of pgloader but because extraction was not perfect.
Actually, some rows are missing some fields, so pgloader throws errors.
In python, the CsvDictReader class takes two nice parameters:
- restval : default value when field is missing (when there are less fields than expected)
- restkey a column where to put additional data (when there are more fields than expected)

Is it already possible with pgloader ? 
Otherwise, any interest in supporting this ?

**Comment by dimitri** [comment]
Yes, there's interest in supporting this. Early support is already included, as can be seen in https://github.com/dimitri/pgloader/blob/master/test/errors.load with the *trailing* column that is not imported.

Will see about adding support for extended *ragged* CSV input as we did already in the fixed case format, unless maybe you want to see about providing a patch for that feature?

**Comment by moshir** [comment]
Would be glad to, unfortunately, i'm not that good with Lisp !
By the way, did you ever take a look at python csvkit, feature complete toolkit to play with csv files, but very slow (*python oblige*).
If you ever decide to switch to node.js (who knows?), I'll be able to give a hand ;).

**Comment by dimitri** [comment]
Please provide a self-contained example of your failure case, as some cases are already handled just fine.

**Comment by dimitri** [comment]
Closing for lack of either test cases or use cases. Please re-open with some if you have them.
