### ISSUE TITLE
Unable to set table name with dbf file

### ISSUE THREAD

**Issue by elliotvr** [dimitri/pgloader#175]
Hi,

I'm trying to import a dbf file from the INSEE (cantons 2014) : 
http://www.insee.fr/fr/methodes/nomenclatures/cog/telechargement/2014/dbf/canton2014.dbf

But i would like to put the data in a specific schema and table (insee.cantons2014 e.g.)

Here is my load file : 

> LOAD DBF
  FROM  http://www.insee.fr/fr/methodes/nomenclatures/cog/telechargement/2014/dbf/canton2014.dbf
  INTO  postgresql://postgres@localhost/bdd
  WITH  no truncate,
        create table,
        table name = 'insee.cantons2014'
  SET   client_encoding TO 'utf8'
  BEFORE LOAD DO
        $$ create schema if not exists insee; $$
  ;

But when i import the load file, i think the dbf module don't really care about the table name option : 

> 2015-02-18T14:13:05.468000+01:00 NOTICE Create table "insee.cantons2014"
2015-02-18T14:13:05.468000+01:00 INFO DROP TABLE IF EXISTS canton2014;
2015-02-18T14:13:05.468000+01:00 INFO CREATE TABLE IF NOT EXISTS canton2014
(
  region                 text,
  dep                    text,
  ar                     text,
  canton                 text,
  typct                  text,
  cheflieu               text,
  tncc                   text,
  artmaj                 text,
  ncc                    text,
  artmin                 text,
  nccenr                 text
);
2015-02-18T14:13:05.468000+01:00 NOTICE COPY "insee.cantons2014" from 'canton2014'

He actually created the table **public.canton2014**, not **insee.cantons2014**.

I would gladly fix this but i'm not friendly with common lisp.

Regards,
Elliot.

**Comment by dimitri** [comment]
Should be ok with that patch, please build pgloader from sources to fix. I just realize the commit message is wrong when it references DSN tablename option, the DBF source being a simple filename here.

**Comment by elliotvr** [comment]
Wow fast.

> 2015-02-18T14:54:11.020000+01:00 LOG Main logs in '/private/tmp/pgloader/pgloader.log'
2015-02-18T14:54:11.023000+01:00 LOG Data errors in '/private/tmp/pgloader/'
2015-02-18T14:54:11.023000+01:00 LOG Parsing commands from file #P"/Users/elliotvr/git/BDD/Data/INSEE/CANTONS/cantons2014.load"
2015-02-18T14:54:11.024000+01:00 LOG Fetching 'http://www.insee.fr/fr/methodes/nomenclatures/cog/telechargement/2014/dbf/canton2014.dbf'
2015-02-18T14:54:12.235000+01:00 WARNING Postgres warning: table "cantons2014" does not exist, skipping
                    table name       read   imported     errors            time
------------------------------  ---------  ---------  ---------  --------------
                         fetch          0          0          0          1.299s
                   before load          1          1          0          0.012s
              create, truncate          0          0          0          0.046s
------------------------------  ---------  ---------  ---------  --------------
             insee.cantons2014          0       4055          0          0.185s
------------------------------  ---------  ---------  ---------  --------------
             Total import time          0       4055          0          1.542s

:-) Thx !
