### ISSUE TITLE
Max connections reached, increase value of TDS_MAX_CONN

### ISSUE THREAD

**Issue by victorkryukov** [dimitri/pgloader#177]
Hello Dimitri, and thanks for writing pgloader!

I'm trying to do a MSSQL migration, and after entering
```
pgloader mssql://user:password@host/db_name postgresql://victor@localhost/test-db
```
I'm getting:
```
2015-02-18T10:29:28.028000-08:00 LOG Main logs in '/private/tmp/pgloader/pgloader.log'
2015-02-18T10:29:28.031000-08:00 LOG Data errors in '/private/tmp/pgloader/'
Max connections reached, increase value of TDS_MAX_CONN
An unhandled error condition has been signalled: junk in string "NIL"
```

I'm on a Mac OS 10.10.2, and I compiled the latest pgloader myself after installing sbcl and freetds with brew as suggested by installation instructions.

Any ideas what might be going on?

**Comment by victorkryukov** [comment]
I'm have just tried using `bsqldb` utility supplied with freetds to see if my setup is working at all, and it seems to work fine, e.g. after
```
bsqldb -U user -P password -S host -D db_name
```
I can run queries against the MS SQL database.

**Comment by dimitri** [comment]
The message `increase value of TDS_MAX_CONN` seems to be harmless, we have it in all our tests. What I need to help you here is the output when using both `--verbose --debug` options on the command line, so that I see where the string "NIL" is actually coming from and failing to be processed.

**Comment by victorkryukov** [comment]
Here you are: https://gist.githubusercontent.com/victorkryukov/0b1edf324cc484916883/raw/gistfile1.txt. Please let me know once you finish working with this file, so that I can put the gist down - I tried to sanitize information there but I just want to make sure that nothing sensitive is being leaked.

**Comment by victorkryukov** [comment]
Looks like parsing integers, where it finds a "NIL", is given pgloader problems.

**Comment by dimitri** [comment]
I don't think I'm going to be able to do anything on that tonight, but I saved a local copy of your file already so that you can put it down.

**Comment by victorkryukov** [comment]
Thanks a lot Dimitri, both for willing to look into this and for such a quick response (not to mention your fantastic work on pgloader)!

**Comment by dimitri** [comment]
The culprit seems to be that your floats don't have a *scale* in the MS SQL type definition for the column, which confused the heck out of my very simple code. If that analysis is correct and baring other hidden bugs, you should be ok after a rebuild of pgloader.

The part of the trace that was useful to determine that is reproduced here:

```
11: (PGLOADER.SOURCES:CAST "agent_detailed_status" "total_time" "float" "float(53,NIL)" NIL "YES" NIL)
12: ((:METHOD PGLOADER.PGSQL:FORMAT-PGSQL-COLUMN (PGLOADER.MSSQL::MSSQL-COLUMN)) #S(PGLOADER.MSSQL::MSSQL-COLUMN :SCHEMA "dbo" :TABLE-NAME "agent_detailed_status" :NAME "total_time" :TYPE "float" :DEFAULT NIL :NULLABLE "YES" :IDENTITY NIL :CHARACTER-MAXIMUM-LENGTH NIL :NUMERIC-PRECISION 53 :NUMERIC-PRECISION-RADIX 2 :NUMERIC-SCALE NIL :DATETIME-PRECISION NIL :CHARACTER-SET-NAME NIL :COLLATION-NAME NIL)) [fast-method]
```

**Comment by victorkryukov** [comment]
Yes, I was reading through your code (man, it was a long time ago when I did SBCL) and noticed that `mssql-column-ctype` always bakes something of a form `XXX(precision,scale)`, while FLOATs in MSSQL don't have scale, and `parse-column-typemod` is indeed a bit simplistic in this regard - it didn't expect NIL, but then, MSSQL is a very weird beast and this is one of the reasons I'm moving over to MS SQL!

**Comment by victorkryukov** [comment]
I tried the latest version, and it still fails with the same error message - I think you've mixed up `if` clauses in your commit, and also should probably use `mssql-column-numeric-precision`, not `mssql-column-numeric-scale`, in your commit - but I don't see where `mssql-column-numeric-*` predicates are defined.

I've fixed it (will submit a patch shortly), and it now fails with a different error messages - will try to debug myself before I bother you again :).
