### ISSUE TITLE
MS SQL column names with spaces are not quoted properly

### ISSUE THREAD

**Issue by victorkryukov** [dimitri/pgloader#180]
I have a MS SQL table with the following definition:
```sql
CREATE TABLE case_addition (
	"Case Number" varchar(50),
	"Parent Name" varchar(50),
	"Account Name" varchar(50),
	"Account Number" varchar(50),
	"SFDC Account Id" varchar(50)
);
```
and when I am migrating this database, the migration fails at re-creating this table in PostgreSQL with the following error message:
```
2015-02-18T16:12:46.062000-08:00 INFO DROP TABLE IF EXISTS case_addition;
2015-02-18T16:12:46.062000-08:00 WARNING Postgres warning: table "case_addition" does not exist, skipping
2015-02-18T16:12:46.062000-08:00 INFO CREATE TABLE case_addition 
(
  ""Case Number""        text,
  ""Parent Name""        text,
  ""Account Name""       text,
  ""Account Number""     text,
  ""SFDC Account Id""    text
);
2015-02-18T16:12:46.062000-08:00 ERROR Database error 42601: zero-length delimited identifier at or near """"
QUERY: CREATE TABLE case_addition 
(
  ""Case Number""        text,
  ""Parent Name""        text,
  ""Account Name""       text,
  ""Account Number""     text,
  ""SFDC Account Id""    text
);
```

It's clear that pgloader is trying to quote columns which are already quoted, but I'm not that familiar with the source (yet) to find an exact place that needs to be fixed.

**Comment by victorkryukov** [comment]
Looks like it's `list-all-columns` in mssql-schema.lisp that is used to generate column definitions. When I manually run
```sql
select c.table_schema,
     c.table_name,
     c.column_name,
     c.data_type
     
from information_schema.columns c
     join information_schema.tables t
          on c.table_schema = t.table_schema
         and c.table_name = t.table_name

where c.table_schema = 'dbo' and c.table_name = 'case_addition'
```
I receive
```
table_schema table_name column_name data_type
dbo case_addition	"Case Number"	varchar
dbo	case_addition	"Parent Name"	varchar
dbo	case_addition	"Account Name"	varchar
dbo	case_addition	"Account Number"	varchar
dbo	case_addition	"SFDC Account Id"	varchar
```
i.e. the columns names are already quoted.

**Comment by victorkryukov** [comment]
Ok, I think I found the issue. 
```lisp
(defmethod format-pgsql-column ((col mssql-column))
```
unconditionally calls `apply-identifier-case`, which quotes everything that's not alpha-numeric, which clearly fails for the case above.

What constitutes an identifier in MS SQL is [complicated](https://msdn.microsoft.com/en-us/library/ms175874(v=sql.105).aspx); I'm not sure we can simply omit `apply-identifier-case` here.

**Comment by victorkryukov** [comment]
Please let me know whether approach I used in my commit is correct. It does seem to solve the problem for me - my MS SQL transition is underway!

**Comment by dimitri** [comment]
Thanks for your contribution, I cherry-picked your patch on top of current tree ;-)
