### ISSUE TITLE
Package for wheezy requires libc6 >= 2.14

### ISSUE THREAD

**Issue by txaj** [dimitri/pgloader#185]
I pulled the .deb from http://pgloader.io/files/pgloader_3.2.0+dfsg-1_amd64.deb linked from http://pgloader.io/download.html

```
# dpkg -i pgloader_3.2.0+dfsg-1_amd64.deb 
Selecting previously unselected package pgloader.
(Reading database ... 45221 files and directories currently installed.)
Unpacking pgloader (from pgloader_3.2.0+dfsg-1_amd64.deb) ...
dpkg: dependency problems prevent configuration of pgloader:
 pgloader depends on libc6 (>= 2.14); however:
  Version of libc6:amd64 on system is 2.13-38+deb7u8.

dpkg: error processing pgloader (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db ...
Errors were encountered while processing:
 pgloader
```

However the current version of libc6 for wheezy is 2.13-38+deb7u8 ( https://packages.debian.org/wheezy/libc6 )

was the package built on sid ? :-)

**Comment by dimitri** [comment]
Actually yes :( I need help for the release engineering...

**Comment by txaj** [comment]
unfortunately a lot of build-depends are not available on wheezy and I don't have the time to dig further for now...

**Comment by JamesChevalier** [comment]
I managed to get [v3.2.1 preview](https://github.com/dimitri/pgloader/releases/tag/v3.2.1.preview) installed onto Debian wheezy by taking these steps...

- `sudo nano /etc/apt.d/sources.list.d/jessie.list` and add the following content:

        deb ftp://ftp.debian.org/debian/ jessie main
        deb-src ftp://ftp.debian.org/debian/ jessie main
- `sudo nano /etc/apt/preferences.d/jessie` and add the following content:

        Package: *
        Pin: release a=wheezy
        Pin-Priority: 900

        Package: sbcl
        Pin: release a=jessie
        Pin-Priority: 910

        Package: cl-asdf
        Pin: release a=jessie
        Pin-Priority: 910
- `sudo apt-get update`
- `sudo apt-get install sbcl git curl patch unzip devscripts pandoc libsqlite3-dev freetds-dev cl-asdf`
- `wget https://github.com/dimitri/pgloader/archive/v3.2.1.preview.tar.gz`
- `tar -xzvf v3.2.1.preview.tar.gz`
- `cd pgloader-3.2.1.preview`
- `make pgloader`
- You can now run pgloader: `./build/bin/pgloader --help`

**Comment by dimitri** [comment]
I guess that I can close this issue now that jessie is the current stable. It comes with the right versions of the software we need here and with a pgloader package.
