### ISSUE TITLE
MySQL Schema A to Postgres Schema B

### ISSUE THREAD

**Issue by JavaTheHaute** [dimitri/pgloader#188]
I first apologize if this is not the proper arena for this communication. We are seeking a way/syntax to use pgloader to export from MySQL Schema A to Postgres Schema B. According to https://twitter.com/bestsql/status/448227294973538304 it is possible but the link in that tweet does not show the details.

The default syntax of pgloader appears to allow specification of the Postgres database name and imports the objects into the "public" schema. We are looking to import them into something other than "public" and a name different from the source schema, e.g. from schema "A" to schema "B". As a fallback we can import into public and then change the schema and owner of the objects but we're hoping there is a better way. Thank-you for your time.

**Comment by dimitri** [comment]
Hi, thanks for opening an issue here!

The schema mentioned in the tweet you reference is to read as *ddl* or *structure* of the database and refers to the *MATERIALIZING VIEWS* clause of pgloader.

Now you're not out of luck, see https://github.com/dimitri/pgloader/blob/master/test/sakila.load for a complete example where the `sakila` database content in MySQL is migrated over to a `sakila` schema in PostgreSQL, overriding the `public` default. The key here is the `SET search_path TO 'sakila'` part of the command file.

It's also possible to use `--set "search_path='foo'"` on the command line if you're not already using a command file and prefer that way of operation.

**Comment by JavaTheHaute** [comment]
Setting the search_path worked. Thanks so much for a great product and quick solution to our problem!
