### ISSUE TITLE
Exit with non-zero exit status on error

### ISSUE THREAD

**Issue by jdufresne** [dimitri/pgloader#190]
When `pgloader` fails to properly convert a MySQL database, the command line exit status is always 0. This makes it difficult to know if an error occurred or whether the database was correctly converted.

I'm using pgloader in a script to automate the conversion process. The script has been configured to abort early on the first error. However, since `pgloader` does not follow typical exit status conventions, the script continues and fails further down where the error is harder to diagnose.

Please consider changing the behavior to exit with a non-zero exit status on failure.

A simple example with an invalid command line argument:

```
$ /tmp/tmpzM5yRL/pgloader/build/bin/pgloader --asdfsadf
Undefined option --asdfsadf
...

$ echo $?
0
```

**Comment by dimitri** [comment]
Should be all good now, thanks for reporting the bug and sorry about the delay in fixing it.
