### ISSUE TITLE
How do I disable single cast?

### ISSUE THREAD

**Issue by sc0rp10** [dimitri/pgloader#198]
Hello.
I'm using pgloader for migrate existing database from mysql to postgres. I don't need convert tinyint to bool, but pgloader does it.
How can I disable only one cast "tinyint-to-boolean" and don't touch any other?
Thanks.

**Comment by dimitri** [comment]
If using command line only you can use the `--with` option and the `CAST` rule:

    pgloader --with `cast tinyint to smallint drop typemod` mysql://.. pgsql://...

**Comment by dimitri** [comment]
I suppose it's ok now, as not being commented further. If you still happen to have a problem here, please consider re-opening the issue with more details. Thanks.

**Comment by id-tarzanych** [comment]
Hello @dimitri ,

For me it doesn't work with load file, the only way to disable tinyint-to-boolean transformation was recompiling pgloader from source without this modification.

```
LOAD DATABASE
     FROM      mysql://...
     INTO postgresql://...

 WITH include drop, create tables, create indexes, reset sequences,
      workers = 8, concurrency = 1,
      multiple readers per thread, rows per range = 50000

  SET PostgreSQL PARAMETERS
      maintenance_work_mem to '4096MB',
      work_mem to '8192MB',
      search_path to 'public, "$user"'

  SET MySQL PARAMETERS
      net_read_timeout  = '120',
      net_write_timeout = '120'

CAST type tinyint when (= precision 1) to smallint drop typemod

INCLUDING ONLY TABLE NAMES MATCHING ~/^phpbb3_/;
```

What can you suggest with this case?

**Comment by dimitri** [comment]
Hi @id-tarzanych ; I will need more context / information. Can you show me the schema in MySQL, the load file (I guess you have sent it already, is that the one you're using?) and the schema in PostgreSQL? Also I need the version of pgloader you're using, and if you did any changes to the code, the `diff` that shows the changes.

**Comment by guetouille** [comment]
Hello Dimitri , seems doesnt works for me , i'm in a 3.6.7 version , and using this command :
pgloader --verbose --with "batch rows = 1000" --with "batch concurrency = 2" --with "cast tinyint to smallint drop typemod" 


2023-08-07T16:05:47.007999Z NOTICE Starting pgloader, log system is ready.
2023-08-07T16:05:47.015999Z LOG pgloader version "3.6.7~devel"
2023-08-07T16:05:47.015999Z ERROR Could not parse --with ("batch concurrency = 2"
                        "cast tinyint to smallint drop typemod"):
2023-08-07T16:05:47.019999Z ERROR At

  cast tinyint to smallint
  ^ (Line 1, Column 0, Position 0)

In context MYSQL-OPTION:
