### ISSUE TITLE
pgloader fails with password with a leading colon

### ISSUE THREAD

**Issue by jdufresne** [dimitri/pgloader#199]
The following password was randomly generated, which may contain a leading colon. Using the same password below without the leading colon works. If a password contains a leading colon, pgloader fails with the following message: 

```
An unhandled error condition has been signalled: At

  stgresql://development::jTkAwXF,%v/t*!brE:#U~^<@unix:/tm
                                  ^ (Line 1, Column 34, Position 34)

Could not parse DOUBLED-COLON. Expected:

  the string "::"

Reached via

     DOUBLED-COLON
  -> (AND "::")
  -> "::"

Could not parse DOUBLED-AT-SIGN. Expected:

  the string "@@"

Reached via

     DOUBLED-AT-SIGN
  -> (AND "@@")
  -> "@@"

Could not parse PUNCT. Expected:

     the character , (COMMA)
  or the character - (HYPHEN-MINUS)
  or the character _ (LOW_LINE)

Reached via

     PUNCT
  -> (OR "," "-" "_")

Could not parse DSN-USER-PASSWORD. Expected:

  the character @ (COMMERCIAL_AT)

Reached via

     DSN-USER-PASSWORD
  -> (AND USERNAME (? (AND ":" (? PASSWORD))) "@")
  -> "@"
```

The documentation makes no mention of how to handle passwords with a leading colon. It implies a leading colon is possible with the language "Can contain any character":

> password

> Can contain any character, including that at sign (@) which must then be doubled (@@). To leave the password empty, when the user name ends with at at sign, you then have to use the syntax user:@.

> When omitted, the password defaults to the value of the PGPASSWORD environment variable if it is set, otherwise the password is left unset.

**Comment by jdufresne** [comment]
> I don't see how to nicely handle passwords that begin with colon in the dburi

One idea, could you escape special characters (`:`, `@`, and '\') with a leading backslash? That way  `user\::pass` would be parsed as username `user:` and password `pass` while `user:\:pass` would be parsed as username `user` and password `:pass`. Escaping characters with a leading backslash is very common and I don't think it would be a big surprise to your users.

> can you filter them out from your random generator output

Yes. I have gone ahead and done this for my own application. This workaround solves the issue for me locally. I was simply reporting the issue as a courtesy. If you prefer to close this as won't fix, no problem. However, it might be worth at least documenting the issue for other users.

**Comment by jdufresne** [comment]
I suppose another idea would be to treat the dburi more like a real URI and percent-encode all the parts. So `:pass` would become `%3Apass`.

See <https://en.wikipedia.org/wiki/Percent-encoding> and <https://tools.ietf.org/html/rfc3986#section-2.1>

**Comment by dimitri** [comment]
I like the URI approach here but it has its own problems:

```
Parse error:URI "%3AjTkAwXF,%v/t*!brE:#U~^<" contains illegal character #\^ at position 24.
```

I guess I will see about adding some escaping yes.

**Comment by jdufresne** [comment]
If pgloader supported percent encoded URIs I would pass the whole portion as percent encoded, not just the `:` character.

```
$ python3 -c 'import urllib.parse; print(urllib.parse.quote(":jTkAwXF,%v/t*!brE:#U~^<"))'
%3AjTkAwXF%2C%25v/t%2A%21brE%3A%23U%7E%5E%3C
```

So, for the password above, I think the URI should be something like: 
```
postgresql://username:%3AjTkAwXF%2C%25v/t%2A%21brE%3A%23U%7E%5E%3C@...
```

**Comment by jdufresne** [comment]
I'm not too familiar with the various libraries of common LISP. However, a quick search reveals [cl-uri](https://common-lisp.net/project/cl-uri/). So maybe this library is already doing what you need to parse a URI? It claims to following the RFC 3986 and so should handle percent encoded components.

**Comment by dimitri** [comment]
Just had a look at the PostgreSQL connection strings format documented here: http://www.postgresql.org/docs/9.3/interactive/libpq-connect.html#LIBPQ-CONNSTRING and I think pgloader should just do the same thing here and allow for url-encoded (percent-encoded) parameters in the options part of the URI string. This will allow you to use '&password=jTkAwXF,%25v/t*!brE:#U~^<' (remember to percent-encode your % into %25 here).

Note that those extra parameters take precedence over other parts of the URI as in PostgreSQL.

**Comment by chrissound** [comment]
In what version was this fixed?

**Comment by dimitri** [comment]
If I'm reading https://github.com/dimitri/pgloader/commit/d1fce3728af99a60f40582b015e89a0f203d3961 right, 3.2.2 (and followings, so 3.4.1 released yesterday is good). Also you can escape colon by doubling it, or you can also use the `PGPASSWORD` environment variable to host your password.
