### ISSUE TITLE
downcase identifiers not working

### ISSUE THREAD

**Issue by kmzijadev** [dimitri/pgloader#200]
Ran conversion with these options:

WITH quote identifiers, downcase identifiers, include drop, create tables, no truncate, create indexes, reset sequences, foreign keys

And the resulting tables have uppercase column names in some places.

**Comment by dimitri** [comment]
You can either *quote* or *downcase* identifiers, you can' t do both. There's no error handling on providing both the options tho...

**Comment by kmzijadev** [comment]
That seems like a very odd limitation.

**Comment by dimitri** [comment]
How so? it's two different ways oh handling the identifiers, what is the behavior you would like to have?

**Comment by kmzijadev** [comment]
They both do different things which are not mutually exclusive.

`quote identifiers` allows lots of things in addition to mixed-case names--names which begin with numbers, for example, or names which contain odd characters (or spaces).

`downcase identifiers` simply lowercases names.

The two aren't entirely orthogonal, but there are lots of cases where one might want to lowercase all of one's identifiers, but also enquote them.

**Comment by dimitri** [comment]
In fact the idea behind *lowercase identifiers* is to ensure that you can use them directly in PostgreSQL without having to ever quote them...

**Comment by kmzijadev** [comment]
Except that downcasing is not guaranteed to result in Pg-safe identifiers; MySQL has different naming rules than Pg.

Either way, the interaction between the two is obvious and presumably extremely easy to implement.

**Comment by dimitri** [comment]
Here's the current code for lowercasing and quoting identifiers, where you will see that lowercasing actually does more than just lowercase (it could be argued that it's then a misnomer). Given what the current code actually implements the interaction between *quote* and *downcase* identifiers is anything but obvious to me. If you want to see anything done on that front, please define the behavior you are interested into, with examples.

```lisp
(defun quoted-p (s)
  "Return true if s is a double-quoted string"
  (and (eq (char s 0) #\")
       (eq (char s (- (length s) 1)) #\")))

(defun apply-identifier-case (identifier)
  "Return given IDENTIFIER with CASE handled to be PostgreSQL compatible."
  (let* ((lowercase-identifier (cl-ppcre:regex-replace-all
                                "[^a-zA-Z0-9.]" (string-downcase identifier) "_"))
         (*identifier-case*
          ;; we might need to force to :quote in some cases
          ;;
          ;; http://www.postgresql.org/docs/9.1/static/sql-syntax-lexical.html
          ;;
          ;; SQL identifiers and key words must begin with a letter (a-z, but
          ;; also letters with diacritical marks and non-Latin letters) or an
          ;; underscore (_).
          (cond ((quoted-p identifier)
                 :none)

                ((cl-ppcre:scan "^[^A-Za-z_]" identifier)
                 :quote)

                ((member lowercase-identifier *pgsql-reserved-keywords*
                         :test #'string=)
                 (progn
                   ;; we need to both downcase and quote here
                   (when (eq :downcase *identifier-case*)
                     (setf identifier lowercase-identifier))
                   :quote))

                ;; in other cases follow user directive
                (t *identifier-case*))))

    (ecase *identifier-case*
      (:downcase lowercase-identifier)
      (:quote    (format nil "\"~a\""
                         (cl-ppcre:regex-replace-all "\"" identifier "\"\"")))
      (:none     identifier))))
```

**Comment by kmzijadev** [comment]
It seems like a making it a fall-through would do the trick.

If downcasing is enabled, downcase; then compare to key words and other "must-quote" situations (table names in Pg can contain any non-null token, _including_ the double quote character), and enable quoting if it isn't already enabled, if necessary.

Then quote if the quote flag has been enabled by any means.

**Comment by dimitri** [comment]
Never got along to implement that, closing the issue here. Feel free to still come up with a patch if you have more interest to do it that I do.
