### ISSUE TITLE
MSSQL - Issue migrating uniqueidentifiers

### ISSUE THREAD

**Issue by renata-ssg** [dimitri/pgloader#204]
Hello, and thanks for the wonderful tool.

I am trying to migrate from a Microsoft SQL database, and am hitting issues with GUIDs.  Most of my tables have a PK column of type uniqueidentifier, and when I run pgloader I get the error message 'An unhandled error condition has been signalled: The value "(newid())" is not of type (OR NULL (VECTOR (UNSIGNED-BYTE 8) 16)).'

I was under the impression these would be automatically converted to uuids using the sql-server-uniqueidentifier-to-uuid transform as specified in the docs.  Is there something else I need to do?

Thanks much.

**Comment by dimitri** [comment]
It looks like your default value isn't handled as it's calling a MS SQL specific function to generate a new UUID. We could migrate without the default or with a `generate_uuid_v4()` function call for the new default, then depending on the `ossp-uuid` extension to be installed on the target server.

Meanwhile you could just unset the default value before using pgloader?

**Comment by renata-ssg** [comment]
Thanks, that's basically what I ended up doing.

**Comment by dimitri** [comment]
Ok, thanks for the feedback that the approach works. As soon as https://github.com/dimitri/pgloader/pull/210 finds its way in, I will then add a special case for the default value `newid()` maybe with an option towards using [uuid-ossp](http://www.postgresql.org/docs/9.4/interactive/uuid-ossp.html).
