### ISSUE TITLE
pgloader cannot read file

### ISSUE THREAD

**Issue by opoudel-iora** [dimitri/pgloader#205]
Getting following error

ERROR The value :WAITING-FOR-NEXT is not of the expected type (MEMBER :WAITING :COLLECTING-QUOTED :COLLECTING).

Not sure what is this mean.

**Comment by dimitri** [comment]
It's an error from the CSV parser lib that pgloader is using, cl-csv. Please run again in --debug mode and send the details.

**Comment by dimitri** [comment]
Closing for lack of details ever having been sent. Please consider opening again with enough details to fix.
