### ISSUE TITLE
MSSQL "((0))" "(0)" default values not working

### ISSUE THREAD

**Issue by luqelinux** [dimitri/pgloader#207]
Hi,

is it possible to workaround this?

```
An unhandled error condition has been signalled:
   The value "((0))" is not of type (OR NULL SINGLE-FLOAT DOUBLE-FLOAT).


Date/time: 2015-04-10-22:36An unhandled error condition has been signalled:
                              The value "((0))"
                              is not of type
                                (OR NULL SINGLE-FLOAT DOUBLE-FLOAT).


Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10073EE903}>
0: (PGLOADER.TRANSFORMS::FLOAT-TO-STRING "((0))") [tl,external]
1: (PGLOADER.SOURCES::FORMAT-PGSQL-DEFAULT-VALUE "((0))" PGLOADER.TRANSFORMS::FLOAT-TO-STRING)
2: (PGLOADER.SOURCES::FORMAT-PGSQL-TYPE (:TABLE-NAME "x" :COLUMN-NAME "y" :TYPE "decimal" :CTYPE "decimal(18,2)" :TYPEMOD (18 . 2) :DEFAULT "((0))" :NOT-NULL T :AUTO-INCREMENT NIL) (:TYPE "numeric") PGLOADER.TRANSFORMS::FLOAT-TO-STRING)
```

**Comment by dimitri** [comment]
This reminds me of the work we did at https://github.com/dimitri/pgloader/commit/7ccbb45763d17a99a252e400f98d1a6dec3dcb89 from the issue #162. I still would like to understand in which case does MS SQL register `((0))` as a default value and if there's a sane way not to get that from our catalog queries.

Here's the query we use to get the columns meta-data, maybe you know of a way to get a cleaner/easier value to deal with than what `information_schema.columns.column_default` outputs?

```sql
  select c.table_schema,
         c.table_name,
         c.column_name,
         c.data_type,
         c.column_default,
         c.is_nullable,
         COLUMNPROPERTY(object_id(c.table_name), c.column_name, 'IsIdentity'),
         c.CHARACTER_MAXIMUM_LENGTH,
         c.NUMERIC_PRECISION,
         c.NUMERIC_PRECISION_RADIX,
         c.NUMERIC_SCALE,
         c.DATETIME_PRECISION,
         c.CHARACTER_SET_NAME,
         c.COLLATION_NAME

    from information_schema.columns c
         join information_schema.tables t
              on c.table_schema = t.table_schema
             and c.table_name = t.table_name

   where     c.table_catalog = '~a'
         and t.table_type = '~a'
         ~:[~*~;and (~{~a~^~&~10t or ~})~]
         ~:[~*~;and (~{~a~^~&~10t and ~})~]

order by c.table_schema, c.table_name, c.ordinal_position
```

**Comment by luqelinux** [comment]
I have no MS SQL experience. 

Below link mentions sys.default_constraints table. It is supposed to be free from parentheses.
https://connect.microsoft.com/SQLServer/feedback/details/525491/sql-server-scripts-default-constraint-with-a-double-parentheses

Parentheses may be also striped with
replace(replace(c.column_default,'(',''),')','')

**Comment by luqelinux** [comment]
sys.default_constraints table also contains double parentheses. 
I've managed to strip parentheses in secure way with below modification:

 select c.table_schema,
         c.table_name,
         c.column_name,
         c.data_type,
         CASE
             WHEN c.column_default LIKE '((%' AND c.column_default LIKE '%))' THEN SUBSTRING(c.column_default,3,len(c.column_default)-4)
             WHEN c.column_default LIKE '(%' AND c.column_default LIKE '%)' THEN SUBSTRING(c.column_default,2,len(c.column_default)-2)
             ELSE c.column_default END,
         c.is_nullable,

It still did not fix the problem, but with modification of float-to-string function it worked  (see below). 


STRIPPED:

An unhandled error condition has been signalled:
   The value "0" is not of type (OR NULL SINGLE-FLOAT DOUBLE-FLOAT).

Date/time: 2015-04-13-12:02An unhandled error condition has been signalled:
                              The value "0"
                              is not of type
                                (OR NULL SINGLE-FLOAT DOUBLE-FLOAT).


Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10073EEC53}>
0: (PGLOADER.TRANSFORMS::FLOAT-TO-STRING "0") [tl,external]
1: (PGLOADER.SOURCES::FORMAT-PGSQL-DEFAULT-VALUE "0" PGLOADER.TRANSFORMS::FLOAT-TO-STRING)
2: (PGLOADER.SOURCES::FORMAT-PGSQL-TYPE (:TABLE-NAME "x" :COLUMN-NAME "y" :TYPE "decimal" :CTYPE "decimal(18,2)" :TYPEMOD (18 . 2) :DEFAULT "0" :NOT-NULL T :AUTO-INCREMENT NIL) (:TYPE "numeric") PGLOADER.TRANSFORMS::FLOAT-TO-STRING)
3: (PGLOADER.SOURCES::APPLY-CASTING-RULES "decimal" "decimal(18,2)" "0" "NO" NIL :TABLE-NAME "x" :COLUMN-NAME "y" :RULES NIL)
4: (PGLOADER.SOURCES:CAST "x" "y" "decimal" "decimal(18,2)" "0" "NO" NIL)
5: ((:METHOD PGLOADER.PGSQL:FORMAT-PGSQL-COLUMN (PGLOADER.MSSQL::MSSQL-COLUMN)) #S(PGLOADER.MSSQL::MSSQL-COLUMN :SCHEMA "dbo" :TABLE-NAME "x" :NAME "y" :TYPE "decimal" :DEFAULT "0" :NULLABLE "NO" :IDENTITY NIL :CHARACTER-MAXIMUM-LENGTH NIL :NUMERIC-PRECISION 18 :NUMERIC-PRECISION-RADIX 10 :NUMERIC-SCALE 2 :DATETIME-PRECISION NIL :CHARACTER-SET-NAME NIL :COLLATION-NAME NIL)) [fast-method]

SINGLE:

An unhandled error condition has been signalled:
   The value "(0)" is not of type (OR NULL SINGLE-FLOAT DOUBLE-FLOAT).

Date/time: 2015-04-13-12:11An unhandled error condition has been signalled:
                              The value "(0)"
                              is not of type
                                (OR NULL SINGLE-FLOAT DOUBLE-FLOAT).


Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10073EEC53}>
0: (PGLOADER.TRANSFORMS::FLOAT-TO-STRING "(0)") [tl,external]
1: (PGLOADER.SOURCES::FORMAT-PGSQL-DEFAULT-VALUE "(0)" PGLOADER.TRANSFORMS::FLOAT-TO-STRING)
2: (PGLOADER.SOURCES::FORMAT-PGSQL-TYPE (:TABLE-NAME "x" :COLUMN-NAME "y" :TYPE "decimal" :CTYPE "decimal(18,2)" :TYPEMOD (18 . 2) :DEFAULT "(0)" :NOT-NULL T :AUTO-INCREMENT NIL) (:TYPE "numeric") PGLOADER.TRANSFORMS::FLOAT-TO-STRING)
3: (PGLOADER.SOURCES::APPLY-CASTING-RULES "decimal" "decimal(18,2)" "(0)" "NO" NIL :TABLE-NAME "x" :COLUMN-NAME "y" :RULES NIL)
4: (PGLOADER.SOURCES:CAST "x" "y" "decimal" "decimal(18,2)" "(0)" "NO" NIL)
5: ((:METHOD PGLOADER.PGSQL:FORMAT-PGSQL-COLUMN (PGLOADER.MSSQL::MSSQL-COLUMN)) #S(PGLOADER.MSSQL::MSSQL-COLUMN :SCHEMA "dbo" :TABLE-NAME "x" :NAME "y" :TYPE "decimal" :DEFAULT "(0)" :NULLABLE "NO" :IDENTITY NIL :CHARACTER-MAXIMUM-LENGTH NIL :NUMERIC-PRECISION 18 :NUMERIC-PRECISION-RADIX 10 :NUMERIC-SCALE 2 :DATETIME-PRECISION NIL :CHARACTER-SET-NAME NIL :COLLATION-NAME NIL)) [fast-method]

DOUBLE:

An unhandled error condition has been signalled:
   The value "((0))" is not of type (OR NULL SINGLE-FLOAT DOUBLE-FLOAT).


Date/time: 2015-04-10-22:36An unhandled error condition has been signalled:
                              The value "((0))"
                              is not of type
                                (OR NULL SINGLE-FLOAT DOUBLE-FLOAT).


Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10073EE903}>
0: (PGLOADER.TRANSFORMS::FLOAT-TO-STRING "((0))") [tl,external]
1: (PGLOADER.SOURCES::FORMAT-PGSQL-DEFAULT-VALUE "((0))" PGLOADER.TRANSFORMS::FLOAT-TO-STRING)
2: (PGLOADER.SOURCES::FORMAT-PGSQL-TYPE (:TABLE-NAME "x" :COLUMN-NAME "y" :TYPE "decimal" :CTYPE "decimal(18,2)" :TYPEMOD (18 . 2) :DEFAULT "((0))" :NOT-NULL T :AUTO-INCREMENT NIL) (:TYPE "numeric") PGLOADER.TRANSFORMS::FLOAT-TO-STRING)

I've modified string-to-float function (added string to declare type):

(defun float-to-string (float)
  "Transform a Common Lisp float value into its string representation as
   accepted by PostgreSQL, that is 100.0 rather than 100.0d0."
  (declare (type (or null float string) float))
  (when float
    (typecase float
      (double-float (let ((*read-default-float-format* 'double-float))
                      (princ-to-string float)))
      (t            (princ-to-string float)))))

And it resolved my problem.

**Comment by dimitri** [comment]
Wow, cool! Would you consider attaching the patch you did to a Pull Request with mentioning "fix #207" in the commit message so that I just commit your changes. That way you will be remembered in the hall of fame of pgloader. I mean the `git --no-pager shortlog -n -s` ;-)

**Comment by jstans** [comment]
I just tested luqelinux's changes and can confirm they worked nicely. +1 for merge.

**Comment by jstans** [comment]
Currently using:

    WHEN c.column_default LIKE '((%' AND c.column_default LIKE '%))' THEN
        CASE
            WHEN SUBSTRING(c.column_default,3,len(c.column_default)-4) = 'newid()' THEN 'generate_uuid_v4()'
            WHEN SUBSTRING(c.column_default,3,len(c.column_default)-4) LIKE 'convert(%varchar%,getdate(),%)' THEN 'today'
            WHEN SUBSTRING(c.column_default,3,len(c.column_default)-4) = 'getdate()' THEN 'now'
            WHEN SUBSTRING(c.column_default,3,len(c.column_default)-4) LIKE '''%''' THEN SUBSTRING(c.column_default,4,len(c.column_default)-6)
            ELSE SUBSTRING(c.column_default,3,len(c.column_default)-4)
        END
    WHEN c.column_default LIKE '(%' AND c.column_default LIKE '%)' THEN
        CASE
            WHEN SUBSTRING(c.column_default,2,len(c.column_default)-2) = 'newid()' THEN 'generate_uuid_v4()'
            WHEN SUBSTRING(c.column_default,2,len(c.column_default)-2) LIKE 'convert(%varchar%,getdate(),%)' THEN 'today'
            WHEN SUBSTRING(c.column_default,2,len(c.column_default)-2) = 'getdate()' THEN 'now'
            WHEN SUBSTRING(c.column_default,2,len(c.column_default)-2) LIKE '''%''' THEN SUBSTRING(c.column_default,3,len(c.column_default)-4)
            ELSE SUBSTRING(c.column_default,2,len(c.column_default)-2)
        END
    ELSE c.column_default END,

It's pretty messy but solves a lot of problems I'm having with defaults.

**Comment by dimitri** [comment]
Hopefully I didn't break MS SQL support with this commit, should it be the case please re-open the issue!

Thanks very much both @luqelinux and @jstans for your contributions to pgloader.
