### ISSUE TITLE
Conversion fails with "Argument Y is not a NUMBER: NIL"

### ISSUE THREAD

**Issue by jwm** [dimitri/pgloader#208]
Hi, I'm trying to use the latest version of pgloader (3.2.0+dfsg-1) to move an existing MySQL database used by a Django web application to a Postgres database.

I created the (matching) table structure in the Postgres database using Django (and South) and configured pgloader to not drop and create tables. However, I'm having trouble getting pgloader to do the conversion.

My pgloader.conf:

```
[jwm@taxi:pts/0 ~> cat pgloader.conf
LOAD DATABASE
     FROM      mysql://root@localhost/oh
     INTO postgresql:///oh

 WITH include no drop, create no tables, create no indexes,
      truncate, reset sequences, foreign keys;
```

yields:

```
An unhandled error condition has been signalled: Argument Y is not a NUMBER: NIL
```

pgloader doesn't write anything to pgloader.log, and I can't make much of the --debug output:

```
[jwm@taxi:pts/0 ~> pgloader pgloader.conf --debug
An unhandled error condition has been signalled:
   There is no applicable method for the generic function
     #<STANDARD-GENERIC-FUNCTION PGLOADER.CONNECTION:CONN-TYPE (1)>
   when called with arguments
     (NIL).

;
; compilation unit aborted
;   caught 1 fatal ERROR condition
```

I can successfully connect using psql(1):

```
[jwm@taxi:pts/0 ~> psql oh
psql (9.4.1)
Type "help" for help.

oh=> \dt
                             List of relations
 Schema |                       Name                       | Type  | Owner
--------+--------------------------------------------------+-------+-------
 public | account_invitationrequest                        | table | jwm
 public | auth_group                                       | table | jwm
 public | auth_group_permissions                           | table | jwm
[...]
```

Am I doing something wrong?

**Comment by dimitri** [comment]
Is the debug trace you're pasting here full? seems like you've cut it down to some minimum where I don't see the information I need to debug the situation. Can you please give the full debug output?

**Comment by jwm** [comment]
Yup, that's the entire debug trace, unedited. pgloader(1) exits with status 1.

**Comment by dimitri** [comment]
I just tried the same setup or abouts as what you provide, and I fail to reproduce your situation. Can you please try building the current version of the code from git and report?

**Comment by jwm** [comment]
I cloned the repo and installed the dependencies (basically read `bootstrap-debian.sh` and installed what was necessary) on a Debian sid system.

Building failed with:

```
buildapp --require sb-posix                         \
                 --require sb-bsd-sockets                   \
                 --load /usr/share/common-lisp/source/cl-asdf/build/asdf.lisp \
                 --asdf-path .                              \
                 --asdf-tree /usr/share/common-lisp/systems \
                 --load-system asdf-finalizers              \
                 --load-system asdf-system-connections      \
                 --load-system pgloader                     \
                 --load src/hooks.lisp                      \
                 --entry pgloader:main                      \
                 --dynamic-space-size 4096               \
                 --compress-core                            \
                 --output build/bin/pgloader
; compiling file "/usr/share/common-lisp/source/cl-asdf/build/asdf.lisp" (written 22 OCT 2
014 04:15:20 PM):

; /home/jwm/pgloader/debian/home/.cache/common-lisp/sbcl-1.2.4.debian-linux-x64/usr/share$
common-lisp/source/cl-asdf/build/asdf-TMP.fasl written
; compilation finished in 0:00:10.221
;; loading file #P"/usr/share/common-lisp/source/cl-asdf/build/asdf.lisp"
;; loading system "asdf-finalizers"
;; loading system "asdf-system-connections"
;; loading system "pgloader"
Fatal COMPILE-FILE-ERROR:
  COMPILE-FILE-ERROR while
  compiling #<CL-SOURCE-FILE "pgloader" "src" "sources" "db3" "db3">

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Retry
                                     compiling #<CL-SOURCE-FILE "pgloader" "src" "sources"
 "db3" "db3">.
  1: [ACCEPT                       ] Continue, treating
                                     compiling #<CL-SOURCE-FILE "pgloader" "src" "sources"
 "db3" "db3">
                                     as having been successful.
  2:                                 Retry ASDF operation.
  3: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  4: [RETRY                        ] Retry EVAL of current toplevel form.
  5: [CONTINUE                     ] Ignore error and continue loading file "/home/jwm/pgl
oader/dumper-2SKVI5f7.lisp".
  6: [ABORT                        ] Abort loading file "/home/jwm/pgloader/dumper-2SKVI5f
7.lisp".
  7:                                 Ignore runtime option --load "/home/jwm/pgloader/dump
er-2SKVI5f7.lisp".
  8:                                 Skip rest of --eval and --load options.
  9:                                 Skip to toplevel READ/EVAL/PRINT loop.
 10: [EXIT                         ] Exit SBCL (calling #'EXIT, killing the process).

(UIOP/LISP-BUILD:CHECK-LISP-COMPILE-RESULTS NIL T T "~/asdf-action::format-action/" ((#<AS
DF/LISP-ACTION:COMPILE-OP > . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "pgloader" "src" "sources"
 "db3" "db3">)))
0]
```

I don't have any Common Lisp experience; did I do something wrong? How can I go about debugging this?

**Comment by dimitri** [comment]
It looks like it's the same error as before, which is very strange to me as really it should mean that your copy of cl-db3 is too old. Maybe try the following then build again?

    cd build/quicklisp/local-projects/cl-db3
    git pull

**Comment by dimitri** [comment]
Oh by the way, reading this again, I just realize the problem you have with your `--debug` attempt. It really needs to be spelled out that way, with the switch first and the setup file next:

    pgloader --debug pgloader.conf

Can you try that again so that I fix the problem you had first? Then, we will still need to figure out how to have you build from the source code, or I might be able to offer a qemu or docker minimal image...

**Comment by jwm** [comment]
Hi Dimitri, thanks for your help. I had been trying to build the source using `dpkg-buildpackage` from a cloned copy of the pgloader git repository. Doing a make-based build worked once I removed the cl-db3 Debian package.

Running the latest code with `--debug` in the right order still fails, but now emits debug output. :smiley:

```
[...]
2015-04-19T19:50:06.354000+03:00 DEBUG TARGET: auth_group_permissions
2015-04-19T19:50:06.354000+03:00 NOTICE COPY auth_group_permissions
2015-04-19T19:50:06.354000+03:00 DEBUG pgsql:copy-from-queue: auth_group_permissions (id group_id permission_id)
2015-04-19T19:50:06.354000+03:00 DEBUG CONNECT #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://jwm@localhost:5432/oh {1009160D93}>
2015-04-19T19:50:06.354000+03:00 INFO COPY auth_group_permissions done.
2015-04-19T19:50:06.354000+03:00 DEBUG TARGET: auth_permission
2015-04-19T19:50:06.354000+03:00 NOTICE COPY auth_permission
2015-04-19T19:50:06.354000+03:00 DEBUG pgsql:copy-from-queue: auth_permission (id name content_type_id codename)
2015-04-19T19:50:06.354000+03:00 DEBUG CONNECT #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://jwm@localhost:5432/oh {1009160D93}>
2015-04-19T19:50:06.354000+03:00 DEBUG BEGIN
An unhandled error condition has been signalled: Argument Y is not a NUMBER: NIL

Date/time: 2015-04-19-12:50An unhandled error condition has been signalled:
                              Argument Y is not a NUMBER: NIL


Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1008D8E523}>
0: ((LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX))
1: (SB-IMPL::CALL-WITH-SANE-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX) {100B92A86B}>)
2: (SB-IMPL::%WITH-STANDARD-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX) {100B92A83B}>)
3: (PRINT-BACKTRACE :STREAM #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDOUT* {10002A5A33}> :START 0 :FROM :DEBUGGER-FRAME :COUNT 4611686018427387903 :PRINT-THREAD T :PRINT-FRAME-SOURCE NIL :METHOD-FRAME-STYLE NIL)
4: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE-TO-STREAM #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDOUT* {10002A5A33}>)
5: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE #<SIMPLE-TYPE-ERROR expected-type: NUMBER datum: NIL> :OUTPUT #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDOUT* {10002A5A33}> :IF-EXISTS :APPEND :VERBOSE T)
6: (SIGNAL #<SIMPLE-TYPE-ERROR expected-type: NUMBER datum: NIL>)
7: (ERROR #<SIMPLE-TYPE-ERROR expected-type: NUMBER datum: NIL>)
8: (LPARALLEL.KERNEL::UNWRAP-RESULT #<unavailable lambda list>)
9: ((:METHOD PGLOADER.SOURCES:COPY-FROM (PGLOADER.MYSQL:COPY-MYSQL)) #<PGLOADER.MYSQL:COPY-MYSQL {100B4EC493}> :KERNEL #<LPARALLEL.KERNEL:KERNEL :NAME "lparallel" :WORKER-COUNT 2 :USE-CALLER NIL :ALIVE T :SPIN-COUNT 2000 {1009DB90F3}> :TRUNCATE NIL) [fast-method]
10: ((:METHOD PGLOADER.SOURCES:COPY-DATABASE (PGLOADER.MYSQL:COPY-MYSQL)) #<PGLOADER.MYSQL:COPY-MYSQL {1009CCE6B3}> :STATE-BEFORE #S(PGLOADER.UTILS::PGSTATE :TABLES #<HASH-TABLE :TEST EQUAL :COUNT 1 {10092B7AC3}> :TABNAMES ("fetch meta data") :READ 145 :ROWS 145 :ERRS 0 :SECS 0.903) :STATE-AFTER #S(PGLOADER.UTILS::PGSTATE :TABLES #<HASH-TABLE :TEST EQUAL :COUNT 0 {1009310823}> :TABNAMES NIL :READ 0 :ROWS 0 :ERRS 0 :SECS 0.0) :STATE-INDEXES #S(PGLOADER.UTILS::PGSTATE :TABLES #<HASH-TABLE :TEST EQUAL :COUNT 0 {10093103A3}> :TABNAMES NIL :READ 0 :ROWS 0 :ERRS 0 :SECS 0.0) :TRUNCATE T :DATA-ONLY NIL :SCHEMA-ONLY NIL :CREATE-TABLES NIL :INCLUDE-DROP NIL :CREATE-INDEXES NIL :RESET-SEQUENCES T :FOREIGN-KEYS T :ONLY-TABLES NIL :INCLUDING NIL :EXCLUDING NIL :DECODING-AS NIL :MATERIALIZE-VIEWS NIL) [fast-method]
11: ((LAMBDA ()))
12: (PGLOADER:RUN-COMMANDS #P"/home/jwm/pgloader.conf" :START-LOGGER NIL :SUMMARY NIL :LOG-FILENAME NIL :LOG-MIN-MESSAGES NIL :CLIENT-MIN-MESSAGES NIL)
13: (PGLOADER::PROCESS-COMMAND-FILE "pgloader.conf")
14: ((FLET #:CLEANUP-FUN-281 :IN PGLOADER::MAIN)) [cleanup]
15: (PGLOADER::MAIN ("pgloader" "--debug" "pgloader.conf"))
16: ((LAMBDA NIL :IN "/tmp/pgloader/dumper-2SKVI5f7.lisp"))
17: ((FLET #:WITHOUT-INTERRUPTS-BODY-89 :IN SAVE-LISP-AND-DIE))
18: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))
```

I don't see any suspect data in `auth_permission`, which looks like:

```
mysql> desc auth_permission;
+-----------------+--------------+------+-----+---------+----------------+
| Field           | Type         | Null | Key | Default | Extra          |
+-----------------+--------------+------+-----+---------+----------------+
| id              | int(11)      | NO   | PRI | NULL    | auto_increment |
| name            | varchar(50)  | NO   |     | NULL    |                |
| content_type_id | int(11)      | NO   | MUL | NULL    |                |
| codename        | varchar(100) | NO   |     | NULL    |                |
+-----------------+--------------+------+-----+---------+----------------+
```

All rows have integer data in both integer columns; no values are NULL.

**Comment by dimitri** [comment]
Could you install the following patch on your local source tree. I think the error handling here masks some important debug information, and with the patched version we should be able to have a full debug trace:

```diff
index bb1e1e1..2ba9bed 100644
--- a/src/sources/mysql/mysql.lisp
+++ b/src/sources/mysql/mysql.lisp
@@ -119,7 +119,7 @@
                             :dbname (db-name (target-db mysql))
                             :state *state*
                             :summary summary)
-      (lp:task-handler-bind ((error #'lp:invoke-transfer-error))
+      (lp:task-handler-bind ()
         (log-message :notice "COPY ~a" table-name)
         ;; read data from MySQL
         (lp:submit-task channel #'copy-to-queue mysql queue)
```

**Comment by jwm** [comment]
That was exactly it. Looks like it's a processing ordering problem:

```
2015-04-19T14:46:22.923000-04:00 ERROR Database error 23503: insert or update on table "auth_permission" violates foreign key constraint "content_type_id_refs_id_d043b34a"
DETAIL: Key (content_type_id)=(1) is not present in table "django_content_type".
```

pgloader is processing `auth_permissions` before `django_content_type`, which is causing a foreign key constraint violation.

Is there a way to handle this with pgloader other than figuring out the dependencies manually and processing tables in that order?

**Comment by dimitri** [comment]
Please add the option `disable triggers` in the `WITH` clause of your command, it should do it. From the docs:

		When this option is listed, pgloader issues an `ALTER TABLE ...
		DISABLE TRIGGER ALL` command against the PostgreSQL target table
		before copying the data, then the command `ALTER TABLE ... ENABLE
		TRIGGER ALL` once the `COPY` is done.

        This option allows loading data into a pre-existing table ignoring
        the *foreign key constraints* and user defined triggers and may
        result in invalid *foreign key constraints* once the data is loaded.
        Use with care.

**Comment by jwm** [comment]
That works great, and I have the database converted. Thanks very much for your help!

**Comment by michaelsanford** [comment]
Hi !

Is it possible to overcome this issue when the loading user cannot issue `DISABLE TRIGGER ALL` on a table? I'm facing this issue with AWS RDS:

```
QUERY: ALTER TABLE <table> DISABLE TRIGGER ALL;
An unhandled error condition has been signalled:
   Database error 42501: permission denied: "RI_ConstraintTrigger_a_17904" is a system trigger
QUERY: ALTER TABLE <table> DISABLE TRIGGER ALL;
```

(This was executed as the `rds_superuser` role user, [who notably lacks](http://serverfault.com/questions/661661/why-cant-i-create-a-superuser-in-aws-postgresql-instance) PostgreSQL's true `superuser` privilege).

I've adapted [this workaround](http://dba.stackexchange.com/questions/96961/how-to-temporarily-disable-foreign-keys-in-amazon-rds-postgresql)
```
BEFORE LOAD DO
$$ set session_replication_role = replica; $$

AFTER LOAD DO
$$ set session_replication_role = default; $$;
```

but because of the above error, I'm met with `Argument Y is not a NUMBER: NIL` if I don't / can't add `WITH disable triggers`.

Loading the same data set into a PostgreSQL database as a user to which I _can_ grant `superuser` works.

**Comment by dimitri** [comment]
Is it possible for you to give me a minimal test case wherein I would easily get the same error and debug it? it could be just a minimal MySQL schema that I can then run pgloader against...

**Comment by michaelsanford** [comment]
Hi @dimitri , thanks for your rapid response!

I've used the via-local-MySQL solution to solve my immediate problem, but I'll try to get you an [MCVE](http://stackoverflow.com/help/mcve) next week for others who experience this issue.

**Comment by jonny64** [comment]
I've just deleted test case :)
https://gist.github.com/jonny64/3e6857bd775898e5d65eb0a7f2ddd1e6
log.params is longtext. is this somehow encoding related? looks like utf8 chars written as cp1251

**Comment by dimitri** [comment]
Is it possible for you to prepare a minimal test case again? I would like to solve the issue...

**Comment by jonny64** [comment]
@dimitri, I caught them again
[log_fail.sql.gz](https://github.com/dimitri/pgloader/files/1381693/log_fail.sql.gz)
deleting those 8 records will make my load pass, again

**Comment by dimitri** [comment]
Current version is 3.4.1 and current development version are 3.4.git-hash. Please try again with something recent, as lots of error managing fixes went through recently.

**Comment by jonny64** [comment]
`docker pull dimitri/pgloader`
I've tried latest image: it hangs here:

#<THREAD "lparallel" RUNNING {100B483F23}>:
2017-10-16T14:07:22.740000Z ERROR PostgreSQL ["srv14_housing_real.log"] Database error 22P05:      0xef 0xbf 0xbd   "UTF8"    "WIN1251"
CONTEXT: COPY log,  262
  Argument Y is not a NUMBER: NIL
2017-10-16T14:07:22.740000Z INFO Entering error recovery.

debugger invoked on a SIMPLE-TYPE-ERROR in thread
#<THREAD "lparallel" RUNNING {100B486A73}>:
  Argument Y is not a NUMBER: NIL
2017-10-16T14:07:22.747000Z ERROR PostgreSQL ["srv14_housing_real.log"] Database error 22P05:      0xef 0xbf 0xbd   "UTF8"    "WIN1251"
CONTEXT: COPY log,  1130
2017-10-16T14:07:22.747000Z INFO Entering error recovery.
2017-10-16T14:07:22.996000Z SQL ALTER TABLE log ENABLE TRIGGER ALL;
2017-10-16T14:07:23.231000Z SQL ALTER TABLE log ENABLE TRIGGER ALL;

What can I do to workaround this?

**Comment by dimitri** [comment]
I just tried the dump on my local test system, and il passed without a glitch. The 8 rows are copied over. Is it possible for you to compile from fresh sources?
