### ISSUE TITLE
supported environment to use pgloader

### ISSUE THREAD

**Issue by vinpokale** [dimitri/pgloader#209]
Hi,
I would like to know the supported environment to use pgloader.
I mean supported PostgreSQL versions and Supported OS versions.

Regards,
Vinayak

**Comment by dimitri** [comment]
On the PostgreSQL side, I don't remember needing anything much recent, as pgloader mainly uses the COPY protocol directly. You should be fine with any supported PostgreSQL release, starting at 9.0. We are using a `DO` block for the *reset sequences* option though, so you might need to turn that off and do it yourself when using unsupported PostgreSQL releases.

About OS versions, pgloader is known to be compatible with the [SBCL](http://sbcl.org/platform-table.html) and [CCL](http://ccl.clozure.com/) Common Lisp compilers, so any platform they do support should be a target for pgloader. pgloader is currently known to work on Linux, MacOSX and Windows.
