### ISSUE TITLE
mysql to postgresql - Failed to connect

### ISSUE THREAD

**Issue by Summer88** [dimitri/pgloader#214]
Want to leave mysql to go with postgresql...
If I try this command:

```
@server:~# pgloader mysql://myuser:mypwd@127.0.0.1:3306/mydb postgresql:///pippo

got this error:
2015-04-23T16:24:12.083000+03:00 LOG Main logs in '/tmp/pgloader/pgloader.log'
2015-04-23T16:24:12.088000+03:00 LOG Data errors in '/tmp/pgloader/'
An unhandled error condition has been signalled:
   Failed to connect to mysql at "127.0.0.1" (port 3306) as user "myuser": Condition USOCKET:CONNECTION-REFUSED-ERROR was signalled.

pgloader version "3.2.0"
compiled with SBCL 1.2.4.debian
```

what am I missing?
Thanks, BR

**Comment by dimitri** [comment]
Is your MySQL server listening on 127.0.0.1 on port 3306? it happens that in some settings you would suppose it's doing that when it actually only listens on a local socket. Please debug using `lsof -i :3306` or some such command.

**Comment by Summer88** [comment]
dear dimitri, thanks for the answer, but I'm afraid this is not the problem:

lsof -i :3306
COMMAND  PID  USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
mysqld  3594 mysql    8u  IPv4  15393      0t0  TCP server.local:mysql (LISTEN)
mysqld  3594 mysql   10u  IPv4  81801      0t0  TCP server.local:mysql->internalip:52649 (ESTABLISHED)

**Comment by Summer88** [comment]
Solved! it was that! 
changed from 127.0.0.1 to the ip address in my.cnf solved!
THANKS for the help! Have a nice day!

**Comment by sergiomb2** [comment]
and not using special characters in password ?

**Comment by boholder** [comment]
> 
> 
> and not using special characters in password ?

Convert them to url encode type, one online convertor: https://www.urlencoder.org/ .
example: A@1203 -> encode: A%401203, where "%40" is "@" in url encode.

**Comment by topetope024** [comment]
@Summer88  please elaborate you change the bind-address="127.0.0.1"? to bind-address="(my IP address?) please reponse, im desperate

**Comment by RobyCigar** [comment]
> [@summer88](https://github.com/summer88) please elaborate you change the bind-address="127.0.0.1"? to bind-address="(my IP address?) please reponse, im desperate

same problem here, i donno where to put bind-address="(my IP address?)"
