### ISSUE TITLE
csv import: generic trim-whitespace option or better right-trimg documentation

### ISSUE THREAD

**Issue by mbanck** [dimitri/pgloader#215]
The CSV import has a per-column option to trim whitespace, however, in larger projects, specifying each column is infeasible. So I think a global CSV option to trim at the end of the string would be good.

It seems this is already present with the right-trimg function, but the lisp transformation functions are undocumented for non-list speaking people, at least some simple examples on how to write a --load (btw, the option is --load-list-file/-l and not --load as referenced in the manual) would be appreciated.

**Comment by dimitri** [comment]
As examples you can have a look at https://github.com/dimitri/pgloader/issues/81, https://github.com/dimitri/pgloader/issues/92 and https://github.com/dimitri/pgloader/issues/90 wherein a non lisp user did use the `--load-lisp-file` to enhance pgloader for his use case. I leave this open while I see about adding the per-file option rather than per-column...

**Comment by mbanck** [comment]
The documentation at http://pgloader.io/howto/pgloader.1.html says "trim unquoted blanks" was the default, but I can try to set it explicitly.

By the way, I believe said documentation has a typo in the "TRANSFORMATION FUNCTIONS" section further down, it says "right-trimg" (see issue title), but looking at the source the correct function seems to be "right-trim"?

Finally, thanks for the pointer to issues with custom lisp. So if I read those issues right, one can optionally pass a custom lisp file, but the methods in that custom file and/or transforms.lisp can only be applied in the "using" clause for a explicitly specified column, not in general for the whole data?

**Comment by dimitri** [comment]
Closing for lack of movement/interest on that front. Current situation is still that the trimming option needs to be set separately for each input field where you want it to happen.
