### ISSUE TITLE
custom NULL-value

### ISSUE THREAD

**Issue by mbanck** [dimitri/pgloader#217]
The COPY-Syntax allows for a custom NULL-value, would be good if that could be folded into the LOAD-File Syntax so CSV-Data with non-standard NULL values can be easily loaded.

**Comment by dimitri** [comment]
There's a per-column `null if` option for file based loading in pgloader, can you use that?

**Comment by mbanck** [comment]
> There's a per-column `null if` option for file based loading in pgloader, can you use that?

I realized that, but I plan to use this in a 100+ tables scenario, so having to inspect every column for that potential problem and adding the option is not feasible.

As there is such an option in the COPY-syntax (WITH NULL "null" e.g.), I assumed it would not be a big issue, but looking at the code a bit I realize you might use a different interface.

In any case, I managed to work-around this limitation by adjusting the exported file format, but I think a bite more fleibility here would't hurt.

**Comment by dimitri** [comment]
The CSV parser is getting quite complex nowadays, the issue I see with using the `WITH NULL` syntax of the `COPY` command would be with double-effects of sorts, wherein some input value in the CSV file get transformed into a processed value which is then the expected `NULL` value...

BTW, where are those 100+ tables coming from? we might be able to bypass the intermediate CSV files altogether?

**Comment by mbanck** [comment]
On Sun, Apr 26, 2015 at 11:04:43AM -0700, Dimitri Fontaine wrote:
> The CSV parser is getting quite complex nowadays, the issue I see with using the `WITH NULL` syntax of the `COPY` command would be with double-effects of sorts, wherein some input value in the CSV file get transformed into a processed value which is then the expected `NULL` value...

I actually had this issue when I tried a JDBC-based copy/import/export tool (SQLWorkbench/J).  It has a trim-whitespace feature, and the from the resulting CSV on export it wasn't possible to see whether the data was a NULL or a trimmed string.  The solution for that was exactly a custom NULL value (except that I couldn't use pgloader in CSV mode so far cause I wasn't able to specify a custom NULL value on import)

I think for pgloader, it would be safe to assume that any non-NULL value that happens to be the (custom) NULL string got escaped by the export (at least that is what PostgreSQL's COPY TO does in CSV mode according to the documentation).
 
> BTW, where are those 100+ tables coming from? we might be able to bypass the intermediate CSV files altogether?

A DB2 database.  It would be nice to bypass the intermediate files, but AFAIK pgloader does not support DB2 as a source yet, right?

**Comment by dimitri** [comment]
I think I'd rather work on a DB2 support as a source here ;-)

**Comment by dimitri** [comment]
Closing this issue for clean-up. Please open a new one if you're interested into direct DB2 support for pgloader, using either an ODBC connection driver or a native one.
