### ISSUE TITLE
COPY TEXT format required enumeration of column names

### ISSUE THREAD

**Issue by mbanck** [dimitri/pgloader#218]
Contrary to the COPY CSV format, the COPY TEXT format option apparently requires that the column names are enumerated in the load file. As there is no such requirement in the COPY CSV format, I think this is an unneeded limitation.

Also, the COPY TEXT format rather arbitrarily requires the filename in a copy:// URI syntax, unilke the COPY CSV option. This would not be a huge issue if the resulting error message was clear, but the Lisp parser errors tend to be not very clear at all, at least to non-Lisp people. Unless there is a very good reason, I think both syntaxes for the file location should be accepted by both formats (I have not checked whether the COPY CSV format accepts the copy:// syntax).

**Comment by dimitri** [comment]
Well you could think of the COPY format as a very strongly specified form of the CSV one... given it has *by design* no flexibility at all, I want users to pick CSV whenever the COPY format doesn't cut it. I'd rather have COPY limited to the PostgreSQL format of the same name, full stop.

**Comment by mbanck** [comment]
On Sun, Apr 26, 2015 at 11:09:01AM -0700, Dimitri Fontaine wrote:
> Well you could think of the COPY format as a very strongly specified form of the CSV one...  given it has *by design* no flexibility at all, I want users to pick CSV whenever the COPY format doesn't cut it. I'd rather have COPY limited to the PostgreSQL format of the same name, full stop.

At least DELIMITER and NULL can be set in both AFAICT. HEADER, QUOTE and ESCAPE are CSV-only, though.

In any case, while I mostly agree that COPY TEXT should need less customization than COPY CSV, I am not sure what this has to do with having to enumerate the column names or not.  The PostgreSQL COPY documentation says: "column_name: An optional list of columns to be copied. If no column list is specified, all columns of the table will be copied."

**Comment by dimitri** [comment]
You're actually right, so while I was fixing another bug in the COPY support I just added support for your requests here. Please confirm you're all set, or re-open the issue with specific examples.

**Comment by mbanck** [comment]
Yeah, it works great now
