### ISSUE TITLE
Assertion error trying to convert an SQLite database?

### ISSUE THREAD

**Issue by rfilmyer** [dimitri/pgloader#220]
I tried converting an sqlite database using the command described [here](http://pgloader.io/howto/pgloader.1.html) and got a very strange error that I wasn't able to find on google:

```  
    bash-3.2$ ../../pgloader/build/bin/pgloader -v drive_stats.db postgresql:///backblaze
    2015-04-27T15:56:28.014000-04:00 NOTICE Starting pgloader, log system is ready.
    2015-04-27T15:56:28.030000-04:00 LOG Main logs in '/private/tmp/pgloader/pgloader.log'
    2015-04-27T15:56:28.035000-04:00 LOG Data errors in '/private/tmp/pgloader/'
    An unhandled error condition has been signalled:
       The assertion (= 1 (LENGTH PGLOADER.SQLITE::TOKENS)) failed with 
       (LENGTH PGLOADER.SQLITE::TOKENS) = 2.
```

What causes this error and how can I resolve it?

I'm using the latest github version of pgloader on OSX Yosemite, reading from an sqlite3 (v3.8.8.3) database that's about 2.5 GB large.

**Comment by rfilmyer** [comment]
I also tried dumping the sqlite db to a .sql file. The same error occurs, and the logs are exactly what I saw on the console and put above.

**Comment by dimitri** [comment]
How did you dump the sqlite db to a .sql file? Also I would need a `--debug` output from pgloader to help you there, and we might even need to patch sources for a better diagnostic...

**Comment by rfilmyer** [comment]
The command I actually used in sqlite to dump was `sqlite3 drive_stats.db .dump > backblaze.sql`.

Although I ran pgloader with both the .db and the .sql dump, with the same error.

**Comment by rfilmyer** [comment]
Here is the error I got when ran with `--debug`:

bash-3.2$ ../../pgloader/build/bin/pgloader --debug drive_stats.db postgresql:///backblaze
sb-impl::*default-external-format* :UTF-8
tmpdir: #P"/var/folders/g9/ct5f3_r52c37rbls5_9nc_qc0000gn/T/"
2015-04-28T11:03:44.021000-04:00 NOTICE Starting pgloader, log system is ready.
2015-04-28T11:03:44.036000-04:00 INFO Starting monitor
2015-04-28T11:03:44.041000-04:00 LOG Main logs in '/private/tmp/pgloader/pgloader.log'
2015-04-28T11:03:44.041000-04:00 LOG Data errors in '/private/tmp/pgloader/'
An unhandled error condition has been signalled:
   The assertion (= 1 (LENGTH PGLOADER.SQLITE::TOKENS)) failed with
   (LENGTH PGLOADER.SQLITE::TOKENS) = 2.

Date/time: 2015-04-28-11:03An unhandled error condition has been signalled:
                              The assertion
                              (= 1 (LENGTH PGLOADER.SQLITE::TOKENS)) failed
                              with (LENGTH PGLOADER.SQLITE::TOKENS) = 2.


Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10086771C3}>
0: ((LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX))
1: (SB-IMPL::CALL-WITH-SANE-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX) {1009862D0B}>)
2: (SB-IMPL::%WITH-STANDARD-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX) {1009862CDB}>)
3: (PRINT-BACKTRACE :STREAM #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDOUT* {1000295B83}> :START 0 :FROM :DEBUGGER-FRAME :COUNT 4611686018427387903 :PRINT-THREAD T :PRINT-FRAME-SOURCE NIL :METHOD-FRAME-STYLE NIL)
4: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE-TO-STREAM #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDOUT* {1000295B83}>)
5: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE #<SIMPLE-ERROR "~@<The assertion ~S failed~:[.~:; ~
                                    with ~:*~{~{~S = ~S~}~^, ~}.~]~:@>" {100985C1A3}> :OUTPUT #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDOUT* {1000295B83}> :IF-EXISTS :APPEND :VERBOSE T)
6: (SIGNAL #<SIMPLE-ERROR "~@<The assertion ~S failed~:[.~:; ~
                                    with ~:*~{~{~S = ~S~}~^, ~}.~]~:@>" {100985C1A3}>)
7: (ERROR #<SIMPLE-ERROR "~@<The assertion ~S failed~:[.~:; ~
                                    with ~:*~{~{~S = ~S~}~^, ~}.~]~:@>" {100985C1A3}>)
8: (SB-KERNEL:ASSERT-ERROR (= 1 (LENGTH PGLOADER.SQLITE::TOKENS)) (((LENGTH PGLOADER.SQLITE::TOKENS) 2)) NIL NIL)
9: (PGLOADER.SQLITE::NORMALIZE "INTEGER (8)")
10: (PGLOADER.SQLITE::LIST-COLUMNS "drive_stats" #<SQLITE:SQLITE-HANDLE {1009694B33}>)
11: (PGLOADER.SQLITE::LIST-ALL-COLUMNS #<SQLITE:SQLITE-HANDLE {1009694B33}>)
12: (PGLOADER.SQLITE::FETCH-SQLITE-METADATA #<PGLOADER.SQLITE:COPY-SQLITE {10094E3363}> :STATE #S(PGLOADER.UTILS::PGSTATE :TABLES #<HASH-TABLE :TEST EQUAL :COUNT 2 {1008F03923}> :TABNAMES ("fetch meta data" "fetch") :READ 0 :ROWS 0 :ERRS 0 :SECS 0.0) :INCLUDING NIL :EXCLUDING NIL)
13: ((:METHOD PGLOADER.SOURCES:COPY-DATABASE (PGLOADER.SQLITE:COPY-SQLITE)) #<PGLOADER.SQLITE:COPY-SQLITE {10094E3363}> :STATE-BEFORE #S(PGLOADER.UTILS::PGSTATE :TABLES #<HASH-TABLE :TEST EQUAL :COUNT 2 {1008F03923}> :TABNAMES ("fetch meta data" "fetch") :READ 0 :ROWS 0 :ERRS 0 :SECS 0.0) :DATA-ONLY NIL :SCHEMA-ONLY NIL :TRUNCATE NIL :CREATE-TABLES T :INCLUDE-DROP T :CREATE-INDEXES T :RESET-SEQUENCES T :ONLY-TABLES #<unused argument> :INCLUDING NIL :EXCLUDIN
G NIL :ENCODING :UTF-8) [fast-method]
14: ((LAMBDA ()))
15: (PGLOADER:RUN-COMMANDS (LAMBDA NIL (LET* ((PGLOADER.PARSER::STATE-BEFORE (PGLOADER.UTILS:MAKE-PGSTATE)) (PGLOADER.PARAMS:*STATE* (PGLOADER.UTILS:MAKE-PGSTATE)) (PGLOADER.SOURCES:*DEFAULT-CAST-RULES* (QUOTE ((:SOURCE (:TYPE "character") :TARGET (:TYPE #1="text" :DROP-TYPEMOD T)) (:SOURCE (:TYPE "varchar") :TARGET (:TYPE #1# :DROP-TYPEMOD T)) (:SOURCE (:TYPE "nvarchar") :TARGET (:TYPE #1# :DROP-TYPEMOD T)) (:SOURCE (:TYPE "char") :TARGET (:TYPE #1# :DROP-TYPEMOD T)) (:SOURCE (:TYPE "nchar") :TARGET (:TYPE #1# :DROP-TYPEMOD T)) (:SOURCE (:TYPE "clob") :TARGET (:TYPE #1# :DROP-TYPEMOD T)) (:SOURCE (:TYPE "tinyint") :TARGET (:TYPE "smallint")) (:SOURCE (:TYPE #2="float") :TARGET (:TYPE #2#) :USING PGLOADER.TRANSFORMS::FLOAT-TO-STRING) (:SOURCE (:TYPE #3="real") :TARGET (:TYPE #3#) :USING PGLOADER.TRANSFORMS::FLOAT-TO-STRING) (:SOURCE (:TYPE "double") :TARGET (:TYPE "double precision") :USING PGLOADER.TRANSFORMS:
:FLOAT-TO-STRING) (:SOURCE (:TYPE #4="numeric") :TARGET (:TYPE #4#) :USING PGLOADER.TRANSFORMS::FLOAT-TO-STRING) (:SOURCE (:TYPE "blob") :TARGET (:TYPE "bytea") :USING PGLOADER.TRANSFORMS::BYTE-VECTOR-TO-BYTEA) (:SOURCE (:TYPE "datetime") :TARGET (:TYPE #5="timestamptz") :USING PGLOADER.TRANSFORMS::SQLITE-TIMESTAMP-TO-TIMESTAMP) (:SOURCE (:TYPE #6="timestamp") :TARGET (:TYPE #6#) :USING PGLOADER.TRANSFORMS::SQLITE-TIMESTAMP-TO-TIMESTAMP) (:SOURCE (:TYPE #5#)
 :TARGET (:TYPE #5#) :USING PGLOADER.TRANSFORMS::SQLITE-TIMESTAMP-TO-TIMESTAMP)))) (PGLOADER.SOURCES:*CAST-RULES* (QUOTE NIL)) (PGLOADER.PARAMS:*PG-SETTINGS* (QUOTE NIL)) (PGLOADER.PGSQL::*PGSQL-RESERVED-KEYWORDS* (PGLOADER.PGSQL:LIST-RESERVED-KEYWORDS #7=#<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://roger@UNIX:5432/backblaze {1008E94FE3}>)) (PGLOADER.PARAMS:*COPY-BATCH-ROWS* (OR NIL PGLOADER.PARAMS:*COPY-BATCH-ROWS*)) (PGLOADER.PARAMS:*COPY-BATCH-SIZE* (OR NIL PGLOADER.PARAMS:*COPY-BATCH-SIZE*)) (PGLOADER.PARAMS:*CONCURRENT-BATCHES* (OR NIL PGLOADER.PARAMS:*CONCURRENT-BATCHES*)) (PGLOADER.PARSER::SOURCE-DB (PGLOADER.UTILS:WITH-STATS-COLLECTION ("fetch" :STATE PGLOADER.PARSER::STATE-BEFORE) (PGLOADER.CONNECTION:EXPAND (PGLOADER.CONNECTION:FETCH-FILE #<PGLOADER.SQLITE:SQLITE-CONNECTION sqlite:///Users/roger/projects/Fun with Data/backblaze/drive_stats.db {1008898433}>)))) (PGLOADER.PARSER::SOURCE (MAKE-INSTANCE (QUOTE PGLOADER.SQLITE:COPY-SQLITE) :TARGET-DB #7# :SOURCE-DB PGLOADER.PARSER::SOURCE-DB))) (PGLOADER.SOURCES:COPY-DATABASE PGLOADER.PARSER::SOURCE :STATE-BEFORE PGLOADER.PARSER::STATE-BEFORE :INCLUDING (QUOTE NIL) :EXCLUDING (QUOTE NIL)))) :START-LOGGER NIL :SUMMARY NIL :LOG-FILENAME NIL :LOG-MIN-MESSAGES NIL :CLIENT-MIN-MESSAGES NIL)
16: ((FLET #:CLEANUP-FUN-294 :IN PGLOADER::MAIN)) [cleanup]
17: (PGLOADER::MAIN ("../../pgloader/build/bin/pgloader" "--debug" "drive_stats.db" "postgresql:///backblaze"))
18: ((LAMBDA NIL :IN "/Users/roger/projects/pgloader/dumper-2SKVI5f7.lisp"))

**Comment by dimitri** [comment]
Should be fine now, sorry about the bug. Please retest and confirm!

**Comment by rfilmyer** [comment]
Wow, that was fast! Thanks for the quick response!  
Unfortunately, it looks like I'm running into two errors now, depending on whether I open the `.db` or the `.sql` dump. I'm not sure if they're related to this problem, but I wasn't able to find a similar problem on google:

    bash-3.2$ ../../pgloader/build/bin/pgloader -v backblaze.sql postgresql:///backblaze
    An unhandled error condition has been signalled:
       There is no applicable method for the generic function
         #<STANDARD-GENERIC-FUNCTION PGLOADER.CONNECTION:CONN-TYPE (1)>
       when called with arguments
         (NIL).

    ;
    ; compilation unit aborted
    ;   caught 1 fatal ERROR condition

    bash-3.2$ ../../pgloader/build/bin/pgloader -v drive_stats.db postgresql:///backblaze
    An unhandled error condition has been signalled:
       Index 0 out of bounds for (SIMPLE-ARRAY CHARACTER
                                  (0)), should be nonnegative and <0.

**Comment by rfilmyer** [comment]
Running `--debug` on `drive_stats.db` I get:
    bash-3.2$ ../../pgloader/build/bin/pgloader --debug drive_stats.db postgresql://
    /backblaze
    sb-impl::*default-external-format* :UTF-8
    tmpdir: #P"/var/folders/g9/ct5f3_r52c37rbls5_9nc_qc0000gn/T/"
    2015-04-28T15:54:08.015000-04:00 NOTICE Starting pgloader, log system is ready.
    2015-04-28T15:54:08.032000-04:00 INFO Starting monitor
    2015-04-28T15:54:08.037000-04:00 LOG Main logs in '/private/tmp/pgloader/pgloader.log'
    2015-04-28T15:54:08.037000-04:00 LOG Data errors in '/private/tmp/pgloader/'
    An unhandled error condition has been signalled:
       Index 0 out of bounds for (SIMPLE-ARRAY CHARACTER
                                  (0)), should be nonnegative and <0.
    
    Date/time: 2015-04-28-15:54An unhandled error condition has been signalled:
                                  Index 0 out of bounds for (SIMPLE-ARRAY CHARACTER
                                                             (0)), should be nonnegative and <0.
    Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {100869F1C3}>
    0: (SB-IMPL::OPTIMIZED-DATA-VECTOR-REF #<unavailable argument> #<unavailable argument>)
    1: ((LAMBDA (PGLOADER.SQLITE::TOKEN) :IN PGLOADER.SQLITE::NORMALIZE) "")
    2: (REMOVE-IF #<FUNCTION (LAMBDA (PGLOADER.SQLITE::TOKEN) :IN PGLOADER.SQLITE::NORMALIZE) {100454F36B}> (""))
    3: (PGLOADER.SQLITE::NORMALIZE "")
    4: (PGLOADER.SQLITE::LIST-COLUMNS "drive_days" #<SQLITE:SQLITE-HANDLE {10096CCE03}>)
    5: (PGLOADER.SQLITE::LIST-ALL-COLUMNS #<SQLITE:SQLITE-HANDLE {10096CCE03}>)
    6: (PGLOADER.SQLITE::FETCH-SQLITE-METADATA #<PGLOADER.SQLITE:COPY-SQLITE {100951B363}> :STATE #S(PGLOADER.UTILS::PGSTATE :TABLES #<HASH-TABLE :TEST EQUAL :COUNT 2 {1008F3B453}> :TABNAMES ("fetch meta data" "fetch") :READ 0 :ROWS 0 :ERRS 0 :SECS 0.0) :INCLUDING NIL :EXCLUDING NIL)
    7: ((:METHOD PGLOADER.SOURCES:COPY-DATABASE (PGLOADER.SQLITE:COPY-SQLITE)) #<PGLOADER.SQLITE:COPY-SQLITE {100951B363}> :STATE-BEFORE #S(PGLOADER.UTILS::PGSTATE :TABLES #<HASH-TABLE :TEST EQUAL :COUNT 2 {1008F3B453}> :TABNAMES ("fetch meta data" "fetch") :READ 0 :ROWS 0 :ERRS 0 :SECS 0.0) :DATA-ONLY NIL :SCHEMA-ONLY NIL :TRUNCATE NIL :DISABLE-TRIGGERS NIL :CREATE-TABLES T :INCLUDE-DROP T :CREATE-INDEXES T :RESET-SEQUENCES T :ONLY-TABLES #<unused argument> :INCLUDING NIL :EXCLUDING NIL:ENCODING :UTF-8) [fast-method]
    8: ((LAMBDA ()))
    9: (PGLOADER:RUN-COMMANDS (LAMBDA NIL (LET* ((PGLOADER.PARSER::STATE-BEFORE (PGLOADER.UTILS:MAKE-PGSTATE)) (PGLOADER.PARAMS:*STATE* (PGLOADER.UTILS:MAKE-PGSTATE)) (PGLOADER.SOURCES:*DEFAULT-CAST-RULES* (QUOTE ((:SOURCE (:TYPE "character") :TARGET (:TYPE #1="text" :DROP-TYPEMOD T)) (:SOURCE (:TYPE "varchar") :TARGET (:TYPE #1# :DROP-TYPEMOD T)) (:SOURCE (:TYPE "nvarchar") :TARGET (:TYPE #1# :DROP-TYPEMOD T)) (:SOURCE (:TYPE "char") :TARGET (:TYPE #1# :DROP-TYPEMOD T)) (:SOURCE (:TYPE "nchar") :TARGET (:TYPE #1# :DROP-TYPEMOD T)) (:SOURCE (:TYPE "clob") :TARGET (:TYPE #1# :DROP-TYPEMOD T)) (:SOURCE (:TYPE "tinyint") :TARGET (:TYPE "smallint")) (:SOURCE (:TYPE #2="float") :TARGET (:TYPE #2#) :USING PGLOADER.TRANSFORMS::FLOAT-TO-STRING) (:SOURCE (:TYPE #3="real") :TARGET (:TYPE #3#) :USING PGLOADER.TRANSFORMS::FLOAT-TO-STRING) (:SOURCE (:TYPE "double") :TARGET (:TYPE "double precision") :USING PGLOADER.TRANSFORMS::FLOAT-TO-STRING) (:SOURCE (:TYPE #4="numeric") :TARGET (:TYPE #4#) :USING PGLOADER.TRANSFORMS::FLOAT-TO-STRING) (:SOURCE (:TYPE "blob") :TARGET (:TYPE "bytea") :USING PGLOADER.TRANSFORMS::BYTE-VECTOR-TO-BYTEA) (:SOURCE (:TYPE "datetime") :TARGET (:TYPE #5="timestamptz") :USING PGLOADER.TRANSFORMS::SQLITE-TIMESTAMP-TO-TIMESTAMP) (:SOURCE (:TYPE #6="timestamp") :TARGET (:TYPE #6#) :USING PGLOADER.TRANSFORMS::SQLITE-TIMESTAMP-TO-TIMESTAMP) (:SOURCE (:TYPE #5#) :TARGET (:TYPE #5#) :USING PGLOADER.TRANSFORMS::SQLITE-TIMESTAMP-TO-TIMESTAMP)))) (PGLOADER.SOURCES:*CAST-RULES* (QUOTE NIL)) (PGLOADER.PARAMS:*PG-SETTINGS* (QUOTE NIL)) (PGLOADER.PGSQL::*PGSQL-RESERVED-KEYWORDS* (PGLOADER.PGSQL:LIST-RESERVED-KEYWORDS #7=#<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://roger@UNIX:5432/backblaze {1008ECC4E3}>)) (PGLOADER.PARAMS:*COPY-BATCH-ROWS* (OR NIL PGLOADER.PARAMS:*COPY-BATCH-ROWS*)) (PGLOADER.PARAMS:*COPY-BATCH-SIZE* (OR NIL PGLOADER.PARAMS:*COPY-BATCH-SIZE*)) (PGLOADER.PARAMS:*CONCURRENT-BATCHES* (OR NIL PGLOADER.PARAMS:*CONCURRENT-BATCHES*)) (PGLOADER.PARSER::SOURCE-DB (PGLOADER.UTILS:WITH-STATS-COLLECTION ("fetch" :STATE PGLOADER.PARSER::STATE-BEFORE) (PGLOADER.CONNECTION:EXPAND (PGLOADER.CONNECTION:FETCH-FILE #<PGLOADER.SQLITE:SQLITE-CONNECTION sqlite:///Users/roger/projects/Fun with Data/backblaze/drive_stats.db {1008D88723}>)))) (PGLOADER.PARSER::SOURCE (MAKE-INSTANCE (QUOTE PGLOADER.SQLITE:COPY-SQLITE) :TARGET-DB #7# :SOURCE-DB PGLOADER.PARSER::SOURCE-DB))) (PGLOADER.SOURCES:COPY-DATABASE PGLOADER.PARSER::SOURCE :STATE-BEFORE PGLOADER.PARSER::STATE-BEFORE :INCLUDING (QUOTE NIL) :EXCLUDING (QUOTE NIL)))) :START-LOGGER NIL :SUMMARY NIL :LOG-FILENAME NIL :LOG-MIN-MESSAGES NIL :CLIENT-MIN-MESSAGES NIL)
    10: ((FLET #:CLEANUP-FUN-294 :IN PGLOADER::MAIN)) [cleanup]
    11: (PGLOADER::MAIN ("../../pgloader/build/bin/pgloader" "--debug" "drive_stats.db" "postgresql:///backblaze"))
    12: ((LAMBDA NIL :IN "/Users/roger/projects/pgloader/dumper-2SKVI5f7.lisp"))
    13: ((FLET #:WITHOUT-INTERRUPTS-BODY-87 :IN SAVE-LISP-AND-DIE))
    14: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))
    debugger invoked on a SB-INT:INVALID-ARRAY-INDEX-ERROR in thread
    #<THREAD "main thread" RUNNING {100869F1C3}>:
      Index 0 out of bounds for (SIMPLE-ARRAY CHARACTER
                                 (0)), should be nonnegative and <0.
    
    Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.
    
    restarts (invokable by number or by possibly-abbreviated name):
      0: [ABORT] Exit application
    
    
    debugger invoked on a TYPE-ERROR in thread
    #<THREAD "main thread" RUNNING {100869F1C3}>:
      The value INVOKE-DEBUGGER is not of type SB-DI:FRAME.
    
    Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.
    
    restarts (invokable by number or by possibly-abbreviated name):
      0: [ABORT] Exit application
    
    (SB-DEBUG::FRAME-CALL INVOKE-DEBUGGER :METHOD-FRAME-STYLE :NORMAL :REPLACE-DYNAMIC-EXTENT-OBJECTS NIL)
    0[2] 2015-04-28T15:54:08.240000-04:00 INFO SOURCE: #<PGLOADER.SQLITE:SQLITE-CONNECTION sqlite:///Users/roger/projects/Fun with Data/backblaze/drive_stats.db {1008D88723}>
    2015-04-28T15:54:08.240000-04:00 INFO TARGET: #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://roger@UNIX:5432/backblaze {1008ECC4E3}>
    2015-04-28T15:54:08.240000-04:00 DEBUG LOAD DATA FROM #<PGLOADER.SQLITE:SQLITE-CONNECTION sqlite:///Users/roger/projects/Fun with Data/backblaze/drive_stats.db {1008D88723}>
    2015-04-28T15:54:08.240000-04:00 DEBUG CONNECT #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://roger@UNIX:5432/backblaze {1008ECC4E3}>
    2015-04-28T15:54:08.240000-04:00 FATAL We have a situation here.

**Comment by rfilmyer** [comment]
Meanwhile when I use the sql dump, I get:

    bash-3.2$ !598
    ../../pgloader/build/bin/pgloader --debug backblaze.sql postgresql:///backblaze; ../../pushbullet-exit/pushbullet-exit.sh $?
    sb-impl::*default-external-format* :UTF-8
    tmpdir: #P"/var/folders/g9/ct5f3_r52c37rbls5_9nc_qc0000gn/T/"
    An unhandled error condition has been signalled:
       There is no applicable method for the generic function
         #<STANDARD-GENERIC-FUNCTION PGLOADER.CONNECTION:CONN-TYPE (1)>
       when called with arguments
         (NIL).
    
    Date/time: 2015-04-28-16:00An unhandled error condition has been signalled:
                                  There is no applicable method for the generic function
                                    #<STANDARD-GENERIC-FUNCTION
                                      PGLOADER.CONNECTION:CONN-TYPE (1)>
                                  when called with arguments
                                    (NIL).
    
    Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {100869F1C3}>
    0: ((LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX))
    1: (SB-IMPL::CALL-WITH-SANE-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX) {10087748FB}>)
    2: (SB-IMPL::%WITH-STANDARD-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX) {10087748CB}>)
    3: (PRINT-BACKTRACE :STREAM #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDOUT* {1000295B83}> :START 0 :FROM :DEBUGGER-FRAME :COUNT 4611686018427387903 :PRINT-THREAD T :PRINT-FRAME-SOURCE NIL :METHOD-FRAME-STYLE NIL)
    4: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE-TO-STREAM #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDOUT* {1000295B83}>)
    5: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE #<SIMPLE-ERROR "~@<There is no applicable method for the generic function ~2I~_~S~
              ~I~_when called with arguments ~2I~_~S.~:>" {1008756E33}> :OUTPUT #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDOUT* {1000295B83}> :IF-EXISTS :APPEND :VERBOSE T)
    6: (SIGNAL #<SIMPLE-ERROR "~@<There is no applicable method for the generic function ~2I~_~S~
              ~I~_when called with arguments ~2I~_~S.~:>" {1008756E33}>)
    7: (ERROR "~@<There is no applicable method for the generic function ~2I~_~S~
              ~I~_when called with arguments ~2I~_~S.~:>" #<STANDARD-GENERIC-FUNCTION PGLOADER.CONNECTION:CONN-TYPE (1)> (NIL))
    8: ((:METHOD NO-APPLICABLE-METHOD (T)) #<STANDARD-GENERIC-FUNCTION PGLOADER.CONNECTION:CONN-TYPE (1)> NIL) [fast-method]
    9: (SB-PCL::CALL-NO-APPLICABLE-METHOD #<STANDARD-GENERIC-FUNCTION PGLOADER.CONNECTION:CONN-TYPE (1)> (NIL))
    10: ((FLET #:CLEANUP-FUN-294 :IN PGLOADER::MAIN)) [cleanup]
    11: (PGLOADER::MAIN ("../../pgloader/build/bin/pgloader" "--debug" "backblaze.sql" "postgresql:///backblaze"))
    12: ((LAMBDA NIL :IN "/Users/roger/projects/pgloader/dumper-2SKVI5f7.lisp"))
    13: ((FLET #:WITHOUT-INTERRUPTS-BODY-87 :IN SAVE-LISP-AND-DIE))
    14: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))
    debugger invoked on a SIMPLE-ERROR in thread
    #<THREAD "main thread" RUNNING {100869F1C3}>:
      There is no applicable method for the generic function
        #<STANDARD-GENERIC-FUNCTION PGLOADER.CONNECTION:CONN-TYPE (1)>
      when called with arguments
        (NIL).
    
    Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.
    
    restarts (invokable by number or by possibly-abbreviated name):
      0: [ABORT] Exit application
    
    
    debugger invoked on a TYPE-ERROR in thread
    #<THREAD "main thread" RUNNING {100869F1C3}>:
      The value INVOKE-DEBUGGER is not of type SB-DI:FRAME.
    
    Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.
    
    restarts (invokable by number or by possibly-abbreviated name):
      0: [ABORT] Exit application
    
    (SB-DEBUG::FRAME-CALL INVOKE-DEBUGGER :METHOD-FRAME-STYLE :NORMAL :REPLACE-DYNAMIC-EXTENT-OBJECTS NIL)
    0[2] 2015-04-28T16:00:33.016000-04:00 NOTICE Starting pgloader, log system is ready.
    2015-04-28T16:00:33.032000-04:00 INFO Starting monitor
    2015-04-28T16:00:33.037000-04:00 LOG Main logs in '/private/tmp/pgloader/pgloader.log'
    2015-04-28T16:00:33.037000-04:00 LOG Data errors in '/private/tmp/pgloader/'
    2015-04-28T16:00:33.038000-04:00 FATAL We have a situation here.

**Comment by rfilmyer** [comment]
Are these unrelated issues, or are they the same as this bug?

**Comment by dimitri** [comment]
There's no code in pgloader to handle anything SQL like, so please just feed it with the sqlite binary database file, that's all it knows how to deal with. Looking at your other report...

**Comment by dimitri** [comment]
Can you please run the following query in your sqlite command line tool against your database file and paste the result? If you can send me (here of offline at my profile's email) a SQL dump of the table so that I can reproduce the problem locally that'd be even better.

    PRAGMA table_info(drive_days)

**Comment by rfilmyer** [comment]
sqlite> PRAGMA table_info(drive_days);
    0|model|TEXT|0||0
    1|drive_days||0||0

I put the dump on to [pastebin.com](http://pastebin.com/11XP1dks). The dataset is from [here](https://www.backblaze.com/hard-drive-test-data.html); it's hard drive reliability stats from a cloud storage company, so it's not proprietary or confidential or anything like that.

**Comment by dimitri** [comment]
So, apparently SQLite is quite happy to work with a column that has no type specified. pgloader assume that we know the type of columns, here it's an empty string. I just added a pretty generic conversion to "text", please use the following option if you want `integer` in your specific case, which I think will be the case:

   pgloader --cast "column drive_days.drive_days to integer" drive_stats.db postgresql:///backblaze

Other than that I would advice doing `ALTER TABLE drive_days ALTER COLUMN drive_days TYPE integer;` in the source database...

**Comment by rfilmyer** [comment]
Okay! With that everything seems to be working well, although I discovered another issue with types that I put into issue #227

**Comment by dimitri** [comment]
Cool, one bug at a time though, happy that this one is dealt with now ;-)

**Comment by rfilmyer** [comment]
Of course :smiley:
