### ISSUE TITLE
Sql Server 2000

### ISSUE THREAD

**Issue by jstans** [dimitri/pgloader#221]
The queries are using functions that don't exist in SQL Server 2000 (7.1) such as schema_name, is there a minimum supported version of MSSQL or is there a flag that needs setting to tell it to use an alternative approach?

Thanks.

**Comment by dimitri** [comment]
The current minimum version is SQL Server 2005. The reason it's not written that way in the docs is that I'm interested into expanding the support to older version of SQL Server. Are you in a position to patch the queries in https://github.com/dimitri/pgloader/blob/master/src/sources/mssql/mssql-schema.lisp so as to be compliant that far back?

**Comment by jstans** [comment]
For now I'm getting around the problem by restoring the database to a SQL Server 2008 express installation and working from there. I realise that may not be an option for everyone especially because of the database size limits of the express version. So I'll certainly take a look at modifying the queries if I find the time; my priority right now is to at least get this fully working from the 2008 version.

**Comment by jstans** [comment]
Here's a start:

list-all-indexes:

SELECT  
	SchemaName = u.name,
    TableName = OBJECT_NAME(i.id), 
    IndexName = i.name, 
	ColumnName = co.name,
    is_unique = INDEXPROPERTY(i.id, i.name, 'IsUnique'), 
	is_primary_key = CASE  
		WHEN T.TABLE_NAME IS NOT NULL THEN 1 
		ELSE 0
	END,
	is_clustered = INDEXPROPERTY(i.id, i.name, 'IsClustered')
FROM sysindexes i 
LEFT OUTER JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS T ON T.CONSTRAINT_NAME = i.name
	AND T.TABLE_NAME = OBJECT_NAME(i.id)
	AND T.CONSTRAINT_TYPE = 'PRIMARY KEY'
INNER JOIN sysobjects o ON i.id = o.id
INNER JOIN sysusers u ON o.uid = u.uid
RIGHT JOIN syscolumns co ON o.id = co.id
WHERE (i.indid BETWEEN 1 AND 254) 
    AND (i.Status & 64)=0 
    AND OBJECTPROPERTY(i.id, 'IsMsShipped') = 0

Thanks to http://databases.aspfaq.com/schema-tutorials/schema-how-do-i-list-all-the-indexes-in-a-database.html as a basis.

Unfortunately I'm a bit confused by what the list-all-fkeys query is trying to achieve. INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS seems to exist but not contain anything in my instance of mssql 2000.

**Comment by dimitri** [comment]
Thanks for your first investigation, please update this issue if you get to something more complete. Meanwhile IIUC your migration is already done so it's not urgent anymore for any of us...

**Comment by dimitri** [comment]
Closing the issue in an act of clean-up, please re-open with a compatible query to see it being fixed.
