### ISSUE TITLE
Mysql to Postgres with Crontab

### ISSUE THREAD

**Issue by Summer88** [dimitri/pgloader#223]
Need to get data from a Mysql to a Postgres database on a periodical basis, every 30 min.
If I add the pgloader command to crontab got this error from log:

```
An unhandled error condition has been signalled:
   Failed to connect to pgsql at :UNIX (port 5432): The value of CL-POSTGRES::USER is NIL, which is not of type STRING.

; 
; compilation unit aborted
;   caught 1 fatal ERROR condition
```

if I manually launch the script it run without errors.

I've tried to add user and password to postgresql:///destdb:
```
postgresql:///user:pwd@127.0.0.1/destdb
```

but it doesn't work:

```
An unhandled error condition has been signalled: At

  postgresql:///postgres:pippo@127.0.0.1:5432
                        ^ (Line 1, Column 22, Position 22)

Incomplete parse.
```
What am I missing?
Thanks in advance

**Comment by dimitri** [comment]
The connection string you have is incorrect (see the number of slashes) and should be written:

    postgresql://postgres:pippo@127.0.0.1:5432/
