### ISSUE TITLE
Swap Schema

### ISSUE THREAD

**Issue by jstans** [dimitri/pgloader#224]
Is there any current way to map a schema name from one to another?

i.e. SQL Server's default dbo to Postgres's public.

Thanks.

**Comment by jstans** [comment]
It's easier than I thought to do this once it's in postgres. Though it still might be nice to have as an option.

**Comment by dimitri** [comment]
It would be cool to be able to do that in pgloader itself indeed, for now just add your SQL command(s) in the 'AFTER LOAD DO/EXECUTE' parts, or even the `--after` command line option (which expects a filename where to find SQL statements to execute).

**Comment by chanmix51** [comment]
I was wondering if it was possible to specify to PgLoader that a given set of tables could be imported to a given schema with the ability to specify several groups of tables with every time a different destination schema. 

I could not find this in the documentation.

**Comment by dimitri** [comment]
It's not implemented yet, it's accepted as a todo list item tho.

**Comment by dimitri** [comment]
Closing without support for MS SQL yet for lack of testing facilities. If one of you MSSQL/pgloader users would have a sample database to give me for testing, I could see about hosting it somewhere. Of course if it comes hosted and with remote access (ssh or tcp/1433) that would be even better. Thanks ;-)
