### ISSUE TITLE
Mysql to Postgres change table name

### ISSUE THREAD

**Issue by Summer88** [dimitri/pgloader#228]
I've read documentation  but I'm unable to find how to change the name of the destination table  

with this I select the tables to be copied:
 INCLUDING ONLY TABLE NAMES MATCHING 'cli','mytb','test','lll'

but should I add to get:
table 'cli' copied to 'clients'
table 'mytb' copied to 'themytb'

**Comment by dimitri** [comment]
There's no support for table names and schema names mapping yet in pgloader, that's right. At the moment you can add SQL lines once the COPY is over, in a `AFTER LOAD DO` section. Either one of those depending on what you want to achieve, which is not clear to me:

    ALTER TABLE cli RENAME TO clients;
    INSERT INTO clients SELECT * FROM cli;

**Comment by Summer88** [comment]
hope you will add it, thanks for explanation Dimitri!

**Comment by dimitri** [comment]
FYI, it's been added now, check the `ALTER TABLE` pgloader clause syntax.
