### ISSUE TITLE
Red Hat Linux 6.6 compatible?

### ISSUE THREAD

**Issue by jls14** [dimitri/pgloader#229]
Is 6.6 not supported? I keep getting this error after i installed the rpm:
debugger invoked on a SIMPLE-ERROR in thread
#<THREAD "main thread" RUNNING {1006DB2E63}>:
  Error opening shared object "libsybdb.so":
  libsybdb.so: cannot open shared object file: No such file or directory.

**Comment by dimitri** [comment]
Can you try `yum install freetds`? In recent versions of pgloader it should start fine without the lib unless you need it, that is if you're migrating data from a MS SQL database source.

**Comment by jls14** [comment]
Still getting the same error after doing the yum install

I am just trying to run pgloader --help to see if it will even work and getting this complaint.

I installed the rpm with this command rpm -i pgloader<version>.rpm

This version was from yesterday. Any ideas why this is happening

**Comment by dimitri** [comment]
`libsybdb.so` is provided by the freetds package so my idea why this is happening is because of missing dependency, but you're telling me it's not that. Can you `strace pgloader --help` to see what's happening?

**Comment by jls14** [comment]
This is the last bit that I get.

--- SIGSEGV (Segmentation fault) @ 0 (0) ---
mprotect(0x10007e0000, 32768, PROT_READ|PROT_WRITE|PROT_EXEC) = 0
rt_sigreturn(0x633780)                  = 19354968846
poll([{fd=4, events=POLLIN|POLLPRI}], 1, -1

**Comment by walpino** [comment]
[root@chbo1srv28 tmp]# pgloader --version

debugger invoked on a SIMPLE-ERROR in thread
#<THREAD "main thread" RUNNING {1006DB2DA3}>:
  Error opening shared object "libsybdb.so":
  libsybdb.so: cannot open shared object file: No such file or directory.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [CONTINUE       ] Skip this shared object and continue.
  1: [RETRY          ] Retry loading this shared object.
  2: [CHANGE-PATHNAME] Specify a different pathname to load the shared object from.

(SB-SYS:DLOPEN-OR-LOSE #S(SB-ALIEN::SHARED-OBJECT :PATHNAME #P"libsybdb.so" :NAMESTRING "libsybdb.so" :HANDLE NIL :DONT-SAVE NIL))

**Comment by dimitri** [comment]
Can you try and run the following command then try again:

   sudo ln -s /usr/lib64/libsybdb.so.5 /usr/lib64/libsybdb.so

**Comment by dimitri** [comment]
You can also try the docker image that is now available: https://hub.docker.com/r/dimitri/pgloader/
