### ISSUE TITLE
SQLite text (UTF-8) column convert to string of byte values

### ISSUE THREAD

**Issue by kubina** [dimitri/pgloader#231]
I am trying to import the Wikipedia SQLite dumps (http://dumps.wikimedia.org/htmldumps/dumps/) into postgres using pgloader. The body column in the data table of the SQLite database, which contains the UTF-8 HTML of the articles, gets converted to a string of the byte values in the Postgres database created by pgloader.

The schema for the SQLite database is:

```
$ sqlite3 ab.wikipedia.org.articles.ns0.sqlite3 
SQLite version 3.6.20
sqlite> .schema data
CREATE TABLE data(title TEXT,revision INTEGER,tid TEXT,body TEXT,page_id INTEGER,namespace INTEGER,timestamp TEXT,comment TEXT,user_name TEXT,user_id INTEGER,PRIMARY KEY(title ASC, revision DESC));
```

The Postgres database is imported using
```
pgloader --type sqlite ab.wikipedia.org.articles.ns0.sqlite3 postgres://user:password@localhost/ab

$ pgloader --version
pgloader version "3.2.8e6e67f"
compiled with SBCL 1.2.11
```

The schema for the postgres database is:
```
$ psql -U user ab
psql (9.4.1)
ab=> \d+ data

                          Table "public.data"
  Column   |  Type  | Modifiers | Storage  | Stats target | Description 
-----------+--------+-----------+----------+--------------+-------------
 title     | text   |           | extended |              | 
 revision  | bigint |           | plain    |              | 
 tid       | text   |           | extended |              | 
 body      | text   |           | extended |              | 
 page_id   | bigint |           | plain    |              | 
 namespace | bigint |           | plain    |              | 
 timestamp | text   |           | extended |              | 
 comment   | text   |           | extended |              | 
 user_name | text   |           | extended |              | 
 user_id   | bigint |           | plain    |              | 
```

The SQLite database has the HTML in body:
```
sqlite3 ab.wikipedia.org.articles.ns0.sqlite3 
SQLite version 3.6.20
sqlite> select body from data where title='93';
<!DOCTYPE html>.....</body></html>
```

But in Postgres database contains a string of the bytes values of the HTML:

```
ab=> select body from data where title='93';
 #(60 33 68 79 67 84 89 .... 116 109 108 62)
(1 row)
```

I am on linux (centos) and all my locale are set to en_US.UTF-8. Any suggestions on how to get the Postgres database to store the body as the original text?

**Comment by dimitri** [comment]
I need to add logs information so that we are able to double-check pgloader type conversion choices, and in this case it looks like the SQLite driver just gave binary data to pgloader, which is then used as is. I can reproducing the bug locally, will attempt debugging as soon as possible.

**Comment by dimitri** [comment]
After some research I couldn't find any explanation for such a behavior, and we're using in pgloader the usual C coded sqlite driver (the system's provided .so). So let's just swallow it and hack around receiving unsigned bytes when we know we actually want strings.

I could successfully import your sample wikipedia file here, please let me know about any problem you might still have by re-opening this issue if needs be, or creating new ones.
