### ISSUE TITLE
Error message on CSV load

### ISSUE THREAD

**Issue by jls14** [dimitri/pgloader#234]
Received this error message and I dont understand which row, or what it means exactly.  It all is using UTF-8 encoding and the csv seems normal

```
2015-05-18T18:18:58.461000Z ERROR :UTF-8 stream decoding error on
#<SB-SYS:FD-STREAM
  for "file C:path-to-file\csv\fdskuout.csv"
  {274F29F9}>:

  the octet sequence #(201 32) cannot be decoded.
```

**Comment by dimitri** [comment]
Can you try using `--debug` and maybe both `--debug` and `--verbose` to have more information? Meanwhile, I will see what can be done to have more details in that error message...

**Comment by dimitri** [comment]
Any way to have more information or a sample csv file that triggers the problem?

**Comment by dimitri** [comment]
Note that with the following fix in pgloader you might now have a proper error message: 
https://github.com/dimitri/pgloader/commit/250ed1c7918c26c748da894d499bcc3a8b2f3b29

Please try again with a fresh compile from sources?

**Comment by dominicmauro** [comment]
I'm seeing a similar error. The `pgloader.log` says:

> 2015-11-24T15:56:52.081000-05:00 ERROR :UTF-8 stream decoding error on
> #<SB-SYS:FD-STREAM for "file /Users/dominicmauro/data/ALL_REPORTS.out"
  {1009081673}>:
>
>  the octet sequence #(201 34) cannot be decoded.

I'm using OS X 10.11 and pgloader version 3.2.0 compiled with SBCL 1.2.15. I've attached a [sample file](https://github.com/dimitri/pgloader/files/43217/sample.txt) of the CSV which trips up the parser. The same thing happens when the command file has `client_encoding` set to '`latin1`' or '`UTF8`' – not sure if that makes a difference.

**Comment by dimitri** [comment]
You can specify the encoding of the input file using the `FROM ... WITH ENCODING ...` clause or the `--encoding` command line option. The `client_encoding` is related to what encoding we are using when talking to PostgreSQL and pgloader always speak utf-8 there, so the parameter shouldn't be changed.

It appears to me that the encoding error is genuine:

```lisp
(with-open-file (s "/Users/dim/dev/temp/234.csv"
                            :direction :input
                            :external-format :utf-8)
  (read-line s))
```

Gives the following error message:

```
:UTF-8 stream decoding error on
#<SB-SYS:FD-STREAM for "file /Users/dim/dev/temp/234.csv"
  {100305C693}>:

  the octet sequence #(201 34) cannot be decoded.
   [Condition of type SB-INT:STREAM-DECODING-ERROR]
```

**Comment by dimitri** [comment]
Closing: it's an encoding error.
