### ISSUE TITLE
newsequentialid() error converting from mssql to postgres

### ISSUE THREAD

**Issue by outburstx** [dimitri/pgloader#246]
When trying to convert from a MS SQL Server 2008 database to a PostgreSQL 9.2.7 database, I get the following error:

```
An unhandled error condition has been signalled:
   The value "newsequentialid()"
   is not of type
     (OR NULL (VECTOR (UNSIGNED-BYTE 8) 16)).
```

I am using this command:
```
pgloader mssql://username:password@egServer70/dbname postgresql:///dbname
```

Let me know if I can provide any additional information.

**Comment by dimitri** [comment]
The default values of MSSQL are not all managed by pgloader, see related bugs and fixes in https://github.com/dimitri/pgloader/issues/204 and https://github.com/dimitri/pgloader/pull/210

If you recompile pgloader from sources (I guess you're using a older version) you should be able to get past the current error into another one wherein the `newsequentialid()` function is unknown in PostgreSQL. I will see about properly fixing that, thanks for the report.
