### ISSUE TITLE
Centos5: had to install more packages

### ISSUE THREAD

**Issue by lance-edmodo** [dimitri/pgloader#254]
I downloaded pgloader-3.2.0-22.el6.x86_64.rpm (marked for Centos 4) and installed it on Centos 5.

I had to also install freets-devel and openssl-devel before the PGLoader program would run. Maybe these packages should be in the required list for the RPM builder? And I guess any other packages used by any of the database drivers.

Anyway, great project. I hope to bring it up against Amazon Redshift, which is a variant of Postgres 8.

**Comment by dimitri** [comment]
Are you in a position to contribute to the .spec file for RPM building? That would be great!

Oh, and please consider getting back to me wrt to Redshift, I'm quite interested into hearing about that!

**Comment by dimitri** [comment]
Closing because I decided to not handle RPM packaging anymore, someone will have to step up for that. Building from sources should be easy enough, and there's an automated docker build available at https://hub.docker.com/r/dimitri/pgloader/ if you prefer that.
