### ISSUE TITLE
PGLoader does not work with Amazon Redshift

### ISSUE THREAD

**Issue by ghost** [dimitri/pgloader#255]
Amazon Redshift is a parallelized variant of Postgres.  It started life as (I think) Postgres 8.1, and was then rewired to work in very parallelized ways. Some features were removed, I don't know what. It talks the Postgres protocols, so it seems like PGloader should be able to use it.

When I try to run a job, I get this error:

```
2015-07-04T01:35:18.078000Z NOTICE Starting pgloader, log system is ready.
2015-07-04T01:35:18.143000Z LOG Main logs in 'NIL'
2015-07-04T01:35:18.153000Z LOG Data errors in '/tmp/pgloader/'
2015-07-04T01:35:18.153000Z LOG Parsing commands from file #P"/home/lance/test1.load"
An unhandled error condition has been signalled:
   Database error 42883: function pg_get_keywords() does not exist
HINT: No function matches the given name and argument types. You may need to add explicit type casts.
QUERY: select word
                   from pg_get_keywords()
                  where catcode IN ('R', 'T')
```

**Comment by dimitri** [comment]
This function is used in pgloader so has to decide about which keywords to avoid in table and column names, forcing the use of quotes in those cases. We could handle the error and provide a static list of keywords... and I've just committed a blind patch about that. Please build from sources and try again?

**Comment by lance-edmodo** [comment]
Ok, did a full build and now get this error. array_agg() was added to Postgres in version 8.4. Redshift started as PG 8 or 8.1 and the developers have not felt that compatibility was important. 

Oh well. I think if you want to fully get this you'll need your own free cluster on Amazon. All you need is a credit card :)


2015-07-04T18:59:38.049000-07:00 LOG Main logs in 'NIL'
2015-07-04T18:59:38.053000-07:00 LOG Data errors in '/tmp/pgloader/'
2015-07-04T18:59:38.053000-07:00 LOG Parsing commands from file #P"/home/lance/open/pgloader/test1.load"
2015-07-04T18:59:38.454000-07:00 ERROR Database error 42883: function pg_get_keywords() does not exist
HINT: No function matches the given name and argument types. You may need to add explicit type casts.
QUERY: select word
                   from pg_get_keywords()
                  where catcode IN ('R', 'T')
       table name       read   imported     errors            time
-----------------  ---------  ---------  ---------  --------------
  fetch meta data          2          2          0          0.786s
     create, drop          0          0          0          0.000s
-----------------  ---------  ---------  ---------  --------------
-----------------  ---------  ---------  ---------  --------------
-----------------  ---------  ---------  ---------  --------------
Total import time          0          0          0          0.786s
2015-07-04T18:59:39.455000-07:00 ERROR Database error 42883: function array_agg(name) does not exist
HINT: No function matches the given name and argument types. You may need to add explicit type casts.
QUERY: 
  select relname, array_to_string(array_agg(conname), ',')
    from pg_class c
         join pg_namespace n on n.oid = c.relnamespace
         left join pg_constraint co on c.oid = co.conrelid
    where contype = 'f' and nspname = current_schema()
 group by relname;
2015-07-04T18:59:39.455000-07:00 FATAL Failed to create the schema, see above.

**Comment by dimitri** [comment]
Or you can add the `array_agg` aggregate definition yourself, it's easy enough and documented, see http://www.postgresql.org/docs/8.1/static/xaggr.html and paste:

```sql
CREATE AGGREGATE array_accum (
    sfunc = array_append,
    basetype = anyelement,
    stype = anyarray,
    initcond = '{}'
);
```

Then you can try again and see what's the next blocker...

**Comment by MegaByte** [comment]
I don't think Redshift supports that either (no custom function support and no array support).

**Comment by dimitri** [comment]
We're not using `array_agg()` anymore in pgloader any more, so please retry from current sources?
