### ISSUE TITLE
Please provide up to date package on http://pgloader.io/download.html

### ISSUE THREAD

**Issue by Tarick** [dimitri/pgloader#259]
I need new option "--with 'disable triggers'" and it appears that 3.2.0 debian package on download page doesn't have it. Trying to compile this new version fails as well with:
```
debugger invoked on a ASDF:MISSING-DEPENDENCY-OF-VERSION in thread
#<THREAD "initial thread" RUNNING {10029996A3}>:
  Component "asdf" does not match version 3.0, required by
  #<SYSTEM "asdf-finalizers">
```

Please provide latest builds if possible.

**Comment by dimitri** [comment]
Can you tell me more about your OS (name, version, `lsb_release -a` output if relevant), and your lisp implementation version? (SBCL 1.2.12 say).

**Comment by Tarick** [comment]
Yes, sorry.
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.5 LTS
Release:        12.04
Codename:       precise
Arch: x86_64
Installed sbcl 1.0.55.0-1, currently I'm trying to build sbcl-1.2.13 but have troubles with that as well.
The question is rather not why it fails, but if there is the possibility to have latests builds, since building it is pretty tedious.

**Comment by dimitri** [comment]
Building is quite easy one you have a recent enough SBCL, 1.0.55 is way too old. Will try again to have sbcl and pgloader enter debian backports.

**Comment by mbanck** [comment]
Personally, what I think would be useful would be mostly-statically-linked snapshots that one can use without having to install the SBCL and MSSQL library dependencies. That would allow to try the current development snapshots on systems where one does not have root (which can frequently be the case in DBA environments)

In addition to packages on mainstream distros, I mean.

**Comment by dimitri** [comment]
So I have been working on that with the debian package and pgloader is already available this way, and we are working on having it in apt.postgresql.org too (covering some more distributions, stable and oldstable, and some Ubuntu LTS releases too).

About the snapshots with already linked dependencies, I'm thinking about offering a minimal docker image. Would you use that?

Also, I want to solve the release process so that it's easy for me to release more often, maybe monthly or something like that...

**Comment by mbanck** [comment]
I think a docker image would be useful, just not for me personally.

But yeah, probably it makes most sense to automate the release process and release more often!

**Comment by dimitri** [comment]
An automated docker build is now setup at https://hub.docker.com/r/dimitri/pgloader/.
