### ISSUE TITLE
Problems building on MacOS with MacPorts installed

### ISSUE THREAD

**Issue by Themanwithoutaplan** [dimitri/pgloader#261]
MacPorts is a package management system in the tradition of BSD ports. It differs significantly to Homebrew in that it allows a near complete replacement of Apple's posix packages. This is a philosophical difference as much as anything else.

The current build instructions for pgloader are based entirely around the Homebrew infrastructure. This leads to some problems because library paths maybe different.

Current problems:

* #161 the FreeTDS shared library can't be found, this also prevents the precompiled package from running
* pgloader must be compiled with `COMPRESS_CORE=NO`
* the package builder step fails

The situation might be improved with, either more compile options, or discovery/configure steps. There should also be an `install` target. Compilation with MacPorts installed is usually very similar to compiling from source on BSD or Linux.

One solution might simply be to create a port for pgloader and make use of existing scripts but that wouldn't help test development versions.

It should be possible to run MacPorts and Homebrew next to each other: MacPorts defaults to installing everything in `/opt/local`.

**Comment by dimitri** [comment]
The best way to have at it seems to me that we'd have a MacPorts package for pgloader. Closing this issue...
