### ISSUE TITLE
1.Not null collumns from MSSQL. 2. parallel load 

### ISSUE THREAD

**Issue by galinrustem** [dimitri/pgloader#263]
1. Is it possible in load file 'CAST' section to specify that null values are changed to 0 or " in not null columns with type integer and string ?  a few examples please.
2. When loading from mssql requires "drop schema", which is not very convenient when loading multiple tables in parallel. For exampe: 1 table 80 million records in 1 thread, 2 table 100 million records in the other. How to make so early in the boot schema was not created?

**Comment by dimitri** [comment]
The following casting rule should do what you want for integers, if I understand correcty:

    cast type integer to integer drop not null

I would advice doing so at a column target level tho.

You can use the option `with include no drop` to disable the "clean start" default approach of pgloader.

**Comment by galinrustem** [comment]
2. The scheme was created and I don't need to remove it, I want to download additional.
With my load:
 WITH include no drop, create tables
CAST type ntext to text,
     type smalldatetime to date,
     type integer to integer drop not null
including only table names like 'rost'  in schema 'dbo'
excluding table names like '%arh%', '%zip%', '%gis%', '%sales%' in schema 'dbo';
error:
2015-07-27T19:10:05.026000+05:00 NOTICE Starting pgloader, log system is ready.
2015-07-27T19:10:05.037000+05:00 LOG Main logs in '/tmp/pgloader/pgloader.log'
2015-07-27T19:10:05.042000+05:00 LOG Data errors in '/tmp/pgloader/'
2015-07-27T19:10:05.042000+05:00 LOG Parsing commands from file #P"/home/rustem/aptall2"
Max connections reached, increase value of TDS_MAX_CONN
       table name       read   imported     errors            time
-----------------  ---------  ---------  ---------  --------------
  fetch meta data          7          7          0          1.095s
 create, truncate          0          0          0          0.000s
-----------------  ---------  ---------  ---------  --------------
-----------------  ---------  ---------  ---------  --------------
-----------------  ---------  ---------  ---------  --------------
Total import time          0          0          0          1.095s
2015-07-27T19:10:06.643000+05:00 NOTICE CREATE TABLES
2015-07-27T19:10:06.643000+05:00 NOTICE CREATE SCHEMA dbo;
2015-07-27T19:10:06.644000+05:00 ERROR Database error 42P06:  "dbo"
QUERY: CREATE SCHEMA dbo;
2015-07-27T19:10:06.644000+05:00 FATAL Failed to create the schema, see above.

**Comment by dimitri** [comment]
I now better understand the problem you face: the default options will lead to pgloader dropping the schema itself at startup, rather than what's in the schema, right? I need to see if that should be the default (avoiding to drop the schema or not), and I have some cleanup needed in the code in this area anyway.

**Comment by galinrustem** [comment]
Ok.

**Comment by dimitri** [comment]
So please try again using the `create no schemas` option.
