### ISSUE TITLE
Mix SQL queries with SQL scripts before|after load

### ISSUE THREAD

**Issue by chanmix51** [dimitri/pgloader#265]
It is possible I am misusing `pg_loader` but I could not find an example in the documentation of the following use case:

I need to build a migration framework to drive several data loading from MySql to Postgres. Data will be migrated in a pg schema named `migration` and then dispatched in the new structure using Postgresql rich SQL features. 

Therefore I need to be able to create the `migration` schema and then load some project dependent sql files prior to the loading. The following does not work:

 ```
   BEFORE LOAD DO
       $$ CREATE SCHEMA migration; $$

   BEFORE LOAD EXECUTE
      /some/dir/sources/schema/postgres/before_constraints.sql,
      /some/dir/sources/schema/postgres/new.dump.sql
```

It looks like query and script execution are mutually exclusive, is there a way to do both in a specified order ?

**Comment by dimitri** [comment]
I think they are exclusive just because I didn't think about that use case, I would simply add the create schema command into its own file and add that file in the `EXECUTE` parts. What do you think?

**Comment by dimitri** [comment]
Actually, only a single file is supported by EXECUTE, but you can have `\i` and `\ir` lines just like in psql scripts, so you can have a single `prepare.sql` file with:

    \ir schema.sql
    \i /some/dir/sources/schema/postgres/before_constraints.sql
    \i /some/dir/sources/schema/postgres/new.dump.sql

**Comment by chanmix51** [comment]
It would work of course but prevent people from overriding this schema name. A nice feature would imho be something like:

```
BEFORE LOAD
  DO $$ drop schema if exists migration $$,
  EXECUTE '/some/dir/sources/schema/postgres/before_constraints.sql',
  DO $$ create schema migration $$,
  EXECUTE '/some/dir/sources/schema/postgres/new.dump.sql'
```
This would make pg_loader really flexible. Not an emergency anyway… :innocent:

**Comment by dimitri** [comment]
Well \ir will load a relative file so that you can have a schema.sql file per pgloader command... and it works already without me having to work on it ;-) I will consider implementing more flexibility into the before/after commands blocks tho. Thanks for the use case and idea!

**Comment by dimitri** [comment]
Just had a look at it, and found it's actually simplifying the parser, so that I have absolutely no excuse whatsoever about doing that. So it's in ;-)

**Comment by chanmix51** [comment]
Simple is beautiful :+1: Thank you.
