### ISSUE TITLE
date format before 2000

### ISSUE THREAD

**Issue by infinex** [dimitri/pgloader#266]
Using date format gave the wrong year if before year 2000.I am currently using postgres 9.3.5.

**Comment by dimitri** [comment]
I need more information to be able to help you, like the full command and some error messages or data source and data loaded in PostgreSQL. Better yet, a test case that reproduces your problem (see in https://github.com/dimitri/pgloader/tree/master/test for examples of self-contained test cases).

**Comment by infinex** [comment]
HI, I tried running the the below code by changing the date to before 1999.
The date in the postgres data gave 3999-10-02 00:33:12.123456.

There were no error messages.

```
LOAD CSV
     FROM inline (rownum, ts [date format 'YYYY-MM-DD HH24-MI-SS.US'])
     INTO postgresql:///pgloader?dateformat (rownum, ts)

     WITH truncate,
          fields optionally enclosed by '"',
          fields escaped by double-quote,
          fields terminated by ','

      SET client_encoding to 'latin1',
          work_mem to '12MB',
          standard_conforming_strings to 'on'

   BEFORE LOAD DO
    $$ drop table if exists dateformat; $$,
    $$ create table dateformat (
        rownum smallint,
        ts     timestamp
       );
    $$;

1,1999-10-02 00-33-12.123456
2,2014-10-02 00-33-13.123456
3,2014-10-02 00-33-14.123456
```

**Comment by dimitri** [comment]
Thanks for the report, I integrated your test case into the official one and fixed the bug.
