### ISSUE TITLE
Display width typecasting not handled correctly

### ISSUE THREAD

**Issue by Fryie** [dimitri/pgloader#268]
My MySQL table has the type "int(11)" for the users.id column.

The typecast "CAST column user.id to integer" leads to the following error:
```
INFO CREATE TABLE users
(
  id                     integer(11) not null,
  termination_id         integer(11),
  service_type           text,
  created_at             timestamptz,
  updated_at             timestamptz
);
2015-07-27T16:41:02.440000+01:00 ERROR Database error 42601: syntax error at or near "("
```

it appears the ```(11)``` part is copied over to the new column, but that doesn't make sense in the PostgreSQL context.

**Comment by dimitri** [comment]
Yes, try

    CAST column user.id to integer drop typemod

**Comment by Fryie** [comment]
Ah, should have read the docs more carefully. :) thanks, that works.
