### ISSUE TITLE
create no tables option was broken between 5e7e5391ef0 and 56a89e9b53e

### ISSUE THREAD

**Issue by acatton** [dimitri/pgloader#273]
One of the commit between 5e7e5391ef0 and 56a89e9b53e actually broke the `create no table` option for MySQL import. I wonder if this was intended or not.

Here's the error I got:
```
An unhandled error condition has been signalled: At

  WITH include no drop, create no tables, truncate,  
                                  ^ (Line 5, Column 34, Position 97)

Could not parse WHITESPACE. Expected:

     the character Space
  or the character Tab
  or the character Newline
  or the string "--"
  or the string "/*"

Reached via

     WHITESPACE
  -> (+ (OR Space Tab Newline Newline COMMENTS))
  -> (OR Space Tab Newline Newline COMMENTS)
  -> COMMENTS
  -> (OR SINGLE-LINE-COMMENT MULTI-LINE-COMMENT)
  -> MULTI-LINE-COMMENT
  -> (AND "/*" (+ (NOT "*/")) "*/")
  -> "/*"

Could not parse MYSQL-OPTION. Expected:

     the string "indexes", disregarding case
  or the character Space
  or the character Tab
  or the character Newline
  or the string "--"
  or the string "/*"
  or the string "schemas", disregarding case

Reached via

     ANOTHER-MYSQL-OPTION
  -> (AND COMMA MYSQL-OPTION)
  -> MYSQL-OPTION
  -> (OR OPTION-WORKERS OPTION-BATCH-ROWS OPTION-BATCH-SIZE
         OPTION-BATCH-CONCURRENCY OPTION-TRUNCATE OPTION-DISABLE-TRIGGERS
         OPTION-DATA-ONLY OPTION-SCHEMA-ONLY OPTION-INCLUDE-DROP
         OPTION-CREATE-TABLES OPTION-CREATE-INDEXES OPTION-INDEX-NAMES
         OPTION-RESET-SEQUENCES OPTION-FOREIGN-KEYS OPTION-IDENTIFIERS-CASE)
  -> OPTION-CREATE-INDEXES
  -> (AND KW-CREATE (? KW-NO) KW-INDEXES)
  -> KW-INDEXES
  -> (AND IGNORE-WHITESPACE (~ "indexes") IGNORE-WHITESPACE)
  -> "indexes"

; 
; compilation unit aborted
;   caught 1 fatal ERROR condition
zsh: exit 1     pgloader import.load
```

**Comment by dimitri** [comment]
Certainly not intended, sorry about that. I should improve the testing coverage, it's been on the todo for awhile to have testing support for database sources... thanks for the hint here!

**Comment by willkessler** [comment]
dimitri, pgloader is a massive lifesaver for me.
just a +1 on this bug, it hit me too. I rolled back to 3.2.5e7e539 in order to make things work for now. thanks!!

**Comment by dimitri** [comment]
Are you saying that current HEAD code is still broken?!

**Comment by willkessler** [comment]
I get the message with:

> build/bin/pgloader --version
pgloader version "3.2.56a89e9"
compiled with SBCL 1.1.14.debian

Looks like:

```
An unhandled error condition has been signalled: At

   WITH include drop, create tables, create indexes, reset sequences
                             ^ (Line 5, Column 28, Position 306)

Could not parse KW-NO. Expected:

     the character Space
  or the character Tab
  or the character Newline
  or the string "--"
  or the string "/*"
  or the string "no", disregarding case
```

**Comment by dimitri** [comment]
Fixed by https://github.com/dimitri/pgloader/commit/178210b6f8d0300ef7147daccbe4cfa569decb02 in where I missed the # char.

**Comment by willkessler** [comment]
Cool, I'll give it a try. As I said before, life without pgloader would be miserable...

**Comment by acatton** [comment]
@dimitri, I just wanted to say thank you for handling that so quickly. This is a great project.

**Comment by dimitri** [comment]
@willkessler BTW it looks lire you're only using default options, so you should be able to just:

    pgloader mysql:///foo pgsql:///bar

**Comment by willkessler** [comment]
@dimitri planning on expanding work_mem and maintenance_work_mem to speed it up though.  are those used only during the pgloader session?

**Comment by dimitri** [comment]
yeah, pgloader dynamically change the setting in the SET clause just for when it runs.
