### ISSUE TITLE
Feature Request: how to load multi ARCHIVE files

### ISSUE THREAD

**Issue by WanpengQian** [dimitri/pgloader#278]
Thanks for this nice tools. I can use it to solve my problem.

But I have a lots zip files that contain multi csv files.
when I use LOAD ARCHIVE, it can only process one zip file for a time.

is there any way to process multi-zip file?
like 
```
LOAD ARCHIVE
  FROM ALL FILENAMES IN DIRECTORY ../config
  INTO postgresql:///testdb
...
```
or the FROM can be overide from command line, so I can parse FROM from script, like 
```
#!/bin/bash
pgloader archive.load --FROM=../config/test1.zip
pgloader archive.load --FROM=../config/test2.zip
...
```

thanks.

**Comment by dimitri** [comment]
Currently it's not possible to use that `ALL FILENAMES` clause for archives, only for CSV, COPY and FIXED formats. Will see how much work is required here... thanks for the use case!

**Comment by dimitri** [comment]
Currently there's no way in pgloader to use the load command as a *template* of sorts and override some of its fields from the command line. The archive support is already going a tad to far off the scope of the tool, so I'm not in favor of writing that feature myself.

I would consider a Pull Request implementing load command files as templates, tho.
