### ISSUE TITLE
pgloader mysql://user@localhost/sakila postgresql:///pagila

### ISSUE THREAD

**Issue by algarecu** [dimitri/pgloader#279]
Why am I getting this error in despite of being able to migrate mysql to postgres after hitting 0 in debug console?

```
debugger invoked on a SIMPLE-ERROR in thread
#<THREAD "main thread" RUNNING {1006E666D3}>:
  Error opening shared object "libsybdb.dylib":
  dlopen(libsybdb.dylib, 10): image not found.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [CONTINUE       ] Skip this shared object and continue.
  1: [RETRY          ] Retry loading this shared object.
  2: [CHANGE-PATHNAME] Specify a different pathname to load the shared object from.

(SB-SYS:DLOPEN-OR-LOSE #S(SB-ALIEN::SHARED-OBJECT :PATHNAME #P"libsybdb.dylib" :NAMESTRING "libsybdb.dylib" :HANDLE NIL :DONT-SAVE NIL))
0] 0
```

*** Backup starts throwing warnings about non-existing tables that MySQL schema definition tries to DROP on postgres (that is OK).
*** And ends (with no errors!)

```
Total import time    4974944    4974944          0         56.014s
```

**Comment by dimitri** [comment]
I need your pgloader version here (`pgloader --version`) and I guess it's going to be 3.2.0 or something like that, because it looks like a bug I have fixed already:

  https://github.com/dimitri/pgloader/commit/5f52073

**Comment by algarecu** [comment]
I installed the package from pkg in the pgloader site, which is for an earlier version of OS X (MacOSX 10.9.2) than what I have I have (10.10.5) Yosemite. 

pgloader version "3.1.560c838"
compiled with SBCL 1.2.2.

Building from source as explained in https://github.com/dimitri/pgloader/blob/master/INSTALL.md worked fine and without throwing such error when I use the tool.

**Comment by dimitri** [comment]
Thanks for reporting back and trying current version!
