### ISSUE TITLE
default unix socket path in pgloader.

### ISSUE THREAD

**Issue by WanpengQian** [dimitri/pgloader#286]
I check the document and source, cannot find the define of default unix socket path.
in debian system, the postgresql is build with default unix socket path of ```/var/run/postgresql```
and in redhat like system, the postgresql is build with default unix socket path of ```/tmp```

i just download the package from 
```
http://pgloader.io/files/pgloader-3.1.0-22.el6.x86_64.rpm
```

in this package, the default unix socket path is ```/var/run/postgresql```

I think it is better to change the default unix socket path in rpm build to ```/tmp```,
other wise it will confuse some people, just like me.
take me sometime to figure it out...

**Comment by dimitri** [comment]
You can also `export PGHOST=/tmp` before using pgloader. Also, I will stop releasing binary packages from pgloader and leave that to packagers, they will be able to change that kind of defaults in their build systems.
