### ISSUE TITLE
How to load csv files containing time type values : Got this error  invalid input syntax for type time:

### ISSUE THREAD

**Issue by rbarraco** [dimitri/pgloader#288]
Hi 
i am trying to import data contained in csv files created by DB2. One of the fields is  TIME DB2 format i.e. "HH24.MI.SS"  thus separated by dot.  Postgres expects in the format "HH24:MI:SS" .There is a way to transform it ?
Many thanks 

For example : 
my table is  declared
```sql
create table tgen.prova ( dt timestamp, d_data date,d_ora_msg time );
```

The input file  contains this data  :  

```
 "2015-07-01-00.20.09.411075",20150701,"00.05.02"
```

The load file contains  

```
 LOAD CSV
FROM inp_prova.data
HAVING FIELDS
(
DT [date format 'YYYY-MM-DD-HH24.MI.SS.US'],
D_DATA,
D_ORA_MSG
)

  INTO postgresql:///prova?TGEN.prova

  WITH truncate,
       fields optionally enclosed by '"',
       fields terminated by ','

;
```

**Comment by rbarraco** [comment]
LOAD  CSV
      FROM  inp_prova.data
           HAVING FIELDS
        (
           DT [date format 'YYYY-MM-DD-HH24.MI.SS.US'],
           D_DATA,
           D_ORA_MSG
        )

      INTO postgresql:///prova?TGEN.prova

      WITH truncate,
           fields optionally enclosed by '"',
           fields terminated by ','

;

**Comment by dimitri** [comment]
I just tried here with `[date format 'YYYY-MM-DD HH24.MI.SS.US']` and it works fine. I will need you to provide me with the version of pgloader you are using (`pgloader --version`) and full `--debug --verbose` output, thanks.

**Comment by rbarraco** [comment]
Hi Dimitri
Thanks for your help.
Below what you’ve answered .


pgloader version "3.2.0"
compiled with SBCL 1.2.4.debian


Attached the fully output required .
Thanks


Da: Dimitri Fontaine [mailto:notifications@github.com]
Inviato: venerdì 4 settembre 2015 14:34
A: dimitri/pgloader
Cc: Roberto Barraco
Oggetto: Re: [pgloader] How to load csv files containing time type values : Got this error invalid input syntax for type time: (#288)


I just tried here with [date format 'YYYY-MM-DD HH24.MI.SS.US'] and it works fine. I will need you to provide me with the version of pgloader you are using (pgloader --version) and full --debug --verbose output, thanks.

**Comment by dimitri** [comment]
As I didn't receive your issue as a mail, I don't have the attachement. Please consider uploading on github directly... or sending me an email at my personal address (to be found on my github profile).

**Comment by rbarraco** [comment]
Hi 
here the text 
Many thanks 

sb-impl::*default-external-format* :UTF-8
tmpdir: #P"/tmp/pgloader/"
2015-09-04T16:22:17.089000+03:00 NOTICE Starting pgloader, log system is ready.
2015-09-04T16:22:17.202000+03:00 INFO Starting monitor
2015-09-04T16:22:17.239000+03:00 LOG Main logs in '/tmp/pgloader/pgloader.log'
2015-09-04T16:22:17.239000+03:00 LOG Data errors in '/tmp/pgloader/'
2015-09-04T16:22:17.239000+03:00 LOG Parsing commands from file #P"/var/lib/postgresql/prove/inp_prova.load"
2015-09-04T16:22:17.240000+03:00 DEBUG CONNECT #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://postgres@UNIX:5432/prova {10090373E3}>
2015-09-04T16:22:17.241000+03:00 DEBUG CONNECT #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://postgres@UNIX:5432/prova {10090373E3}>
2015-09-04T16:22:17.241000+03:00 DEBUG BEGIN
                    table name       read   imported     errors            time
------------------------------  ---------  ---------  ---------  --------------
                         fetch          0          0          0          0.062s
------------------------------  ---------  ---------  ---------  --------------
                    TGEN.prova          1          0          1          0.093s
------------------------------  ---------  ---------  ---------  --------------
             Total import time          1          0          1          0.155s
2015-09-04T16:22:17.441000+03:00 NOTICE COPY TGEN.prova
2015-09-04T16:22:17.442000+03:00 DEBUG CONNECT #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://postgres@UNIX:5432/prova {10090373E3}>
2015-09-04T16:22:17.442000+03:00 DEBUG BEGIN
2015-09-04T16:22:17.442000+03:00 NOTICE TRUNCATE tgen.prova;
2015-09-04T16:22:17.442000+03:00 INFO COPY FROM #P"/var/lib/postgresql/prove/inp_prova.data"
2015-09-04T16:22:17.443000+03:00 DEBUG pgsql:copy-from-queue: TGEN.prova NIL
2015-09-04T16:22:17.443000+03:00 DATA < #("2015-07-01 00:20:09.411075" "20150701" "00.05.02")
2015-09-04T16:22:17.443000+03:00 DEBUG CONNECT #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://postgres@UNIX:5432/prova {10090373E3}>
2015-09-04T16:22:17.443000+03:00 DEBUG BEGIN
2015-09-04T16:22:17.444000+03:00 DATA > "2015-07-01 00:20:09.411075	20150701	00.05.02
"
2015-09-04T16:22:17.444000+03:00 ERROR Database error 22007: invalid input syntax for type time: "00.05.02"
CONTEXT: COPY prova, line 1, column d_ora_msg: "00.05.02"
2015-09-04T16:22:17.444000+03:00 INFO Entering error recovery.
2015-09-04T16:22:17.445000+03:00 INFO error recovery at 1/1, processing bad row
2015-09-04T16:22:17.445000+03:00 INFO Recovery found 1 errors in 1 row
2015-09-04T16:22:17.445000+03:00 DEBUG copy-batch TGEN.prova 0 rows
2015-09-04T16:22:17.445000+03:00 INFO Stopping monitor

**Comment by dimitri** [comment]
The failing column is `D_ORA_MSG` where you didn't give any parsing hints, it's sent as read, and as you say the format isn't compatible with PostgreSQL. Please try using a date format here too.

**Comment by rbarraco** [comment]
Hi 
excuse me for the delay . I've changed my load file in this way 
LOAD  CSV
      FROM  inp_prova.data
           HAVING FIELDS
        (
           DT [date format 'YYYY-MM-DD-HH24.MI.SS.US'],
           D_DATA,
           D_ORA_MSG [date format 'HH24.MI.SS']
        )

      INTO postgresql:///prova?TGEN.prova

      WITH truncate,
           fields optionally enclosed by '"',
           fields terminated by ','

;


Here the result 

postgres@vegano:~/prove$ pgloader inp_prova.load
2015-09-07T14:25:01.260000+03:00 LOG Main logs in '/tmp/pgloader/pgloader.log'
2015-09-07T14:25:01.282000+03:00 LOG Data errors in '/tmp/pgloader/'
2015-09-07T14:25:01.283000+03:00 LOG Parsing commands from file #P"/var/lib/postgresql/prove/inp_prova.load"
                    table name       read   imported     errors            time
------------------------------  ---------  ---------  ---------  --------------
                         fetch          0          0          0          0.043s
------------------------------  ---------  ---------  ---------  --------------
                    TGEN.prova          1          0          1          0.075s
------------------------------  ---------  ---------  ---------  --------------
             Total import time          1          0          1          0.118s
2015-09-07T14:25:01.686000+03:00 ERROR Could not read line 1: The value NIL is not of type STRING.
postgres@vegano:~/prove$
 
Regards

**Comment by dimitri** [comment]
Should be ok now with current code (please build from sources). As usual, should you still have problem related to that issue, please just re-open it!

**Comment by rbarraco** [comment]
OK Dimitri 
many thanks

**Comment by rbarraco** [comment]
Hi Dimitri 
i've followed what you suggested (i.e.  buill from sources) . I compiled pgloader and the version is now

pgloader version "3.2.1~devel"
compiled with SBCL 1.1.14.debian

Unfortunately I've received another error descibed below 

--------- Start output pgloader ---
postgres@barraco-ubu-acer:~/prove$  pgloader --verbose --debug inp_prova.load
sb-impl::*default-external-format* :UTF-8
tmpdir: #P"/tmp/pgloader/"
2015-09-09T18:55:26.040000+02:00 NOTICE Starting pgloader, log system is ready.
2015-09-09T18:55:26.077000+02:00 INFO Starting monitor
2015-09-09T18:55:26.089000+02:00 LOG Main logs in '/tmp/pgloader/pgloader.log'
2015-09-09T18:55:26.090000+02:00 LOG Data errors in '/tmp/pgloader/'
2015-09-09T18:55:26.090000+02:00 LOG Parsing commands from file #P"/var/lib/postgresql/prove/inp_prova.load"
2015-09-09T18:55:26.090000+02:00 DEBUG CONNECTED TO #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://postgres@UNIX:5432/prova {100740AE33}>
An unhandled error condition has been signalled:
   Database error 3F000: schema "(tgen" does not exist
QUERY:
    select attname
      from pg_class c
           join pg_namespace n on n.oid = c.relnamespace
           left join pg_attribute a on c.oid = a.attrelid
           join pg_type t on t.oid = a.atttypid
     where c.oid = '(TGEN . prova)'::regclass and attnum > 0
  order by attnum

Date/time: 2015-09-09-18:55An unhandled error condition has been signalled:
                              Database error 3F000: schema "(tgen" does not exist
QUERY:
    select attname
      from pg_class c
           join pg_namespace n on n.oid = c.relnamespace
           left join pg_attribute a on c.oid = a.attrelid
           join pg_type t on t.oid = a.atttypid
     where c.oid = '(TGEN . prova)'::regclass and attnum > 0
  order by attnum


Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1006F632D3}>
0: ((LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX))
1: (SB-IMPL::CALL-WITH-SANE-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX) {100818DA7B}>)
2: (SB-IMPL::%WITH-STANDARD-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX) {100818DA4B}>)
3: (PRINT-BACKTRACE :STREAM #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDOUT* {10002CBC23}> :START 0 :FROM :DEBUGGER-FRAME :COUNT 4611686018427387903 :PRINT-THREAD T :PRINT-FRAME-SOURCE NIL :METHOD-FRAME-STYLE NIL)
4: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE-TO-STREAM #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDOUT* {10002CBC23}>)
5: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE #<CL-POSTGRES:DATABASE-ERROR {1008185083}> :OUTPUT #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDOUT* {10002CBC23}> :IF-EXISTS :APPEND :VERBOSE T)
6: (SIGNAL #<CL-POSTGRES:DATABASE-ERROR {1008185083}>)
7: (ERROR CL-POSTGRES:DATABASE-ERROR :CODE "3F000" :MESSAGE "schema \"(tgen\" does not exist" :DETAIL NIL :HINT NIL :CONTEXT NIL :POSITION NIL)
8: (CL-POSTGRES::GET-ERROR #<SB-SYS:FD-STREAM for "socket, peer: /var/run/postgresql/.s.PGSQL.5432" {10080DB443}>)
9: (CL-POSTGRES::SEND-QUERY #<unavailable argument> #<unavailable argument> #<unavailable argument>)
10: ((LABELS #:G568 :IN CL-POSTGRES:EXEC-QUERY))
11: (POSTMODERN::CALL-WITH-TRANSACTION #<CLOSURE (LAMBDA (#:G474) :IN PGLOADER.PGSQL:LIST-COLUMNS) {10080DF54B}>)
12: (PGLOADER.PGSQL:LIST-COLUMNS #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://postgres@UNIX:5432/prova {100740AE33}> ("TGEN" . "prova") :SCHEMA NIL)
13: ((:METHOD INITIALIZE-INSTANCE :AFTER (PGLOADER.CSV:COPY-CSV)) #<PGLOADER.CSV:COPY-CSV {1008036623}>) [fast-method]
14: ((LAMBDA (SB-PCL::|.P1.|)) #<unavailable argument>)
15: ((LAMBDA ()))
16: (PGLOADER:RUN-COMMANDS #P"/var/lib/postgresql/prove/inp_prova.load" :START-LOGGER NIL :SUMMARY NIL :LOG-FILENAME NIL :LOG-MIN-MESSAGES NIL :CLIENT-MIN-MESSAGES NIL)
17: (PGLOADER::PROCESS-COMMAND-FILE "inp_prova.load")
18: ((FLET #:CLEANUP-FUN-272 :IN PGLOADER::MAIN)) [cleanup]
19: (PGLOADER::MAIN ("pgloader" "--verbose" "--debug" "inp_prova.load"))
20: ((LAMBDA NIL :IN "/home/roberto/Downloads/pgloader-master/dumper-2SKVI5f7.lisp"))
21: ((FLET #:WITHOUT-INTERRUPTS-BODY-54 :IN SAVE-LISP-AND-DIE))
22: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))


debugger invoked on a CL-POSTGRES:DATABASE-ERROR in thread
#<THREAD "main thread" RUNNING {1006F632D3}>:
  Database error 3F000: schema "(tgen" does not exist
QUERY:
    select attname
      from pg_class c
           join pg_namespace n on n.oid = c.relnamespace
           left join pg_attribute a on c.oid = a.attrelid
           join pg_type t on t.oid = a.atttypid
     where c.oid = '(TGEN . prova)'::regclass and attnum > 0
  order by attnum

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit application


debugger invoked on a TYPE-ERROR in thread
#<THREAD "main thread" RUNNING {1006F632D3}>:
  The value INVOKE-DEBUGGER is not of type SB-DI:FRAME.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit application

(SB-DEBUG::FRAME-CALL INVOKE-DEBUGGER :METHOD-FRAME-STYLE :NORMAL :REPLACE-DYNAMIC-EXTENT-OBJECTS NIL)
0[2] 2015-09-09T18:55:26.291000+02:00 DEBUG CONNECTED TO #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://postgres@UNIX:5432/prova {100740AE33}>
2015-09-09T18:55:26.291000+02:00 DEBUG BEGIN
2015-09-09T18:55:26.291000+02:00 ERROR Database error 3F000: schema "(tgen" does not exist
QUERY:
    select attname
      from pg_class c
           join pg_namespace n on n.oid = c.relnamespace
           left join pg_attribute a on c.oid = a.attrelid
           join pg_type t on t.oid = a.atttypid
     where c.oid = '(TGEN . prova)'::regclass and attnum > 0
  order by attnum
2015-09-09T18:55:26.291000+02:00 FATAL We have a situation here.

^C

debugger invoked on a SB-SYS:INTERACTIVE-INTERRUPT in thread
#<THREAD "main thread" RUNNING {1006F632D3}>:
  Interactive interrupt at #x7FFFF71C112D.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [CONTINUE] Return from SB-UNIX:SIGINT.
  1: [ABORT   ] Reduce debugger level (to debug level 2).
  2:            Exit application

("bogus stack frame")
0[3] 2
---- End of output pgloader---

As you can see from the following select command the table tgen.prova exists : 


postgres@barraco-ubu-acer:~/prove$ psql -d prova
psql (9.3.9)
Type "help" for help.

prova=# select * from tgen.prova;
 dt | d_data | d_ora_msg
----+--------+-----------
(0 rows)

prova=#

Thank you for your help 
Regards

**Comment by dimitri** [comment]
You should have:

```
$ ./build/bin/pgloader --version
pgloader version "3.2.60d58a9"
compiled with SBCL 1.2.12
```

**Comment by rbarraco** [comment]
Hi Dimitri
have you already released the 3.2.60 version ?

**Comment by dimitri** [comment]
When building from source the version number ends with the git commit hash.

**Comment by rbarraco** [comment]
Hi 
I have compiled pgloader with a newer version. The situation is now  
postgres@vegano:~/prove$ pgloader --version
pgloader version "3.2.1~devel"
compiled with SBCL 1.2.15
postgres@vegano:~/prove$ 

Unfortunately pgloader gets the same error : 

pgloader --verbose --debug inp_prova.load
sb-impl::*default-external-format* :UTF-8
tmpdir: #P"/tmp/pgloader/"
2015-09-10T15:48:24.057000+02:00 NOTICE Starting pgloader, log system is ready.
2015-09-10T15:48:24.087000+02:00 INFO Starting monitor
2015-09-10T15:48:24.099000+02:00 LOG Main logs in '/tmp/pgloader/pgloader.log'
2015-09-10T15:48:24.099000+02:00 LOG Data errors in '/tmp/pgloader/'
2015-09-10T15:48:24.099000+02:00 LOG Parsing commands from file #P"/var/lib/postgresql/prove/inp_prova.load"
2015-09-10T15:48:24.099000+02:00 DEBUG CONNECTED TO #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://postgres@UNIX:5432/prova {10079E3613}>
An unhandled error condition has been signalled:
   Database error 3F000: schema "(tgen" does not exist
QUERY: 
    select attname
      from pg_class c
           join pg_namespace n on n.oid = c.relnamespace
           left join pg_attribute a on c.oid = a.attrelid
           join pg_type t on t.oid = a.atttypid
     where c.oid = '(TGEN . prova)'::regclass and attnum > 0
  order by attnum

Date/time: 2015-09-10-15:48An unhandled error condition has been signalled:
                              Database error 3F000: schema "(tgen" does not exist
QUERY: 
    select attname
      from pg_class c
           join pg_namespace n on n.oid = c.relnamespace
           left join pg_attribute a on c.oid = a.attrelid
           join pg_type t on t.oid = a.atttypid
     where c.oid = '(TGEN . prova)'::regclass and attnum > 0
  order by attnum


Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10074B6743}>
2015-09-10T15:48:24.300000+02:00 DEBUG CONNECTED TO #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://postgres@UNIX:5432/prova {10079E3613}>
2015-09-10T15:48:24.300000+02:00 DEBUG BEGIN
2015-09-10T15:48:24.300000+02:00 ERROR Database error 3F000: schema "(tgen" does not exist
QUERY: 
    select attname
      from pg_class c
           join pg_namespace n on n.oid = c.relnamespace
           left join pg_attribute a on c.oid = a.attrelid
           join pg_type t on t.oid = a.atttypid
     where c.oid = '(TGEN . prova)'::regclass and attnum > 0
  order by attnum
2015-09-10T15:48:24.300000+02:00 FATAL We have a situation here.
0: ((LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX))
1: (SB-IMPL::CALL-WITH-SANE-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX) {100869068B}>)
2: (SB-IMPL::%WITH-STANDARD-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX) {100869065B}>)
3: (PRINT-BACKTRACE :STREAM #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDOUT* {1000290393}> :START 0 :FROM :DEBUGGER-FRAME :COUNT 4611686018427387903 :PRINT-THREAD T :PRINT-FRAME-SOURCE NIL :METHOD-FRAME-STYLE NIL)
4: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE-TO-STREAM #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDOUT* {1000290393}>)
5: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE #<CL-POSTGRES:DATABASE-ERROR {1008688273}> :OUTPUT #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDOUT* {1000290393}> :IF-EXISTS :APPEND :VERBOSE T)
6: (SIGNAL #<CL-POSTGRES:DATABASE-ERROR {1008688273}>)
7: (ERROR CL-POSTGRES:DATABASE-ERROR :CODE "3F000" :MESSAGE "schema \"(tgen\" does not exist" :DETAIL NIL :HINT NIL :CONTEXT NIL :POSITION NIL)
8: (CL-POSTGRES::GET-ERROR #<SB-SYS:FD-STREAM for "socket, peer: /var/run/postgresql/.s.PGSQL.5432" {10085D7823}>)
9: (CL-POSTGRES::SEND-QUERY #<unavailable argument> #<unavailable argument> #<unavailable argument>)
10: ((LABELS #:G494 :IN CL-POSTGRES:EXEC-QUERY))
11: (POSTMODERN::CALL-WITH-TRANSACTION #<CLOSURE (LAMBDA (#:G440) :IN PGLOADER.PGSQL:LIST-COLUMNS) {10085DA11B}>)
12: (PGLOADER.PGSQL:LIST-COLUMNS #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://postgres@UNIX:5432/prova {10079E3613}> ("TGEN" . "prova") :SCHEMA NIL)
13: ((:METHOD INITIALIZE-INSTANCE :AFTER (PGLOADER.CSV:COPY-CSV)) #<PGLOADER.CSV:COPY-CSV {10085D14A3}>) [fast-method]
14: ((LAMBDA (SB-PCL::|.P1.|)) #<unavailable argument>)
15: ((LAMBDA ()))
16: (PGLOADER:RUN-COMMANDS #P"/var/lib/postgresql/prove/inp_prova.load" :START-LOGGER NIL :SUMMARY NIL :LOG-FILENAME NIL :LOG-MIN-MESSAGES NIL :CLIENT-MIN-MESSAGES NIL)
17: (PGLOADER::PROCESS-COMMAND-FILE "inp_prova.load")
18: ((FLET #:CLEANUP-FUN-264 :IN PGLOADER::MAIN)) [cleanup]
19: (PGLOADER::MAIN ("pgloader" "--verbose" "--debug" "inp_prova.load"))
20: ((LAMBDA NIL :IN "/home/roberto/Downloads/pgloader-master/dumper-2SKVI5f7.lisp"))
21: ((FLET #:WITHOUT-INTERRUPTS-BODY-83 :IN SAVE-LISP-AND-DIE))
22: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))


debugger invoked on a CL-POSTGRES:DATABASE-ERROR in thread
#<THREAD "main thread" RUNNING {10074B6743}>:
  Database error 3F000: schema "(tgen" does not exist
QUERY: 
    select attname
      from pg_class c
           join pg_namespace n on n.oid = c.relnamespace
           left join pg_attribute a on c.oid = a.attrelid
           join pg_type t on t.oid = a.atttypid
     where c.oid = '(TGEN . prova)'::regclass and attnum > 0
  order by attnum

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit application


debugger invoked on a TYPE-ERROR in thread
#<THREAD "main thread" RUNNING {10074B6743}>:
  The value INVOKE-DEBUGGER is not of type SB-DI:FRAME.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit application

(SB-DEBUG::FRAME-CALL INVOKE-DEBUGGER :METHOD-FRAME-STYLE :NORMAL :REPLACE-DYNAMIC-EXTENT-OBJECTS NIL)
0[2] 


Regards

**Comment by dimitri** [comment]
It is still telling version `3.2.1~devel`, are you sure you are using the pgloader binary you just built, to be found in `.//build/bin/pgloader` from the pgloader source repository top directory?

**Comment by rbarraco** [comment]
Hi Dimitri
I have today downloaded the last version from the https://github.com/dimitri/pgloader web site. I've pushed the button "Download ZIP" . Then , after unzip the zip file , I've launched this command:

make COMPRESS_CORE=no DYNSIZE=1024

After the compilation this is the result : 

roberto@barraco-ubu-acer:~/Downloads/pgloader-master/build/bin$ ./pgloader --version
pgloader version "3.2.1~devel"
compiled with SBCL 1.2.15
roberto@barraco-ubu-acer:~/Downloads/pgloader-master/build/bin$

I hope this can help you.
Bye

**Comment by dimitri** [comment]
Please consider doing a git clone of the repository instead. That's what I meant by building from sources, sorry if that was unclear.

    git clone https://github.com/dimitri/pgloader.git
    make COMPRESS_CORE=no DYNSIZE=1024
    ./build/bin/pgloader --version
    ./build/bin/pgloader inp_prova.load

Also the latest release is https://github.com/dimitri/pgloader/releases/tag/v3.2.2 and should provide you with pgloader version 3.2.2 rather than 3.2.1~devel.

**Comment by rbarraco** [comment]
Hi 
I've followed your suggestion to clone 
the situation is now this : 

ostgres@barraco-ubu-acer:~/prove$ pgloader --version 
pgloader version "3.2.e054eb3"
compiled with SBCL 1.2.15
postgres@barraco-ubu-acer:~/prove$ 

postgres@barraco-ubu-acer:~/prove$ pgloader inp_prova.load
An unhandled error condition has been signalled:
   Database error 3F000: schema "(tgen" does not exist
QUERY: 
    select attname
      from pg_class c
           join pg_namespace n on n.oid = c.relnamespace
           left join pg_attribute a on c.oid = a.attrelid
           join pg_type t on t.oid = a.atttypid
     where c.oid = '(TGEN . prova)'::regclass and attnum > 0
  order by attnum


Regards

**Comment by dimitri** [comment]
Thanks for doing that, now I have to look at the bug which I though I already fixed before... Will keep you posted!

**Comment by dimitri** [comment]
Please try again:

    git pull
    make COMPRESS_CORE=no DYNSIZE=1024
    ./build/bin/pgloader --version
    ./build/bin/pgloader inp_prova.load

Should be ok this time, if not, please consider re-opening this issue with more details!

**Comment by rbarraco** [comment]
Hi Dimitri 
It's ok now. Well done.
Thank you very very much
