### ISSUE TITLE
Default casting rules for MySQL

### ISSUE THREAD

**Issue by rikvdkleij** [dimitri/pgloader#290]
Using default casting rules this MySQL column definition:
` 'id' int(9) NOT NULL AUTO_INCREMENT`
is converted to PostgreSQL definition:
 `id BIGINT PRIMARY KEY NOT NULL DEFAULT nextval('user_id_seq'::regclass)`

I wonder why no conversion to Serial or BigSerial data type.

Btw, I tried with version 3.2.0 and 3.2.e054eb3 (built locally from source).
OS: Ubuntu 15.04

**Comment by dimitri** [comment]
I can reproduce it locally, trying to figure out when/how it got broken...

**Comment by dimitri** [comment]
When PostgreSQL is given a SERIAL column type, it will expand it into an `integer` with a default value taken from an associated sequence. Can you please show me the `CREATE TABLE` command sent to PostgreSQL from pgloader, as seen in the logs when using `--verbose` option?

**Comment by rikvdkleij** [comment]
@dimitri I have set option--verbose but I do not see an explicit create table in the /tmp/pgloader/pgloader.log

I see in log:
- copy;
- creating indices
- alter tables to add primary key

**Comment by dimitri** [comment]
Oh then you need `--debug`, my bad.

**Comment by rikvdkleij** [comment]
@dimitri Hmm, in the log:
`INFO CREATE TABLE user 
(
  id                     bigserial not null,
  .....
);`

After that the data is copied, indices and primary key are created.

While after the load:
`id BIGINT PRIMARY KEY NOT NULL DEFAULT nextval('user_id_seq'::regclass)`

**Comment by rikvdkleij** [comment]
@dimitri Btw, also setting custom casting rules for ints with precision in the load file are not working. Probably same issue.

**Comment by dimitri** [comment]
So the conversion targets `big serial` and all is fine. Read http://www.postgresql.org/docs/current/static/datatype-numeric.html#DATATYPE-SERIAL for the whole story.

About the other issue, my wild guess fu isn't great, so I will need to see the load file and the output and a comparison to what you expected to see instead of what you're seeing. We call that level of details a bug report...

**Comment by rikvdkleij** [comment]
Thanks!

The other "issue" has the same clarification.
