### ISSUE TITLE
Cannot parse timestamp from CSV file. 

### ISSUE THREAD

**Issue by gkowalski** [dimitri/pgloader#293]
I'm getting a feeling that parsing an incoming oddball timestamp from a CSV and loading it into postgres is not supported. I have the following data :

```
1198,166,Bruins Football,222,LB,N/A,N/A,Defense,03/31/15,07:39.45.440

1201,166,Bruins Football,333,LB,N/A,N/A,Defense,03/31/15,08:07.36.780
```

Note the Milliseconds on the timestamp field.

I'm trying to read it in with :

```
LOAD CSV
FROM 'test.csv' (
event_id,
event_team_id,
team,
displayed_player_id,
primary_position,
secondary_position,
tertiary_position,
subgroup,
impact_date,
impact_time[ date format 'HH24:MI.SS.MS'] 
```
...

No luck ,

```
Encountered at:
HH24:MI.SS.MS
^ (Line 1, Column 4, Position 4)
2015-09-11T21:22:18.278000+02:00 ERROR Could not read line 2: Incomplete parse.
```

for each record. Is this possible to do ? I need the data and time in separate fields and the milliseconds are critically important . 

George

**Comment by dimitri** [comment]
There were a couple bugs preventing you from achieving what you need with pgloader, should be all good now: you need to build from sources (and from a fresh git clone). Should you have other related problems, please consider opening that issue again.

**Comment by gkowalski** [comment]
Thanks !
