### ISSUE TITLE
MSSQL definition problems

### ISSUE THREAD

**Issue by randomee** [dimitri/pgloader#294]
(apologies if this is not the correct forum, please redirect me if so.)

I'm trying to load data from a MSSQL DB, and it seems I don't have the DB URL correct.

my config file - cleansed to remove personal details: 

```
load database
 from mssql://dbuser:pass@ipaddr:/sourcedb
 to postgresql://dbuser:pass@dbhostname:5432/destdb
WITH create tables
including only table names like 'AUDIT_DETAIL' in schema 'dbo'
including only table names like 'AUDIT' in schema 'dbo'
set work_mem to '16MB', maintenance_work_mem to '512 MB';
```

The odd thing is, in /tmp/pgloader, I have 2 subdirs - one named "destdb" and one named "NIL".  I'm guessing that my DB URL for the source mssql db is somehow wrong.  Also, I get a message 
"Max connections reached, increase value of TDS_MAX_CONN"

Here's the output from the log:

```
pgloader --logfile /tmp/l --debug --client-min-messages debug --verbose direct.pgloader
mkdir -p #P"//tmp/pgloader//"
sb-impl::*default-external-format* :UTF-8
tmpdir: #P"/tmp/pgloader/"
2015-09-14T04:40:03.029000Z NOTICE Starting pgloader, log system is ready.
2015-09-14T04:40:03.060000Z INFO Starting monitor
2015-09-14T04:40:03.066000Z LOG Main logs in '/tmp/l'
2015-09-14T04:40:03.067000Z LOG Data errors in '//tmp/pgloader//'
2015-09-14T04:40:03.067000Z LOG Parsing commands from file #P"/root/direct.pgloader"
Max connections reached, increase value of TDS_MAX_CONN
2015-09-14T04:40:03.268000Z DEBUG CONNECTED TO #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://dbuser@dbhostname:5432/destdb {10074C0F23}>
2015-09-14T04:40:03.268000Z DEBUG SET work_mem TO '16MB'
2015-09-14T04:40:03.269000Z DEBUG SET maintenance_work_mem TO '512 MB'
            table name       read   imported     errors            time
----------------------  ---------  ---------  ---------  --------------
       fetch meta data2015-09-14T04:40:03.469000Z NOTICE DROP then CREATE TABLES
2015-09-14T04:40:03.469000Z DEBUG CONNECTED TO #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://dbuser@dbhostname:5432/destdb {10074C0F23}>
2015-09-14T04:40:03.469000Z DEBUG SET work_mem TO '16MB'
2015-09-14T04:40:03.470000Z DEBUG SET maintenance_work_mem TO '512 MB'
2015-09-14T04:40:03.470000Z DEBUG BEGIN
2015-09-14T04:40:03.470000Z NOTICE Reset sequences
2015-09-14T04:40:03.470000Z DEBUG CONNECTED TO #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://dbuser@dbhostname:5432/destdb {10082A8B73}>
2015-09-14T04:40:03.470000Z DEBUG SET work_mem TO '16MB'
2015-09-14T04:40:03.471000Z DEBUG SET maintenance_work_mem TO '512 MB'
2015-09-14T04:40:03.471000Z DEBUG SET work_mem TO '16MB'
2015-09-14T04:40:03.471000Z DEBUG SET maintenance_work_mem TO '512 MB'
2015-09-14T04:40:03.471000Z DEBUG CONNECTED TO #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://dbuser@dbhostname:5432/destdb {100829D4C3}>
2015-09-14T04:40:03.471000Z DEBUG SET work_mem TO '16MB'
2015-09-14T04:40:03.471000Z DEBUG SET maintenance_work_mem TO '512 MB'
          0          0          0          0.271s
      create, truncate          0          0          0          0.023s
----------------------  ---------  ---------  ---------  --------------
Index Build Completion          0          0          0          0.000s
----------------------  ---------  ---------  ---------  --------------
       Reset Sequences          0          0          0          0.024s
          Primary Keys          0          0          0          0.000s
          Foreign Keys          0          0          0          0.000s
----------------------  ---------  ---------  ---------  --------------
     Total import time          0          0          0          0.318s
2015-09-14T04:40:03.672000Z INFO Stopping monitor
```

**Comment by randomee** [comment]
Hum, ok.  Seems the schema on the MSSQL end was wrong.  It would help if there were a useful error/debug message saying the from table was not found.

**Comment by dimitri** [comment]
Can you try with this `INCLUDE` clause instead and report back?

    including only table names like 'AUDIT_DETAIL', 'AUDIT' in schema 'dbo'

**Comment by randomee** [comment]
I got it reading from the table(s) now.  Seems the MSSQL DBA has those tables in a custom schema.  Thanks.  

Now, I'm having encoding issues.  The source is latin9(ISO8859-15), and postgres really wants the input in UTF8.  

I added "SET client_encoding to 'ISO-8859-15'" to the config.   But I'm getting lots of 
2015-09-14T18:31:15.082000Z ERROR Illegal :UTF-8 character starting at position 12.
(with the position varied of course).

**Comment by dimitri** [comment]
Remove the `client_encoding` bits altogether, pgloader should automatically handle that.

**Comment by randomee** [comment]
No luck.  I tried it without client_encoding, and with.  And by specifying it on the command line as well. 

--debug does not seem to add much to the story.  The illegal char errors start immediately after the "select ..." statement.

**Comment by dimitri** [comment]
Then we need to figure out the MS SQL encoding and have pgloader aware of that. Can you paste the result of the following query adjusted with the schema and table name, so that we can check if MS SQL is providing the right information. pgloader doesn't take care of that yet...

```sql
 select c.column_name, c.data_type,
         c.CHARACTER_SET_NAME,
         c.COLLATION_NAME
    from information_schema.columns c
 where c.table_schema = '...' and c.table_name = '...
```

Other than that, do you know if it's possible with MS SQL to force the `client_encoding` as we do with PostgreSQL?

**Comment by randomee** [comment]
If i remember right, pgloader is using freetds to connect to MSSQL.  If that's right, it looks like it will do some char set conversions.
http://www.freetds.org/userguide/unicodefreetds.htm
Though it might make more sense to use iconv more directly in pgloader?

grep -v column_name char1
data_type:          numeric
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          nvarchar
CHARACTER_SET_NAME: UNICODE
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          nvarchar
CHARACTER_SET_NAME: UNICODE
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          nvarchar
CHARACTER_SET_NAME: UNICODE
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          nvarchar
CHARACTER_SET_NAME: UNICODE
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          numeric
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          nvarchar
CHARACTER_SET_NAME: UNICODE
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          nvarchar
CHARACTER_SET_NAME: UNICODE
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          nvarchar
CHARACTER_SET_NAME: UNICODE
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          nvarchar
CHARACTER_SET_NAME: UNICODE
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          nvarchar
CHARACTER_SET_NAME: UNICODE
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          nvarchar
CHARACTER_SET_NAME: UNICODE
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          numeric
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          nvarchar
CHARACTER_SET_NAME: UNICODE
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          numeric
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          nvarchar
CHARACTER_SET_NAME: UNICODE
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          nvarchar
CHARACTER_SET_NAME: UNICODE
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          nvarchar
CHARACTER_SET_NAME: UNICODE
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          datetime
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          numeric
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          numeric
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          nchar
CHARACTER_SET_NAME: UNICODE
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          numeric
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          datetime
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          datetime
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          char
CHARACTER_SET_NAME: iso_1
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          nvarchar
CHARACTER_SET_NAME: UNICODE
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          nvarchar
CHARACTER_SET_NAME: UNICODE
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          varchar
CHARACTER_SET_NAME: iso_1
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          numeric
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          numeric
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          nvarchar
CHARACTER_SET_NAME: UNICODE
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          nvarchar
CHARACTER_SET_NAME: UNICODE
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          nvarchar
CHARACTER_SET_NAME: UNICODE
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          numeric
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          numeric
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          nvarchar
CHARACTER_SET_NAME: UNICODE
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          numeric
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          nvarchar
CHARACTER_SET_NAME: UNICODE
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          decimal
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          decimal
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          decimal
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          decimal
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          decimal
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          decimal
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          decimal
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          varchar
CHARACTER_SET_NAME: iso_1
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          numeric
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          numeric
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          numeric
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          numeric
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          numeric
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          numeric
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          numeric
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          numeric
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          numeric
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          numeric
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          varchar
CHARACTER_SET_NAME: iso_1
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          int
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          numeric
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          numeric
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          numeric
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          nvarchar
CHARACTER_SET_NAME: UNICODE
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          datetime
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          nvarchar
CHARACTER_SET_NAME: UNICODE
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          numeric
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          nvarchar
CHARACTER_SET_NAME: UNICODE
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          nvarchar
CHARACTER_SET_NAME: UNICODE
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          numeric
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          numeric
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          numeric
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          datetime
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          numeric
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          varchar
CHARACTER_SET_NAME: iso_1
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          numeric
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          nvarchar
CHARACTER_SET_NAME: UNICODE
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          datetime
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          numeric
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          nvarchar
CHARACTER_SET_NAME: UNICODE
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          nvarchar
CHARACTER_SET_NAME: UNICODE
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          decimal
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          int
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          varchar
CHARACTER_SET_NAME: iso_1
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          datetime
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          numeric
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          numeric
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          numeric
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          numeric
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          numeric
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          numeric
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          nvarchar
CHARACTER_SET_NAME: UNICODE
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          nvarchar
CHARACTER_SET_NAME: UNICODE
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          nvarchar
CHARACTER_SET_NAME: UNICODE
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          numeric
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          nvarchar
CHARACTER_SET_NAME: UNICODE
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          nvarchar
CHARACTER_SET_NAME: UNICODE
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          nvarchar
CHARACTER_SET_NAME: UNICODE
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          nvarchar
CHARACTER_SET_NAME: UNICODE
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          nvarchar
CHARACTER_SET_NAME: UNICODE
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          numeric
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          numeric
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          nchar
CHARACTER_SET_NAME: UNICODE
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          numeric
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          varchar
CHARACTER_SET_NAME: iso_1
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          nvarchar
CHARACTER_SET_NAME: UNICODE
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          varchar
CHARACTER_SET_NAME: iso_1
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          nvarchar
CHARACTER_SET_NAME: UNICODE
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          numeric
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          varchar
CHARACTER_SET_NAME: iso_1
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          nvarchar
CHARACTER_SET_NAME: UNICODE
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          numeric
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          numeric
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          nvarchar
CHARACTER_SET_NAME: UNICODE
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          numeric
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          numeric
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          nvarchar
CHARACTER_SET_NAME: UNICODE
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          numeric
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          datetime
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          datetime
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          char
CHARACTER_SET_NAME: iso_1
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          nvarchar
CHARACTER_SET_NAME: UNICODE
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          nvarchar
CHARACTER_SET_NAME: UNICODE
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          nvarchar
CHARACTER_SET_NAME: UNICODE
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          nvarchar
CHARACTER_SET_NAME: UNICODE
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          numeric
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          nvarchar
CHARACTER_SET_NAME: UNICODE
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          numeric
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          numeric
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          int
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          int
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          int
CHARACTER_SET_NAME: NULL
COLLATION_NAME:     NULL

data_type:          varchar
CHARACTER_SET_NAME: iso_1
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          varchar
CHARACTER_SET_NAME: iso_1
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

data_type:          varchar
CHARACTER_SET_NAME: iso_1
COLLATION_NAME:     SQL_Latin1_General_CP1_CI_AS

**Comment by randomee** [comment]
Ok, so changing /etc/freetds/freetds.conf to add this
    [global]
        # TDS protocol version
        tds version = 8.0
        client charset = UTF-8
        dump file = /tmp/freetds.log
        debug flags = 0xffff

makes it happier about text.  now it's complaining about numeric issues.
2015-09-15T17:58:33.906000Z ERROR The value 7398007430430451440
is not of type
  (OR NULL FIXNUM SINGLE-FLOAT DOUBLE-FLOAT (VECTOR CHARACTER) (VECTOR NIL)
      BASE-STRING).
2015-09-15T17:58:33.906000Z ERROR The value 7954895796917364464
is not of type
  (OR NULL FIXNUM SINGLE-FLOAT DOUBLE-FLOAT (VECTOR CHARACTER) (VECTOR NIL)
      BASE-STRING).
... (ad infinitum)

and in the freetds log (i'm sure this does not match the lines above, but I'm guessing it's the same class of error).

17:58:34.278435 25254 (dblib.c:3162):dbdata(0x7fffe0000b30, 30)
17:58:34.278438 25254 (dblib.c:2831):dbcoltype(0x7fffe0000b30, 30)
17:58:34.278441 25254 (dblib.c:3133):dbdatlen(0x7fffe0000b30, 30)
17:58:34.278443 25254 (dblib.c:3142):dbdatlen() type = 108, len= 35
17:58:34.278452 25254 (dblib.c:2217):dbconvert(0x7fffe0000b30, SYBNUMERIC, 0x7fffe005d040, -1, SYBCHAR, 0x7fffef77ffc8, 45)
17:58:34.278457 25254 (dblib.c:2349):dbconvert() calling tds_convert
17:58:34.278461 25254 (dblib.c:2352):dbconvert() called tds_convert returned 8
17:58:34.278463 25254 (dblib.c:2455):dbconvert() outputting 8 bytes character data destlen = 45
17:58:34.278469 25254 (dblib.c:3162):dbdata(0x7fffe0000b30, 31)
17:58:34.278472 25254 (dblib.c:2831):dbcoltype(0x7fffe0000b30, 31)
17:58:34.278475 25254 (dblib.c:3133):dbdatlen(0x7fffe0000b30, 31)
17:58:34.278478 25254 (dblib.c:3142):dbdatlen() type = 108, len= 35
17:58:34.278484 25254 (dblib.c:2217):dbconvert(0x7fffe0000b30, SYBNUMERIC, 0x7fffe005d068, -1, SYBCHAR, 0x7fffef77ffc8, 45)
17:58:34.278505 25254 (dblib.c:2349):dbconvert() calling tds_convert
17:58:34.278509 25254 (dblib.c:2352):dbconvert() called tds_convert returned 20
17:58:34.278512 25254 (dblib.c:2455):dbconvert() outputting 20 bytes character data destlen = 45
17:58:34.278519 25254 (dblib.c:3162):dbdata(0x7fffe0000b30, 32)
17:58:34.278523 25254 (dblib.c:2831):dbcoltype(0x7fffe0000b30, 32)

**Comment by dimitri** [comment]
To be able to debug that error I will need more information, can you try again in `--debug` mode please?

**Comment by dimitri** [comment]
Closing the issue for clean-up. Please re-open with more details if needed, making sure you tried again with a recent pgloader. I believe MS SQL support saw quite some improvements in the meantime.
