### ISSUE TITLE
libsybdb is not loaded when --dry-run is used

### ISSUE THREAD

**Issue by vtzi** [dimitri/pgloader#295]
This is small but annoying bug. 
I had connectivity problems to mssql but was getting different errors when running with and without --dry-run. After digging in the code it apears libsysdb is not loaded on demand when --dry-run is specified, resulting in ffi error.

On a side note it is good to state somewhere the 30 character limitation in FreeTDS for user/password/host. My host was 39 characters :(.

Thanks for the great tool.
  Vlad

**Comment by dimitri** [comment]
Thanks for reporting, the libsybdb bug should now be solved. About the FreeTDS limit you're mentioning, do you have a link to their documentation about that? is it possible to change the limit from some config?

**Comment by vtzi** [comment]
I don't have a link to documentation but it is related to
TDS_MAX_LOGIN_STR_SZ constant which is/was 30 and this check:
https://github.com/FreeTDS/freetds/blob/master/src/dblib/dblib.c#L786

This commit changes it to 128:
https://github.com/FreeTDS/freetds/commit/74e5457faef4d0116b3e8f6944790424efa74890

However either there are no new releases or Ubuntu repos (Ubuntu
14.04.2 LTS) are not updated.

I found few discussions about the issue mentioning the 30 characters
like: https://groups.google.com/d/msg/pymssql/fI4a6T8Yj_k/Fxce4GB8im0J

My problem was with host url - 39 characters. Changed it to resolved
ip adress and everything went well.

**Comment by dimitri** [comment]
Thanks for the details, I'm not too sure if pgloader should be documenting that and how...
