### ISSUE TITLE
Build Error - "*IXF-STREAM*"

### ISSUE THREAD

**Issue by john-lamb** [dimitri/pgloader#296]
Hi Dimitri,

I am having a problem compiling pgloader-3.2.2 on CentOS 6.7 on a clean OS install with only the dependents installed per you instructions: https://github.com/dimitri/pgloader/blob/master/bootstrap-centos.sh

Symbol "*IXF-STREAM*" not found in the IXF package.

```
$ more /etc/system-release
CentOS release 6.7 (Final)
```

I previously tried with version sbcl 1.1.14 and had the same issue

```
$ sbcl --version
SBCL 1.2.15
```

Here is the error message :

```
[package pgloader.ixf]............................
[package pgloader.db3]............................
[package pgloader.mysql]..........................
[package pgloader.sqlite].........................
[package pgloader.mssql]..........................
[package pgloader.syslog].........................
[package pgloader.parser].........................
[package pgloader]................................
..................................................
.................................................;
; caught ERROR:
;   READ error during COMPILE-FILE:
;
;     Symbol "*IXF-STREAM*" not found in the IXF package.
;
;       Line: 70, Column: 25, File-Position: 2414
;
;       Stream: #<SB-INT:FORM-TRACKING-STREAM
;                 for "file /home/john_lamb/pgloader-3.2.2/src/sources/ixf/ixf-schema.lisp"
;                 {100A569AF3}>

debugger invoked on a UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread
#<THREAD "main thread" RUNNING {1002C46CF3}>:
  COMPILE-FILE-ERROR while
  compiling #<CL-SOURCE-FILE "pgloader" "src" "sources" "ixf" "ixf-schema">

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Retry
                                     compiling #<CL-SOURCE-FILE "pgloader" "src" "sources" "ixf" "ixf-schema">.
  1: [ACCEPT                       ] Continue, treating
                                     compiling #<CL-SOURCE-FILE "pgloader" "src" "sources" "ixf" "ixf-schema">
                                     as having been successful.
  2:                                 Retry ASDF operation.
  3: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  4: [ABORT                        ] Give up on "pgloader"
  5: [CONTINUE                     ] Ignore runtime option --eval "(ql:quickload \"pgloader\")".
  6:                                 Skip rest of --eval and --load options.
  7:                                 Skip to toplevel READ/EVAL/PRINT loop.
  8: [EXIT                         ] Exit SBCL (calling #'EXIT, killing the process).

(UIOP/LISP-BUILD:CHECK-LISP-COMPILE-RESULTS NIL T T "~/asdf-action::format-action/" ((#<ASDF/LISP-ACTION:COMPILE-OP > . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "pgloader" "src" "sources" "ixf" "ixf-schema">)))
0]
```

**Comment by dimitri** [comment]
I made some recent API changes in the cl-ixf library used by pgloader, so you need to ensure you have the latest version of it. The easiest way is to `make clean` then `make` again, as that will `git clone` the cl-ixf project again in `build/quicklisp/local-projects/`. You could also `(cd build/quicklisp/local-projects/cl-ixf/ && git pull)` before building again with `make`.

**Comment by john-lamb** [comment]
Thanks for the quick response however I had previously reviewed issue #204 and already done what you suggest. I did try again though and get the same results.

$ cd build/quicklisp/local-projects/cl-ixf/ && git pull
Already up-to-date.

[package pgloader]................................
..................................................
.................................................;
; caught ERROR:
;   READ error during COMPILE-FILE:
;
;     Symbol "*IXF-STREAM*" not found in the IXF package.
;
;       Line: 70, Column: 25, File-Position: 2414

**Comment by john-lamb** [comment]
Correction issue #203

**Comment by dimitri** [comment]
Maybe it's pgloader that's not uptodate then, please git pull pgloader itself...

**Comment by john-lamb** [comment]
I pulled from https://github.com/dimitri/pgloader/archive/master.zip today, is this the latest or should I pull from another link ?

**Comment by dimitri** [comment]
You need to get the current HEAD of the git repository, because there's no release yet with the IXF changes that are not done yet (current tree is stable, but offers incomplete support for IXF yet): 

    git clone https://github.com/dimitri/pgloader.git

**Comment by john-lamb** [comment]
Cool Bananas. Great that did the trip. Thank you so much.

;; loading system "pgloader"
;; loading file #P"/home/john_lamb/git/pgloader/src/hooks.lisp"
[undoing binding stack and other enclosing state... done]
[saving current Lisp image into build/bin/pgloader.tmp:
writing 4944 bytes from the read-only space at 0x20000000
compressed 32768 bytes into 1811 at level -1
writing 4704 bytes from the static space at 0x20100000
compressed 32768 bytes into 1549 at level -1
writing 121962496 bytes from the dynamic space at 0x1000000000
compressed 121962496 bytes into 21802848 at level -1
done]
# that's ugly, but necessary when building on Windows :(
mv build/bin/pgloader.tmp build/bin/pgloader


$ ./pgloader --help
./pgloader [ option ... ] command-file ...
./pgloader [ option ... ] SOURCE TARGET
  --help -h                       boolean  Show usage and exit.
  --version -V                    boolean  Displays pgloader version and exit.
  --quiet -q                      boolean  Be quiet
  --verbose -v                    boolean  Be verbose
  --debug -d                      boolean  Display debug level information.
  --client-min-messages           string   Filter logs seen at the console (default: "warning")
  --log-min-messages              string   Filter logs seen in the logfile (default: "notice")
  --summary -S                    string   Filename where to copy the summary
  --root-dir -D                   string   Output root directory. (default: #P"//tmp/pgloader//")
  --upgrade-config -U             boolean  Output the command(s) corresponding to .conf file for
                                           v2.x
  --list-encodings -E             boolean  List pgloader known encodings and exit.
  --logfile -L                    string   Filename where to send the logs.
  --load-lisp-file -l             string   Read user code from files
  --dry-run                       boolean  Only check database connections, don't load anything.
  --with                          string   Load options
  --set                           string   PostgreSQL options
  --field                         string   Source file fields specification
  --cast                          string   Specific cast rules
  --type                          string   Force input source type
  --encoding                      string   Source expected encoding
  --before                        string   SQL script to run before loading the data
  --after                         string   SQL script to run after loading the data
  --self-upgrade                  string   Path to pgloader newer sources

**Comment by dimitri** [comment]
Have fun, thanks for reporting back!

**Comment by john-lamb** [comment]
FYI I copied the binary to an "Amazon Linux AMI release 2014.09" instance and bingo it works :)

I appreciate your work and support on this, this looks like it's a great tool.

$ ../pgloader csv.load
2015-09-17T19:37:08.071000+01:00 LOG Main logs in 'NIL'
2015-09-17T19:37:08.076000+01:00 LOG Data errors in '/tmp/pgloader/'
2015-09-17T19:37:08.076000+01:00 LOG Parsing commands from file #P"/home2/jlamb/pgload_test/csv.load"
       table name       read   imported     errors            time
-----------------  ---------  ---------  ---------  --------------
            fetch          0          0          0          0.011s
      before load          2          2          0          0.133s
-----------------  ---------  ---------  ---------  --------------
              csv          6          6          0          0.236s
-----------------  ---------  ---------  ---------  --------------
Total import time          6          6          0          0.380s

**Comment by BradRuderman** [comment]
I am also getting this on Amazon Linux AMI Release 2016.03
```
; caught ERROR:
;   READ error during COMPILE-FILE:
;
;     Symbol "*IXF-STREAM*" not found in the IXF package.
;
;       Line: 70, Column: 25, File-Position: 2414
;
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/ec2-user/pgloader-3.2.2/build/quicklisp/dists/quicklisp/software/pgloader-3.2.2/src/sources/ixf/ixf-schema.lisp" {100BEABB73}>

debugger invoked on a UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread
#<THREAD "main thread" RUNNING {100291EBE3}>:
  COMPILE-FILE-ERROR while
  compiling #<CL-SOURCE-FILE "pgloader" "src" "sources" "ixf" "ixf-schema">

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Retry
                                     compiling #<CL-SOURCE-FILE "pgloader" "src" "sources" "ixf" "ixf-schema">.
  1: [ACCEPT                       ] Continue, treating
                                     compiling #<CL-SOURCE-FILE "pgloader" "src" "sources" "ixf" "ixf-schema">
                                     as having been successful.
  2:                                 Retry ASDF operation.
  3: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  4: [ABORT                        ] Give up on "pgloader"
  5: [CONTINUE                     ] Ignore runtime option --eval "(ql:quickload \"pgloader\")".
  6:                                 Skip rest of --eval and --load options.
  7:                                 Skip to toplevel READ/EVAL/PRINT loop.
  8: [EXIT                         ] Exit SBCL (calling #'EXIT, killing the process).

(UIOP/LISP-BUILD:CHECK-LISP-COMPILE-RESULTS NIL T T "~/asdf-action::format-action/" ((#<ASDF/LISP-ACTION:COMPILE-OP > . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "pgloader" "src" "sources" "ixf" "ixf-schema">)))
```

With

```
$ sudo sbcl --version
SBCL 1.3.6
```
