### ISSUE TITLE
Bug " T names a defined constant, and cannot be used as a local variable. "

### ISSUE THREAD

**Issue by jacques-p** [dimitri/pgloader#297]
Table with a column named T can't be loadede with pgloader (no problem with COPY directely).
Dimitri F. said to me the bug " T names a defined constant, and cannot be used as a local variable. " is due to the fact pgloader is made from Common Lisp compilator.

Has anyone got an idea for solving this issue ?

Test made :
```
-- table creation :
psql -d theBase -U a_dba_account
psql (9.4.0)
CREATE TABLE tutu(a integer, b timestamp without time zone, c real, t real);
GRANT all ON tutu TO anonymous;
```

```
-- with the command file pgloader_commands.txt :
LOAD CSV
FROM './data_to_load.csv' (a, b, c, t)
INTO postgresql://anonymous:anonymous@theMachine:5432/theBase?tutu(a,b,c,t)
WITH fields terminated by ';'
;
```

```
-- and the data file data_to_load.csv :
100;2015-01-01 00:00:00;-6;10
101;2015-01-02 00:00:00;-2.1;12.5
102;2015-01-03 00:00:00;3.4;5.5
103;2015-01-04 00:00:00;4.7;-2.3
104;2015-01-05 00:00:00;0.4;0
```

```
-- launch of pgloader :
pgloader ./pgloader_commands.txt
```

**Comment by jacques-p** [comment]
Table with a column named T can't be loadede with pgloader (no problem with COPY directely).
Dimitri F. said to me the bug " T names a defined constant, and cannot be used as a local variable. " is due to the fact pgloader is made from Common Lisp compilator.

Has anyone got an idea for solving this issue ?

Test made :
-- table creation :
psql -d theBase -U a_dba_account
psql (9.4.0)
CREATE TABLE tutu(a integer, b timestamp without time zone, c real, t real);
GRANT all ON tutu TO anonymous;

-- with the command file pgloader_commands.txt :
LOAD CSV
FROM './data_to_load.csv' (a, b, c, t)
INTO postgresql://anonymous:anonymous@theMachine:5432/theBase?tutu(a,b,c,t)
WITH fields terminated by ';'
;

-- and the data file data_to_load.csv :
100;2015-01-01 00:00:00;-6;10
101;2015-01-02 00:00:00;-2.1;12.5
102;2015-01-03 00:00:00;3.4;5.5
103;2015-01-04 00:00:00;4.7;-2.3
104;2015-01-05 00:00:00;0.4;0

-- launch of pgloader :
pgloader ./pgloader_commands.txt

**Comment by dimitri** [comment]
Please build from sources and try again, should work now.
