### ISSUE TITLE
End of data when type error found in row (CSV Import)

### ISSUE THREAD

**Issue by lunswor** [dimitri/pgloader#300]
I have a CSV file i'm importing into postgres which is around 200k rows but has 3 rows of which has an overflow for one column. On my dev server this just skips the 3 rows and continues with the import and all works how I hope.
On my production server I can't seem to get the exact same version of pgloader and end up with the following errors.

Its worth also noting I have used the exact same CSV and loader script to import this. I can add the loader script if needed.

    2015-10-03T21:07:40.447000Z DEBUG BEGIN
    2015-10-03T21:07:40.648000Z DEBUG copy-batch awproducts 10000 rows
    2015-10-03T21:07:41.670000Z DEBUG BEGIN
    2015-10-03T21:07:41.870000Z DEBUG copy-batch awproducts 10000 rows
    2015-10-03T21:07:42.918000Z DEBUG BEGIN
    2015-10-03T21:07:43.119000Z ERROR Database error 22003: numeric field overflow
    DETAIL: A field with precision 10, scale 5 must round to an absolute value less than 10^5.
    CONTEXT: COPY awproducts, line 280, column search_price: "708000"
    2015-10-03T21:07:43.119000Z INFO Entering error recovery.
    2015-10-03T21:07:43.120000Z DEBUG BEGIN
    2015-10-03T21:07:43.120000Z INFO error recovery at 0/10000, next error at 280, loading 279 rows

    debugger invoked on a TYPE-ERROR in thread
    #<THREAD "lparallel" RUNNING {100A3F1883}>:
      The value NIL is not of type PGLOADER.UTILS::PGTABLE.
    2015-10-03T21:07:43.320000Z INFO error recovery at 280/10000, processing bad row
    2015-10-03T21:07:48.752000Z DEBUG Sending last batch (9018 rows)
    2015-10-03T21:07:48.752000Z DEBUG End of data.

My dev server which works is running the following version so i tried to compile this from source

    pgloader version "3.2.0"
    compiled with SBCL 1.2.4.debian

When I tried compiling 3.2.0 from source and I get the following error on build
    
    [package pgloader.mysql]..........................
    [package pgloader.sqlite].........................
    [package pgloader.mssql]..........................
    [package pgloader.syslog].........................
    [package pgloader.parser].........................
    [package pgloader]................................
    ..........................;
    ; caught ERROR:
    ;   READ error during COMPILE-FILE:
    ;
    ;     Symbol "*IXF-STREAM*" not found in the IXF package.
    ;
    ;       Line: 61, Column: 25, File-Position: 2071
    ;
    ;       Stream: #<SB-SYS:FD-STREAM
    ;                 for "file /home/lee/pgloader/src/sources/ixf/ixf-schema.lisp"
    ;                 {1008720C03}>

    debugger invoked on a UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread
    #<THREAD "main thread" RUNNING {1002A8B923}>:
      COMPILE-FILE-ERROR while
      compiling #<CL-SOURCE-FILE "pgloader" "src" "sources" "ixf" "ixf-schema">

    Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

    restarts (invokable by number or by possibly-abbreviated name):
      0: [RETRY   ] Retry
                    compiling #<CL-SOURCE-FILE "pgloader" "src" "sources" "ixf" "ixf-schema">.
      1: [ACCEPT  ] Continue, treating
                    compiling #<CL-SOURCE-FILE "pgloader" "src" "sources" "ixf" "ixf-schema">
                    as having been successful.
      2: [ABORT   ] Give up on "pgloader"
      3: [CONTINUE] Ignore runtime option --eval "(ql:quickload \"pgloader\")".
      4:            Skip rest of --eval and --load options.
      5:            Skip to toplevel READ/EVAL/PRINT loop.
      6: [EXIT    ] Exit SBCL (calling #'EXIT, killing the process).

**Comment by lunswor** [comment]
FYI copying the binary from the working server to development made everything work ok but its not ideal.

**Comment by dimitri** [comment]
The build error you have is because of a later patch in IXF where the API has changed. You can either force a checkout of `build/quicklisp/cl-ixf` on the version tagged v0.9 (https://github.com/dimitri/cl-ixf/tree/v0.9), which is before the API change (as you're not using IXF anyway) or more simply work from current master branch.

About copying the binary, that is exactly what a packaging system would do for you anyway, I'm not sure about it not being ideal: it's a good way to be sure you are running in production the version you just validated in dev, right?

**Comment by dimitri** [comment]
Closing the issue here because it seems to be related to a bug that's already been fixed. Re-open with more details if you need to!
