### ISSUE TITLE
pgloader fails on geolite example listed on pgloader.io

### ISSUE THREAD

**Issue by htmldoug** [dimitri/pgloader#301]
I can't get pgloader to successfully run the [geolite example](http://pgloader.io/howto/geolite.html) listed on the web site.

## pgloader 3.2.0
I'm on OS X 10.10.5, so I first tried the latest homebrew version at 3.2.0 which produces the following error:
```
$ pgloader geolite.load
An unhandled error condition has been signalled: At

  /*

  ^ (Line 1, Column 0, Position 0)

Could not parse subexpression "into" when parsing
...
```
Here's a gist with the full --debug output: https://gist.github.com/htmldoug/31183f7077dde5401cd2

## pgloader latest master
I saw in another issue you recommended compiling from source, so I compiled at c3726ce and got a different parsing error:
```
~/code/pgloader/build/bin/pgloader geolite.load
2015-10-08T01:56:29.018000-04:00 LOG Main logs in '/private/tmp/pgloader/pgloader.log'
2015-10-08T01:56:29.020000-04:00 LOG Data errors in '/private/tmp/pgloader/'
2015-10-08T01:56:29.020000-04:00 LOG Parsing commands from file #P"/Users/doug/pgloader/geolite.load"
2015-10-08T01:56:29.021000-04:00 FATAL We have a situation here.
An unhandled error condition has been signalled: At

                  region     null if blanks,
                             ^ (Line 44, Column 28, Position 1443)

Could not parse COMMA. Expected:

  the character , (COMMA)
...
```
Another gist with --debug output is here: https://gist.github.com/htmldoug/5e6fe237fd840bf1d7ec

## pgloader v3.2.2 => won't compile
Seeing there's a newer stable pgloader release than what's in homebrew, I intended to build and try v3.2.2, but couldn't get `make clean && make` to complete successfully. Updating to the latest version of sbcl didn't help.

```
...
; caught ERROR:
;   READ error during COMPILE-FILE:
;
;     Symbol "*IXF-STREAM*" not found in the IXF package.
;
;       Line: 70, Column: 25, File-Position: 2414
;
;       Stream: #<SB-INT:FORM-TRACKING-STREAM
;                 for "file /Users/doug/code/pgloader/src/sources/ixf/ixf-schema.lisp"
;                 {100B92CE23}>
...
```

Here's the log from that: https://gist.github.com/htmldoug/55c07f4a63e9942eaf7c

**Comment by dimitri** [comment]
See the example https://github.com/dimitri/pgloader/blob/master/test/archive.load where the per input field options syntax has changed (as covered in the docs) and is now to put in square brackets to make it possible to have several options:

```
(
                locId,
                country,
                region     [ null if blanks ],
                city       [ null if blanks ],
                postalCode [ null if blanks ],
                latitude,
                longitude,
                metroCode  [ null if blanks ],
                areaCode   [ null if blanks ]
             )
``

**Comment by dimitri** [comment]
About building from sources, make clean should have removed your local copy of the IXF system in `build/quicklisp/local-projects/cl-ixf/` and cloned a new one. There has been an incompatible API change in cl-ixf recently to allow for supporting the file format more completely.
