### ISSUE TITLE
Unexpected token on sqlite conversion

### ISSUE THREAD

**Issue by waghanza** [dimitri/pgloader#302]
Hi,

I'm new on pgloader. I want to convert databases (from `sqlite` to postresql`).

I have this file
~~~sh
load database  
  from 'test.db'
  into postgresql://postgres@127.0.0.1:5432/test
  with include drop, create tables, create indexes, reset sequences 
  set work_mem to '16MB', maintenance_work_mem to '512 MB';
~~~
to load my **sqlite** data on my **postgresql** database.
When I run `pgloader sqlite.load`, I have
~~~sh
An unhandled error condition has been signalled:
   The assertion (= 1 (LENGTH PGLOADER.SQLITE::TOKENS)) failed with
   (LENGTH PGLOADER.SQLITE::TOKENS) = 2.
~~~
Regards,
PS : I'm on a `debian jessie` with `pgloader 3.1.0`

**Comment by dimitri** [comment]
To be able to fix bugs here I will need the full stack trace, as you can get with the `--debug` option. Also, please note that I can parse your load file here with current master version of pgloader, so consider using a more recent version (3.2.2 is available from https://wiki.postgresql.org/wiki/Apt -- apt.postgresql.org).

If you still experience the bug with 3.2.2, please consider building from sources too, you will need that anyway once I push a fix (if needed).

**Comment by waghanza** [comment]
I have create a gist : https://gist.github.com/waghanza/7f092d6b32b7a88fee1a
This is the trace for
~~~sh
pgloader --verbose --check sqlite.load
~~~

PS : I have upgraded to `3.2.2`

**Comment by dimitri** [comment]
Could you run the following query in your sqlite database from the sqlite prompt, please?

    PRAGMA table_info(products);

Having *integer auto_increment* in there is news to me...

**Comment by waghanza** [comment]
There it is 
~~~
0|id|integer auto_increment|0||1
1|ticket|text|0||0
2|identifier|text|0||0
3|season_id|text|0||0
4|name|text|0||0
5|open|text|0||0
~~~

**Comment by dimitri** [comment]
Just done some testing and found very strange behavior on SQLite side of things. Please test just posted patch, it should allow your migration to happen but might lose values for the id column when declared in that way, because SQLite is not returning anything but NULLs here, apparently:

```sqlite
sqlite> create table autoinc(id integer auto_increment primary key, ticket text);

sqlite> insert into autoinc(ticket) values('a'), ('b'), ('c');

sqlite> select * from autoinc;
|a
|b
|c

sqlite> pragma table_info(autoinc);
0|id|integer auto_increment|0||1
1|ticket|text|0||0

sqlite> select rowid, id, ticket from autoinc;
1||a
2||b
3||c

sqlite> select rowid, id, id is null, ticket from autoinc;
1||1|a
2||1|b
3||1|c
```

**Comment by waghanza** [comment]
It works

Thanks, @dimitri 

I have built this from source, but will this patch be in official `pgloader` package for `debian` ?

**Comment by dimitri** [comment]
Sure, at next release. And the package will make its way to sid, testing and apt.postgresql.org for stable releases and ubuntu. Thanks for the feedback, have fun with PostgreSQL!

**Comment by waghanza** [comment]
To add a precision, I had to use the precise syntax
~~~
id integer primary key autoincrement
~~~
 instead of
~~~
integer auto_increment primary key
~~~
to have an `id`  as an integer instead of `null`

very strange from `sqlite`

source : http://sqlite.1065341.n5.nabble.com/insert-default-values-td12414.html
