### ISSUE TITLE
Building with ccl fails: Error: The function GETENV is predefined in Clozure CL

### ISSUE THREAD

**Issue by tilthouse** [dimitri/pgloader#303]
I cannot seem to build pgloader using the latest release of CCL.
```
~/pgloader$ make CL=/usr/local/bin/ccl64
mkdir -p build
curl -o build/quicklisp.lisp http://beta.quicklisp.org/quicklisp.lisp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 57144  100 57144    0     0  1166k      0 --:--:-- --:--:-- --:--:-- 1187k
/usr/local/bin/ccl64 --no-init --load build/quicklisp.lisp                        \
             --load src/getenv.lisp                                               \
             --eval '(quicklisp-quickstart:install :path "build/quicklisp" :proxy (getenv "http_proxy"))' \
             --eval '(quit)'

  ==== quicklisp quickstart 2015-01-28 loaded ====

    To continue with installation, evaluate: (quicklisp-quickstart:install)

    For installation options, evaluate: (quicklisp-quickstart:help)

> Error: The function GETENV is predefined in Clozure CL.
> While executing: CCL::REDEFINE-KERNEL-FUNCTION, in process listener(1).
> Type :GO to continue, :POP to abort, :R for a list of available restarts.
> If continued: Replace the definition of GETENV.
> Type :? for other options.
1 >
```

```
$ ccl64 --version
Version 1.10-r16196  (LinuxX8664)
```

**Comment by dimitri** [comment]
What I have here is another error. Can you make sure you have the most recent pgloader git master checkout please?

```
;; loading system "pgloader"
Fatal SIMPLE-ERROR:
  Compilation failed: In MAKE-DOUBLE-FLOAT: Type declarations violated in (THE FIXNUM 4294967295) in /Users/dim/dev/pgloader/build/quicklisp/local-projects/qmynd/src/common/utilities.lisp
Fatal error in "buildapp" : Error #<SILENT-EXIT-ERROR #xC3671F6>
```

**Comment by tilthouse** [comment]
Yes, i'm on latest master for pgloader. 

It does appear that quicklisp is putting stuff into `~/quicklisp` instead of the `build` directory. If I change the Makefile to use that, I get further

**Comment by tilthouse** [comment]
Okay, I can get past it by manually pasting in `(quicklisp-quickstart:install :path "build/quicklisp" :proxy (getenv "http_proxy"))` into the prompt after the error. Now I get:  
```
Fatal error in "pgloader" : Filename "/tmp\\/pgloader/" contains illegal character #\/
```

I also had to really force it to use ccl64 by symlinking ccl to ccl64.

**Comment by dimitri** [comment]
I just pushed a fix that should allow you to get past this error!

**Comment by djbusby** [comment]
Using latest CCL and git-master of pgloader from today I saw this issue as well.  Entering the commands from @tilthouse (two above) the process continues but no pgloader is built.

I'm on master:
    3673c5c - Dimitri Fontaine, 2 days ago : Add a Travis CI Build badge.

    /opt/ccl/lx86cl64 --version
    Version 1.10-r16196  (LinuxX8664)

    Linux: 3.13.0-48-generic; Ubuntu Trusty

**Comment by dimitri** [comment]
@djbusby do you have a build log to share?

**Comment by Enalmada** [comment]
I had the same problem..."Error: The function GETENV is predefined." from git pull of source.
Seems like quicklisp is being installed to my home directory and not build directory (for me I found quicklisp at /home/ubuntu/quicklisp) causing bad things to happen.
My workaround for those struggling with same issue, edit the makefile:
line 21 - change QLDIR variable to $HOME/quicklisp
remove lines 86 to 92 - the $(QLDIR)/setup.lisp block 

Hopefully this workaround also helps @dimitri figure out what might be going wrong to cause this in the first place.

**Comment by dimitri** [comment]
I think we fixed it, so I'm closing the issue. If you still have the problem, please open it again.
