### ISSUE TITLE
sslmode and client certificates?

### ISSUE THREAD

**Issue by bazeli** [dimitri/pgloader#308]
Hello,

I'm looking to connect to a postgres server on the same subnet using SSL with client certificate authentication.  While I've read in the pgloader documentation that the only user definable option is `sslmode`, I'm assuming pgloader follows the postgres standard of looking for client certificates in `~/.postgresql/postgresql.crt`.    Unforunately, I'm getting the following error:

`Database error 28000: connection requires a valid client certificate`

**Postgres connection string** portion of pgloader is:

`postgresql://dbuser@dbserver/userdb?sslmode=prefer`

**pg_hba.conf:**

`hostssl    userdb             +sslcertusers             privateip          cert   clientcert=1`

(sslcertusers is a table containing a valid record for "dbuser")

**postgresql.conf**

```
ssl = true	
ssl_cert_file = '/var/lib/postgresql/9.4/main/server.crt'
ssl_key_file = '/var/lib/postgresql/9.4/main/server.key'
ssl_ca_file = '/var/lib/postgresql/9.4/main/root.crt'
```

Client certificates are signed via in-house CA.  The client certificate itself is functioning correctly when using **psql on the command line**:

```
psql -h dbserver -U dbuser userdb
psql (9.4.4)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.
```

and **verified as OK by openssl**:

```user@webserver:~/.postgresql$ openssl verify -CAfile root.crt -purpose sslclient postgresql.crt
postgresql.crt: OK```

I have also tried exporting the PGSSLCERT and PGSSLCERT env vars standard to postgres, but still can't seem to connect with pgloader.   As a last resort, I have confirmed that pgloader does in fact connect fine when I modify my pg_hba.conf file to allow for md5 based authentication without SSL.

Surely I must be missing something - any help would be most appreciated.

**Comment by dimitri** [comment]
Hi, I am not sure the PostgreSQL driver we use in pgloader allows for SSL Client Certificates yet, see at http://marijnhaverbeke.nl/postmodern/. Will inquire time permitting, meanwhile if that's an option for you, consider another security setup?

**Comment by bazeli** [comment]
Thanks very much for the response - looking at the postmodern docs, it states that SSL support is provided by CL+SSL.   On the CL+SLL reference page it provides API documentation for the `CL+SSL:MAKE-SSL-CLIENT-STREAM` function, which takes as parameters file paths pointing to the client certificate and client key. 

https://common-lisp.net/project/cl-plus-ssl/ 

Knowing nothing about CL, my fingers are crossed that this will be an easy fix. :)

**Comment by bazeli** [comment]
Even better - postmodern, at least according to the docs, does support SSL certificate files:

http://marijnhaverbeke.nl/postmodern/cl-postgres.html#connecting

```
variable *ssl-certificate-file*
variable *ssl-key-file*

When using SSL (see open-database), these can be used to provide client key and certificate files. They can be either NIL, for no file, or a pathname.

```

Support for this in pgloader would be extremely helpful for cases where the network is somewhat untrusted (VPS), running without a VPN.   Perhaps it could work something along the lines of libpq:

http://www.postgresql.org/docs/9.1/static/libpq-ssl.html#LIBPQ-SSL-FILE-USAGE

**Comment by dimitri** [comment]
We can implement the *client certificate* and *client private key* parts thanks to matching postmodern API, but I think we will lack *trusted certificate authorities* and *certificates revoked by certificate authorities* that libpq provides. Does that sounds good enough for you?

Also, the setup would be dependent on the existence of the `~/.postgresql/postgresql.crt` and `~/.postgresql/postgresql.key` files on the file-system, plus the usage of the right ssl mode of course.

**Comment by dimitri** [comment]
Please test with this patch and report back, hopefully I didn't break non-ssl connections and you should get support for your client side certificates...

**Comment by bazeli** [comment]
Thank you very much for the patch - I've tested and encountered the following error:

```
An unhandled error condition has been signalled:
   Failed to connect to pgsql at "dbserver" (port 5432) as user "dbuser": /home/dbuser/.postgresql/postgresql.key is not a Lisp string or pointer.
```

**Comment by dimitri** [comment]
Can you please retry in `--debug` mode so that we have a full stack trace and more details?

**Comment by bazeli** [comment]
Hi, stack trace is below.  Again, I can confirm that `/home/dbuser/.postgresql/postgresql.key` exists and is readable by the account invoking pgloader.

```
sb-impl::*default-external-format* :UTF-8
tmpdir: #P"/tmp/pgloader/"
2015-11-11T08:38:14.090000+09:00 NOTICE Starting pgloader, log system is ready.
2015-11-11T08:38:14.150000+09:00 INFO Starting monitor
2015-11-11T08:38:14.168000+09:00 LOG Main logs in '/tmp/pgloader/pgloader.log'
2015-11-11T08:38:14.168000+09:00 LOG Data errors in '/tmp/pgloader/'
2015-11-11T08:38:14.169000+09:00 INFO SOURCE: #<PGLOADER.SQLITE:SQLITE-CONNECTION sqlite:///path/to/sqlite/data.db {1007195933}>
2015-11-11T08:38:14.169000+09:00 INFO TARGET: #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://dbuser@dbserver:5432/userdb {10072BACE3}>
2015-11-11T08:38:14.170000+09:00 DEBUG LOAD DATA FROM #<PGLOADER.SQLITE:SQLITE-CONNECTION sqlite:///path/to/sqlite/data.db {1007195933}>
An unhandled error condition has been signalled:
   Failed to connect to pgsql at "dbserver" (port 5432) as user "dbuser": /home/dbuser/.postgresql/postgresql.key is not a Lisp string or pointer.

Date/time: 2015-11-11-08:38An unhandled error condition has been signalled:
                              Failed to connect to pgsql at "dbserver" (port 5432) as user "dbuser": /home/dbuser/.postgresql/postgresql.key is not a Lisp string or pointer.


Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1006F83F23}>
0: ((LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX))
1: (SB-IMPL::CALL-WITH-SANE-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX) {1008BEF1FB}>)
2: (SB-IMPL::%WITH-STANDARD-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX) {1008BEF1CB}>)
3: (PRINT-BACKTRACE :STREAM #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDOUT* {10002CBC23}> :START 0 :FROM :DEBUGGER-FRAME :COUNT 4611686018427387903 :PRINT-THREAD T :PRINT-FRAME-SOURCE NIL :METHOD-FRAME-STYLE NIL)
4: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE-TO-STREAM #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDOUT* {10002CBC23}>)
5: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE #<PGLOADER.CONNECTION:DB-CONNECTION-ERROR {1008BE8873}> :OUTPUT #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDOUT* {10002CBC23}> :IF-EXISTS :APPEND :VERBOSE T)
6: (SIGNAL #<PGLOADER.CONNECTION:DB-CONNECTION-ERROR {1008BE8873}>)
7: (ERROR PGLOADER.CONNECTION:DB-CONNECTION-ERROR :MESG "/home/dbuser/.postgresql/postgresql.key is not a Lisp string or pointer." :TYPE "pgsql" :HOST "dbserver" :PORT 5432 :USER "dbuser")
8: (PGLOADER.PGSQL:LIST-RESERVED-KEYWORDS #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://dbuser@dbserver:5432/userdb {10072BACE3}>)
9: ((LAMBDA ()))
10: (PGLOADER:RUN-COMMANDS (LAMBDA NIL (LET* ((PGLOADER.SOURCES:*DEFAULT-CAST-RULES* (QUOTE ((:SOURCE (:TYPE "character") :TARGET (:TYPE #1="text" :DROP-TYPEMOD T)) (:SOURCE (:TYPE "varchar") :TARGET (:TYPE #1# :DROP-TYPEMOD T)) (:SOURCE (:TYPE "nvarchar") :TARGET (:TYPE #1# :DROP-TYPEMOD T)) (:SOURCE (:TYPE "char") :TARGET (:TYPE #1# :DROP-TYPEMOD T)) (:SOURCE (:TYPE "nchar") :TARGET (:TYPE #1# :DROP-TYPEMOD T)) (:SOURCE (:TYPE "clob") :TARGET (:TYPE #1# :DROP-TYPEMOD T)) (:SOURCE (:TYPE "tinyint") :TARGET (:TYPE "smallint")) (:SOURCE (:TYPE "integer") :TARGET (:TYPE "bigint")) (:SOURCE (:TYPE #2="float") :TARGET (:TYPE #2#) :USING PGLOADER.TRANSFORMS::FLOAT-TO-STRING) (:SOURCE (:TYPE #3="real") :TARGET (:TYPE #3#) :USING PGLOADER.TRANSFORMS::FLOAT-TO-STRING) (:SOURCE (:TYPE "double") :TARGET (:TYPE "double precision") :USING PGLOADER.TRANSFORMS::FLOAT-TO-STRING) (:SOURCE (:TYPE #4="numeric") :TARGET (:TYPE #4#) :USING PGLOADER.TRANSFORMS::FLOAT-TO-STRING) (:SOURCE (:TYPE "blob") :TARGET (:TYPE "bytea") :USING PGLOADER.TRANSFORMS::BYTE-VECTOR-TO-BYTEA) (:SOURCE (:TYPE "datetime") :TARGET (:TYPE #5="timestamptz") :USING PGLOADER.TRANSFORMS::SQLITE-TIMESTAMP-TO-TIMESTAMP) (:SOURCE (:TYPE #6="timestamp") :TARGET (:TYPE #6#) :USING PGLOADER.TRANSFORMS::SQLITE-TIMESTAMP-TO-TIMESTAMP) (:SOURCE (:TYPE #5#) :TARGET (:TYPE #5#) :USING PGLOADER.TRANSFORMS::SQLITE-TIMESTAMP-TO-TIMESTAMP)))) (PGLOADER.SOURCES:*CAST-RULES* (QUOTE NIL)) (PGLOADER.PARAMS:*PG-SETTINGS* (QUOTE NIL)) (PGLOADER.PGSQL::*PGSQL-RESERVED-KEYWORDS* (PGLOADER.PGSQL:LIST-RESERVED-KEYWORDS #7=#<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://dbuser@dbserver:5432/userdb {10072BACE3}>)) (PGLOADER.PARAMS:*COPY-BATCH-ROWS* (OR NIL PGLOADER.PARAMS:*COPY-BATCH-ROWS*)) (PGLOADER.PARAMS:*COPY-BATCH-SIZE* (OR NIL PGLOADER.PARAMS:*COPY-BATCH-SIZE*)) (PGLOADER.PARAMS:*CONCURRENT-BATCHES* (OR NIL PGLOADER.PARAMS:*CONCURRENT-BATCHES*)) (PGLOADER.PARSER::SOURCE-DB (PGLOADER.MONITOR:WITH-STATS-COLLECTION ("fetch" :SECTION :PRE) (PGLOADER.CONNECTION:EXPAND (PGLOADER.CONNECTION:FETCH-FILE #<PGLOADER.SQLITE:SQLITE-CONNECTION sqlite:///path/to/sqlite/data.db {1007195933}>)))) (PGLOADER.PARSER::SOURCE (MAKE-INSTANCE (QUOTE PGLOADER.SQLITE:COPY-SQLITE) :TARGET-DB #7# :SOURCE-DB PGLOADER.PARSER::SOURCE-DB))) (PGLOADER.SOURCES:COPY-DATABASE PGLOADER.PARSER::SOURCE :INCLUDING (QUOTE NIL) :EXCLUDING (QUOTE NIL) :CREATE-INDEXES NIL))) :START-LOGGER NIL :SUMMARY NIL :LOG-FILENAME NIL :LOG-MIN-MESSAGES NIL :CLIENT-MIN-MESSAGES NIL)
11: (PGLOADER:LOAD-DATA :FROM #<PGLOADER.SQLITE:SQLITE-CONNECTION sqlite:///path/to/sqlite/data.db {1007195933}> :INTO #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://dbuser@dbserver:5432/userdb {10072BACE3}> :ENCODING :UTF-8 :FIELDS NIL :OPTIONS (:CREATE-INDEXES NIL) :GUCS NIL :CASTS NIL :BEFORE NIL :AFTER NIL :START-LOGGER NIL)
12: ((FLET #:CLEANUP-FUN-272 :IN PGLOADER::MAIN)) [cleanup]
13: (PGLOADER::MAIN ("./pgloader" "--debug" "--verbose" "--with" "create no indexes" "sqlite:///path/to/sqlite/data.db" "postgresql://dbuser@dbserver/userdb?sslmode=prefer"))
14: ((LAMBDA NIL :IN "/home/dbuser/tmp/pgloader/dumper-2SKVI5f7.lisp"))
15: ((FLET #:WITHOUT-INTERRUPTS-BODY-54 :IN SAVE-LISP-AND-DIE))
16: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))


debugger invoked on a PGLOADER.CONNECTION:DB-CONNECTION-ERROR in thread
#<THREAD "main thread" RUNNING {1006F83F23}>:
  Failed to connect to pgsql at "dbserver" (port 5432) as user "dbuser": /home/dbuser/.postgresql/postgresql.key is not a Lisp string or pointer.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit application


debugger invoked on a TYPE-ERROR in thread
#<THREAD "main thread" RUNNING {1006F83F23}>:
  The value INVOKE-DEBUGGER is not of type SB-DI:FRAME.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit application

(SB-DEBUG::FRAME-CALL INVOKE-DEBUGGER :METHOD-FRAME-STYLE :NORMAL :REPLACE-DYNAMIC-EXTENT-OBJECTS NIL)
0[2] 2015-11-11T08:38:14.370000+09:00 FATAL We have a situation here.
```

**Comment by dimitri** [comment]
I failed to reproduce the problem locally (or rather didn't properly setup testing environment), so I will still ask you to do the testing here... please report back again!

**Comment by bazeli** [comment]
Hi Dimitri - your latest fix is working as intended, with pgloader successfully loading to a remote postgres sever authenticated by ssl certificates.   Many thanks! :beers:

**Comment by dimitri** [comment]
Awesome, have fun with PostgreSQL!

**Comment by prakharkan** [comment]
Hi Dimitri,

I am trying pgloader using certificate , but getting below error 
--
pgloader csv.load
2022-08-18T02:29:13.168000+01:00 LOG pgloader version "3.6.2"
KABOOM!
FATAL error: Failed to connect to pgsql at "***********" (port ******) as user "*******": Database error 28000: connection requires a valid client certificate
An unhandled error condition has been signalled:
   Failed to connect to pgsql at "**********" (port ****) as user "*****": Database error 28000: connection requires a valid client certificate
What I am doing here?
Failed to connect to pgsql at "*********" (port *****) as user "*******": Database error 28000: connection requires a valid client certificate

####I have tested the connection from psql using certificate . it's working 
 export PGSSLCERT="/**/**/***/.postgresql/postgresql.crt"
 export PGSSLKEY="/**/**/**/.postgresql/postgresql.key"
psql -h ********* -p **** -U ******* -d *******
psql (9.2.24, server 11.5)
WARNING: psql version 9.2, server version 11.0.
         Some psql features might not work.
SSL connection (cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256)
Type "help" for help.

************=>

##### I am trying with pgloader as below 
export PGSSLCERT="/**/**/***/.postgresql/postgresql.crt"
export PGSSLKEY="/**/**/**/.postgresql/postgresql.key"

csv.load file entry 
-LOAD CSV
FROM '/tmp/pk.csv' (x, y, a, b, c, d)
INTO postgres://*******@servername/dbname?port=****&sslmode=prefer&schemaname.tablename(a, b, d, c)

Please suggest

**Comment by dimitri** [comment]
At the moment we don't support the environment variables, the file names are hard-coded.

```lisp
(defvar *pgsql-client-certificate* "~/.postgresql/postgresql.crt"
  "File where to read the PostgreSQL Client Side SSL Certificate.")

(defvar *pgsql-client-key* "~/.postgresql/postgresql.key"
  "File where to read the PostgreSQL Client Side SSL Private Key.")
```

**Comment by prakharkan** [comment]
Hi Dimitri,  

Thanks , Now i have set ssl_cert_file & ssl_key_file to the user file & cert but  stil getting error -

=# alter system set ssl_cert_file to '/var/lib/postgresql/.postgresql/postgresql.crt';
ALTER SYSTEM
=# alter system set ssl_key_file to '/var/lib/postgresql/.postgresql/postgresql.key';
ALTER SYSTEM

 pwd
/**************/.postgresql
% ls -ltra
total 0
lrwxrwxrwx. 1 postgres postgres  31 Aug 18 02:49 postgresql.crt ->*************/FA10337.crt
lrwxrwxrwx. 1 postgres postgres  31 Aug 18 02:49 postgresql.key ->*************/FA10337.key
lrwxrwxrwx. 1 postgres postgres  41 Aug 18 03:28 root.crt -> ********************certs/cacerts.pem


error :- database error 28000: connection requires a valid client certificate

Can you please look and suggest , Thanks in advance

# select name,setting from pg_settings where name like '%ssl%';
                  name                  |                    setting
----------------------------------------+------------------------------------------------
 ssl                                    | on
 ssl_ca_file                            | ***************/certs/cacerts.pem
 ssl_cert_file                          |  ***************/.postgresql/postgresql.crt
 ssl_ciphers                            | HIGH:MEDIUM:+3DES:!aNULL
 ssl_crl_file                           |
 ssl_dh_params_file                     |
 ssl_ecdh_curve                         | prime256v1
 ssl_key_file                           |  ***************.postgresql/postgresql.key
 ssl_passphrase_command                 |
 ssl_passphrase_command_supports_reload | off
 ssl_prefer_server_ciphers              | on
(11 rows)
