### ISSUE TITLE
MSSQL -> Postgres Database error 42P01: relation does not exist

### ISSUE THREAD

**Issue by davidweterings** [dimitri/pgloader#309]
I'm trying to convert a large MSSQL database to postgresql, as an experiment I first tried converting the following simple database: https://gist.github.com/davidweterings/46a01a05c6dba36f4ef4 
with the command:
./pgloader mssql://user details@mssqldb:1433/test postgresql://user details@localhost/loyalty

My assumption is that this command would handle stuff like foreign keys without anything extra (please correct me if I'm wrong).

It fails with a "FATAL We have a situation here" and just before that a "ERROR Database error 42P01: relation "dbo.card" does not exist" but does create the schema, the tables and inserts the data. It fails to create the foreign keys. The output with -v --debug can be found here:
>https://gist.github.com/davidweterings/d6dd8e6dc3ef6f04c1bc

Running on Mac OSX 10.10.5 (16gb) with pgloader version build a few days ago:
>pgloader version "3.2.da05782"
>compiled with SBCL 1.2.15

**Comment by dimitri** [comment]
It is failing in the last step (*reset sequences*), so you can tweak it to bypass that and it should stop failing. There's apparently a problem with quoting of the table names in your case, I will see about that.

    pgloader --with 'reset no sequences' ...

**Comment by dimitri** [comment]
Can you try again with building from current pgloader sources, as some recent changes should improve the situation here (sharing the code with other database source types that work correctly).

**Comment by gavinwahl** [comment]
I think I am having this same issue. Qualified table names are being quoted incorrectly. pgloader tries to run this query:

```sql
CREATE INDEX "idx-foo" ON "dbo.foo" (column);
```

But the schema name and table name must be quoted separately:

```sql
CREATE INDEX "idx-foo" ON "dbo"."foo" (column);
```

**Comment by dimitri** [comment]
Which version of pgloader are you using? (`pgloader --version` tells you)

**Comment by gavinwahl** [comment]
I can't run --version because I don't currently have a working build, but I was running a0dc59624cb.

**Comment by dimitri** [comment]
Thanks, that's a version from Sep 11, 2015 ; and I have been working on fixes for that range of problems more recently (see https://github.com/dimitri/pgloader/commit/9e4938cea45c5e33a83d1affae4d0d798456dbd2 and follow-up patches). So please consider retrying with a fresh git pull of the code, I think it's all it takes for you to make progress.

**Comment by dimitri** [comment]
I believe this is fixed now, so I'm closing the issue. Please re-open if needed.
