### ISSUE TITLE
Troubles with complex SQLite schema

### ISSUE THREAD

**Issue by richardkmichael** [dimitri/pgloader#310]
Hello Dimitri,

Thank you for pgloader, it is very helpful. :-)  I see people occasionally use "Issues" for support requests, so I hope posting here is OK ; please let me know if I should move to a mailing list, or elsewhere. 

I have a SQLite database with many tables and views.  I am using a pgloader command file to migrate only 1 specific table to PostgreSQL.  However pgloader seems unable to handle portions of the SQLite schema, and I am unsure how best to proceed.  (Maybe I should load a lisp file and change pgloader's behaviour when reading the source schema?)

At the bottom, I included a minimal test case and version info.

* First, a `CREATE VIEW ... AS WITH ...` causes a problem.  I do not need to migrate this view, so as a workaround, I drop it.  It is unfortunate that pgloader dies here, because, at a minimum, it could skip this view entirely.  (I thought it might ignore the view, as my command file uses `INCLUDE ONLY TABLES MATCHING ...`.)

* Second (after I drop the troublesome view), pgloader dislikes a default column value which is an SQLite function.  I imagine this is a difficult case for pgloader.  It appears to believe the column default is a string (i.e. the function call with parameters is all a string), but the inner quotes are not escaped ...?  So, `strftime(..., 'now')` becomes `'strftime(...,'now')'`, but perhaps should be `..., \'now\')'`?  (Aside, although casting it all to text is a bit bizarre, it would be acceptable because I could fix it in postgres after migration.  OTOH, the column is a TIMESTAMP so I can imagine pgloader casting is confused completely.)  Now in fact, I don't care about the default value at all, so I could even accept no default value.  However, because SQLite does not support `ALTER COLUMN ...` [so that I could change the source column definition to help pgloader], the workaround is not very simple: I must create a new table in SQLite with an adjusted schema and use pgloader against the new table.

* Third, is it possible to use `INCLUDING ONLY TABLES MATCHING` on the pgloader command line?  This would eliminate my need for the command file.  Sorry if I missed this in the documentation.

Here is the test-case, the actual SQLite schema is more complex, but not much. :-)

Thank you very much for any comments.

```
$ pgloader --version
pgloader version "3.2.2"
compiled with SBCL 1.3.0

$ postgres -V
postgres (PostgreSQL) 9.4.5

$ sqlite3 --version
3.9.2 2015-11-02 18:31:45 bda77dda9697c463c3d0704014d51627fceee328

$ cat | sqlite3 test.sqlite
CREATE VIEW first_names AS WITH names AS (SELECT "Richard" AS name) SELECT name AS first_name FROM names;
CREATE TABLE appointments (time TIMESTAMP DEFAULT (strftime('%Y-%m-%d %H:%M:%f', 'now')));

$ cat > test.load
LOAD DATABASE
  FROM sqlite://./test.sqlite
  INTO postgresql:///test
  INCLUDING ONLY TABLE NAMES MATCHING 'appointments'
;

$ createdb test

$ pgloader test.load

2015-11-22T13:58:10.038000-05:00 LOG Main logs in '/private/tmp/pgloader/pgloader.log'
2015-11-22T13:58:10.044000-05:00 LOG Data errors in '/private/tmp/pgloader/'
2015-11-22T13:58:10.044000-05:00 LOG Parsing commands from file #P"/Users/testuser/tmp/pgloader-testcase/appointments.load"
An unhandled error condition has been signalled:
   Could not prepare an sqlite statement.
Code CORRUPT: malformed database schema (first_names) - near "WITH": syntax error.
Database: /Users/testuser/tmp/pgloader-testcase/./test.sqlite
SQL: SELECT tbl_name
                FROM sqlite_master
               WHERE type='table' AND tbl_name <> 'sqlite_sequence'

$ sqlite3 test.sqlite 'DROP VIEW first_names;'

$ pgloader test.load

2015-11-22T13:59:43.173000-05:00 LOG Main logs in '/private/tmp/pgloader/pgloader.log'
2015-11-22T13:59:43.179000-05:00 LOG Data errors in '/private/tmp/pgloader/'
2015-11-22T13:59:43.179000-05:00 LOG Parsing commands from file #P"/Users/testuser/tmp/pgloader-testcase/appointments.load"
2015-11-22T13:59:43.180000-05:00 WARNING PostgreSQL warning: table "appointments" does not exist, skipping
2015-11-22T13:59:43.180000-05:00 ERROR Database error 42601: syntax error at or near ":"
QUERY: CREATE TABLE appointments
(
  time                   timestamp default 'strftime('%Y-%m-%d %H:%M:%f', 'now')'
);
2015-11-22T13:59:43.180000-05:00 FATAL Failed to create the schema, see above.
```

**Comment by dimitri** [comment]
Thanks for opening this bug report, that's the intended way to do it!

I couldn't reproduce the `CREATE VIEW` problem here, because the `WITH` syntax is not accepted by my version of SQLite (*SQLite version 3.7.13 2012-07-17 17:46:21*), but the problem looks straightforward enough: the table list pgloader operates on is only filtered after the fact. One may wonder why `SELECT tbl_name FROM sqlite_master WHERE type='table'` returns *VIEWS*, but we'd rather filter table names right from the SQL query here. Now done, which means using the `LIKE` feature and changing the LOAD file syntax.

About the second part, you can tweak your load command to disregard default values. The sqlite test case now has:

```
  cast column character.f1 to text drop typemod,
       column appointments.time to timestamptz drop default
```

Using the same thing you should be able to make progress.

Have fun using PostgreSQL!

**Comment by dimitri** [comment]
BTW, will see about a `--including-only` and `--excluding` pair of command line options, you already have `--cast` after all.

**Comment by richardkmichael** [comment]
Thank you very much for your reply and the fix for views!

I think `MATCHING` was OK, but `LIKE` is obviously the "more-DBA-friendly approach", as you say in the docs.  I'll look at the type casting modifiers more carefully, sorry I did not notice earlier.

> One may wonder why SELECT tbl_name FROM sqlite_master WHERE type='table' returns VIEWS

Yes, it makes removing items from the SQLite schema cumbersome because, in fact, `DROP VIEW ...` and `DROP TABLE ...` do return an error when not operating on the their respective type; yet, there is no way trivial way to introspect type.

> Have fun using PostgreSQL!

Always. ;-)

(Aside, SQLite performance improved substantially since 3.7, so I always update it aside from the vendored version with my OS.)

**Comment by richardkmichael** [comment]
Hi Dimitri,

I built pgloader from source and tried the new `INCLUDING ONLY TABLES LIKE ...` option, but I have the same SQLite schema parsing problem I originally reported.

```

$ pgloader --version
pgloader version "3.2.af9e423"
compiled with SBCL 1.3.0

$ cat <<_SQL | sqlite3 test.sqlite
CREATE VIEW first_names AS WITH names AS (SELECT "Richard" AS name) SELECT name AS first_name FROM names;
CREATE TABLE appointments (time TIMESTAMP DEFAULT (strftime('%Y-%m-%d %H:%M:%f', 'now')));
_SQL

$ cat <<_SQL > test.load
LOAD DATABASE
  FROM sqlite://./test.sqlite
  INTO postgresql:///test
  INCLUDING ONLY TABLE NAMES MATCHING 'appointments'
;
_SQL

$ dropdb --if-exists test ; createdb test

$ pgloader test.load

2015-11-27T23:58:17.039000-05:00 LOG Main logs in '/private/tmp/pgloader/pgloader.log'
2015-11-27T23:58:17.045000-05:00 LOG Data errors in '/private/tmp/pgloader/'
2015-11-27T23:58:17.045000-05:00 LOG Parsing commands from file #P"/Users/testuser/test.load"
An unhandled error condition has been signalled:
   Could not prepare an sqlite statement.
Code CORRUPT: malformed database schema (first_names) - near "WITH": syntax error.
Database: /Users/testuser/./test.sqlite
SQL: SELECT tbl_name
                FROM sqlite_master
               WHERE type='table'
                     AND tbl_name <> 'sqlite_sequence'
                     AND ((tbl_name LIKE 'appointments'))

```

If you have a time, could you please tell me what I am still doing wrong?

Thank you,
Richard

**Comment by dimitri** [comment]
Hi,

It looks like the SQLite driver in use by pgloader is to blame here, can you `ldd` against the binary and see what's loaded? We can see in the error message the SQL query that was sent, and it's the proper one which should ignore the `first_names` view. The `Code CORRUPT:` error message does not come from pgloader sources, so I guess it comes from the SQLite driver...

**Comment by richardkmichael** [comment]
Hi @dimitri,

Yes, it is the sqlite version -- thank you, your tip pointed me in the right direction.  pgloader is compiling against the system sqlite, not the newer sqlite.  On my Linux system, with only one [recent] version of sqlite, there is no problem at all (obviously).  I should have guessed!

Perhaps I need to help the build process and `cl-sqlite` find the newer sqlite; I'll investigate.

However, and only mentioning this because you suggested it, neither `otool` nor `ldd` indicate dynamic linking to the sqlite library.  Should I set build flags to perform more aggressive dynamic compiling ; vs. static?

```
$ otool -L build/bin/pgloader
build/bin/pgloader:
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 169.3.0)
        /usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
```

```
$ ldd build/bin/pgloader
        linux-vdso.so.1 (0x00007ffcfea5f000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f594a560000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f594a344000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f594a03b000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f5949c7b000)
        /lib64/ld-linux-x86-64.so.2 (0x000055a540267000)
```

**Comment by dimitri** [comment]
The standalone target was created to support the macosx brew packaging system, and has not been edited in a while, I guess it still works. About `otool` and `ldd`, you're right, that was a brain fart from me, sorry about that.

Glad it works!
