### ISSUE TITLE
Support for sequence increment in MySQL migrations

### ISSUE THREAD

**Issue by mhagander** [dimitri/pgloader#312]
MySQL has configuration parameters like:

> auto_increment_increment   = 10

at a global level.

It would be interesting to migrate this over as `INCREMENT BY` and  on all sequences. Possibly not by default, but making it an option (and needs to be an option whether on by default or not of course, so it can be controlled).

**Comment by dimitri** [comment]
Do you know how to query for that configuration parameter value at the SQL level?

**Comment by dimitri** [comment]
Ok, I just tried to see what that thing really is, and the documentation is at https://dev.mysql.com/doc/refman/5.6/en/replication-options-master.html. If someone can translate it in terms of http://www.postgresql.org/docs/9.4/interactive/sql-createsequence.html options, I will consider implementing the feature...

**Comment by dimitri** [comment]
Closing, re-open if needed (raise of interest or more details to implement).
