### ISSUE TITLE
Heap exhausted for mysql to postgresql

### ISSUE THREAD

**Issue by aven92** [dimitri/pgloader#315]
When I use pgloader to migration data from mysql to postgresql, it got a error like this:
```
Heap exhausted during garbage collection: 48 bytes available, 64 requested.
 Gen StaPg UbSta LaSta LUbSt Boxed Unboxed LB   LUB  !move  Alloc  Waste   Trig    WP  GCs Mem-age
   0:     0     0     0     0     0     0     0     0     0        0     0 42949672    0   0  0.0000
   1:     0     0     0     0     0     0     0     0     0        0     0 42949672    0   0  0.0000
   2:     0     0     0     0     0     0     0     0     0        0     0 42949672    0   0  0.0000
   3: 108520 118097     0     0  3408 84869    91     0    81 2828098224 67544400 988502376    0   1  1.0456
   4: 102478 131071     0     0  1967 36671   175     0    42 1243485920 28338464  2000000    0   0  0.0000
   5:     0     0     0     0     0     0     0     0     0        0     0  2000000    0   0  0.0000
   6:     0     0     0     0  2737  1154     0     0     0 127500288     0  2000000 2562   0  0.0000
   Total bytes allocated    = 4199084432
   Dynamic-space-size bytes = 4294967296
GC control variables:
   *GC-INHIBIT* = true
   *GC-PENDING* = true
   *STOP-FOR-GC-PENDING* = false
fatal error encountered in SBCL pid 607(tid 140736814839552):
Heap exhausted, game over.
```
The environment is:
```
$ ./pgloader --version
pgloader version "3.2.7c64a71"
compiled with SBCL 1.2.8-1.el7

$ uname -a
Linux hostname 3.10.0-123.el7.x86_64 #1 SMP Mon Jun 30 12:09:22 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by dimitri** [comment]
Can you tweak `batch rows` and `batch size` to limit memory pressure (having smaller batches)?

**Comment by aven92** [comment]
Yeap, it works. thank you very much!
But, I found out it's just copy one table a time, doesn't it support multiple tables for concurrency. The batch option is:
```
batch size = 3 MB, batch rows = 1000, batch concurrency = 10
```
The batch concurrency is the number of batches build in memory? did I read it right?

**Comment by dimitri** [comment]
Exactly, we queue batches in between a reader thread and a writer thread, and we block when we have 10 batches read that are waiting to be applied... which seldom happens as PostgreSQL COPY is currently quite faster than reading from the source ; but might happen when we handle *bad rows*.

If you compile the current pgloader source tree you will have multiple-table concurrency enabled by default, but without user level settings about it yet, it's coming soon tho!
