### ISSUE TITLE
Build on FreeBSD 11 Current. error message similar to #80

### ISSUE THREAD

**Issue by WanpengQian** [dimitri/pgloader#319]
Since the pgloader in FreeBSD port tree is quite old. (2.3)
I try to build it under FreeBSD 11 Current.
```
$ pgloader --version
pgloader version "3.2.72e7c2a"
compiled with SBCL 1.3.1
```
The build itself is quite straight forward, and success.
after I run it, I got the follow error. similar to #80
```
Import CSV data to DB...

debugger invoked on a BORDEAUX-THREADS::BORDEAUX-MP-CONDITION:
  There is no thread support in this instance.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit application

(BORDEAUX-THREADS::%MAKE-THREAD #<unavailable argument> #<unavailable argument>)
0] 
```
I have read the issue #80, and I have no idea how to solve it.
please give me some tiips.
Thanks.

**Comment by dimitri** [comment]
See *Compiling SBCL yourself* in the INSTAL.md document:

    sh make.sh --with-sb-core-compression --with-sb-thread

Check about the FreeBSD port build options for SBCL, my understanding here is that needs to be upgraded to allow core compression and threads.

**Comment by WanpengQian** [comment]
After dig a little bit. I comment out sbcl Makefile of THREAD, and rebuild/reinstall sbcl.
also rebuild pgloader after that. it works flawless.

Thank you very much.

**Comment by dimitri** [comment]
Are you in a position to update/maintain the FreeBSD port of pgloader? that would be awesome!

**Comment by WanpengQian** [comment]
Sorry, I wish I could. :-)
