### ISSUE TITLE
SQLite does not support BEFORE/AFTER LOAD

### ISSUE THREAD

**Issue by gitblit** [dimitri/pgloader#321]
It would appear that the SQLite command parser does not support BEFORE/AFTER LOAD statements nor the `--before` and `--after` command-line args.

Maybe I am doing something wrong, but after comparing `command-sqlite.lisp` to `command-mysql.lisp`, the implementations seem absent.

It would be really handy to have support for the BEFORE/AFTER LOAD statements.

**Comment by dimitri** [comment]
Can't remember why that wasn't already done... please build from fresh sources to get the feature!

**Comment by gitblit** [comment]
Awesome :metal: !

Now to review your building from source instructions... :)
