### ISSUE TITLE
Is it possible to read .sql file?

### ISSUE THREAD

**Issue by maksimf** [dimitri/pgloader#325]
I'm importing mysql DB to postgres and I want to make use of `pv` command to show the progress, but to do that I'll need to read `.sql` file from STDIN, but I can't do that, can I? I only managed to read `.csv` file as it is shown in the examples.

**Comment by dimitri** [comment]
Exactly, pgloader doesn't know how to read and process a SQL file, for that you have `psql`, which should work with pv and stdin by the way.

**Comment by maksimf** [comment]
Do you think psql would process .sql file craeted by mysqldump?

**Comment by dimitri** [comment]
Oh, it certainly won't. What about using pgloader against a MySQL live server as in the docs?

**Comment by maksimf** [comment]
It works, but I want to see the progress with pv

**Comment by maksimf** [comment]
So, basically, the question is: can I somehow import from mysql and see the progress?

**Comment by dimitri** [comment]
You can try --verbose to get a sense of progress being made, but there's no provision for a progress bar in pgloader at the moment...

**Comment by maksimf** [comment]
So, just to confirm: there is currently no way to import data from .sql file using STDIN and passing `pv` as a middleware?

**Comment by dimitri** [comment]
Indeed. I'm closing the issue here, consider opening again if necessary.
