### ISSUE TITLE
casting enums

### ISSUE THREAD

**Issue by traufeisen** [dimitri/pgloader#326]
Hello,
it seems not possible to apply a casting rule to all enum columns in a mysql database.
It would be very useful to define something like this in the config file:

```
CAST type enum drop not null using empty-string-to-null
```

However, when I do this now, pgloader tries to create a table like this:

```
CREATE TABLE foo
(
  bar     enum default 'no'
);
```

**Comment by dimitri** [comment]
Each `enum` type in MySQL is its own independent data type, so matching them all at once seems rather strange. Why aren't you using a matching `enum` in PostgreSQL?

**Comment by traufeisen** [comment]
In my case the Mysql database is using Enums very often.
Listing all if them in the config file would be a pain.
And because they all suffer from the same inconsistency it would be very helpful to allow NULL on all of them and also convert empty strings to NULL too.
That way the data could be stored in the postgres and additional "data tweaking" could take place manually.
It´s like the date casting: "type date drop not null drop default using zero-dates-to-null" but for all enums too.

**Comment by dimitri** [comment]
Actually, what happens if you try:

    CAST type enum to text drop not null using empty-string-to-null

I don't have the time to test right now, sorry.

**Comment by traufeisen** [comment]
pgloader is converting all enum columns to text and also creates the postgres types for the enums.
But these are not used in any way on the columns.

**Comment by dimitri** [comment]
IS it good enough for you? I guess we could avoid creating the enums then, maybe they serve as “documentation” but maybe it is just me being lazy now ;-)

**Comment by traufeisen** [comment]
yes, it is (for now :) ). Thank you.
I guess I´m fu***d anyway when it comes to clean up the data mess.

**Comment by dimitri** [comment]
Yeah, well, good luck with that parts... Leaving this open to instruct pgloader to avoid creating useless enum types when the cast rule has been overloaded.

**Comment by dimitri** [comment]
Closing the issue, no time to clean that up and there's no major drawback that I can see here. For future reference, I would accept a contribution that cleans that up and adds an option to always cast the enums even when they are not used (for reference later), defaulting to false (the sane setting).
