### ISSUE TITLE
Build broken

### ISSUE THREAD

**Issue by gavinwahl** [dimitri/pgloader#330]
When trying to build master I get:

```
sbcl --no-sysinit --no-userinit --load build/quicklisp/setup.lisp                 \
             --eval '(push "/home/fusionbox/pgloader/" asdf:*central-registry*)'      \
             --eval '(ql:quickload "pgloader")'                     \
             --eval '(quit)'
This is SBCL 1.2.4.debian, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
To load "pgloader":
  Load 1 ASDF system:
    pgloader
; Loading "pgloader"
..................................................
..................................................
......; 
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Symbol "WITH-IXF-STREAM" not found in the IXF package.
;   
;       Line: 70, Column: 22, File-Position: 2411
;   
;       Stream: #<SB-SYS:FD-STREAM
;                 for "file /home/fusionbox/pgloader/src/sources/ixf/ixf-schema.lisp"
;                 {100B089CE3}>

debugger invoked on a UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread
#<THREAD "main thread" RUNNING {10039CED43}>:
  COMPILE-FILE-ERROR while
  compiling #<CL-SOURCE-FILE "pgloader" "src" "sources" "ixf" "ixf-schema">

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Retry
                                     compiling #<CL-SOURCE-FILE "pgloader" "src" "sources" "ixf" "ixf-schema">.
  1: [ACCEPT                       ] Continue, treating
                                     compiling #<CL-SOURCE-FILE "pgloader" "src" "sources" "ixf" "ixf-schema">
                                     as having been successful.
  2:                                 Retry ASDF operation.
  3: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  4: [ABORT                        ] Give up on "pgloader"
  5: [CONTINUE                     ] Ignore runtime option --eval "(ql:quickload \"pgloader\")".
  6:                                 Skip rest of --eval and --load options.
  7:                                 Skip to toplevel READ/EVAL/PRINT loop.
  8: [EXIT                         ] Exit SBCL (calling #'EXIT, killing the process).

(UIOP/LISP-BUILD:CHECK-LISP-COMPILE-RESULTS NIL T T "~/asdf-action::format-action/" ((#<ASDF/LISP-ACTION:COMPILE-OP > . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "pgloader" "src" "sources" "ixf" "ixf-schema">)))
0] 
```

I did a bisect and it was broken by a195ac6dd48cb8235b58a5a95eabb5dfb676d72f. I am building on debian 8.2.

**Comment by dimitri** [comment]
Your local copy of the `cl-ixf` lib isn't uptodate, please `make clean` and `make again`.

**Comment by gavinwahl** [comment]
That fixed the build error, but now when running pgloader I get 

```
An unhandled error condition has been signalled:
   Undefined alien: "SSL_CTX_set_default_verify_dir"
```

Or with --debug enabled:

```
An unhandled error condition has been signalled:
   There is no applicable method for the generic function
     #<STANDARD-GENERIC-FUNCTION PGLOADER.CONNECTION:CONN-TYPE (1)>
   when called with arguments
     (NIL).

; 
; compilation unit aborted
;   caught 1 fatal ERROR condition
```

**Comment by dimitri** [comment]
That now looks related to https://github.com/cl-plus-ssl/cl-plus-ssl/issues/33 ; my current understanding is that it happens when the OpenSSL version used at build time is not the same than the version found at run time. Maybe you can use the docker image which doesn't have this problem?

https://hub.docker.com/r/dimitri/pgloader/builds/

**Comment by gavinwahl** [comment]
How do I use the docker build? Can I copy the binary onto my system out of the docker?

**Comment by julianandrews** [comment]
I just built pgloader in docker (following the instructions [here](https://github.com/dimitri/pgloader/blob/master/INSTALL.md#building-a-docker-image)) and I get the identical error.

For reference, I stripped down the .load file to:

    LOAD DATABASE
               FROM mssql://db:user@host/DB
               INTO postgres:///db
    ;

**Comment by radu-porumb** [comment]
Same here. Pulled latest pgloader docker image and the same error appears when trying to do a load from MS SQL. For future reference, you should also tag your Docker images with some kind of build number so if recently built images have an isolated issue we can still pull an older image that works.

**Comment by dimitri** [comment]
@radu-porumb : which of the multiple errors mentioned in this bug report did you see?

**Comment by radu-porumb** [comment]
@dimitri 

I am getting this error:
```
An unhandled error condition has been signalled:
   Undefined alien: "SSL_CTX_set_default_verify_dir"
````

Update: I've done a bit of digging. Since I\m not a Lisp guy, my digging on that side is severely limited. I have however pulled the repo and attempted to build a docker image using alternative OS base images (debian wheezy, jessie, stretch, sid and ubuntu 14.04, 15.04, 15.10). Every time the image build succeeded I encountered the same error when trying to run `pgloader`. The one time the build did not succeed was on `debian stretch` because it uses different versions of OpenSSL and libssl.

This is what's in the config file I'm using for pgloader:
```
load database
     from mssql://user:password@host:port/db
     into postgresql://user:password@host:port/db
;
```

I might be totally off base here, but the fact that the app builds with several different versions of OpenSSL/libssl on several different OS base images, the phrasing of the error message and the absence of any references to that function in your code leads me to believe the error comes from a Lisp library that you're bringing in via Quicklisp that is trying to import this nonexistent function from OpenSSL/libssl.

**Comment by gavinwahl** [comment]
Is there some workaround for this? I don't think I'm even using ssl.

**Comment by dimitri** [comment]
While at FOSDEM I had a good talk about that with people who know more about it than I do, and I think I have a clear way forward. Work still needs to be done, obviously. Will keep you updated.

Basically: you might have several version of SSL available in your system, and pgloader is not picking the same .so file at build-time and run-time, hence the error.

**Comment by dimitri** [comment]
In the docker image I have here, I only find one potential ssl shared object that pgloader would use, so it fails to explain the situation :/

**Comment by gavinwahl** [comment]
Presumably the docker image was working before, right? Could you try git bisecting to see if this was introduced by a change in pgloader?

**Comment by dimitri** [comment]
Well my docker image works well, I'm trying to blind debug yours :/ Can you do `pgloader -version` and `pgloader --help` without failure?

**Comment by julianandrews** [comment]
@dimitri Have you tried building a new docker image? I built one using the instructions from the bottom of the `INSTALL.md` file and got the same issue; it builds fine, but fails if you run it. I haven't worked much with Docker, but I would assume that should be pretty easy to reproduce.

**Comment by julianandrews** [comment]
Ohh! Forgot to mention; `pgloader --version` and `pgloader --help` both work. In case it helps:

    root@82491ecf4faa:/opt/src/pgloader/build/bin# ./pgloader --version
    pgloader version "3.3.0.50~devel"
    compiled with SBCL 1.2.4.debian

But with a command file I get the same error as @radu-porumb and @gavinwahl

**Comment by dimitri** [comment]
Ok I can now reproduce. Will try to understand and fix, thanks.

```
$ docker run --rm --name pgloader pgloader:debian pgloader --dry-run ./test/parse/magnus.load 
An unhandled error condition has been signalled:
   Undefined alien: "SSL_CTX_set_default_verify_dir"
```

**Comment by gavinwahl** [comment]
Hey @dimitri, thanks for looking into this. Have you been able to figure anything out yet?

**Comment by dimitri** [comment]
Not yet. I'm quite out of my league on CFFI concerns unfortunatly :/

**Comment by dimitri** [comment]
I just opened a bug on CFFI bug tracker: https://bugs.launchpad.net/cffi/+bug/1549280

**Comment by gavinwahl** [comment]
On another system, I'm getting 'Undefined alien: "SSLv3_client_method"'. SSLv3 support has been removed from ssl -- could the bindings be out of date?

**Comment by dimitri** [comment]
Given the preference towards either binary packages in debian or the docker image, I think the way the libs were treated isn't warranted anymore: we now expect the libs to be found at runtime at the same place than they were found at build time. Doing nothing special allows me to pass the test locally:

```
docker run --rm --name pgloader pgloader:debian pgloader --dry-run ./test/parse/magnus.load 
2016-03-05T21:45:06.058000Z LOG Main logs in '/tmp/pgloader/pgloader.log'
2016-03-05T21:45:06.063000Z LOG Data errors in '/tmp/pgloader/'
2016-03-05T21:45:06.066000Z LOG Parsing commands from file #P"/opt/src/pgloader/test/parse/magnus.load"
2016-03-05T21:45:06.066000Z LOG Loading the FreeTDS shared librairy (sybdb)
2016-03-05T21:45:06.066000Z LOG DRY RUN, only checking connections.
2016-03-05T21:45:06.067000Z LOG Attempting to connect to #<MSSQL-CONNECTION mssql://dim@11.22.33.44:1433/magnus_customer_sample {1009031EE3}>
  C-c C-c^C2016-03-05T21:47:03.344000Z FATAL Failed to connect to #<MSSQL-CONNECTION mssql://dim@11.22.33.44:1433/magnus_customer_sample {1009031EE3}>: Failed to connect to mssql at "52.27.252.43" (port 1433) as user "dim": Interactive interrupt at #x7FFFF71D350D.
2016-03-05T21:47:03.344000Z LOG Attempting to connect to #<PGSQL-CONNECTION pgsql://dim@localhost:54393/magnush {10090331A3}>
2016-03-05T21:47:03.345000Z FATAL Failed to connect to #<PGSQL-CONNECTION pgsql://dim@localhost:54393/magnush {10090331A3}>: Failed to connect to pgsql at "localhost" (port 54393) as user "dim": Database error: Socket error in "connect": ECONNREFUSED (Connection refused)
```

Yes, I couldn't set myself to wait until the end of the TCP timeout here.
