### ISSUE TITLE
Compiling for Windows

### ISSUE THREAD

**Issue by alokshah14** [dimitri/pgloader#332]
When compiling for windows under Ubuntu 14.04 LTS using the following command:

    make pgloader OS="Windows_NT"

the program runs fine and create a EXE file. But when I try to run it under windows it comes up as 16-bit application and won't run. Can you please advise on how to fix the issue?

Thanks

**Comment by dimitri** [comment]
I have no idea what the OS parameter here will have as an impact on the build tools such as SBCL. When I wanted a binary for windows I compiled on windows directly. It's easy to get a recent SBCL binary distribution for windows, then you need the usual `make` and friends unix tools.
