### ISSUE TITLE
MySQL'varbinary NOT NULL DEFAULT' leads to 'assertion (STRING= "" VECTOR) failed'

### ISSUE THREAD

**Issue by natmaka** [dimitri/pgloader#333]
My context:

pgloader version "3.3.64ab4d2" compiled with SBCL 1.2.4.debian
MySQL 5.5 and PostgreSQL 9.4 from Debian amd64 stable
To exhibit the problem

on a MySQL empty DB 'tst1' do
```
CREATE TABLE `tst3` (   `foo` varbinary(30) NOT NULL DEFAULT 'unknown' );


pgloader -d --verbose mysql://((your connection string))/tst1 postgresql:/((your connection string))//somedb

```
It produces:
```
An unhandled error condition has been signalled:
   The assertion (STRING= "" VECTOR) failed with VECTOR = "unknown".
```
Thx!

**Comment by dimitri** [comment]
Please build from (fresh) sources and try again. The "unknown" string doesn't make it into a bytea field so in the current code a WARNING is issued and no default is defined. You can use `ALTER TABLE ... COLUMN ... SET DEFAULT` after the migration is done to fix that, either in the *AFTER LOAD* clause or the `--after` command line switch.
