### ISSUE TITLE
MySQL views are not loaded

### ISSUE THREAD

**Issue by haisamido** [dimitri/pgloader#338]
It appears that MySQL views are ignored by pgloader.  Perhaps I'm missing a cast or an argument.

I downloaded the latest pgloader code and compiled on CentOS 7. So I have this version:

```
pgloader version "3.3.765bbb7"
compiled with SBCL 1.2.8-1.el7

and ran with this cast

--cast "type bigint when (= 20 precision) to bigint drop typemod"

```

**Comment by dimitri** [comment]
MySQL uses a SQL dialect which is very far from the standard and from PostgreSQL. To be able to transfer view definitions we would need to be able to transform the MySQL dialect into proper SQL. Note that in some cases we know it's impossible to match MySQL behavior, e.g. for `GROUP BY` forms using non-aggregated non-grouped projections (bare fields in the `SELECT` clause).

What pgloader can do is *MATERIALIZE* views by porting over the view definition then the data obtained via `SELECT * FROM view`.

**Comment by haisamido** [comment]
Thanks @dimitri .  Are you saying that pgloader is currently able to MATERIALIZE MySQL views by porting over the view definition via SELECT * FROM view? If so how does one do that?

**Comment by dimitri** [comment]
The MySQL catalogs are exposing the view structure in the same way as a table structure, and that's what pgloader uses in both cases (`information_schema.tables` and `information_schema.columns`). So pgloader has no idea about the view definition itself, but can still create a table that will host the view data ...

**Comment by haisamido** [comment]
Sorry, perhaps I'm misunderstanding. So can pgloader "create a table that will host the view data" automagically, if so how does one do that?

**Comment by dimitri** [comment]
See the section about *MATERIALIZING VIEWS* in the docs, it should be all you need really... ask more questions as needed here, of course!
