### ISSUE TITLE
MSSQL import broken

### ISSUE THREAD

**Issue by sKolar42** [dimitri/pgloader#340]
There are a few places in which I've noticed that MSSQL import doesn't work:

- In mssql.lisp, fetch-metadata returns an integer, when it's expected to return catalog.
- In mssql-schema.lisp, you removed the qualify-name function, but list-all-indexes and list-all-fkeys still use it.

These are the only two I've noticed so far.

**Comment by dimitri** [comment]
Thanks! Would you send a patch to fix those? it would be great!

**Comment by dimitri** [comment]
I think both issues are fixed now. Thanks for the report.
