### ISSUE TITLE
Creating a table with default timestamp value has invalid quotes

### ISSUE THREAD

**Issue by pathikrit** [dimitri/pgloader#341]
I get this:

```
2016-02-18T17:43:17.385000-08:00 ERROR Database error 0A000: date/time value "current" is no longer supported
QUERY: CREATE TABLE foo
(
  id                     bigserial not null,
  name              text,
  created_on             timestamptz(6) not null default 'CURRENT_TIMESTAMP(6)'
);
2016-02-18T17:43:17.385000-08:00 FATAL Failed to create the schema, see above.
```

But, when I remove the single-quotes, it works:
```
CREATE TABLE foo
(
  id                     bigserial not null,
  name              text,
  created_on             timestamptz(6) not null default CURRENT_TIMESTAMP(6)
);
```

This my config:

```
LOAD database
  FROM  mysql://dev:dev@localhost/main
  INTO  postgresql://dev@localhost/main
  WITH  include drop, create tables, no truncate, create indexes, reset sequences, foreign keys
  SET   maintenance_work_mem to '512MB', work_mem to '128MB', search_path to 'main'
  CAST type datetime to timestamptz
  BEFORE LOAD DO $$ CREATE SCHEMA IF NOT EXISTS main; $$
;
```

**Comment by dimitri** [comment]
Can you provide me with the MySQL table definition so that I can reproduce the bug locally then fix it?

**Comment by pathikrit** [comment]
Here it is:

```sql
CREATE TABLE `foo` (
  `id` int(11) NOT NULL AUTO_INCREMENT,  
  `name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_on` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_on` datetime(6) DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`)  
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
```

**Comment by pathikrit** [comment]
I know PostgreSQL does not support the `ON UPDATE` as MYSQL does - but just putting it there for you. Also, `INT NOT NULL AUTO_INCREMENT` should map to `SERIA` and not `BIGSERIAL` I think.

**Comment by dimitri** [comment]
Seems I can't quite reproduce your situation here:

```
    -> ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '6),
  `updated_on` datetime(6) DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(6),
  PR' at line 4
```

And with minimal tweaking, still failing:

```sql
 CREATE TABLE `default_current_timestamp` (
  `id` int(11) NOT NULL AUTO_INCREMENT,  
  `name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_on` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_on` datetime(6) DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)  
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
    -> ERROR 1067 (42000): Invalid default value for 'created_on'
```

**Comment by pathikrit** [comment]
Had a slight typo. See now:

```
sql> CREATE TABLE `default_current_timestamp` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_on` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_on` datetime(6) DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
[2016-02-19 22:29:15] completed in 525ms
```

**Comment by dimitri** [comment]
Just tried a blind fix that should do, please report back! (was hesitant to do so but the fix is very well contained so it should be ok).

**Comment by dancek** [comment]
I have a similar issue with pgloader installed from Homebrew on macOS.

```console
$ pgloader --version
pgloader version "3.4.1"
compiled with SBCL 1.4.4
```

I get the error

```sql
2018-04-24T12:57:08.497000+01:00 ERROR Database error 0A000: date/time value "current" is no longer supported
QUERY: CREATE TABLE mydb.file_migrationdata
(
  id                bigserial not null,
  creation_time     timestamptz not null default 'current_timestamp()',
  importid          bigint default NULL,
  modification_time timestamptz not null default 'current_timestamp()',
  original_id       numeric not null,
  container_name    varchar(255) not null
);
```

The table definition (created by mysqldump) is like:

```sql
CREATE TABLE `file_migrationdata` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `creation_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `importId` int(11) DEFAULT NULL,
  `modification_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `original_id` bigint(20) NOT NULL,
  `container_name` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_FILE_MIGRATIONDATA_ID` (`id`),
  KEY `IDX_ORIGINAL_ID` (`original_id`),
  KEY `IDX_CONTAINER_NAME` (`container_name`),
  CONSTRAINT `FK_FILE_MIGRATIONDATA_ORIGINAL_ID` FOREIGN KEY (`original_id`) REFERENCES `file_metadata` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

Please inform me if there is any other information that would be helpful.

**Comment by dimitri** [comment]
I see your using pgloader 3.4.1, please compile from source and try again, I believe the error is fixed in the source repository.

**Comment by dancek** [comment]
Yes, the issue goes away by running the HEAD version.

**Comment by lidragonli** [comment]
I have the similar issue too. 

```
pgloader --version
pgloader version "3.4.2~devel"
compiled with SBCL 1.3.14.debian
```

I used the latest docker image.

```
master /Dockerfile latest 8 days ago 2018-04-29T17:06:36.387Z
```

I got this error:
```
ERROR Database error 0A000: date/time value "current" is no longer supported
QUERY: CREATE TABLE act_hi_identitylink
(
  id_             varchar(64) not null,
  timestamp_      timestamptz not null default 'current_timestamp(3)',
  type_           varchar(255) default NULL,
  user_id_        varchar(255) default NULL,
  group_id_       varchar(255) default NULL,
  task_id_        varchar(64) default NULL,
  proc_def_id_    varchar(64) default NULL,
  operation_type_ varchar(64) default NULL,
  assigner_id_    varchar(64) default NULL,
  proc_def_key_   varchar(255) default NULL,
  tenant_id_      varchar(64) default NULL
);
2018-05-07T09:12:06.691000Z FATAL Failed to create the schema, see above.
```
The mariadb create statement:
```
CREATE TABLE `act_hi_identitylink` (
  `ID_` varchar(64) COLLATE utf8_bin NOT NULL,
  `TIMESTAMP_` timestamp(3) NOT NULL DEFAULT current_timestamp(3) ON UPDATE current_timestamp(3),
  `TYPE_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `USER_ID_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `GROUP_ID_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `TASK_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `PROC_DEF_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `OPERATION_TYPE_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `ASSIGNER_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `PROC_DEF_KEY_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `TENANT_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`ID_`),
  KEY `ACT_IDX_HI_IDENT_LNK_USER` (`USER_ID_`),
  KEY `ACT_IDX_HI_IDENT_LNK_GROUP` (`GROUP_ID_`),
  KEY `ACT_IDX_HI_IDENT_LNK_TENANT_ID` (`TENANT_ID_`),
  KEY `ACT_IDX_HI_IDENT_LNK_PROC_DEF_KEY` (`PROC_DEF_KEY_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
```

**Comment by handerpeder** [comment]
I'm getting the same error

```
2019-04-11T23:10:11.540000+02:00 ERROR Database error 0A000: date/time value "current" is no longer supported
QUERY: CREATE TABLE mydb.test 
(
  ts timestamptz not null default 'current_timestamp(3)'
);
```

Create table with
```
MariaDB [mydb]> create table test ( ts datetime(3) not null default current_timestamp(3) );
```

```
$ pgloader --version
pgloader version "3.6.1"
compiled with SBCL 1.4.16

$ mysql --version
mysql  Ver 15.1 Distrib 10.3.14-MariaDB, for Linux (x86_64) using readline 5.1
```

**Comment by r0bis** [comment]
I can confirm that with more recent version 

`pgloader version "3.6.2"
compiled with SBCL 2.0.1`

it works well

**Comment by fjitexvietnam** [comment]
Xin giup tôi :


-- Cấu trúc bảng cho bảng `wp_404_to_301`
--

CREATE TABLE `wp_404_to_301` (
  `id` bigint(20) NOT NULL,
  `date` datetime NOT NULL,
  `url` varchar(512) NOT NULL,
  `ref` varchar(512) NOT NULL DEFAULT '',
  `ip` varchar(40) NOT NULL DEFAULT '',
  `ua` varchar(512) NOT NULL DEFAULT '',
  `redirect` varchar(512) DEFAULT '',
  `options` longtext DEFAULT NULL,
  `status` bigint(20) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Đang đổ dữ liệu cho bảng `wp_404_to_301`
--

**Comment by khanhdb** [comment]
I'm faced with this issue when using `pgloader version "3.6.9"
compiled with SBCL 2.2.10`

**Comment by linux-root** [comment]
I'm faced with this issue when using `pgloader version "3.6.9" compiled with SBCL 2.2.10`

**Comment by subkryl** [comment]
Hi there,

I just push some materials if it can help.

MariaDB [mattermost]> show create table focalboard_blocks;
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+                       
| Table             | Create Table                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                             |                       
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+                       
| focalboard_blocks | CREATE TABLE `focalboard_blocks` (
  `id` varchar(36) NOT NULL,
  `insert_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `parent_id` varchar(36) DEFAULT NULL,
  `schema` bigint(20) DEFAULT NULL,
  `type` text DEFAULT NULL,
  `title` text DEFAULT NULL,
  `fields` text DEFAULT NULL,
  `create_at` bigint(20) DEFAULT NULL,
  `update_at` bigint(20) DEFAULT NULL,
  `delete_at` bigint(20) DEFAULT NULL,
  `root_id` varchar(36) DEFAULT NULL,
  `modified_by` varchar(36) NOT NULL,
  `workspace_id` varchar(36) NOT NULL,
  `created_by` varchar(36) NOT NULL,
  PRIMARY KEY (`workspace_id`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+                       
1 row in set (0.00 sec)


LOAD database
  FROM mysql://mmuser:XXX@mysql/mattermost
  INTO postgres://mmuser:XXX@postgres/mattermost
  WITH  include drop, create tables, no truncate, create indexes, reset sequences, foreign keys
  SET   maintenance_work_mem to '512MB', work_mem to '128MB', search_path to 'main'
  CAST column focalboard_blocks.insert_at to "timestamptz not null default current_timestamp(6)" drop default drop not null
;

2023-04-07T01:10:43.208005Z ERROR Database error 42601: syntax error at or near "("
QUERY: CREATE TABLE mattermost.focalboard_blocks
(
  id           varchar(36) not null,
  insert_at    timestamptz not null default current_timestamp(6)(6),
  parent_id    varchar(36) default NULL,
  schema       bigint default NULL,
  type         text default NULL,
  title        text default NULL,
  fields       text default NULL,
  create_at    bigint default NULL,
  update_at    bigint default NULL,
  delete_at    bigint default NULL,
  root_id      varchar(36) default NULL,
  modified_by  varchar(36) not null,
  workspace_id varchar(36) not null,
  created_by   varchar(36) not null
);

(6)(6) << ? :-)

If I use :

LOAD database
  FROM mysql://mmuser:meashegh3eesh3Phe4ch@mysql/mattermost
  INTO postgres://mmuser:meashegh3eesh3Phe4ch@postgres/mattermost
  WITH  include drop, create tables, no truncate, create indexes, reset sequences, foreign keys
  SET   maintenance_work_mem to '512MB', work_mem to '128MB', search_path to 'main'
  -- CAST column focalboard_blocks.insert_at to "timestamptz not null default current_timestamp(6)" drop default drop not null
;

2023-04-07T01:12:57.112005Z ERROR Database error 0A000: date/time value "current" is no longer supported
QUERY: CREATE TABLE mattermost.focalboard_blocks 
(
  id           varchar(36) not null,
  insert_at    timestamptz not null default 'current_timestamp(6)',
  parent_id    varchar(36) default NULL,
  schema       bigint default NULL,
  type         text default NULL,
  title        text default NULL,
  fields       text default NULL,
  create_at    bigint default NULL,
  update_at    bigint default NULL,
  delete_at    bigint default NULL,
  root_id      varchar(36) default NULL,
  modified_by  varchar(36) not null,
  workspace_id varchar(36) not null,
  created_by   varchar(36) not null
);

I used the last docker image and also the last master branch builded directly inside the docker image after adding few dependencies. But the result is the same.

**Comment by chlupnoha** [comment]
I employed the following workaround:
```
LOAD
DATABASE from mysql://xxx:xxx@mariadb:3306/mattermost
INTO postgresql://xxx:xxxx@localhost:5432/mattermost
CAST type datetime to timestamp, type timestamp to "timestamptz not null default current_timestamp" drop default drop not null
```
As mentioned above, the issue lies with the single quotes.
