### ISSUE TITLE
Best way to use a temporary table when loading data?

### ISSUE THREAD

**Issue by thbar** [dimitri/pgloader#344]
I'm trying to determine the best way to load the data into a temporary table (e.g. `tmp_my_target`), then if and only if everything went fine, to drop and replace the existing `my_target` atomically. Is there a built-in feature specifically for that, or should I just rely on `AFTER LOAD DO`? Thanks!

**Comment by dimitri** [comment]
A temporary table is a per-session object so you won't be able to achieve what you need with before and after sections. Unless you mean a *normal* table that you drop when the load is done, that is easy to do with before and after sections...

**Comment by thbar** [comment]
Thanks @dimitri. I didn't have a clear idea in mind, so either a real temporary table (but I kind of expected what you replied) or a "real" table, maybe stored in a different schema to avoid pollution. This replies to my question nonetheless, I'll use `AFTER LOAD DO` or something similar (from caller program) to handle this. Thanks for the quick reply!
