### ISSUE TITLE
Invalid query generated when migrating from MySQL

### ISSUE THREAD

**Issue by mausch** [dimitri/pgloader#345]
Thanks for this project!

Just getting started with pgloader, I run this:

`pgloader -vd mysql://my_user:my_pass@localhost/my_db postgresql://pguser:pgpass@localhost/my_db`

and get this error:

```
MySQL Error [1055]: "Expression #6 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'information_schema.rc.UPDATE_RULE' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by"
```

The offending query is:

```sql
SELECT tc.table_name, tc.constraint_name, k.referenced_table_name ft,

           group_concat(         k.column_name
                        order by k.ordinal_position) as cols,

           group_concat(         k.referenced_column_name
                        order by k.position_in_unique_constraint) as fcols,

           rc.update_rule, rc.delete_rule

      FROM information_schema.table_constraints tc

           JOIN information_schema.referential_constraints rc
             ON rc.constraint_schema = tc.table_schema
            AND rc.constraint_name = tc.constraint_name
            AND rc.table_name = tc.table_name

      LEFT JOIN information_schema.key_column_usage k
             ON k.table_schema = tc.table_schema
            AND k.table_name = tc.table_name
            AND k.constraint_name = tc.constraint_name

    WHERE     tc.table_schema = 'company_information_system'
          AND k.referenced_table_schema = 'company_information_system'
          AND tc.constraint_type = 'FOREIGN KEY'
         
 GROUP BY tc.table_name, tc.constraint_name, ft
```

which would be fixed by adding the last two fields `rc.update_rule, rc.delete_rule` to the group by clause:

```sql
SELECT tc.table_name, tc.constraint_name, k.referenced_table_name ft,

           group_concat(         k.column_name
                        order by k.ordinal_position) as cols,

           group_concat(         k.referenced_column_name
                        order by k.position_in_unique_constraint) as fcols,

           rc.update_rule, rc.delete_rule

      FROM information_schema.table_constraints tc

           JOIN information_schema.referential_constraints rc
             ON rc.constraint_schema = tc.table_schema
            AND rc.constraint_name = tc.constraint_name
            AND rc.table_name = tc.table_name

      LEFT JOIN information_schema.key_column_usage k
             ON k.table_schema = tc.table_schema
            AND k.table_name = tc.table_name
            AND k.constraint_name = tc.constraint_name

    WHERE     tc.table_schema = 'company_information_system'
          AND k.referenced_table_schema = 'company_information_system'
          AND tc.constraint_type = 'FOREIGN KEY'
         
 GROUP BY tc.table_name, tc.constraint_name, rc.update_rule, rc.delete_rule, ft
```

**Comment by mausch** [comment]
I removed `only_full_group_by` from the global `sql_mode` and things worked.

[`only_full_group_by` is a default in MySQL 5.7](http://dev.mysql.com/doc/refman/5.7/en/sql-mode.html) , apparently this changed in 5.7.

Probably worth changing the SQL used by pgloader... or at least documenting this.

**Comment by dimitri** [comment]
The change you are proposing might return a different number of rows, right? Can you edit the query in the sources and try it, see what happens and report back? Other than that, I guess we could set the `only_full_group_by` parameter to `false` in the MySQL connection where we fetch metadata...

Maybe we should even support a `SET` clause for MySQL, while at it... but I hope it's not required.

**Comment by mausch** [comment]
To be honest I had never seen this non-standard usage of group-by.
The behaviour for 5.6 and previous versions is described in detail in http://dev.mysql.com/doc/refman/5.6/en/group-by-handling.html#group-by-handling .
I ran a few sample queries on one of my databases (not related to pgloader at all) and they seem to behave the same way. The only difference I see is that including all non-aggregated fields in the group-by clause is 100x slower approx (!).
I'll see if I can make some time to change the query in the sources and see what happens.

**Comment by thiagokronig** [comment]
@dimitri and @mausch,

I think there is as way to refactor the query without breaking behavior.

The inner join with the `referential_constraints` table can be done outside of the main query if `table_schema` is projected and be part of the `group by` clause. That's easy to validate, because the `table_schema` is already fixed on the `where` clause.

Following this reasoning, we can refactor it to:

```sql
SELECT s.table_name, s.constraint_name, s.ft, s.cols, s.fcols

FROM (
  SELECT tc.table_schema, tc.table_name, tc.constraint_name, k.referenced_table_name ft,

             group_concat(         k.column_name
                          order by k.ordinal_position) as cols,

             group_concat(         k.referenced_column_name
                          order by k.position_in_unique_constraint) as fcols

        FROM information_schema.table_constraints tc

        LEFT JOIN information_schema.key_column_usage k
               ON k.table_schema = tc.table_schema
              AND k.table_name = tc.table_name
              AND k.constraint_name = tc.constraint_name

      WHERE     tc.table_schema = 'company_information_system'
            AND k.referenced_table_schema = 'company_information_system'
            AND tc.constraint_type = 'FOREIGN KEY'

   GROUP BY tc.table_schema, tc.table_name, tc.constraint_name, ft
) s
             JOIN information_schema.referential_constraints rc
               ON rc.constraint_schema = s.table_schema
              AND rc.constraint_name = s.constraint_name
              AND rc.table_name = s.table_name
```

**Comment by dimitri** [comment]
Thanks @thiagokronig, I integrated your version of the query, it should be ok now. At least it didn't break my local tests.

**Comment by mausch** [comment]
Cool, thanks @thiagokronig

**Comment by benlieb** [comment]
I'm having the same issue. I installed via homebrew but the latest version installs is 3.2.2. What should be my solution?

**Comment by dimitri** [comment]
Compile pgloader from sources, fresh from git master's branch! Another release is showing up on the radar, but don't wait for it.

**Comment by vladra** [comment]
Compiled today from source (3.3.7) and got same error

`MySQL Error [1055]: "Expression #3 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'information_schema.statistics.NON_UNIQUE' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by"`

Any tips?

**Comment by dimitri** [comment]
Consider `make clean` and compiling again (with `make`), then `./build/bin/pgloader --version`. BTW 3.3.7 doesn't look like a version of pgloader I know of...

**Comment by vladra** [comment]
Sorry, correct version is:

    pgloader version "3.3.7af6c7a"
    compiled with SBCL 1.3.4

**Comment by dimitri** [comment]
So MySQL 5.7 fixes the `GROUP BY` behavior but keeps its non-normalized specific catalogs, hu? so much fun.
