### ISSUE TITLE
Truncated Column-Names

### ISSUE THREAD

**Issue by mnietz** [dimitri/pgloader#353]
Due to the limit in postgres, the maximum length of a column-name is 63 characters. A longer column-name will be truncated. When trying to migrate such a column from mysql to postgres using pgloader, it stucks after the message that the name will be truncated.

Maybe pgloader can be improved by catching the new column-name ?!

**Comment by dimitri** [comment]
I can't reproduce the problem with pgloader being stuck. Which version are you using, and if not the most recent, can you try with a build from a fresh git checkout of the master's branch?

**Comment by paracord55** [comment]
I have the same problem. During the migration from MSSQL to Postgres, pgloader truncates long column names. The table is created with short column names, but for some reason, no data is added to the table. I get an error like this:
Can't init COPY to "xxx"."TABLE1"...
PostgreSQL warning: identifier "aaa1111" will be truncated to "aaa1"

pgloader version "3.6.10~devel"

**Comment by GingerAdonis** [comment]
> I have the same problem. During the migration from MSSQL to Postgres, pgloader truncates long column names. The table is created with short column names, but for some reason, no data is added to the table. I get an error like this: Can't init COPY to "xxx"."TABLE1"... PostgreSQL warning: identifier "aaa1111" will be truncated to "aaa1"
> 
> pgloader version "3.6.10~devel"

You might want to take a look at [pgferry](https://github.com/Limetric/pgferry), which isn't affected by this issue.

**Comment by paracord55** [comment]
> > I have the same problem. During the migration from MSSQL to Postgres, pgloader truncates long column names. The table is created with short column names, but for some reason, no data is added to the table. I get an error like this: Can't init COPY to "xxx"."TABLE1"... PostgreSQL warning: identifier "aaa1111" will be truncated to "aaa1"
> > pgloader version "3.6.10~devel"
> 
> You might want to take a look at [pgferry](https://github.com/Limetric/pgferry), which isn't affected by this issue.

Thank you. I'll try.

**Comment by paracord55** [comment]
@dimitri 
Is there a solution to this problem in pgloader?

**Comment by paracord55** [comment]
> > I have the same problem. During the migration from MSSQL to Postgres, pgloader truncates long column names. The table is created with short column names, but for some reason, no data is added to the table. I get an error like this: Can't init COPY to "xxx"."TABLE1"... PostgreSQL warning: identifier "aaa1111" will be truncated to "aaa1"
> > pgloader version "3.6.10~devel"
> 
> You might want to take a look at [pgferry](https://github.com/Limetric/pgferry), which isn't affected by this issue.

@GingerAdonis 
pgferry has a similar error: https://github.com/Limetric/pgferry/issues/230

**Comment by dimitri** [comment]
The problem is now solved in pgloader by recognising the error condition and erroring out and asking the user to clean-up the source table definition before the migration ; that's the easiest way forward --- your application will need to work with the new column names anyways.

**Comment by paracord55** [comment]
> В pgloader эта проблема теперь решена путем распознавания ошибки, выдачи сообщения об ошибке и запроса пользователю на очистку определения исходной таблицы перед миграцией; это самый простой способ решения проблемы — вашему приложению все равно придется работать с новыми именами столбцов.


Often, it is not possible to modify column names in the source database because an application work on it.
It would be great, if pgloader could automatically rename these columns to shorter versions on the destination side and also resolve name collision errors caused by truncation.

**Comment by dimitri** [comment]
What kind of policy could be used to produce new names in a way that the application is going to be able to adjust? If there is no automated way to make it work past the migration anyway, why automate the migration. We could of course invent a renaming policy but I wonder if that would be any useful...

That said we already have a column renaming mechanism: use a MATERIALIZED VIEW clause in your load file and EXCLUDE the original table.

**Comment by paracord55** [comment]
I'll try doing it using a materialized view. Thanks.

> What kind of policy could be used to produce new names in a way that the application is going to be able to adjust? If there is no automated way to make it work past the migration anyway, why automate the migration. We could of course invent a renaming policy but I wonder if that would be any useful...
> 
> That said we already have a column renaming mechanism: use a MATERIALIZED VIEW clause in your load file and EXCLUDE the original table.

I'll try doing it using a materialized view. Thanks.
