### ISSUE TITLE
Error while building pgloader on windows

### ISSUE THREAD

**Issue by devkmd** [dimitri/pgloader#357]
I get the following error while building pgloader [both from master (https://github.com/dimitri/pgloader.git)  and version 3.3.0.50]

```
........;
; caught ERROR:
;   READ error during COMPILE-FILE:
;
;     Symbol "*IXF-STREAM*" not found in the IXF package.
;
;       Line: 70, Column: 25, File-Position: 2414
;
;       Stream: #<SB-INT:FORM-TRACKING-STREAM
;                 for "file C:\\kmd\\work\\na\\pacific\\postgres\\pgloader-3.3.0.50\\pgloader-3.3.0.50\\build\\quicklisp\\dists\\quicklisp\\software\\pgloader-3.2.2\\src\\sources\\ixf\\ixf-schema.lisp"
;                 {1002BE9543}>

debugger invoked on a UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread
#<THREAD "main thread" RUNNING {10029F4843}>:
  COMPILE-FILE-ERROR while
  compiling #<CL-SOURCE-FILE "pgloader" "src" "sources" "ixf" "ixf-schema">
```

Any help will be appreciated... 
thanks

**Comment by dimitri** [comment]
Try to `make clean` and build again: your local copy of cl-ixf is too old for the current version of pgloader.

**Comment by devkmd** [comment]
I did that and i get the same result

**Comment by dimitri** [comment]
Can you try with http://pgloader.io/files/pgloader-bundle-3.3.0.50.tgz ?

**Comment by devkmd** [comment]
I get the following error in the log file and the compilation fails:


WARNING:
   Implicitly creating new generic function METABANG.CL-CONTAINERS::LAST-NODE.
STYLE-WARNING: Undefined alien: "close"
STYLE-WARNING: Undefined alien: "SSL_CTX_set_default_verify_dir"
STYLE-WARNING: Undefined alien: "SSL_CTX_set_default_verify_file"
While evaluating the form starting at line 20, column 0
  of #P"C:/Temp/pgloader-bundle-custom/pgloader-bundle-3.3.0.50/dumper-2SKVI5f7.lisp":Fatal SIMPLE-PROGRAM-ERROR:
  unknown &KEY argument: :DIRECTION

(DUMPER464::BACKTRACE-AS-LIST) ;
                               ; compilation unit aborted
                               ;   caught 2 fatal ERROR conditions

**Comment by dimitri** [comment]
Can you see the build output file (`/tmp/pgloader-bundle-build.log`) for more details about the error?

**Comment by devkmd** [comment]
Attached is the file with error message.
[pgloader-bundle-build.txt](https://github.com/dimitri/pgloader/files/172253/pgloader-bundle-build.txt)

**Comment by dimitri** [comment]
Do you still have `dumper-2SKVI5f7.lisp` around, I'd want to see it now to debug. Thanks!

**Comment by devkmd** [comment]
please find attached the lisp file.
[dumper-2SKVI5f7.txt](https://github.com/dimitri/pgloader/files/173078/dumper-2SKVI5f7.txt)

**Comment by dimitri** [comment]
Closing the issue for cleaning-up of the issue list. Please re-open if problem still is true with current master's code.
