### ISSUE TITLE
can't import mysql schema into postgresql schema differ default schema

### ISSUE THREAD

**Issue by rnz** [dimitri/pgloader#359]
```
LOAD DATABASE
     FROM mysql://user:pass@server-mysql/prod
     INTO postgresql://user:pass@server-pg/dev
     WITH schema only
     SET search_path to prod_mysql
     BEFORE LOAD DO $$ create schema if not exists prod_mysql; $$
;
```

```
$ pgloader mysql-to-pg.load 
An unhandled error condition has been signalled: At

  LOAD DATABASE
  ^ (Line 1, Column 0, Position 0)

Could not parse subexpression ";" when parsing

 Expression PGLOADER.PARSER::COMMANDS
    Subexpression (+ PGLOADER.PARSER::COMMAND)
    Subexpression PGLOADER.PARSER::COMMAND
    Subexpression (AND
                   (OR PGLOADER.PARSER::LOAD-ARCHIVE
                       PGLOADER.PARSER::LOAD-CSV-FILE
                       PGLOADER.PARSER::LOAD-FIXED-COLS-FILE
                       PGLOADER.PARSER::LOAD-COPY-FILE
                       PGLOADER.PARSER::LOAD-DBF-FILE
                       PGLOADER.PARSER::LOAD-IXF-FILE
                       PGLOADER.PARSER::LOAD-MYSQL-DATABASE
                       PGLOADER.PARSER::LOAD-MSSQL-DATABASE
                       PGLOADER.PARSER::LOAD-SQLITE-DATABASE)
                   PGLOADER.PARSER::END-OF-COMMAND)
    Subexpression PGLOADER.PARSER::END-OF-COMMAND
    Subexpression (AND PGLOADER.PARSER::IGNORE-WHITESPACE #\;
                       PGLOADER.PARSER::IGNORE-WHITESPACE)
    Subexpression ";"
```

```
$ pgloader --version
pgloader version "3.2.0"
compiled with SBCL 1.2.4.debian
```

File mysql-to-pg.load have not any special/hidden characters.

**Comment by dimitri** [comment]
I think you have an old version of pgloader, the error message I get here directs towards single-quoting the `'prod_mysql'` schema name in the `WITH` clause:

```
At
       SET search_path to prod_mysql
                          ^ (Line 5, Column 25, Position 153)
```

**Comment by rnz** [comment]
Yes, thank you! But after fix this have next error:
```
LOAD DATABASE
     FROM mysql://user:pass@server-mysql/prod
     INTO postgresql://user:pass@server-pg/dev
     WITH schema only
     SET search_path to 'prod_mysql, public'
     BEFORE LOAD DO $$ create schema if not exists prod_mysql; $$
;
```
```
ERROR Database error 3F000:      
QUERY: CREATE TABLE devices 
(
  device_id              bigint not null,
  device_type            bigint not null default '1',
  imei                   text,
  device_owner           bigint default '1',
  device_state           bigint default '1',
  last_time_activity     timestamptz,
  device_serial          text
);
```

I think error in statement 'CREATE TABLE devices'. It must include schema name as 'CREATE TABLE prod_mysql.devices', but how to set it?

**Comment by dimitri** [comment]
The next lines after that should contain the full error message, can you please paste it?

**Comment by rnz** [comment]
Full message:
```
$ pgloader -v mysql-to-pg.load 
2016-03-17T12:26:04.039000Z NOTICE Starting pgloader, log system is ready.
2016-03-17T12:26:04.048000Z LOG Main logs in 'NIL'
2016-03-17T12:26:04.055000Z LOG Data errors in '/tmp/pgloader/'
2016-03-17T12:26:04.055000Z LOG Parsing commands from file #P"/home/rnz/workspace/pgloader/mysql-to-pg.load"
2016-03-17T12:26:04.255000Z NOTICE create schema if not exists prod_mysql;
2016-03-17T12:26:04.456000Z NOTICE CREATE TABLES
                    table name       read   imported     errors            time
------------------------------  ---------  ---------  ---------  --------------
                   before load          1          1          0          0.046s
               fetch meta data         36         36          0          0.142s
                  create, drop          0          0          0          0.000s
------------------------------  ---------  ---------  ---------  --------------
------------------------------  ---------  ---------  ---------  --------------
------------------------------  ---------  ---------  ---------  --------------
             Total import time          0          0          0          0.188s
2016-03-17T12:26:04.656000Z ERROR Database error 3F000:      
QUERY: CREATE TABLE devices 
(
  device_id              bigint not null,
  device_type            bigint not null default '1',
  imei                   text,
  device_owner           bigint default '1',
  device_state           bigint default '1',
  last_time_activity     timestamptz,
  device_serial          text
);
2016-03-17T12:26:04.656000Z FATAL Failed to create the schema, see above.
```

**Comment by dimitri** [comment]
The error 3F000 from PostgreSQL is documented at http://www.postgresql.org/docs/9.5/interactive/errcodes-appendix.html as being `invalid_schema_name`. In my local test cases when I do reproduce your bug, I see the message:

    2016-03-17T17:21:55.827000+01:00 ERROR Database error 3F000: no schema has been selected to create in

The bug is with the `search_path` setting that only accepts a single entry in pgloader, so please do

         SET search_path to 'prod_mysql'

I leave the bug open so that I may fix it properly later.

**Comment by rnz** [comment]
If I use single entry in `search_path` have next error:
```
2016-03-18T19:01:42.446000Z ERROR Database error 42704:  "geometry"  
QUERY: CREATE TABLE geozones 
(
  geozone_id             bigserial not null,
  account_id             bigint,
  geogroup_id            bigint,
  title                  text not null,
  type                   geozones_type not null,
  envelope               polygon not null,
  polygon                geometry not null,
  color                  text,
  icon                   text,
  address                text,
  description            text
);
2016-03-18T19:01:42.446000Z FATAL Failed to create the schema, see above.
```
Type `geometry` in schema `public` (added by postgis).

**Comment by dimitri** [comment]
After a rebuild you should now be able to `SET search_path to 'prod_mysql, public'` as you wanted to.

**Comment by rnz** [comment]
Hi dmitri!
I try import this database again...
`LOAD DATABASE
     FROM mysql://user:pass@server-mysql/prod
     INTO postgresql://user:pass@server-pg/dev
     WITH schema only, include no drop, create tables, no truncate, create indexes, foreign keys
     SET search_path to 'prod_mysql, prod_support, public'
     BEFORE LOAD DO 
     $$ create schema if not exists prod_mysql; $$
;`

> 2016-12-06T15:42:54.243000Z NOTICE create schema if not exists slnet_mysql;
> 2016-12-06T15:42:54.644000Z NOTICE CREATE TABLES
> 2016-12-06T15:42:54.645000Z NOTICE DROP TYPE "geozones_type" CASCADE;
> 2016-12-06T15:42:54.645000Z NOTICE CREATE TYPE geozones_type AS ENUM ('polygon', 'point');
> 2016-12-06T15:42:54.645000Z NOTICE DROP TYPE "events_contact_channel" CASCADE;
> 2016-12-06T15:42:54.645000Z ERROR Database error 42704:  "events_contact_channel"  
> QUERY: DROP TYPE "events_contact_channel" CASCADE;
> 2016-12-06T15:42:54.645000Z FATAL Failed to create the schema, see above.
This log have two points:
1) geozones_type - is existing type enum (polygon, point, square, polyline) in postgresql in schema prod_support, and notice about drop it - confused me (with 'includle no drop').
2) event_contact - table in mysql and channel - enum('contact','comet','push') type in table event_contact in mysql and not existing in postgresql - why pgloader trying drop it and fail on that (same with 'includle no drop')?

**Comment by dimitri** [comment]
Please upgrade to 3.3.2 that was released recently, I think it fixes your problem here.

**Comment by nicraMarcin** [comment]
Hi,
I've the same issue 
`cat db.load 
LOAD DATABASE
FROM mysql://root:toor@localhost/lms
INTO postgresql:///newdb
WITH schema only, include no drop, create tables, no truncate, create indexes, foreign keys
SET search_path to 'lms_mysql, public'
BEFORE LOAD DO
$$ create schema if not exists lms_mysql; $$
;
`
` pgloader db.load 
2017-01-14T03:28:06.039000+01:00 LOG Main logs in '/tmp/pgloader/pgloader.log'
2017-01-14T03:28:06.048000+01:00 LOG Data errors in '/tmp/pgloader/'
2017-01-14T03:28:06.048000+01:00 LOG Parsing commands from file #P"/var/lib/postgresql/db.load"
2017-01-14T03:28:07.325000+01:00 ERROR Database error 3F000: schema "lms" does'n exist
QUERY: CREATE TABLE lms.aliasassignments 
(
  id           bigserial not null,
  aliasid      bigint not null default '0',
  accountid    bigint not null default '0',
  mail_forward varchar(255) not null default ''
);
2017-01-14T03:28:07.326000+01:00 FATAL Failed to create the schema, see above.
2017-01-14T03:28:07.326000+01:00 LOG report summary reset
       table name       read   imported     errors      total time       read      write
-----------------  ---------  ---------  ---------  --------------  ---------  ---------
      before load          1          1          0          0.005s                     
  fetch meta data        273        273          0          0.220s                     
 Create SQL Types          0          0          0          0.006s                     
    Create tables          0          0          0          0.000s                     
-----------------  ---------  ---------  ---------  --------------  ---------  ---------`
`pgloader -V
pgloader version "3.3.1d35290"
compiled with SBCL 1.3.13.debian
`

**Comment by dimitri** [comment]
This changed in https://github.com/dimitri/pgloader/commit/49316043611519c33ca074ba83028e46cd1d6f30 which states:

his changes the default behavior of pgloader with MySQL from always
targetting the 'public' schema to targetting by default a schema named
the same as the MySQL database. You can revert to the old behavior by
adding a rule:

   ALTER SCHEMA 'dbname' RENAME TO 'public'

So in your case please consider adding the following pgloader clause in your command:

    ALTER SCHEMA 'lms' RENAME TO 'public'

**Comment by dbaq** [comment]
@dimitri sorry to bump this up but I am facing the same issue and the `ALTER SCHEMA` clause does not seem working.

I am using:
```
$ ./pgloader -V
pgloader version "3.3.3c4e64e"
compiled with SBCL 1.3.17
```
and
```
LOAD DATABASE
 from      mysql://root@localhost/accounts_fr_FR
 into postgresql://postgres:postgres@127.0.0.1:5432/accounts_fr_fr

WITH schema only, downcase identifiers, include drop, create tables, no truncate,
    create indexes, reset sequences, foreign keys

ALTER SCHEMA 'accounts_fr_fr' RENAME TO 'public'
;
```

here is my output:

```
2017-05-04T15:49:34.048000-07:00 LOG Main logs in '/private/tmp/pgloader/pgloader.log'
2017-05-04T15:49:34.050000-07:00 LOG Data errors in '/private/tmp/pgloader/'
2017-05-04T15:49:34.050000-07:00 LOG Parsing commands from file #P"/Users/dbaq/tools/pgloader/build/bin/accounts_fr_fr.load"
2017-05-04T15:49:40.343000-07:00 ERROR Database error 3F000: schema "accounts_fr_fr" does not exist
QUERY: CREATE TABLE accounts_fr_fr.action
(
...
);
2017-05-04T15:49:40.343000-07:00 FATAL Failed to create the schema, see above.
2017-05-04T15:49:40.343000-07:00 LOG report summary reset
       table name       read   imported     errors      total time
-----------------  ---------  ---------  ---------  --------------
  fetch meta data       1150       1150          0          0.699s
 Create SQL Types          0          0          0          0.006s
    Create tables          0          0          0          0.000s
-----------------  ---------  ---------  ---------  --------------%
```

Do you have any clues of what I am missing here? Thanks for your help.

**Comment by dimitri** [comment]
You are missing the target schema, pgloader won't create it for you by default. Try to add the following clause to your migration command, as per the documentation:

```
   BEFORE LOAD DO $$ create schema if not exists accounts_fr_fr; $$
```

**Comment by dbaq** [comment]
Thanks, just posting the solution, `ALTER SCHEMA` is case sensitive, in my example I wanted to use the `public` schema as the destination schema. But the source schema was `accounts_fr_FR` and not `accounts_fr_fr`. Works perfectly.

**Comment by dimitri** [comment]
Thanks for feedback!
