### ISSUE TITLE
postgres import fixed Lenght txt

### ISSUE THREAD

**Issue by Summer88** [dimitri/pgloader#360]
Dear Sirs, 
I'm trying to import a fixed lenght column file but seems to missing something:

```
LOAD FIXED  
      FROM inline
             (  
                A           from   0 for  18,  
                B           from   19 for 28,
                C           from   47 for 28,  		
             )  
      into postgresql://user:pwd@server:5432/pippopi/csv
             (  
	        A,B,C
             )
      WITH truncate  

      SET client_encoding to 'utf-8',  
          work_mem to '14MB',  
          standard_conforming_strings to 'on'  

    BEFORE LOAD DO  
     $$ drop table if exists csv; $$,  
     $$ create table csv (  
          A      char(18),  
          B      char(28),  
          C      char(28) 
        );  
   $$;
   

CBR8901027         0000000000000CH-PCB         CS.MILLEFORI.PER.CH         000000000000005999999Z0000022596300000225963000100EURPZ 032015041500009105                            
CBR8901028         0299000070742CK-PCB         CS.MILLEFORI.PER.CK         000000000000005999999Z0000004314500000043145000100EURPZ 032015041500009105                            
CBR8904001         8017963017848G2RL-1-24DC    RE_OM__24DC_1SC_12A         000000000000005999999Z0000004832200000048322000100EURPZ 032015041500009105                            
CBR8904002         8017963017855G2RL-2-24DC    RE_OM__24DC_2SC__8A         000000000000005999999Z0000004590600000045906000100EURPZ 032015041500009105                            
CBR8904008         8000000023568G2R-1 48VDC    RE_OM__48DC_1SC_10A         000000000000005999999Z0000004233900000042339000100EURPZ 032015041500009105                            
CBR8904009         8000000023551G2R-2-48VDC    RE_OM__48DC_2SC__5A         000000000000005999999Z0000004590600000045906000100EURPZ 032015041500009105
```

return this error:

> pgloader -v importmetel
> An unhandled error condition has been signalled: At
> 
>   LOAD FIXED  
>   
>   ^ (Line 1, Column 0, Position 0)
> 
> Could not parse subexpression ")" when parsing
> 
>  Expression PGLOADER.PARSER::COMMANDS
>     Subexpression (+ PGLOADER.PARSER::COMMAND)
>     Subexpression PGLOADER.PARSER::COMMAND
>     Subexpression (AND
>                    (OR PGLOADER.PARSER::LOAD-ARCHIVE
>                        PGLOADER.PARSER::LOAD-CSV-FILE
>                        PGLOADER.PARSER::LOAD-FIXED-COLS-FILE
>                        PGLOADER.PARSER::LOAD-COPY-FILE
>                        PGLOADER.PARSER::LOAD-DBF-FILE
>                        PGLOADER.PARSER::LOAD-IXF-FILE
>                        PGLOADER.PARSER::LOAD-MYSQL-DATABASE
>                        PGLOADER.PARSER::LOAD-MSSQL-DATABASE
>                        PGLOADER.PARSER::LOAD-SQLITE-DATABASE)
>                    PGLOADER.PARSER::END-OF-COMMAND)
>     Subexpression (OR PGLOADER.PARSER::LOAD-ARCHIVE
>                       PGLOADER.PARSER::LOAD-CSV-FILE
>                       PGLOADER.PARSER::LOAD-FIXED-COLS-FILE
>                       PGLOADER.PARSER::LOAD-COPY-FILE
>                       PGLOADER.PARSER::LOAD-DBF-FILE
>                       PGLOADER.PARSER::LOAD-IXF-FILE
>                       PGLOADER.PARSER::LOAD-MYSQL-DATABASE
>                       PGLOADER.PARSER::LOAD-MSSQL-DATABASE
>                       PGLOADER.PARSER::LOAD-SQLITE-DATABASE)
>     Subexpression PGLOADER.PARSER::LOAD-FIXED-COLS-FILE
>     Subexpression PGLOADER.PARSER::LOAD-FIXED-COLS-FILE-COMMAND
>     Subexpression (AND PGLOADER.PARSER::FIXED-SOURCE
>                        (ESRAP:? PGLOADER.PARSER::FILE-ENCODING)
>                        PGLOADER.PARSER::FIXED-SOURCE-FIELD-LIST
>                        PGLOADER.PARSER::TARGET
>                        (ESRAP:? PGLOADER.PARSER::CSV-TARGET-COLUMN-LIST)
>                        PGLOADER.PARSER::LOAD-FIXED-COLS-FILE-OPTIONAL-CLAUSES)
>     Subexpression PGLOADER.PARSER::FIXED-SOURCE-FIELD-LIST
>     Subexpression (AND PGLOADER.PARSER::OPEN-PAREN
>                        PGLOADER.PARSER::FIXED-SOURCE-FIELDS
>                        PGLOADER.PARSER::CLOSE-PAREN)
>     Subexpression PGLOADER.PARSER::CLOSE-PAREN
>     Subexpression (AND PGLOADER.PARSER::IGNORE-WHITESPACE #\)
>                        PGLOADER.PARSER::IGNORE-WHITESPACE)
>     Subexpression ")"
> 
> ; 
> ; compilation unit aborted
> ;   caught 1 fatal ERROR condition
>

**Comment by dimitri** [comment]
You have a trailing comma on this line:

                C           from   47 for 28,
