### ISSUE TITLE
How to cast mysql text type to postgresql jsonb type?

### ISSUE THREAD

**Issue by haisamido** [dimitri/pgloader#362]
I have a few different text columns in separate tables in MySQL that I'd like to cast as jsonb as they are loaded in postgresql.  How do I do that?

**Comment by dimitri** [comment]
If the column content are already formatted as JSON data, then you can simply add a user cast for it:

    --cast 'column table_name.col_name to jsonb'

**Comment by haisamido** [comment]
@dimitri excellent! thank you.
