### ISSUE TITLE
Feature request: Reject records in CSV files with too many fields

### ISSUE THREAD

**Issue by almcleanuk** [dimitri/pgloader#364]
I have a source of data that produces text files with tab separated values where occasional records (one every 100,000) are malformed. Some of the fields contain (stray) tabs and the application emits them unquoted. As a result those records appear to contain extra fields. 

I am trying to get the data and/or the application fixed. However, in scenarios like this it would be helpful if pgloader could identify records with more fields than expected and reject them. It would make the system more robust.

**Comment by dimitri** [comment]
Depending on your exact setup, I think it does that already. Can you paste a self-contained test case here? See the test/ files for examples of the `INLINE` source type and how to make a self-contained test case.
