### ISSUE TITLE
Multicolumn and partial indexes not imported correctly

### ISSUE THREAD

**Issue by gavinwahl** [dimitri/pgloader#365]
I have an MSSQL table that looks like this:
~~~
CREATE TABLE [dbo].[foo] (
	[name] [varchar](50) NOT NULL,
        [type] [varchar](10) NOT NULL,
        [deleted] [bit] NOT NULL
);
CREATE UNIQUE NONCLUSTERED INDEX [foo_name_unique] ON [dbo].[foo] 
(
	[name] ASC, [type] ASC
)
INCLUDE ( [deleted]) 
WHERE ([deleted]=(0));
~~~

pgloader should execute

~~~
CREATE UNIQUE INDEX foo_name_unique ON dbo.foo (name, type) WHERE (NOT deleted);
~~~

But instead it tries to do this:

~~~
CREATE UNIQUE INDEX idx_23575_foo_name_unique ON dbo.foo (deleted);
CREATE UNIQUE INDEX idx_23575_foo_name_unique ON dbo.foo (name);
CREATE UNIQUE INDEX idx_23575_foo_name_unique ON dbo.foo (type);
~~~

This is the wrong index, and causes an error too because all those indexes have the same name.

I think it might not be possible to handle partial indexes, because the conditions actually have SQL conditions in them, which are different in different databases. The issue happens for all multicolumn indexes though, partial or not.

**Comment by dimitri** [comment]
The MS SQL introspection query we have gives that result:
```sql
(with-monitor ()
         (with-connection (*mssql-db* (pgloader:parse-source-string "mssql://root:LovJugwLJmFW758TwNF@52.70.70.243/test"))
           (mssql-query     "select schema_name(schema_id) as SchemaName,
           o.name as TableName,
           REPLACE(i.name, '.', '_') as IndexName,
           co.[name] as ColumnName,
           i.is_unique,
           i.is_primary_key

    from sys.indexes i
         join sys.objects o on i.object_id = o.object_id
         join sys.index_columns ic on ic.object_id = i.object_id
             and ic.index_id = i.index_id
         join sys.columns co on co.object_id = i.object_id
             and co.column_id = ic.column_id

   where schema_name(schema_id) not in ('dto', 'sys')
         
         

order by SchemaName,
         o.[name],
         i.[name],
         ic.is_included_column,
         ic.key_ordinal"
)))

(("dbo" "foo" "foo_name_unique" "name" 1 0)
 ("dbo" "foo" "foo_name_unique" "type" 1 0)
 ("dbo" "foo" "foo_name_unique" "deleted" 1 0)
 ("dbo" "GameCategory" "PK_GameCategory" "GameCategoryId" 1 1)
 ("dbo" "Games" "PK_Games" "GameId" 1 1))
```

Are you in a position to contribute a better index introspection query? We would reproduce the `WHERE` clause as-is ; worst case would be a failure to create the partial index again, which I would accept as *bast effort*. Current situation looks like a bug to me, though.

**Comment by dimitri** [comment]
It should be better now, to some degree:

    CREATE UNIQUE INDEX idx_1451867_foo_name_unique ON dbo.foo (name, type, deleted);

The UNIQUE without the WHERE clause might cause some data to fail to load properly, but to avoid that we need to write a MS SQL simple WHERE clause parser and translate that to PostgreSQL syntax, and adapt values too. It's in the realm of things we can do, it's just not done yet.

**Comment by dimitri** [comment]
Using latest patch we now have the following definition:

    CREATE UNIQUE INDEX idx_1457640_foo_name_unique ON dbo.foo (name, type, deleted) WHERE deleted = 'f';

The previous comment contains a mistake: without the WHERE clause the data would still load properly, but the CREATE INDEX command would then fail when there's non-unique data `WHERE deleted` is true. Anyway, I think it's better now. Let's see if that idea of parsing MS SQL filter clauses was remotely viable, waiting for more bug reports...

**Comment by gavinwahl** [comment]
I ran into an error with `([foo]<>(1))`, `<>` is an alias for `!=`.

**Comment by gavinwahl** [comment]
The behavior of throwing an error when the WHERE clause fails to parse is not great, whenever there's a bug the only option is to not import any indexes. It would be nice to be able to skip unparsable indexes and keep going.

**Comment by dimitri** [comment]
It should be better now, thanks for the error handling remark... sometimes I wish I remembered not to push things developed late in the evening before getting a good sleep and a morning's review... anyway.

**Comment by gavinwahl** [comment]
WHERE clause of `([foo] IS NOT NULL)` gets turned into `foo IS-NOT-NULL`
