### ISSUE TITLE
Character encoding issues on Postgresql Database

### ISSUE THREAD

**Issue by sspr28** [dimitri/pgloader#367]
Hello All,

I am facing character encoding issues on Postgresql database.

Version : 9.2.67 on 64 bit 
Client encoding : WIN1252
Server encoding : UTF8

I am using pgloader which is configured on different server .I can able to connect my postgresql database .When i tried to insert some characters using pgloader the character is not showing on database and it shows in single quotes.

Table  data type : ref character varying(10) NOT NULL
command :  pgloader -c pgloader.conf -2 -d (command i used) - shows rows updated and committed.

I am newbie to postgresql database , can any one help to fix the character issues.

Pgloader conf file : 

```
client_encoding ='UTF8'
copy_every      = 5
commit_every    = 5
#copy_delimiter  = %

null         = ""
empty_string = "\ "

[fixed]
table           = table owner name. TEST
format          = fixed
filename        = test.txt
columns         = *
fixed_specs     = REF:0:10
```

Thanks,
Prabhu

**Comment by dimitri** [comment]
You're using pgloader version 2, that is not supported anymore. Please consider using pgloader version 3.x, either from a binary distribution (debian) or from sources (then git checkout the master branch and build).

**Comment by sspr28** [comment]
Thanks Dimitri.

Good day..I am facing a issues using pgloader configuration file...We are using external file to load data to postgresql database using pgloader..After insert , some of the data's are not inserted as expected null (source has null or blank space)..can you help me how to mention null if blanks on configuration file or any possible way to fix.

Thanks,
Prabhu

**Comment by dimitri** [comment]
See https://github.com/dimitri/pgloader/blob/master/test/archive.load and https://github.com/dimitri/pgloader/blob/master/test/csv-nulls.load for examples on how to do that.

**Comment by sspr28** [comment]
Thanks..will it be applicable foe loading from a text file..

We tried [null if blanks] and getting the same errors...
