### ISSUE TITLE
Error building under Windows (esrap)

### ISSUE THREAD

**Issue by almcleanuk** [dimitri/pgloader#369]
I am having problems building under Windows. The error is listed below.

My environment is:
- Windows 10 (64 bit)
- sbcl v1.3.3 also 64 bit

I've tried building from
- master branch from GitHub
- release_3.2_stable branch from GitHub
- bundle  3.3.0.50 tarball

All produce the same error message.

Any ideas?

	[package lparallel]...............................
	[package esrap]
	; file: C:/Users/Andrew/Downloads/pgloader-master/build/quicklisp/local-projects/esrap/esrap.lisp
	; in: DEFMETHOD PRINT-OBJECT :BEFORE (ESRAP-ERROR T)
	;     (FORMAT STREAM "At~:[~:; end of input~]~2%~
	;                             ~2@T~<~@;~A~:>~%~
	;                             ~2@T~V@T^ (Line ~D, Column ~D, Position ~D)~2%"
	;             (= POSITION (LENGTH ESRAP:TEXT))
	;             (LIST (SUBSEQ ESRAP:TEXT ESRAP::START ESRAP::END))
	;             (- POSITION ESRAP::START) (1+ ESRAP::LINE) (1+ ESRAP::COLUMN)
	;             POSITION)
	;
	; caught ERROR:
	;   during macroexpansion of
	;   (FORMATTER "At~:[~:; end of input~]~2%~
	;                             ~2@T~<~@;~A~:>~%~
	;                             ~2@T~V@T^ (Line ~D, Column ~D, Position ~D)~2%").
	;   Use *BREAK-ON-SIGNALS* to intercept.
	;
	;    error in FORMAT: unknown directive (character: Return)
	;     At~:[~:; end of input~]~2%~
	;                             ~2@T~<~@;~A~:>~%~
	;                             ~2@T~V@T^ (Line ~D, Column ~D, Position ~D)~2%
	;                                ^
	..
	; in: DEFMETHOD PRINT-OBJECT (PARSE-ATTEMPT T)
	;     (FORMAT STREAM "~@<Could not parse ~/esrap:print-expression/. ~
	;                            ~@[Reason:~@:_~@:_~
	;                              ~2@T~A~
	;                            ~@:_~@:_~]~
	;                            Expected:~@:_~@:_~
	;                            ~[~
	;                              <nothing> (should not happen)~
	;                              ~;~
	;                              ~2@T~{~A~}~
	;                              ~:;~
	;                              ~5@T~{~A~^~@:_  or ~}~
	;                            ~]~@[~
	;                            ~@:_~@:_~
	;                            Reached via~@:_~@:_~
	;                            ~@<~5@T~{~/esrap:print-expression/~^~@:_~2@T-> ~}~:>~]~
	;                          ~:>"
	;             (ESRAP::PARSE-ATTEMPT-NONTERMINAL-EXPRESSION ESRAP::OBJECT)
	;             (ESRAP::EXPRESSION-ATTEMPT-COMMENT
	;              (ALEXANDRIA.0.DEV:LASTCAR
	;               (ESRAP::PARSE-ATTEMPT-EXPRESSIONS ESRAP::OBJECT)))
	;             (LENGTH ESRAP::EXPECTED)
	;             (MAPCAR #'ESRAP::DESCRIBE-TERMINAL ESRAP::EXPECTED)
	;             (ESRAP::PARSE-ATTEMPT-EXPRESSIONS ESRAP::OBJECT))
	;
	; caught ERROR:
	;   during macroexpansion of
	;   (FORMATTER "~@<Could not parse ~/esrap:print-expression/. ~
	;                            ~@[Reason:~@:_~@:_~
	;                              ~2@T~A~
	;                            ~@:_~@:_~]~
	;                            Expected:~@:_~@:_~
	;                            ~[~
	;                              <nothing> (should not happen)~
	;                              ~;~
	;                              ~2@T~{~A~}~
	;                              ~:;~
	;                              ~5@T~{~A~^~@:_  or ~}~
	;                            ~]~@[~
	;                            ~@:_~@:_~
	;                            Reached via~@:_~@:_~
	;                            ~@<~5@T~{~/esrap:print-expression/~^~@:_~2@T-> ~}~:>~]~
	;                          ~:>").
	;   Use *BREAK-ON-SIGNALS* to intercept.
	;
	;    error in FORMAT: unknown directive (character: Return)
	;     ~@<Could not parse ~/esrap:print-expression/. ~
	;                            ~@[Reason:~@:_~@:_~
	;                              ~2@T~A~
	;                            ~@:_~@:_~]~
	;                            Expected:~@:_~@:_~
	;                            ~[~
	;                              <nothing> (should not happen)~
	;                              ~;~
	;                              ~2@T~{~A~}~
	;                              ~:;~
	;                              ~5@T~{~A~^~@:_  or ~}~
	;                            ~]~@[~
	;                            ~@:_~@:_~
	;                            Reached via~@:_~@:_~
	;                            ~@<~5@T~{~/esrap:print-expression/~^~@:_~2@T-> ~}~:>~]~
	;                          ~:>
	;                                                    ^
	..
	; in: DEFMETHOD PRINT-OBJECT (LEFT-RECURSION T)
	;     (FORMAT STREAM "Left recursion in nonterminal ~S. ~_Path: ~
	;                     ~{~S~^ -> ~}"
	;             (ESRAP:LEFT-RECURSION-NONTERMINAL CONDITION)
	;             (ESRAP:LEFT-RECURSION-PATH CONDITION))
	;
	; caught ERROR:
	;   during macroexpansion of
	;   (FORMATTER "Left recursion in nonterminal ~S. ~_Path: ~
	;                     ~{~S~^ -> ~}").
	;   Use *BREAK-ON-SIGNALS* to intercept.
	;
	;    error in FORMAT: unknown directive (character: Return)
	;     Left recursion in nonterminal ~S. ~_Path: ~
	;                     ~{~S~^ -> ~}
	;                                                ^
	......................
	debugger invoked on a UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread
	#<THREAD "main thread" RUNNING {10029F4413}>:
	  COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "esrap" "esrap">

**Comment by dimitri** [comment]
We're now back to using esrap as packaged in Quicklisp rather than a *work in progress* branch. Closing that issue, please re-open if needed.
