### ISSUE TITLE
Import numbers with floating point

### ISSUE THREAD

**Issue by omnicode** [dimitri/pgloader#373]
Hello, i try to migrate data from mongodb to postgres. And i have a little problem, mongoexport convert big integer to number like 2.173631433e+09.

So while import i see errors, invalid input syntax for integer: "2.173631433e+09"

So, is any easy way to import data like that or i'll have to convert all numbers in mongoexport files.

Thank you!

**Comment by dimitri** [comment]
Is there a way for mongoexport to avoid using scientific notation here? If not then we can either implement a transformation function in pgloader or have pgloader connect directly to MongoDB and bypass using mongoexport entirely.

Is there a *standard* or commonly expected way to automatically translate a mongo collection into a PostgreSQL table or set of tables?

**Comment by omnicode** [comment]
I'll check documentaion for mongoexport ( https://docs.mongodb.org/manual/reference/program/mongoexport/ ) and don't founf any params to change output ...

I think the best way just implement a transformation function. I think it's easy and quicker. 

I'll have small pet project on MongoDB with ~70M rows, couple of weeks ago i decided to move all data to Postgres and was really surprised then i did't found any standart solution to migrate data. 

So i export all my data by mongoexport and try to load them by using pgloader. No problem on small collections, on big i have error on number with floationg point.

As alternative i use mosql utility, but it's extremly slow 8.2M rows inserted in 20 hours! As the bright side, mosql automatic create tables, but you have to set postgres type for each column

**Comment by dimitri** [comment]
For loading data from MongoDB to PostgreSQL, please have a look at ToroDB at http://www.8kdata.com/torodb/
