### ISSUE TITLE
"debugger invoked on a UNBOUND-SLOT in thread"

### ISSUE THREAD

**Issue by thbar** [dimitri/pgloader#374]
Sorry for the rudimentary bug report - it's a bit late here but I still wanted to share what I have. I'll be able to provide more information later though.

I have 2 configurations (a Mac of one of my developers, but also Travis CI Precise builds) for which I get this error message on a specific CSV file (which I cannot share immediately). On other machines (my Mac + ArchLinux), the error does not occur at all.

The error is:

```
debugger invoked on a UNBOUND-SLOT in thread
#<THREAD "lparallel" RUNNING {1008AD4A53}>:
  The slot PGLOADER.CONNECTION:PATH is unbound in the object
  #<CSV-CONNECTION csv://FILENAME: {1007BEC0E3}>.
```

(on Mac, pgloader has been installed via `homebrew`, while on Ubuntu, via `apt-get install`).

I'll be able to give accurate version numbers later.

**Comment by thbar** [comment]
Possibly related: #313

**Comment by dimitri** [comment]
Can you provide a minimal test case with which to reproduce your error?

**Comment by thbar** [comment]
@dimitri I've been trying to, but nothing successful at this point. I will comment here if I manage to get something smaller (or if upgrading to latest fixes it!).

**Comment by dimitri** [comment]
If there's a setting that would allow you to share the file privately, we can do that too. Just send me an email on the address associated with my github profile.

**Comment by thbar** [comment]
I'll check what can be done here, and most importantly, I'll try again with pgloader master, because a co-worker has indicated that upgrading made the error disappear (take this with a grain of salt though, because on my current machine, I'm not able to reproduce again today, with the previous version either).

In all cases, if I get more information or I'm able to share the file, I'll report back here. Thanks!

**Comment by dimitri** [comment]
Closing now. Consider re-opening if you have to, with more details.

**Comment by abrahamsangha** [comment]
This error occurs for me when I specify an incorrect filepath for the import csv file.

**Comment by dimitri** [comment]
Which version of pgloader are you using? the current one (released yesterday) have some related fixes...
