### ISSUE TITLE
Build failure - need ASDF >= 3.1

### ISSUE THREAD

**Issue by Taylor-Mattison** [dimitri/pgloader#379]
I'm trying to build pgloader on CentOS 6.6. After successfully running the bootstrap-centos.sh, I try to 'make' and get the following error:

debugger invoked on a LOAD-SYSTEM-DEFINITION-ERROR in thread #<THREAD "main thread" RUNNING {1002AABCD3}>: Error while trying to load definition for system bordeaux-threads from pathname /home/devuser/dev/pgloader_3.2/pgloader/build/quicklisp/dists/quicklisp/software/bordeaux-threads-v0.8.5/bordeaux-threads.asd: READ error during COMPILE-FILE: You need ASDF >= 3.1 to load this system correctly.(in form starting at line: 1, column: 0, file-position: 0)

I also tried to build it on Windows 7 and got the same error.

Am I making a mistake or is the build broken for CentOS?

**Comment by dimitri** [comment]
Which version of SBCL do you have? Newer version should already include a recent enough ASDF version... The `bootstrap-cantos.sh` script still downloads SBCL 1.1.14 where the current version is either 1.2.7 or 1.3.3 depending on architecture.

Download one of the binary versions directly, that is either http://prdownloads.sourceforge.net/sbcl/sbcl-1.2.7-x86-linux-binary.tar.bz2 or http://prdownloads.sourceforge.net/sbcl/sbcl-1.3.3-x86-64-linux-binary.tar.bz2 ; I believe they now are compiled with `--with-sb-thread --with-sb-core-compression`.

**Comment by Taylor-Mattison** [comment]
I downloaded and installed the sbcl binary and that fixed the problem! Thanks.
