### ISSUE TITLE
Loading hstore columns

### ISSUE THREAD

**Issue by reist** [dimitri/pgloader#38]
I'm trying to load a CSV custom written for loading into postgres with an hstore column.
I'm getting errors similar to the following from pgloader:

```
debugger invoked on a CL-POSTGRES-ERROR:INTERNAL-ERROR in thread
#<THREAD "lparallel" RUNNING {1009552F23}>:
  Database error XX000: Unexpected end of string
CONTEXT: COPY eventstmp, line 4521, column data: ""email"=>"
2014-02-18T01:42:04.711000+02:00 ERROR Database error XX000: Unexpected end of string
```

Can pgloader be made to load hstores or is it an issue with the Postmodern library?

**Comment by Jacob-Kroeze** [comment]
This is can work for naive load of json, too.
`WITH fields not encloses, fields terminated by '0x02', */a control char/* fields escaped by backslash-quote`

If we can have character-level control of the `fields escaped by ` clause, there is more of a guarantee that json can load. For me, backslash-quote is ok.

**Comment by dimitri** [comment]
I would like to use a real JSON parser here and maybe provide a toolkit/DSL allowing to normalize the JSON data on the fly... Meanwhile I could also extend the escape option clause so that you can use whatever you want to...

**Comment by Jacob-Kroeze** [comment]
Extending the the escape option would be nice.

**Comment by dimitri** [comment]
As the CSV parser we are using in pgloader already allows such characters, allowing it in pgloader was indeed quite easy. It's now done with a new test case, see https://github.com/dimitri/pgloader/blob/master/test/csv-json.load for a full example of what I tested.
