### ISSUE TITLE
MSSQL numeric(19,0) 22P02 invalid syntax for type numeric: "2.0d0"

### ISSUE THREAD

**Issue by deepy** [dimitri/pgloader#382]
> 2016-03-30T11:50:42.663000Z INFO CAST Address.id numeric(19,0) [NIL, NOT NULL, auto_increment] TO "id numeric(19,0) not null default NULL"
> 2016-03-30T11:50:42.717000Z NOTICE CREATE TABLE dbo.address 
> (
>   id             numeric(19,0) not null default NULL,
> 2016-03-30T11:50:43.148000Z ERROR Database error 22P02: invalid input syntax for type numeric: "2.0d0"
> CONTEXT: COPY address, line 1, column id: "2.0d0"

**Comment by dimitri** [comment]
Which version of pgloader is that? Do you have user defined casts? the default cast is using the `float-to-string` transformation function which takes care about that.

**Comment by deepy** [comment]
It's from docker and I'm not using any user-defined casts

**Comment by dimitri** [comment]
Can you run in `--client-min-messages info` mode and paste relevant CAST log lines, please?

**Comment by dimitri** [comment]
Closing now, please consider opening again with more information if needed.
