### ISSUE TITLE
pgloader binaries for Windows

### ISSUE THREAD

**Issue by gmusumeci** [dimitri/pgloader#385]
It is possible to try binaries for windows?
If no could I have some suggestion how to build it?

**Comment by dimitri** [comment]
Last time I did a windows build, the normal `Makefile` worked, see https://github.com/dimitri/pgloader/issues/159 for details and a small patch that disables building with MS SQL support for lack of `freetds.dll`.

**Comment by isapir** [comment]
It'd be great to have some basic guide on building for Windows.  The only statements I found are:

`Building for the Windows™ Operating System is easy enough and the platform is fully supported.`

`Building pgloader on Windows is supported, thanks to Common Lisp implementations being available on that platform, and to the Common Lisp Standard for making it easy to write actually portable code.`

Both of which sound very promising, but do not provide any hints as to how to do so.

Thanks.

**Comment by dimitri** [comment]
I must admit that I have never used the Windows platform, so I can't help much. When I've tried compiling pgloader on this OS, I've installed the usual Unix bits (`make` & co) and the SBCL windows binary, even Emacs, and then reproduced the same steps as on a Unix platform. So for me there's nothing specific about windows. Get the same build dependencies and run the same build commands to obtain a binary...

I don't suppose this is very helpful, but that's all I have. What I would like is to setup something like travis for windows with auto-publishing of the resulting binary artefact, or something to that effect...

**Comment by isapir** [comment]
Yes, CI/CD a-la Travis _would_ be great.  Until then...  here's what I got so far, using MSYS2:

Install `sbcl-1.3.18-x86-64-windows-binary.msi` from http://www.sbcl.org/platform-table.html

Install `MSYS2` from http://www.msys2.org/

Now use MSYS2 shell and install `git` and `make`:

    pacman -S git make

Clone pgloader and switch into directory

    git clone https://github.com/dimitri/pgloader.git pgloader && cd pgloader

Install sqlite and create a symlink as per #440 

    pacman -S sqlite

    ln -s /usr/bin/msys-sqlite3-0.dll /usr/bin/libsqlite3.dll

Now it seems to me like we just need to resolve the sybdb.dll issue as per #542 and call

    make pgloader 

(or maybe `pgloader-standalone` is better)?

I just saw your other post RE: freetds.  I will check and report back.

**Comment by isapir** [comment]
I also tried to download from https://moodle.org/mod/forum/discuss.php?d=232844#p1297504 which is from the link that you posted, but I am getting the same error `[Makefile:104: build/libs.stamp] Error 127`

**Comment by isapir** [comment]
So I tried `make clean` and then `make pgloader` again, but I got this error at the end with a Lisp debugger console, so perhaps `sqlite` is not installed properly after all:

```14,646 bytes in 0.00 seconds (2860.55KB/sec)
; Loading "sqlite"
[package sqlite-ffi]...Help! 11 nested errors. SB-KERNEL:*MAXIMUM-ERROR-DEPTH* exceeded.
Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1002DBB0A3}>
Help! ERROR-ERROR is 2 levels deep. Will try to reset the IO streams by calling STREAM-COLD-INIT-OR-RESET.
Help! 11 nested errors. SB-KERNEL:*MAXIMUM-ERROR-DEPTH* exceeded.
Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1002DBB0A3}>
0: ((FLET SB-IMPL::TRY-TO-INVOKE-DEBUGGER :IN SB-IMPL::ERROR-ERROR))
1: ((FLET #:THUNK :IN SB-IMPL::ERROR-ERROR))
2: (SB-IMPL::%WITH-STANDARD-IO-SYNTAX #<CLOSURE (FLET #:THUNK :IN SB-IMPL::ERROR-ERROR) {941BBB}>)
3: (SB-IMPL::ERROR-ERROR "Help! " 11 " nested errors. " "SB-KERNEL:*MAXIMUM-ERROR-DEPTH* exceeded.")
4: (ERROR SB-SYS:MEMORY-FAULT-ERROR :ADDRESS 160)
5: (SB-KERNEL:HANDLE-WIN32-EXCEPTION #.(SB-SYS:INT-SAP #X00941EE0) #.(SB-SYS:INT-SAP #X00942C70))
6: ("foreign function: #x4338BC")
Help! ERROR-ERROR is 3 levels deep. Will try to THROW this thread to the toplevel.
Help! ERROR-ERROR is 2 levels deep. Will try to reset the IO streams by calling STREAM-COLD-INIT-OR-RESET.
Help! 11 nested errors. SB-KERNEL:*MAXIMUM-ERROR-DEPTH* exceeded.
Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1002DBB0A3}>
0: ((FLET SB-IMPL::TRY-TO-INVOKE-DEBUGGER :IN SB-IMPL::ERROR-ERROR))
1: ((FLET #:THUNK :IN SB-IMPL::ERROR-ERROR))
2: (SB-IMPL::%WITH-STANDARD-IO-SYNTAX #<CLOSURE (FLET #:THUNK :IN SB-IMPL::ERROR-ERROR) {93EF3B}>)
3: (SB-IMPL::ERROR-ERROR "Help! " 11 " nested errors. " "SB-KERNEL:*MAXIMUM-ERROR-DEPTH* exceeded.")
4: (ERROR SB-SYS:MEMORY-FAULT-ERROR :ADDRESS 0)
5: (SB-KERNEL:HANDLE-WIN32-EXCEPTION #.(SB-SYS:INT-SAP #X0093F260) #.(SB-SYS:INT-SAP #X0093FFF0))
6: ("foreign function: #x4338BC")
7: ("foreign function: #x403891")
Help! ERROR-ERROR is 3 levels deep. Will try to THROW this thread to the toplevel.
Help! ERROR-ERROR is 3 levels deep. Will try to THROW this thread to the toplevel.
Help! ERROR-ERROR is 4 levels deep. Will try to halt this thread as a last resort.
fatal error encountered in SBCL pid 10244(tid 00000000009C6610):
%PRIMITIVE HALT called; the party is over.


Welcome to LDB, a low-level debugger for the Lisp runtime environment.
ldb>
```

**Comment by isapir** [comment]
I was able to install freetds on MSYS2 via: 

    pacman -S mingw-w64-x86_64-freetds

For good measure I also created a symlink for the dll:

    ln -s /usr/bin/msys-db-5.3.dll /usr/bin/sybdb.dll

But I'm still getting the error below after `make clean && make pgloader`:

```
==================================================
14,646 bytes in 0.00 seconds (2860.55KB/sec)
; Loading "sqlite"
[package sqlite-ffi]...Help! 11 nested errors. SB-KERNEL:*MAXIMUM-ERROR-DEPTH* exceeded.
Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1002DBB0A3}>
Help! ERROR-ERROR is 2 levels deep. Will try to reset the IO streams by calling STREAM-COLD-INIT-OR-RESET.
Help! 11 nested errors. SB-KERNEL:*MAXIMUM-ERROR-DEPTH* exceeded.
Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1002DBB0A3}>
Help! ERROR-ERROR is 3 levels deep. Will try to THROW this thread to the toplevel.
Help! ERROR-ERROR is 2 levels deep. Will try to reset the IO streams by calling STREAM-COLD-INIT-OR-RESET.
Help! 11 nested errors. SB-KERNEL:*MAXIMUM-ERROR-DEPTH* exceeded.
Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1002DBB0A3}>
0: ((FLET SB-IMPL::TRY-TO-INVOKE-DEBUGGER :IN SB-IMPL::ERROR-ERROR))
1: ((FLET #:THUNK :IN SB-IMPL::ERROR-ERROR))
2: (SB-IMPL::%WITH-STANDARD-IO-SYNTAX #<CLOSURE (FLET #:THUNK :IN SB-IMPL::ERROR-ERROR) {93C27B}>)
3: (SB-IMPL::ERROR-ERROR "Help! " 11 " nested errors. " "SB-KERNEL:*MAXIMUM-ERROR-DEPTH* exceeded.")
4: (ERROR SB-SYS:MEMORY-FAULT-ERROR :ADDRESS 0)
5: (SB-KERNEL:HANDLE-WIN32-EXCEPTION #.(SB-SYS:INT-SAP #X0093C5A0) #.(SB-SYS:INT-SAP #X0093D330))
6: ("foreign function: #x4338BC")
7: ("foreign function: #x403891")
Help! ERROR-ERROR is 3 levels deep. Will try to THROW this thread to the toplevel.
Help! ERROR-ERROR is 3 levels deep. Will try to THROW this thread to the toplevel.
Help! ERROR-ERROR is 4 levels deep. Will try to halt this thread as a last resort.
fatal error encountered in SBCL pid 26220(tid 0000000000A86610):
%PRIMITIVE HALT called; the party is over.


Welcome to LDB, a low-level debugger for the Lisp runtime environment.
ldb> exit
fatal error encountered in SBCL pid 26220(tid 0000000000A86610):
%PRIMITIVE HALT called; the party is over.


Welcome to LDB, a low-level debugger for the Lisp runtime environment.
ldb> exit
make: *** [Makefile:104: build/libs.stamp] Error 1
```

**Comment by manoharankarur** [comment]
@isapir . I am Manoharan. My feeling also same like you. I am not finding much help on pgloader in windows. I am a front-end developer and completely new to this. I need to move a mySQL DB to postgres DB. (my freind has mac machine, he easily moved mysql DBs to postgres using brew command). I dont know how to install pgloader in wondows. what are the tools need to be installed. Could you please help in this? Thanks so much in advance.

**Comment by isapir** [comment]
@manoharankarur The problem is that I still can not get it to work myself yet.  If I will manage that then I will gladly share my Windows binaries so that others can use them without the need to build from source.

**Comment by dimitri** [comment]
As soon as we have a repeatable instruction set for building on windows, let's create a Travis or Docker like setup that provides binaries at each commit on the main branch, please. Best would be that a windows user maintains that part of the setup, and probably consume the binaries on a regular basis, too. Who's up for that?

**Comment by isapir** [comment]
I don't mind taking that on, at least while I still use Windows, but ATM I can't get that repeatable instruction set to work even un-repeatably, i.e. once ;)

**Comment by manoharankarur** [comment]
@isapir & @dimitri  Thanks so much for your time and steps you are taking for windows users.  :)

**Comment by isapir** [comment]
@dimitri Does that error message mean anything to you?

```..........make: *** [Makefile:104: build/libs.stamp] Error 127```

**Comment by dimitri** [comment]
I would make clean or at least have a look at the file listed, other than that are you using GNU Make?

**Comment by isapir** [comment]
This is after a `make clean`.

Using GNU Make from MSYS2:

```
> make --version
GNU Make 4.2.1
Built for x86_64-pc-msys
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by efynn** [comment]
> 这是在一个`make clean`。
> 
> 使用MSYS2中的GNU Make：
> 
> ```
> > make --version
> GNU Make 4.2.1
> Built for x86_64-pc-msys
> Copyright (C) 1988-2016 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> ```
Hello, have you compiled pgloader for Windows?
