### ISSUE TITLE
Rate limit for parallel index creation

### ISSUE THREAD

**Issue by mhagander** [dimitri/pgloader#386]
Right now pgloader will open one connection for each CREATE INDEX statement on a single table, which can run the server out of resources on weird schemas.

For example, loading a single table with approx 150 indexes, will spawn 150 parallel connections each doing CREATE INDEX (after having loaded the table itself across a single connection).

There should be a parameter that lets us limit the number of parallel index builders to say 10 per table (or globally - in my example I'm loading one table only in the process, but it might make sense to do it globally for the rest).

**Comment by dimitri** [comment]
See https://github.com/dimitri/pgloader/blob/master/test/sakila.load#L11 for an example on how to use the new feature.
