### ISSUE TITLE
Set connection parameter application_name

### ISSUE THREAD

**Issue by mhagander** [dimitri/pgloader#387]
It would be nice if pgloader set `application_name` to pgloader while running. Makes it easier to detect what it's doing. (Overridable in the connection string as a nice touch, if you want to identify individual loaders)

Nothing urgent, but would be nice to have.

**Comment by dimitri** [comment]
You can already add an option --set "application_name to 'pgloader'" either at the command line or the in `SET` clause of your .load command.

**Comment by antinescience** [comment]
The only problem with this is that Postgres 8 doesn't support `application_name`, so when you set it by default, running against PG8 results in the following:

```
2017-04-13T08:13:06.067000-04:00 LOG Main logs in '/tmp/pgloader/pgloader.log'
2017-04-13T08:13:06.072000-04:00 LOG Data errors in '/tmp/pgloader/'
2017-04-13T08:13:06.072000-04:00 FATAL An unhandled error condition has been signalled:
   Failed to connect to pgsql at "localhost" (port 5439) as user "root": Database error 42704: unrecognized configuration parameter "application_name"
QUERY: SET application_name TO 'pgloader'
```

**Comment by antinescience** [comment]
(for what it's worth, this will also affect usage with Redshift, since that's a fork of 8.0.2)

**Comment by dimitri** [comment]
I was about to say that PostgreSQL 8.x series all have been EOL for a very long time nowadays. We don't have version dependent SQL slang in pgloader has of now, will have a look at how to do that. Can you report the output of `SELECT version()` from a RedShift instance please?
