### ISSUE TITLE
pgloader - Character encoding issue while loading data from flat file

### ISSUE THREAD

**Issue by sspr28** [dimitri/pgloader#388]
Hi ,

We are getting the below error using pgloader to load data into postgresql database.

```
COPY error: invalid byte sequence for encoding "UTF8": 0xe9 0x72 0x65
```

could you please provide a solution to fix the issue.

Thanks

**Comment by dimitri** [comment]
A solution to what issue exactly? Where is the data coming from? What encoding is the source of the data? Can I have some information such as maybe a pgloader output in `--debug` mode?

**Comment by sspr28** [comment]
Hi Dimitri,

We are newbie to postgresql and pgloader utility .we have provided your suggestion to upgrade the pgloader version to 3.x.

But we would like to know any workaround to fix the data encoding issues.
we are getting the data from another application (it is a mainframe) .We are getting as a text file and we are using pgloader to load the fixed file to postgrsql database.

Error : COPY error: invalid byte sequence for encoding "UTF8": 0xe9 0x72 0x65

Client application encoding file is  ISO-8859 and expect utf8

I have tried to convert the source text file using iconv in linux and it got converted and getting the above errors while loading using pgloader.

I have tried to set client_encoding to LATIN1 on database level and again ends with same errors.

But i can able to insert the data's manually in pgadmin. 

Could you please provide any work around for this issue.

Thanks,
Prabhu

**Comment by sspr28** [comment]
when i give file *.txt (source encoding text file ) means am getting

:     ISO-8859 text, with very long lines

**Comment by sspr28** [comment]
error : COPY error on lines 1
COPY error: invalid byte sequence for encoding "UTF8": 0xe9 0x72 0x65
CONTEXT:  COPY

**Comment by dimitri** [comment]
Please provide information, not just context. Context is good. Not enough. What is your load file? can you share a part of the input file to reproduce the problem?

**Comment by sspr28** [comment]
Text file had below data
Chérencé
Chérencé

Errors: 
========
COPY error on lines 181
 COPY error: invalid byte sequence for encoding "UTF8": 0xe9 0x72 0x65
 CONTEXT: COPY tgp02, line 1

Special characters not loaded on postgresql database using pgloader.

When i give file in Linux am getting the below o/p

recv > file fdprfo_ro.txt
fdprfo_ro.txt: ISO-8859 text, with very long lines


configuration file:

[pgsql]
host = xxxxxx
port = 6607
base =  xxx
user = xxxxx
pass = xxxxx

log_file            = /log/RC02_FOUR_RO.log
log_min_messages    = DEBUG
client_min_messages = WARNING
#lc_messages         = C

client_encoding = 'UTF-8'
copy_every      = 10000
commit_every    = 5
#copy_delimiter  = %
null        = 'null'
empty_string = "\ "

max_parallel_sections = 4


[fixed]
table           = TGP02
format          = fixed
filename        = /recv/ro.txt
columns         = TGP02WA

fixed_specs     = TGP02WA:0:2

reformat        =       ALF02DTSUPUP:dataformatter:format_date,
                        ALF02FIABILITE:dataformatter:blank_to_null,
                        TGP02WARH:dataformatter:warh_ro

Thanks,
Prabhu

**Comment by sspr28** [comment]
Good day Dimitri,

could you please check the source data and some of the special characters not inserted properly and getting the above errors.

Thanks,
Prabhu

**Comment by dimitri** [comment]
Thanks for the details. Your configuration file shows that you are using pgloader version 2.x, which is not supported anymore. Please upgrade to pgloader 3.x (get the current git version from here, master branch and build locally, that's the simplest way) and read the docs to upgrade your configuration file into a load command.
