### ISSUE TITLE
pgloader - read first line from flat file.

### ISSUE THREAD

**Issue by sspr28** [dimitri/pgloader#389]
We want to read the fist line from the below data and need to insert in a table using pgloader.

 The data is in fixed length flat file.

```
 01000000820160408 
 0201FLINS 
 0203CERGY 
 0204ST-OUEN 
 0205VILLEROY 
```

 We are using the [fixed] section in the conf file for this purpose.
 But unable to restrict the number of lines to be read.
 We tried the following options,
 1.We tried the option -C <count> in command line - it is throwing the error - "global name 'nb_lines' is not defined"

 2.We added the section nb_lines=1 in the conf file, it is still showing "global name 'nb_lines' is not defined".

 Please help us to resolve this issue or to achieve the same thing using pgloader conf file.

**Comment by dimitri** [comment]
What version of pgloader are you using here? There's no `-C` option in the currently maintained version of it...

To do what you want with pgloader version 3, consider doing something like this:

    head -n1 data.file | pgloader --type fixed --field ... --field ... - pgsql://...

Using dash (`-`) as the source means pgloader reads data from standard input. Read the docs for more details, in particular https://github.com/dimitri/pgloader/blob/master/web/src/quickstart.md or http://pgloader.io/howto/quickstart.html.

```
$ docker run -it --rm dimitri/pgloader:ccl.latest pgloader --version
pgloader version "3.3.0.51~devel"
compiled with Clozure Common Lisp Version 1.11-r16635  (LinuxX8664)

$ docker run -it --rm dimitri/pgloader:ccl.latest pgloader --help
pgloader [ option ... ] command-file ...
pgloader [ option ... ] SOURCE TARGET
  --help -h                       boolean  Show usage and exit.
  --version -V                    boolean  Displays pgloader version and exit.
  --quiet -q                      boolean  Be quiet
  --verbose -v                    boolean  Be verbose
  --debug -d                      boolean  Display debug level information.
  --client-min-messages           string   Filter logs seen at the console (default: "warning")
  --log-min-messages              string   Filter logs seen in the logfile (default: "notice")
  --summary -S                    string   Filename where to copy the summary
  --root-dir -D                   string   Output root directory. (default: #P"/tmp/pgloader/")
  --upgrade-config -U             boolean  Output the command(s) corresponding to .conf file for v2.x
  --list-encodings -E             boolean  List pgloader known encodings and exit.
  --logfile -L                    string   Filename where to send the logs.
  --load-lisp-file -l             string   Read user code from files
  --dry-run                       boolean  Only check database connections, don't load anything.
  --on-error-stop                 boolean  Refrain from handling errors properly.
  --with                          string   Load options
  --set                           string   PostgreSQL options
  --field                         string   Source file fields specification
  --cast                          string   Specific cast rules
  --type                          string   Force input source type
  --encoding                      string   Source expected encoding
  --before                        string   SQL script to run before loading the data
  --after                         string   SQL script to run after loading the data
  --self-upgrade                  string   Path to pgloader newer sources
  --regress                       boolean  Drive regression testing
```

**Comment by sspr28** [comment]
Hi Dimitri,

We are using pgloader 2.x version.

We would like to skip the 1st line of date i,e data starts from 01 and rest of the lines needs to be inserted in table i,e which data starts from 02.

We have used skil_head_files=1 in pgloader configuration file but we are getting the errors.

"global name 'nb_lines' is not defined"

Could you please any solution or documents to fix the issues.

**Comment by sspr28** [comment]
-bash-3.2$ pgloader --version
PGLoader version 2.3.2
0
--bash-3.2$ uname
Linux

**Comment by sspr28** [comment]
pgloader -vc RC08_PARAM.conf -R /admin/reformat -d
pgloader     INFO     Logger initialized
pgloader     INFO     Reformat path is ['/admin/reformat']
pgloader     DEBUG    Preferred psycopg version is None
pgloader     DEBUG    Trying psycopg2 then psycopg
pgloader     INFO     Will consider following sections:
pgloader     INFO       fixed
fixed        DEBUG    [fixed] parse configuration
fixed        DEBUG    _dbconnect copy_sep None
fixed        DEBUG    Reading configuration from section [fixed]
fixed        DEBUG    reject log in /log/RC08_PARAM.rej.log
fixed        DEBUG    rejected data in /log/RC08_PARAM.rej
fixed        DEBUG    client_encoding: 'latin1'
fixed        DEBUG    input_encoding: 'None'
fixed        DEBUG    datestyle: 'None'
fixed        DEBUG    fixed.table: ALF08_PARAMETRES
fixed        DEBUG    fixed.filename: /cour/recv/fdprge.txt
fixed        DEBUG    index None
fixed        DEBUG    columns [('ALF08C', 1), ('ALF08V', 2), ('ALF08L', 3), ('ALF08W', 4)]
fixed        DEBUG    blob_columns None
fixed        DEBUG    udcs: None
fixed        DEBUG    udcs: None
fixed        DEBUG    only_cols None
fixed        DEBUG    columnlist ['ALF08C', 'ALF08V', 'ALF08L', 'ALF08W']
fixed        DEBUG    self.newline_escapes = '[]'
fixed        DEBUG    fixed.section_threads = 1
fixed        DEBUG    fixed.split_file_reading = False
fixed        DEBUG    File '/recv/fdprge.txt' will be read in fixed format
fixed        DEBUG    reader __init__ /recv/fdprge.txt ALF08_PARAMETRES [('ALF08C', 1), ('ALF08V', 2), ('ALF08L', 3), ('ALF08W', 4)]
fixed        DEBUG    reader.readconfig()
fixed        DEBUG    reader._getopt null defaults to 'null'
fixed        DEBUG    reader._getopt empty_string defaults to '\ '
fixed        DEBUG    reader._getopt field_sep defaults to '|'
fixed        DEBUG    reader._getopt skip_head_lines from fixed is '0'
fixed        DEBUG    reader.readconfig null: 'null'
fixed        DEBUG    reader.readconfig empty_string: '\ '
fixed        DEBUG    reader.db <pgloader.db.db instance at 0x19d53f8> copy_sep |
fixed        DEBUG    reader.readconfig field_sep: '|'
fixed        DEBUG    reader.readconfig skip_head_lines: 0
fixed        DEBUG    reader._getopt fixed_specs from fixed is 'ALF08C:0:2,
ALF08V:2:7,
ALF08L:0:2,
ALF08W:0:2'
fixed        DEBUG    reader.readconfig: positions {'ALF08V': (2, 7), 'ALF08C': (0, 2), 'ALF08W': (0, 2), 'ALF08L': (0, 2)}
fixed        DEBUG    reformat [('ALF08C', 'dataformatter', 'code_nbvrest'), ('ALF08L', 'dataformatter', 'param_nb_label'), ('ALF08W', 'dataformatter', 'warh_fr')]
fixed        DEBUG    Found dataformatter at /admin/reformat/dataformatter.py
fixed        DEBUG    Found dataformatter at admin/reformat/dataformatter.py
fixed        DEBUG    Found dataformatter at /admin/reformat/dataformatter.py
fixed        DEBUG    reformat [('ALF08C', <function code_nbvrest at 0x19e0410>), ('ALF08L', <function param_nb_label at 0x19e0500>), ('ALF08W', <function warh_fr at 0x19dccf8>)]
fixed        DEBUG    fixed init done
pgloader     DEBUG    Starting a thread for fixed
fixed        DEBUG    fixed.sem.acquire()
fixed        DEBUG    fixed acquired starting semaphore
fixed        DEBUG    fixed postinit
fixed        DEBUG    Debug: connecting to dns host=s0586ads.mc2.renault.fr port=6607 user=xxx dbname=xxx password=xxxx
fixed        DEBUG    Setting client encoding to latin1
fixed        INFO     fixed processing
pgloader     DEBUG    thread fixed is running
pgloader     INFO     All threads are started, wait for them to terminate
fixed        DEBUG    Opened '/vcour/recv/fdprge.txt' in <open file '/vcour/recv/fdprge.txt', mode 'rb' at 0x1951b70> (fileno 5), ftell 0
fixed        DEBUG    offsets [1]
fixed        DEBUG    reformat
fixed        DEBUG    columns ['01', '0000008', '01', '01']
fixed        DEBUG    data    ['NBVREST', '0000008', 'Nb de jours de vente restant ds le mois', '01']
fixed        DEBUG    < 01000000820160408
fixed        DEBUG      ['ALF08C', 'ALF08V', 'ALF08L', 'ALF08W']
fixed        DEBUG    > ['NBVREST', '0000008', 'Nb de jours de vente restant ds le mois', '01']
fixed        DEBUG    offsets [2]
fixed        DEBUG    reformat
fixed        DEBUG    columns ['02', '01FLINS', '02', '02']
fixed        DEBUG    data    ['11111111111', '01FLINS', '11111111111', '01']
fixed        DEBUG    < 0201FLINS
fixed        DEBUG      ['ALF08C', 'ALF08V', 'ALF08L', 'ALF08W']
fixed        DEBUG    > ['11111111111', '01FLINS', '11111111111', '01']
fixed        DEBUG    offsets [3]
fixed        DEBUG    reformat
fixed        DEBUG    columns ['02', '03CERGY', '02', '02']
fixed        DEBUG    data    ['11111111111', '03CERGY', '11111111111', '01']
fixed        DEBUG    < 0203CERGY
fixed        DEBUG      ['ALF08C', 'ALF08V', 'ALF08L', 'ALF08W']
fixed        DEBUG    > ['11111111111', '03CERGY', '11111111111', '01']
fixed        DEBUG    offsets [4]
fixed        DEBUG    reformat
fixed        DEBUG    columns ['02', '04ST-OU', '02', '02']
fixed        DEBUG    data    ['11111111111', '04ST-OU', '11111111111', '01']
fixed        DEBUG    < 0204ST-OUEN
fixed        DEBUG      ['ALF08C', 'ALF08V', 'ALF08L', 'ALF08W']
fixed        DEBUG    > ['11111111111', '04ST-OU', '11111111111', '01']
fixed        DEBUG    offsets [5]
fixed        DEBUG    reformat
fixed        DEBUG    columns ['02', '05VILLE', '02', '02']
fixed        DEBUG    data    ['11111111111', '05VILLE', '11111111111', '01']
fixed        DEBUG    < 0205VILLEROY
fixed        DEBUG      ['ALF08C', 'ALF08V', 'ALF08L', 'ALF08W']
fixed        DEBUG    > ['11111111111', '05VILLE', '11111111111', '01']
fixed        DEBUG    FileReader stoping, offset 405 >= None
fixed        DEBUG    COPY will use table definition: 'ALF08_PARAMETRES (ALF08C, ALF08V, ALF08L, ALF08W) '
fixed        DEBUG    COPY data buffer saved in /tmp/ALF08_PARAMETRES.w03DmS.pgloader
fixed        DEBUG    using copy_expert
fixed        WARNING  COPY error, trying to find on which line
fixed        DEBUG    Trying to find errors, dividing 5 lines in 2 and 3
fixed        DEBUG    using copy_expert
fixed        DEBUG    Trying to find errors, dividing 2 lines in 1 and 1
fixed        DEBUG    using copy_expert
fixed        DEBUG    COPY ERROR handling progress: 1 rows copied
fixed        DEBUG    using copy_expert
fixed        DEBUG    Notice: found one more line in error
fixed        DEBUG    11111111111|01FLINS|11111111111|01

fixed        DEBUG    using copy_expert
fixed        DEBUG    Trying to find errors, dividing 3 lines in 1 and 2
fixed        DEBUG    using copy_expert
fixed        DEBUG    Notice: found one more line in error
fixed        DEBUG    11111111111|03CERGY|11111111111|01

fixed        DEBUG    using copy_expert
fixed        DEBUG    Trying to find errors, dividing 2 lines in 1 and 1
fixed        DEBUG    using copy_expert
fixed        DEBUG    Notice: found one more line in error
fixed        DEBUG    11111111111|04ST-OU|11111111111|01

fixed        DEBUG    using copy_expert
fixed        DEBUG    Notice: found one more line in error
fixed        DEBUG    11111111111|05VILLE|11111111111|01

fixed        WARNING  COPY error recovery done (4/1) in 0.022s
fixed        ERROR    12 errors found into [fixed] data
fixed        ERROR    please read /log/RC08_PARAM.rej.log for errors log
fixed        ERROR    and /log/RC08_PARAM.rej for data still to process
fixed        INFO      1 rows copied in 1 commits took 0.038 seconds
fixed        ERROR    4 database errors occured
fixed        INFO     Please VACUUM your database to recover space
fixed        DEBUG    loading done
fixed        INFO     closing current database connection
fixed        INFO     releasing fixed semaphore
fixed        INFO     Announce it's over
pgloader     DEBUG    thread fixed processing is over

**Comment by dimitri** [comment]
The version 2.x of pgloader is not maintained anymore. Please switch to using the current version, 3.x.

**Comment by sspr28** [comment]
Hi Dimitri,

Can the issues fixed after upgrade to 3.x version.Can we have the list of bugs fixed on 3.x version and what are all the bugs in 2.3.2 version.. It would be helpful if you provide any documents links for bug list so that we can suggest to business to upgrade.

our issue is :  I want to skip the line 1 datas and rest of lines needs to be inserted in table.How it can be achieved using skip_head_lines =1 , any other parameters needs to be mentioned in conf file.

Please help on this.

Thanks,
Prabhu.

**Comment by dimitri** [comment]
Please read the documentation? You will find it at http://pgloader.io/howto/pgloader.1.html full with detailed examples about the new command format, that includes a `WITH` clause supporting a `skip header = 1` option.

Also see the test files such as https://github.com/dimitri/pgloader/blob/master/test/csv.load where you will see the 2.x era configuration and then the 3.x era command that matches it.

Finally, pgloader offers a `--upgrade-config` option to migrate from your current configuration file to the new command format.

**Comment by sspr28** [comment]
But ours is fixed file.

Skip header = 1 for csv file (am i correct).

Is any options skip_head_lines=1 for fixed file format ..We tried skip_head_lines=1 in pg configuration but it not worked to us.

Thanks for your suggestions. We will inform to upgrade to latest pgloader version.
