### ISSUE TITLE
Matching more than one table while using `INCLUDING ONLY TABLE NAMES..` and table name

### ISSUE THREAD

**Issue by manuca** [dimitri/pgloader#391]
@dimitri I have an issue with the following import script that I copy almost intact (without credentials). 

I was expecting this script only processes the table named `insurance` but it is actually picking more than one that contain `insurance` as part of the name, as if I had applied a regexp instead of a specific string with the table name.

```
LOAD database
	from mysql://[url]
	into postgresql://[url]
	with include no drop,
	     disable triggers,
	     create no indexes,
	     no foreign keys,
	     downcase identifiers,
	     quote identifiers
	CAST type date to date drop not null drop default using zero-dates-to-null,
	     type timestamp to timestamp drop not null drop default using zero-dates-to-null,
	     type enum to varchar drop not null drop default using empty-string-to-null
	INCLUDING ONLY TABLE NAMES MATCHING 'insurance';
```

**Comment by dimitri** [comment]
Can you please run again in `--debug` mode so that you can then paste the MySQL catalog query that is sent to obtain the database information here? Meanwhile you can use `~/^insurance$/` so that only that table is matched...

**Comment by manuca** [comment]
Hi @dimitri I just tried using `~/^insurance$/` and I'm having the exact same issue pgloader picks also `insurance_insurancetype` for example.

**Comment by dimitri** [comment]
Can you share the MySQL query sent as logged in `--debug` mode, please?

**Comment by dimitri** [comment]
Closing as it still needs more information. Consider opening again with more details.
