### ISSUE TITLE
max-parallel-create-index triggers an unhandled error

### ISSUE THREAD

**Issue by leonardsson** [dimitri/pgloader#395]
When using the (newly introduced) max-parallel-create-index, it causes an unhandled exception:
```
>An unhandled error condition has been signalled:
>  Invalid initialization argument:
>     :MAX-PARALLEL-CREATE-INDEX
>   in call for class #<STANDARD-CLASS PGLOADER.CSV:COPY-CSV>.
>See also:
>  The ANSI Standard, Section 7.1.2
  
>An unhandled error condition has been signalled:
>   Invalid initialization argument:
>     :MAX-PARALLEL-CREATE-INDEX
>   in call for class #<STANDARD-CLASS PGLOADER.CSV:COPY-CSV>.
>See also:
>  The ANSI Standard, Section 7.1.2
```

The load file:
```
>LOAD CSV
>  FROM '/path/to/csv.txt' WITH ENCODING 'ISO-8859-1'
>  HAVING FIELDS
>  (
>   [fields]
>  )
>  INTO postgresql://user:pass@host:5432/db?table
>  (
>   [fields]
>  )
>  WITH
>    fields optionally enclosed by '"',
>    fields terminated by ';',
>    truncate,
>    batch rows = 1000,
>    drop indexes,
>    max parallel create index = 4
>  SET
>    client_encoding to 'UTF-8',
>    work_mem to '32MB',
>    maintenance_work_mem to '24MB'
>  ;
```

**Comment by leonardsson** [comment]
This diff seems to fix it for me. Do you want me to submit a pull request for it?

    diff --git a/src/parsers/command-csv.lisp b/src/parsers/command-csv.lisp
    index 2dec5e2..95872a9 100644
    --- a/src/parsers/command-csv.lisp
    +++ b/src/parsers/command-csv.lisp
    @@ -410,6 +410,7 @@
                                              gucs before after options
                                            &aux
                                              (worker-count (getf options :worker-count))
    +                                         (max-parallel-create-index (getf options :max-parallel-create-index))
                                              (concurrency  (getf options :concurrency)))
       `(lambda ()
          (let* (,@(pgsql-connection-bindings pg-db-conn gucs)
    @@ -437,12 +438,15 @@
                                                         :concurrency
                                                         :truncate
                                                         :drop-indexes
    +                                                    :max-parallel-create-index
                                                         :disable-triggers)))))
                (pgloader.sources:copy-database source
                                                ,@ (when worker-count
                                                     (list :worker-count worker-count))
                                                ,@ (when concurrency
                                                     (list :concurrency concurrency))
    +                                           ,@ (when max-parallel-create-index
    +                                                (list :max-parallel-create-index max-parallel-create-index))
                                                :truncate truncate
                                                :drop-indexes drop-indexes
                                                :disable-triggers disable-triggers))

**Comment by dimitri** [comment]
Thanks for the report with a patch! Please see about creating a pull request, with those extra bits if you can add them:

  - move the `max-parallel-create-index` from the `&aux` section to the `let` construct where `truncate` and others are defined,
  - please edit the `copy` and `fixed` support for max parallel index creation the same way.

Thanks!
