### ISSUE TITLE
Having issue using pgloader loader on windows 7 64 bit

### ISSUE THREAD

**Issue by sspr28** [dimitri/pgloader#396]
I am using the exe file for windows from http://pgloader.io/files/pgloader.95961a4.exe.

while running exe file am getting one of the dll object is not shared.

```
debugger invoked on a SIMPLE-ERROR in thread
#<THREAD "main thread" RUNNING {26C88479}>:
  Error opening shared object "libeay32.dll":
 %1 is not a valid Win32 application.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [CONTINUE       ] Skip this shared object and continue.
  1: [RETRY          ] Retry loading this shared object.
  2: [CHANGE-PATHNAME] Specify a different pathname to load the shared object fr
om.

(SB-SYS:DLOPEN-OR-LOSE #S(SB-ALIEN::SHARED-OBJECT :PATHNAME #P"libeay32.dll" :NA
MESTRING "libeay32.dll" :HANDLE NIL :DONT-SAVE NIL))
0]
```

I have placed the exe file under pgadmin\bin folder and the DLL file is also on the same path pgadmin\bin.

Could you look when you have free time and how to fix in windows.

Thanks,
Prabhu

**Comment by dimitri** [comment]
Can you add the dll file to the same directory as where your pgloader binary is installed?

**Comment by sspr28** [comment]
Yes i have tried..

DLL file is located on /pgAdmin/bin directory..I have copied to lib and binary installed location but getting the same error.

**Comment by dimitri** [comment]
You keep mentioning pgAdmin; here we are talking about pgloader.

**Comment by sspr28** [comment]
sorry for that..

while running the pgloader.95961a4 exe file am getting the error...

**Comment by sspr28** [comment]
Am i running the correct exe file for windows.?

**Comment by sspr28** [comment]
I just following the solution#159 ..now i have stuck up with sqlite3.dll error but the same dll is present on pgloader binary location..i tried to continue [choosed oprion 0] but screen got disappeared..I am not sure whether pgloader.exe issue fixed or not

**Comment by dimitri** [comment]
Can you try building pgloader on windows?

**Comment by sspr28** [comment]
I am new to postgresql and am completely in oracle..I have downloaded the exe file http://pgloader.io/files/pgloader.95961a4.exe (as you mentioned # 159) and tried to install the exe and got the above dll issues...can you give some document link or any steps to build.

**Comment by sspr28** [comment]
I have couple of issues (character encoding issues from is-8859-1 to utf8 and skip_head_lines parameters not skipped the line 1 data's), have raised the issues in forum..As you suggested pgloader 2.x is not supported and needs to be migrated 3.x version..So i am trying to configure pgloader on windows for test...
