### ISSUE TITLE
Import from multiple CSV files

### ISSUE THREAD

**Issue by mmuruev** [dimitri/pgloader#397]
Can find if it is already present but I need have import from multiple CSV files by filename template.

**Comment by dimitri** [comment]
Can you use the `FILENAMES MATCHING` feature as described in the documentation?

```
[ ALL FILENAMES | [ FIRST ] FILENAME ]  
MATCHING regexp  
[ IN DIRECTORY '...' ] 
```

**Comment by eggie5** [comment]
@dimitri The documentation doesn't suggest the  `ALL FILENAMES MATCHING` works for `FIXED` files. Also, I tried it and it complains about a syntax error. Should this work for `FIXED` too?

**Comment by dimitri** [comment]
A very quick glance at the parser code makes me believe it should work. Can you paste more details, such as your command and the error message?

**Comment by eggie5** [comment]
The order of the `in directory` was important and wasn't clear to me from the docs. I got this working:

```
LOAD FIXED  
  FROM all filenames matching ~<saltsnck_[drug|groc]>
     in directory '~/Development/DSE/DSE220/IRI_Data/Year1/External/saltsnck/'
```

Thanks.
