### ISSUE TITLE
Heap exhausted migrating using docker

### ISSUE THREAD

**Issue by AndreaCrotti** [dimitri/pgloader#399]
I'm tryng to do a migration from MySQL to Postgres, and I'm using docker since I can't get the standard command to work (because of https://github.com/dimitri/pgloader/issues/149)

I run this command

```
sudo docker run --rm --name pgloader dimitri/pgloader:latest pgloader mysql://mysqlurl postgres://postgresurl
```

And after maybe 5 minutes I see the docker stats going up (but still only using around 1 out of 8GB of memory in total), and it crashes like this:

    Heap exhausted during garbage collection: 16 bytes available, 32 requested.
     Gen StaPg UbSta LaSta LUbSt Boxed Unboxed LB   LUB  !move  Alloc  Waste   Trig    WP  GCs Mem-age
    debug2: channel 1: window 999305 sent adjust 49271
       0:     0     0     0     0     0     0     0     0     0        0     0 42949672    0   0  0.0000
       1:     0     0     0     0     0     0     0     0     0        0     0 42949672    0   0  0.0000
       2: 116645 117020     0     0  3762 35084    79  3171     0 1349806416 29595312 714313752    0   1  1.2292
       3: 46265 131071     0     0  5694 47601   266  4925   488 1867615936 48853312 42949672 3870   0  1.0428
       4: 14118 58361     0     0  2857 21948   193  1023   156 846692848 5963280  2000000 2841   0  0.4149
       5:     0     0     0     0     0     0     0     0     0        0     0  2000000    0   0  0.0000
       6:     0     0     0     0  3378  1076     0     0     0 145948672     0  2000000 3174   0  0.0000
       Total bytes allocated    = 4210063872
       Dynamic-space-size bytes = 4294967296
    GC control variables:
       *GC-INHIBIT* = true
       *GC-PENDING* = true
       *STOP-FOR-GC-PENDING* = false
    fatal error encountered in SBCL pid 1(tid 140737295152896):
    

I've done the same migration before from another machine and it worked fine (and the same db), is it a docker issue or some SBCL settings maybe?
Thanks

**Comment by dimitri** [comment]
I am not sure what is causing the error, meanwhile can you try with this other docker image using CCL rather than SBCL? (CCL is known to be much better at Garbage Collection):

    docker pull dimitri/pgloader:ccl.latest

**Comment by AndreaCrotti** [comment]
Ok I'll try, in the meanwhile I had the same issue without docker with the latest version built from source.

And by the way unrelated question, is it possible to run docker with different versions than :latest?

I didn't manage to do that from my first attempts..

**Comment by AndreaCrotti** [comment]
Yes the CCL version seems to be fine the memory usage is not growing so crazily.
It's very strange though because I did the same operation on the same DB a couple of weeks ago and everything worked fine, not sure what changed since then..

**Comment by dimitri** [comment]
Closing as the CCL version available as a docker image fixed the issue.

**Comment by lucian303** [comment]
I'm also getting this, although it's actually using about 4 out of 60 GB of memory so whatever heap is exhausted is clearly virtual. 

pgloader version "3.3.1"
compiled with SBCL 1.2.4.debian:
```
2016-09-05T20:02:39.065000Z LOG Main logs in '/tmp/pgloader/pgloader.log'
2016-09-05T20:02:39.068000Z LOG Data errors in '/tmp/pgloader/'
2016-09-05T20:02:39.068000Z LOG Parsing commands from file #P"/home/ubuntu/config.conf"
Heap exhausted during garbage collection: 1120 bytes available, 1952 requested.
 Gen StaPg UbSta LaSta LUbSt Boxed Unboxed LB   LUB  !move  Alloc  Waste   Trig    WP  GCs Mem-age
   0:     0     0     0     0     0     0     0     0     0        0     0 42949672    0   0  0.0000
   1:     0     0     0     0     0     0     0     0     0        0     0 42949672    0   0  0.0000
   2:  8778 113349     0     0   310 36719     0 15410     0 1450563184 267757968  2000000    0   0  2.0510
   3:     0     0     0     0     0     0     0     0     0        0     0  2000000    0   0  0.0000
   4:     0     0     0     0     0     0     0     0     0        0     0  2000000    0   0  0.0000
   5:     0     0     0     0     0     0     0     0     0        0     0  2000000    0   0  0.0000
   6:     0     0     0     0  3537  1150     0     0     0 153583616     0  2000000 3332   0  0.0000
   Total bytes allocated    = 3745398192
   Dynamic-space-size bytes = 4294967296
GC control variables:
   *GC-INHIBIT* = true
   *GC-PENDING* = true
   *STOP-FOR-GC-PENDING* = false
fatal error encountered in SBCL pid 31143(tid 140737304065792):
Heap exhausted, game over.

Welcome to LDB, a low-level debugger for the Lisp runtime environment.
ldb> #
```

Is there a CCL version available through apt or in some way runnable outside its container? Inside the container, it's pretty useless.

**Comment by dimitri** [comment]
You can rebuild pgloader to use any image size you want to. Let's say 48GB:

    make DYNSIZE=49152 pgloader
