### ISSUE TITLE
SB-INT:SIMPLE-FILE-ERROR in thread

### ISSUE THREAD

**Issue by kerloom** [dimitri/pgloader#403]
I am getting the following error when trying to export from sqlite to postgresql with `pgloader db.sqlite3 postgresql:///myproject
`
```
debugger invoked on a SB-INT:SIMPLE-FILE-ERROR in thread
#<THREAD "lparallel" RUNNING {1009081ED3}>:
  error opening #P"/tmp/pgloader/pgloader.log": Permission denied
An unhandled error condition has been signalled:
   Can't create directory /tmp/pgloader/NIL/
```
Before this I was able to migrate once successfully, but got errors on my website when inserting new data. I deleted the database and created a new one, and then I got the mentioned error.

**Comment by dimitri** [comment]
Can you try with `--debug` so that we have a stack trace to debug from?

**Comment by dimitri** [comment]
Closing, please open again if needed, with more details.

**Comment by Silence2012** [comment]
The same error message when  I want to migrate a sqlitedb into a postgres db.
the version message is :
    postgres (PostgreSQL) 9.5.3
    sqlite3 --version
    3.8.2 2013-12-06 14:53:30 27392118af4c38c5203a04b8013e1afdb1cebd0d
    pgloader -V
    pgloader version "3.3.2"
    compiled with SBCL 1.2.4.debian
The output error message is :
    2017-03-09T09:42:44.025000Z LOG Main logs in '/tmp/pgloader/pgloader.log'
   2017-03-09T09:42:44.032000Z LOG Data errors in '/tmp/pgloader/'
   2017-03-09T09:42:44.233000Z FATAL An unhandled error condition has been signalled:
   Could not prepare an sqlite statement.
   Code ERROR: near "group": syntax error.

**Comment by Silence2012** [comment]
@dimitri  thx

**Comment by dimitri** [comment]
Is it possible for you to send me the SQLite file, maybe over email on the one included in my GitHub profile? Thanks.
