### ISSUE TITLE
The “client_encoding” option doesn’t seem to be ignored

### ISSUE THREAD

**Issue by KrzysiekJ** [dimitri/pgloader#408]
Running `make check` (after doing `make prepare` inside the `test/` folder) yields the following result:

```
2016-05-18T12:34:46.055000+02:00 WARNING pgloader always talk to PostgreSQL in utf-8, client_encoding has been forced to 'utf8'.
[…]
An unhandled error condition has been signalled:
   Database error 22P05: character with byte sequence 0xc4 0x99 in encoding "UTF8" has no equivalent in encoding "LATIN1"
QUERY: drop table if exists expected.allcols;

An unhandled error condition has been signalled:
   Database error 22P05: character with byte sequence 0xc4 0x99 in encoding "UTF8" has no equivalent in encoding "LATIN1"
QUERY: drop table if exists expected.allcols;
```

If I change the `SET client_encoding to 'latin1'` fragment in `allcols.load` into `SET client_encoding to 'utf8'`, then I get no encoding errors related to this particular file.

The description of commit a3fd22acd38430 states that a WARNING was added “whenever the client_encoding is set to a known bad value. It's a WARNING because we then simply force 'utf-8' anyway.” It seems that `utf-8` isn’t actually forced. Additionally, when I revert encoding value in a load file to `latin1`, the problem doesn’t come back — `make check` fails on a nearest untouched file with `latin1` encoding set. Apparently the testing environment isn’t purged properly between test runs (that may explain why this problem got unnoticed).

**Comment by dimitri** [comment]
My local testing in debug mode shows that the `client_encoding` is indeed forced to `UTF8`... I am not sure how to understand your report here?

```
$ ./build/bin/pgloader --debug ./test/allcols.load | grep 'encoding\|external'
sb-impl::*default-external-format* :US-ASCII
2016-05-18T21:37:40.249000+02:00 WARNING pgloader always talk to PostgreSQL in utf-8, client_encoding has been forced to 'utf8'.
2016-05-18T21:37:40.250000+02:00 DEBUG SET client_encoding TO 'utf8'
2016-05-18T21:37:40.250000+02:00 DEBUG SET client_encoding TO 'utf8'
2016-05-18T21:37:40.251000+02:00 DEBUG SET client_encoding TO 'utf8'
2016-05-18T21:37:40.467000+02:00 DEBUG SET client_encoding TO 'utf8'
```

The `*default-external-format` is inherited from the current `LANG` settings in the shell where the Common Lisp kernel is started from, and my local settings are quite raw:

```
$ locale
LANG=
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

Can you provide enough details for me to reproduce easily? What I'm thinking is that your PostgreSQL cluster and database might be in `latin1` and thus are not in capacity to translate some characters from `utf-8`. I don't see non-latin-1 compatible chars in the `allcols` test file tho.

**Comment by KrzysiekJ** [comment]
The `--regress` option has to be added to yield errors. It seems that pgloader connects to the database twice when doing regression tests: firstly to “change target table-name schema” (when encoding is not overridden) and secondly to do actual loading (when encoding is overridden properly). Based on that, I’ve submitted a quick fix in #410.

**Comment by dimitri** [comment]
First connection is used to prepare the _expected_ data set, then the `load-data` function will manage as many parallel connections as needed depending on the settings of the load file, and finally we have another explicit connection to compare the _expected_ data set with whatever got into the target table.

It should be possible to load the _expected_ data and compare with the _just loaded_ data in the same connection once the `load-data` call has been done, thus reducing how many connections we use in the `--regress` suite. Do you want to tackle this and move some code around in `process-regression-test`?

**Comment by KrzysiekJ** [comment]
Ok, I’ll attempt to do this in #410.
