### ISSUE TITLE
invalid byte sequence for encoding "UTF8"

### ISSUE THREAD

**Issue by jasonheffner** [dimitri/pgloader#411]
I'm using the load CSV option to import data from Canvas which is UTF8.

https://portal.inshosteddata.com/docs

I'm running into random UTF8 errors as such, and typically it is only 3 or 4 files, one line each from approx 55 files.

```
invalid byte sequence for encoding "UTF8": 0x00
CONTEXT: COPY enrollment_rollup_dim, line 3458
```

I searched through most the forums and closed tickets and thought perhaps at first I had a malformed file or bad character in these files. After searching extensively I don't have any null characters in the file and then noticed over several nights that the files and line numbers are different on each load, though consistent on that file for the day.

I was wondering if there are any memory issues that might be causing the problem.  

```
pgloader version "3.3.826d975"
compiled with SBCL 1.2.8-1.el7
```

**Comment by dimitri** [comment]
Can you run the following command on a file where pgloader found a null character?

    grep -a -E '\x00' input_file_with_possibly_null.csv

If the file is clean indeed, can you try a CCL build (either from the `ccl.latest` docker image at https://hub.docker.com/r/dimitri/pgloader/ of from a local build using Clozure CL)?

Then, can you send me the file for local testing?

**Comment by dimitri** [comment]
Closing for lack of details, please consider opening again with them if needed.
