### ISSUE TITLE
NATIVE-NAMESTRING: "dat"

### ISSUE THREAD

**Issue by angercho** [dimitri/pgloader#413]
HI ,
I'm trying to load some data from csv but got following error :
```
2016-05-24T02:35:31.069000Z LOG Main logs in '/opt/pgload/logche'
2016-05-24T02:35:31.080000Z LOG Data errors in '/tmp/pgloader/'
2016-05-24T02:35:31.081000Z LOG Parsing commands from file #P"/opt/pgload/loadi.load"
An unhandled error condition has been signalled:
   type component without a name component in NATIVE-NAMESTRING: "dat"

LOAD CSV
     FROM /opt/pgload/ochudo.dat (a, b, c, d, e, f, g, h, j)
     INTO postgresql://postgres:xxxxxxx@localhost:5432/taal (a, b, c, d, e, f, g, h, j)

     WITH truncate,
          fields terminated by '|'

      SET work_mem to '12MB',
          standard_conforming_strings to 'on'
BEFORE LOAD DO
$$drop table if exists test; $$,
      $$create table test (
a serial,
b integer,
c integer,
d text,
e text,
f text,
g text,
h character varying(255),
j character varying(50)
        ); $$;
```

example of data :
```
1|50|\ |xxxxx xxxx|<p>xxxx xxxx</p>|De xx lijst van xxx woorden^M\xxxxx xxxx en xx xx nog zo xxx zijn, in xxx xxx xx ze xxxxxx it de toon.Â  (...)^M\nbsp;&nbsp;&nbsp;&nbsp;</i> dienen |\ |186-187|
```

can someone advice why I've got such error ? 
and what dose it means?

**Comment by dimitri** [comment]
Can you try again with the `--debug` option so that you can then paste the stack trace here, please?

**Comment by angercho** [comment]
HI Dimitri,
Sorry for the delay - here is the result :
-bash-4.1$ pgloader -L /opt/pgload/logche loadi.load
2016-05-25T18:37:31.077000Z LOG Main logs in '/opt/pgload/logche'
2016-05-25T18:37:31.083000Z LOG Data errors in '/tmp/pgloader/'
2016-05-25T18:37:31.083000Z LOG Parsing commands from file #P"/opt/pgload/loadi.load"
An unhandled error condition has been signalled:
   type component without a name component in NATIVE-NAMESTRING: "dat"

-bash-4.1$ pgloader --debug -L /opt/pgload/logche loadi.load
sb-impl::*default-external-format* :UTF-8
tmpdir: #P"/tmp/pgloader/"
2016-05-25T18:38:03.023000Z NOTICE Starting pgloader, log system is ready.
2016-05-25T18:38:03.076000Z INFO Starting monitor
2016-05-25T18:38:03.082000Z LOG Main logs in '/opt/pgload/logche'
2016-05-25T18:38:03.082000Z LOG Data errors in '/tmp/pgloader/'
2016-05-25T18:38:03.082000Z LOG Parsing commands from file #P"/opt/pgload/loadi.load"
2016-05-25T18:38:03.082000Z DEBUG CONNECT #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://postgres@localhost:5432/taal {10071B1803}>
2016-05-25T18:38:03.082000Z DEBUG SET work_mem TO '12MB'
An unhandled error condition has been signalled:
   type component without a name component in NATIVE-NAMESTRING: "dat"

Date/time: 2016-05-25-21:38An unhandled error condition has been signalled:
                              type component without a name component in NATIVE-NAMESTRING: "dat"


Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1006DB3093}>
0: ((LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX))
1: (SB-IMPL::CALL-WITH-SANE-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX) {100846D65B}>)
2: (SB-IMPL::%WITH-STANDARD-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX) {100846D62B}>)
3: (PRINT-BACKTRACE :STREAM #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDOUT* {10002CBC13}> :START 0 :FROM :DEBUGGER-FRAME :COUNT 4611686018427387903 :PRINT-THREAD T :PRINT-FRAME-SOURCE NIL :METHOD-FRAME-STYLE NIL)
4: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE-TO-STREAM #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDOUT* {10002CBC13}>)
5: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE #<SIMPLE-ERROR "type component without a name component in NATIVE-NAMESTRING: ~S" {100846A503}> :OUTPUT #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDOUT* {10002CBC13}> :IF-EXISTS :APPEND :VERBOSE T)
6: (SIGNAL #<SIMPLE-ERROR "type component without a name component in NATIVE-NAMESTRING: ~S" {100846A503}>)
7: (ERROR "type component without a name component in NATIVE-NAMESTRING: ~S" "dat")
8: (SB-IMPL::UNPARSE-NATIVE-UNIX-NAMESTRING #<PATHNAME (with no namestring) :HOST #<SB-IMPL::UNIX-HOST {100001AF93}> :DEVICE NIL :DIRECTORY (:ABSOLUTE "tmp" "pgloader" "taaladvies") :NAME NIL :TYPE "dat" :VERSION :NEWEST> T)
9: (SB-IMPL::QUERY-FILE-SYSTEM #<PATHNAME (with no namestring) :HOST #<SB-IMPL::UNIX-HOST {100001AF93}> :DEVICE NIL :DIRECTORY (:ABSOLUTE "tmp" "pgloader" "taaladvies") :NAME NIL :TYPE "dat" :VERSION :NEWEST> :TRUENAME NIL)
10: (PROBE-FILE #<PATHNAME (with no namestring) :HOST #<SB-IMPL::UNIX-HOST {100001AF93}> :DEVICE NIL :DIRECTORY (:ABSOLUTE "tmp" "pgloader" "taaladvies") :NAME NIL :TYPE "dat" :VERSION :NEWEST>)
11: (PGLOADER.UTILS:PGSTATE-ADD-TABLE #S(PGLOADER.UTILS::PGSTATE :TABLES #<HASH-TABLE :TEST EQUAL :COUNT 1 {10074658D3}> :TABNAMES (NIL) :READ 0 :ROWS 0 :ERRS 0 :SECS 0.0) "taaladvies" NIL)
12: ((:METHOD PGLOADER.SOURCES:COPY-FROM (PGLOADER.CSV:COPY-CSV)) #<PGLOADER.CSV:COPY-CSV {1008366A03}> :TRUNCATE T) [fast-method]
13: ((LAMBDA ()))
14: (PGLOADER:RUN-COMMANDS #P"/opt/pgload/loadi.load" :START-LOGGER NIL :SUMMARY NIL :LOG-FILENAME NIL :LOG-MIN-MESSAGES NIL :CLIENT-MIN-MESSAGES NIL)
15: (PGLOADER::PROCESS-COMMAND-FILE "loadi.load")
16: ((FLET #:CLEANUP-FUN-281 :IN PGLOADER::MAIN)) [cleanup]
17: (PGLOADER::MAIN ("pgloader" "--debug" "-L" "/opt/pgload/logche" "loadi.load"))
18: ((LAMBDA NIL :IN "/home/vagrant/rpmbuild/BUILD/pgloader/dumper-2SKVI5f7.lisp"))
19: ((FLET #:WITHOUT-INTERRUPTS-BODY-54 :IN SAVE-LISP-AND-DIE))
20: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))


debugger invoked on a SIMPLE-ERROR in thread
#<THREAD "main thread" RUNNING {1006DB3093}>:
  type component without a name component in NATIVE-NAMESTRING: "dat"

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit application


debugger invoked on a TYPE-ERROR in thread
#<THREAD "main thread" RUNNING {1006DB3093}>:
  The value INVOKE-DEBUGGER is not of type SB-DI:FRAME.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit application

(SB-DEBUG::FRAME-CALL INVOKE-DEBUGGER :METHOD-FRAME-STYLE :NORMAL :REPLACE-DYNAMIC-EXTENT-OBJECTS NIL)
0[2] 2016-05-25T18:38:03.287000Z DEBUG CONNECT #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://postgres@localhost:5432/taal {10071B1803}>
2016-05-25T18:38:03.288000Z DEBUG SET work_mem TO '12MB'
2016-05-25T18:38:03.288000Z DEBUG BEGIN
2016-05-25T18:38:03.288000Z NOTICE drop table if exists test;
2016-05-25T18:38:03.288000Z NOTICE create table test (
a serial,
b integer,
c integer,
d text,
e text,
f text,
g text,
h character varying(255),
j character varying(50)
        );
2016-05-25T18:38:03.288000Z FATAL We have a situation here.

**Comment by dimitri** [comment]
Looks like you're running a pretty old version of pgloader, please try again with a build from current sources? (the `pgstate-add-table` is no more, see https://github.com/dimitri/pgloader/commit/96a33de08437332f22c9f731203b00e8f625f1b8 from Oct. 2015).

**Comment by angercho** [comment]
yes I also try before to compile it but got this error : 
; Loading "mssql"

debugger invoked on a LOAD-SYSTEM-DEFINITION-ERROR in thread #<THREAD
                                                               "initial thread" RUNNING
                                                               {1002C278D1}>:
  Error while trying to load definition for system cffi from pathname
  /opt/pgload/new/pgloader-3.2.2/build/quicklisp/dists/quicklisp/software/cffi_0.17.1/cffi.asd:

     error while parsing arguments to DESTRUCTURING-BIND:
       invalid number of elements in
         (OPERATE 'TEST-OP :CFFI-TESTS)
       to satisfy lambda list
         (O C):
       exactly 2 expected, but 3 found

Type HELP for debugger help, or (SB-EXT:QUIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [REINITIALIZE-SOURCE-REGISTRY-AND-RETRY] Retry finding system cffi after
                                              reinitializing the
                                              source-registry.
  1: [ABORT                                 ] Give up on "mssql"
  2:                                          Give up on "pgloader"
  3: [CONTINUE                              ] Ignore runtime option --eval "(ql:quickload \"pgloader\")".
  4:                                          Skip rest of --eval and --load options.
  5:                                          Skip to toplevel READ/EVAL/PRINT loop.
  6: [QUIT                                  ] Quit SBCL (calling #'QUIT, killing the process).

**Comment by dimitri** [comment]
First time I see that one :/ can you try to `git pull` and `make clean` then `make` again?

**Comment by angercho** [comment]
try it .... still same : 
From https://github.com/dimitri/pgloader
   826d975..1378949  master     -> origin/master
Updating 826d975..1378949
Fast-forward
 .travis.yml                           |   12 ++----
 Makefile                              |    8 ++--
 pgloader.1                            |   65 ++++++++++++++++++++++++++++++++-
 pgloader.1.md                         |   57 +++++++++++++++++++++++++++--
 src/parsers/command-cast-rules.lisp   |   11 ++++--
 src/sources/common/casting-rules.lisp |    3 +-
 6 files changed, 135 insertions(+), 21 deletions(-)
[root@localhost pgloader]# git pull
Already up-to-date.

and got same like above  error for mssql 
can I skip it ?

**Comment by angercho** [comment]
and how ? :)

**Comment by dimitri** [comment]
Did you do the `make clean` dance? we don't have conditional compilation at this time, maybe I should think about it...

**Comment by angercho** [comment]
yes :( and still same

**Comment by angercho** [comment]
is there new RPM ?

**Comment by dimitri** [comment]
Closing this issue now for lack of information / details ; please open again with more information if you still reach this error when compiling from current master's branch.
