### ISSUE TITLE
Overly strict csv-raw-field-name definition

### ISSUE THREAD

**Issue by niels** [dimitri/pgloader#416]
When importing from a CSV file with field names such as `Some-Field` or `Some/Field`, pgloader fails during the parsing step with an error like

```
An unhandled error condition has been signalled: At

        "Some-Field",
             ^ (Line 49, Column 18, Position 1295)

Could not parse CSV-QUOTED-FIELD-NAME. Expected:

  the character " (QUOTATION_MARK)

Reached via

     ANOTHER-CSV-SOURCE-FIELD
  -> (AND COMMA CSV-SOURCE-FIELD)
  -> CSV-SOURCE-FIELD
  -> (AND CSV-FIELD-NAME CSV-FIELD-OPTIONS)
  -> CSV-FIELD-NAME
  -> (OR CSV-QUOTED-FIELD-NAME CSV-BARE-FIELD-NAME)
  -> CSV-QUOTED-FIELD-NAME
  -> (AND "\"" CSV-RAW-FIELD-NAME "\"")
  -> "\""

; 
; compilation unit aborted
;   caught 1 fatal ERROR condition
```

When using a load file like

```
LOAD CSV
  FROM /tmp/combined.csv
    HAVING FIELDS (
      "Some-Field"
    )
  […]
```

However, when quoted I would say that these are perfectly valid characters to be in a field name – in fact all characters should be allowed?

After modifying the `csv-raw-field-name` definition in `src/parsers/command-csv.lisp` accordingly (i.e. adding `#\-` and `#\/`), my import ran successfully.

**Comment by dimitri** [comment]
The parsing of identifiers (field names etc) is inspired (or straight) from PostgreSQL lever as documented at https://www.postgresql.org/docs/current/static/sql-syntax-lexical.html : 

> SQL identifiers and key words must begin with a letter (a-z, but also letters with diacritical marks and non-Latin letters) or an underscore (_). Subsequent characters in an identifier or key word can be letters, underscores, digits (0-9), or dollar signs ($). Note that dollar signs are not allowed in identifiers according to the letter of the SQL standard, so their use might render applications less portable. The SQL standard will not define a key word that contains digits or starts or ends with an underscore, so identifiers of this form are safe against possible conflict with future extensions of the standard.

It might be possible to make it accept more things, I'm not sure if it's a good move yet... leaving the issue open for now...

**Comment by niels** [comment]
Mmh, interesting. I would still definitely vote for accepting a wider range of characters however. Note that the above quote only applies to *unquoted* identifiers. Once you quote them, pretty much everything is allowed (emphasis added):

> There is a second kind of identifier: **the delimited identifier or quoted identifier**. It **is formed by enclosing an arbitrary sequence of characters in double-quotes (")**. A delimited identifier is always an identifier, never a key word. So "select" could be used to refer to a column or table named "select", whereas an unquoted select would be taken as a key word and would therefore provoke a parse error when used where a table or column name is expected. The example can be written with quoted identifiers like this:
> 
> UPDATE "my_table" SET "a" = 5;
> 
> **Quoted identifiers can contain any character, except the character with code zero. (To include a double quote, write two double quotes.)** This allows constructing table or column names that would otherwise not be possible, such as ones containing spaces or ampersands. The length limitation still applies.

I did in fact run into a similar issue where pgloader would not allow me to use a table named `2016-05-21` whereas PostgreSQL itself is perfectly happy working with such a table. So pgloader is much more restrictive in what identifiers it accepts than PostgreSQL – and I would assume many other databases?
