### ISSUE TITLE
Database error 23502

### ISSUE THREAD

**Issue by samuraraujo** [dimitri/pgloader#417]
The data contains no null value but I am getting this message. 

```
2016-06-01T16:42:42.589000+02:00 ERROR Database error 23502: null value in column "created_at" violates not-null constraint
```

Any clue why this may be happening?

**Comment by dimitri** [comment]
I need way more information here. Can you show before/after data, the load file, explain what the source is, or even build a self-contained test case?

**Comment by dimitri** [comment]
Closing for lack of information. If you have details you can share, consider opening again.
