### ISSUE TITLE
pgloader process getting killed

### ISSUE THREAD

**Issue by AndreaCrotti** [dimitri/pgloader#418]
I've been trying for a while now to migrate a big database, but even if I exclude all the bigger tables with one of the databases it always fails, now simply saying:

"Killed"

And that's using the pgloader version compiled with ccl, instead with the default one I get the memory issue #399 
I'm also running in debug mode but I don't really get that much information on what is going on, any clue?

What can it be?

**Comment by dimitri** [comment]
Is it killed by the linux OOM killer or something?

**Comment by AndreaCrotti** [comment]
Yes I think that might be the problem, even if normally I would see an OOM error in the terminal which I don't see in this case.

I can try to increase the memory of that machine (which is 8GB already) but does the memory used by pgloader increase infinitely otherwise?
Anything else I can do? 
Maybe I need to create multiple configurations and port one subset of tables at a time?
Which might however have other issues with foreign keys though if some tables required are not there yet right?

**Comment by dimitri** [comment]
For me to be able to help you I will need more information, such as logs...

**Comment by AndreaCrotti** [comment]
Yes well the problem is that even running with the "-d" flag the logs don't really say anything useful.
They just write what they were doing and that's it, I get a "killed" on the terminal it was executing.

Using the version compiled with SBCL it goes into memory troubles and give me an LDB shell, but I doubt I can do much more with that too..

**Comment by dimitri** [comment]
I'm not sure I can do anything useful here given the level of information, so I'm closing the issue in an attempt to clean up the issues list. Consider opening again with more details if needed.

**Comment by AndreaCrotti** [comment]
Yes well I think it's still related with memory usage, which you maybe already addressed here?
https://github.com/dimitri/pgloader/issues/399
