### ISSUE TITLE
Cast of int(11) to serial doesn't work

### ISSUE THREAD

**Issue by jamesjrg** [dimitri/pgloader#421]
The default casting rules change mysql int(11) to postgres bigserial (i.e. bigint with a sequence).

I have a pgloader.load file with the line:
`
CAST column my_table_with_int11_id.id to serial drop typemod`

As far as I can remember, when I used pgloader 3.2.2 installed from the postgres apt sources, the resulting postgres column had type serial. Using the docker image of HEAD yesterday, the resulting postgres column has type bigserial.

It seems to me that it should end up a int/serial, not a bigint/bigserial, and unless I remember incorrectly I think this used to work in 3.2.2.

**Comment by dimitri** [comment]
Can you please share the relevant parts of the logs in `--verbose` mode, where pgloader now logs its CASTing decisions per column?

**Comment by jamesjrg** [comment]
I can't see any specific mention of CAST when running in verbose mode, unless you mean the create table statement:

```
2016-06-16T08:50:07.240000Z NOTICE CREATE TABLE mytable 
(
  id              bigserial not null,
....
```

Btw casting a normal int(11) to int still works, it is just casting int(11) auto increment to serial that has stopped working.

**Comment by dimitri** [comment]
One of the default CAST rules targets `bigint` for `int` when the precision is greater than 10 digits, because at 11 digits you can already pass the 32-bits threshold (of _signed_ integers). Please try to add the `WHEN` clause in your cast rule so that your rule takes precedence over the default one:

```
   CAST type int to bigint when (<= 10 precision)
```

**Comment by jamesjrg** [comment]
I am trying to cast int(11) to int/serial, isn't the suggested cast rule for a different level of precision (<= 10) and a different direction of cast (int -> bigint rather than bigint -> int)?

**Comment by dimitri** [comment]
The default cast rules are:

```lisp
    (:source (:type "int" :auto-increment t :typemod (< precision 10))
     :target (:type "serial"))

    (:source (:type "int" :auto-increment t :typemod (<= 10 precision))
     :target (:type "bigserial"))
```

**Comment by jamesjrg** [comment]
1. As I understand it CAST statements are meant to override the defaults
2. I assume there's a typo in the default rules above

**Comment by dimitri** [comment]
I see what you mean now, I only reported the default cast as a user defined cast rule, I think the rule you want to have looks like this:

    CAST int to int when (<= precision 11)

**Comment by jamesjrg** [comment]
I don't want to cast int to int, I want to cast int to serial for a particular column for a particular table, that's why I tried:

CAST column my_table.id to serial drop typemod
