### ISSUE TITLE
fatal error encountered in SBCL pid 26177(tid 140737354045184): can't find core file at /usr/local/lib/sbcl//sbcl.core

### ISSUE THREAD

**Issue by bunlongheng** [dimitri/pgloader#423]
# VM Details 

- Cent OS 6.7 
- pgloader --version (SBCL 1.1.14)

### I ran 

`pgloader mysql://root@localhost/ssc-portal postgresql://postgres@localhost/portal`

### I got 

`fatal error encountered in SBCL pid 26063(tid 140737354045184):
can't find core file at /usr/local/lib/sbcl//sbcl.core`

**Comment by dimitri** [comment]
Please try and provide more information, there's nothing I can do with only this... :(

**Comment by gvangool** [comment]
@bunlongheng could you check with the updated bootstrap scripts? #424
