### ISSUE TITLE
SSL23_GET_SERVER_HELLO failure in the SSL library occurred

### ISSUE THREAD

**Issue by vmogilev** [dimitri/pgloader#426]
I am trying to run pgloader agaist Amazon MySQL RDS Instance and getting the following error message:

```
An unhandled error condition has been signalled:
   Failed to connect to mysql at "msqlXX.*********-1.rds.amazonaws.com" (port 3306) as user "XX": A failure in the SSL library occurred on handle #.(SB-SYS:INT-SAP #X002155A0) (return code: 1).
SSL error queue:
error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
```

What could be causing this?

**Comment by dimitri** [comment]
We have other reports of problems to connect to RDS from pgloader, it seems that there's a protocol mismatch in between what my MySQL driver expects / implements and what RDS provides :( In this specific case it looks to be at the SSL driver level, which is surprising.

Can you rebuild pgloader locally with a recent enough SSL lib, or use the docker image that I maintain on docker hub, just to see what happens? https://hub.docker.com/r/dimitri/pgloader/

**Comment by vmogilev** [comment]
The openssl version I am using is `openssl/1.0.2h_1`

and I even copied AWS RDS CA cert `rds-combined-ca-bundle.pem` into `openssl/certs` directory and ran `openssl/bin/c_rehash`

still failed with the same error.

**Comment by mwhagedorn** [comment]
same exact problem, osx, pgloader version "3.2.2"
compiled with SBCL 1.3.0,
 MySQL:
Server version: 5.7.9 Homebrew

   Failed to connect to mysql at "localhost" (port 3306) as user "root": A failure in the SSL library occurred on handle #.(SB-SYS:INT-SAP #X12211C00) (return code: 1).
SSL error queue:
error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol

my root user doesnt have a password at this time on my dev box.

**Comment by nguyenhung** [comment]
Same problem on PGLoader 3.2.2.
I think this may help: https://forums.aws.amazon.com/thread.jspa?messageID=610654

**Comment by lucian303** [comment]
Also running into this on OS X pgloader 3.2.2 gives me:

```
2016-09-03T01:38:30.067000+01:00 LOG Main logs in '/private/tmp/pgloader/pgloader.log'
2016-09-03T01:38:30.073000+01:00 LOG Data errors in '/private/tmp/pgloader/'
2016-09-03T01:38:30.073000+01:00 LOG Parsing commands from file #P"/Users/lucian303/Desktop/scripts/pgloader/config-prod.conf"
An unhandled error condition has been signalled:
   Failed to connect to mysql at "ucfdb-prod2.cgf6zny6zvpl.us-east-1.rds.amazonaws.com" (port 3306) as user "ucfroot": A failure in the SSL library occurred on handle #.(SB-SYS:INT-SAP #X11911540) (return code: 1). SSL error queue:
error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
```

The Linux version (same version) works fine. I've experienced SSL problems with some OS X mysql clients as well (but not their linux counterparts) though not all builds. Could be something w/ the OS X OpenSSL version being used...

**Comment by superbool** [comment]
I got the same error in my mac ：
```
2016-10-28T10:49:35.061000+08:00 LOG Main logs in '/private/tmp/pgloader/pgloader.log'
2016-10-28T10:49:35.065000+08:00 LOG Data errors in '/private/tmp/pgloader/'
2016-10-28T10:49:35.065000+08:00 LOG Parsing commands from file #P"/Users/kofee/PycharmProjects/baixing/migrate-data/bx_crm_dev.load"
An unhandled error condition has been signalled:
   Failed to connect to mysql at "119.254.100.162" (port 33066) as user "maxwell": A failure in the SSL library occurred on handle #.(SB-SYS:INT-SAP #X003012A0) (return code: 1). SSL error queue:
error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
```
My pgloader is ：
```
➜  ~ pgloader -V
pgloader version "3.2.2"
compiled with SBCL 1.3.10
```
@lucian303 have you solved it ?

**Comment by lucian303** [comment]
I didn't. I just switched to running it on Ubuntu when converting big
databases.

**Comment by superbool** [comment]
I have changed the default openssl in my mac (use brew install openssl,and set /usr/local/bin/openssl to brew openssl dir),but it still got the same error. So I give up and use pgloader in Centos server .It works fine.

**Comment by brandondrew** [comment]
This is still a problem, more than a year later.  
> pgloader version "3.3.2"
> compiled with SBCL 1.3.19

Is there any solution?

@dimitri  Given that it reportedly works on Linux, is the MySQL driver you're using on each platform different?

**Comment by dimitri** [comment]
The same pure-Common Lisp driver is used on every platform. The SSL support is implement with https://common-lisp.net/project/cl-plus-ssl/ ; a library that provides a mapping to OpenSSL. To be able to fix those problems, I will need help.

**Comment by dimitri** [comment]
I believe we made progress on this issue in the meanwhile. Current pgloader release is 3.6.1. Closing the issue, please open again if needed.
