### ISSUE TITLE
In desparate need of the pgloader executable for Linux redhat

### ISSUE THREAD

**Issue by sadenwala** [dimitri/pgloader#428]
Due to proxy issues and not having root on my linux redhat, I am not able to install pgloader using pgloader-latest.tgz. 

Can someone please give me the pgloader executable (and any associated files) so that I can start using pgloader without going through any of yum or git or rpm or make commands?

Any help will be highly appreciated.

**Comment by dimitri** [comment]
You have several choices already:

  - use the source bundle at http://pgloader.io/files/pgloader-bundle-3.3.0.50.tgz ; it contains all the source level build dependencies and doesn't require Quicklisp nor git when building from it ;

  - use a docker image found at https://hub.docker.com/r/dimitri/pgloader/ so that you don't depend on the current RH environment to be able to run pgloader ;

  - build on a RH setup that's connected to the internet without proxy issues and then transfer the `./build/bin/pgloader` to the proxied machine ;

  - ask your favorite RH or CentOS packager to please take care of pgloader ;

  - it's possible to build pgloader and use a proxy thanks to the `http_proxy` environment variable, when the proxy itself isn't broken ;

  - fix your proxy ;-)

**Comment by sadenwala** [comment]
Thanks for your reply!
I took the 1st option that you suggested, here is my output.  What am I doing wrong?

==> pwd
/home/techsupp/pgloader-bundle-3.3.0.50

==> ls -l
total 32
-rw-r-----  1 techsupp techsupp 6220 Jan 31 12:27 bundle.lisp
drwxr-x---  3 techsupp techsupp 4096 Jun 27 08:57 local-projects
-rw-r-----  1 techsupp techsupp 2805 Jan 31 12:27 Makefile
-rw-r-----  1 techsupp techsupp  917 Jan 31 12:27 README.md
drwxr-x--- 61 techsupp techsupp 4096 Jun 27 08:57 software
-rw-r-----  1 techsupp techsupp 4511 Jan 31 12:27 system-index.txt
zltv0459:/home/techsupp/pgloader-bundle-3.3.0.50
==> make
mkdir -p bin
sbcl --noinform --no-sysinit --no-userinit --load bundle.lisp                           \
             --eval '(asdf:load-system :buildapp)'                    \
             --eval '(buildapp:build-buildapp "bin/buildapp")'                  \
             --eval '(quit)'
;; loading system "buildapp"
[undoing binding stack and other enclosing state... done]
[saving current Lisp image into /home/techsupp/pgloader-bundle-3.3.0.50/bin/buildapp:
writing 3496 bytes from the read-only space at 0x1000000
writing 2240 bytes from the static space at 0x1100000
writing 35893248 bytes from the dynamic space at 0x9000000
done]
git clone https://github.com/dimitri/cl-ixf.git local-projects/cl-ixf
make: git: Command not found
make: *** [local-projects/cl-ixf] Error 127
zltv0459:/home/techsupp/pgloader-bundle-3.3.0.50

Thanks for your assistance!

**Comment by aklaver** [comment]
You do need Git installed to use the bundle.

**Comment by piercej** [comment]
I thought the bundle was self contained?  if its fetching sources from external repositories, thats not even remotely self contained, and would be due cause to be rejected by the packaging policies of most RPM repositories.

**Comment by aklaver** [comment]
I thought I might have confused it with running the default source download, so I ran the bundle again:
aklaver@panda:~/pgloader_test/pgloader-bundle-3.3.0.50> make  DYNSIZE=1024
mkdir -p bin
sbcl --noinform --no-sysinit --no-userinit --load bundle.lisp                           \
             --eval '(asdf:load-system :buildapp)'                    \
             --eval '(buildapp:build-buildapp "bin/buildapp")'                  \
             --eval '(quit)'
;; loading system "buildapp"
[undoing binding stack and other enclosing state... done]
[saving current Lisp image into /home/aklaver/pgloader_test/pgloader-bundle-3.3.0.50/bin/buildapp:
writing 3496 bytes from the read-only space at 0x0x1000000
writing 2240 bytes from the static space at 0x0x1100000
writing 41041920 bytes from the dynamic space at 0x0x9000000
done]
git clone https://github.com/dimitri/cl-ixf.git local-projects/cl-ixf
Cloning into 'local-projects/cl-ixf'...
remote: Counting objects: 68, done.
remote: Total 68 (delta 0), reused 0 (delta 0), pack-reused 68
Unpacking objects: 100% (68/68), done.
Checking connectivity... done.
git clone https://github.com/dimitri/cl-db3.git local-projects/cl-db3
Cloning into 'local-projects/cl-db3'...
remote: Counting objects: 10, done.
remote: Total 10 (delta 0), reused 0 (delta 0), pack-reused 10
Unpacking objects: 100% (10/10), done.
Checking connectivity... done.
git clone https://github.com/AccelerationNet/cl-csv.git local-projects/cl-csv
Cloning into 'local-projects/cl-csv'...
remote: Counting objects: 487, done.
....
More of same.

**Comment by jhickner** [comment]
I'm in a similar situation attempting to build the binaries for Ubuntu. I tried via both pulling the latest head from github, and pulling the source .tgz linked above. After running make, both approaches fail with the same error:

```
debugger invoked on a LOAD-SYSTEM-DEFINITION-ERROR in thread #<THREAD "main thread"
RUNNING {1002A8BDB3}>: Error while trying to load definition for system bordeaux-threads
from pathname /data/pgloader-bundle-3.3.0.50/local-projects/pgloader-
3.3.0.50/build/quicklisp/dists/quicklisp/software/bordeaux-threads-v0.8.5/bordeaux-
threads.asd: READ error during COMPILE-FILE: You need ASDF >= 3.1 to load this system
correctly.(in form starting at line: 1, column: 0, file-position: 0)
```

This is with a clean ubuntu installation with only `apt-get install sbcl unzip libsqlite3-dev make curl gawk freetds-dev libzip-dev` installed as per the readme. 

It looks like the right version of ASDF is not installed. How do I install ASDF >= 3.1? Also, this would be a good addition to the readme.

**Comment by aklaver** [comment]
What version of Ubuntu?
What version of sbcl?

**Comment by jhickner** [comment]
14.04 LTS
SBCL 1.1.14.debian

**Comment by aklaver** [comment]
If it where me I would enable backports and see if I could get a newer version of sbcl.

**Comment by dimitri** [comment]
Indeed, ASDF is distributed as part of the main CL implementation, SBCL and CCL included, so try to see if you can get a more recent version of the compiler environment.

Other than that, I probably should have included my local git clones in the bundle so that @sadenwala doesn't need `git` when building from the bundle... the whole point being to reduce build dependencies, right? So that's what I've done in http://pgloader.io/files/pgloader-bundle-3.3.0.51.tgz
