### ISSUE TITLE
PGLoader does not parse table name with schema correctly from command line

### ISSUE THREAD

**Issue by lholloway-r7** [dimitri/pgloader#430]
When attempting to perform a csv bulkload with the following command:
`pgloader --type csv --field "field1,field2,..." --with "skip header = 1" --with "fields terminated by ','" file.csv postgres://localhost:5432/dbname?bulkload.mytable`

This error occurs:
```
An unhandled error condition has been signalled:
   Database error 3F000: schema "(bulkload" does not exist
QUERY:
    select attname
      from pg_class c
           join pg_namespace n on n.oid = c.relnamespace
           left join pg_attribute a on c.oid = a.attrelid
           join pg_type t on t.oid = a.atttypid
     where c.oid = '(bulkload . mytable)'::regclass and attnum > 0
  order by attnum
```

EDIT: removing the `()` wil fix the query.

`pgloader -V` returns 
```
pgloader version "3.2.2"
compiled with SBCL 1.3.0
```

**Comment by dimitri** [comment]
I think this problem has been fixed in the current source tree meanwhile, so please consider building from sources (git master branch) and trying again.

**Comment by lholloway-r7** [comment]
@dimitri That fixed it, thanks!
