### ISSUE TITLE
ERROR not supported type SYB-DATETIME4 for MSSQL

### ISSUE THREAD

**Issue by abnerx** [dimitri/pgloader#431]
Hello,

I've been trying to load a mssql table using pgloader, one of the fields within the mssql table is of type smalldatetime. I've tried casting the field as either date or timestamptz, in both cases I get an error msg of: ERROR not supported type SYB-DATETIME4.

I noticed that you have a monkey patch listing this type on: https://github.com/dimitri/pgloader/blob/master/src/monkey/mssql.lisp#L25

Is this fix on the current stable version? 

Thanks!

**Comment by dimitri** [comment]
The datatype isn't supported in the `case` statement starting L97 on current code. Can you try the following simple patch and report? 

```diff
-             (:syb-datetime
+             ((:syb-datetime :syb-datetime4)
``

**Comment by abnerx** [comment]
That made the error message change into: ERROR Database error 22007: invalid input syntax for type timestamp with time zone: "Jun 26 2015 12:00:00:000AM" when casted as timestamptz.

I casted it as date as well with similar error output in reference: ERROR Database error 22007: invalid input syntax for type date: "Jun 26 2015 12:00:00:000AM"

**Comment by abnerx** [comment]
If it is of any help this is a PG casting/transformation for this smalldatetime field: to_date(cast(smalldatetime_field as TEXT),'Mon DD YYYY HH12:MI:SS:MSAM')

**Comment by dimitri** [comment]
In `pgloader:src/sources/mssql/mssql-schema.lisp` we have the following:

```lisp
(defun get-column-sql-expression (name type)
  "Return per-TYPE SQL expression to use given a column NAME.

   Mostly we just use the name, and make try to avoid parsing dates."
  (case (intern (string-upcase type) "KEYWORD")
    (:datetime  (format nil "convert(varchar, [~a], 126)" name))
    (:bigint    (format nil "cast([~a] as numeric)" name))
    (t          (format nil "[~a]" name))))
```

Could you test the following patch on top of that:
```diff
--- a/src/sources/mssql/mssql-schema.lisp
+++ b/src/sources/mssql/mssql-schema.lisp
@@ -281,7 +281,8 @@ ORDER BY KCU1.CONSTRAINT_NAME, KCU1.ORDINAL_POSITION"
 
    Mostly we just use the name, and make try to avoid parsing dates."
   (case (intern (string-upcase type) "KEYWORD")
-    (:datetime  (format nil "convert(varchar, [~a], 126)" name))
+    ((:datetime :datetime4)
+                (format nil "convert(varchar, [~a], 126)" name))
     (:bigint    (format nil "cast([~a] as numeric)" name))
     (t          (format nil "[~a]" name))))
```

**Comment by nicowernli** [comment]
Hi @dimitri, I've tried this patch but didn't work for me, still getting the error:

```
2017-01-11T10:52:36.116000+01:00 ERROR not supported type SYB-DATETIME4
2017-01-11T10:52:36.116000+01:00 ERROR not supported type SYB-DATETIME4
```

**Comment by dimitri** [comment]
Hi @nicowernli, thanks for testing with the patch!  In `--debug` mode you should see the generated SQL to fetch the content of that source table, can you please check if it contains the proper `convert` expression for the source column? Do we need another `convert` expression in MS SQL for the short date time type?

**Comment by nicowernli** [comment]
Hi @dimitri I runed in `--debug` mode and looks like the field is not getting converted at all.

```
SELECT [Name], ..., convert(varchar, [LastEdit], 126), [DateTimeCheckedMarkers] FROM [dbo].[TABLENAME];
```

And the error is:
```
ERROR Database error 22007: invalid input syntax for type timestamp: "Feb  3 2014 12:45:00:000PM" 
CONTEXT: COPY TABLENAME, line 38, column datetimecheckedmarkers: "Feb  3 2014 12:45:00:000PM"
```

The MSSQL field type is `SMALLDATETIME` and values are stored like `2014-02-03 12:45:00`.

**Comment by dimitri** [comment]
Can you run the SQL query at https://github.com/dimitri/pgloader/blob/master/src/sources/mssql/mssql-schema.lisp#L218 and show the result for this table, so that we can check what MSSQL is reporting as the column type here...

Another angle is to check your build process and when you did apply the patch in there, to make sure you are indeed using a patched version of the binary.

The easiest would be for me to have access to your database and plug my development environment against it.

**Comment by dimitri** [comment]
Finally, I could have access to a database from which to reproduce the problem. So here's a fix for it.
