### ISSUE TITLE
PERFORMANCES  should be PERFORMANCE

### ISSUE THREAD

**Issue by jeffwidman** [dimitri/pgloader#432]
Thanks for this tool, really helpful. 

Reading the docs, I noticed it looks like you're a non-native speaker... PERFORMANCES  should be PERFORMANCE... unless referring to specific instances, such as musical performances. I'm not sure of the technical reason, just that that's the way we say it. 

I'd submit a PR to fix, but I'm unsure of the difference between `pgloader.1` and `pgloader.1.md` as they both seem similar.

**Comment by dimitri** [comment]
Thanks! `pgloader.1` is the result of `make docs` which processes the `pgloader.1.md`, please submit a PR that edits the latter, and if you can that includes the fixed generated man page!
