### ISSUE TITLE
Getting 'ERROR Argument X is not a NUMBER: "0" ' when doing a fixed-width load

### ISSUE THREAD

**Issue by iwarford** [dimitri/pgloader#434]
We have several files in fixed-width format that we are attempting to load, and we are always getting this error in the output when trying:

```
2016-07-20T22:11:31.292000Z ERROR Argument X is not a NUMBER: "0"
2016-07-20T22:11:31.292000Z ERROR Argument X is not a NUMBER: "0"
2016-07-20T22:11:31.293000Z ERROR Argument X is not a NUMBER: "0"
2016-07-20T22:11:31.293000Z ERROR Argument X is not a NUMBER: "0"
2016-07-20T22:11:31.293000Z ERROR Argument X is not a NUMBER: "0"
2016-07-20T22:11:31.293000Z ERROR Argument X is not a NUMBER: "0"
2016-07-20T22:11:31.293000Z ERROR Argument X is not a NUMBER: "0"
2016-07-20T22:11:31.293000Z ERROR Argument X is not a NUMBER: "0"
2016-07-20T22:11:31.293000Z ERROR Argument X is not a NUMBER: "0"
2016-07-20T22:11:31.293000Z ERROR Argument X is not a NUMBER: "0"
...
...
...
             table name       read   imported     errors      total time       read      write
-----------------------  ---------  ---------  ---------  --------------  ---------  ---------
                  fetch          0          0          0          0.014s                     
-----------------------  ---------  ---------  ---------  --------------  ---------  ---------
            generic_foo          0          0        251          0.004s                     
-----------------------  ---------  ---------  ---------  --------------  ---------  ---------
COPY Threads Completion          3          3          0          0.005s                     
-----------------------  ---------  ---------  ---------  --------------  ---------  ---------
      Total import time          0          0        251          0.299s                     
```

The data is currently a list of nullable integers, however that isn't the Argument that the loader seems to be complaining about.  The "0" it's referring to is actually the 0 in the command file.  The above was generated by a load file that's simply this:

```
LOAD FIXED  
     FROM stdin
          (  
           a 0 32
          )  
           INTO postgresql://username:password@our.database.host/database?generic_foo  
          (  
           a
          );  
````

If we change the first 0 there to another number:

```
LOAD FIXED  
     FROM stdin
          (  
           a 42 32
          )  
...
...
...
```

we get:

```
2016-07-20T22:25:00.318000Z ERROR Argument X is not a NUMBER: "42"
```

So that's definitely where the parsing issue is coming from.  

We also encountered a similar error with the example provided in [your documentation](http://webcache.googleusercontent.com/search?q=cache:http://pgloader.io/howto/pgloader.1.html) (using the google cache because the pgloader site is down at the time of writing).  Attached the load file from the documentation and the output, where the same error happens.  

[fixed.load.txt](https://github.com/dimitri/pgloader/files/374805/fixed.load.txt)

[output.txt](https://github.com/dimitri/pgloader/files/374803/output.txt)

**Comment by iwarford** [comment]
Just as an update, I patched in a workaround in `src/sources/fixed.lisp`.  This is probably not the Right Way to do it, but Lisp isn't my first language, so it'll have to do for now.

```
55,57c55,57
<                 (let ((end (+ start length)))
<                   (when (<= start len)
<                     (subseq line start (min len end)))))))
---
>                 (let ((end (+ (parse-integer start) (parse-integer length))))
>                   (when (<= (parse-integer start) len)
>                     (subseq line (parse-integer start) (min len end)))))))
```

It looks like for whatever reason, the offsets/lengths in fixed-col-specs are being stored as strings, not numbers.  There's probably a better place to correct this, but this got things working and loading for me.

**Comment by dimitri** [comment]
Thanks for the inquiry and proposal, you're right that it's not the proper place to fix the bug, so I did otherwise. As noted in the commit messages several areas will now need more investigation...
