### ISSUE TITLE
MSSQL not importing foreign keys

### ISSUE THREAD

**Issue by xbogdan** [dimitri/pgloader#436]
Everything get imported except contraints.
Am I doing something wrong ?

```
LOAD database
     from mssql://user@host/dbname
     into postgresql://postgres:mysecret@172.17.0.2/postgres
WITH schema only, create indexes, foreign keys, reset sequences, downcase identifiers, include drop
CAST
     type smalldatetime to timestamp

EXCLUDING TABLE NAMES like 'stuff%' in schema 'dbo'
```

**Comment by dimitri** [comment]
Which kind of constraints? We only support Primary Keys, UNIQUE indexes and Foreign-keys at the moment. You can review https://github.com/dimitri/pgloader/blob/master/src/sources/mssql/mssql-schema.lisp for the details of what we support exactly.

**Comment by xbogdan** [comment]
Yes those types of constraints. Its not importing them and I thought that maybe I m doing something wrong.

I get no foreign keys.

Also after creating all the tables the process/visual output its not closing. Its stays open. I have to ctrl + c to close, it should be like that ? Maybe thats the error though I don't get any errors in the log, only warning that the "table doesn't exists. skipping..."

**Comment by dimitri** [comment]
Please try running with `--client-min-message info` or `--verbose` and report more information. You shouldn't have to kill the process, it normally prints out a summary of the actions done before exiting itself.
