### ISSUE TITLE
Building with CCL fails

### ISSUE THREAD

**Issue by lucian303** [dimitri/pgloader#438]
I've tried building both the git repo and the pgloader bundle. Nowhere does it actually pull in CCL apparantely. Also tried to download CCL from SVN but that's useless as there are no build/install instructions. This is from the tarball, but the error from the git repo is more or less the same. 

```
╭─root at ip-172-31-22-203 in /home/ubuntu/pgloader-bundle-3.3.0.50 using
╰─○ make CL=ccl pgloader
make: ccl: Command not found
mkdir -p bin
ccl --noinform --no-sysinit --no-userinit --load bundle.lisp                           \
             --eval '(asdf:load-system :buildapp)'                    \
             --eval '(buildapp:build-buildapp "bin/buildapp")'                  \
             --eval '(quit)'
make: ccl: Command not found
make: *** [bin/buildapp] Error 127
```

**Comment by dimitri** [comment]
Please review http://ccl.clozure.com/install.html and that parts:

> In the scripts/ directory of the ccl directory, there are two files named ccl and ccl64. Copy these files into /usr/local/bin or some other directory that is on your path, and then edit them so that the value of CCL_DEFAULT_DIRECTORY is your ccl directory. You can then start up the lisp with "ccl" or "ccl64".

Complete Clozure Common Lisp install then try again.

**Comment by lucian303** [comment]
I get:

```
Couldn't load lisp heap image from /home/ubuntu/ccl/lx86cl64.image: No such file or directory
```

I was able to build the lx86cl64 binary and modify the starting script to point to the right directory, but I have no idea where the heap image is or how to make one. Nor does it say how to in the installation. It says "In the ccl directory, you will find heap images and pre-compiled lisp kernel binaries for your platform." which quite simply is false. Neither exist. The binary at least can be compiled.

**Comment by dimitri** [comment]
Can you give the list of commands you typed to get where you are, please? I never had any problem to work with CCL myself, but on Mac you can either use the AppStore or `brew` and it just works...

**Comment by lucian303** [comment]
I was able to get it working. Apparently, I was using the OS X branch of CCL on Linux as I just copied the SVN link directly from their page. The Linux branch had the right image.
