### ISSUE TITLE
32 bit Windows sqlite dependency build error with MSys2.  

### ISSUE THREAD

**Issue by jrpetit** [dimitri/pgloader#440]
Build environment: pgloader(v3.3.1). MSys2 (32bit) on Windows 10. SBCL (32bit) from their website. Added dependencies using MSys2 package manager (pacman).

Msys2 package manager shows sqlite is installed:
```bash
$pacman -Q | grep sqlite
libsqlite 3.10.0.0-1
sqlite 3.10.0.0-1
```
Relevant build output:
```make
$ make pgloader
sbcl --noinform --no-sysinit --no-userinit --load build/quicklisp/setup.lisp                 \
             --eval '(push "/c/Users/user/Documents/company/Src/project/pgloader/" asdf:*central-registry*)'      \
             --eval '(ql:quickload "pgloader")'                     \
             --eval '(quit)'
To load "pgloader":
  Load 1 ASDF system:
    pgloader
; Loading "pgloader"
............
debugger invoked on a LOAD-FOREIGN-LIBRARY-ERROR in thread
#<THREAD "main thread" RUNNING {23E37749}>:
  Unable to load any of the alternatives:
   ((:DEFAULT "libsqlite3") (:DEFAULT "sqlite3"))

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Try loading the foreign library again.
  1: [USE-VALUE                    ] Use another library instead.
  2: [TRY-RECOMPILING              ] Recompile sqlite-ffi and try loading it again
  3: [RETRY                        ] Retry
                                     loading FASL for #<CL-SOURCE-FILE "sqlite" "sqlite-ffi">.
  4: [ACCEPT                       ] Continue, treating
                                     loading FASL for #<CL-SOURCE-FILE "sqlite" "sqlite-ffi">
                                     as having been successful.
  5:                                 Retry ASDF operation.
  6: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  7: [ABORT                        ] Give up on "pgloader"
  8: [CONTINUE                     ] Ignore runtime option --eval "(ql:quickload \"pgloader\")".
  9:                                 Skip rest of --eval and --load options.
 10:                                 Skip to toplevel READ/EVAL/PRINT loop.
 11: [EXIT                         ] Exit SBCL (calling #'EXIT, killing the process).

(CFFI::FL-ERROR "Unable to load any of the alternatives:~%   ~S" ((:DEFAULT "libsqlite3") (:DEFAULT "sqlite3")))
0] 11
;
; compilation unit aborted
;   caught 2 fatal ERROR conditions
Makefile:101: recipe for target 'build/libs.stamp' failed
make: *** [build/libs.stamp] Error 1
```
Tried using option 1 with: ("libsqlite"), since that's what the package manager lists for version 3, instead of libsqlite3. Didn't work.

Tried patching: build/quicklisp/dists/quicklisp/software/cl-sqlite-20130615-git/sqlite-ffi.lisp and adding  (:default "libsqlite") to the list. That didn't work either.

**Comment by dimitri** [comment]
I think on windows the current working directory is by default in the path where it looks for the dll dependencies. Can you copy `libsqlite` there, and then also have a copy of it in the `./build/bin` directory where the `pgloader` binary is to be found?

It should then work, and then you might be able to figure out better _rules_ for the build and run-time environment and dependencies...

**Comment by jrpetit** [comment]
That's one of the places Windows looks. There's also a PATH variable and registry configurations as well as the Windows system folders. 

MSys2 creates all the usual root folders /usr/bin /usr/local /usr/local/bin etc.. and puts them in the PATH when you start a shell. Note: I'm using Msys2 because it's the best maintained UNIX build environment on Windows right now aside from cygwin (which is very heavy). Microsoft's recent introduction of a bash shell to Windows came requiring a lot of tweaking to make respectable so I uninstalled it.

Anyway, turns out the problem is library naming:

Msys2 installs sqlite libraries named msys-sqlite3-0.dll in /usr/bin 

Creating a symbolic link to that file called libsqlite3.dll in the same location fixed that build error. I didn't need to copy any files.

**Comment by dimitri** [comment]
Excellent, closing the issue then! Thanks for the detailed follow-up! Do you want to be enrolled as our windows binary maintainer, I guess we only need to distribute a .zip file containing `pgloader.exe` and the needed DLL in the same repository?

**Comment by isapir** [comment]
@jrpetit Can you please clarify where/how you created the symbolic link?  Did you use MSYS2's `ln` command?

I see `/usr/bin/msys-sqlite3-0.dll` when I run `pacman -Ql | grep sqlite` but am not sure where to link it to.

I would copy it over rather than link but it looks like there are about 30 different dlls with that prefix so I might need to copy all of them if that's the case.

@dimitri I'd be happy to share my binaries once I have them built.

**Comment by isapir** [comment]
Looks like the link is a simple:  `ln -s /usr/bin/msys-sqlite3-0.dll /usr/bin/libsqlite3.dll`

I can't install freetds on MSYS2 though, so now I'm getting an error 

    Unable to load foreign library (SYBDB).
    Error opening shared object "sybdb.dll":

**Comment by dimitri** [comment]
Doing a very quick search, I find https://docs.moodle.org/23/en/Installing_MSSQL_for_PHP ; is it possible that those FreeTDS drivers are what we need for pgloader on windows?
