### ISSUE TITLE
Default numbers for `workers` and `concurrency`?

### ISSUE THREAD

**Issue by alexanderad** [dimitri/pgloader#442]
I'm reading `A note on parallelism` in docs from new version (https://github.com/dimitri/pgloader/blob/master/pgloader.1.md#a-note-about-parallelism, btw, pgloader.io website still has old version of docs deployed) and I'm curious before I jump on board of testing `workers` and `concurrency` options, what are defaults values? Are they dynamic / static?

**Comment by dimitri** [comment]
Default values are currently 4 workers and concurrency of 1 with a database source, and 8 workers and concurrency of 2 with non-database sources. I will see about documenting that... also I've updated pgloader.io, thanks!

**Comment by alexanderad** [comment]
Thanks!
