### ISSUE TITLE
Ignoring certain fields

### ISSUE THREAD

**Issue by willcodeforfoo** [dimitri/pgloader#445]
Is it possible to ignore certain field types or names, just setting them to `NULL` or not including them in the new table altogether? I have several `LINESTRING` columns in a MySQL database that I'd rather import a different way then through pgloader, since it doesn't support them.

I looked through the various casting options, but didn't seem to find one that would just throw away the data...

**Comment by dimitri** [comment]
You could define a view `SELECT col1, col4 FROM source` on top of your tables and then play with `EXCLUDING` and `MATERIALIZE VIEWS` clauses to get what you want. This allows you to be more creative and use any SQL level transformation of the source data, too.

The real fix might be to just fix pgloader support for your columns, which doesn't sound too bad. Can you show me an example of line string data and needed output. I guess you would cast that to the PostgreSQL `path` datatype, or maybe it is more like a `polygon`? See https://www.postgresql.org/docs/9.5/static/datatype-geometric.html#DATATYPE-LINE.

See also https://github.com/dimitri/pgloader/blob/master/src/utils/transforms.lisp#L179 where we have support for the MySQL `point` datatype already.

**Comment by willcodeforfoo** [comment]
Thanks for the quick response! I'm sorry for the delay in responding, but I'm back on this endeavor of migrating our MySQL app to PostgreSQL!

The column in question is a LINESTRING one, and I intend to import into a Postgres database with PostGIS enabled.

A relevant value looks like this: `LINESTRING(-87.87342467651445 45.79684462673078,-87.87170806274479 45.802110434248966,-87.84492888794016 45.79732335706963,-87.84046569213925 45.79349339919981,-87.83703246459994 45.795887153715135,-87.82261290893646 45.7954084110377,-87.82261290893646 45.781523084289475,-87.82879271850615 45.7796075953549,-87.84115233764729 45.779128712838755,-87.85110869751074 45.78008647375808,-87.83737578735439 45.782001946240946,-87.84527221069374 45.78343850741725)` (in a text format called WKT).

My plan was rather than trying to import the geometry fields directly, I'd create text fields in Postgres to hold the WKT representation (which I can output from MySQL with `AsWKT(the_geom)` perhaps in a view), then [run a query in Postgres](http://postgis.net/docs/manual-2.3/using_postgis_dbmanagement.html#idm2006) to load those text values into the proper geometry column:

```
LOAD DATABASE
     FROM      mysql://root@localhost/vintageaerial_production
     INTO postgresql://kmarsh@localhost/vintageaerial_import_test_6

MATERIALIZE VIEWS rolls_import AS $$ SELECT id, AsWKT(the_geom) AS geom_import FROM rolls $$

INCLUDING ONLY TABLE NAMES MATCHING 'rolls_import'

ALTER TABLE NAMES MATCHING 'rolls_import' RENAME TO 'rolls'

BEFORE LOAD DO
  $$ CREATE EXTENSION postgis; $$

AFTER LOAD DO
  $$ ALTER TABLE rolls ADD COLUMN geom geometry(LINESTRING, 4326); $$,
  $$ UPDATE rolls SET geom = ST_GeomFromText(geom_import, 4326); $$,
  $$ ALTER TABLE rolls DROP COLUMN geom_import; $$

;
```

Seems to be working pretty well on some small scale tests I did.

(As an aside, it's funny how much bad data I'm finding that in MySQL was OK but PG won't put up with!)

Cheers for such a helpful tool!

**Comment by dimitri** [comment]
In https://github.com/dimitri/pgloader/blob/master/src/sources/mysql/mysql-schema.lisp#L336 we already use `astext()` function on MySQL *geometry* and *point* datatypes. It sounds possible and easy enough to add `AsWKT` for the *linestring* data type.

Thing is, I would like to output the data in a format compatible to PostgreSQL path datatype as shown in https://www.postgresql.org/docs/current/static/datatype-geometric.html. That sounds like a good general approach.

We could also think about PostGIS support out of the box, with PostGIS specific cast rules for geometry data types in MySQL, such as linestring. But then, where does the 4326 comes from?

**Comment by willcodeforfoo** [comment]
4326 refers to the spatial reference system the data is in, in this particular case [WGS84](http://spatialreference.org/ref/epsg/wgs-84/).

Would it be possible to write my own Lisp functions to create the proper column in the schema (e.g., MySQL `LINESTRING` → PostGIS `geometry(LINESTRING, 4326)`... I haven't seen an example of this) and row (this I think I have seen...)? I could take a stab at that, and if they are useful and general-purpose enough, submit a PR to include them. Are there examples of such anywhere? I imagine they are loaded with the `--load-lisp-file` option?

One drawback of my materialized view approach is losing the auto_increment primary key.

**Comment by dimitri** [comment]
It could be possible to use a CAST rule in your load command, but the parsing of the target type name is currently limited and won't support `geometry(linestring, 4326)`. We could fix that.

But then, writing a transformation function that takes WKT input and outputs a PostGIS geometry text input would mean rewriting `ST_GeomFromText` in Common Lisp, right?

What about using the following after load SQL instead:

```sql
      ALTER TABLE rolls
     ALTER COLUMN geom_import
             TYPE geometry(LINESTRING, 4326)
            USING ST_GeomFromText(geom_import, 4326);
```

**Comment by willcodeforfoo** [comment]
That makes sense, at this point I think I can achieve my migration by:

1. Writing a custom cast rule in Lisp to call `AsWKT()` on geometry fields (is it possible to extend `get-column-sql-expression` in a file passed to `--load-lisp-file`?)

2. Tell pgloader to create text fields for `linestring` fields with something like:

```
    (:source (:type "linestring")
     :target (:type "text")
     :using pgloader.transforms::convert-mysql-linestring)
```

3. Create the actual PostGIS geometry column/indices and perform the geometry-loading from text after migration

**Comment by dimitri** [comment]
Can you please try the attached patch, by building pgloader from (fresh) sources? I took the time to create a local test case then run it, it's working fine here and targets the PostgreSQL *path* datatype as documented at https://www.postgresql.org/docs/current/static/datatype-geometric.html#AEN7103.
