### ISSUE TITLE
'Killed' while importing from MySQL, foreign & primary keys missing

### ISSUE THREAD

**Issue by youkaihiei** [dimitri/pgloader#449]
Trying to import into postgres from mysql 5.7 I get 'Killed' as the output in the command line. When I check the database in pgAdmin, it looks like the data is imported, however when I try viewing the rows in the table it says theres no primary keys. Looking into it some more it doesn't look like the primary keys or foreign keys are set. I wouldn't be surprised if I'm missing some configuring somewhere.

The load file I'm using looks like this:

```
LOAD DATABASE  
     FROM      mysql://[user]:[pass]@localhost/[dbname] 
     INTO postgresql://[user]:[pass]@localhost/[dbname]

WITH no truncate, create tables, include drop, create indexes, reset sequences, foreign keys, downcase identifiers

SET maintenance_work_mem to '128MB', work_mem to '12MB', search_path to 'public'

CAST type datetime to timestamp drop default drop not null using zero-dates-to-null,
    type timestamp to timestamp using zero-dates-to-null,
     type date drop not null drop default using zero-dates-to-null,
     -- type tinyint to boolean using tinyint-to-boolean,
     type year to integer

BEFORE LOAD DO
$$ create schema if not exists public; $$;
```

**Comment by dimitri** [comment]
Try again without a load file to test with all-defaults options, and with a recent version of pgloader. Then if it happens again, I will need more details.

**Comment by youkaihiei** [comment]
I tried without the load file and got the same results. I built pgloader from the source, the result from the -V flag is:

pgloader version "3.3.d7d36c5"
compiled with SBCL 1.3.1.debian

What else do you need?

**Comment by dimitri** [comment]
Can you try also with a CCL (Clozure Common Lisp) build? it might be related to SBCL itself. There's no recipe to follow at this point really, you could try in `--debug` mode and send the traces, just in case, but in previous cases I couldn't see anything anyway...

**Comment by dimitri** [comment]
Closing for cleanup, open again if needed.
