### ISSUE TITLE
“Unable to load any of the alternatives” while installing

### ISSUE THREAD

**Issue by kadaztrof** [dimitri/pgloader#452]
Hello, I am currently trying to install pgloader (v.3.3.1) on a RedHat Enterprise Linux 6 machine with PostgreSQL 9.5.4. I have downloaded the tar.gz and extracted the files. As required, I use

```
make
```

while in the directory in order to build the program. Installing pgloader requires a Lisp compiler, so I use the current version of SBCL (1.2.7) for this purpose.
During the operation, I get an error concerning libssl alternatives, although I have the latest version of openssl installed on the system.

```
 [root@ebsvis122 pgloader-3.3.1]# make
sbcl --noinform --no-sysinit --no-userinit --load build/quicklisp/setup.lisp
         --eval '(push "/root/pgloader-3.3.1/" asdf:*central-registry*)'
         --eval '(ql:quickload "pgloader")'                     \
         --eval '(quit)'
To load "pgloader":
Load 1 ASDF system:
pgloader
; Loading "pgloader"
.....................
debugger invoked on a CFFI:LOAD-FOREIGN-LIBRARY-ERROR in thread
#<THREAD "main thread" RUNNING {AF43679}>:
Unable to load any of the alternatives:
  ("libssl.so.1.0.2" "libssl.so.1.0.1l" "libssl.so.1.0.1e"     "libssl.so.1.0.1j"
"libssl.so.1.0.1" "libssl.so.1.0.0q" "libssl.so.1.0.0" "libssl.so.0.9.8ze"
"libssl.so.0.9.8" "libssl.so" "libssl.so.4" "libssl.so.10")

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
0: [RETRY                        ] Try loading the foreign library again.
1: [USE-VALUE                    ] Use another library instead.
2: [TRY-RECOMPILING              ] Recompile reload and try loading it again
3: [RETRY                        ] Retry
                                 loading FASL for #<CL-SOURCE-FILE "cl+ssl"
4: [ACCEPT                       ] Continue, treating
                                 loading FASL for #<CL-SOURCE-FILE "cl+ssl"
                                 as having been successful.
5:                                 Retry ASDF operation.
6: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                 configuration.
7: [ABORT                        ] Give up on "pgloader"
8: [CONTINUE                     ] Ignore runtime option --eval "     (ql:quickload
9:                                 Skip rest of --eval and --load options.
10:                                 Skip to toplevel READ/EVAL/PRINT loop.
11: [EXIT                        ] Exit SBCL (calling #'EXIT, killing the     proc

(CFFI::FL-ERROR "Unable to load any of the alternatives:~%   ~S" 
("libssl.so.1.0.9.8ze" "libssl.so.0.9.8" "libssl.so" "libssl.so.4" "libssl.so.10"))
```

Whenever I choose Accept, Retry, or Continue, the installation keeps failing :(

I also tried different parameters while building the program, like

```
make DYNSIZE=2048 COMPRESS_CORE=no
```

but the error keeps popping.

**Comment by dimitri** [comment]
Can you make sure your system OpenSSL library is available in your `LD_LIBRARY_PATH` or equivalent setup? Some users have been able to symlink some .so files around and made it work.

**Comment by kadaztrof** [comment]
I have managed to add 3 directories in my `LD_LIBRARY_PATH` which returns now :
`[root@ebsvis122 openssl]# echo $LD_LIBRARY_PATH`
`/usr/local/lib:/usr/lib:/root/openssl`

I have added the /root/openssl directory, since this is the one which contains several .so :
`lrwxrwxrwx  1 root root      13 Oct  4 10:30 libssl.so -> libssl.so.1.1`
`-rwxr-xr-x  1 root root  517476 Oct  4 10:30 libssl.so.1.1`
`lrwxrwxrwx  1 root root      16 Oct  4 10:30 libcrypto.so -> libcrypto.so.1.1`
`-rwxr-xr-x  1 root root 2805192 Oct  4 10:30 libcrypto.so.1.1`

Unfortunally, the problem remains the same.
