### ISSUE TITLE
No "IF EXISTS" on "DROP TYPE"

### ISSUE THREAD

**Issue by fpietka** [dimitri/pgloader#453]
I upgraded pgloader to 3.3.1, and now I have issue on a `DROP TYPE ...`. Since the target DB is brand new I have no types for mysql enum, but since I read no `IF EXISTS`, I assume I'm missing something to do so.

Here are the logs from the event:
```
2016-10-05T09:17:19.258000Z NOTICE create schema if not exists encheres;
2016-10-05T09:17:20.468000Z NOTICE DROP then CREATE TABLES
2016-10-05T09:17:20.468000Z NOTICE DROP TYPE "contacts_type" CASCADE;
2016-10-05T09:17:20.468000Z ERROR Database error 42704: type "contacts_type" does not exist
QUERY: DROP TYPE "contacts_type" CASCADE;
2016-10-05T09:17:20.468000Z FATAL Failed to create the schema, see above.
```

Maybe I'm missing something really obvious?

**Comment by fpietka** [comment]
I must add that in debug mode I see a bunch of CAST on table not supposed to be included.

Here is my pgloader file:

```
LOAD database
     from mysql://user:password@1.1.1.1/encheres
     into postgresql://user:password@localhost/migration

 WITH include drop, create tables, no truncate,
      create indexes, reset sequences, foreign keys,
      batch rows = 5000

  SET maintenance_work_mem to '128MB', work_mem to '12MB', search_path to 'encheres'

 CAST type datetime to timestamptz
                drop default drop not null using zero-dates-to-null,
      type date drop not null drop default using zero-dates-to-null,
      type enum to text drop not null using empty-string-to-null

 INCLUDING ONLY TABLE NAMES MATCHING 'articles', 'contacts'

 BEFORE LOAD DO
 $$ create schema if not exists encheres; $$;
```

**Comment by fpietka** [comment]
Solved my matching issue using `~/^articles$/`, but still have issue trying to drop types that aren't there...

**Comment by fpietka** [comment]
I grabbed the 3.2.1 from your releases (pgloader_3.2.1.preview.dfsg-2_amd64.deb), and it works (it has the `IF EXISTS`)

**Comment by dimitri** [comment]
See https://github.com/dimitri/pgloader/commit/5b6adb02b090081ef4a448f0f1b3d36561d57a18

You might prefer building a new version from sources, which should fix your current problem.

**Comment by fpietka** [comment]
Ok, thank you (didn't look in the master's commits...)

**Comment by dimitri** [comment]
No problem, thanks for the report!

**Comment by alasdairdc** [comment]
Just came across this myself using the debian (stable) packaged version 3.3.1+dfsg-1~pgdg80+1

Incase anyone comes here and wants to stay on the packaged version the current workaround is to use the following in your loader script for every enum you have:

```
before load do $$

    DROP TYPE IF EXISTS typename_reported_in_error;

$ do $$
 
    CREATE TYPE typename_reported_in_error AS ENUM ('');

$$

This will drop the type if it exists (what https://github.com/dimitri/pgloader/commit/5b6adb02b090081ef4a448f0f1b3d36561d57a18 reintroduces) then create a dummy type so pgloader can properly drop it.

**Comment by fpietka** [comment]
@alasdairdc clever

**Comment by alasdairdc** [comment]
Thinking theres other issues with the current stable build though, cloning master to see if they are still present before posting.

**Comment by grinapo** [comment]
@alasdairdc thanks for the hack fix; I would like to comment that it doesn't work that way, but 

```
BEFORE LOAD DO
 $$ DROP TYPE IF EXISTS problematic1; $$,
 $$ CREATE TYPE problematic1 AS ENUM (''); $$,
 $$ DROP TYPE IF EXISTS problematic2; $$,
 $$ CREATE TYPE problematic2 AS ENUM (''); $$;
```

It is probably obvious for everyone but those who google for the problem and the above dies with cryptic syntax errors. :-) 
(Also worth noting that with just a few enums the amount of problems is the enums multiplied by all their usage, may be an impressive list. I hope the debian package will be updated soon.)

**Comment by alasdairdc** [comment]
@grinapo Cheers for the update. If you're having problems with the Debian version you really should try compiling it yourself.  You may also experience issues that are really only overcome by using `CCL`
