### ISSUE TITLE
pgloader fails for schema qualified tables

### ISSUE THREAD

**Issue by jcharliervermeire** [dimitri/pgloader#457]
I receive the following error (the names have been changed to protect the innocent) while trying to load a csv into postgres.  It seems that pgloader adds parentheses around a schema qualified table name which then fails on the conversion to a regclass.

```
2016-10-17T15:24:38.019000Z NOTICE Starting pgloader, log system is ready.
2016-10-17T15:24:38.031000Z LOG Main logs in '/tmp/pgloader/pgloader.log'
2016-10-17T15:24:38.033000Z LOG Data errors in '/tmp/pgloader/'
2016-10-17T15:24:38.234000Z ERROR Database error 3F000: schema "(my" does not exist
QUERY: 
    select attname
      from pg_class c
           join pg_namespace n on n.oid = c.relnamespace
           left join pg_attribute a on c.oid = a.attrelid
           join pg_type t on t.oid = a.atttypid
     where c.oid = '(my . table)'::regclass and attnum > 0
  order by attnum
2016-10-17T15:24:38.234000Z FATAL We have a situation here.
```

Here is the terminal command (again, names are changed):

```
pgloader --type csv --field "a,list,of,columns,that,are,in,the,file" --with truncate --with "fields terminated by ','" ./my_table.csv postgresql://iamauser:Th1s!Sm4P@ssw0rd@localhost:5432/db_ultra?tablename=my.table
```

**Comment by jcharliervermeire** [comment]
This also occurs when trying to load from a script file:

2016-10-17T15:47:53.031000Z LOG Main logs in '/tmp/pgloader/pgloader.log'
2016-10-17T15:47:53.034000Z LOG Data errors in '/tmp/pgloader/'
2016-10-17T15:47:53.034000Z LOG Parsing commands from file #P"/home/me/Documents/SQL/load_csv_my_table.pgloader"
An unhandled error condition has been signalled:
   Database error 3F000: schema "(my" does not exist
QUERY: 
    select attname
      from pg_class c
           join pg_namespace n on n.oid = c.relnamespace
           left join pg_attribute a on c.oid = a.attrelid
           join pg_type t on t.oid = a.atttypid
     where c.oid = '(my . table)'::regclass and attnum > 0
  order by attnum

2016-10-17T15:47:53.234000Z ERROR Database error 3F000: schema "(my" does not exist
QUERY: 
    select attname
      from pg_class c
           join pg_namespace n on n.oid = c.relnamespace
           left join pg_attribute a on c.oid = a.attrelid
           join pg_type t on t.oid = a.atttypid
     where c.oid = '(my . table)'::regclass and attnum > 0
  order by attnum
2016-10-17T15:47:53.234000Z FATAL We have a situation here.

**Comment by dimitri** [comment]
It seems like you're using an old version of pgloader, for all I can see this has been fixed a while ago already... Can you share your `pgloader --version` and then either try 3.3.1 or build from current tree?

**Comment by jcharliervermeire** [comment]
ah ha. that would do it.  I installed it from the default repo on ubuntu.  Should have payed more attention.

Version is 3.2.2

I'll pull from gh and build if I need to.

**Comment by jcharliervermeire** [comment]
That fixed the issue.  Thanks.
