### ISSUE TITLE
.pgpass not supported

### ISSUE THREAD

**Issue by piercej** [dimitri/pgloader#460]
we need pgpass support or equivalent in pgloader, putting a plaintext password in the environment variable PGPASSWORD is insecure, it can be viewed via ps on many OS's.

**Comment by dimitri** [comment]
Hi, the `.pgass` solution is implemented in `libpq`, the C library to talk to PostgreSQL. We're not using that in pgloader yet. I will see about making it happen, unless you want to contribute the feature?
