### ISSUE TITLE
An error is coming while runnning multiple commands in load file  

### ISSUE THREAD

**Issue by navengp** [dimitri/pgloader#461]
Hi
I have created sakila.load file which look like this 

```
load database
     from      mysql://root:sqlpwd@localhost/IIPCOREDB
     into postgresql://postgres@localhost/demo_postgre

BEFORE LOAD
 DO $$create schema if not exists demo_postgre $$;

 DO $$DROP DATABASE IF EXISTS demo_postgre $$;

 DO $$create database demo_postgre $$;
```

but when try to run pgloader sakila.load 

i am getting the following error

```
An unhandled error condition has been signalled: At


   DO $$DROP DATABASE IF EX
   ^ (Line 8, Column 1, Position 198)

In context COMMANDS:

While parsing COMMANDS. Expected:

     the character Tab
  or the character Newline
  or the character Return
  or the character Space
  or the string "--"
  or the string "/*"
  or the string "load"
```

can you suggest me,How can i get rid of this because i want to run multiple querie in BEFORE LOAD clause

Regards
Naveen

**Comment by navengp** [comment]
some i have removed the above error but, i got differnet error this time 

DROP DATABASE cannot run inside a transaction block
QUERY: DROP DATABASE IF EXISTS demo_postgre;

my sakil.load file is

load database
     from      mysql://root:sqlpwd@localhost/IIPCOREDB
     into postgresql://postgres@localhost/demo_postgre
BEFORE LOAD DO
 $$ DROP DATABASE IF EXISTS demo_postgre; $$,
 $$ create schema if not exists demo_postgre; $$,
 $$ create database demo_postgre; $$;
 can you suggest any other solution

**Comment by dimitri** [comment]
You found the proper fix for your syntax problem (commas, not semi-colons). For the `DROP DATABASE` you just can't do that from the pgloader `BEFORE LOAD` command block, check PostgreSQL documentation for details (basically you need to connect to another database to be able to do that, and you can't be in a transaction).
