### ISSUE TITLE
Unable to build from source

### ISSUE THREAD

**Issue by dxk3355** [dimitri/pgloader#465]
Whenever I try to build from source I'm getting stuck at this point, it looks like the version of ASDF being pull is out of date.
[output.txt](https://github.com/dimitri/pgloader/files/542260/output.txt)

**Comment by dxk3355** [comment]
I was able to work around that by replacing the ASDF.lisp file, but that results in qmynd missing.

**Comment by dimitri** [comment]
The error message you get is pretty specific:
```
You need ASDF >= 3.1 to load this system correctly.
```

ASDF is usually integrated into the CL system you're using (either SBCL or CCL here I suppose), what version do you have? Can you try again with a recent enough version of SBCL / CCL ?
