### ISSUE TITLE
Compilation failed in src/parsers/command-alter-table.lisp

### ISSUE THREAD

**Issue by mltsy** [dimitri/pgloader#466]
I'm trying to build from source to get around the `this is incompatible with sql_mode=only_full_group_by` error, but I get this error in compilation:

```
build/bin/buildapp.sbcl      --logfile /tmp/build.log                \
                         --require sb-posix --require sb-bsd-sockets --require sb-rotate-byte                        \
                         --sbcl sbcl                            \
                         --asdf-path .                           \
                         --asdf-tree build/quicklisp/local-projects     \
                         --manifest-file build/manifest.ql             \
                         --asdf-tree build/quicklisp/dists              \
                         --asdf-path .                           \
                         --load-system pgloader               \
                         --load src/hooks.lisp                   \
                         --entry pgloader:main                   \
                         --dynamic-space-size 4096         \
                         --compress-core                    \
                         --output build/bin/pgloader.tmp
;; loading system "pgloader"
Fatal SIMPLE-ERROR:
  Compilation failed: :TYPE and :TARGET are not a known argument keywords. in /opt/pgloader-master/src/parsers/command-alter-table.lisp
Makefile:133: recipe for target 'build/bin/pgloader' failed
make: *** [build/bin/pgloader] Error 1
```

According to `/tmp/build.log`, it failed during:

```
; compiling (DEFRULE ALTER-SCHEMA-RENAME-TO ...)
While evaluating the form starting at line 21, column 0
  of #P"/opt/pgloader-master/dumper-2SKVI5f7.lisp":Fatal SIMPLE-ERROR:
  Compilation failed: :TYPE and :TARGET are not a known argument keywords. in /opt/pgloader-master/src/parsers/command-alter-table.lisp
```

 so I'm assuming this is the line it's referring to: https://github.com/dimitri/pgloader/blob/master/src/parsers/command-alter-table.lisp#L77

I don't know the first thing about lisp... This is the only other place in the repo I found `make-match-rule` and it appears to be commented out, so I'm stumped: https://github.com/dimitri/pgloader/blob/master/src/utils/alter-table.lisp#L24

Any ideas?

**Comment by dimitri** [comment]
Have you tried to `make clean` and build again? Other than that the `only_full_group_by` should have been fixed already, see https://github.com/dimitri/pgloader/commit/44b9ec81c9becdbd55f3981988084ffd82de240d.

**Comment by mltsy** [comment]
Right!  I'm just building form source because the apt package for Ubuntu doesn't have the new version yet with that fix.  I haven't changed the source code at all (which is why I was surprised it wouldn't compile)!
I tried `make clean` and `make pgloader` again and got the same error.  Very strange.  I've figured out another way to migrate my database, but if you want any more info, let me know! :)

**Comment by dimitri** [comment]
I could reproduce here after a `make clean`, so here's a fix for your to build pgloader from current sources. Sorry about having broken the build without noticing :(

**Comment by mltsy** [comment]
Aha!  Awesome, thanks for the update :)

**Comment by manibollu** [comment]
dvc
