### ISSUE TITLE
Not data option for specific tables

### ISSUE THREAD

**Issue by alasdairdc** [dimitri/pgloader#467]
I was looking for a way to to import from MySQL but not import the data for specific (log) tables and am struggling to find a way, i.e. import all tables and data except the data for table_x but still create the structure for table_x.

Came across this https://github.com/dimitri/pgloader/issues/316 issue suggesting I can use materialize views.

so came up with this extract of the load file.

```
EXCLUDING TABLE NAMES MATCHING 'a_log', 'b_log'

MATERIALIZE VIEWS a_log_empty as $$
       select * from a_log where 1=0;
$$

MATERIALIZE VIEWS b_log_empty as $$
       select * from b_log where 1=0;
$$

after load do $$
    ALTER TABLE a_log_empty RENAME TO a_log;
$$ do $$
    ALTER TABLE b_log_empty RENAME TO b_log;
$$
```

however it seems to ignore the second `MATERIALIZE VIEWS` statement.
1. What should the correct syntax for multiple `MATERIALIZE VIEWS` be?  
2. Is there an easier / batter way to restrict importing the data from certain tables?

Obviously not wanting to import then truncate due to the size of these log tables.

**Comment by dimitri** [comment]
Try the following:

```
MATERIALIZE VIEWS
    a_log_empty as $$ select * from a_log where 1=0; $$,
    b_log_empty as $$ select * from b_log where 1=0; $$
```

Other than that, we don't yet have an option to choose _data only_ or _schema only_ per table. Maybe we need that tho. Do you want to contribute the feature?

**Comment by alasdairdc** [comment]
Yep that syntax works fine. Thank You.

I think per-table _data only_ or _schema only_ would be a nice-to-have as excluding the tables, creating empty materialized views for the structure, then renaming these to the original table name seems quite cumbersome.  It does work though.

My lisp knowledge is effectively non-existant but I will take a look when I have the time.

**Comment by dimitri** [comment]
Thanks! If you need any guidance, please feel free to ask here or on the #lisp channel on the FreeNode IRC channel.

**Comment by dimitri** [comment]
Actually, you can rename the Materialized Views right into the pgloader command, so it's not that bad. On reviewing the idea, I don't think that adding per-table *schema only* or *data only* options is a good idea: getting those options right has been more work than anticipated...

```
MATERIALIZE VIEWS
    a_log_empty as $$ select * from a_log where 1=0; $$,
    b_log_empty as $$ select * from b_log where 1=0; $$

ALTER TABLE 'a_log_empty' RENAME TO 'a'
ALTER TABLE 'b_log_empty' RENAME TO 'b'
```
