### ISSUE TITLE
Cannot transfer table from MSSQL to Postgres

### ISSUE THREAD

**Issue by Charmatzis** [dimitri/pgloader#468]
Hi, and great job.

I have been working on a solution for transferring data from one table in MSSQL to Postgres.

My load file is smth like that 

```
load database
 from mssql://my connection to DB
 INTO postgresql://my connection to DB


SET client_encoding to 'latin1'


including only table names like 'my table' in schema 'dbo'
ALTER SCHEMA 'dbo' RENAME TO 'public';

set work_mem to '16MB', maintenance_work_mem to '512 MB';

```

besides I am using the last version of pgloader and I have successfully insert data from csv to postgres and the --try-dry can connect successfully. 

the issue is there 

```
9: ((LAMBDA ()))
10: (PGLOADER:RUN-COMMANDS #P"/opt/src/pgloader-3.3.1/build/bin/pgloader.load" :START-LOGGER NIL :SUMMARY NIL :LOG-FILENAME NIL :LOG-MIN-MESSAGES NIL :CLIENT-MIN-MESSAGES NIL)
11: ((FLET #:CLEANUP-FUN-269 :IN PGLOADER::MAIN)) [cleanup]
12: (PGLOADER::MAIN ("./pgloader" "--verbose" "--debug" "pgloader.load"))
13: ((LAMBDA NIL :IN "/opt/src/pgloader-3.3.1/dumper-2SKVI5f7.lisp"))
14: ((FLET #:WITHOUT-INTERRUPTS-BODY-86 :IN SAVE-LISP-AND-DIE))
15: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))

An unhandled error condition has been signalled: %dbsqlexec fail

Date/time: 2016-10-25-15:21An unhandled error condition has been signalled:
                              %dbsqlexec fail


Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1006ED6B43}>
0: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE-TO-STREAM #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDOUT* {1000275D13}>)
1: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE %dbsqlexec fail :OUTPUT #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDOUT* {1000275D13}> :IF-EXISTS :APPEND :VERBOSE T)
2: ((FLET #:CLEANUP-FUN-269 :IN PGLOADER::MAIN)) [cleanup]
3: (PGLOADER::MAIN ("./pgloader" "--verbose" "--debug" "pgloader.load"))
4: ((LAMBDA NIL :IN "/opt/src/pgloader-3.3.1/dumper-2SKVI5f7.lisp"))
5: ((FLET #:WITHOUT-INTERRUPTS-BODY-86 :IN SAVE-LISP-AND-DIE))
6: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))
```

Thank you for your time,
X.

**Comment by dimitri** [comment]
Hi, what version of MS SQL are you running? and of pgloader? In recent enough version of pgloader and using `--debug` you should have the query it wants to execute printed in the logs...

**Comment by Charmatzis** [comment]
Hi, I am working on MSSQL 2014 and Postgres 9.5 . pgloader version is the latest I have compile it from source. The query that the log prints, are valid but I believe there is a problem with mapping the field with the right encoding. Eg, I have one table with one field INTEGER and even that table can't copy it to postgres.

**Comment by dimitri** [comment]
When you say the query are valid, does it mean you can copy/paste them to your usual MS SQL query tool and have the expected results? I also have a hard time understanding the _encoding_ problem with `integer` fields. Is it possible for you to give me more information?

**Comment by Charmatzis** [comment]
Well, now I have turned to other migration solution, because of luck of time. I will return when I have time.

Thank you very much for the support and keep up the good job!
