### ISSUE TITLE
Fields name mapping don't work

### ISSUE THREAD

**Issue by slardiere** [dimitri/pgloader#470]
Trying to load a fixed files with lots of fields, i have to "map" fields from the file to the actual name, as shown in the following example : http://pgloader.io/howto/fixed.html 

partly from the url updated : (http://www2.census.gov/geo/docs/maps-data/data/gazetteer/places2k.zip)

I got this error :

```
2016-10-27T17:02:37.469000+02:00 FATAL Can't init COPY to places("usps", "fips", "fips_code", "LocationName"): 
Database error 42703: column "LocationName" of relation "places" does not exist
```

from the example, LocationName is loc_name in the table. 

I want a way to map fields name from file to table.

pgloader version "3.3.43bb879"

**Comment by dimitri** [comment]
Have you tried the following test case provided with pgloader? Does it handle your situation well enough?

  https://github.com/dimitri/pgloader/blob/master/test/census-places.load

I'm not sure what you want exactly here, please give me an example of input and expected behavior / output. Thanks.

**Comment by slardiere** [comment]
The use case is very simple : to use different field names from the file definition and table 

In the http://pgloader.io/howto/fixed.html example, It's seems possible, but it don't work. In your test file, names are not different, so, it probably works, but it's not that I need. 

I think that you should merge the example in the web page  http://pgloader.io/howto/fixed.html with your test case. 

My use case come from a file provided by legacy system, which has bill tuples in one line, that i want to use, something like : 

`
BillID0000BillTuple010000000BillTuple020000000BillTuple030000000BillTuple040000000
`

the bill tuple fields are repeated (51 tuples), each tuple contains 10 fields, and I need to load these tuple in one table. 

Currently, I produce a file with each fields identified by a unique name, like tupleNfieldM, and I want to use this generated field name inside the INTO section.

So, It seems that it's not possible today. 

I can provide sample data in private.

**Comment by dimitri** [comment]
Yeah your use case isn't supported today, the field names are created in the load command itself: file content is not expected to contain the field names, we only need them to map them into PostgreSQL table columns. Can you use your target columns names as fields names?

My understanding is that the best way for you to fix this given current existing code is to generate the load file with the generated field names.

**Comment by dimitri** [comment]
I think https://github.com/dimitri/pgloader/commit/b1d55e07d665333fb039be18e6ded7b20f48f851 solves the issue here, or should help. Closing now. Please re-open if more actions are needed.
