### ISSUE TITLE
Wishlist: Simple variable substitution in command file

### ISSUE THREAD

**Issue by a-mckinley** [dimitri/pgloader#477]
Hi Dmitri,

I have just started trying pgloader and would really like the capability to do variable substitution as you can with psql using the ":variable" and psql -v variable="something" notation.  Is this something you have considered?

**Comment by dimitri** [comment]
Hi,

Thanks for the idea, which I didn't consider. The path is slippery for the load command syntax to allow for a turing complete (mini) language, and I'm not good enough at programming language design for me to want to do that...

My current thinking is that you probably should consider using a templating solution to generate your load commands and only then give them to pgloader. I guess that when you need the variable substitution in the load command you reach a complex enough setup that having the commands a generated product in your multi-stage command set is not a lot to swallow...

**Comment by a-mckinley** [comment]
Hi Dimitri,

Thanks for your response and thanks for all of your efforts in pgloader, it is really impressive software.  

I have a data warehouse building bash script that calls a number of other psql scripts, which are parameterised simply with the psql -v notation.  This means I can reuse the same scripts that act of different partitions of the table.

I recently switched to loading with pgloader (because of its awesome features and performance!) to deal with bad data on the fly and to speed up loading performance.

It is nice in pgloader to be able to use the GETENV syntax for the file input and table name (I can fill in the partition name this way), the issue is that if I want to capture some sql for table creation,index creation,table updates etc.  I think it would be fantastic to capture the entire life cycle of each partition inside a parameterised pgloader script.

I don't think it necessarily requires a mini-language to be useful.  In the simplified example below I could reuse the same pgloader command file for multiple input files and partitions.

Maybe it would be ok to just do a search and replace for tokens starting with ":" before parsing?

E.g.

```sql
LOAD CSV 
    FROM :my_input_file with encoding 'LATIN1'
    (   
        col1,
        col2
    )   
    INTO :my_partition
    TARGET COLUMNS (
        col1,
        col2
    )   
    WITH truncate,
        fields terminated by ',';
    
    
BEFORE LOAD DO
     $$ create table if not exists :my_table  
        (
            col1 INTEGER,
            col2 INTEGER
        )
     $$, 
     $$ create table if not exists :my_partition :my_check inherits (:my_table) $$, 
     $$ create index index1 on :my_partition (col1) $$ ;
```

**Comment by dimitri** [comment]
Hi, thanks for your detailed comment and example. I think the best way to address your problem here is to produce the load command file from a template using e.g. awk. 

When I see your example I can't help but think that the next step involves being able to define conditional parts of the command, then maybe have parts that depend on some other parts. In other words variables and logic ; or a programming language.

If you fancy doing advanced stuff that way, please note that you can write an application in Common Lisp that would use pgloader as a library. Given ABCL it might even be possible to do that in Java.

**Comment by fare** [comment]
Instead of awk to produce the load command, I recommend Common Lisp :-)
