### ISSUE TITLE
"Database error 53300: remaining connection slots are reserved"

### ISSUE THREAD

**Issue by otheus** [dimitri/pgloader#481]
I'm doing an import from mysql to postgres. The postgres database has a limit of 10 connections, which is enough for normal operation, but for some reason, not enough for pgloader...

```
ERROR Failed to connect to #<PGSQL-CONNECTION pgsql://openproject_ce@XXXX:5432/openproject_ce {100C778023}>: Database error 53300: remaining connection slots are reserved for non-replication superuser connections; will try again in 0.5s
```

Nothing else was connected to the database at the time. Are you trying dozens of parallel connections?

**Comment by dimitri** [comment]
Yes, the number of connection depend on the specific parallel level you've picked, and how many indexes you have on the table where you have the greatest number of them. I've been reported of cases with hundreds of indexes, thus hundreds of connections trying to allocate each 1GB of memory...

Please read the docs again and setup the limits according to your environment!

**Comment by otheus** [comment]
Your documentation is in general excellent, but this section "A note about parallelization" is a little weak.  That's some "note"!  First, no where in the parallel section does it say it creates n _connections_ to the database; just that it starts n _tasks_.  Second, the section as a whole seems to require a level of familiarity with the internals of the tool that I shouldn't need to understand. It's also quite complex. I mean, I've read it 3 times, but I really don't understand the point.

> By default, as many CREATE INDEX threads as the maximum number of indexes per table are found in your source schema. It is possible to set the max parallel create index WITH option to another number in case there's just too many of them to create.

I guess this is what you're alluding to, but I think if you read it again, you'll realize why it bears no obvious relation to my problem. :)

**Comment by dimitri** [comment]
Is it possible for you to propose a patch rewording the docs on those parts? I take your point that we need a better documentation here... and would appreciate some help.
