### ISSUE TITLE
Incorrect/misleading warning message on import of missing tables

### ISSUE THREAD

**Issue by otheus** [dimitri/pgloader#482]
When running a pgloader of mysql-postgresql, on a newly created database, I get errors like

```
2016-11-11T17:42:40.029000Z WARNING PostgreSQL warning: table "wiki_content_versions" does not exist, skipping
```

for all the tables. Is that an error in the implementation (that it tries to create the table twice)? Or the warning message?

**Comment by dimitri** [comment]
It's an expected error message because with default options we issue `DROP TABLE ... IF EXISTS` commands, and PostgreSQL is kind enough to inform us that the table indeed doesn't exists yet.

**Comment by otheus** [comment]
OK, yeah, that confusing message is postgresql's fault. 

You can squelch this warning by issuing

     SET session client_min_messages=warning

in each connection/session that might do something like this. Even though the error above reports "WARNING", it's acutally at the NOTICE level. Cheers

**Comment by dimitri** [comment]
You can use the `--quiet` option of pgloader to that end... I didn't want to change PostgreSQL severity of messages in pgloader logs...
