### ISSUE TITLE
The value of LPARALLEL.KERNEL::WORKER-COUNT is 0, which is not of type (INTEGER 1 4611686018427387903).

### ISSUE THREAD

**Issue by mnemonicflow** [dimitri/pgloader#484]
Hello,

Any ideas about this error? Why it happens? What are the consequences? Can I ignore it?
The data seems to be imported correctly.

When I run the following:
`PGPASSWORD='pass' PGUSER=user PGHOST='host' PGDATABASE=db pgloader --verbose --type csv --field f1 --field f2 --field f3 --field f4 --field f5 --with 'disable triggers' --with 'drop indexes' --with truncate --with "fields terminated by ','" file.txt 'postgresql:///user?tablename=mytable'`
The output at the end is this:
```
An unhandled error condition has been signalled:
   The value of LPARALLEL.KERNEL::WORKER-COUNT is 0, which is not of type (INTEGER
                                                                           1
                                                                           4611686018427387903).

An unhandled error condition has been signalled:
   The value of LPARALLEL.KERNEL::WORKER-COUNT is 0, which is not of type (INTEGER
                                                                           1
                                                                           4611686018427387903).
```

with
```
pgloader-docker --version
pgloader version "3.3.0.51~devel"
compiled with SBCL 1.2.4.debian

uname -a
Linux milkyway 4.2.0-42-generic #49-Ubuntu SMP Tue Jun 28 21:26:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

Built from the latest Docker image. 
But the same happens with the latest package from the repo on Debian
```
Package: pgloader
Version: 3.3.1+dfsg-1~pgdg15.10+1
Architecture: amd64
```

I've imported the same data in the past and haven't noticed this error, something changed recently.

**Comment by dimitri** [comment]
Please consider building from source and trying again. Thanks to your detailed report I could reproduce the problem locally then fix it here.

**Comment by mnemonicflow** [comment]
Thanks! Your commit fixes the problem!
I've recently removed the index and added it to the primary key and forgot to remove the `--with 'drop indexes'` option when running pgloader.
