### ISSUE TITLE
Document MySQL credential environment variable support

### ISSUE THREAD

**Issue by ldcasillas-progreso** [dimitri/pgloader#485]
The documentation currently does not say very clearly what are the options to provide host, username and password for a MySQL source.  The code, however, shows that some standard MySQL environment variables are supported:

* https://github.com/dimitri/pgloader/blob/8fb542bc902c20fb20cda7ca4c8d0482015579c4/src/parsers/command-mysql.lisp#L101

This should be documented.

**Comment by dimitri** [comment]
Would you consider contributing a documentation patch to that end?
