### ISSUE TITLE
MSSQL - can't connect

### ISSUE THREAD

**Issue by randomee** [dimitri/pgloader#488]
I'm trying to setup a pgloader config to read directly from a MSSQL instance.  I can connect via sqsh and tsql fine.  

since I believe pgloader is using freetds/tsql underneath, i figure testing w/ tsql is a good check. I know this command works:

```
tsql -S 10.100.1.10 -H 10.100.1.10 -U dbuser -D dbname -P blah -p 1433
```

but this pgloader config does not
```
     from mssql://dbuser:blah@10.100.1.10:/dbname
```

I get this error:
```
2016-12-05T23:46:36.451000+03:00 FATAL An unhandled error condition has been signalled:
   Failed to connect to mssql at "10.100.1.10" (port 1433) as user "dbuser": Connection to the database failed for an unknown reason.
```

**Comment by randomee** [comment]
Looking at strace, it looks like it connects, and negotiates the SSL, then dies?  Unclear if it's failing SSL, or password.  

I tried to use ltrace as well, but pgloader catches it, and goes into ldb.

The password does have punctuation in it (e.g. ? &).  I've escaping (\) and quoting (" '), but no change.  

Any thoughts on what to try next?

**Comment by dimitri** [comment]
You need only to escape `@` and `:` in the password, by doubling the character, so that `@` becomes `@@` and `:` becomes `::`. See the docs about that.

**Comment by xenu256** [comment]
+1
