### ISSUE TITLE
 Unknown Code Page "01208"

### ISSUE THREAD

**Issue by Meier123** [dimitri/pgloader#491]
Hello Dimitri,

i installed the pgloader using apt-get install ...
After a successful Installation i wanted to load an ixf file and get the error:

```
2016-12-12T14:22:54.115000Z LOG Main logs in '/tmp/pgloader/pgloader.log'
2016-12-12T14:22:54.124000Z LOG Data errors in '/tmp/pgloader/'
2016-12-12T14:22:54.124000Z LOG Parsing commands from file #P"/home/inst2/pgloader/ixfload.load"
An unhandled error condition has been signalled: Unknown Code Page "01208"

An unhandled error condition has been signalled: Unknown Code Page "01208"
```
That is the command inside my loadfile: 

```
LOAD IXF from /home/itgain/blob/blob.ixf into postgresql://127.0.0.1:5430/blobtest?public.blobtest with truncate ;
```

I tried to use --Encoding but it does not work. It is ignored while loading:

```
2016-12-12T14:25:37.049000Z LOG Main logs in '/tmp/pgloader/pgloader.log'
2016-12-12T14:25:37.059000Z LOG Data errors in '/tmp/pgloader/'
2016-12-12T14:25:37.059000Z FATAL Option "--encoding" is ignored when using a load file
```

Do you have any clue what to do, to solve that issue ?

Thank you very much for your time and your help.

best regards

Meier

**Comment by dimitri** [comment]
The encoding is a property of the IXF file, and the code page 01208 seems not to be recognized by pgloader... meaning SBCL here really. Is it possible for you to change the encoding in which your input file has been produced?

**Comment by Meier123** [comment]
Hello Dimitri,

thanks for your fast Reply. The weird Thing is, codpage 1208 is UTF-8. Thats why i wonder that ist not working. When i enter an Encoding (UTF-8) for the load, the pgloader says, it cant be encoded while iam using a file, where the COPY command is saved in.

**Comment by Meier123** [comment]
I tried to Change the Export to another Formats, which produces the following message:

`An unhandled error condition has been signalled:
   IXF Type mapping unknown for: 404
`

**Comment by dimitri** [comment]
The encoding list is maintained in the cl-ixf package, see https://github.com/dimitri/cl-ixf/blob/master/encodings.lisp ; which doesn't contain `01208`. Can you try a local build of pgloader with a local version of cl-ixf edited to add `01208` as an encoding?

If that works we'll update the cl-ixf *driver* then next version of pgloader will benefit.

**Comment by Meier123** [comment]
I saw, that u have an Encoding 01209 which is UTF-8. Are you sure, u ment 01209? Because the Encoding 01208 is UTF-8

**Comment by dimitri** [comment]
See the IBM reference for code pages at  http://www-01.ibm.com/software/globalization/ccsid/ccsid_registered.html ; where you will see that 1208 is *UTF-8 with IBM PUA* (and I don't know what this means), and 1209 just UTF-8.

**Comment by Meier123** [comment]
Good Morning Dimitri,

thanks for your help so far. I will try and add the Codepage to the cl-ixf package.
There is only 1 Problem ^^ I cant find it. can you tell me the Location ?

Thanks a lot

**Comment by ChristophBerg** [comment]
My guess is it's at https://github.com/dimitri/cl-ixf/blob/master/encodings.lisp.

**Comment by Meier123** [comment]
Hello Christoph,

i already received the link from Dimitri. This Package/Lisp should be somewhere in the Installation package right ? And i dont know where to find it there, to edit it.

**Comment by ChristophBerg** [comment]
After `apt-get install cl-ixf` (or `apt-get build-dep pgloader`) the file is at `/usr/share/common-lisp/source/ixf/encodings.lisp`.

**Comment by ChristophBerg** [comment]
I was curious so I digged up what "PUA" means, it's "private use area":

> “IBM codepage (not CCSID) 1449 assigns IBM-specific characters to U+F83D..U+F8FF (the last 195 BMP-PUA code points)” [Markus Scherer, Unicode List, 2003-4-24]

http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=VendorUseOfPUA

**Comment by Meier123** [comment]
Thanks for your help.

I installed the package, edited the Encoding.lisp and added:
("01208" . :UTF-8)
I tried again to load the ixf file, but i get the same error message:

`An unhandled error condition has been signalled: Unknown Code Page "01208"`

It seems like the Encoding.lisp is not used ? Just for my interest: After the Installation of the cl-ixf package, the Encoding list is used as Standard for the pgloader?

**Comment by ChristophBerg** [comment]
You need to recompile pgloader for that.

**Comment by Meier123** [comment]
Well, i reinstalled it using apt-get. Isn't that the same somehow ?

**Comment by ChristophBerg** [comment]
No, pgloader.deb ships a precompiled binary. It doesn't need anything from the cl-* packages; these are only used when actually compiling it.

```
apt-get source pgloader
apt-get build-dep pgloader
... edit /usr/share/common-lisp/source/ixf/encodings.lisp
dpkg-buildpackage
dpkg -i pgloader*.deb
```

**Comment by Meier123** [comment]
Thanks for your fast Reply.

I tried it and get an error while 

`;; loading system "pgloader"`

The Error message:

`;; loading system "pgloader"
Fatal COMPILE-FILE-ERROR:
  COMPILE-FILE-ERROR while
  compiling #<CL-SOURCE-FILE "pgloader" "src" "sources" "ixf" "ixf-schema">
debian/rules:31: die Regel für Ziel „override_dh_auto_build“ scheiterte
make[1]: *** [override_dh_auto_build] Fehler 1
make[1]: Verzeichnis „/home/inst2/pgloader/pgloader_dev/pgloader-3.3.2+dfsg“ wird verlassen
debian/rules:55: die Regel für Ziel „build“ scheiterte
make: *** [build] Fehler 2
dpkg-buildpackage: Fehler: Fehler-Exitstatus von debian/rules build war 2`

You have any clue what the matter with this issue is ?

Thanks again for your help.

**Comment by Meier123** [comment]
When i try to complie using "make" i get the following error:

`; caught ERROR:
;   READ error during COMPILE-FILE:
;
;     Symbol "+BLOB-LOCATION-SPEC+" not found in the IXF package.
;
;       Line: 45, Column: 32, File-Position: 1354
;
;       Stream: #<SB-INT:FORM-TRACKING-STREAM
;                 for "file /home/inst2/pgloader/pgloader_dev/pgloader-3.3.2+dfsg/src/sources/ixf/ixf-schema.lisp"
;                 {1009518A73}>

debugger invoked on a UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread
#<THREAD "main thread" RUNNING {100399CE43}>:
  COMPILE-FILE-ERROR while
  compiling #<CL-SOURCE-FILE "pgloader" "src" "sources" "ixf" "ixf-schema">`

It seems there is an issue with the ixf Format ?

**Comment by Meier123** [comment]
So during Installation i ignored that Errors and continued. I edited the Encoding.lisp and added line:

`("01208" . :UTF-8)`

I executed the pgloader:

`pgloader-3.3.2+dfsg/build/bin/pgloader ixfload.load`

and still get the error:

`FATAL An unhandled error condition has been signalled: Unknown Code Page "01208"`

which is quite awkward, because the Codepage shouldn't be unknown now, right?

**Comment by Meier123** [comment]
Well, i exported a testrow from IBM DB2 to Encodings, which should be known from pgloader, but i always get the message:

`IXF Type mapping unknown for: 404`

Do you have any clue, why that happens ? Sorry for posting so many times, but i wanted to Report all my Tasks and doings :)

**Comment by dimitri** [comment]
Can you try compiling from sources instead, a local copy of cl-ixf will be fetched from its github repository and that's the one you will have to hack (in `build/quicklisp/local-projects`).

**Comment by Meier123** [comment]
Hello Dimitri. Well, i compiled it from source like Christoph wrote before. What i didnt knew is to edit the Encoding.list in that Directory. 
Just for the hint, pgloader is not installed with apt-get, thats why i start it with: 

pgloader-3.3.2+dfsg/build/bin/pgloader ixfload.load

Now its getting a Little awkward, because after changing `build/quicklisp/local-projects/cl-ixf/Encodings.list`
i still get the message unknown Codepage 01208. Is there any Thing else iam missing. Really weird :(

**Comment by Meier123** [comment]
If you want to, i can send you the testfile, as well.

**Comment by dimitri** [comment]
Yes please send me the test file. Also, it seems like you're not doing to edit/compile/test cycle in the right order...

**Comment by Meier123** [comment]
Hello Dimitri,

sorry for my late answer, i've been on Holidays. Well, i also assume, that i do a wrong step while compiling.

My Steps:
-  apt-get source pgloader
-  apt-get build-dep pgloader
-  then i do a "make"
-  i edit the local-prjects - cl-ixf/Encoding.lisp
and do a make pgloader again. I think somehwere inside These steps is an error. After i do a make, i can see the download from github for the cl-ixf files.

Nevertheless i tried to LOAD (copy) the file again and get a new error message:
`FATAL An unhandled error condition has been signalled:
   IXF Type mapping unknown for: 404`

**Comment by Meier123** [comment]
Forgot 2 say : Happy New Year everyone :=)

How can i send you the testfile ?

**Comment by Meier123** [comment]
I also have an error while compiling:

; caught ERROR:
;   READ error during COMPILE-FILE:
;
;     Symbol "+BLOB-LOCATION-SPEC+" not found in the IXF package.
;
;       Line: 45, Column: 32, File-Position: 1354
;
;       Stream: #<SB-INT:FORM-TRACKING-STREAM
;                 for "file /home/inst2/pgloader/pgloader_dev/pgloader-3.3.2+dfsg/build/quicklisp/dists/quicklisp/software/pgloader-3.3.2/src/sources/ixf/ixf-schema.lisp"
;                 {100506D613}>



In my case i want to Import a BLOB from the ixf file. Maybe thats the reason why it won't work ?

**Comment by dimitri** [comment]
Please try again, I finally added 1208 as UTF-8 in cl-ixf and you should pick that up when building pgloader from sources, if you think of doing a `make clean` so that you force a new `git clone` of cl-ixf.
