### ISSUE TITLE
pgloader transformation before loading

### ISSUE THREAD

**Issue by rajmhnr** [dimitri/pgloader#495]
Hi,

New to postgres. Don't, know, whether this is right forum to ask for help.Kindly bear with me.

Different version of pgloader documentation is confusing me. Loading flat file to postgres table.I need to do few transformations while reading the file and load it. 

Like
-->Check for characters, if it is present, default some value with number. Reg_Exp can be used in oracle. How the functions can be called in below syntax?
-->TO_DATE function from text format. File will have date format as YYYYMMDD
-->Check for Null and defaulting some value
-->Trim functions
-->Only few columns from source file should be loaded. Different ordering in source files & target columns.
-->Defaulting values, say for instance, source file has only 2 columns. But we need to load 3 columns. Third column should be defaulted with some value.

File don't have header.

LOAD CSV
    FROM 'filename'
    INTO postgresql://role@host:port/database_name?tablename
        TARGET COLUMNS  
            (  
                alphanm,alphnumnn,nmrc,dte
            ) 

    WITH truncate,  
         skip header = 0,  
         fields optionally enclosed by '"',  
         fields escaped by double-quote,  
         fields terminated by '|',
         batch rows = 100,
         batch size = 1MB,     
         batch concurrency = 64

    SET work_mem to '32 MB', maintenance_work_mem to '64 MB';

Kindly help me, how this can be accomplished used pgloader? Some sample syntax would be greatly helpful.

Thanks

**Comment by dimitri** [comment]
Hi!

I suggest you have a look at https://github.com/dimitri/pgloader/tree/master/test example files and also at http://pgloader.io/howto/geolite.html for some examples, then get back with more specific questions. Another way for me to be able to help you would be if you can share some example data file and target table definition so that I could be able to setup a test case for you with full details.

**Comment by rajmhnr** [comment]
Thanks Dimitri. Those samples are resourceful. I'm looking that.

Here is the sample data.File has no header.

```
Sample Data:
ABC|20170101|DEF ||GHIJ|KLM
```

```
Target Table Definition:
COLA numeric(5,0)
COLB date
COLC text
COLD text
COLE text
```

```
First column-->COLA
Second column-->COLB
Third column-->COLD
Fourth column-->COLC
Fifth column-->Some default value(column is not present in source) 
```

```
Transformation:
-->First column-->COLA. It is numeric in target table. If any alpha-characters were present, default this column with '0'. Otherwise, source value should be moved to table.
-->Second column-->COLB. TO_DATE function from text format. File will have date format as YYYYMMDD. It should be converted to date.
-->Third column-->COLD.Need to Trim both leading and trailing spaces.
-->Fourth column-->COLC. If it NULL, some value should be defaulted.
-->Only few columns from source file should be loaded. In this case, only first four columns should be loaded.
-->Different ordering in source files & target columns.In this case,
        Third column-->COLD
        Fourth column-->COLC
-->COLE should be loaded with default value. This column is not present in source file.
```

These transformations, can be handled with query after loading all the data as varchar and nullable. But we need to handle this before loading as like we do in Oracle.

**Comment by rajmhnr** [comment]
Dimitri,

Tried this code, getting below error; FATAL An unhandled error condition has been signalled: Argument X is not a NUMBER: NIL.

> /*
>  * 
>  *
>  * [table_name]
>  * table        = schema.table_name
>  * format       = text
>  * filename     = Filepath/file_name
>  * field_sep    = |
>  * columns      = COLA:1,COLB:2,COLD:3,COLC:4
>  * null		    = ''
>  * udc_COLE     = HH
>  */
> LOAD CSV
> 	FROM inline 
> 		(
> 			COLA, 
> 			COLB [date format 'YYYYMMDD'] , 
> 			COLD,
> 			COLC,
> 			COLE
> 		)
> 	INTO postgresql://role@host:port/database_name?tablename
>         (  
>            	COLA, 
> 			COLB, 
> 			COLD,
> 			COLC,
> 			COLE
> 		) 
> 
> 	WITH truncate,  
> 	     skip header = 0,  
> 	     fields optionally enclosed by '"',  
> 	     fields escaped by double-quote,  
> 	     fields terminated by '|',
> 	     batch rows = 100,
> 	     batch size = 1MB,     
> 	     batch concurrency = 64
> 
> 	SET work_mem to '32 MB', maintenance_work_mem to '64 MB';

How to handle this below transformation? Kindly help me.

Transformation:
-->First column-->COLA. It is numeric in target table. If any alpha-characters were present, default this column with '0'. Otherwise, source value should be moved to table.
-->Third column-->COLD.Need to Trim both leading and trailing spaces.
-->Fourth column-->COLC. If it NULL, some value should be defaulted.

Thanks

**Comment by rajmhnr** [comment]
Hi Dimitri,

Used the following code, it worked for few transformations.

```
> LOAD CSV
> 	FROM file
> 		(
> 			COLA [null if blanks,trim both whitespace], 
> 			COLB [null if blanks,trim both whitespace], 
> 			COLD [null if blanks,trim both whitespace],
> 			COLC [null if blanks,trim both whitespace]
> 		)
> 	INTO postgresql://role@host:port/database_name?tablename
>         (  
>            	        COLA, 
> 			COLB using (date-with-no-separator dte), 
> 			COLD,
> 			COLC,
> 			COLE text using "85"
> 		) 
> 
> 	WITH truncate,  
> 	     skip header = 0,  
> 	     fields optionally enclosed by '"',  
> 	     fields escaped by double-quote,  
> 	     fields terminated by '|',
> 	     batch rows = 100,
> 	     batch size = 1MB,     
> 	     batch concurrency = 64
> 
> 	SET work_mem to '32 MB', maintenance_work_mem to '64 MB';
```

But i cannot do following few transformation.

**-->First column-->COLA. It is numeric in target table. If any alpha-characters were present, default this column with '0'. Otherwise, source value should be moved to table.
-->Fourth column-->COLC. If it NULL, some value should be defaulted.**

Is there is any other solution to handle above transformations? Kindly guide me.

**-->Second column-->COLB. TO_DATE function from text format. File will have date format as YYYYMMDD. It should be converted to date.**

date style is 'dmy' format. Do i need to change it to ymd in transforms.lisp file? 

Thanks

**Comment by dimitri** [comment]
Here's a self-contained test case that implements what you're asking for, as far as I can tell. Note that if you want more complex parsing rules you will need to write a lisp file then use that with the `--load-lisp-file` option, using https://github.com/dimitri/pgloader/blob/master/src/utils/transforms.lisp as an example.

Also note that `YYYYMMDD` is recognized as a date just fine by PostgreSQL so we don't have any transformation to do here.

```
LOAD CSV
	FROM inline
		HAVING FIELDS
                (
			COLA [null if blanks,trim both whitespace], 
			COLB [null if blanks,trim both whitespace], 
			COLD [null if blanks,trim both whitespace],
			COLC [null if blanks,trim both whitespace]
		)
	INTO postgresql:///pgloader?t495
        	TARGET COLUMNS
	        (  
           	        COLA numeric
                          using (if (some (function alpha-char-p) cola) "0" cola),
			COLB,
			COLD,
			COLC text using (or colc "default"),
			COLE text using "85"
		) 

	WITH truncate,  
	     skip header = 0,  
	     fields optionally enclosed by '"',  
	     fields escaped by double-quote,  
	     fields terminated by '|',
	     batch rows = 100,
	     batch size = 1MB,     
	     batch concurrency = 64

	SET work_mem to '32 MB', maintenance_work_mem to '64 MB'

	BEFORE LOAD DO
		$$ drop table if exists t495; $$,
		$$
		create table t495
		(
			COLA numeric(5,0),
			COLB date,
			COLC text,
			COLD text,
			COLE text
		);
		$$;


ABC|20170101|DEF ||GHIJ|KLM
10|20161227|DEF |plop|GHIJ|KLM
```

That gives the following table content:

```
pgloader# table t495;
 cola |    colb    |  colc   | cold | cole 
------+------------+---------+------+------
    0 | 2017-01-01 | default | DEF  | 85
   10 | 2016-12-27 | plop    | DEF  | 85
(2 rows)
```

**Comment by rajmhnr** [comment]
Great. Thanks Dimitri.  It worked.
