### ISSUE TITLE
MySQL: regex in INCLUDING ONLY TABLE NAMES MATCHING not working

### ISSUE THREAD

**Issue by mfn** [dimitri/pgloader#498]
Tested with
```
pgloader version "3.3.2"
compiled with SBCL 1.2.4.debian
```
I don't think `INCLUDING ONLY TABLE NAMES MATCHING ~/table/` is working as expected; it does not match any tables, not matter what I tried.

Using `--debug` I saw the generated SQL statement:
```SQL
  SELECT table_name, index_name, sum(non_unique),
         cast(GROUP_CONCAT(column_name order by seq_in_index) as char)
    FROM information_schema.statistics
   WHERE table_schema = 'project'

         and (table_name REGEXP '(REGEX table)')

GROUP BY table_name, index_name;
```
I think the line
```SQL
         and (table_name REGEXP '(REGEX table)')
```
should read
```SQL
         and (table_name REGEXP 'table')
```

**Comment by medley56** [comment]
I think this is still an issue. I can't get the regex to match anything.

**Comment by medley56** [comment]
Ha, no sorry. I'm working with the version that Homebrew installs, 3.3.2. Which version contains the fix?

**Comment by medley56** [comment]
Actually, this is strange. Homebrew says it installs version 3.4.1 but then when I run pgloader --version I get 3.3.2. Is this an issue with Homebrew?

`▶ pgloader --version
zsh: command not found: pgloader

~                                                                             ⍉
▶ brew install pgloader
==> Downloading https://homebrew.bintray.com/bottles/pgloader-3.4.1.sierra.bottl
Already downloaded: /Users/ecelt-07/Library/Caches/Homebrew/pgloader-3.4.1.sierra.bottle.tar.gz
==> Pouring pgloader-3.4.1.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/pgloader/3.4.1: 7 files, 20.8MB

~                                                                              
▶ pgloader --version
pgloader version "3.3.2"
compiled with SBCL 1.3.19`

**Comment by dimitri** [comment]
Can you try compiling from a git clone of this repository? I guess brew took care of installing build needed dependencies when you did the `--HEAD` build. As I am not maintaining the brew formula, someone would need to step up and fix it ideally.

**Comment by medley56** [comment]
Compiled from a git clone and now I get a seemingly more serious error:

```
KABOOM!
FATAL error: Failed to connect to mysql at "localhost" (port 3306) as user "root": SSL verify error: 19 X509_V_ERR_SELF_SIGNED_CERT_IN_CHAIN
An unhandled error condition has been signalled:
   Failed to connect to mysql at "localhost" (port 3306) as user "root": SSL verify error: 19 X509_V_ERR_SELF_SIGNED_CERT_IN_CHAIN



2017-08-10T10:34:18.231000-06:00 LOG Data errors in '/private/tmp/pgloader/'
2017-08-10T10:34:18.237000-06:00 LOG Parsing commands from file #P"/Users/ecelt-07/SLM_Migration/PGLOAD"

What I am doing here?

Failed to connect to mysql at "localhost" (port 3306) as user "root": SSL verify error: 19 X509_V_ERR_SELF_SIGNED_CERT_IN_CHAIN


Waiting for the monitor thread to complete.
```

**Comment by dimitri** [comment]
I guess you might be able to connect to *localhost* without SSL? At least try the unix socket?

**Comment by medley56** [comment]
Perhaps this is a silly question but how do I do those things? Should I specify --no-ssl somewhere?

**Comment by dimitri** [comment]
Reading the docs you would find the spelling for the Unix Socket file in the connection string, as show in the following example:

```
     -- from   mysql://root@localhost/pgloader
     from      mysql://root@unix:/tmp/mysql.sock:3306/pgloader
```

**Comment by medley56** [comment]
Excellent! Thank you for the support. I really appreciate your time.
