### ISSUE TITLE
Passing arguments in runtime

### ISSUE THREAD

**Issue by rajmhnr** [dimitri/pgloader#500]
Hi Dimitri,

Have one more question.

I need to pass the Filename, File Path, Host, Port, Database, Username, Schema, Password as arguments, something like below;

```
pgloader filename.ctl $1 $2 $3 $4 $5 $6
```

where 
$1 denotes Host
$2 denotes Username
$3 denotes Database name
$4 denotes Password
$5 denotes File Path
$6 denotes File Name

These parameters will be passed by scheduler, during run time. Kindly help me, how this can be done?

Thanks

**Comment by dimitri** [comment]
Please have a look at the documentation about the connection strings (https://github.com/dimitri/pgloader/blob/master/pgloader.1.md#connection-string) that explains how we support environment parameters for some parameters.

If you want to avoid using environment variables for security reasons (in a multi user system, say), then you need to consider your load file (`filename.ctl` in your example) as a template and implement a way to instantiate the template with your variables.
