### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by VojtechBartos** [dimitri/pgloader#502]
just FYI http://pgloader.io site is down, i am not able to load it at all ;)

**Comment by thomaskeefe** [comment]
Yeah, site is still down... I like pgloader I hope the site comes back up!!!

**Comment by dimitri** [comment]
I had to move the hosting facility and we are now using Github project pages for pgloader.io, straight static pages from the `docs` directory of the project. Only bit left is the source release (`pgloader-latest.tgz`) that's not back online yet. Thanks for your support guys!
