### ISSUE TITLE
ERROR not supported type SYB-MSXML

### ISSUE THREAD

**Issue by nicowernli** [dimitri/pgloader#503]
This happens when trying to migrate a table with a MSSQL XML field type to a PostgreSQL XML.

The query with --debug is not performing any conversion in the field:
```
SELECT [ID], ..., [ExtendedInfo], ... FROM [dbo].[TABLENAME];
``` 

I'm getting this warning first:
```
2017-01-12T12:26:27.635000+01:00 WARNING Source column "public"."TABLENAME"."extendedinfo" is casted to type "text" which is not the same as "xml", the type of current target database column "public"."commandlog"."extended info".
```

and then the error:
```
2017-01-12T12:26:27.851000+01:00 ERROR not supported type SYB-MSXML
```

Looks like pgloader is trying to cast an XML field to a text field.
Thanks!

**Comment by BoiDareia** [comment]
Having the same problem, it seems that pgloader is not being able cast the XML type correctly. Here's my load file content:

**_load database
     from mssql://user:password@sqlserver/database
     into postgresql://user@server.pt:5432/database_**

**_WITH create tables, create indexes, create schemas, include drop, batch rows = 1000, batch concurrency = 5_**

**_CAST type xml to text drop typemod_**

**_ALTER SCHEMA 'dbo' RENAME TO 'public'_**

**_set work_mem to '16MB', maintenance_work_mem to '512 MB' ;_**

Where you able to do anything with this issue?

**Comment by dimitri** [comment]
Are there any documentation about what the XML data look like when transferred to clients? I would have to have a test case to reproduce the problem, too.

**Comment by BoiDareia** [comment]
Not that I know of. Will create a test case and send it to you,

**Comment by dimitri** [comment]
Thanks for the test case. Fixed now: XML is sent as text by the FreeTDS driver...
