### ISSUE TITLE
Add the ability to ignore lines that match a given regex.

### ISSUE THREAD

**Issue by davidklebanoff** [dimitri/pgloader#507]
I think it would be great to have the ability to specify a regular expression, that when matched, skips the line in a CSV file. I foresee it being a WITH configuration similar to the "skip header" option.

This addresses a common problem I have where some sources that I am importing have comments embedded within them. For example, one datasource embeds comments with the CSV files using `##` to identify them:
```
## This is a comment
a,b,c,d
e,f,g,h
## This is another comment
i,j,k,l
```

I've also seen CSVs with single hashes `#` in front of comments.

My apologies if this feature is already possible - I could not find it.

**Comment by dimitri** [comment]
We currently lack per-line processing in our CSV support. One problem is that the filtering or even transformation would kick-in *before* having parsed the line, so without any way to understand if it is part of a logical row spreading more than one physical line...
