### ISSUE TITLE
Column order matters when importing from SQLite into an existing table in Postgres

### ISSUE THREAD

**Issue by k-jackson** [dimitri/pgloader#509]
I'm getting the same issue with column ordering as #132, but with SQLite as a source. 

This happens when using `WITH include no drop, create no tables, truncate, create indexes, disable triggers, reset sequences`, as the table on the Postgres end matches the table in SQLite3 (with the order of the columns being the only difference). 

The import errors often show up as type issues when the positional columns have differing types, which is what tipped me off in the first place, in addition to the import being incorrect.
```
ERROR Database error 22P02: invalid input syntax for integer: "some text here"
```

**Comment by dimitri** [comment]
It should be good now, please build from sources and try again.

**Comment by k-jackson** [comment]
This has completely resolved the issue. Thank you for the rapid fix!

**Comment by madtimber** [comment]
@dimitri Looks like this may be a problem again.

Here's my command file:

```
LOAD DATABASE
  FROM './goldenbear.db'
  INTO postgresql:///scratch

  WITH include no drop, create no tables, reset sequences

  SET work_mem to '16MB', maintenance_work_mem to '512 MB'

  /* some casting that we need to do between pgloaders defaults and what we really want */
  CAST type integer to integer,
       type varchar to varchar,
       type bool to boolean

  EXCLUDING TABLE NAMES LIKE  'south_migrationhistory'
;

```
Here are some of the errors I'm seeing:
```
CONTEXT: COPY golfpool_singletournamentpool, line 1, column owner_id: "single"
2017-09-08T14:52:40.517000-04:00 ERROR Database error 22P02: invalid input syntax for integer: "single"
```
```
2017-09-08T14:52:39.881000-04:00 ERROR Database error 22P02: invalid input syntax for integer: "2017-08-21 01:22:23.527270"
CONTEXT: COPY golfpool_singletournamentpoolentry, line 1, column pool_id: "2017-08-21 01:22:23.527270"
```
There's many more (many types), but wanted to keep it brief.

Essentially almost all of my columns are being matched incorrectly.

I'm running off of ```-HEAD``` in homebrew.

Thoughts?

**Comment by madtimber** [comment]
Both schemas are identical as they're controlled by Django's Model/ORM/Migration mechanism.

What I've done for my migration to Postgres, is to create the new PS database, run the django migrations I have to create the schema, and now I'm wanting to load the data from sqlite.

**Comment by dimitri** [comment]
It's been reporting that `HEAD` in homebrew might not be uptodate actually, can you please report `pgloader --version`?

**Comment by madtimber** [comment]
```
pgloader version "3.3.2"
compiled with SBCL 1.3.21
```

**Comment by madtimber** [comment]
Yeah, that looks like I'm a minor point behind. Would 3.4.x help me out here?

**Comment by dimitri** [comment]
Latest released version is 3.4.1, and head should be 3.4.e7f6505 until next commit. Please consider building from sources and trying again, I'd be surprised if you still had the problem then.

**Comment by madtimber** [comment]
Will try that and let you know, thanks!

**Comment by madtimber** [comment]
After a few build problems, all is good!
