### ISSUE TITLE
Couldn't re-execute SBCL with proper personality flags

### ISSUE THREAD

**Issue by Chekote** [dimitri/pgloader#511]
I'm trying to run pgloader, but I always get the following error as soon as I execute the program. Even if I do something as simple as `pgloader --help`:

```
WARNING:
Couldn't re-execute SBCL with proper personality flags (/proc isn't mounted? setuid?)
Trying to continue anyway.

debugger invoked on a SIMPLE-ERROR in thread
#<THREAD "main thread" RUNNING {1008CC43B3}>:
  Error opening shared object "libssl.so.1.0.0":
  libssl.so.1.0.0: cannot open shared object file: No such file or directory.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [CONTINUE       ] Skip this shared object and continue.
  1: [RETRY          ] Retry loading this shared object.
  2: [CHANGE-PATHNAME] Specify a different pathname to load the shared object from.

(SB-SYS:DLOPEN-OR-LOSE #S(SB-ALIEN::SHARED-OBJECT :PATHNAME #P"libssl.so.1.0.0" :NAMESTRING "libssl.so.1.0.0" :HANDLE NIL :DONT-SAVE NIL))
```

**Comment by dimitri** [comment]
Looks like an SBCL problem, I don't think I can help you with that. Please see http://www.sbcl.org and ask them...

**Comment by yamila-moreno** [comment]
Hello! I'm facing the same problem, @Chekote, did you find any solution?

**Comment by fabswt** [comment]
Same here.

**Comment by fabswt** [comment]
I posted a [bug report](https://bugs.launchpad.net/sbcl/+bug/1706963) over at SBCL, but I now suspect this to be a Docker issue because:

a) I tried to compile a bunch of SBCL Dockerfiles found online and they all end up with the same `Couldn't re-execute SBCL with proper personality flags (/proc isn't mounted? setuid?)`

b) I managed to install and execute `pgloader` and `sbcl` without warning on a non-Docker Ubuntu install (on an Amazon EC2 instance), using the same commands I was using inside the Dockerfile.

I'd be happy to hear which environment @Chekote and @yamila-moreno  were using.

**Comment by yamila-moreno** [comment]
Hi @fabswt thanks for your answer and your research; indeed I was using a Docker environment; my docker-compose has 3 services:
- postgres
- mysql
- pgloader
and a network to connect them all. I could access both the databases from the pgloader container (so it wasn't a networking issue).

I'll try with a virtualbox machine. Thanks for sharing!!

**Comment by yamila-moreno** [comment]
Hi again; I've tried to use pgloader inside a virtualbox (with postgres, mysql and pgloader) and after some tuning (with ONLY_FULL_GROUP_BY) it finally worked!!

Thanks to @fabswt cause your hint lead me to the next step 👍

**Comment by mmariani** [comment]
@yamila-moreno afaik you can do it in docker with `docker run --security-opt seccomp=unconfined `

or by providing an explicit seccomp profile. See: https://github.com/daewok/slime-docker/blob/master/README.md#sbcl-aslr

**Comment by yamila-moreno** [comment]
@mmariani thanks for your tip! Very appreciated.

**Comment by dimitri** [comment]
Please consider adding those tips to the wiki here!

**Comment by mmariani** [comment]
done https://github.com/dimitri/pgloader/wiki/Running-in-Docker-(SBCL-warning)
