### ISSUE TITLE
Interpreting "ERROR The value xxx is not of type STRING"?

### ISSUE THREAD

**Issue by hampelm** [dimitri/pgloader#512]
I'm trying to copy data (including some geodata columns) from mysql into posgres using the standard loading command (`pgloader mysql://... postgresql://...`). I also tried using a loading config file as [described in the docs](http://pgloader.io/howto/mysql.html). 

With both, the schema is successfully copied. However, I get a variant of the following error for what looks like every row it tries to import: 

```
2017-02-06T15:26:26.319000-05:00 ERROR The value
  #(1 0 0 0 1 3 0 0 0 1 0 0 0 5 0 0 0 127 14 239 103 245 143 94 192 185 231 250
    136 255 236 66 64 194 38 20 253 246 143 94 192 149 31 123 49 6 237 66 64
    107 94 65 40 249 143 94 192 252 47 63 205 4 237 66 64 1 255 13 147 247 143
    94 192 69 206 223 30 254 236 66 64 127 14 239 103 245 143 94 192 185 231
    250 136 255 236 66 64)

is not of type
  STRING
```

I've tried with pgloader installed with brew (`pgloader version "3.3.2"
compiled with SBCL 1.3.12`) and built from source (`pgloader version "3.3.024579c" compiled with SBCL 1.3.14`) on OS X 10.10.

Is there a way to get more detail on that error -- for example, does it refer to a specific column? I tried running with `--debug` which provided lots of information up until that point.

**Comment by dimitri** [comment]
I will need some of the `--debug` information to be of any help here. Also if you can share the table where that error happens (as a MySQL dump file) that would allow me to reproduce and fix the problem.

**Comment by hampelm** [comment]
Thank you! I will try to isolate it into a few rows of test data this week, which may get me closer to a solution as well.

**Comment by dimitri** [comment]
Any luck in identifying a self-contained test case?

**Comment by hampelm** [comment]
My apologies for not following up on this. We ended up using [ogr2ogr](http://www.gdal.org/ogr2ogr.html) since there was spatial data involved, and I didn't get around to creating a test case. 

Thanks for your work on this project, and happy to close this out.
