### ISSUE TITLE
pgloader supports the Postgres Enterprise Edition(EDB)?

### ISSUE THREAD

**Issue by rajmhnr** [dimitri/pgloader#517]
Will the pgloader supports the Postgres Enterprise Edition(EDB)? I want to try that in EDB.

Thanks

**Comment by dimitri** [comment]
What happens when you try?

To my knowledge EDB is a fork of PostgreSQL and uses the same protocol so from the point of view of any client connection, it's just another PostgreSQL instance: it should be transparent.

**Comment by rajmhnr** [comment]
I didn't try that. Will let you know, if it works.
