### ISSUE TITLE
pgloader in multiple session after breaking the files into chunks

### ISSUE THREAD

**Issue by rajmhnr** [dimitri/pgloader#519]
I want to load the data into partitioned tables(child tables) directly. Tables were partitioned based on DATE. Name will be something like this TABLENAME_20170222. It has index and primary keys and no triggers on it.

Need few clarification. Kindly help me.

=>Pgloader log says

> 2017-02-22T13:10:56.606000-05:00 WARNING Target table "TABLENAME_20160906" has 1 indexes defined against it.
> 2017-02-22T13:10:56.606000-05:00 WARNING That could impact loading performance badly.
> 2017-02-22T13:10:56.607000-05:00 WARNING Consider the option 'drop indexes'.

Is it right approach to drop the INDEX before loading the data and recreate it after loading the partitioned(child) table? Any solution to do that in pgloader using argument or in control file?
I have primary keys as well.Keeping the primary keys will not affect the performance. right? Why because, i need to capture duplicate records in separate file.

=>I want to have reject and log directory in my separate directory. By default, it was writing to ROOT DIRECTORY. Need to pass that in control file. How to handle this?

-j, --reject-data
Filename, with a single "%s" placeholder, where to store the bad data (the exact lines that didn’t make it from your input file). If you want to put a percent in the file name, write it %%.

This description was not clear. Can you please provide some example?

=>Used to get file in the size of 30-40gb. Splitted the file into chunks and loaded the file using COPY command. I can find huge difference in performance. Will it work the same way in pgloader? Will it create any other issues? Thinking to try that tomorrow.

Thanks

**Comment by dimitri** [comment]
Usually the right approach is indeed to `drop` the index before the load and then `create` it again. The pgloader option `drop indexes` will do that automatically for you, as hinted in the error reporting.

The root directory option is a command line option, please use that (see `pgloader --help`).

About the `--reject-data` option it looks like you're not reading the current documentation?
