### ISSUE TITLE
bad error handling.

### ISSUE THREAD

**Issue by paranormal** [dimitri/pgloader#520]
I have no errors and no result too :)

I'm on freebsd, I tried both repo and built from sources versions. Both .load and db://
I have no results at all it finishes after few seconds running. The most I can get from it by using -d is;
```
sb-impl::*default-external-format* :US-ASCII
tmpdir: #P"/tmp/pgloader/"
```

Which is a shame, looking at documentation it is clear that a lot of effort was made to create pgloader, and I'm sure that it's supposed to be a great piece of software...

**Comment by dimitri** [comment]
Can you tell me which version you are running (`--version`) and give me more details about what you're trying to achieve and what you see?

**Comment by paranormal** [comment]
version:
```
./build/bin/pgloader --version
pgloader version "3.3.8ec2ea0"
```
Trying:
```
./build/bin/pgloader mysql://root@localhost/db postgres:///db
```

**Comment by paranormal** [comment]
Having system pgloader:
```
pgloader --version
PGLoader version 2.3.1
```
The results are the same: it does nothing, works for 1-2 seconds.

**Comment by paranormal** [comment]
If you would help me fixing it I would update FreeBSD port

**Comment by dimitri** [comment]
The version 2.3.1 is not maintained at all and not compatible in any way with the command line and command language that are available in pgloader version 3.x. Can you please give me the full output of the commands you type so that I have enough information to figure out what's happening?

In the worst case a remote login to a box where I can easily reproduce the problem might help fix it.

**Comment by paranormal** [comment]
2.3.1 - This is why I downloaded the current one using github.

```
root@host:~/pgloader # time ./build/bin/pgloader -v -d mysql://root@localhost/db postgres:///db
sb-impl::*default-external-format* :US-ASCII
tmpdir: #P"/tmp/pgloader/"
0.482u 0.094s 0:00.92 61.9%	232+217k 2+0io 0pf+0w
root@host:~/pgloader # 
```

Both databases created and accessible. I could give you an access to this box, it's just a freshly installed jail.

**Comment by paranormal** [comment]
In any case it should pgloader shouldn't be silent.

**Comment by dimitri** [comment]
Yeah it shouldn't be silent, I agree totally here. There must be something fishy that it doesn't like, maybe non existing `--root-dir` or something? can you `strace` it and see what gives?

**Comment by paranormal** [comment]
truss output :
```
mprotect(0x1000588000,32768,PROT_READ|PROT_WRITE|PROT_EXEC) = 0 (0x0)
sigreturn(0x811f17810)				 = 68725283743 (0x1000589b9f)
stat("/tmp/pgloader",{ mode=drwxr-xr-x ,inode=50400,size=2,blksize=4096 }) = 0 (0x0)
lstat("/tmp",{ mode=drwxrwxrwt ,inode=24,size=10,blksize=131072 }) = 0 (0x0)
lstat("/tmp/pgloader",{ mode=drwxr-xr-x ,inode=50400,size=2,blksize=4096 }) = 0 (0x0)
SIGNAL 11 (SIGSEGV)
sigprocmask(SIG_SETMASK,{ SIGHUP|SIGINT|SIGQUIT|SIGPIPE|SIGALRM|SIGTERM|SIGURG|SIGTSTP|SIGCHLD|SIGIO|SIGXCPU|SIGXFSZ|SIGVTALRM|SIGPROF|SIGWINCH },0x0) = 0 (0x0)
mprotect(0x10006d0000,32768,PROT_READ|PROT_WRITE|PROT_EXEC) = 0 (0x0)
sigreturn(0x811f17810)				 = 537919511 (0x20100017)
SIGNAL 11 (SIGSEGV)
sigprocmask(SIG_SETMASK,{ SIGHUP|SIGINT|SIGQUIT|SIGPIPE|SIGALRM|SIGTERM|SIGURG|SIGTSTP|SIGCHLD|SIGIO|SIGXCPU|SIGXFSZ|SIGVTALRM|SIGPROF|SIGWINCH },0x0) = 0 (0x0)
mprotect(0x1000d18000,32768,PROT_READ|PROT_WRITE|PROT_EXEC) = 0 (0x0)
sigreturn(0x811f17810)				 = 217 (0xd9)
SIGNAL 11 (SIGSEGV)
sigprocmask(SIG_SETMASK,{ SIGHUP|SIGINT|SIGQUIT|SIGPIPE|SIGALRM|SIGTERM|SIGURG|SIGTSTP|SIGCHLD|SIGIO|SIGXCPU|SIGXFSZ|SIGVTALRM|SIGPROF|SIGWINCH },0x0) = 0 (0x0)
mprotect(0x10001c8000,32768,PROT_READ|PROT_WRITE|PROT_EXEC) = 0 (0x0)
sigreturn(0x811f17810)				 = 81 (0x51)
SIGNAL 11 (SIGSEGV)
```

**Comment by paranormal** [comment]
Hm, but I can't believe it got SIGSEGV from lstat. Give me a moment I'll try other options.

**Comment by paranormal** [comment]
Is there are way to compile it so I could run in form gdb/lldb with symbols accessible?

**Comment by dimitri** [comment]
I don't know about that. Common Lisp comes with its own debugger protocol, try running it from a Common Lisp _standard_ environment such as Emacs & Slime, that might be the easiest. Or send me accesses and I'll try to see what gives.

**Comment by paranormal** [comment]
Ok. sent to email from your profile.

**Comment by dimitri** [comment]
Ok we got nowhere here, there's something strange and fishy in your environment. I'm closing the issue...

**Comment by paranormal** [comment]
Env is fine, I run into it using my dev workstation and gave you some very different environment. It just doesn't work on FreeBSD.

**Comment by dimitri** [comment]
Maybe we should report that to the SBCL community then... did you try with CCL?
