### ISSUE TITLE
Include Static Text with CSV Import

### ISSUE THREAD

**Issue by TDMatthews** [dimitri/pgloader#522]
I'll try and keep this brief as it should be a simple answer. I have pgloader working fine with my CSVs, but I want to include additional metadata with the import, for example the filename that the data came from. For now I am hardcoding the text - tried with both ' and " - and I get unbound errors for every row:

`ERROR The value NIL is not of type SIMPLE-ARRAY.
ERROR Could not read input: The variable PGLOADER.USER-SYMBOLS::DATAFILE is unbound.`

my load file looks like so:
```
LOAD CSV
      FROM './filename_20170227.csv' ('filename_20170227.csv',samplenumber,project_id,site)
      INTO postgresql:///mydb?myschema.mytable (datafile,samplenumber,project_id,site)

      WITH truncate,
           skip header = 1,
           fields optionally enclosed by '"',
           fields terminated by ','  ;
```

The datafile column is nullable, so removing it loads the data fine. Is it possible to interject static data as well?

**Comment by dimitri** [comment]
Check the following example from the test suite that does exactly that. It's named "udc" per “User Defined Columns” as they used to be called already in pgloader v2 suite.

  https://github.com/dimitri/pgloader/blob/master/test/udc.load
