### ISSUE TITLE
Question: will pgloader handle MySQL 4.1 to Postgres 9.6

### ISSUE THREAD

**Issue by MichaelDBA** [dimitri/pgloader#524]

**Comment by dimitri** [comment]
What happens when you try?

**Comment by MichaelDBA** [comment]
I haven't tried.  Do I need to look at the source code myself to get the answer?

**Comment by MichaelDBA** [comment]
I am considering tools to use.  So I just want this answer before I start evaulating it.  Can you just tell me if the program relies on querying the system/metadata tables in MySQL?  If it does, then we know it won't work for MySQL pre 5.0.

**Comment by dimitri** [comment]
Please consider for a moment why I would do your homework for you on top of providing pgloader for free. Having a try will cost you the whole of 5 mins to 30 mins. Either you're interested into evaluating the software or you're not. Your call.

And if needs be, yes, look at the source code yourself. I wrote it myself, after all.

If you have any specific problems when using the software and the docs aren't helpful to you, please consider then opening issues I can help you with here, I'll be happy to offer you free support on top of the free software. Now please do *your* homework.

**Comment by MichaelDBA** [comment]
I figured since you wrote it, you would have the answer off the top of your head about whether or not this program uses MySQL metadata tables, which takes **5 seconds**, instead of me downloading MySQL 4.1, installing and configuring it.  Then downloading your program and configure it and run it.

I don't think my request is unreasonable.

**Comment by jd** [comment]
@MichaelDBA This is an issue tracker, not a forum. You could at least send a kind email to the author to ask if it knows if it does. :)
