### ISSUE TITLE
Loading transformations.lisp prevents command file from running

### ISSUE THREAD

**Issue by lyonssp** [dimitri/pgloader#526]
I am attempting to cast `binary(16)` columns from MySQL to `uuid` and so I am going to attempt to create my own `transformations.lisp` to pass to `pgloader`

When I run
```
pgloader etl.load
```
Everything seems to work fine, and I get a typical output summary.

When I attempt to pass a lisp file using 
```
pgloader --load-lisp-file lisp/transforms.lisp etl.load
```
I get no output of any kind, even when using `--verbose`.  I see no results present in my target database, although the lisp file actually is compiled to `transforms.fasl`.  

Is there any way to include this transform file without a command line option that might serve as a workaround?

Details:
```
$ pgloader -V
pgloader version "3.2.2"
compiled with SBCL 1.3.1.debian
```

**Comment by dimitri** [comment]
Is it possible for you to share the lisp and load files for me to reproduce the bug?

Otherwise it is possible to use a Common Lisp developper environment and load your transformation file on top of pgloader in there before to run the command in the REPL.

**Comment by lyonssp** [comment]
So the lisp that I am using is
https://github.com/dimitri/pgloader/blob/master/src/utils/transforms.lisp
just for testing the issue out

And here is the command file I'm using:
```
load database  
     from <SOURCE DB URL>
     into <TARGET DB URL>

WITH include drop, create tables, create indexes, reset sequences

INCLUDING ONLY TABLE NAMES MATCHING 'nd_roles'

CAST type datetime to timestamptz drop default drop not null using zero-dates-to-null,  
    type date drop not null drop default using zero-dates-to-null,  
    type year to integer,
    type enum to text drop not null using empty-string-to-null
;
```

**Comment by dimitri** [comment]
A copy of the output you see in `--debug --verbose` mode would be helpful.

**Comment by lyonssp** [comment]
Like I wrote in the original issue, unfortunately I get no output from the program with or without the verbose flag.  It's a particularly unhelpful failure, haha.  Essentially, the behavior seems to be that the transform file compiles and nothing else happens.

**Comment by lyonssp** [comment]
This is that output
```
$ pgloader --debug --verbose --load-lisp-file=lisp/transforms.lisp etl.load
sb-impl::*default-external-format* :UTF-8
tmpdir: #P"/tmp/pgloader/"
```

**Comment by dimitri** [comment]
Please build pgloader from sources and try again, you should be able to understand what happens. Might just have been some warnings even. And sorry for the delay in answering that bug report, it kind of fell through the cracks.
