### ISSUE TITLE
MSSQL tinyint cast not working properly

### ISSUE THREAD

**Issue by BoiDareia** [dimitri/pgloader#528]
Hi, I've encountered a new "hiccup" in my mssql migrations. I've been testing in my own machine migrations between SQL Server 2005 and EDB PostgreSQL 9.5/9.6 without problem. But as soon as I went to my development machine I encountered an issue with one of the databases I'm trying to migrate.

So it seems that when I try to migrate a database that has a tinyint type in one of the fields it gives me the following error:

```
2017-03-17T12:06:53.246000Z NOTICE DROP then CREATE TABLES
2017-03-17T12:06:53.447000Z ERROR Database error 42704: type "tinyint" does not exist
QUERY: CREATE TABLE public.utilizperfis
(
  id        tinyint not null,
  perfil    text not null,
  descricao text not null
);
```

The weird part is that it only happens to me in Community PostgreSQL (either 9.5 or 9.6) flavour. It seems to be able to do the cast without a problem in an EDB PostgreSQL.
Here's my load file content:

```
load database
     from mssql://user:pass@sqlmachine.com/database
     into postgresql://user@machine.com:5432/database

WITH create tables, create indexes, create schemas, include drop, batch rows = 1000, batch concurrency = 5

ALTER SCHEMA 'dbo' RENAME TO 'public'

set work_mem to '16MB', maintenance_work_mem to '512 MB' ;
```

Have anyone had this problem?

*Dimitri, if you need to I can do a copy of the database like we did last time, for testing.

**Comment by dimitri** [comment]
The `tinyint` datatype should already be casted to `smallint`. You can force that through using the `CAST` clause in the load file:

    CAST type tinyint to smallint

Which version of pgloader are you using?

**Comment by BoiDareia** [comment]
I tryied to force it and it didn't work as well. Will be creating a test case for you to try an see the situation. 

Iam using:

 pgloader version "3.3.2~devel"
compiled with SBCL 1.3.11-1.el7

**Comment by dimitri** [comment]
Can you try with current sources from the master's branch, just in case? Thanks.

**Comment by BoiDareia** [comment]
Will do and report afterwards.

**Comment by BoiDareia** [comment]
Same ERROR with master's branch sources:

**2017-03-21T11:24:56.064000Z NOTICE CREATE TABLE public.utilizperfis 
(
  id        tinyint not null,
  perfil    text not null,
  descricao text not null
);
2017-03-21T11:24:56.066000Z ERROR Database error 42704: type "tinyint" does not exist**

**Comment by dimitri** [comment]
Given https://github.com/dimitri/pgloader/blob/master/src/sources/mssql/mssql-cast-rules.lisp#L30 I am quite surprised so I think we need a test case to reproduce...

**Comment by BoiDareia** [comment]
You already have one on your email. 👍
