### ISSUE TITLE
"drop indexes" fails with index names that need quoting

### ISSUE THREAD

**Issue by davidread** [dimitri/pgloader#530]
I get this error when using "WITH drop indexes" for the indexes whose names begin with a number:
```
2017-03-31T12:41:50.257000Z ERROR Database error 42601: syntax error at or near ".40e7"
QUERY: DROP INDEX IF EXISTS public.40e7e6d8b60115dbc276bec5b8b05f0f433d3adf;
```
It works fine for indexes with names starting with a letter.

In psql it works if I use quoting:
```
# DROP INDEX IF EXISTS public.40e7e6d8b60115dbc276bec5b8b05f0f433d3adf;
ERROR:  syntax error at or near ".40e7"
LINE 1: DROP INDEX IF EXISTS public.40e7e6d8b60115dbc276bec5b8b05f0f...
                                   ^
# DROP INDEX IF EXISTS public."40e7e6d8b60115dbc276bec5b8b05f0f433d3adf";
DROP INDEX
```
I'm using latest pgloader, built from source.

**Comment by dimitri** [comment]
Please build from sources again (after having `git pull`ed the most recent ones), your bug should be fixed now!

**Comment by davidread** [comment]
That's brilliant!! This all works for me now :)
