### ISSUE TITLE
FATAL An unhandled error condition has been signalled

### ISSUE THREAD

**Issue by abournier** [dimitri/pgloader#531]
Hello,

Just using the script. It works like a charm with default values, converting from MySQL:

```
LOAD DATABASE
FROM mysql://root:pass@localhost/database
INTO postgresql://admin:pass@localhost/database
```

But I would like to have tables with datetimes without time zone, so I tried this:

```
LOAD DATABASE
FROM mysql://root:pass@localhost/database
INTO postgresql://admin:pass@localhost/database
CAST type datetime to timestamp without time zone;
```

Datetime is MYSQL datetime type.

This is the error obtained:

```
FATAL An unhandled error condition has been signalled: At

  INTO postgresql://admin:password@localhost/database
  CAST type datetime to timestamp without time zone;
  
                                      ^ (Line 4, Column 36, Position 146)

In context MYSQL-OPTIONS:

While parsing MYSQL-OPTIONS. Expected:

     the character Tab
  or the character Newline
  or the character Return
  or the character Space
  or the string "--"
  or the string "/*"
  or the string "batch"
  or the string "concurrency"
  or the string "create"
  or the string "data"
  or the string "disable"
  or the string "downcase"
  or the string "foreign"
  or the string "include"
  or the string "max"
  or the string "no"
  or the string "preserve"
  or the string "quote"
  or the string "reset"
  or the string "schema"
  or the string "truncate"
  or the string "uniquify"
  or the string "workers"
...
```

My goal is:
- create tables withe datetimes timezone
- if possible, migrate only schemas first, then data 5 I saw the option "no create database" but i there an option "no create content" ?

So that I can modify my tables structure before the migration. (for example I want to change BIGINT to SMALLINT for some tables before migrating content)

Thanks.

**Comment by dimitri** [comment]
I think the datatype name parser in the cast rule is not prepared for multiple words type identifier, so just try using "timestamp" as the type name here? (that means no timezone in PostgreSQL).

That said, unless you are implementing a calendaring system meant to schedule meetings across TZ, I would be very surprised that removing the timezone support is anything but a disaster waiting to happen. Consider very carefully what you are doing it, and if not so sure, just keep the `timestamptz` target.

**Comment by abournier** [comment]
Using only timestamp seems to work well ! Nice.
Yes, I don't want timezone, my MySQL database is using UTC datetime to manage a sync engine. I need these exact UTC dates in Postgres too.

**Comment by dimitri** [comment]
Using `timestamp with time zone` is actually using UTC, and allows you to then display the information in whichever Time Zone you need it. Have a careful read at https://www.postgresql.org/docs/current/static/datatype-datetime.html#datatype-timezones again, would be my advice.
