### ISSUE TITLE
MySQL single quote escape issue

### ISSUE THREAD

**Issue by rangerer** [dimitri/pgloader#533]
If the source database includes stupidly (but valid) escaped defaults like

    CREATE TABLE x ( y VARCHAR(20) DEFAULT '''z''' )

The resulting PostgreSQL statement will be

    CREATE TABLE x ( y VARCHAR(20) DEFAULT ''z'' )

which is not going to work.

**Comment by rangerer** [comment]
A possible work-around is to change the default values via

    ALTER TABLE x MODIFY COLUMN y VARCHAR(20) DEFAULT 'z'

**Comment by dimitri** [comment]
I don't see a clean way to detect that without implementing PostgreSQL literal parser and I am not sure I want to do that. Also, what is the actual value inserted in MySQL rows with that notation? I'd rather not play that game...

My understanding is that the error is clear enough that you can act on it with a work around like proposed, and that it happens right before the migration happens in pgloader, so it's easy to fix and happens at a convenient timing in the process.

Can we agree to live with that limitation in pgloader?

**Comment by rangerer** [comment]
I totally agree with you that its not worth the effort to implement literal parsing!

Thanks for the super-fast response!

**Comment by dimitri** [comment]
Also, you can say `cast column x.y to text drop default` so that it just works for pgloader and that you can still use it in a CI environment to prepare for your migration. Maybe we could implement support for actually editing the default value from the CAST rules?
