### ISSUE TITLE
migrate mysql to postgresql,  column name "oid" conflicts with a system column name error

### ISSUE THREAD

**Issue by rchen9012** [dimitri/pgloader#536]
pgloader mysql://root@localhost/test postgresql:///test

I had make sure there's no "oid" column name, but this error keep popping up.  Any idea?

**Comment by dimitri** [comment]
Have a look at the PostgreSQL docs: https://www.postgresql.org/docs/current/static/ddl-system-columns.html.

> The object identifier (object ID) of a row. This column is only present if the table was created using WITH OIDS, or if the default_with_oids configuration variable was set at the time. This column is of type oid (same name as the column); see Section 8.18 for more information about the type.

Did you create your tables with the OIDS option? Which version of PostgreSQL are you targetting?
