### ISSUE TITLE
Funny trick when build pgloader with ccl

### ISSUE THREAD

**Issue by kevin2seedlink** [dimitri/pgloader#541]
Hi, I'm trying to build pgloader with ccl. The funny thing is when I use

```
> ln -s /usr/local/src/scripts/ccl64 /usr/local/bin/ccl64
> make CL=ccl64 pgloader  
```

It reports error  
```
> To load "buildapp": 
>  Install 1 Quicklisp release: 
>  buildapp 
>  ; Fetching #<URL "http://beta.quicklisp.org/archive/buildapp/2015-12-18/buildapp-1.5.6.tgz">
>  ; 16.00KB
> \==================================================
> 16,389 bytes in 0.00 seconds (29152.79KB/sec)
> ; Loading "buildapp"
> [package buildapp]...........
> \> Error: Error #<SILENT-EXIT-ERROR #x302000FB6C4D>
> \> While executing: (:INTERNAL MAIN), in process listener(1).
> \> Type :GO to continue, :POP to abort, :R for a list of available restarts.
> \> If continued: Skip evaluation of (buildapp:build-buildapp "build/bin/buildapp.ccl")
> \> Type :? for other options. 
> 1 \> (quit)  
```

But If I use
```
> ln -s /usr/local/src/scripts/ccl /usr/local/bin/ccl64
> make CL=ccl pgloader  
```

It works!

What's going on here?

**Comment by dimitri** [comment]
I don't think we have enough information on your output to really understand what's happening here yet... is it possible that there's more information not on the screen?

**Comment by kxjhlele** [comment]
build/bin/buildapp.ccl      --logfile /tmp/build.log                \
                                                 \
                         --sbcl ccl64                            \
                         --asdf-path .                           \
                         --asdf-tree build/quicklisp/local-projects     \
                         --manifest-file build/manifest.ql             \
                         --asdf-tree build/quicklisp/dists              \
                         --asdf-path .                           \
                         --load-system pgloader               \
                         --load src/hooks.lisp                   \
                         --entry pgloader:main                   \
                         --dynamic-space-size 4096         \
                                             \
                         --output build/bin/pgloader.tmp
/root/ccl/scripts/ccl: 48: exec: /root/ccl/lx86cl: not found
Fatal error in "buildapp" : Error #<SILENT-EXIT-ERROR #x30200059FFAD>
Makefile:136: recipe for target 'build/bin/pgloader' failed
make: *** [build/bin/pgloader] Error 255

uname -a
Linux debian0 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux


cd /root/ccl/scripts/
mv ccl ccl86
ln -s ccl64 ccl
make CL=ccl pgloader  is ok

**Comment by dimitri** [comment]
Looks like a problem with either CCL (unlikely) or buildapp (more likely). Will investigate, thanks for the report.
