### ISSUE TITLE
I don't get it

### ISSUE THREAD

**Issue by peebles** [dimitri/pgloader#547]
I did an "apt-get install pgloader" on Ubuntu 16.04.  Just cut and paste quick start example, it complains about the command line:

```bash
pgloader --type csv                                 \
         --field id --field field                        \
         --with truncate                                \
         --with "fields terminated by ','"       \
         ./test/data/matching-1.csv              \
         postgres:///pgloader?tablename=matching
```

Yes, I know the file does not exist and the connection string is not right, but I am trying to understand how this command line works.  My own real attempt fails for the same reason.

```bash
pgloader --type csv --field timestamp,cameraId,data --with "fields terminated by ','" --with "skip header = 1" ./02eba5cb-0f77-4825-bbcb-c2d45ea9f7b7.csv 'postgresql:///postgres/metadb?table=message'
pgloader [ option ... ] command-file ...
  --help -h                       boolean  Show usage and exit. 
  --version -V                    boolean  Displays pgloader version and exit. 
  --quiet -q                      boolean  Be quiet 
  --verbose -v                    boolean  Be verbose 
  --debug -d                      boolean  Display debug level information. 
  --client-min-messages           string   Filter logs seen at the console  (default: "warning")
  --log-min-messages              string   Filter logs seen in the logfile  (default: "notice")
  --summary -S                    string   Filename where to copy the summary 
  --root-dir -D                   string   Output root directory.  (default: #P"//tmp/pgloader//")
  --upgrade-config -U             boolean  Output the command(s) corresponding to .conf file for
                                           v2.x 
  --list-encodings -E             boolean  List pgloader known encodings and exit. 
  --logfile -L                    string   Filename where to send the logs. 
  --load-lisp-file -l             string   Read user code from files 
  --self-upgrade                  string   Path to pgloader newer sources 
```

**Comment by peebles** [comment]
I'd also like to note that after first installing pgloader, my first attempt bombed with the complaint:

  Error opening shared object "libsqlite3.so.0":
  libsqlite3.so.0: cannot open shared object file: No such file or directory.

why is there an sqlite3 dependency?  And if there really is (for what I am doing) then why didn't the apt-get install resolve it?

**Comment by peebles** [comment]
LOAD CSV
      FROM './02eba5cb-0f77-4825-bbcb-c2d45ea9f7b7.csv' (timestamp, cameraId, data)  
      INTO postgresql:///postgres/db?table=messages (timestamp, cameraId, data)
      
      WITH truncate,  
           skip header = 1,  
           fields optionally enclosed by '"',  
           fields escaped by double-quote,  
           fields terminated by ','  
 
       SET client_encoding to 'latin1',  
           work_mem to '12MB',  
           standard_conforming_strings to 'on'

pgloader PGLOAD.cmd:

```bash
# pgloader PGLOAD.cmd
An unhandled error condition has been signalled:
   Could not parse subexpression ";" when parsing

 Expression PGLOADER.PARSER::COMMANDS
    Subexpression (+ PGLOADER.PARSER::COMMAND)
    Subexpression PGLOADER.PARSER::COMMAND
    Subexpression (AND
                   (OR PGLOADER.PARSER::LOAD-ARCHIVE
                       PGLOADER.PARSER::LOAD-CSV-FILE
                       PGLOADER.PARSER::LOAD-FIXED-COLS-FILE
                       PGLOADER.PARSER::LOAD-DBF-FILE
                       PGLOADER.PARSER::LOAD-IXF-FILE
                       PGLOADER.PARSER::LOAD-MYSQL-DATABASE
                       PGLOADER.PARSER::LOAD-SQLITE-DATABASE
                       PGLOADER.PARSER::LOAD-SYSLOG-MESSAGES)
                   PGLOADER.PARSER::END-OF-COMMAND)
    Subexpression PGLOADER.PARSER::END-OF-COMMAND
    Subexpression (AND PGLOADER.PARSER::IGNORE-WHITESPACE #\;
                       PGLOADER.PARSER::IGNORE-WHITESPACE)
    Subexpression ";"

  Encountered at:
    LOAD CSV
  FROM './02eba
    ^ (Line 1, Column 0, Position 0)


; 
; compilation unit aborted
;   caught 1 fatal ERROR condition
```

**Comment by phy25** [comment]
Sorry I don't look into this throughly, but if you installed pgloader via apt-get or something, it's v2 which is not supported here anymore. You can try compile with source here on GitHub, which is the latest v3.

**Comment by peebles** [comment]
I've managed to get much further using your docker container.  Although, if I change the base image to ubuntu:16.04, the build fails.  So I kept it at debian:jesse and it builds and runs.

**Comment by peebles** [comment]
You ought to consider pushing a prebuilt docker image to Dockerhub.  Then it becomes more strait forward I think.  After all, I would guess for most folks, this sort of thing is a one-shot-deal.  I spend almost 4 hours on it.

```bash
docker run --rm --name pgloader -v $(pwd)/ddb-data:/data --link postgres --workdir /data pgloader:debian bash -c "sh ./import.sh"
```

**Comment by dimitri** [comment]
Hi, sorry it's been taking you more time than you wanted. Your load file is missing the final `;` as per the error message (_ Could not parse subexpression ";" when parsing_). Please try again with the file fixed. As for the `libsqlite` dependency, yes it's required and yes the packaging should take care of that...
