### ISSUE TITLE
Unable To Copy Data From MySql Database Without Dropping Constraints

### ISSUE THREAD

**Issue by TheServerAsterisk** [dimitri/pgloader#549]
I have the following .load file

```
LOAD DATABASE
     FROM      mysql://user:password@remotelocation/mydbname
     INTO postgresql://user@localhost/dbname

 WITH data only,truncate, workers = 8, concurrency = 1

  SET maintenance_work_mem to '128MB',
      work_mem to '12MB',
      search_path to 'mydbname'

 CAST type datetime to timestamptz drop default drop not null using zero-dates-to-null,
      type mediumint with extra auto_increment to bigserial,
      type date drop not null drop default using zero-dates-to-null,
      type tinyint to boolean using tinyint-to-boolean;
```
I get an error like so

```
Database error 2BP01: cannot drop constraint random_pkey on table random because other objects depend on it. 
```
If I understand the docs correctly it shouldn't be dropping any indexes. Then again if it does and I misread how do I deal with the issue? 

You can find the full debug output [here](https://gist.github.com/TheServerAsterisk/a96043ed8fc9e0ed1079140816c8707e)

Also, I am using pgloader 3.3.2 and the postgres' version is 9.6

**Comment by dimitri** [comment]
Please try with the option `include no drop`, as per default we indeed drop constraints: keeping them slows down the data loading a lot, it's better to drop them and create them again once the data is loaded. This default option assumes no concurrency traffic tho.

Also, it might be that version 3.3.2 will not play along friendly here, so if `include no drop` doesn't help you at all, please consider building from current source (or using the docker image at https://hub.docker.com/r/dimitri/pgloader/) as several bug fixes have been committed recently in this area.

**Comment by TheServerAsterisk** [comment]
The `include no drop` didn't work for 3.3.2. However, building from source allowed me to move beyond that error message. Thanks.

**Comment by dimitri** [comment]
Thanks for feedback!
