### ISSUE TITLE
ALTER TABLE broken when importing from sqlite?

### ISSUE THREAD

**Issue by bdharrington7** [dimitri/pgloader#552]
### Versions
pgloader version (on docker):
```
pgloader version "3.3.0.51~devel"
compiled with SBCL 1.2.4.debian
```

sqlite version: 3.x
Postgres version: 9.6.2

### Issue:
I saw that an ALTER TABLE clause was added in response to #228, but I tried it when importing a sqlite3 database and was met with an error. The syntax was taken from [the examples](http://pgloader.io/howto/pgloader.1.html) under LOAD MYSQL DATABASE

Here is the load file I'm using:

```
LOAD DATABASE  
    FROM '/data/db.sqlite'
    INTO postgresql://postgres@172.16.123.1:5432/postgres

WITH reset sequences, create tables, include drop, create indexes
INCLUDING ONLY TABLE NAMES LIKE 'modules', 'versions'
ALTER TABLE NAMES MATCHING 'modules' RENAME TO 'modules_imported'
SET work_mem to '200MB', maintenance_work_mem to '512 MB';

```

And the error I get :
```
An unhandled error condition has been signalled: At

  ALTER TABLE NAMES MATCHING 'modules' RENAME TO 'modules_imported'
  ^ (Line 7, Column 1, Position 236)

Could not parse KW-AFTER. Expected:

  the string "after"

Reached via

     AFTER-LOAD
  -> (AND KW-AFTER KW-LOAD (+ (OR LOAD-DO LOAD-EXECUTE)))
  -> KW-AFTER
  -> (AND IGNORE-WHITESPACE (~ "after") IGNORE-WHITESPACE)
  -> "after"

Could not parse KW-BEFORE. Expected:

  the string "before"

Reached via

     BEFORE-LOAD
  -> (AND KW-BEFORE KW-LOAD (+ (OR LOAD-DO LOAD-EXECUTE)))
  -> KW-BEFORE
  -> (AND IGNORE-WHITESPACE (~ "before") IGNORE-WHITESPACE)
  -> "before"
...
```

The entire stack trace, if needed, is here: https://pastebin.com/eAjsqHn5

**Comment by dimitri** [comment]
The `ALTER TABLE` clause is not supported for SQLite as of yet... I will see what it entails to add support to it, unless you want to have a look?

**Comment by bdharrington7** [comment]
Ah, I was hoping it was just supported across databases. Unfortunately, I don't think I'll have enough time in the near future to make a PR... For now I can work around it using the `AFTER LOAD DO` statement

**Comment by dimitri** [comment]
Here you have the support for `ALTER TABLE` for SQLite. If you want to avoid that extra `ALTER TABLE` statement after the load, you can build pgloader from sources and have the conversion happen in pgloader itself instead.

**Comment by radusuciu** [comment]
A little late to the party but thank you for this!
