### ISSUE TITLE
Unable to use pgloader on a dedicated server because of memory limit

### ISSUE THREAD

**Issue by abournier** [dimitri/pgloader#553]
Hello,

I used pgloader on my mac, then on my test server (Ubuntu 14.04 VPS - 2Gb ram). It works well.
Now I installed it on my dedicated server (Ubuntu 14.04 64 Gb ram !) with `apt-get install pgloader`.

Then I tried to run it after creating my migration.lisp script:
`~# pgloader migration.lisp`

I got:

```
mmap: wanted 1040384 bytes at 0x20000000, actually mapped at 0x61b83f9fa000
ensure_space: failed to validate 1040384 bytes at 0x20000000
(hint: Try "ulimit -a"; maybe you should increase memory limits.)
```

So I run **ulimit -a**:

> core file size          (blocks, -c) 0
> data seg size           (kbytes, -d) unlimited
> scheduling priority             (-e) 0
> file size               (blocks, -f) unlimited
> pending signals                 (-i) 257261
> max locked memory       (kbytes, -l) 64
> max memory size         (kbytes, -m) unlimited
> open files                      (-n) 1024
> pipe size            (512 bytes, -p) 8
> POSIX message queues     (bytes, -q) 819200
> real-time priority              (-r) 0
> stack size              (kbytes, -s) 8192
> cpu time               (seconds, -t) unlimited
> max user processes              (-u) 257261
> virtual memory          (kbytes, -v) unlimited
> file locks                      (-x) unlimited

Well, I don't know why and what I need to change in memory size... and didn't understand why it works on my simple VPS and not on the dedicated server.
Thanks in advance,

EDIT1: I tried to build it from source and encountered the same error.
EDIT2: I tried to downcrease the memory size with `make DYNSIZE=128` but got the same error

**Comment by dimitri** [comment]
It might be that your server implements ASLR (Address Space Layout Randomization), which SBCL doesn't support at the moment (at least in my understanding). See Ubuntu help about that such as https://askubuntu.com/questions/318315/how-can-i-temporarily-disable-aslr-address-space-layout-randomization
