### ISSUE TITLE
Can't connect to MySQL. Error 1045

### ISSUE THREAD

**Issue by utkgarg** [dimitri/pgloader#554]
I am getting the following error after running the pgloader command:

> An unhandled error condition has been signalled:
>    Failed to connect to mysql at "localhost" (port 3306) as user "root": MySQL Error [1045]: "Access denied for user 'root'@'localhost' (using password: NO)"

**Comment by dimitri** [comment]
It looks like a plain MySQL error message, right? Can you try the same connection string or parameters with other tools, such as the plain `mysql` client.

**Comment by utkgarg** [comment]
Yes it seems like a plain mysql password.
I am able to access mysql through the usual command i.e. 
> mysql -u root -p

It then asks for password. 
Since the error is showing 

> using password : NO,

 , maybe I have to pass the password too in the command. Is there any provision for it?

**Comment by dimitri** [comment]
Yes of course, please consider reading the documentation... https://github.com/dimitri/pgloader/blob/master/pgloader.1.md#source-connection-string

**Comment by annapogorelova** [comment]
@dimitri the link you provided is not accessible now. I am having the same issue as @utkgarg  now.
