### ISSUE TITLE
Using the GETENV command in the loader file

### ISSUE THREAD

**Issue by bdharrington7** [dimitri/pgloader#555]
pgloader version:
```
# pgloader -V
pgloader version "3.3.0.51~devel"
compiled with SBCL 1.2.4.debian
```

I need to have a dynamic way of loading sqlite databases into Postgres, and when I found the `GETENV` option, I thought this would solve that issue. When I use it though, pgloader fails with a `could not parse WHITESPACE` error in a seemingly unrelated part of the command file. 

Here's the command file I tried:
```
LOAD DATABASE
    FROM GETENV 'DBPATH'
    INTO postgresql://dri@172.16.123.1:5432/dri

WITH reset sequences, create tables, include drop, create indexes
INCLUDING ONLY TABLE NAMES LIKE 'modules', 'versions'
SET work_mem to '200MB',
	maintenance_work_mem to '512 MB',
	search_path to 'import'
BEFORE LOAD DO
	$$ CREATE SCHEMA IF NOT EXISTS import; $$;
```

and I execute with:
```
export DBPATH=/data/db-file.sqlite; pgloader /data/command-file 
```

The error I get is:

```
An unhandled error condition has been signalled: At

  INCLUDING ONLY TABLE NAMES LIKE 'modules', 'versions'
                             ^ (Line 6, Column 28, Position 182)

Could not parse WHITESPACE. Expected:

     the character Space
  or the character Tab
  or the character Newline
  or the string "--"
  or the string "/*"

Reached via

     WHITESPACE
  -> (+ (OR Space Tab Newline Newline COMMENTS))
  -> (OR Space Tab Newline Newline COMMENTS)
  -> COMMENTS
  -> (OR SINGLE-LINE-COMMENT MULTI-LINE-COMMENT)
  -> MULTI-LINE-COMMENT
  -> (AND "/*" (+ (NOT "*/")) "*/")
  -> "/*"

Could not parse KW-MATCHING. Expected:

     the character Space
  or the character Tab
  or the character Newline
  or the string "--"
  or the string "/*"
  or the string "matching", disregarding case
```

When I run the loader file normally, everything works as expected:
```
LOAD DATABASE
    FROM '/data/db-file.sqlite'
    INTO postgresql://dri@172.16.123.1:5432/dri

WITH reset sequences, create tables, include drop, create indexes
INCLUDING ONLY TABLE NAMES LIKE 'modules', 'versions'
SET work_mem to '200MB',
	maintenance_work_mem to '512 MB',
	search_path to 'import'
BEFORE LOAD DO
	$$ CREATE SCHEMA IF NOT EXISTS import; $$;
```

**Comment by dimitri** [comment]
The problem seems to be that the `getenv` integration in the parsing is wrong, meaning that the parser has already decided it is processing another clause even when it reads the source URL. I am not yet sure how to fix that, will have a look next week. Thanks for the bug report!

**Comment by dimitri** [comment]
Ok it's now kind of fixed. The `GETENV` is no longer supported. Now instead, pgloader implements the Mustache templating system with the addition of being able to look-up environment for variable values. Consider the following patch to your command file:

```diff
-    FROM GETENV 'DBPATH'
+    FROM '{{DBPATH}}'
```

Then please build pgloader from fresh sources and try again.

**Comment by snusnu** [comment]
While it seems that the mustache templating works for the `FROM` clause, I cannot get it to work for the `INTO` clause. `GETENV` doesn't work either (even though the parser error mentions it as one possible alternative).

This means that in order to invoke `pgloader` in a scripted environment with varying postgres target connection settings (e.g. database names), we're currently left with having to treat the `.load` file as being a template and perform manual (`sed`) replacements prior to feeding it to `pgloader`. I've no experience using LISP, but it seems to me that "target url from environment" support was removed in [this patch](https://github.com/dimitri/pgloader/commit/f719d2976d97f5e570881aca78f3d9e865166e29#diff-b108bef867543578731f5a7e71c04da5R217)

Could mustache support be added to the `FROM` clause as well?

For reference, here's the error I get:

```
KABOOM!
FATAL error: At

  FROM '{{MYSQL_DATABASE_URL}}'
  INTO '{{POSTGRES_DATABASE_URL
       ^ (Line 4, Column 5, Position 50)

In context TARGET:

While parsing TARGET. Expected:

     the character Tab
  or the character Newline
  or the character Return
  or the character Space
  or the string "--"
  or the string "/*"
  or the string "getenv"
  or the string "pgsql"
  or the string "postgres"
  or the string "postgresql"
```

PS: Apologies for getting back so late, I really appreciated your quick response at #645. Thanks a lot for making `pgloader` available for free, it's great!

**Comment by dimitri** [comment]
I just did a quick test with the following load file and the command line, and it works fine. Which version of pgloader are you using?

    PG_DB_URI=pgsql:///pgloader DBPATH=sqlite/sqlite.db ./build/bin/pgloader ./test/sqlite-env.load

```
load database
     from '{{DBPATH}}'
     into {{PG_DB_URI}}
```

**Comment by snusnu** [comment]
Thanks for taking a look at it so quickly! I had tried that before and unfortunately, I keep getting the same error:

```
sb-impl::*default-external-format* :UTF-8
tmpdir: #P"/tmp/pgloader/"
KABOOM!
FATAL error: At

  FROM '{{MYSQL_DATABASE_URL}}'
  INTO {{POSTGRES_DATABASE_URL}
       ^ (Line 4, Column 5, Position 50)

In context TARGET:

While parsing TARGET. Expected:

     the character Tab
  or the character Newline
  or the character Return
  or the character Space
  or the string "--"
  or the string "/*"
  or the string "getenv"
  or the string "pgsql"
  or the string "postgres"
  or the string "postgresql"
Date/time: 2017-11-23-11:14An unhandled error condition has been signalled: At

  FROM '{{MYSQL_DATABASE_URL}}'
  INTO {{POSTGRES_DATABASE_URL}
       ^ (Line 4, Column 5, Position 50)

In context TARGET:

While parsing TARGET. Expected:

     the character Tab
  or the character Newline
  or the character Return
  or the character Space
  or the string "--"
  or the string "/*"
  or the string "getenv"
  or the string "pgsql"
  or the string "postgres"
  or the string "postgresql"


Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10091D47F3}>
0: ((LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX))
1: (SB-IMPL::CALL-WITH-SANE-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX) {100953516B}>)
2: (SB-IMPL::%WITH-STANDARD-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX) {100953513B}>)
3: (PRINT-BACKTRACE :STREAM #<SB-IMPL::STRING-OUTPUT-STREAM {1009331053}> :START 0 :FROM :DEBUGGER-FRAME :COUNT 4611686018427387903 :PRINT-THREAD T :PRINT-FRAME-SOURCE NIL :METHOD-FRAME-STYLE NIL)
4: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE-TO-STREAM #<SB-IMPL::STRING-OUTPUT-STREAM {1009331053}>)
5: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE #<ESRAP:ESRAP-PARSE-ERROR #<ESRAP::FAILED-PARSE PGLOADER.PARSER::TARGET @50> @50 {1009330ED3}> :OUTPUT NIL :IF-EXISTS :APPEND :VERBOSE NIL)
6: ((FLET #:H0 :IN PGLOADER::MAIN) #<ESRAP:ESRAP-PARSE-ERROR #<ESRAP::FAILED-PARSE PGLOADER.PARSER::TARGET @50> @50 {1009330ED3}>)
7: (SIGNAL #<ESRAP:ESRAP-PARSE-ERROR #<ESRAP::FAILED-PARSE PGLOADER.PARSER::TARGET @50> @50 {1009330ED3}>)
8: (ERROR ESRAP:ESRAP-PARSE-ERROR :TEXT "LOAD DATABASE
```

From your example command, I take it that you're running a build from latest sources. That's unfortunately not an easy enough option for me. I'm running the latest version available via `apt`.

**Comment by dimitri** [comment]
You need to have a copy of pgloader with the following patch: https://github.com/dimitri/pgloader/commit/f719d2976d97f5e570881aca78f3d9e865166e29 ; which is not distributed in the 3.4.1 version of the software.

**Comment by lb1c** [comment]
I had a similar issue today, then i obtained the sources and build a pgloader binary from the commit 48af01dbbc5c2145ff508c0585c7bfd50a3589ef .
This should include the patch you mentioned f719d29 but it still breaks and even in the FROM clause, not only the INTO:
```
$ env | grep SOURCEFILE
SOURCEFILE=hotels.csv
```
Load file:
https://gist.github.com/lb1c/b33dbff4604f06090279e8385513470a

Logoutput
https://gist.github.com/lb1c/ab836887e8dbf583d541e62a87817719

**Comment by dimitri** [comment]
I failed to reproduce your example and added a test case in the test/ directory, as you can see in previous attached patch. Can you double check that the environment variable is set when you run pgloader?

```
~/dev/pgloader export SOURCEFILE=data/2013_Gaz_113CDs_national.txt
~/dev/pgloader ./build/bin/pgloader /Users/dim/dev/pgloader/test/csv-districts-env.load
             table name     errors       rows      bytes      total time
-----------------------  ---------  ---------  ---------  --------------
                  fetch          0          0                     0.005s
            before load          0          2                     0.016s
-----------------------  ---------  ---------  ---------  --------------
   "public"."districts"          0        440    29.3 kB          0.075s
-----------------------  ---------  ---------  ---------  --------------
        Files Processed          0          1                     0.018s
COPY Threads Completion          0          2                     0.084s
-----------------------  ---------  ---------  ---------  --------------
      Total import time          ✓        440    29.3 kB          0.102s
```

**Comment by lb1c** [comment]
Found the issue, i didn't had the `ruby-mustache` package installed on my system.
From the docs i thoughts this would be embedded in pgloader. After installing the package my (little bit modified) script works:
https://gist.github.com/lb1c/cfb38c250f9702062f39f69b0a1ee70a 

Maybe improving the docs at the mustache section would be an appropriate solution?

**Comment by dimitri** [comment]
We're using https://github.com/kanru/cl-mustache and I don't think this requires any external package. Your assumption that pgloader embeds the mustache templating is right... that's strange.

**Comment by lb1c** [comment]
But as you can see in my original gist is, that the filename is searched with the mustache placeholder instead of the actual value. Shouldn't the debug mode print out the generated string with the mustache replacements?

**Comment by dimitri** [comment]
My guess would be that you tested with a pgloader version that didn't have the feature, that is, that you didn't use the binary you compiled, or something like that. That's a classic...
