### ISSUE TITLE
MySQL Error: 1055

### ISSUE THREAD

**Issue by utkgarg** [dimitri/pgloader#557]
I am getting the following error when running the pgloader command:

> MySQL Error [1055]: "Expression #6 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'information_schema.rc.UPDATE_RULE' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by"

I can't figure out what is the problem.

**Comment by dimitri** [comment]
Reminds me of a very old bug we had in pgloader MySQL catalog queries. Which version are you using? if not current, can you try building from fresh sources?

**Comment by utkgarg** [comment]
I am using MySQL 5.7.18.

**Comment by dimitri** [comment]
Ok normally the bug I was thinking about is fixed in 3.3.2, can you upgrade please? consider building from sources...

https://github.com/dimitri/pgloader/commit/44b9ec81c9becdbd55f3981988084ffd82de240d

**Comment by utkgarg** [comment]
Yes. Thanks the bug is resolved.

**Comment by rjmyers** [comment]
Hi dimitri,

I'm getting the exact same error as utkgarg except I don't know how to upgrade pgloader. I also have pgloader 3.2.2 installed, as he did.

> $ pgloader mysql://<password>:<username>@localhost/<dbname> pgsql://<password>:<username>@localhost/<dbname>
> 2017-08-16T19:55:00.028000Z LOG Main logs in '/tmp/pgloader/pgloader.log'
> 2017-08-16T19:55:00.035000Z LOG Data errors in '/tmp/pgloader/'
> An unhandled error condition has been signalled:
>    MySQL Error [1055]: "Expression #6 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'information_schema.rc.UPDATE_RULE' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by"

I'm a fledgling Linux person/programmer so if you are able to provide simple step by step instructions on how to do this that would be really greatly appreciated.

Best,

Rupert

**Comment by dimitri** [comment]
You can build from sources if you want: clone the git repository then `make`, with the build dependencies in place as per the README at https://github.com/dimitri/pgloader#build-from-sources. As far as upgrades go, it all depends on the system you're using and how you installed pgloader in there, so I will need more information to be able to help you.

**Comment by rjmyers** [comment]
Dear dimitri, 

I managed to solve the issue and use pgloader to convert my MySQL database. The issue was that I didn't realise that I needed to click the green download button on this page: https://github.com/dimitri/pgloader#build-from-sources and then after unzipping the files, point to the pgloader file in one of the directories.

Thanks a lot for your help.

Rupert
