### ISSUE TITLE
max parallel create index = 1 cause Could not parse WHITESPACE.

### ISSUE THREAD

**Issue by jonny64** [dimitri/pgloader#558]
> docker run --rm --name pgloader \
> 		-v $(CURDIR):/var/projects/ \
> 		-v $(CURDIR):/tmp \
> 		dimitri/pgloader:latest \
> 		pgloader \
> 		--log-min-messages debug \
> 		--client-min-messages info \
> 		/var/projects/pg.load

pg.load:
> LOAD DATABASE
> -- something
> WITH
> 	include drop,
> 	create tables,
> 	create indexes,
> 	max parallel create index = 1,
> 	workers = 8,
> 	concurrency = 1,
> 	batch rows = 1000
> 

results in 

> An unhandled error condition has been signalled: At
> 
>         max parallel create index = 1,
>     (Line 11, Column 2, Position 283)
> 
> Could not parse KW-NO. Expected:
> 
>      the character Space
>   or the character Tab
>   or the character Newline
>   or the string "--"
>   or the string "/*"
>   or the string "no", disregarding case
>

**Comment by dimitri** [comment]
Which version of pgloader are you using? It looks like you're using something that was released before we added that option...

**Comment by jonny64** [comment]
I've used docker dimitri/pgloader:latest for the time of this post.
I've set `create no indexes` to workaround this issue .
