### ISSUE TITLE
[Feature] AFTER LOAD FORCE DO

### ISSUE THREAD

**Issue by andrewgy8** [dimitri/pgloader#560]
Im running into some issues when migrating my DB. Particularly the absence of the UNIQUE constraint in my sqlite DB on certain FKs.  Pgloader spits back and error when indexing:
`there is no unique constraint matching given keys for referenced table`

Instead of fixing these in SQLite, which is a huge headache in a highly relational DB, I have opted to go through with altering the tables in Postgres after the migration. After that,  I run the Indexing again.  And voila!, the tables are perfect.  

It would be a nice feature, if I could run these queries to fix the tables in the .load file, sort of like `After load do`, even if PgLoader runs into the error above.  

Any thoughts?

**Comment by dimitri** [comment]
I'm thinking that maybe a good answer to that kind of problems would be to extend the support we have in the catalog editing features in pgloader. We could maybe have `alter table` commands that would impact the MySQL catalog as loaded in pgloader's memory before it gets converted to a PostgreSQL catalog, and you could add the `UNIQUE` constraints there. Of course that requires a proper data set for the whole thing to work at the end.

**Comment by dimitri** [comment]
I think it should be solvable with the new support for the AFTER CREATE SCHEMA EXECUTE facility of current pgloader: https://pgloader.readthedocs.io/en/latest/pgloader.html#after-create-schema-execute.
