### ISSUE TITLE
Latest version of pgloader not getting installed

### ISSUE THREAD

**Issue by utkgarg** [dimitri/pgloader#562]
I am trying to install pgloader through command line on remote server with Ubuntu 14.04. But it is installing version 2.3.3 instead of version 3.3.2. I tried the following commands:
`sudo apt-get install pgloader`
`sudo apt install pgloader`

I was able to install version 3.3.2 on Ubuntu 16.04 with the second command.

**Comment by dimitri** [comment]
If I read https://packages.ubuntu.com/search?keywords=pgloader correctly then yes it's expected. Please consider using https://wiki.postgresql.org/wiki/Apt to get the latest version of pgloader available for your platform of choice.
