### ISSUE TITLE
[SQLite] PKs don't get transferred

### ISSUE THREAD

**Issue by bdharrington7** [dimitri/pgloader#563]
I'm running the latest pgloader (3.3.2~devel) on 21208980fd2b8e5403ba97f2743467fdc4d103c9 and I'm getting the error:

```
ERROR Database error 42830: there is no unique constraint matching given keys for referenced table "components"
QUERY: ALTER TABLE links ADD FOREIGN KEY(component_id) REFERENCES components(id) ON UPDATE NO ACTION ON DELETE NO ACTION
```

In the source database, the `id` column is the Primary Key, but when I look at the transferred DB in Postgres (even though it didn't finish), none of the columns on my tables that are Primary Keys in the source DB are defined as primary keys in the Postgres DB. 

```
postgres=# \d components
                             Table "public.components"
     Column     |  Type  |                        Modifiers                        
----------------+--------+---------------------------------------------------------
 id             | bigint | not null default nextval('components_id_seq'::regclass)
 component      | text   | 
 version        | text   | 
Indexes:
    "idx_40142_sqlite_autoindex_components_1" UNIQUE, btree (component, version)

postgres=#
```

I also tried adding the `disable triggers` statement, but it still throws that error
```
WITH no truncate, create tables, include drop, create indexes, reset sequences, disable triggers
```

**Comment by dimitri** [comment]
It should be that your Primary Keys are installed before pgloader runs the Foreign Key statements. Can you try again in verbose mode so that we see the SQL commands sent to PostgreSQL? If we see no `ALTER TABLE ... ADD PRIMARY KEY ... USING INDEX ...` in the logs, we will then have to inspect the source SQLite schema to see how those primary keys are handled.

**Comment by dimitri** [comment]
pgloader doesn't parse the `.schema` output, it uses `pragma` commands to have structure data about the table. Can you try and report the following?

```
$ sqlite3
> .headers on
> .mode column
> PRAGMA table_info(components);
> PRAGMA index_list(components);
> PRAGMA index_info(<name of the pk index);
```

What we look for in pgloader is that the column list for the PK index in `index_info` matches the list of columns marked `pk` in `table_info` for the table. That's how you find about it in SQLite apparently.

**Comment by bdharrington7** [comment]
```
sqlite> PRAGMA table_info(components);
cid         name        type        notnull     dflt_value  pk        
----------  ----------  ----------  ----------  ----------  ----------
0           id          INTEGER     0                       1         
1           component   TEXT        1                       0         
2           version     TEXT        1                       0         
```

```
sqlite> PRAGMA index_list(components);
seq         name                           unique      origin      partial   
----------  -----------------------------  ----------  ----------  ----------
0           sqlite_autoindex_components_1  1           u           0        
```

```
sqlite> PRAGMA index_info(sqlite_autoindex_components_1);
seqno       cid         name      
----------  ----------  ----------
0           1           component 
1           2           version 
```

So does this mean there needs to be a separate index on the `id` column? AFAIK Postgres will create an index on a column defined as a PK, is that not true (of either Postgresql or sqlite)?

**Comment by dimitri** [comment]
So in the SQLite catalogs we see a single index, and it is properly migrated to PostgreSQL by pgloader. I don't know why the primary key isn't listed in your pragma queries output here... reading the docs again at https://sqlite.org/pragma.html#pragma_index_info doesn't make the situation any clearer.

Is it possible that the Primary Key index is listed somewhere else? I now see in the docs the notion of a schema, can you see about that? You might have attached another databases and you can list them with `.databases` and then inquire `pragma <database_name>.index_list(components);`. I know that sounds fishy, it's all I can think of just now.

**Comment by zklaus** [comment]
I am running into the same problem. I boiled the database down to a minimal example (attached).
Just running
sqlite3 -batch test.db <pk_test.txt
pgloader --verbose test.db postgresql://postgres:mysecretpassword@localhost/test
Produces the same problem.


[pk_test.txt](https://github.com/dimitri/pgloader/files/1060325/pk_test.txt)

**Comment by zklaus** [comment]
I think I found the reason at least in my case: According to [this](http://www.sqlite.org/lang_createtable.html#rowid), sqlite will not create an index for a single column integer primary key and instead use its internal b-tree structure called rowid for the primary key.
Hence, no index that can be copied. The fix for the import then should be to manually create the index if it is a single column primary key of type integer.

**Comment by dimitri** [comment]
Thanks for digging what's happening there, and please consider building from current sources and test again, it should be fine now. Applies to both @zklaus and @bdharrington7 cases.

**Comment by zklaus** [comment]
Works for me, thanks!

**Comment by gjcarneiro** [comment]
I have the same problem, while trying to convert grafana db to postgresql.  Using pgloader (3.4.1+dfsg-1~pgdg14.04+1) ubuntu updated package on ubuntu 14.04.  So, assuming this 3.4.1 package is well built, it doesn't seem to fix it for me :(

**Comment by dimitri** [comment]
The 3.4.1 version of pgloader was released in July and the patch made it in June, so it should be good. Can you test with a fresh build from sources? if the bug is still present in some form, we will need to compile from sources again to check any fix I could come up with anyway...

**Comment by gjcarneiro** [comment]
I just built from git master, on my desktop instead of the server itself (on Ubuntu 14.04 it doesn't even build, on my desktop Ubuntu 17.10 it builds fine).  I did the migration again with the freshly built pgloader.  Still, no sequences in sight :(
```
grafana=> \d alert
                  Table "public.alert"
     Column      |           Type           | Modifiers 
-----------------+--------------------------+-----------
 id              | bigint                   | not null
[...]
Indexes:
    "idx_22532_alert_pkey" PRIMARY KEY, btree (id)
    "idx_22532_idx_alert_dashboard_id" btree (dashboard_id)
    "idx_22532_idx_alert_org_id_id" btree (org_id, id)
    "idx_22532_idx_alert_state" btree (state)
```

**Comment by gjcarneiro** [comment]
I ended up using [sequel](https://github.com/jeremyevans/sequel) for the migration, sorry!  sequel is excruciatingly slow to copy the rows data over (unlike pgloader), but it handled the schema migration very well.

**Comment by dimitri** [comment]
Can you send me your SQLite database, or another one that allows to reproduce the bug (and then fix it)? I might all depend on the SQLite version you had when creating the schema, and we need to have a deep look at how the catalogs represent the information that you're now missing in the migration.

Other than that, adding a sequence after the fact to the PostgreSQL database is easy enough, and can be from from the AFTER LOAD DO or AFTER LOAD EXECUTE commands.

**Comment by dimitri** [comment]
Thanks for providing me with a SQLite database from where I could easily reproduce the bug. It turns out it's nothing to do with SQLite internals ; pgloader code was looking at the right place. It's my mistake, the plumbing was left unfinished. It's now fixed and I could test it here. Please refresh your source copy and build again.

**Comment by jcmcken** [comment]
@dimitri I'm still running into this issue using the latest build as of this comment (e4dca1a). It works if the table already has data in it. But if the table is empty on the SQLite side, then on the PostgreSQL side, the primary key column is missing the autoincrement. When the app goes to actually populate an initial row, it fails because it says the ``id`` is ``NULL``

**Comment by jcmcken** [comment]
For a table that already had rows:

```
   Column   |           Type           |                       Modifiers                        | S
torage  | Stats target | Description
------------+--------------------------+--------------------------------------------------------+--
--------+--------------+-------------
id         | bigint                   | not null default nextval('dashboard_id_seq'::regclass) | p
lain    |              |
```

For one that doesn't:

```
   Column   |           Type           |   Modifiers   | Storage  | Stats target | Description
------------+--------------------------+---------------+----------+--------------+-------------
 id         | bigint                   | not null      | plain    |              |
```

**Comment by jcmcken** [comment]
It appears as though (based on the database I'm trying to migrate) if there are no rows in the table, SQLite doesn't create a sequence for the table, even though its ``CREATE`` statement definitely includes the ``AUTOINCREMENT`` primary key. The only surefire way to check it is to either check ``.schema`` or run something like:

```sql
SELECT name FROM sqlite_master WHERE tbl_name="<table>" AND sql LIKE "%AUTOINCREMENT%"
```

**Comment by dimitri** [comment]
Can you fix it after pgloader is done and before you use the database, with maybe the `AFTER LOAD` clause of the pgloader's command? It's a workaround, but the SQLite sequence code is already complex and I'll see later about adding test cases and fixes for the sequence not yet created situation...

**Comment by jcmcken** [comment]
Yep, that's what I'll have to do for now. Thanks
