### ISSUE TITLE
Version 3.3.2 not available on ubuntu 16.04.2 apt-get rep

### ISSUE THREAD

**Issue by utkgarg** [dimitri/pgloader#565]
I am trying to install pgloader on remote server which runs ubuntu 16.04.2. But the latest version of pgloader i.e. version 3.3.2 is not available on the apt-get repository. Version 3.2.2 is being installed, which shows some bug which is resolved in 3.3.2. I don't know how I can resolve this issue.

**Comment by dimitri** [comment]
I am surprised, seeing that https://apt.postgresql.org/pub/repos/apt/pool/main/p/pgloader/ contains in particular https://apt.postgresql.org/pub/repos/apt/pool/main/p/pgloader/pgloader_3.3.2%2bdfsg-1%7epgdg16.04%2b1_amd64.deb. Are you sure your setup is all good?

**Comment by utkgarg** [comment]
Okay. Thanks. The problem is solved.

**Comment by skyrocknroll** [comment]
You should add postgres ppa as mentioned here  https://www.postgresql.org/download/linux/ubuntu/
