### ISSUE TITLE
Not supported type SYB-MSDATE

### ISSUE THREAD

**Issue by BoiDareia** [dimitri/pgloader#568]
Like in Issue #503 I now have a situation migrating the SYB-MSDATE type. Does it need correcting like the SYB-MSXML?

> 2017-06-06T15:47:11.160210+01:00 ERROR A thread failed with error: not supported type SYB-MSDATE
> 2017-06-06T15:47:11.160401+01:00 FATAL An unhandled error condition has been signalled: not supported type SYB-MSDATE

Thank you

**Comment by dimitri** [comment]
Yes, a test case with some data to play with would be perfect. It might be as simple as registering the datatype as a string variant like `syb-datetime` and `syb-datetime4` and then adding a `convert(varchar, [ColumnName], 126)` in the `SELECT` query used by pgloader. Best would be to actually test it tho.

**Comment by BoiDareia** [comment]
Test case available and sent to you.
