### ISSUE TITLE
MSSQL type cast loses typemod

### ISSUE THREAD

**Issue by disco-stu** [dimitri/pgloader#571]
Hi,

im currently working on a MSSQL to PostgreSQL migration. Some of the original tables have types like varchar(50). By default pgloader converts these varchar columns to text. However if I specify an explicit CAST the original typmod gets lost. Even if I use keep typemod:

`CAST type varchar to varchar keep typemod`

Heres my pgloader.conf:

```
load database
 from mssql://sa:****@192.168.122.225/test
 INTO postgresql://avo@localhost:5496/test

 with
         downcase identifiers,
         quote identifiers,
	 disable triggers,
	 reset sequences,
	 create schemas

CAST type varchar to varchar keep typemod;
```

The original MSSQL table definition looks like:

```
CREATE TABLE [dbo].[tbl1](
	[id] [bigint] NOT NULL,
	[content] [varchar](50) NULL,
 CONSTRAINT [PK_tbl1] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
```

And the migrated table definition is:

```
CREATE TABLE tbl1 (
    id bigint NOT NULL,
    content character varying
);

ALTER TABLE ONLY tbl1
    ADD CONSTRAINT idx_75246_pk_tbl1 PRIMARY KEY (id);
```

You will find the pgloader log (wich includes --debug and --verbose) attached.
[pgloader_typemod.log.txt](https://github.com/dimitri/pgloader/files/1061306/pgloader_typemod.log.txt)

Many thanks for your efforts.

Regards,
  Adrian

**Comment by dimitri** [comment]
I failed to reproduce your test case with the current code, but against a SQLite database --- the CAST code path is generic for all data sources, with some small amount of source specific code. You didn't mention the version of pgloader you are playing so can you try building from current sources first, and if that fails, then provide me access to a MS SQL instance with which I could reproduce the problem then hopefully fix it? See my email on my GitHub page for connection parameters.

**Comment by disco-stu** [comment]
Hi Dimitri,

right I forgot to mention the version. I've rebuild the debian package from current HEAD (this morning). The latest release (3.3.2) had a bunch of other errors. I will try to provide you access to a development SQL-Server but that could be a bit difficult  and would require some preparation.

One thing I found in the log. While converting the "content" column pgloader correctly recognizes the varchar length (:CHARACTER-MAXIMUM-LENGTH 50). But after the conversion it' gone (:TYPE-MOD NIL):

```
    #S(PGLOADER.MSSQL::MSSQL-COLUMN
                                                                      :SCHEMA "dbo"
                                                                      :TABLE-NAME "tbl1"
                                                                      :NAME "content"
                                                                      :TYPE "varchar"
                                                                      [...]
                                                                      :CHARACTER-MAXIMUM-LENGTH 50
                                                                      [...]
                                                      :COLUMN-LIST (#S(PGLOADER.CATALOG:COLUMN
                                                                       :NAME "id"
                                                                       [...]
                                                                    #S(PGLOADER.CATALOG:COLUMN
                                                                       :NAME "content"
                                                                       :TYPE-NAME "varchar"
                                                                       :TYPE-MOD NIL
                                                                       :[...]))
```

BTW: I'm using TDS Version 8.0 which is a alias for 7.1. varchar(max) support was added in 7.2 [1] but it doesn't show any difference. I don't know if this is relevant.

Please let me know if you need any other information.

Thanks.

[1] http://www.freetds.org/userguide/choosingtdsprotocol.htm

Cheers,
Adrian

**Comment by dimitri** [comment]
I think the problem lies in the `mssql-column-ctype` method found at https://github.com/dimitri/pgloader/blob/master/src/sources/mssql/mssql-cast-rules.lisp#L91. It is not considering the `character-maximum-length` information.

Can you try the following patch?

```diff
modified   src/sources/mssql/mssql-cast-rules.lisp
@@ -107,6 +107,12 @@
                           (mssql-column-numeric-precision col)
                           (or (mssql-column-numeric-scale col) 0)))))
 
+          ((member type '("varchar" "nvarchar" "text") :test #'string=)
+           ;; the user might have a CAST rule with keep typemod, so we need
+           ;; to deal with character-maximum-length for now
+           (format nil "~a(~a)"
+                   type (mssql-column-character-maximum-length col)))
+
           (t type))))
 
 (defmethod cast ((field mssql-column))

```

**Comment by disco-stu** [comment]
Thanks verify much. The provided patch works for varchar(n).

Here's the generated table definition:

```
avo@[local]:5496 [test] # \d dbo.tbl1 
                         Table "dbo.tbl1"
 Column  |         Type          |            Modifiers            
---------+-----------------------+---------------------------------
 id      | bigint                | not null
 content | character varying(50) | default NULL::character varying
Indexes:
    "idx_75323_pk_tbl1" PRIMARY KEY, btree (id)
```

However, I've verified your patch against a table with text column and it crashed:

```
2017-06-09T08:35:58.483000Z NOTICE DROP TABLE IF EXISTS dbo.tbl2 CASCADE;
2017-06-09T08:35:58.484000Z NOTICE CREATE TABLE dbo.tbl2 
(
  id       bigint default NULL,
  content1 varchar(50) default NULL,
  content2 text default NULL,
  content3 text(2147483647) default NULL,
  content4 text default NULL
);
2017-06-09T08:35:58.484000Z ERROR Database error 42601: type modifier is not allowed for type "text"
QUERY: CREATE TABLE dbo.tbl2 
(
  id       bigint default NULL,
  content1 varchar(50) default NULL,
  content2 text default NULL,
  content3 text(2147483647) default NULL,
  content4 text default NULL
);
```
This is because PostgreSQL doesn't support a typemod for `text`, as you would already know. Moreover MSSQL also doesn't support typemods on `text` or `ntext`.

Other types that should support a typemod are `binary`, `char` and `nchar`.

Thanks verify much

I will come up with an updated patch.

**Comment by dimitri** [comment]
Merged in https://github.com/dimitri/pgloader/pull/572. Thanks!

**Comment by disco-stu** [comment]
I've prepared a pull request (#572). The patch is tested against the following MSSQL table definition:

```
CREATE TABLE [dbo].[tbl2](
	[id] [bigint] NULL,
	[c_varchar_50] [varchar](50) NULL,
	[c_nvarchar_50] [nvarchar](50) NULL,
	[c_text] [text] NULL,
	[c_ntext] [ntext] NULL,
	[c_char_50] [char](50) NULL,
	[c_nchar_50] [nchar](50) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
```

With the following casting rules we create a table like:
```
CREATE TABLE tbl2 (
    id bigint,
    c_varchar_50 character varying(50) DEFAULT NULL::character varying,
    c_nvarchar_50 character varying(50) DEFAULT NULL::character varying,
    c_text text,
    c_ntext text,
    c_char_50 character(50) DEFAULT NULL::bpchar,
    c_nchar_50 character(50) DEFAULT NULL::bpchar
);
```

Used rules:
```
CAST type varchar to varchar,
     type nvarchar to varchar,
     type char to char,
     type nchar to char
```

Without the explicit casting rules we would create the following table definition:
```
CREATE TABLE tbl2 (
    id bigint,
    c_varchar_50 text,
    c_nvarchar_50 text,
    c_text text,
    c_ntext text,
    c_char_50 text,
    c_nchar_50 text
);
```
