### ISSUE TITLE
MSSQL: missing ON UPDATE / DELETE rules

### ISSUE THREAD

**Issue by disco-stu** [dimitri/pgloader#579]
While importing a MSSQL schema I've noticed ON DELETE / ON CASCADE rules on foreign key constraints are dropped.

I will come up with a possible patch. Please have a deeper look at it. My lisp is horrible.

**Comment by disco-stu** [comment]
Pushed: #580

**Comment by dimitri** [comment]
Merged #580 wherein I couldn't spot any horrible lisp ;-)
