### ISSUE TITLE
MySQL to PostgreSQL migration fails with ERROR Database error 3F000: schema "<name>" does not exist

### ISSUE THREAD

**Issue by bsimpson** [dimitri/pgloader#582]
Pulled the Docker image marked "latest" as of June 17th 2017 5pm EST (image id ef0edd010e27). I ran the following command to migrate a MySQL database to a PostgreSQL database:

```
$ docker run --rm --name pgloader dimitri/pgloader:latest pgloader mysql://user:password@host/database postgresql://user:password@host/schema
```

I received the following output:

```
2017-06-15T23:06:09.040000Z LOG Main logs in '/tmp/pgloader/pgloader.log'
2017-06-15T23:06:09.044000Z LOG Data errors in '/tmp/pgloader/'
2017-06-15T23:06:09.647000Z ERROR Database error 3F000: schema "schema" does not exist
QUERY: CREATE TABLE schema.external_containers
(
<table schema info>
);
2017-06-15T23:06:09.647000Z FATAL Failed to create the schema, see above.
2017-06-15T23:06:09.647000Z LOG report summary reset
       table name       read   imported     errors      total time
-----------------  ---------  ---------  ---------  --------------
  fetch meta data         10         10          0          0.227s
 Create SQL Types          0          0          0          0.010s
    Create tables          0          0          0          0.000s
-----------------  ---------  ---------  ---------  --------------$
```
I have verified both connection strings are correct. This worked on an older version of pgloader with the Docker image id 8a5d0afe3ff7.

Looking around this seems to be an issue introduced within the last few weeks. I didn't find much information around this error.

MySQL version: 5.6.27-log (hosted as AWS RDS)
PostgreSQL version: 9.6.1 (hosted as AWS RDS)

**Comment by dimitri** [comment]
Can you try to add `--with create-schema` to your command line, it defaults to not doing that, and we changed the target schema in the MySQL case from being the default PostgreSQL *public* schema to being a schema of the same name as that of the MySQL database.

So I guess that in your case the *schema* in the logs and the MySQL *database* in the connection string are the same thing?

If you still want to target the PostgreSQL *public* schema you can use a pgloader command like the following:

```
load database
     from mysql://user:password@host/database
     into postgresql://user:password@host/schema
 ALTER SCHEMA 'schema' RENAME TO 'public';
```

**Comment by dimitri** [comment]
Thinking more about your case, the default should certainly be to *create schemas*, so the attached patch does that. Now, remember that the new schema will not be in the `search_path` and you will need to prefix your tables with the schema each time, or change your `search_path` as in the following:

~~~ sql
ALTER DATABASE schema SET search_path TO schema, public;
~~~

**Comment by bsimpson** [comment]
Thanks @dimitri for the feedback! This makes sense now:

> So I guess that in your case the schema in the logs and the MySQL database in the connection string are the same thing?

That is correct. I've removed the specific names from the example, but my intention is for the MySQL database name to be loaded into a PostgreSQL database by the same name, but in the public schema.

pgloader was attempting to create a table in the schema ("schema" - obfuscated in the example) before this schema existed. Your instruction to run `ALTER SCHEMA 'schema' RENAME TO 'public'` after the data is migrated would rename the schema from "schema" to "public". Had I done this, it would remove the need to alter the user search path as "public" is included by default.

Older versions of pgloader must default to the "public" schema? I neglected to mention that the database existed already in PostgreSQL, and with it the default "public" schema. But any other schemas would also need to be created prior, or with the `--with create-schemas` flag on pgloader.

**Comment by dimitri** [comment]
The `ALTER SCHEMA` suggestion is a pgloader command that is meant to change the pgloader internal representation and matching of the source (MySQL) and target (PostgreSQL) catalogs, so that the source objects found in *schema* end up in the PostgreSQL schema *public*.
