### ISSUE TITLE
option for using citext for string columns?

### ISSUE THREAD

**Issue by joevandyk** [dimitri/pgloader#586]
I'm converting a mysql database to postgresql.

mysql unfortunately has case-insensitive string comparisons. one way to mimic the same behavior in postgresql is to use the citext extension.

is there a way to tell pgloader to use citext columns instead of varchar/text?

**Comment by dimitri** [comment]
You can target the citext data type in your user defined cast rules, see the docs about them at https://github.com/dimitri/pgloader/blob/master/pgloader.1.md#load-mysql-database
