### ISSUE TITLE
Failure to convert dates from DBF

### ISSUE THREAD

**Issue by dimitri** [dimitri/pgloader#589]
From a gitter conversation:

Is it possible to handle empty dates when converting from dbase files? I get the following error:

```
Database error 22007: invalid input syntax for type date: " - - "
```

and it seems like casting is not compatible using dbase as source.

**Comment by dimitri** [comment]
For reference, from the OP:
```
Same error, but for type numeric:
2017-07-03T07:17:33.101000Z ERROR Database error 22P02: invalid input syntax for type numeric: " "
CONTEXT: COPY per, line 1, column timezone: " "
```

**Comment by dimitri** [comment]
https://github.com/dimitri/pgloader/commit/f6cb428c6dae8ee663868623c102eb14c4f0a31d

**Comment by kler** [comment]
Your second fix seems to have solved the second error. But, the princess is in another castle...
However, I suggest we stop this rather time consuming error hunt - it may be the database on my end which is faulty in every way.

Here's the latest error - but again, I don't think we should continue this madness :)

```
2017-07-04T21:43:58.445000Z ERROR PostgreSQL ["table"] Database error 23502: null value in column "hbup" violates not-null constraint
DETAIL: Failing row contains (0, 1010.00000, null, null, 2007-08-28, n, 0.00000, 7.00000, , 1, 2007-07-31, k, 2007.00000, 2006-05-09, k, 2006-05-09, k, p,, 2008-04-23, 0.00000, 0.00000, , null, 0, null, null, null, null, , null, null, ).
CONTEXT: COPY per, line 1: "0	          1010.00000	\N	\N	2007-08-28	n	             0.00000	             7.00000		1	2007-07-31..."
```

**Comment by dimitri** [comment]
For that you can create the target table table yourself and then use the WITH option `data only`.

**Comment by kler** [comment]
True, thx
