### ISSUE TITLE
pgloader doesn't seem to properly pass my credentials to mysql

### ISSUE THREAD

**Issue by furkle** [dimitri/pgloader#591]
I'm trying to use pgloader to import a database from MySQL into PostgreSQL. This is the command I'm using in the shell:

`pgloader mysql://root:mypassword@localhost/twinepm pgsql:///twinepm`

Obviously the password used is not `mypassword`, but the one used is definitely the correct password -- I can login through `mysql -p` with that exact string without any problems. However, when I use pgloader, I always get the following error message:

`Failed to connect to mysql at "localhost" (port 3306) as user "root": MySQL Error [1045]: "Access denied for user 'root'@'localhost' (using password: YES)"`

I've googled for a couple days about this issue and can't find anything related to 1045 errors with pgloader. Hopefully it's a simple fix but I've got no idea what it could be! Thanks.

**Comment by dimitri** [comment]
Is it possible that your password contains characters that need escaping, namely `@` or `:`? Another solution for you to test might be to have the password in the `MYSQL_PWD` environment variable.

**Comment by furkle** [comment]
A few notes:

1. The password is all lower-case Latin letters.
2. mysql with MYSQL_PWD environment variable set and exported, mysql -ppassword, and mysql --password=password all work.
3. MYSQL_PWD does not change the failure code or message when using pgloader, despite definitely being set properly (works in mysql/shows `using password: YES` with pgloader)

Please let me know if there's anything else I can do to test or reproduce the error. It's not the end of the world if I can't get it working; I'm sure I can get the `mysqldump` result to work in postgres somehow. Thanks for the time you've already spent!

**Comment by dimitri** [comment]
Please try the mysql client with `-h localhost`, as this require a different set of rules than the local unix socket, and it might be that your access privileges aren't setup for that: it could be that your mysql client tests and pgloader tests are not using the same connection string.

**Comment by furkle** [comment]
Each method of password entry (`MYSQL_PWD`, `-ppassword`, `--password=password`) also works through the mysql client with `-h localhost`.

**Comment by errazudin** [comment]
Stumbled here while scratching my head here and there ...

Anyhow, if anyone uses docker, pls turn if off before u run pgloader
In my case, after i turn off docker, it works.. my bad. Couldn't see 172.17.0.1 messages clearly :)


$ pgloader mysql://myusername:mygrandpass@localhost/scores postgresql:///scores
2017-07-19T08:46:06.015000+01:00 LOG Main logs in '/private/tmp/pgloader/pgloader.log'
2017-07-19T08:46:06.160000+01:00 LOG Data errors in '/private/tmp/pgloader/'
2017-07-19T08:46:06.161000+01:00 FATAL An unhandled error condition has been signalled:
   Failed to connect to mysql at "localhost" (port 3306) as user "myusername": MySQL Error [1045]: "Access denied for user 'myusername'@'172.17.0.1' (using password: YES)"

**Comment by Jtcruthers** [comment]
This is still an issue with the default installation of both mysql and postgres on Ubuntu 20.04.
