### ISSUE TITLE
Support MDB input files

### ISSUE THREAD

**Issue by rleonhardt** [dimitri/pgloader#592]
To enable easier migration away from Microsoft Office it would be nice if pgloader would support [MDB](https://www.loc.gov/preservation/digital/formats/fdd/fdd000462.shtml) database files, i.e. free [geo databases](http://ec.europa.eu/eurostat/web/gisco/geodata/reference-data/administrative-units-statistical-units/countries) from the European Commission.

There are no cross-platform libraries to read MDB files, so converting them to PostgreSQL would be a big advantage to break out from vendor lock-in.

[ACCDB](https://www.loc.gov/preservation/digital/formats/fdd/fdd000463.shtml) files (MS Access 2007+) files are not so widespread at the moment, could be supported at a later time.

**Comment by dimitri** [comment]
It seems interesting for pgloader to consider supporting MDB files. On the other hand I see the https://github.com/brianb/mdbtools project which seems to offer all you need. What would pgloader offer that mdbtools doesn't?

**Comment by dimitri** [comment]
Lacking information to decide project's interest, closing the issue. Please consider opening again if necessary, with more details.

**Comment by oaeide** [comment]
I reccomend re-opening this issue. Here is a good resource to see why MDBTools doesn't cut it: https://ewen.mcneill.gen.nz/blog/entry/2016-04-08-microsoft-access-to-postgresql/

One could of course argue to fix mdbtools, but I think having this in pgloader would make a ton of sense, further adding to it's versatility.

**Comment by dimitri** [comment]
Well then I'll be happy to review and help cooking a PR that implements MDB support in pgloader. A first good step would be to create a Common Lisp utility that knows to read the format, like I did in the past for DBase files (thanks to Xach initial code, see https://github.com/dimitri/cl-db3) and then with IBM IXF format (see https://github.com/dimitri/cl-ixf).

If that layer already exists, then integrating it in pgloader should be an easy enough task, recommended for a first contribution even.

Feel free to get started on adding MDB support to pgloader!
