### ISSUE TITLE
Failed to connect to pgsql 

### ISSUE THREAD

**Issue by chrissound** [dimitri/pgloader#593]
I'm able to successfully connect via psql using the credentials. I'm also using the exact same URI string in another application which works fine.

I get an error of:
`Failed to connect to pgsql at "xyz.amazonaws.com" (port 5432) as user "root": Database error 28P01: password authentication failed for user "root".`

I'm using the following command (with different credentials):
`pgloader -v "mysql://mysqluser:urlendcodedpassword@xyz.rds.amazonaws.com/mysqldbname" "postgres://root:urlencodedpassword@xyz.rds.amazonaws.com/pgdbname"`

**Comment by dimitri** [comment]
With a URLencoded password spelling that's quite strange. Can you try `PGPASSWORD` environment variable to rule out password parsing?

**Comment by chrissound** [comment]
And leave the password blank in the connection string?

**Comment by chrissound** [comment]
It works!! :) Wow this is great.

The password was using `)` `~` `:` and `&` chars.

**Comment by dimitri** [comment]
The characters `@` and `:` must be escaped in the connection string as per the documentation. To escape them, double them. Anyway, seems we can close the issue then.

**Comment by chrissound** [comment]
Those characters were URL escaped though. Do the docs need need to updated to mention `:` escaping? I see this in the docs (http://pgloader.io/howto/pgloader.1.html):

> Can contain any character, including the at sign (@) which must then be doubled (@@). To leave the password empty, when the user name ends with at at sign, you then have to use the syntax user:@.
