### ISSUE TITLE
`include no drop` option prevents index/primary key creation

### ISSUE THREAD

**Issue by kozak** [dimitri/pgloader#595]
Using the following config file:

```
load database
     from      mysql://localhost:3306/devel
     into      postgresql:///devel
WITH
    include no drop,
     workers = 16,
     concurrency = 8,
     multiple readers per thread,
     rows per range = 100000
ALTER SCHEMA 'devel' RENAME TO 'public';
```

.. and doing `drop schema public cascade; create schema public;` before the pg.load command the latest (HEAD built from source) command will not create indexes including the primary key index. 

If I  remove the `include no drop` property the indexes are created.

Adding `create indexes` doesn't help.

**Comment by dimitri** [comment]
This is strange. Can you send me the source database schema for reproducing the bug locally?

**Comment by kozak** [comment]
You can create a schema with just one table, only with primary key say "id". And the primary key will not be copied.  

```

**Comment by kozak** [comment]
Also it seems that the summary doesn't even include index creation: 
```
skubacz feature/postgresql % pgloader pg.load
2017-07-18T13:59:57.752000+02:00 LOG report summary reset
             table name       read   imported     errors      total time
-----------------------  ---------  ---------  ---------  --------------
        fetch meta data          1          1          0          1.354s
         Create Schemas          0          0          0          0.001s
       Create SQL Types          0          0          0          0.006s
          Create tables          1          1          0          0.007s
         Set Table OIDs          1          1          0          0.006s
-----------------------  ---------  ---------  ---------  --------------
              test.test          0          0          0          0.016s
-----------------------  ---------  ---------  ---------  --------------
COPY Threads Completion          4          4          0          0.075s
        Reset Sequences          1          1          0          0.012s
       Install Comments          0          0          0          0.000s
-----------------------  ---------  ---------  ---------  --------------
      Total import time          0          0          0          1.756s
```

**Comment by dimitri** [comment]
In the current logic pgloader doesn't create the indexes when *include no drop* is selected. The idea is that we should be able to run pgloader in a CI environment, as many times as necessary, so either we drop then create the indexes again, or we don't touch them and they are present both at the beginning and the end of the load.

What's your use-case here?

**Comment by kozak** [comment]
Thanks for looking into this so quickly! 

The public schema in Postgresql doesn't belong to the database owner but to the superuser (this is the default), and because of that `public` can't be dropped, unless I change the owner. I wanted to remove all the objects from public schema (which belong to the database owner), and then have pgloader re-create them for me. 

If you think that this is not a justified use case, it might be good to at least update the documentation about `include no drop`

For your CI use case, without schema changes, wouldn't the `data only` option make more sense ?

**Comment by dimitri** [comment]
Just don't use the default *public* schema maybe? Create your own application's schema, have that schema owned by the database owner and run the following command to be all set:

```sql
alter database test set search_path to appschema, public;
```

**Comment by kozak** [comment]
Sure, there are workarounds. However as you said: 

> This is strange

 :)

**Comment by dimitri** [comment]
Reading that after a good break, it seems to me that you could add the option *create no schemas* in your case. Can you test that?
