### ISSUE TITLE
Cast string to boolean

### ISSUE THREAD

**Issue by hyperborea** [dimitri/pgloader#598]
How do I go about casting predefined string values into a boolean? In my specific case I'm loading data from CSV and booleans are represented by "JA" for true and "NEJ" for false.

Unfortunately my Lisp knowledge is virtually non-existent and I wasn't able to find the answer elsewhere.

**Comment by dimitri** [comment]
Here's a complete self-contained test-case that should allow you to implement your use case:

```
LOAD CSV
     FROM INLINE (c)
     INTO postgresql:///pgloader?t598
          (
            b boolean using (if (string-equal "ja" c) "t" "f")
          )

   BEFORE LOAD DO
    $$ drop table if exists t598; $$,
    $$ CREATE TABLE t598 (b boolean); $$;

JA
ja
NEJ
nej
```

Which gives the expected:

```
pgloader# table t598;
 b 
═══
 t
 t
 f
 f
(4 rows)
```

**Comment by hyperborea** [comment]
Thanks, works like a charm!
