### ISSUE TITLE
Table names in PRAGMA statements are not escaped

### ISSUE THREAD

**Issue by muodov** [dimitri/pgloader#600]
I had an SQLite database with a table named `transaction`. pgloader is generating this error:

```Could not prepare an sqlite statement.
Code ERROR: near "transaction": syntax error.
Database: ***
SQL: PRAGMA table_info(transaction)
```

I understand it's because `transaction` is a reserved word and while it is allowed to name tables with it, it should be escaped with backticks.

In my case, I just renamed the table, but I think it's still a pgloader's bug which can probably be fixed very easily.

**Comment by dimitri** [comment]
Thanks, it should be fixed now. Please consider retrying with a local build from fresh sources.
