### ISSUE TITLE
pgloader gets killed, no errors issued

### ISSUE THREAD

**Issue by yoxel** [dimitri/pgloader#602]
I am migrating a MySQL database to Postgres:

```
pgloader -v --debug --on-error-stop pgloader.dsl
```

pgloaded simply stops running with:

```
zsh: killed     pgloader -v --debug --on-error-stop pgloader.dsl
```

The last debug messages are:

```
2017-08-02T20:43:16.313000+03:00 DATA < #("20870" "26" NIL "..." NIL NIL "51" "00160000018YQhzAAG"
    NIL NIL NIL "0")
2017-08-02T20:43:16.313000+03:00 DATA < #("20871" "26" NIL "..." NIL NIL "51"
    "00132000019U4DUAA0" NIL NIL NIL "0")
2017-08-02T20:43:16.313000+03:00 DATA < #("20872" "26" NIL "..." NIL NIL "51" "00132000019U4DeAAK"
    NIL NIL NIL "0")
```

Any ideas what may be going wrong?

A small/test database migration went fine. This is one is a larger production database.

**Comment by dimitri** [comment]
Which version of pgloader are you using? Can you try with `--debug` but without `--verbose` so that we don't have the DATA output, and so that you can paste here more of the output, with some luck including interesting parts...

If you're not running version 3.4.1 of pgloader, please consider building from source and trying again first.

**Comment by yoxel** [comment]
pgloader --version                                                                                                                                                
pgloader version "3.4.1"
compiled with SBCL 1.3.14.debian

Rerunning with --debug only ...

**Comment by yoxel** [comment]
The run seems to have stopped here:

2017-08-03T02:58:22.012000+03:00 DEBUG copy-batch[0] company 31236 rows [  2.2 MB] in 0.536000s

debugger invoked on a SB-FORMAT:FORMAT-ERROR in thread
#<THREAD "lparallel" RUNNING {10058AD7A3}>:
  error in FORMAT: No more arguments
  copy-batch[~a] ~a ~d row~:p [~a] in ~6$s~@[ [oversized]~]
                  ^
while processing indirect format string:
  ~{~}
   ^

**Comment by dimitri** [comment]
It is quite strange that this error would show up only in some cases, depending on the data or something. Will try to understand. Meanwhile, can you try in `--verbose` mode only, so that you don't issue the DEBUG level log message? I think that then you would skip the error, which happens when emitting a DEBUG log message...

Also, do you have a test case that you could share for me to reproduce the bug?

**Comment by yoxel** [comment]
pgloader -v --on-error-stop pgloader.dsl

just gets killed at some point and it's not clear why.

...
2017-08-04T00:11:45.389000+03:00 NOTICE SET search_path TO yoxeldbN;
2017-08-04T00:11:45.389000+03:00 NOTICE CREATE INDEX idx_217310_contid ON yoxeldbN.projectcontact (contid);
2017-08-04T00:11:45.389000+03:00 NOTICE CREATE UNIQUE INDEX idx_217310_primary ON yoxeldbN.projectcontact (subjectid, contid);
zsh: killed     pgloader -v --on-error-stop pgloader.dsl

Providing a testcase is tough as it's all sensitive customer data. What else can be done to debug this?

Thanks

**Comment by dimitri** [comment]
Ah yes, check your server's logs to see about OOM Killer being involved. The default build of pgloader considers it can use up to 4GB of memory, you have to rebuild with 1GB only:

    make DYNSIZE=1024

About the customer data, consider making it available to me via email. Check about http://pgloader.io/pgloader-moral-license.html if you need some sort of commercial contract to protect your asset from a legal dept. point of view.

**Comment by yoxel** [comment]
I am trying to run the same command on a different server (Mac Book).
Getting this error now (the same config file):

2017-08-05T07:10:51.015000+01:00 NOTICE Starting pgloader, log system is ready.
2017-08-05T07:10:51.022000+01:00 INFO Starting monitor
2017-08-05T07:10:51.025000+01:00 LOG Main logs in '/private/tmp/pgloader/pgloader.log'
2017-08-05T07:10:51.025000+01:00 LOG Data errors in '/private/tmp/pgloader/'
2017-08-05T07:10:51.025000+01:00 LOG Parsing commands from file #P"/Users/alexey/Yoxel/pgloader/pgloader.dsl"
2017-08-05T07:10:51.026000+01:00 FATAL Date/time: 2017-08-04-23:10An unhandled error condition has been signalled: At

   
  SET PostgreSQL PARAMETERS  
  
                ^ (Line 7, Column 14, Position 225)

In context GENERIC-OPTION:

While parsing GENERIC-OPTION. Expected:

     the character Tab
  or the character Newline
  or the character Return
  or the character Space
  or the string "--"
  or the string "/*"
  or the character = (EQUALS_SIGN)
  or the string "to"

**Comment by yoxel** [comment]
Then also tried to build from source on Debian:

debugger invoked on a SB-INT:SIMPLE-PROGRAM-ERROR in thread
#<THREAD "main thread" RUNNING {1002979903}>:
  unknown &KEY argument: :OVERWRITE-FNDB-SILENTLY

Type HELP for debugger help, or (SB-EXT:QUIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [TRY-RECOMPILING] Recompile fndb and try loading it again
  1: [RETRY          ] Retry
                       loading FASL for #<NIBBLES-SOURCE-FILE "nibbles" "sbcl-opt" "fndb">.
  2: [ACCEPT         ] Continue, treating
                       loading FASL for #<NIBBLES-SOURCE-FILE "nibbles" "sbcl-opt" "fndb">
                       as having been successful.
  3: [ABORT          ] Give up on "nibbles"
  4:                   Give up on "uuid"
  5:                   Give up on "pgloader"
  6: [CONTINUE       ] Ignore runtime option --eval "(ql:quickload \"pgloader\")".
  7:                   Skip rest of --eval and --load options.
  8:                   Skip to toplevel READ/EVAL/PRINT loop.
  9: [EXIT           ] Exit SBCL (calling #'EXIT, killing the process).

(SB-C::%DEFKNOWN
 (%CHECK-BOUND)
 (SB-INT:SFUNCTION
  ((SIMPLE-ARRAY (UNSIGNED-BYTE 8) (*)) INDEX (AND FIXNUM SB-EXT:WORD)
   (MEMBER 2 4 8 16))
  INDEX)
 7
 :OVERWRITE-FNDB-SILENTLY
 T)[:OPTIONAL]

**Comment by dimitri** [comment]
The load command parsing error looks like it's because you're using an older pgloader release, where the SET command didn't expect the PostgreSQL keyword (because it didn't support setting MySQL parameters at the time).

The debian build error might be related to using a ancient version of SBCL. Which version are you using?

**Comment by yoxel** [comment]
You're right re: Mac version. Even though I tried "brew install --HEAD pgloader" it did not install the latest version. 

No idea re: SBCL. I'll check.

**Comment by yoxel** [comment]
Hi Dimitri, how do I avoid these?

2017-08-11T21:15:21.628000+03:00 ERROR Failed to connect to #<PGSQL-CONNECTION pgsql://<host>:5432/d32fe08qn4v8b3 {100784EE73}>: Database error 53300: too many connections for role "username"; will try again in 0.5s

**Comment by yoxel** [comment]
The process is running but see these errors. And also this:

debugger invoked on a QMYND:PARTIAL-READ in thread
#<THREAD "lparallel" RUNNING {10075C02F3}>:
  MySQL ERROR: Partial Read of 15 bytes, expected 19
Detail: check MySQL logs for (Got timeout writing communication packets)
Hint: adjust net_read_timeout and net_write_timeout

**Comment by dimitri** [comment]
When PostgreSQL refuses connection, it's a transient error and pgloader retrys again and again, until it works or until it decides it tried hard enough. You will have a FATAL error when pgloader consider the error serious enough to warrant stopping.

About the Partial Read in MySQL, you can adjust the MySQL parameters right from the load file, in a SET MySQL parameters section.

**Comment by yoxel** [comment]
Thank you.

Any idea why pgloader would not run if I commented out these? With syntax errors around ALTER

ALTER SCHEMA 'loadingshema' RENAME TO 'yoxeldbN'

-- BEFORE LOAD DO  
--   $$ alter database mydbname set search_path to yoxeldbN, public; $$;

I did not want pgloader to modify my database. My Postgres params have this:

search_path to 'yoxeldbN, public'

which should be good enough. No?

**Comment by dimitri** [comment]
It should be enough, but I'm not sure why you say it's not: you're not providing error messages. See the logs in --client-min-messages sql level or in --debug to have all the SQL commands sent to PostgreSQL, including the SET commands.

**Comment by yoxel** [comment]
If I comment those two lines (BEFORE LOADDO) I get:

pgloader -v --on-error-stop config.dsl 
KABOOM!
2017-08-11T21:58:04.009000+03:00 NOTICE Starting pgloader, log system is ready.
FATAL error: At

   
  ALTER SCHEMA 'yoxeldb3272' RENAME TO 'yoxeldbN'  
  
                                                 ^ (Line 34, Column 47, Position 1505)

In context COMMAND:

While parsing COMMAND. Expected:

     the character Tab
  or the character Newline
  or the character Return
  or the character Space
  or the string "--"
  or the string "/*"
  or the character ; (SEMICOLON)
  or the string "after"
  or the string "alter"
  or the string "before"
  or the string "cast"
  or the string "decoding"
  or the string "excluding"
  or the string "including"
  or the string "materialize"
  or the string "set"
  or the string "with"
An unhandled error condition has been signalled: At

   
  ALTER SCHEMA 'yoxeldb3272' RENAME TO 'yoxeldbN'  
  
                                                 ^ (Line 34, Column 47, Position 1505)

**Comment by yoxel** [comment]
And it seems my pgloader run has stuck. Log has not printed anything new in a while and no network activity ... will try again after adjusting MySQL parameters

**Comment by yoxel** [comment]
--debug has this error as we know already:

2017-08-11T22:29:15.525000+03:00 DEBUG copy-batch[0] company 19610 rows [  1.9 MB] in 2.774000s

debugger invoked on a SB-FORMAT:FORMAT-ERROR in thread
#<THREAD "lparallel" RUNNING {10058ACC23}>:
  error in FORMAT: No more arguments
  copy-batch[~a] ~a ~d row~:p [~a] in ~6$s~@[ [oversized]~]
                  ^
while processing indirect format string:
  ~{~}
   ^

**Comment by yoxel** [comment]
--client-min-messages sql worked better.

This must be the reason for earlier hanging:
 
Heap exhausted during garbage collection: 32768 bytes available, 55552 requested.
 Gen StaPg UbSta LaSta LUbSt Boxed Unboxed LB   LUB  !move  Alloc  Waste   Trig    WP  GCs Mem-age
   0:     0     0     0     0     0     0     0     0     0        0     0 42949672    0   0  0.0000
   1: 124657 130340     0     0   481 14119     6    47    11 420451152 59698352 382735336    0   1  0.8081
   2: 83502 131070     0     0  1760 36972    40  1681    55 1175887456 149676448 42949672 1273   0  1.1217
   3:  7966 121474     0     0  3396 67019  1966   746   209 2098396256 297829280  2000000 5123   0  0.6844
   4:     0     0     0     0     0     0     0     0     0        0     0  2000000    0   0  0.0000
   5:     0     0     0     0     0     0     0     0     0        0     0  2000000    0   0  0.0000
   6:     0     0     0     0  1717  1115     0     0     0 92798976     0  2000000 1567   0  0.0000
   Total bytes allocated    = 3787533840
   Dynamic-space-size bytes = 4294967296
GC control variables:
   *GC-INHIBIT* = true
   *GC-PENDING* = true
   *STOP-FOR-GC-PENDING* = false
fatal error encountered in SBCL pid 17401(tid 140737265432320):
Heap exhausted, game over.

Welcome to LDB, a low-level debugger for the Lisp runtime environment.

**Comment by dimitri** [comment]
Which version are you using? it looks like several of the latest issues you're reporting would be fixed/improved by using current master version...

**Comment by yoxel** [comment]
Using Debian package: dpkg -i ./pgloader_3.4.1+dfsg-1_amd64.deb

pgloader --version
pgloader version "3.4.1"
compiled with SBCL 1.3.14.debian

Why the memory heap problem? The server has 8Gb ram.

**Comment by yoxel** [comment]
I finally built from source:

1. The syntax error after commenting out BEFORE LOAD DO was not fixed
2. New issue related to sslmode=required:

FATAL error: Failed to connect to pgsql at "host.amazonaws.com" (port 5432) as user "username": SSL verify error: 18 X509_V_ERR_DEPTH_ZERO_SELF_SIGNED_CERT

previous pgloader did not complain this way. Is there an option to accept self-signed certificates?

**Comment by yoxel** [comment]
What is the difference between these two versions in terms SSL handling?

pgloader version "3.4.1"
compiled with SBCL 1.3.14.debian

No issues connecting to my Postgres database (sslmode=require)

Build from sources:
pgloader version "3.4.20a8505"
compiled with SBCL 1.3.20

>SSL verify error: 18 X509_V_ERR_DEPTH_ZERO_SELF_SIGNED_CERT

**Comment by dimitri** [comment]
Reading again your load file, you commented out the final semicolon, which is mandatory. That's why you have an error parsing the file.

About the memory usage, by default pgloader is built with 4GB of heap, and SBCL is known to have a *too conservative* Garbage Collector. You can build pgloader with Clozure CL instead (see docs about that), it's slower but has a much better Garbage Collector.

About SSL, nothing changed in the source code on this topic, I guess the version of the library that is picked at build-time/run-time enforces a different set of constraints. It's only a guess tho.

**Comment by yoxel** [comment]
Thanks. Good catch re: ';'

It seems I finally solved my memory issue by using

WITH batch size = 10MB, prefetch rows = 50000

Does it make sense?

Could not used the version built from source because I am not sure what ssl library it picks and how to make it pick one that would not result in X509_V_ERR_DEPTH_ZERO_SELF_SIGNED_CERT.

**Comment by dimitri** [comment]
Makes sense yes. Those parameters are still somewhat an experiment, still meant to be useful in such cases as the one you're experiencing. If it's working for you, please consider closing this issue.

**Comment by dimitri** [comment]
Both settings will help, also concurrency and workers settings. Concurency is how many concurrent threads will use *prefetch rows* and *workers* how many of those are active at a single time. You don't want too many threads busy with data in-memory with no worker to actually consume the data.

Also check that your workers setting makes sense with respect to how many CPU/cores you have on the machine where pgloader runs.

About SSL, it's out of my league. Please see docs from your OS / distribution about how to handle self-signed certs with the version of SSL you're using. Yes it's annoying, but I've had no time to figure that out properly yet.

**Comment by yoxel** [comment]
Thank you.

**Comment by yoxel** [comment]
Dimitri,

libssl library is exactly the same version between the apt package and manually build but the manually built pgloader loads all these extra libraries for some reason and they're probably used to validate SSL certificates.

open("/lib/x86_64-linux-gnu/libkeyutils.so.1", O_RDONLY|O_CLOEXEC) = 4
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 4
open("/usr/lib/x86_64-linux-gnu/libkrb5support.so.0", O_RDONLY|O_CLOEXEC) = 4
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 4
open("/lib/x86_64-linux-gnu/libcom_err.so.2", O_RDONLY|O_CLOEXEC) = 4
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 4
open("/usr/lib/x86_64-linux-gnu/libk5crypto.so.3", O_RDONLY|O_CLOEXEC) = 4
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 4
open("/usr/lib/x86_64-linux-gnu/libkrb5.so.3", O_RDONLY|O_CLOEXEC) = 4
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 4
open("/usr/lib/x86_64-linux-gnu/libgnutls.so.30", O_RDONLY|O_CLOEXEC) = 4
open("/dev/urandom", O_RDONLY)          = 4
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 5
open("/usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2", O_RDONLY|O_CLOEXEC) = 5
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 5
open("/usr/lib/x86_64-linux-gnu/libsybdb.so.5", O_RDONLY|O_CLOEXEC) = 5
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 5
open("/usr/lib/x86_64-linux-gnu/libsqlite3.so.0", O_RDONLY|O_CLOEXEC) = 5
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 5
open("/usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.2", O_RDONLY|O_CLOEXEC) = 5

**Comment by chrisspen** [comment]
I'm also getting this error while trying to convert a MySQL database to PostgreSQL. I see this:

    debugger invoked on a QMYND:PARTIAL-READ in thread
    #<THREAD "lparallel" RUNNING {100A205B03}>:
      MySQL ERROR: Partial Read of 114 bytes, expected 172
    Detail: check MySQL logs for (Got timeout writing communication packets)
    Hint: adjust net_read_timeout and net_write_timeout

then a few normal warnings messages from PostgreSQL, but pgloader appears to hang and doesn't complete even after an hour. Similarly sized databases I've converted using this script typically take about 10 minutes, so I'm forced to kill pgloader.

I'm running version:

    pgloader version "3.4.1"
    compiled with SBCL 1.3.1.debian

Is there a simple work around for this? If I'm reading this thread correctly, this is a memory management bug and the only solution is to fiddle with some params and recompile from source?

**Comment by yoxel** [comment]
I had to add those settings to my config file:

SET MySQL PARAMETERS 
        ...
        net_read_timeout  = '120',  
        net_write_timeout = '240'

**Comment by chrisspen** [comment]
@yoxel How do you specify a config file? I don't see any documentation for a custom config file in `pgloader --help`.

**Comment by dimitri** [comment]
The command file with the LOAD command is what @yoxel is naming the config file here.

**Comment by chrisspen** [comment]
@dimitri I don't understand. What command file? I see the `pgloader [ option ... ] command-file ...` calll option, but I can't find any documentation on what constitutes the "command-file". I'm just calling pgloader from the command line with source and target. How do I specify memory parameters from there?

**Comment by yoxel** [comment]
pgloader -v --on-error-stop config.dsl

This DSL format is what the man page refers to in its examples:
http://pgloader.io/howto/pgloader.1.html

**Comment by chrisspen** [comment]
@yoxel Thanks. However, those docs seem to be incomplete. For example, it doesn't explain what the legal values for "source-type" are in the LOAD command. And where would I put the MySQL memory settings? In your example, you use the `SET` statement, but those docs imply that this is only used for specifying PostgreSQL parameters (`[ SET <postgresql-settings> ]`). Are there any sample dsl files?

**Comment by chrisspen** [comment]
Nevermind, I see the examples all the way at the bottom. I think I now have a working file.

**Comment by griebd** [comment]
@yoxel have you solved your ssl problem?
```sh
$ pgloader mysql://user:pass@localhost/sampledb postgres://user:pass@xxx.amazonaws.com:port/database?sslmode=require
KABOOM!
FATAL error: Failed to connect to pgsql at "xxx.amazonaws.com" (port port) as user "user": SSL verify error: 18 X509_V_ERR_DEPTH_ZERO_SELF_SIGNED_CERT
An unhandled error condition has been signalled:
   Failed to connect to pgsql at "xxx.amazonaws.com" (port port) as user "user": SSL verify error: 18 X509_V_ERR_DEPTH_ZERO_SELF_SIGNED_CERT

What I am doing here?

Failed to connect to pgsql at "xxx.amazonaws.com" (port port) as user "user": SSL verify error: 18 X509_V_ERR_DEPTH_ZERO_SELF_SIGNED_CERT

Waiting for the monitor thread to complete.
```

But both `psql` and `heroku` works!!

```sh
$ psql postgres://user:pass@xxx.amazonaws.com:port/database
psql (10.1)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

database=>
```

```sh
$ heroku pg:psql 
--> Connecting to postgresql-regular-xxx
psql (10.1)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

app::database=>
```

**Comment by yoxel** [comment]
Unfortunately I have not. I keep using the default package version which does not seem to do the SSL certificate check.

**Comment by mikepaszkiewicz** [comment]
@griebd any luck figuring this out? running into the same thing.

**Comment by griebd** [comment]
not really! I just migrated my data through brute force... I just hope I don't need to do it again!!! :wink:

**Comment by revolunet** [comment]
i'm also getting unexpected kills of pgloader process without error message, with docker images, standard or ccl (on osx); converting a 3Gb sqlite file then it stops suddenly.

`--debug` just show the last queries

**Comment by dimitri** [comment]
@revolunet if you can share the SQLite file, or offer an SSH connection to a box where I can play around, that might help solving it. See my email on my profile page, and the Moral Licence to establish a business contract with default privacy protection rules if you need them here.

**Comment by revolunet** [comment]
Hi, 

I'm getting the silents crashs with the docker images on OSX

Tried with pgloader brew version with the same DB, it works longer, but then i get another issue :

```
2018-04-06T16:23:03.301000+01:00 NOTICE CREATE INDEX idx_319726_liens_src_idx ON liens (src_id);
KABOOM!
FATAL error: There is no applicable method for the generic function
               #<STANDARD-GENERIC-FUNCTION PGLOADER.CATALOG:FORMAT-TABLE-NAME (1)>
             when called with arguments
               (NIL).
See also:
  The ANSI Standard, Section 7.6.6
An unhandled error condition has been signalled:
   There is no applicable method for the generic function
     #<STANDARD-GENERIC-FUNCTION PGLOADER.CATALOG:FORMAT-TABLE-NAME (1)>
   when called with arguments
     (NIL).
See also:
  The ANSI Standard, Section 7.6.6

2018-04-06T16:24:00.758000+01:00 NOTICE Complete PostgreSQL database.
```

here my load file :

```
LOAD database
    FROM '../tarballs/xxx.sqlite'
    INTO postgresql://user:pass@127.0.0.1:5444/xxx

    WITH include drop, create tables, create indexes, reset sequences, batch rows = 100, batch concurrency = 2

    CAST type day to varchar
    CAST type blob to varchar

    INCLUDING ONLY TABLE NAMES LIKE 'articles', 'sommaires', 'textes_versions', 'db_meta', 'liens', 'sections'

    AFTER LOAD DO
    $$ CREATE INDEX textes_versions_cid_idx ON "public".textes_versions (cid); $$,
    $$ CREATE INDEX textes_versions_date_debut_idx ON "public".textes_versions (date_debut); $$,
    $$ CREATE INDEX textes_versions_date_fin_idx ON "public".textes_versions (date_fin); $$,
    $$ CREATE INDEX sommaires_debut_idx ON "public".sommaires (debut); $$,
    $$ CREATE INDEX sommaires_fin_idx ON "public".sommaires (fin); $$,
    $$ CREATE INDEX articles_id_idx ON "public".articles (id); $$,
    $$ CREATE INDEX articles_cid_idx ON "public".articles (cid); $$,
    $$ CREATE INDEX articles_date_debut_idx ON "public".articles (date_debut); $$,
    $$ CREATE INDEX articles_date_fin_idx ON "public".articles (date_fin); $$;
```

this is public data so you can get the DB here : https://drive.google.com/file/d/1NQSL3AY62KH2I8fhlpJ8OHnnV4W7Lp2B/view?usp=sharing

**Comment by dimitri** [comment]
Which version are you using? 
Some recent patches should help a lot, in particular https://github.com/dimitri/pgloader/commit/3bb128c5db9fc7b8926586113aa1b97c59a7b457 ; https://github.com/dimitri/pgloader/commit/8ee799070a8c8a4d7d7d1e957ebfbd21f9a1d975 ; and https://github.com/dimitri/pgloader/commit/f86371970fa62a2ddb2d939947428a74c938484a.

**Comment by revolunet** [comment]
the brew version  is 

```sh
$ pgloader --version                                                                     
pgloader version "3.4.1"
compiled with SBCL 1.4.4
```

**Comment by dimitri** [comment]
Please compile from source and try again. I'm doing that here, now, seeing some errors. Will see about fixing them. Here's the load command I'm playing with:

```
load database
  from sqlite:///Users/dim//Downloads/legilibre.sqlite
  into pgsql:///legilibre

  cast type day to date;
```

**Comment by dimitri** [comment]
Ok, testing with current version in git master's branch, I had to use the following command:

```
load database
  from sqlite:///Users/dim//Downloads/legilibre.sqlite
  into pgsql:///legilibre

  cast type day to date,
       column db_meta.value to text;
```

And here's the log:

```
2018-04-07T01:14:31.026842+03:00 LOG Migrating from #<SQLITE-CONNECTION sqlite:///Users/dim/Downloads/legilibre.sqlite #x30202E91A07D>
2018-04-07T01:14:31.027097+03:00 LOG Migrating into #<PGSQL-CONNECTION pgsql://dim@UNIX:5432/legilibre #x30202E919FAD>
2018-04-07T01:31:48.623761+03:00 ERROR PostgreSQL Database error 42601: syntax error at or near ")"
QUERY: ALTER TABLE textes_versions ADD FOREIGN KEY() REFERENCES textes() ON UPDATE NO ACTION ON DELETE NO ACTION
2018-04-07T01:31:48.631181+03:00 LOG report summary reset
             table name     errors       rows      bytes      total time
-----------------------  ---------  ---------  ---------  --------------
                  fetch          0          0                     0.000s
        fetch meta data          0         26                     0.017s
         Create Schemas          0          0                     0.003s
       Create SQL Types          0          0                     0.000s
          Create tables          0         20                  5m39.432s
         Set Table OIDs          0         10                     0.002s
-----------------------  ---------  ---------  ---------  --------------
                db_meta          0          3     0.0 kB          0.034s
                 textes          0          0                     0.019s
         textes_structs          0     108308    31.0 MB         10.524s
        textes_versions          0     108310   179.3 MB         48.372s
               sections          0     189314    26.2 MB         21.103s
               articles          0    1353852     1.7 GB       7m56.116s
              sommaires          0    1662407   179.4 MB       2m22.577s
                  liens          0    5948833   496.9 MB       6m11.785s
        duplicate_files          0      33807    89.0 MB         35.037s
 textes_versions_brutes          0          0                     0.088s
-----------------------  ---------  ---------  ---------  --------------
COPY Threads Completion          0          4                   9m2.344s
         Create Indexes          0         16                  6m21.539s
 Index Build Completion          0         16                  2m35.439s
        Reset Sequences          0          0                     0.084s
           Primary Keys          0          2                     0.011s
    Create Foreign Keys          1          0                     0.002s
        Create Triggers          0          0                     0.000s
       Install Comments          0          0                     0.000s
-----------------------  ---------  ---------  ---------  --------------
      Total import time          ✓    9404834     2.7 GB      17m59.420s
```

**Comment by revolunet** [comment]
yes, rebuilt with master and `make DYNSIZE=16384 pgloader` and it works 🎉 

i was worried by the make, but it was flawless

7m12.451s minutes on my MBP to convert the 2.7Gb database 👍 

i plan to use pgloader in an open legal document fetch/transform/publish pipeline; without further optim than the added indexes, the speed gain is already x10 between sqlite and postgresql so it will makes a huge difference; thanks !

**Comment by revolunet** [comment]
i'm just wondering why the sqlite articles table returns `1 353 657` row while pg returns `1 353 852`!

using `select count(*) from articles;`; any idea ?

**Comment by thongly** [comment]
`batch size = 40MB` did it for me as well.  I also lowered it to `concurrency = 1` just to be safe
