### ISSUE TITLE
MSSQL: "varbinary" data is improperly migrated to "bytea"

### ISSUE THREAD

**Issue by maciej-arkit** [dimitri/pgloader#603]
**Short Description:** When running migration from MSSQL to PostgreSQL following issue occures: "varbinary" data is improperly migrated to "bytea" - file is truncated (max. allowed size is 64512 Bytes).

## Evidence:
1. Dump of a binary file after migration ( from PostgreSQL) produces an empty PDF file (size=64512 Bytes).

2. All _bytea_ columns after migration have length = 64512 Bytes (64512 = 2^16 - 1024) which may suggest issue with max value.

## Steps to reproduce:
1. Create MSSQL database using attached "create_MSSQL_db.sql" script. Script contains procedure to import 1 row with 10.3 MB PDF file (PDF file [1.pdf] is attached as well).
2. Create empty PostgreSQL database named "documents"
3. Execute `./pgloader documents.config` ("documents.config" is attached)
5. Check that data has been migrated
6. Execute following query to verify that "Docs.PDF" column is missing some bytes:
	`select length(pdf) from docs;`
7. Extract data to a disk `copy (SELECT encode(pdf, 'hex') FROM docs LIMIT 1) TO
	    '/tmp/docs_pdf.hex'`
8. Convert extracted file:
	`xxd -p -r /tmp/docs_pdf.hex /tmp/docs.pdf`
9. Please check size of file. It will be  64512 Bytes which is not corresponding to original file size, which was 10.3 MB.
10. Please try to open PDF file - **it will be empty**.
## Attachments:

- [1.pdf](https://github.com/dimitri/pgloader/files/1198633/1.pdf)
- [create_MSSQL_db.sql.tar.gz](https://github.com/dimitri/pgloader/files/1198638/create_MSSQL_db.sql.tar.gz)
- [documents.config.tar.gz](https://github.com/dimitri/pgloader/files/1198639/documents.config.tar.gz)

**Comment by dimitri** [comment]
As I don't have an MS SQL environment locally available to reproduce, would it be possible for you to set an access for me to a testing environment loaded with the (very small) dataset? You can send me details by email, found on my profile page here. That'd help tremendously fix the problem, as I suspect something to do at the driver/protocol level...

**Comment by maciej-arkit** [comment]
Which OS do you use? If you use Linux it's pretty quick to setup local environment - I can prepare a script for you.
Otherwise, please let me know and if needed I will try to figure out if I have any options to expose MSSQL instance.

**Comment by dimitri** [comment]
It turns out this is the expected behavior for a MS SQL client program, unless the client goes out of his way and asks explicitly to please receive all the bits for a column. Which you do by tweaking the MS SQL server side parameter *textsize*, even for binary content.

Anyway, previous commit adds support for a *SET* comment targeting MS SQL and you can use it that way:

```
load database
   from mssql://user@server/dbname
   into pgsql:///db603

  set mssql parameters textsize to '104857600'

  alter schema 'dbo' rename to 'public';
```

I also have edited my `~/.freetds.conf` file, but it seems to have no effect one way or another. In case it's important:

```ini
[global]
	tds version = 7.4
	client charset = UTF-8
        text size = 52428800
```

**Comment by adammoisa** [comment]
`set mssql parameters textsize to '104857600'` fixed it for me. Thank you @dimitri!
