### ISSUE TITLE
Migration from MS SQL to PostgreSQL Failed due to %dbsqlexec fail

### ISSUE THREAD

**Issue by Runomu** [dimitri/pgloader#605]
i struggling to migrate db from MS SQL 2012 to Postgre SQL 9.6. yesterday i tried with apt-get installation and i got  following.

```
Max connections reached, increase value of TDS_MAX_CONN
%dbsqlexec fail
```

And today i removed apt-get installation and wanted to test it with build from sources. i had some problems with sbcl and i installed it using binary 1.3.3.. so i managed to create  /build/bin/pgloader.
But im getting similar errors if i try to  execute pgloader with load file.

```
./build/bin/pgloader --debug  ~/migration.load
```

```
load database
     from mssql://testUser:xxx@192.168.1.xx/testDB3
     into postgresql://postgres:xxx@localhost/testDB3
set work_mem to '64MB', maintenance_work_mem to '512 MB';
```

error in output:

```
2017-08-06T23:00:22.640000+03:00 INFO Stopping monitor

What I am doing here?
%dbsqlexec fail
Waiting for the monitor thread to complete.
```

is there anything  im doing wrong ? any suggestions ?

**Comment by dimitri** [comment]
Do you have more information than that on the console? the part you've pasted here isn't that helpful... Also, `%dbsqlexec fail` might be related to your FreeTDS setup, see the docs about it at https://github.com/dimitri/pgloader/blob/master/pgloader.1.md#driver-setup-and-encoding.

**Comment by Runomu** [comment]
i created default ~/.freetds.conf  with following configuration

`
         [global]
        tds version = 7.4
        client charset = UTF-8

        min pool conn = 20
        max pool conn = 300
        max member age = 120
 `
and output on 

`./build/bin/pgloader --debug  ~/migration.load`

`sb-impl::*default-external-format* :UTF-8
tmpdir: #P"/tmp/pgloader/"
2017-08-07T13:26:18.009000+03:00 NOTICE Starting pgloader, log system is ready.
2017-08-07T13:26:18.025000+03:00 INFO Starting monitor
Max connections reached, increase value of TDS_MAX_CONN
KABOOM!
2017-08-07T13:26:18.234000+03:00 DEBUG CONNECTED TO #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://postgres@localhost:5432/digifinanstest1 {1007AC1513}>
2017-08-07T13:26:18.234000+03:00 DEBUG SET client_encoding TO 'utf8'
2017-08-07T13:26:18.235000+03:00 DEBUG SET work_mem TO '64MB'
2017-08-07T13:26:18.235000+03:00 DEBUG SET maintenance_work_mem TO '1024 MB'
2017-08-07T13:26:18.235000+03:00 DEBUG SET application_name TO 'pgloader'
2017-08-07T13:26:18.235000+03:00 SQL MSSQL: sending query: -- params: dbname
--         table-type-name
--         including
--         filter-list-to-where-clause including
--         excluding
--         filter-list-to-where-clause excluding
  select c.table_schema,
         c.table_name,
         c.column_name,
         c.data_type,
         CASE
         WHEN c.column_default LIKE '((%' AND c.column_default LIKE '%))' THEN
             CASE
                 WHEN SUBSTRING(c.column_default,3,len(c.column_default)-4) = 'newid()' THEN 'generate_uuid_v4()'
                 WHEN SUBSTRING(c.column_default,3,len(c.column_default)-4) LIKE 'convert(%varchar%,getdate(),%)' THEN 'today'
                 WHEN SUBSTRING(c.column_default,3,len(c.column_default)-4) = 'getdate()' THEN 'CURRENT_TIMESTAMP'
                 WHEN SUBSTRING(c.column_default,3,len(c.column_default)-4) LIKE '''%''' THEN SUBSTRING(c.column_default,4,len(c.column_default)-6)
                 ELSE SUBSTRING(c.column_default,3,len(c.column_default)-4)
             END
         WHEN c.column_default LIKE '(%' AND c.column_default LIKE '%)' THEN
             CASE
                 WHEN SUBSTRING(c.column_default,2,len(c.column_default)-2) = 'newid()' THEN 'generate_uuid_v4()'
                 WHEN SUBSTRING(c.column_default,2,len(c.column_default)-2) LIKE 'convert(%varchar%,getdate(),%)' THEN 'today'
                 WHEN SUBSTRING(c.column_default,2,len(c.column_default)-2) = 'getdate()' THEN 'CURRENT_TIMESTAMP'
                 WHEN SUBSTRING(c.column_default,2,len(c.column_default)-2) LIKE '''%''' THEN SUBSTRING(c.column_default,3,len(c.column_default)-4)
                 ELSE SUBSTRING(c.column_default,2,len(c.column_default)-2)
             END
         ELSE c.column_default
         END,
         c.is_nullable,
         COLUMNPROPERTY(object_id(c.table_name), c.column_name, 'IsIdentity'),
         c.CHARACTER_MAXIMUM_LENGTH,
         c.NUMERIC_PRECISION,
         c.NUMERIC_PRECISION_RADIX,
         c.NUMERIC_SCALE,
         c.DATETIME_PRECISION,
         c.CHARACTER_SET_NAME,
         c.COLLATION_NAME

    from information_schema.columns c
         join information_schema.tables t
              on c.table_schema = t.table_schema
             and c.table_name = t.table_name

   where     c.table_catalog = 'digifinanstestDB2'
         and t.table_type = 'BASE TABLE'



order by c.table_schema, c.table_name, c.ordinal_position;
2017-08-07T13:26:18.237000+03:00 SQL MSSQL: sending query: -- params: including
--         filter-list-to-where-clause including
--         excluding
--         filter-list-to-where-clause excluding
    select schema_name(schema_id) as SchemaName,
           o.name as TableName,
           REPLACE(i.name, '.', '_') as IndexName,
           co.[name] as ColumnName,
           i.is_unique,
           i.is_primary_key,
           i.filter_definition

    from sys.indexes i
         join sys.objects o on i.object_id = o.object_id
         join sys.index_columns ic on ic.object_id = i.object_id
             and ic.index_id = i.index_id
         join sys.columns co on co.object_id = i.object_id
             and co.column_id = ic.column_id

   where schema_name(schema_id) not in ('dto', 'sys')



order by SchemaName,
         o.[name],
         i.[name],
         ic.is_included_column,
         ic.key_ordinal;
FATAL error: %dbsqlexec fail
Date/time: 2017-08-07-13:26An unhandled error condition has been signalled:
                              %dbsqlexec fail


Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1007514BD3}>
0: ((LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX))
1: (SB-IMPL::CALL-WITH-SANE-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX) {1008E501AB}>)
2: (SB-IMPL::%WITH-STANDARD-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX) {1008E5017B}>)
3: (PRINT-BACKTRACE :STREAM #<SB-IMPL::STRING-OUTPUT-STREAM {1008E4D323}> :START 0 :FROM :DEBUGGER-FRAME :COUNT 4611686018427387903 :PRINT-THREAD T :PRINT-FRAME-SOURCE NIL :METHOD-FRAME-STYLE NIL :EMERGENCY-BEST-EFFORT NIL)
4: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE-TO-STREAM #<SB-IMPL::STRING-OUTPUT-STREAM {1008E4D323}>)
5: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE %dbsqlexec fail :OUTPUT NIL :IF-EXISTS :APPEND :VERBOSE NIL)
6: ((FLET #:H0 :IN PGLOADER::MAIN) %dbsqlexec fail)
7: (SIGNAL %dbsqlexec fail)
8: (ERROR MSSQL::MSSQL-ERROR :MESSAGES ("%dbsqlexec fail"))
9: (MSSQL::%DBSQLEXEC #.(SB-SYS:INT-SAP #X0064C900))
10: (MSSQL:QUERY "-- params: including
--         filter-list-to-where-clause including
--         excluding
--         filter-list-to-where-clause excluding
    select schema_name(schema_id) as SchemaName,
           o.name as TableName,
           REPLACE(i.name, '.', '_') as IndexName,
           co.[name] as ColumnName,
           i.is_unique,
           i.is_primary_key,
           i.filter_definition

    from sys.indexes i
         join sys.objects o on i.object_id = o.object_id
         join sys.index_columns ic on ic.object_id = i.object_id
             and ic.index_id = i.index_id
         join sys.columns co on co.object_id = i.object_id
             and co.column_id = ic.column_id

   where schema_name(schema_id) not in ('dto', 'sys')



order by SchemaName,
         o.[name],
         i.[name],
         ic.is_included_column,
         ic.key_ordinal;
" :CONNECTION #<MSSQL:DATABASE-CONNECTION {10087BE673}> :FORMAT :LISTS)
11: (PGLOADER.MSSQL::LIST-ALL-INDEXES #1=#S(PGLOADER.CATALOG:CATALOG :NAME "digifinanstestDB2" :SCHEMA-LIST (#2=#S(PGLOADER.CATALOG:SCHEMA :SOURCE-NAME #3="dbo" :NAME "dbo" :CATALOG #1#
...
:COLLATION-NAME NIL) #S(PGLOADER.MSSQL::MSSQL-COLUMN :SCHEMA "dbo" :TABLE-NAME "veinproductcatalog" :NAME "last_modified_by" :TYPE "varchar" :DEFAULT NIL :NULLABLE "YES" :IDENTITY NIL :CHARACTER-MAXIMUM-LENGTH 50 :NUMERIC-PRECISION NIL :NUMERIC-PRECISION-RADIX NIL :NUMERIC-SCALE NIL :DATETIME-PRECISION NIL :CHARACTER-SET-NAME "iso_1" :COLLATION-NAME "SQL_Latin1_General_CP1_CI_AS") #S(PGLOADER.MSSQL::MSSQL-COLUMN :SCHEMA "dbo" :TABLE-NAME "veinproductcatalog" :NAME "last_modified_date" :TYPE "datetime" :DEFAULT NIL :NULLABLE "YES" :IDENTITY NIL :CHARACTER-MAXIMUM-LENGTH NIL :NUMERIC-PRECISION NIL :NUMERIC-PRECISION-RADIX NIL :NUMERIC-SCALE NIL :DATETIME-PRECISION 3 :CHARACTER-SET-NAME NIL :COLLATION-NAME NIL)) :COLUMN-LIST NIL :INDEX-LIST NIL :FKEY-LIST NIL :TRIGGER-LIST NIL)) :VIEW-LIST NIL)) :TYPES-WITHOUT-BTREE NIL) :MATERIALIZE-VIEWS #<unused argument> :ONLY-TABLES #<unused argument> :CREATE-INDEXES T :FOREIGN-KEYS T :INCLUDING NIL :EXCLUDING NIL) [fast-method]
13: ((:METHOD PGLOADER.SOURCES:COPY-DATABASE (PGLOADER.SOURCES:DB-COPY)) #<PGLOADER.MSSQL:COPY-MSSQL {10084E0E93}> :ON-ERROR-STOP NIL :WORKER-COUNT 4 :CONCURRENCY 1 :MULTIPLE-READERS NIL :MAX-PARALLEL-CREATE-INDEX NIL :TRUNCATE NIL :DISABLE-TRIGGERS NIL :DATA-ONLY NIL :SCHEMA-ONLY NIL :CREATE-SCHEMAS T :CREATE-TABLES T :INCLUDE-DROP T :DROP-SCHEMA NIL :CREATE-INDEXES T :INDEX-NAMES :UNIQUIFY :RESET-SEQUENCES T :FOREIGN-KEYS T :REINDEX NIL :ONLY-TABLES NIL :INCLUDING NIL :EXCLUDING NIL :SET-TABLE-OIDS T :ALTER-TABLE NIL :ALTER-SCHEMA NIL :MATERIALIZE-VIEWS NIL) [fast-method]
14: ((LAMBDA ()))
15: (PGLOADER:RUN-COMMANDS #P"/var/lib/postgresql/migration.load" :START-LOGGER NIL :FLUSH-SUMMARY T :SUMMARY NIL :LOG-FILENAME NIL :LOG-MIN-MESSAGES NIL :CLIENT-MIN-MESSAGES NIL)
16: (PGLOADER::PROCESS-COMMAND-FILE ("/var/lib/postgresql/migration.load") :FLUSH-SUMMARY T)
17: (PGLOADER::MAIN ("./build/bin/pgloader" "--debug" "/var/lib/postgresql/migration.load"))
18: ((LAMBDA NIL :IN "/var/lib/postgresql/pgloader/dumper-2SKVI5f7.lisp"))
19: ((FLET #:WITHOUT-INTERRUPTS-BODY-84 :IN SAVE-LISP-AND-DIE))
20: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))



2017-08-07T13:26:18.438000+03:00 INFO Stopping monitor

What I am doing here?

%dbsqlexec fail


Waiting for the monitor thread to complete.
`

**Comment by dimitri** [comment]
If you copy/paste the failing query into another tool, do you have the same error? (I guess not). I don't know enough of MS SQL to be very helpful here unfortunately, you can search in the issues here in case other users have found ways around it. 

  https://github.com/dimitri/pgloader/issues?utf8=%E2%9C%93&q=%25dbsqlexec%20fail

**Comment by dimitri** [comment]
The other option of course is to provide me with a connection to a test case where I can reproduce the bug and see about it...

**Comment by Splarv** [comment]
Hm, the error message "Max connections reached, increase value of TDS_MAX_CONN" very confusing. Is it always raised, even if the problem is other, for instance in syntax.

**Comment by dimitri** [comment]
That's from the FreeTDS lib itself, I'm not sure if I can do anything about it. If you know how to make it disappear I'll try something!

**Comment by Splarv** [comment]
Well, if you know that this false error message come from FreeTDS lib, then you must know what function call return this wrong message? I'll investigate deeply.

**Comment by paulcos11** [comment]
Hi Dimitri,

I have the same issue it seems, do you have any idea how to resolve. Thanks

ubuntu@me:~/Documents$ pgloader --debug sqlToPostgres 
sb-impl::*default-external-format* :UTF-8
tmpdir: #P"/tmp/pgloader/"
2018-05-26T12:12:50.018000Z NOTICE Starting pgloader, log system is ready.
2018-05-26T12:12:50.033000Z INFO Starting monitor
Max connections reached, increase value of TDS_MAX_CONN
KABOOM!
FATAL error: %dbsqlexec fail
Date/time: 2018-05-26-13:12An unhandled error condition has been signalled:
                              %dbsqlexec fail


Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10091D4523}>
0: ((LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX))
1: (SB-IMPL::CALL-WITH-SANE-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX) {100AB8048B}>)
2: (SB-IMPL::%WITH-STANDARD-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX) {100AB8045B}>)
3: (PRINT-BACKTRACE :STREAM #<SB-IMPL::STRING-OUTPUT-STREAM {100AB7D713}> :START 0 :FROM :DEBUGGER-FRAME :COUNT 4611686018427387903 :PRINT-THREAD T :PRINT-FRAME-SOURCE NIL :METHOD-FRAME-STYLE NIL)
4: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE-TO-STREAM #<SB-IMPL::STRING-OUTPUT-STREAM {100AB7D713}>)
5: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE %dbsqlexec fail :OUTPUT NIL :IF-EXISTS :APPEND :VERBOSE NIL)
6: ((FLET #:H0 :IN PGLOADER::MAIN) %dbsqlexec fail)
7: (SIGNAL %dbsqlexec fail)
8: (ERROR MSSQL::MSSQL-ERROR :MESSAGES ("%dbsqlexec fail"))
9: (MSSQL::%DBSQLEXEC #.(SB-SYS:INT-SAP #X0066C3E0))
10: (MSSQL:QUERY "-- params: including

13: ((:METHOD PGLOADER.SOURCES:COPY-DATABASE (PGLOADER.SOURCES:DB-COPY)) #<PGLOADER.MSSQL:COPY-MSSQL {100A234EF3}> :ON-ERROR-STOP NIL :WORKER-COUNT 4 :CONCURRENCY 1 :MULTIPLE-READERS NIL :MAX-PARALLEL-CREATE-INDEX NIL :TRUNCATE NIL :DISABLE-TRIGGERS NIL :DATA-ONLY NIL :SCHEMA-ONLY NIL :CREATE-SCHEMAS T :CREATE-TABLES T :INCLUDE-DROP T :CREATE-INDEXES T :INDEX-NAMES :UNIQUIFY :RESET-SEQUENCES T :FOREIGN-KEYS T :REINDEX NIL :ONLY-TABLES NIL :INCLUDING (("dbo" "tblBarCount" "tblBars" "tblClient" "tblCount")) :EXCLUDING NIL :SET-TABLE-OIDS T :ALTER-TABLE NIL :ALTER-SCHEMA ((#S(PGLOADER.CATALOG:MATCH-RULE :RULE #S(PGLOADER.CATALOG:STRING-MATCH-RULE :TARGET "dbo") :SCHEMA NIL :ACTION #<FUNCTION PGLOADER.CATALOG::ALTER-SCHEMA-RENAME> :ARGS ("public")))) :MATERIALIZE-VIEWS NIL) [fast-method]
14: ((LAMBDA ()))
15: (PGLOADER:RUN-COMMANDS #P"/home/ubuntu/Documents/sqlToPostgres" :START-LOGGER NIL :FLUSH-SUMMARY T :SUMMARY NIL :LOG-FILENAME NIL :LOG-MIN-MESSAGES NIL :CLIENT-MIN-MESSAGES NIL)
16: (PGLOADER::PROCESS-COMMAND-FILE ("sqlToPostgres") :FLUSH-SUMMARY T)
17: (PGLOADER::MAIN ("pgloader" "--debug" "sqlToPostgres"))
18: ((LAMBDA NIL :IN "/build/pgloader-cLcLIO/pgloader-3.4.1+dfsg/dumper-2SKVI5f7.lisp"))
19: ((FLET #:WITHOUT-INTERRUPTS-BODY-82 :IN SAVE-LISP-AND-DIE))
20: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))



2018-05-26T12:24:10.239000Z DEBUG CONNECTED TO #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://postgres@127.0.0.1:5432/databassename {10097FC793}>
2018-05-26T12:24:10.240000Z DEBUG SET client_encoding TO 'utf8'
2018-05-26T12:24:10.240000Z DEBUG SET work_mem TO '16MB'
2018-05-26T12:24:10.240000Z DEBUG SET maintenance_work_mem TO '512 MB'
2018-05-26T12:24:10.240000Z DEBUG SET application_name TO 'pgloader'
2018-05-26T12:24:10.240000Z SQL MSSQL: sending query: -- params: dbname
--         table-type-name
--         including
--         filter-list-to-where-clause including
--         excluding
--         filter-list-to-where-clause excluding
  select c.table_schema,
         c.table_name,
         c.column_name,
         c.data_type,
         CASE
         WHEN c.column_default LIKE '((%' AND c.column_default LIKE '%))' THEN
             CASE
                 WHEN SUBSTRING(c.column_default,3,len(c.column_default)-4) = 'newid()' THEN 'generate_uuid_v4()'
                 WHEN SUBSTRING(c.column_default,3,len(c.column_default)-4) LIKE 'convert(%varchar%,getdate(),%)' THEN 'today'
                 WHEN SUBSTRING(c.column_default,3,len(c.column_default)-4) = 'getdate()' THEN 'CURRENT_TIMESTAMP'
                 WHEN SUBSTRING(c.column_default,3,len(c.column_default)-4) LIKE '''%''' THEN SUBSTRING(c.column_default,4,len(c.column_default)-6)
                 ELSE SUBSTRING(c.column_default,3,len(c.column_default)-4)
             END
         WHEN c.column_default LIKE '(%' AND c.column_default LIKE '%)' THEN
             CASE
                 WHEN SUBSTRING(c.column_default,2,len(c.column_default)-2) = 'newid()' THEN 'generate_uuid_v4()'
                 WHEN SUBSTRING(c.column_default,2,len(c.column_default)-2) LIKE 'convert(%varchar%,getdate(),%)' THEN 'today'
                 WHEN SUBSTRING(c.column_default,2,len(c.column_default)-2) = 'getdate()' THEN 'CURRENT_TIMESTAMP'
                 WHEN SUBSTRING(c.column_default,2,len(c.column_default)-2) LIKE '''%''' THEN SUBSTRING(c.column_default,3,len(c.column_default)-4)
                 ELSE SUBSTRING(c.column_default,2,len(c.column_default)-2)
             END
         ELSE c.column_default
         END,
         c.is_nullable,
         COLUMNPROPERTY(object_id(c.table_name), c.column_name, 'IsIdentity'),
         c.CHARACTER_MAXIMUM_LENGTH,
         c.NUMERIC_PRECISION,
         c.NUMERIC_PRECISION_RADIX,
         c.NUMERIC_SCALE,
         c.DATETIME_PRECISION,
         c.CHARACTER_SET_NAME,
         c.COLLATION_NAME

    from information_schema.columns c
         join information_schema.tables t
              on c.table_schema = t.table_schema
             and c.table_name = t.table_name

   where     c.table_catalog = 'Mydb'
         and t.table_type = 'BASE TABLE'
         and ((c.table_schema = 'dbo' and c.table_name LIKE 'tblBarCount')
           or (c.table_schema = 'dbo' and c.table_name LIKE 'tblBars')
           or (c.table_schema = 'dbo' and c.table_name LIKE 'tblClient')
           or (c.table_schema = 'dbo' and c.table_name LIKE 'tblCount'))
         

order by c.table_schema, c.table_name, c.ordinal_position;
2018-05-26T12:24:10.241000Z SQL MSSQL: sending query: -- params: including
--         filter-list-to-where-clause including
--         excluding
--         filter-list-to-where-clause excluding
    select schema_name(schema_id) as SchemaName,
           o.name as TableName,
           REPLACE(i.name, '.', '_') as IndexName,
           co.[name] as ColumnName,
           i.is_unique,
           i.is_primary_key,
           i.filter_definition

    from sys.indexes i
         join sys.objects o on i.object_id = o.object_id
         join sys.index_columns ic on ic.object_id = i.object_id
             and ic.index_id = i.index_id
         join sys.columns co on co.object_id = i.object_id
             and co.column_id = ic.column_id

   where schema_name(schema_id) not in ('dto', 'sys')
         and ((schema_name(schema_id) = 'dbo' and o.name LIKE 'tblBarCount') or (schema_name(schema_id) = 'dbo' and o.name LIKE 'tblBars') or (schema_name(schema_id) = 'dbo' and o.name LIKE 'tblClient') or (schema_name(schema_id) = 'dbo' and o.name LIKE 'tblCount'))
         

order by SchemaName,
         o.[name],
         i.[name],
         ic.is_included_column,
         ic.key_ordinal;
2018-05-26T12:24:10.241000Z INFO Stopping monitor

What I am doing here?

%dbsqlexec fail


Waiting for the monitor thread to complete.

**Comment by dimitri** [comment]
I'm not sure how to debug that now, do you have any logs on the MS SQL server side?

**Comment by wblaszczyk** [comment]
I have a similar issue. The solution was to change in .freetds.conf file "tds version" parameter from "7.4" to "7.3", because source was SQL Server 2008.
`sa
sa`
cat .freetds.conf
[global]
tds version = 7.3
client charset = UTF-8

See http://www.freetds.org/userguide/choosingtdsprotocol.htm

**Comment by tallpeak** [comment]
I got this same error about TDS_MAX_CONN, because my SQL 2005 instance does not support filtered indexes.

grep "filter" /tmp/freetds.log | tail -1
12:34:53.235122 74582 (dbutil.c:75):msgno 207: "Invalid column name 'filter_definition'."

**Comment by nohea** [comment]
The sys.indexes filter_definition column doesn't exist for MS SQL 2005 and earlier (TDS version 7.2). It will throw this error.
