### ISSUE TITLE
SQLite default type CURRENT_DATE is not supported

### ISSUE THREAD

**Issue by Jenselme** [dimitri/pgloader#607]
Hi,

If I create a sqlite3 table with a column of type `datetime` and the default value `current_date`, `pgloader` will fail with this error:

```
2017-08-08T14:56:03.238000Z ERROR Database error 0A000: date/time value "current" is no longer supported
QUERY: CREATE TABLE test 
(
  id       bigint,
  my_value timestamptz default 'current_date'
);
2017-08-08T14:56:03.239000Z FATAL Failed to create the schema, see above.
```

Tested with `pgloader` version 3.4.1 and 3.3.2.

SQLite session:

```sql
create table test (id integer primary key, my_value datetime default current_date);
insert into test (id) values (1);
```

If I run `select * from test;` I get `1|2017-08-08` which means the date column correctly used the default value. So the table is correct from sqlite perspective.

BTW, thanks for your awesome tool!

**Comment by dimitri** [comment]
If should be fixed now. Please consider building from (fresh) sources and trying again!

**Comment by Jenselme** [comment]
It works. Thanks for the quick fix!
