### ISSUE TITLE
Cast of mysql enum types doesn't work any more

### ISSUE THREAD

**Issue by Jenselme** [dimitri/pgloader#608]
Hi,

We updated our version of pgloader from `3.2.1.preview` to `3.3.2` and the CAST clause `type enum to text drop not null using empty-string-to-null` doesn't appear to work any more. I also tried on `3.4.1` and `master` without success.

From the logs, I see that the enum type is created in Postgresql and that it is used in the `CREATE TABLE` statement. The problem is that pgloader creates an empty enum type. So this results in the import to fail.

```
$ pgloader --verbose encheres.load 
WARNING:
Couldn't re-execute SBCL with proper personality flags (/proc isn't mounted? setuid?)
Trying to continue anyway.
2017-08-10T10:21:55.045000Z NOTICE Starting pgloader, log system is ready.
2017-08-10T10:21:55.061000Z LOG Main logs in '/tmp/pgloader/pgloader.log'
2017-08-10T10:21:55.064000Z LOG Data errors in '/tmp/pgloader/'
2017-08-10T10:21:55.064000Z LOG Parsing commands from file #P"/root/sql/encheres/encheres.load"
2017-08-10T10:21:55.265000Z NOTICE create schema if not exists encheres;
2017-08-10T10:21:55.665000Z NOTICE DROP then CREATE TABLES
2017-08-10T10:21:55.666000Z NOTICE DROP TYPE IF EXISTS contacts_type CASCADE;
2017-08-10T10:21:55.666000Z NOTICE CREATE TYPE contacts_type AS ENUM ();
2017-08-10T10:21:55.666000Z NOTICE DROP TABLE IF EXISTS contacts CASCADE;
2017-08-10T10:21:55.666000Z NOTICE CREATE TABLE contacts 
(
  id_contact bigserial not null,
  type       contacts_type
);
2017-08-10T10:21:55.873000Z ERROR Database error 22P02: invalid input value for enum contacts_type: "Collaborateur"
CONTEXT: COPY contacts, line 1, column type: "Collaborateur"
```

The problem with the enum creation may be related to https://github.com/dimitri/pgloader/issues/120 since the enum contains values with spaces and accents (`é`).

I tried the workaround described here : https://github.com/dimitri/pgloader/issues/453#issuecomment-258916023 but the import process drops my manually created enum.

I also tried to rewrite the clause to `type contacts_type to text drop not null using empty-string-to-null` without success.

**Comment by dimitri** [comment]
See the more recent bug https://github.com/dimitri/pgloader/issues/597 which is now fixed. I think the fix for #597 should apply to your case here. Please try with a fresh build from sources and try again.

About the CAST expression to target an ENUM, will have a look.

**Comment by Jenselme** [comment]
>  I think the fix for #597 should apply to your case here.

I don't see how. Anyway, I already tested with a fresh build from master without success.

**Comment by dimitri** [comment]
It should be ok now with a cast rule that matches against the *column* rather than its type:

```
cast column contacts.type to text drop not null using empty-string-to-null
```

You will have to rebuild from an updated source tree.

**Comment by Jenselme** [comment]
It works, thanks!

**Comment by Jenselme** [comment]
Hi,

We are needing this patch but would like to avoid building from source. Is there a release planned soon?

**Comment by dimitri** [comment]
Nothing planned as of now. Any reason not to build from source?

**Comment by Jenselme** [comment]
We would like to rely on debian packages and not manage this ourselves.

**Comment by dimitri** [comment]
About relying on debian, that's the reason why I maintain the pgloader package, fully agreed, that's the ideal plan. About build time dependencies, pgloader will fetch them as needed when you type in `make`.

Now, I am in the middle of some changes in pgloader. Let me see about finishing a first series and releasing before continuing to the next part of the changes. Also, I've been thinking about a *monthly* release management, maybe it's time I would actually do that...

**Comment by Jenselme** [comment]
Sounds good. Thanks for your answer.
