### ISSUE TITLE
Feature Request: Allow env variables in BEFORE/AFTER LOAD scripts

### ISSUE THREAD

**Issue by timc13** [dimitri/pgloader#609]
It would be great to pass an environment variables to BEFORE/AFTER LOAD script.  I imagine this could be done using psql variable assignment semantics.

**Comment by dimitri** [comment]
As always with those kind of feature requests, I'm not sure how much pgloader should try to be doing itself. Can you give me more details about your use case please?

**Comment by timc13** [comment]
My use case is that I have several files that all have the same fields, but I want to load it into different tables using a single load file.  I also wanted to create the tables BEFORE LOAD and so I figured since the table name is passed in as part of the connection string variable, it would make sense to create a table from a variable as well.

I think you are right though - this is probably better off separate from pgloader.

**Comment by dimitri** [comment]
For your use case, I think it's best to use a template system of some sorts and fill in the variable in the load file before handing it over to pgloader. Maybe with something like https://mustache.github.io/, for example.

**Comment by dimitri** [comment]
Actually, using mustache makes a lot of sense, even from pgloader itself. And I had a bug I didn't know how to fix, related to reading from the environment, and I could now remove the buggy feature.

Consider building pgloader from sources and using `{{varname}}` with bindings either from the environment or from an INI file that you pass as the `--context` command line argument.
