### ISSUE TITLE
Wiki empty

### ISSUE THREAD

**Issue by randomee** [dimitri/pgloader#610]
The wiki content was deleted?  Looks correct at version 0e52233.

(I noticed due to openssl compile issues.)

**Comment by dimitri** [comment]
If you look in the Pages menu on the right it's all there. Apparently the addition of the docker page also nuked the home page. Want to reinstall a proper home page?

**Comment by randomee** [comment]
I can poke at it.  But can't you just revert to 0e52233? That seems the easier path.

**Comment by dimitri** [comment]
Then we lose the docker page, I think.

**Comment by randomee** [comment]
i copied the diff from the good version.  Should be good now.

**Comment by dimitri** [comment]
Thanks!
