### ISSUE TITLE
Build failure 

### ISSUE THREAD

**Issue by randomee** [dimitri/pgloader#611]
Trying to compile from git with a fresh pull.  I get an error.  I can "continue" and it will finish building, but, that seems wrong.

```
[package pgloader.user-symbols]...................
..................................................
..............................;
; caught ERROR:
;   READ error during COMPILE-FILE:
;
;     Symbol "+BLOB-LOCATION-SPEC+" not found in the IXF package.
;
;       Line: 45, Column: 32, File-Position: 1354
;
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /root/git-pgloader/pgloader/src/sources/ixf/ixf-schema.lisp" {1001E8DAC3}>

debugger invoked on a UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread
#<THREAD "main thread" RUNNING {1001E06BC3}>:
  COMPILE-FILE-ERROR while
  compiling #<CL-SOURCE-FILE "pgloader" "src" "sources" "ixf" "ixf-schema">

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Retry
                                     compiling #<CL-SOURCE-FILE "pgloader" "src" "sources" "ixf" "ixf-schema">.
  1: [ACCEPT                       ] Continue, treating
                                     compiling #<CL-SOURCE-FILE "pgloader" "src" "sources" "ixf" "ixf-schema">
                                     as having been successful.
  2:                                 Retry ASDF operation.
  3: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  4: [ABORT                        ] Give up on "pgloader"
  5: [CONTINUE                     ] Ignore runtime option --eval "(ql:quickload \"pgloader\")".
  6:                                 Skip rest of --eval and --load options.
  7:                                 Skip to toplevel READ/EVAL/PRINT loop.
  8: [EXIT                         ] Exit SBCL (calling #'EXIT, killing the process).

(UIOP/LISP-BUILD:CHECK-LISP-COMPILE-RESULTS NIL T T "~/asdf-action::format-action/" ((#<ASDF/LISP-ACTION:COMPILE-OP > . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "pgloader" "src" "sources" "ixf" "ixf-schema">)))
0]

```

**Comment by dimitri** [comment]
It sounds strange yes. Is is possible that you already had a local version of pgloader sources and just did a `git pull; make`? if yes, please try to `make clean` then `make` again: it's possible that your local copy of cl-ixf is outdated and has no blob support.

**Comment by randomee** [comment]
I thought of that kind of problem.  I deleted the entire directory, and did a clean git clone.  No change.

I do have a .deb of 3.3.2 installed.  

Also, if I "continue", and then try the resulting build, I get the "SSL_CTX_set_default_verify_dir" error.  Although I have openssl 1.1.0f-4 installed (both directly in /usr/local & from a locally built .deb.  (I can reopen the SSL thread if it's useful.)

**Comment by randomee** [comment]
I tried updating sbcl to a newer version, and no change.  Still fails as above.
SBCL 1.3.14.debian
Compiled locally from the debian testing source/diff set.

Any ideas on more things to try?  Or other logs/diagnostics you'd like?

**Comment by dimitri** [comment]
It could be that ASDF defaults to using system provided packages, and that your cl-ixf package is too old. Either try to upgrade it, or setup ASDF so that it uses local Quicklisp packages. For that you can create a `~/.config/common-lisp/source-registry.conf.d/pgloader.conf` file in which you enter a line such as:

``` lisp
(:tree (:home "git-pgloader/pgloader"))
```

**Comment by randomee** [comment]
That seems to have done it.  

Thanks!

**Comment by dimitri** [comment]
Ubuntu LTS then maybe? debian ships with recent enough package: https://packages.debian.org/search?keywords=cl-ixf
