### ISSUE TITLE
support for json lines

### ISSUE THREAD

**Issue by rolandoam** [dimitri/pgloader#612]
Hi,

I was wondering if you have though about adding support for [json lines](http://jsonlines.org/), or what are your thoughts about it. It should be relatively straight forward if every key maps to a column && type.

What would be the best way to start implementing this? just copy the csv loader and work from there? I couldn't find any docs on how to add a new source, could you point me in the right direction?

**Comment by dimitri** [comment]
Yeah it looks easy enough to add support for flat json line documents. What should we do about nested objects tho, such as in the following example from the website:

```json
{"name": "Gilbert", "wins": [["straight", "7♣"], ["one pair", "10♥"]]}
```

**Comment by dimitri** [comment]
About implementation, I'd copy the *fixed* support and use a CL json lib (there are a few around, https://github.com/madnificent/jsown claims to be simple and fast), parsing a line at a time. Then you will need to copy also the command parser for the fixed format and see about available options for the json-line format and the URL prefix (`jsonl://` I suppose?).

**Comment by rolandoam** [comment]
That's a very good point, about nested objects. Tricky thing, because most of the time you want to have access to that data as well... could they be treated as a joined table? where the key of the object, in your example "wins" would be reflected in three insertions:

```sql
insert into games values (1, 'Gilbert');
insert into wins values ('straight', '7♣', 1); -- 1 is game_id
insert into wins  values ('one pair', '10♥', 1);
```
however, that would break the `COPY` stream (AFAIK). As a first case, I could ignore nested objects and then try to find more use cases. For flat structures should be simple enough. I'll try to find some time during the next few days to play with your suggestion.

**Comment by dimitri** [comment]
I think we should just try to send the nested objects as a text or json string, and let PostgreSQL decide what to with them. The user might have an extra column of type json, after all. What's important is that users understand the limitations of our json lines implementation: it's flat.

**Comment by dimitri** [comment]
Thanks for trying to implement it! If you need help I'm available on IRC on freenode, user "dim", or by email (listed on my profile here).

**Comment by rolandoam** [comment]
yes, I think that makes sense. I'll try to give it a shot with your suggestions!

**Comment by dimitri** [comment]
Any news? Did you try implementing the feature? How did it go? Need some help?
