### ISSUE TITLE
sqlite conversion error

### ISSUE THREAD

**Issue by cvickery** [dimitri/pgloader#615]
I installed from homebrew, and the first time I tried to do a conversion I got this:

```
   The assertion (= 1 (LENGTH PGLOADER.SQLITE::TOKENS)) failed with
   (LENGTH PGLOADER.SQLITE::TOKENS) = 2.
```

After brew install pgloader I did this:
```
$ pgloader --version
pgloader version "3.3.2"
compiled with SBCL 1.3.19

$ createdb cuny_courses

$ pgloader [long path here]/cuny_catalog.db postgresql:///cuny_courses
2017-08-19T22:35:11.020000+01:00 LOG Main logs in '/private/tmp/pgloader/pgloader.log'
2017-08-19T22:35:11.023000+01:00 LOG Data errors in '/private/tmp/pgloader/'
2017-08-19T22:35:11.227000+01:00 FATAL An unhandled error condition has been signalled:
   The assertion (= 1 (LENGTH PGLOADER.SQLITE::TOKENS)) failed with
   (LENGTH PGLOADER.SQLITE::TOKENS) = 2.
```

Not sure how to proceed ...

**Comment by dimitri** [comment]
Please try in `--debug` mode. The problem is a type name that pgloader couldn't parse, and the ASSERT in the code is there to catch those problems: I prefer that we fix the type name or the pgloader parser's rather than making poor casting decisions.

**Comment by cvickery** [comment]
[debug.txt](https://github.com/dimitri/pgloader/files/1236695/debug.txt)

Am I correct that this is a date/time (timestamp) column?

**Comment by dimitri** [comment]
The spelling that got pgloader to fail parsing your datatype is the following:

```
7: (PGLOADER.SQLITE::NORMALIZE "number primary_key")
```

From a very quick search, it seems to me it's a typo you might be interested into fixing in the source database...

**Comment by cvickery** [comment]
I can't tell you how many times I've tried to use primary_key as a keyword. Maybe I should try to get the language changed!

Anyway, many thanks and my apologies for causing the trouble.

Chris

On Aug 20, 2017, at 1:49 PM, Dimitri Fontaine <notifications@github.com<mailto:notifications@github.com>> wrote:


The spelling that got pgloader to fail parsing your datatype is the following:

7: (PGLOADER.SQLITE::NORMALIZE "number primary_key")


From a very quick search, it seems to me it's a typo you might be interested into fixing in the source database...

-
