### ISSUE TITLE
concat record separator?

### ISSUE THREAD

**Issue by tendres** [dimitri/pgloader#616]
The spec for the file I am importing uses STX (ASCII character 2) + “n” for a record separator.
Using:
`lines terminated by '0x02'`
appears to work but not sure if responsible for an unrelated error.
Is it possible for pgloader to recognize something like '0x02' + 'n'? as a record separator?
Thanks!

**Comment by dimitri** [comment]
Separator is meant to be a single character, sorry about that...

**Comment by tendres** [comment]
Thanks Dimitri for confirming my suspicions - super appreciate your work.
