### ISSUE TITLE
multiple readers per thread has no effect

### ISSUE THREAD

**Issue by agseekda** [dimitri/pgloader#619]
Hi,

We are planning to use pgloader to migrate our MySQL database (160GB) to Postgresql.
To minimize the downtime we want this process to be as fast as possible.

While testing with pgloader I tried to use "multiple readers per thread" to speed up the migration of the 
larger tables.

However even with setting concurrency, "rows per range" and a high number of workers it still uses only one query for each table.

"Show fullprocess list" on mysql shows that not a single query uses a WHERE statement,

The largest table where it matters has a primary key consisting of an integer (bigint autoincrement) only.

What exactly do I have to set up to make it use multiple readers for one table?

Current settings are:

WITH include drop, create tables, no truncate,
    batch rows = 100000, batch concurrency = 4, batch size = 512MB,
    multiple readers per thread, rows per range = 50000,
    workers = 32, create indexes, foreign keys, reset sequences

**Comment by dimitri** [comment]
In `--debug` output, do you have any *Read Concurrency Enabled for* messages, followed by the table name with support fro concurrency? If you don't, consider sending me a dump of your schema only so that I have a look.

**Comment by agseekda** [comment]
No ... the specific table is this:

CREATE TABLE `history` (
  `hotel_id` varchar(16) NOT NULL,
  `update_type` varchar(255) NOT NULL,
  `code` varchar(255) DEFAULT NULL,
  `affected_from` date DEFAULT NULL,
  `affected_to` date DEFAULT NULL,
  `submit_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `submit_ip` varchar(15) DEFAULT NULL,
  `submit_user` varchar(255) DEFAULT NULL,
  `id` bigint(20) UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


ALTER TABLE `history`
  ADD PRIMARY KEY (`id`) USING BTREE,
  ADD KEY `update_type` (`update_type`),
  ADD KEY `hotel_id` (`hotel_id`);

ALTER TABLE `history`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT;

but does not seem to trigger for any other tables.

For the sake of completeness I also have the following cast rules:

CAST type datetime to timestamptz using zero-dates-to-null,
     type int when (= precision 11) to integer drop typemod,
     type bigint when (= precision 20) to bigint drop typemod

**Comment by dimitri** [comment]
I now see that you didn't change the *concurrency* parameter, as per the docs:

> When using *multiple readers per thread* pgloader may be able to divide the reading work into several threads, as many as the *concurrency* setting, which needs to be greater than 1 for this option to kick be activated.

Please retry with e.g. `concurrency = 16` (given 32 workers, sound an interesting value) or something else, 2 or more.

**Comment by agseekda** [comment]
Thanks this was it.
I somehow confused batch concurrency with concurrency.

**Comment by dimitri** [comment]
It's an experimental feature that needs user feedback, please let me know if it enables faster transfers for you!
