### ISSUE TITLE
Sync database from MySQL to postgres

### ISSUE THREAD

**Issue by nitishxp** [dimitri/pgloader#620]
Hi sir I read a lot about ur software but there is a doubt actually I am working on a project where I need to get data from MySQL to postgres . Is there any way to synch databases with particular tables so that I need not to fetch whole database I.e to fetch particular tables plus real-time 

Thanks

**Comment by dimitri** [comment]
Currently we don't have incremental solution in pgloader. See https://github.com/dimitri/pgloader/issues/166 for more details on how we might some day achieve it.
