### ISSUE TITLE
Allow ":" for socket directory

### ISSUE THREAD

**Issue by timc13** [dimitri/pgloader#621]
https://github.com/dimitri/pgloader/blob/d5072d11e5d52e10b9e82301fa7f16b49fd42d08/src/parsers/command-db-uri.lisp#L58

It would be convenient to allow ":" for socket directories to connect to Google Cloud SQL instances using `cloud_sql_proxy` which creates socket directories with the format `<PROJECT-ID>:<REGION>:<INSTANCE_NAME>`.

see: https://cloud.google.com/sql/docs/postgres/connect-external-app

**Comment by dimitri** [comment]
Support added by espacing the colons in the socket directory name by doubling them, so you'd have to write:

    postgresql://unix:/tmp/project::region::instance:5432/dbname

You need to build pgloader from sources if you want to try now.
