### ISSUE TITLE
Random UTF-8 decoding errors

### ISSUE THREAD

**Issue by umassd-isdi** [dimitri/pgloader#622]
Hello,

We migrated from EnterpriseDB to Heroku Postgresql and in the process switched from the pretty solid & dependable edb*loader to pgloader.  Most of the time it works great, but we've been having persistent but unpredictable UTF-8 decoding errors on some files:

```
2017-08-31T23:03:01.903000+03:00 FATAL :UTF-8 stream decoding error on
#<SB-SYS:FD-STREAM for "file myfile_load.csv" {10120D3093}>:
   the octet sequence #(225 34 44) cannot be decoded.
```

and then the block in the control file quits (in this case after processing 5484 rows).  If I re-execute pgloader with the same csv file then 99% of the time it goes through without issue:

```
2017-08-31T23:49:46.850000+03:00 LOG report summary reset
             table name       read   imported     errors      total time
-----------------------  ---------  ---------  ---------  --------------
                  fetch          0          0          0          0.014s 
-----------------------  ---------  ---------  ---------  --------------
  mytable       6086       6086          0          0.636s 
-----------------------  ---------  ---------  ---------  --------------
        Files Processed          1          1          0          0.023s 
COPY Threads Completion          2          2          0          0.638s 
-----------------------  ---------  ---------  ---------  --------------
      Total import time       6086       6086          0          1.859s 
```

We're using:
pgloader version "3.4.1"
compiled with SBCL 1.3.14.debian

but the same issue was happening with around the same frequency with 3.3.2 as well. p

**Comment by dimitri** [comment]
Is it possible for you to create a self contained test case that I could use to reproduce then hopefully fix the bug?

**Comment by umassd-isdi** [comment]
I've been trying to reproduce again and I just can't force it to happen... I've restarted the machine in question since posting this original ticket...

On a (somewhat) related note, I'm attempting to make this less disastrous when this (or similar things) happen with some plpgsql.  I can't figure out how to get this to work with either the after execute load do or after load execute syntax.  I assume it has something to do with the $do$ blocks:

$do$
BEGIN
IF EXISTS (SELECT 1 FROM temp_table) THEN
truncate target_table;
insert into target_table
(select * from temp_table);
ELSE
   RAISE NOTICE 'DATALOAD DID NOT COMPLETE!';
END IF;
END;
$do$
 
How do I structure this such that I can execute in a .sql file? Passing --debug to pgloader yields no errors or insights:

2017-09-05T19:34:06.659000+03:00 DEBUG copy-batch[0] temp_table 5574 rows [  1.1 MB] in 0.150000s
2017-09-05T19:34:06.660000+03:00 DEBUG Writer[0] for temp_table is done in 0.000000s
2017-09-05T19:34:06.660000+03:00 DEBUG Finished processing WRITER for "temp_table"  0.000000s
2017-09-05T19:34:06.661000+03:00 LOG report summary reset

Control file:

LOAD CSV
        FROM source.csv
                INTO postgresql://xxxx@xxxx.umassd.edu:5432/db?temp_table
set search_path to 'import'
WITH truncate,
        csv header,
        fields optionally enclosed by '"',
        fields escaped by double-quote,
        fields terminated by ','
AFTER LOAD EXECUTE after-load.sql
;

**Comment by umassd-isdi** [comment]
.. i figured out my own problem. 

works w/ this syntax:

DO
$$
BEGIN
IF EXISTS (SELECT 1 FROM temp_table) THEN
truncate target_table;
insert into target_table
(select * from temp_table);
ELSE
RAISE NOTICE 'DATALOAD DID NOT COMPLETE!';
END IF;
END
$$;
