### ISSUE TITLE
Using pgloader as a sync tool

### ISSUE THREAD

**Issue by Anmol-Tuple** [dimitri/pgloader#624]
Hi sir , I have heard lot about your tool but I have a doubt in my mind actually I am looking for a software which convert all data source to postgres . We have clients whose data are on various others db your tool seem to fit in it. But I have a question that my source contains too much data and I have to whole my data to meet my requirements (25-150 millions ) AVG.. Can I used this tool as sync tool if not what is the average time to fully migrate a source to destination. 
Thanks

**Comment by dimitri** [comment]
What happens when you try?

Average time depends on many things, ranging from disk speed to network bandwidth and latency up to parsing efforts needed and transforming options. Can't tell you anything. Please test.

**Comment by Anmol-Tuple** [comment]
Means sir? I haven't try out the tool yet sir

**Comment by dimitri** [comment]
Given the questions you ask, it's time for you to try it.

**Comment by Anmol-Tuple** [comment]
Ok sir I am going to try it ..any parameters to fetch certain tables?
