### ISSUE TITLE
Can't connect to Postgres (follow up to #623)

### ISSUE THREAD

**Issue by maclonghorn** [dimitri/pgloader#626]
So I've started Postgres in its own Docker container, so both MySQL and Postgres are running in Docker containers.  I can connect to each via DB tool (Valentina studio).  Both allow connections via localhost.
```
Failed to connect to pgsql at "localhost" (port 5432) as user "postgres": Database error: Socket error in "connect": ECONNREFUSED (Connection refused)
```
What is the problem?  Is there anywhere I can look to see a more detailed error message?

NOTE: I am running pgloader via Docker like this:
```
docker run --rm --name pgloader dimitri/pgloader:latest pgloader .....
```

**Comment by maclonghorn** [comment]
Follow up:
I installed `pgloader` via Brew and it works now.

It would be helpful to add some documentation on how to connect when running via Docker.

Good tool!

**Comment by dimitri** [comment]
Thanks!

About docker usage, it's a classic problem of configuring docker network access in between the host and the container, and I'm not sure it should be documented in pgloader docs. It's good material for the wiki here, tho.

**Comment by maclonghorn** [comment]
Yeah, probably so.
