### ISSUE TITLE
RedHat Binaries

### ISSUE THREAD

**Issue by leematos** [dimitri/pgloader#627]
First of all, Thanks for your help! This is a great project and I've used it successfully to move clients from MySQL to Postgres 🎉 . That said, a few of them had _weird_ non-internet-connected RedHat based environments and it would be great to have RedHat Binaries. Any particular reason those are not being built?

GitLab (My Employer) is willing to Mirror pgloader and auto-build them but we'd need to add a .gitlab-ci.yml file to the repo so the mirror will build.

**Comment by dimitri** [comment]
Hi! RPMs are currently taken care of by https://yum.postgresql.org. Auto-build sounds good and I would accept a Pull Request with the necessary setup, of course!

**Comment by dimitri** [comment]
Closing the issue as you didn't get back to me with specific steps on how to enable auto-build and mirror and such. Re-open or send me an email to make things happen!
