### ISSUE TITLE
Camel cased names to snake case 

### ISSUE THREAD

**Issue by mtangoo** [dimitri/pgloader#631]
I want to migrate MySQL database to PGS and pgloader have proved to be just great, thank you for the tool.

I have this one question though. My tables as camel cased akin TableName and pgloader  (rightly) lowers the case to tablename. However, for readability, I want them to be table_name. Is it possible to tell pgloader to turn into "snake case mode" where all capitalization is turned to "underscored"?

Regards,

**Comment by dimitri** [comment]
It turns out the transformation code from CamelCase to snake_case was already in pgloader's source code, so I made it available as a new identifier case option: `snake_case`. Please try compiling from sources and using the following option in your load file:

    with snake_case identifiers

**Comment by mtangoo** [comment]
Hi,
thanks for quick reply.
Am new to pgloader. Can you explain where that variable goes? I used commandline:

`./pgloader --verbose  mysql://root:password@localhost/database postgresql://postgres:password@localhost:5432/database `

TIA

**Comment by mtangoo** [comment]
one more thing on same question: what option that ensures tables are not quoted?

**Comment by mtangoo** [comment]
never mind, I found it and here is a sample

```
LOAD DATABASE
     FROM      mysql://root:password@localhost/database
     INTO postgresql://postgres:password@localhost:5432/database

WITH snake_case identifiers
;
```

**Comment by dimitri** [comment]
See the docs, the option belongs to the with clause, which you can pass from the command line with the `--with` switch. There's no option to ensure a table name is never quoted, because sometimes PostgreSQL requires quoting. See https://www.postgresql.org/docs/current/static/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS

**Comment by samir-byte** [comment]
I can see this one is already closed.
Just want to know is there a way to tell pgloader to make camelCase wherever there were camelCase ?

**Comment by dwidge** [comment]
@samir-byte Tell pgloader to preserve case (e.g. camelCase) of table and column names, and put the tables under specific schema name instead of source database name (`newSchemaName` instead of `oldDatabaseName`):
```
LOAD DATABASE
     FROM mysql://root:password@localhost/oldDatabaseName
     INTO postgresql://postgres:password@localhost:5432/database

WITH quote identifiers

ALTER TABLE NAMES MATCHING ~/./ SET SCHEMA 'newSchemaName';
```
