### ISSUE TITLE
MySQL 5.7.5 changed default sql_mode, breaking pgloader

### ISSUE THREAD

**Issue by drmoose** [dimitri/pgloader#632]
I've got a small shell script which restores a mysqldump to a docker mysql container, then uses pgloader to import that data into postgres. A recent change to mysql, however, seems to have broken pgloader:

```
What I am doing here?

MySQL Error [1055]: "Expression #3 of SELECT list is not in GROUP BY clause and
contains nonaggregated column 'information_schema.statistics.INDEX_TYPE' which 
is not functionally dependent on columns in GROUP BY clause; this is incompatible 
with sql_mode=only_full_group_by"
```

This happens when importing from the `mysql:5.7` docker container. The same script works against `mysql:5.6` because in 5.7.5, mysql have [changed their default `sql_mode`](https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_only_full_group_by).

The pgloader query that triggers the error appears to be [this one](https://github.com/dimitri/pgloader/blob/master/src/sources/mysql/sql/list-all-indexes.sql). My guess is you just need to add `index_type` to the `GROUP BY` clause, but I haven't looked at the calling context enough to be sure.

**Comment by dimitri** [comment]
I only added *index_type* in this query recently and it works well against MariaDB 10.2.8 here. can you please edit the SQL file as suggested (it seems like the right solution indeed), build pgloader and test again in your scenario?

**Comment by drmoose** [comment]
[Yup!](#633) It works in my test environment against `mysql:latest`.

**Comment by dimitri** [comment]
Thanks for the extra testing and the patch, applied. I confirm my local test cases do pass too!
