### ISSUE TITLE
.sql files missing

### ISSUE THREAD

**Issue by NathaTerrien** [dimitri/pgloader#636]
After a bit  of struggle, I manage to build pgLoader for Windows and did my first try:

`C:\pgloader\bin\pgloader.exe --type csv --field id --field lib --with truncate --with "fields terminated by ','" test.csv postgres:///TESTSV?tablename=testpgload`

But I end with:
> KABOOM!
> FATAL error: URL "/pgsql/query-table-schema.sql" not found!
> An unhandled error condition has been signalled:
>    URL "/pgsql/query-table-schema.sql" not found!
> What I am doing here?
> URL "/pgsql/query-table-schema.sql" not found!
> Waiting for the monitor thread to complete.
> 

I tried adding 'C:\pgloader\local-projects\pgloader-3.4.1\src\pgsql\' and 'C:\pgloader\local-projects\pgloader-3.4.1\src\pgsql\sql\' to my PATH environment variable, without success.
Also tried copying all the .sql files  in "[...]\src\pgsql\sql\" to "C:\pgloader\pglsq\", withtout success.

What am I doing wrong?

**Comment by dimitri** [comment]
Those files should have been loaded into the `pgloader.exe` binary at compile time, so it's pretty strange that you wouldn't have them. Also it should have failed at compile time. Do you have some errors in the build process? Can you share more details about how you built pgloader on windows?
