### ISSUE TITLE
If PGLoader cannot write to the log file, it will not output any logging to the terminal

### ISSUE THREAD

**Issue by leematos** [dimitri/pgloader#638]
This came up when we ran PGLoader as root, and then due to system constraints we ran it again as a different user. If PGLoader cannot write to the log file, it will look "hung" even if it was actually successful. 

I might suggest either 1) hard failing if it can't write to the log or 2) still logging to the terminal. The first is probably better.

**Comment by dimitri** [comment]
Thanks for the bug report, I believed it's now fixed. If you want to try, consider building from sources.

```
$ chmod u-wx /tmp/pgloader/
$ ./build/bin/pgloader ./test/csv.load 
FATAL: Failed to start the monitor thread.

error opening #P"/private/tmp/pgloader/pgloader.log": Permission denied
```

And it cleanly gives the prompt back.
