### ISSUE TITLE
pgloader bundle tarball

### ISSUE THREAD

**Issue by sttachoires** [dimitri/pgloader#644]
Hi,

I had problems building pgloader, you send me this links that's works and solved my problems.
https://github.com/dimitri/pgloader/releases/download/v3.4.1/pgloader-bundle-3.4.1.tgz

I now have a question; Is it possible to have a URL that point to the latest bundle? I mean that will evolve over time to the most recent bundle. Something like https://github.com/dimitri/pgloader/releases/download/lastest/pgloader-bundle.tgz

So that I can update pgloader as easily as I could install it.

**Comment by dimitri** [comment]
At the moment you have to go to the release page of GitHub to get the information. There's an API to do that kind of things, documented at https://developer.github.com/v3/repos/releases/ for the releases. A quick try locally with `curl` and `jq` allows me to easily fetch the URL of the latest release:

```bash
~ curl -s https://api.github.com/repos/dimitri/pgloader/releases | jq '.[0]["assets"][0]["browser_download_url"]'
"https://github.com/dimitri/pgloader/releases/download/v3.4.1/pgloader-bundle-3.4.1.tgz"
```

Do you need anything else?

**Comment by sttachoires** [comment]
I didn't know those API, they are perfect.
Thanks Dimitri, you rock :)
