### ISSUE TITLE
error when connecting to postgres host with SSL

### ISSUE THREAD

**Issue by rolandoam** [dimitri/pgloader#648]
Hi,

From my linux machines (archlinux and centos), I'm getting the following error when trying to connect to my postgres instance:

```
Failed to connect to pgsql at "xxxx.xxxx.xxxx" (port 5432) as user "dbuser": SSL verify error: 20 X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT_LOCALLY 
```

This works just fine from a macOS machine. This is my pg url:

```
postgresql://dbuser:password@xxx.xxx.xxxx:5432/dbname?sslmode=require&tablename=my.table.name
```

Any ideas what could be going wrong? is there anything else I need to specify for this to work? I can connect just fine using `psql` from all machines (and the same url)

**Comment by rolandoam** [comment]
nevermind. It was a client cert issue. Adding the server cert to the ca-bundles fixed the issue.

**Comment by toobulkeh** [comment]
Any tips on how to "add the server cert to the ca-bundles"?

**Comment by R-N** [comment]
> Any tips on how to "add the server cert to the ca-bundles"?

I downloaded, installed, and set the ISRG X1 Root CA path to SSL_CERT_FILE variable by `SET SSL_CERT_FILE=4042bcee.0`

https://github.com/dimitri/pgloader/issues/768#issuecomment-2475450281
