### ISSUE TITLE
pgloader seems to work but nothing in docker container?

### ISSUE THREAD

**Issue by ckcollab** [dimitri/pgloader#655]
Heyo, thanks so much for pgloader! Has saved my butt quite a few times.

I'm having a bit of a snag now though, everything seems to work fine:

```bash
$ pgloader --version
pgloader version "3.4.1"
compiled with SBCL 1.2.4.debian

$ pgloader mysql://connection/db_name postgresql://connection/db_name
....
....
-----------------------------------------------  ---------  ---------  ---------  --------------
                        COPY Threads Completion          4          4          0          1.512s 
                                 Create Indexes        208        208          0          5.208s 
                         Index Build Completion        208        208          0          0.409s 
                                Reset Sequences         62         62          0          0.051s 
                                   Primary Keys         63         63          0          0.094s 
                            Create Foreign Keys         90         90          0          0.236s 
                                Create Triggers          0          0          0          0.001s 
                               Install Comments          0          0          0          0.000s 
-----------------------------------------------  ---------  ---------  ---------  --------------
                              Total import time       3943       3943          0          5.659s 

```

However, when I look inside the postgres `db_name` there aren't any tables...? A little confused, everything seems to be working. I tried doing dry-runs, debug, verbose, etc. to get more information and everything seems OK as far as I can tell? Maybe it's just been a long day and I'm doing something silly..

Anyway, appreciate any help and thanks again for pgloader!

**Comment by ckcollab** [comment]
It looks like 3.3.1 works?!

**Comment by thevest** [comment]
After reading your comment @ckcollab I built it from source using v3.3.1 and indeed it is working, thanks.

**Comment by dimitri** [comment]
See the answer at #654, the default target schema for pgloader is no longer `public` in PostgreSQL, but a new schema with the same name as the source MySQL database. Also, this should be quite obvious in the output where every table name is written `schemaname.tablename`.

**Comment by ckcollab** [comment]
> Also, this should be quite obvious in the output where every table name is written schemaname.tablename.

Absolutely, that's why I was so confused. There was no error and no data was transferred. I specified the db name in the postgres url (`postgres:///db_name`) so I assumed (like previous behavior) that it would work.

**Comment by dimitri** [comment]
Is your data found in the `db_name` schema? can you paste some lines of output from the main section of the summary, maybe anonymising table names?
