### ISSUE TITLE
Casting POLYGON?

### ISSUE THREAD

**Issue by volksman** [dimitri/pgloader#656]
Hello!  Sorry to post this here but I've tried a few avenues and things and still can't figure out how to migrate polygons from mysql to postgresql.

I've tried version 3.4.1 and a clone of master.  Both seem to error on the same records. 

I have a mysql database with a polygon (geometry) field defined.  Any record that has a value in the field errors on migration with:

`2017-10-26T14:27:45.200000Z ERROR communities_community: Illegal UTF-8 character starting at position 18: 175.`

or in previous (< 3.4.1) versions it would error with:

```
2017-10-26T13:19:59.582000Z ERROR Error while formating a row from "communities_community":
2017-10-26T13:19:59.583000Z ERROR The value
  #(0 0 0 0 1 3 0 0 0 1 0 0 0 24 0 0 0 113 176 244 247 218 236 82 192 13 100
    164 153 10 169 70 64 163 176 244 239 211 236 82 192 200 37 41 142 14 169 70
    64 113 176 244 247 218 236 82 192 204 38 55 4 62 169 70 64 105 176 244 103
    227 236 82 192 226 219 167 104 115 169 70 64 136 176 244 63 237 236 82 192
    253 73 107 158 184 169 70 64 115 176 244 167 238 236 82 192 59 147 194 36
    226 169 70 64 156 176 244 15 240 236 82 192 235 250 220 170 11 170 70 64
    156 176 244 15 240 236 82 192 84 27 232 42 55 170 70 64 160 176 244 215 235
    236 82 192 16 94 44 223 80 170 70 64 84 176 244 47 12 237 82 192 64 146 21
    37 57 170 70 64 43 176 244 207 152 237 82 192 40 103 121 129 194 169 70 64
    252 175 244 151 238 237 82 192 127 251 29 93 119 169 70 64 38 176 244 183
    176 237 82 192 189 180 244 223 153 168 70 64 1 176 244 103 151 237 82 192 0
    136 176 189 165 168 70 64 58 176 244 63 116 237 82 192 109 243 64 138 183
    168 70 64 36 176 244 247 97 237 82 192 5 90 240 103 195 168 70 64 68 176
    244 31 88 237 82 192 138 88 250 40 217 168 70 64 65 176 244 111 68 237 82
    192 9 30 175 239 236 168 70 64 115 176 244 183 41 237 82 192 13 207 18 188
    254 168 70 64 84 176 244 47 12 237 82 192 114 21 86 182 0 169 70 64 129 176
    244 175 245 236 82 192 222 215 139 199 250 168 70 64 123 176 244 55 230 236
    82 192 13 207 18 188 254 168 70 64 119 176 244 191 214 236 82 192 13 100
    164 153 10 169 70 64 113 176 244 247 218 236 82 192 13 100 164 153 10 169
    70 64)
is not of type
  STRING.
```

Wondering what I can do to fix this?  I'm not completely against ignoring the column and reseting the geom data later by hand but getting this working would save me a lot of trouble and it seems like I should be able to do this according to the release notes of 3.4.1.

Thanks in advance for any insight!

**Comment by dimitri** [comment]
Currently this type isn't supported. Have a look at https://github.com/dimitri/pgloader/issues/445 for the work needed to add support to the POLYGON data type. Also please review which PostgreSQL data type would be best suited for it. It might be the `path` type again. Then provide me with a sample dataset to work with, and consider buying a pgloader Moral Licence to support the work here: http://pgloader.io/pgloader-moral-license.html.
