### ISSUE TITLE
Protocol Version Mismatch - Mariadb to Postgresql Database Migration over TCP/IP

### ISSUE THREAD

**Issue by SomePoorBastard** [dimitri/pgloader#657]
I am having trouble migrating a Nextcloud database from Mariadb (mysql) to Postgresql using pgloader. The Mariadb server resides on a CentOS 7 machine at 192.168.15.100 (mariadb-host), and the Postgresql server resides on a FreeBSD 11.1 machine at 192.168.15.145 (postgres-host). pgloader is being run from postgres-host.

Software Versions:

- pgloader -> `root@postgres-host:~ # pgloader version "3.4.1" compiled with Clozure Common Lisp Version 1.11  (FreebsdX8664)`
- postgres -> `root@postgres-host:~ # postgres --version postgres (PostgreSQL) 10.0`
- mariadb -> `[root@mariadb-host]# mysql --version mysql  Ver 15.1 Distrib 5.5.56-MariaDB, for Linux (x86_64) using readline 5.1`

I run:
```shell
root@postgres-host: pgloader --dry-run mysql://root@192.168.15.100/nextcloud pgsql://pgsql_root@localhost/nextcloud
```

...and receive the following error message:

```
KABOOM!
FATAL error: Failed to connect to mysql at "192.168.15.100" (port 3306) as user "root": Error #<QMYND-IMPL::PROTOCOL-VERSION-MISMATCH #x3020011B6B5D>
An unhandled error condition has been signalled: Failed to connect to mysql at "192.168.15.100" (port 3306) as user "root": Error #<QMYND-IMPL::PROTOCOL-VERSION-MISMATCH #x3020011B6B5D>

What I am doing here?

Failed to connect to mysql at "192.168.15.100" (port 3306) as user "root": Error #<QMYND-IMPL::PROTOCOL-VERSION-MISMATCH #x3020011B6B5D>

Waiting for the monitor thread to complete.
```

I have searched for the keywords "QMYND-IMPL", "PROTOCOL-VERSION-MISMATCH", and "mysql protocol mismatch"; none of which have lead me to a sensible indicator of what the root cause is. What can I correct to eliminate the error?

**Comment by dimitri** [comment]
Can you try with `--debug` so that we have more information, such as the version number that MariaDB sends on the wire? We might then have to edit pgloader sources to accept this number and see if we actually support it...

**Comment by SomePoorBastard** [comment]
Note: Needed to add --client-min-messages as --debug alone does not show all output.

> root@pgsql-host:~ # pgloader --dry-run --debug --client-min-messages=debug mysql://root@192.168.15.100/nextcloud pgsql://pgsql_root@localhost/nextcloud
> tmpdir: #P"/tmp/pgloader/"
> 2017-10-31T12:52:59.000894-04:00 NOTICE Starting pgloader, log system is ready.
> 2017-10-31T12:52:59.001859-04:00 INFO Starting monitor
> 2017-10-31T12:52:59.002423-04:00 INFO     SOURCE: "mysql://root@192.168.15.100/nextcloud"
> 2017-10-31T12:52:59.003000-04:00 INFO SOURCE URI: #<MYSQL-CONNECTION mysql://root@192.168.15.100:3306/nextcloud #x30200115394D>
> 2017-10-31T12:52:59.003298-04:00 INFO     TARGET: "pgsql://pgsql_root@localhost/nextcloud"
> 2017-10-31T12:52:59.003655-04:00 INFO TARGET URI: #<PGSQL-CONNECTION pgsql://pgsql_root@localhost:5432/nextcloud #x30200114D62D>
> 2017-10-31T12:52:59.003949-04:00 DEBUG LOAD DATA FROM #<MYSQL-CONNECTION mysql://root@192.168.15.100:3306/nextcloud #x30200115394D>
> KABOOM!
> FATAL error: Failed to connect to mysql at "192.168.15.100" (port 3306) as user "root": Error #<QMYND-IMPL::PROTOCOL-VERSION-MISMATCH #x3020011B622D>
> Date/time: 2017-10-31-12:52An unhandled error condition has been signalled: Failed to connect to mysql at "192.168.15.100" (port 3306) as user "root": Error #<QMYND-IMPL::PROTOCOL-VERSION-MISMATCH #x3020011B622D>
> 
> 
>  (824A190D0) : 0 (PRINT-CALL-HISTORY :CONTEXT NIL :PROCESS NIL :ORIGIN NIL :DETAILED-P NIL :COUNT 1152921504606846975 :START-FRAME-NUMBER 0 :STREAM #<STRING-OUTPUT-STREAM  #x3020011B4BDD> :PRINT-LEVEL 2 :PRINT-LENGTH 5 :SHOW-INTERNAL-FRAMES NIL :FORMAT :TRADITIONAL) 853
>  (824A19238) : 1 (PRINT-BACKTRACE-TO-STREAM #<STRING-OUTPUT-STREAM  #x3020011B4BDD>) 85
>  (824A19268) : 2 (PRINT-BACKTRACE #<PGLOADER.CONNECTION:DB-CONNECTION-ERROR #x3020011B58BD> :OUTPUT NIL :IF-EXISTS :APPEND :VERBOSE NIL) 797
>  (824A19300) : 3 (FUNCALL #'#<(:INTERNAL PGLOADER::MAIN)> #<PGLOADER.CONNECTION:DB-CONNECTION-ERROR #x3020011B58BD>) 141
>  (824A19330) : 4 (SIGNAL #<PGLOADER.CONNECTION:DB-CONNECTION-ERROR #x3020011B58BD>) 989
>  (824A19388) : 5 (%ERROR #<PGLOADER.CONNECTION:DB-CONNECTION-ERROR #x3020011B58BD> (:MESG "Error #<QMYND-IMPL::PROTOCOL-VERSION-MISMATCH #x3020011B622D>" :TYPE "mysql" :HOST ...) 4371788406) 117
>  (824A193B0) : 6 (FUNCALL #'#<#<STANDARD-METHOD PGLOADER.SOURCES:FETCH-METADATA (PGLOADER.MYSQL:COPY-MYSQL PGLOADER.CATALOG:CATALOG)>> #<PGLOADER.MYSQL:COPY-MYSQL #x3020011BD8BD> #S(PGLOADER.CATALOG:CATALOG :NAME "nextcloud" :SCHEMA-LIST (#) ...) :MATERIALIZE-VIEWS NIL :ONLY-TABLES NIL :CREATE-INDEXES T :FOREIGN-KEYS T :INCLUDING NIL :EXCLUDING NIL) 1885
>  (824A19468) : 7 (%%CHECK-KEYWORDS #(2 #(:EXCLUDING :INCLUDING :FOREIGN-KEYS :CREATE-INDEXES :ONLY-TABLES ...) #<METHOD-FUNCTION PGLOADER.SOURCES:FETCH-METADATA #>) 4371788440) 229
>  (824A19538) : 8 (FUNCALL #'#<#<STANDARD-METHOD PGLOADER.SOURCES:COPY-DATABASE (PGLOADER.SOURCES:DB-COPY)>> #<PGLOADER.MYSQL:COPY-MYSQL #x3020011BD8BD> :ON-ERROR-STOP NIL :WORKER-COUNT 4 :CONCURRENCY 1 :MULTIPLE-READERS NIL :MAX-PARALLEL-CREATE-INDEX NIL :TRUNCATE NIL :DISABLE-TRIGGERS NIL :DATA-ONLY NIL :SCHEMA-ONLY NIL :CREATE-SCHEMAS T :CREATE-TABLES T :INCLUDE-DROP T :CREATE-INDEXES T :INDEX-NAMES :UNIQUIFY :RESET-SEQUENCES T :FOREIGN-KEYS T :REINDEX NIL :ONLY-TABLES NIL :INCLUDING NIL :EXCLUDING NIL :SET-TABLE-OIDS T :ALTER-TABLE NIL :ALTER-SCHEMA NIL :MATERIALIZE-VIEWS NIL) 1125
>  (824A19768) : 9 (%%CHECK-KEYWORDS #(1 #(:ALTER-SCHEMA :ALTER-TABLE :ONLY-TABLES :REINDEX :INDEX-NAMES ...) #<METHOD-FUNCTION PGLOADER.SOURCES:COPY-DATABASE #>) 4371788536) 229
>  (824A19830) : 10 (FUNCALL #'#<Anonymous Function #x30200118DF2F>) 805
>  (824A19950) : 11 (RUN-COMMANDS (LAMBDA NIL (LET* # NIL # NIL)) :START-LOGGER NIL :FLUSH-SUMMARY T :SUMMARY NIL :LOG-FILENAME #P"/tmp/pgloader/pgloader.log" :LOG-MIN-MESSAGES :NOTICE :CLIENT-MIN-MESSAGES :DEBUG) 3109
>  (824A19A60) : 12 (LOAD-DATA :FROM #<MYSQL-CONNECTION mysql://root@192.168.15.100:3306/nextcloud #x30200115394D> :INTO #<PGSQL-CONNECTION pgsql://pgsql_root@localhost:5432/nextcloud #x30200114D62D> :ENCODING :UTF-8 :FIELDS NIL :OPTIONS NIL :GUCS NIL :CASTS NIL :BEFORE NIL :AFTER NIL :START-LOGGER NIL :FLUSH-SUMMARY T) 3709
>  (824A19B60) : 13 (MAIN ("/usr/local/bin/pgloader3" "--dry-run" "--client-min-messages=debug" "mysql://root@192.168.15.100/nextcloud" "pgsql://pgsql_root@localhost/nextcloud")) 8757
>  (824A19D70) : 14 (FUNCALL #'#<Anonymous Function #x30000343F93F>) 389
>  (824A19DB0) : 15 (FUNCALL #'#<(:INTERNAL CCL::%SAVE-APPLICATION-INTERNAL)>) 85
>  (824A19DC8) : 16 (FUNCALL #'#<(:INTERNAL CCL::MAKE-MCL-LISTENER-PROCESS)>) 661
>  (824A19E60) : 17 (RUN-PROCESS-INITIAL-FORM #<PROCESS toplevel(2) [Active] #x3020011350FD> (#<COMPILED-LEXICAL-CLOSURE # #x30200113480F>)) 709
>  (824A19EF0) : 18 (FUNCALL #'#<(:INTERNAL (CCL::%PROCESS-PRESET-INTERNAL (PROCESS)))> #<PROCESS toplevel(2) [Active] #x3020011350FD> (#<COMPILED-LEXICAL-CLOSURE # #x30200113480F>)) 573
>  (824A19F98) : 19 (FUNCALL #'#<(:INTERNAL CCL::THREAD-MAKE-STARTUP-FUNCTION)>) 277
> 
> 
> 2017-10-31T12:52:59.209262-04:00 DEBUG CONNECTED TO #<PGSQL-CONNECTION pgsql://pgsql_root@localhost:5432/nextcloud #x30200114D62D>
> 2017-10-31T12:52:59.209541-04:00 DEBUG SET client_encoding TO 'utf8'
> 2017-10-31T12:52:59.209767-04:00 DEBUG SET application_name TO 'pgloader'
> 2017-10-31T12:52:59.209997-04:00 INFO Stopping monitor
> 
> What I am doing here?
> 
> Failed to connect to mysql at "192.168.15.100" (port 3306) as user "root": Error #<QMYND-IMPL::PROTOCOL-VERSION-MISMATCH #x3020011B622D>
> 
> 
> Waiting for the monitor thread to complete.

**Comment by dimitri** [comment]
The error is caught to late, we don't have the information I wanted to access to. Can you provide me ssh access to a (virtual/docker) machine with the same setup as you have so that I can play around and debug the connection?

Also, is it possible for you to try other MySQL versions with the same data?

**Comment by SomePoorBastard** [comment]
I found out how to retrieve the protocol version from the `INFORMATION_SCHEMA` database. It is stored as an integer value in the `global_variables` table ([Mysql Reference Manual 5.7](https://dev.mysql.com/doc/refman/5.5/en/server-system-variables.html#sysvar_protocol_version)).

SQL Query to search in the server variables for names with "protocol" inside.
```
MariaDB [information_schema]> SELECT * FROM `global_variables` WHERE (variable_name LIKE '%PROTOCOL%');
+---------------------------+----------------+
| VARIABLE_NAME             | VARIABLE_VALUE |
+---------------------------+----------------+
| SLAVE_COMPRESSED_PROTOCOL | OFF            |
| PROTOCOL_VERSION          | 10             |
+---------------------------+----------------+
2 rows in set (0.00 sec)
```
Will attach network capture for packets to this note in the future. Will attempt exporting Nextcloud database to earlier Mysql version.

**Comment by dimitri** [comment]
Thanks for the details heads-up! What I don't understand is that in your connection privileges test, we get the expected error message from pgloader:

```
2017-11-01T23:17:27.216983-04:00 FATAL Failed to connect to #<MYSQL-CONNECTION #1=mysql://#3=SomePoorBastard@#2=192.168.15.100:3306/nextcloud #x3020011ED8DD>: Failed to connect to #1# at #2# (port 3306) as user #3#: MySQL Error [1045]: "Access denied for user 'SomePoorBastard'@'192.168.15.145' (using password: NO)"
```

Can you reproduce the protocol mismatch error message from the first post with an *access denied* situation?

About the password, the usual. Either in the connection string in the pgloader command, or in the environment variable `MYSQL_PWD`. I don't think MySQL has something equivalent to PostgreSQL's `.pgpass` file --- see https://www.postgresql.org/docs/current/static/libpq-pgpass.html.

**Comment by SomePoorBastard** [comment]
I can reproduce the error; but only if the server sends SQLSTATE[HY000][1130] ([Section B3 of the MySQL 5.5 Reference Manual](https://dev.mysql.com/doc/refman/5.5/en/error-messages-server.html#error_er_host_not_privileged)).

The error does not show up when the server sends SQLSTATE[HY000][1045] ([Section B3 of the MySQL 5.5 Reference Manual](https://dev.mysql.com/doc/refman/5.5/en/error-messages-server.html#error_er_access_denied_error)). I assume this is expected, and typical behavior.

<hr />

**To reproduce the error:**
Set up a database where the user exists, but is only allowed to connect to a host you are not connecting from. For example, the root user is a great test since by default the root user is only allowed to connect to the local machine ('localhost', '::1', '127.0.0.1' in the host fields). Make sure that a firewall is not in place (firewalld has port 3306 open for TCP/IP connections).

**The key however, is that no other user has a host that can match the host you are connecting from.** I tested this by removing all users except for the root user (and the nextcloud user I had setup for the local nextcloud instance):

```
MariaDB [(none)]> SELECT user, host FROM mysql.user;
+-----------+-----------+
| user      | host      |
+-----------+-----------+
| root      | 127.0.0.1 |
| root      | ::1       |
| nextcloud | localhost |
| root      | localhost |
+-----------+-----------+
4 rows in set (0.00 sec)
```
I run: `root@postgres-host: pgloader --dry-run mysql://root@192.168.15.100/nextcloud pgsql://pgsql_root@localhost/nextcloud`, and reproduced the Protocol Mismatch Error:

```
root@postgres-host:~ # pgloader --dry-run --debug --client-min-messages=debug mysql://root@192.168.15.100/nextcloud pgsql://pgsql_root@localhost/nextcloud
tmpdir: #P"/tmp/pgloader/"
2017-11-02T14:00:52.000904-04:00 NOTICE Starting pgloader, log system is ready.
2017-11-02T14:00:52.001888-04:00 INFO Starting monitor
2017-11-02T14:00:52.002335-04:00 INFO     SOURCE: "mysql://root@192.168.15.100/nextcloud"
2017-11-02T14:00:52.002857-04:00 INFO SOURCE URI: #<MYSQL-CONNECTION mysql://root@192.168.15.100:3306/nextcloud #x30200115394D>
2017-11-02T14:00:52.003137-04:00 INFO     TARGET: "pgsql://pgsql_root@localhost/nextcloud"
2017-11-02T14:00:52.003485-04:00 INFO TARGET URI: #<PGSQL-CONNECTION pgsql://pgsql_root@localhost:5432/nextcloud #x30200114D62D>
2017-11-02T14:00:52.003785-04:00 DEBUG LOAD DATA FROM #<MYSQL-CONNECTION mysql://root@192.168.15.100:3306/nextcloud #x30200115394D>
KABOOM!
FATAL error: Failed to connect to mysql at "192.168.15.100" (port 3306) as user "root": Error #<QMYND-IMPL::PROTOCOL-VERSION-MISMATCH #x3020011B638D>
Date/time: 2017-11-02-14:00An unhandled error condition has been signalled: Failed to connect to mysql at "192.168.15.100" (port 3306) as user "root": Error #<QMYND-IMPL::PROTOCOL-VERSION-MISMATCH #x3020011B638D>


 (824A190D0) : 0 (PRINT-CALL-HISTORY :CONTEXT NIL :PROCESS NIL :ORIGIN NIL :DETAILED-P NIL :COUNT 1152921504606846975 :START-FRAME-NUMBER 0 :STREAM #<STRING-OUTPUT-STREAM  #x3020011B4D3D> :PRINT-LEVEL 2 :PRINT-LENGTH 5 :SHOW-INTERNAL-FRAMES NIL :FORMAT :TRADITIONAL) 853
 (824A19238) : 1 (PRINT-BACKTRACE-TO-STREAM #<STRING-OUTPUT-STREAM  #x3020011B4D3D>) 85
 (824A19268) : 2 (PRINT-BACKTRACE #<PGLOADER.CONNECTION:DB-CONNECTION-ERROR #x3020011B5A1D> :OUTPUT NIL :IF-EXISTS :APPEND :VERBOSE NIL) 797
 (824A19300) : 3 (FUNCALL #'#<(:INTERNAL PGLOADER::MAIN)> #<PGLOADER.CONNECTION:DB-CONNECTION-ERROR #x3020011B5A1D>) 141
 (824A19330) : 4 (SIGNAL #<PGLOADER.CONNECTION:DB-CONNECTION-ERROR #x3020011B5A1D>) 989
 (824A19388) : 5 (%ERROR #<PGLOADER.CONNECTION:DB-CONNECTION-ERROR #x3020011B5A1D> (:MESG "Error #<QMYND-IMPL::PROTOCOL-VERSION-MISMATCH #x3020011B638D>" :TYPE "mysql" :HOST ...) 4371788406) 117
 (824A193B0) : 6 (FUNCALL #'#<#<STANDARD-METHOD PGLOADER.SOURCES:FETCH-METADATA (PGLOADER.MYSQL:COPY-MYSQL PGLOADER.CATALOG:CATALOG)>> #<PGLOADER.MYSQL:COPY-MYSQL #x3020011BDA1D> #S(PGLOADER.CATALOG:CATALOG :NAME "nextcloud" :SCHEMA-LIST (#) ...) :MATERIALIZE-VIEWS NIL :ONLY-TABLES NIL :CREATE-INDEXES T :FOREIGN-KEYS T :INCLUDING NIL :EXCLUDING NIL) 1885
 (824A19468) : 7 (%%CHECK-KEYWORDS #(2 #(:EXCLUDING :INCLUDING :FOREIGN-KEYS :CREATE-INDEXES :ONLY-TABLES ...) #<METHOD-FUNCTION PGLOADER.SOURCES:FETCH-METADATA #>) 4371788440) 229
 (824A19538) : 8 (FUNCALL #'#<#<STANDARD-METHOD PGLOADER.SOURCES:COPY-DATABASE (PGLOADER.SOURCES:DB-COPY)>> #<PGLOADER.MYSQL:COPY-MYSQL #x3020011BDA1D> :ON-ERROR-STOP NIL :WORKER-COUNT 4 :CONCURRENCY 1 :MULTIPLE-READERS NIL :MAX-PARALLEL-CREATE-INDEX NIL :TRUNCATE NIL :DISABLE-TRIGGERS NIL :DATA-ONLY NIL :SCHEMA-ONLY NIL :CREATE-SCHEMAS T :CREATE-TABLES T :INCLUDE-DROP T :CREATE-INDEXES T :INDEX-NAMES :UNIQUIFY :RESET-SEQUENCES T :FOREIGN-KEYS T :REINDEX NIL :ONLY-TABLES NIL :INCLUDING NIL :EXCLUDING NIL :SET-TABLE-OIDS T :ALTER-TABLE NIL :ALTER-SCHEMA NIL :MATERIALIZE-VIEWS NIL) 1125
 (824A19768) : 9 (%%CHECK-KEYWORDS #(1 #(:ALTER-SCHEMA :ALTER-TABLE :ONLY-TABLES :REINDEX :INDEX-NAMES ...) #<METHOD-FUNCTION PGLOADER.SOURCES:COPY-DATABASE #>) 4371788536) 229
 (824A19830) : 10 (FUNCALL #'#<Anonymous Function #x30200118E09F>) 805
 (824A19950) : 11 (RUN-COMMANDS (LAMBDA NIL (LET* # NIL # NIL)) :START-LOGGER NIL :FLUSH-SUMMARY T :SUMMARY NIL :LOG-FILENAME #P"/tmp/pgloader/pgloader.log" :LOG-MIN-MESSAGES :NOTICE :CLIENT-MIN-MESSAGES :DEBUG) 3109
 (824A19A60) : 12 (LOAD-DATA :FROM #<MYSQL-CONNECTION mysql://root@192.168.15.100:3306/nextcloud #x30200115394D> :INTO #<PGSQL-CONNECTION pgsql://pgsql_root@localhost:5432/nextcloud #x30200114D62D> :ENCODING :UTF-8 :FIELDS NIL :OPTIONS NIL :GUCS NIL :CASTS NIL :BEFORE NIL :AFTER NIL :START-LOGGER NIL :FLUSH-SUMMARY T) 3709
 (824A19B60) : 13 (MAIN ("/usr/local/bin/pgloader3" "--dry-run" "--client-min-messages=debug" "mysql://root@192.168.15.100/nextcloud" "pgsql://pgsql_root@localhost/nextcloud")) 8757
 (824A19D70) : 14 (FUNCALL #'#<Anonymous Function #x30000343F93F>) 389
 (824A19DB0) : 15 (FUNCALL #'#<(:INTERNAL CCL::%SAVE-APPLICATION-INTERNAL)>) 85
 (824A19DC8) : 16 (FUNCALL #'#<(:INTERNAL CCL::MAKE-MCL-LISTENER-PROCESS)>) 661
 (824A19E60) : 17 (RUN-PROCESS-INITIAL-FORM #<PROCESS toplevel(2) [Active] #x3020011350FD> (#<COMPILED-LEXICAL-CLOSURE # #x30200113480F>)) 709
 (824A19EF0) : 18 (FUNCALL #'#<(:INTERNAL (CCL::%PROCESS-PRESET-INTERNAL (PROCESS)))> #<PROCESS toplevel(2) [Active] #x3020011350FD> (#<COMPILED-LEXICAL-CLOSURE # #x30200113480F>)) 573
 (824A19F98) : 19 (FUNCALL #'#<(:INTERNAL CCL::THREAD-MAKE-STARTUP-FUNCTION)>) 277


2017-11-02T14:00:52.217204-04:00 DEBUG CONNECTED TO #<PGSQL-CONNECTION pgsql://pgsql_root@localhost:5432/nextcloud #x30200114D62D>
2017-11-02T14:00:52.217465-04:00 DEBUG SET client_encoding TO 'utf8'
2017-11-02T14:00:52.217683-04:00 DEBUG SET application_name TO 'pgloader'
2017-11-02T14:00:52.217913-04:00 INFO Stopping monitor

What I am doing here?

Failed to connect to mysql at "192.168.15.100" (port 3306) as user "root": Error #<QMYND-IMPL::PROTOCOL-VERSION-MISMATCH #x3020011B638D>


Waiting for the monitor thread to complete.
```

Then, I added in a test user whom would match the host I was connecting from.
```
MariaDB [(none)]> CREATE USER 'test'@'%';                                                                                                          Query OK, 0 rows affected (0.00 sec)

MariaDB [(none)]> FLUSH PRIVILEGES;                                                Query OK, 0 rows affected (0.00 sec)

MariaDB [(none)]> SELECT user, host FROM mysql.user;
+-----------+-----------+
| user      | host      |
+-----------+-----------+
| test      | %         |
| root      | 127.0.0.1 |
| root      | ::1       |
| nextcloud | localhost |
| root      | localhost |
+-----------+-----------+
5 rows in set (0.00 sec)
```
...and I run `root@postgres-host: pgloader --dry-run mysql://root@192.168.15.100/nextcloud pgsql://pgsql_root@localhost/nextcloud` again. This time, the error is as expected for someone not allowed to connect (access denied for that user from that host):
```
root@postgres-host:~ # pgloader --dry-run --debug --client-min-messages=debug mysql://root@192.168.15.100/nextcloud pgsql://pgsql_root@localhost/nextcloud
tmpdir: #P"/tmp/pgloader/"
2017-11-02T14:18:34.000920-04:00 NOTICE Starting pgloader, log system is ready.
2017-11-02T14:18:34.001918-04:00 INFO Starting monitor
2017-11-02T14:18:34.002370-04:00 INFO     SOURCE: "mysql://root@192.168.15.100/nextcloud"
2017-11-02T14:18:34.002902-04:00 INFO SOURCE URI: #<MYSQL-CONNECTION mysql://root@192.168.15.100:3306/nextcloud #x30200115394D>
2017-11-02T14:18:34.003182-04:00 INFO     TARGET: "pgsql://pgsql_root@localhost/nextcloud"
2017-11-02T14:18:34.003524-04:00 INFO TARGET URI: #<PGSQL-CONNECTION pgsql://pgsql_root@localhost:5432/nextcloud #x30200114D62D>
2017-11-02T14:18:34.003829-04:00 DEBUG LOAD DATA FROM #<MYSQL-CONNECTION mysql://root@192.168.15.100:3306/nextcloud #x30200115394D>
KABOOM!
FATAL error: Failed to connect to mysql at "192.168.15.100" (port 3306) as user "root": MySQL Error [1045]: "Access denied for user 'root'@'192.168.15.145' (using password: NO)"
Date/time: 2017-11-02-14:18An unhandled error condition has been signalled: Failed to connect to mysql at "192.168.15.100" (port 3306) as user "root": MySQL Error [1045]: "Access denied for user 'root'@'192.168.15.145' (using password: NO)"


 (824A190D0) : 0 (PRINT-CALL-HISTORY :CONTEXT NIL :PROCESS NIL :ORIGIN NIL :DETAILED-P NIL :COUNT 1152921504606846975 :START-FRAME-NUMBER 0 :STREAM #<STRING-OUTPUT-STREAM  #x3020011B33CD> :PRINT-LEVEL 2 :PRINT-LENGTH 5 :SHOW-INTERNAL-FRAMES NIL :FORMAT :TRADITIONAL) 853
 (824A19238) : 1 (PRINT-BACKTRACE-TO-STREAM #<STRING-OUTPUT-STREAM  #x3020011B33CD>) 85
 (824A19268) : 2 (PRINT-BACKTRACE #<PGLOADER.CONNECTION:DB-CONNECTION-ERROR #x3020011B40DD> :OUTPUT NIL :IF-EXISTS :APPEND :VERBOSE NIL) 797
 (824A19300) : 3 (FUNCALL #'#<(:INTERNAL PGLOADER::MAIN)> #<PGLOADER.CONNECTION:DB-CONNECTION-ERROR #x3020011B40DD>) 141
 (824A19330) : 4 (SIGNAL #<PGLOADER.CONNECTION:DB-CONNECTION-ERROR #x3020011B40DD>) 989
 (824A19388) : 5 (%ERROR #<PGLOADER.CONNECTION:DB-CONNECTION-ERROR #x3020011B40DD> (:MESG "MySQL Error [1045]: \"Access denied for user 'root'@'192.168.15.145' (using password: NO)\"" :TYPE "mysql" :HOST ...) 4371788406) 117
 (824A193B0) : 6 (FUNCALL #'#<#<STANDARD-METHOD PGLOADER.SOURCES:FETCH-METADATA (PGLOADER.MYSQL:COPY-MYSQL PGLOADER.CATALOG:CATALOG)>> #<PGLOADER.MYSQL:COPY-MYSQL #x3020011BDA1D> #S(PGLOADER.CATALOG:CATALOG :NAME "nextcloud" :SCHEMA-LIST (#) ...) :MATERIALIZE-VIEWS NIL :ONLY-TABLES NIL :CREATE-INDEXES T :FOREIGN-KEYS T :INCLUDING NIL :EXCLUDING NIL) 1885
 (824A19468) : 7 (%%CHECK-KEYWORDS #(2 #(:EXCLUDING :INCLUDING :FOREIGN-KEYS :CREATE-INDEXES :ONLY-TABLES ...) #<METHOD-FUNCTION PGLOADER.SOURCES:FETCH-METADATA #>) 4371788440) 229
 (824A19538) : 8 (FUNCALL #'#<#<STANDARD-METHOD PGLOADER.SOURCES:COPY-DATABASE (PGLOADER.SOURCES:DB-COPY)>> #<PGLOADER.MYSQL:COPY-MYSQL #x3020011BDA1D> :ON-ERROR-STOP NIL :WORKER-COUNT 4 :CONCURRENCY 1 :MULTIPLE-READERS NIL :MAX-PARALLEL-CREATE-INDEX NIL :TRUNCATE NIL :DISABLE-TRIGGERS NIL :DATA-ONLY NIL :SCHEMA-ONLY NIL :CREATE-SCHEMAS T :CREATE-TABLES T :INCLUDE-DROP T :CREATE-INDEXES T :INDEX-NAMES :UNIQUIFY :RESET-SEQUENCES T :FOREIGN-KEYS T :REINDEX NIL :ONLY-TABLES NIL :INCLUDING NIL :EXCLUDING NIL :SET-TABLE-OIDS T :ALTER-TABLE NIL :ALTER-SCHEMA NIL :MATERIALIZE-VIEWS NIL) 1125
 (824A19768) : 9 (%%CHECK-KEYWORDS #(1 #(:ALTER-SCHEMA :ALTER-TABLE :ONLY-TABLES :REINDEX :INDEX-NAMES ...) #<METHOD-FUNCTION PGLOADER.SOURCES:COPY-DATABASE #>) 4371788536) 229
 (824A19830) : 10 (FUNCALL #'#<Anonymous Function #x30200118E09F>) 805
 (824A19950) : 11 (RUN-COMMANDS (LAMBDA NIL (LET* # NIL # NIL)) :START-LOGGER NIL :FLUSH-SUMMARY T :SUMMARY NIL :LOG-FILENAME #P"/tmp/pgloader/pgloader.log" :LOG-MIN-MESSAGES :NOTICE :CLIENT-MIN-MESSAGES :DEBUG) 3109
 (824A19A60) : 12 (LOAD-DATA :FROM #<MYSQL-CONNECTION mysql://root@192.168.15.100:3306/nextcloud #x30200115394D> :INTO #<PGSQL-CONNECTION pgsql://pgsql_root@localhost:5432/nextcloud #x30200114D62D> :ENCODING :UTF-8 :FIELDS NIL :OPTIONS NIL :GUCS NIL :CASTS NIL :BEFORE NIL :AFTER NIL :START-LOGGER NIL :FLUSH-SUMMARY T) 3709
 (824A19B60) : 13 (MAIN ("/usr/local/bin/pgloader3" "--dry-run" "--client-min-messages=debug" "mysql://root@192.168.15.100/nextcloud" "pgsql://pgsql_root@localhost/nextcloud")) 8757
 (824A19D70) : 14 (FUNCALL #'#<Anonymous Function #x30000343F93F>) 389
 (824A19DB0) : 15 (FUNCALL #'#<(:INTERNAL CCL::%SAVE-APPLICATION-INTERNAL)>) 85
 (824A19DC8) : 16 (FUNCALL #'#<(:INTERNAL CCL::MAKE-MCL-LISTENER-PROCESS)>) 661
 (824A19E60) : 17 (RUN-PROCESS-INITIAL-FORM #<PROCESS toplevel(2) [Active] #x3020011350FD> (#<COMPILED-LEXICAL-CLOSURE # #x30200113480F>)) 709
 (824A19EF0) : 18 (FUNCALL #'#<(:INTERNAL (CCL::%PROCESS-PRESET-INTERNAL (PROCESS)))> #<PROCESS toplevel(2) [Active] #x3020011350FD> (#<COMPILED-LEXICAL-CLOSURE # #x30200113480F>)) 573
 (824A19F98) : 19 (FUNCALL #'#<(:INTERNAL CCL::THREAD-MAKE-STARTUP-FUNCTION)>) 277


2017-11-02T14:18:34.205036-04:00 DEBUG CONNECTED TO #<PGSQL-CONNECTION pgsql://pgsql_root@localhost:5432/nextcloud #x30200114D62D>
2017-11-02T14:18:34.205335-04:00 DEBUG SET client_encoding TO 'utf8'
2017-11-02T14:18:34.205486-04:00 DEBUG SET application_name TO 'pgloader'
2017-11-02T14:18:34.205629-04:00 INFO Stopping monitor

What I am doing here?

Failed to connect to mysql at "192.168.15.100" (port 3306) as user "root": MySQL Error [1045]: "Access denied for user 'root'@'192.168.15.145' (using password: NO)"


Waiting for the monitor thread to complete
```

**Comment by dimitri** [comment]
Wow, thanks for your detailed analysis of the bug, I count not only reproduce it locally, but also then fix it! It turns out 255 isn't a protocol number in our case, the bug MySQL ERR Packet tag, of course. Please `make clean` and `make` again: this should fetch the `qmynd` sources from git again, with the bug fix, and compile a pgloader version with the fix included for you.

**Comment by SomePoorBastard** [comment]
All set; thank you for your help!
