### ISSUE TITLE
Compatible with CockroachDB?

### ISSUE THREAD

**Issue by leenux** [dimitri/pgloader#662]
Compatible with CockroachDB?

**Comment by dimitri** [comment]
Do they implement the COPY protocol and the same catalog tables as PostgreSQL? What happens when you try?

**Comment by damienhollis** [comment]
Hi Dimitri,

I've had a go but it looks like cockroachdb hasn't implemented all the necessary internal tables:

> 2018-02-02T09:50:36.305000Z ERROR Database error 42P01: relation "pg_opclass" does not exist
QUERY: select typname,
       array_agg(amname order by amname <> 'gist', amname <> 'gin')
  from pg_type
       join pg_opclass on pg_opclass.opcintype = pg_type.oid
       join pg_am on pg_am.oid = pg_opclass.opcmethod
 where substring(typname from 1 for 1) <> '_'
       and not exists
       (
         select amname
           from pg_am am
                join pg_opclass c on am.oid = c.opcmethod
                join pg_type t on c.opcintype = t.oid
          where amname = 'btree' and t.oid = pg_type.oid
       )
group by typname;
2018-02-02T09:50:36.305000Z FATAL Failed to create the schema, see above.

Is there any way to work around this?

**Comment by dimitri** [comment]
This query is used to support special (non-Btree) index types and create appropriate GiST or GIN indexes on the data instead: Full-Text Search and Geographic indexes are examples of that. You could try commenting lines 31/32 in the pgloader function `prepare-pgsql-database`, where we fetch the PostgreSQL catalog information that are needed:

  https://github.com/dimitri/pgloader/blob/master/src/sources/common/db-methods.lisp#L31-L32

I guess you will then hit something else, but if not, this function could be made optional or errors from it might turn into a WARNING.

**Comment by nstewart** [comment]
@dimitri -- can we support CockroachDB using the pgloader moral license? 

I also have a few questions around are about timing and this language in your [Sustainable Open Source Blog](https://tapoueh.org/blog/2018/02/sustainable-open-source-development/#the-varnish-moral-license): "please note that the license does not cover any guarantee or contract and bears no legal authority, it only acknowledges that the purchaser made a payment to pgloader."

Do you have an email address where we could iron out the details to see if this approach makes sense?  In parallel Cockroach Labs is looking at what internal tables we would need to support so this would work out of the box.

**Comment by dimitri** [comment]
Hi @nstewart ! Of course we can make it happen through the pgloader moral license. My email is on my Github profile page if you want to continue from there!

**Comment by gigatexal** [comment]
Here's to hoping the CRDB people or other enterprising persons can make this happen. This would be absolutely awesome for me.

**Comment by dimitri** [comment]
It should be easier nowadays than it was in the past. Have a look at https://github.com/dimitri/pgloader/blob/master/src/pgsql/connection.lisp#L407 where we parse PostgreSQL version string for _variants_ of Postgres (e.g. Redshift), and then have a look at https://github.com/dimitri/pgloader/tree/master/src/pgsql/sql where it's possible to have version-specific queries for querying the catalogs.
