### ISSUE TITLE
mysql to postgresql - type "double" does not exist for mysql double, AUTO_INCREMENT field type

### ISSUE THREAD

**Issue by sahapasci** [dimitri/pgloader#664]
hi all, 
I used pgloader for the first time with this command below;

`pgloader mysql://user:pass@host:port/db postgresql://postgres@/db`

and have got this error; 

> ERROR Database error 42704: type "double" does not exist
> QUERY: CREATE TABLE schema_name.table_name
> (
>   field1   double not null,
>   field2  varchar(50),
>   field3    bigint,
>   field4  smallint
> );

The ddl of the table in mysql is like below;

```
CREATE TABLE `table_name` (
  `field1` double NOT NULL AUTO_INCREMENT,
  `field2` varchar(50) DEFAULT NULL,
  `field3` int(11) DEFAULT NULL,
  `field4` tinyint(3) DEFAULT NULL,
  PRIMARY KEY (`field1`),
  KEY `idx_field3` (`field3`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=COMPACT;

```
After that i used load file with the configuration below;

> LOAD database
> ...
> WITH
>   create tables,
>   create indexes,
>   foreign keys,
>   downcase identifiers,
>   schema only
> 
> CAST
>   type year to smallint  drop typemod,
>   type double to double precision drop typemod
> ;
> 

This time i've got this syntax error below. 

> 
> ...
> At
> 
>     type year to smallint  drop typemod,
>     type double to double precision drop typemod
> 
>                           ^ (Line 18, Column 24, Position 339)
> 
> In context COMMAND:
> 
> While parsing COMMAND. Expected:
> ...
> 

First time with pgloader, so I am not sure if this is a bug. Am I missing something? 

pgloader version (just compiled from source today)
```
pgloader version "3.4.db7a91d"
compiled with SBCL 1.3.14.debian
```

Thanks

**Comment by dimitri** [comment]
Hi,

So what is the expected behaviour when using a *double* data type in MySQL with the *auto_increment* facility? By how much does it increment? what if you have non-integers data in the column now?

I am wondering what the default target data type for PostgreSQL should be. Either we keep the *auto_increment* facility with a sequence and have to cast all the floating point numbers to integers on the way, error on floats with a decimal part. Or we target a *double precision* data type but lose the *auto_increment* facility, which would be a *sequence* in PostgreSQL.

Related : https://bugs.mysql.com/bug.php?id=31032

Maybe for pgloader to refuse handling such a data type is the right behavior here. Consider fixing your MySQL schema and then running the migration?

**Comment by sahapasci** [comment]
I really know that auto_increment in double is really silly :(. Moreover, you are absolutely right about default behavior. Maybe giving an error like 'type "double" (auto_increment) does not exist.' would be better.
Anyway, long story short, unfortunately, fixing the mysql schema is not practically possible. However if there is a way (or for my situation a workaround) like mapping double auto increment field into a bigserial i would appreciate.

**Comment by sahapasci** [comment]
Just found the solution in documentation. I am trying it now; 

```
CAST
  type double with extra auto_increment  
    to bigserial drop typemod keep default keep not null
;
```

**Comment by sahapasci** [comment]
Solved with the configuration above. Closing the issue, thanks.

**Comment by dimitri** [comment]
Glad you found how to solve it, sorry I was focusing on whether this should be default in pgloader, and I'm quite reluctant to doing so. Thanks to have reported your solution here for other users to find.

**Comment by hashaam-zameen** [comment]
sahapasci how to use load file with configuration ?
LOAD database
...
WITH
create tables,
create indexes,
foreign keys,
downcase identifiers,
schema only

CAST
type year to smallint drop typemod,
type double to double precision drop typemod
;

where is it located?

**Comment by hashaam-zameen** [comment]
ERROR Database error 42704: type "double" does not exist
QUERY: CREATE TABLE byt_main.byt_comments 
(
  comment_id     double not null,
  comment_userid double precision,
  comment_by     varchar(75),
  comment_date   timestamptz,
  comment_text   bytea
);
2021-05-18T07:04:16.988167+01:00 FATAL Failed to create the schema, see above.
2021-05-18T07:04:16.988213+01:00 LOG report summary reset
       table name     errors       rows      bytes      total time
-----------------  ---------  ---------  ---------  --------------
  fetch meta data          0       2586                     5.214s
   Create Schemas          0          0                     0.001s
 Create SQL Types          0        201                     0.134s
    Create tables          0          0                     0.000s
-----------------  ---------  ---------  ---------  --------------
-----------------  ---------  ---------  ---------  --------------

**Comment by goldman7911** [comment]
I have a customer MySQL dump that does not have auto_increment yet I was getting the same error message and then I fixed by following this CAST here

 CAST type double with extra auto_increment to double drop typemod
 
 This is a bit of customer MySQL dump
 
 ```
-- MySQL dump 10.13  Distrib 8.0.19, for Win64 (x86_64)
--
-- Host: 127.0.0.1    Database: XXX
-- ------------------------------------------------------
-- Server version	5.7.44

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `pmts_rf`
--

DROP TABLE IF EXISTS `pmts_rf`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `pmts_rf` (
  `xxx` double DEFAULT NULL,
  `xxx$RF` double DEFAULT NULL,
  `xxx$RF` double DEFAULT NULL,
  `xx$RF` double DEFAULT NULL,
  `xxx$RF` double DEFAULT NULL,
  `xxx` double DEFAULT NULL,
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
``` 

this is my compose to load this dump

```
  mysql-xxxx-xx:
    image: mysql:8.0.33-debian
    environment:
      MYSQL_ROOT_PASSWORD: xxx
      MYSQL_DATABASE: xxx
      MYSQL_USER: xxx
      MYSQL_PASSWORD: xxx
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - ./dump-xxxx-202411251033.sql:/docker-entrypoint-initdb.d/dump.sql
    command: ["--character-set-server=utf8mb3", "--skip-character-set-client-handshake", "--innodb-file-per-table=1", "--innodb-strict-mode=OFF", "--default-authentication-plugin=mysql_native_password"]
```

My .load file:

![image](https://github.com/user-attachments/assets/6fb33855-64bb-49d6-a35e-96c9bbf0cc0c)

without that it doesn't work at all with the same error syntax error
