### ISSUE TITLE
geolite example: ip4r is not avaible for pg10

### ISSUE THREAD

**Issue by wibrt** [dimitri/pgloader#670]
This example doesn't work anymore for pg10:

http://pgloader.io/howto/geolite.html

as it needs the extension ip4r.

Not directly a pgloader issue.., just for this example

**Comment by dimitri** [comment]
Can you open an issue at https://github.com/RhodiumToad/ip4r ?

**Comment by wibrt** [comment]
Done

**Comment by RhodiumToad** [comment]
ip4r works fine on pg 10, so I'm completely at a loss as to what you think the issue is.

**Comment by wibrt** [comment]
probably a misunderstanding, this issue is closed,
at the time i ran into this the ip4r extension was not yet available for pg 10 (using apt.postgresql.org);
so no worries
