### ISSUE TITLE
pgloader windows runtime error

### ISSUE THREAD

**Issue by chdemars** [dimitri/pgloader#671]
I was able to compile pgloader-3.4.1 under cygwin on Windows7.

When running it, either under a cygwin command prompt or cmd.exe, I get the following error:

FATAL error: URL "/pgsql/list-typenames-without-btree-support.sql" not found!
An unhandled error condition has been signalled:
   URL "/pgsql/list-typenames-without-btree-support.sql" not found!

I have tried creating a /pgsql directory with the required sql files in cygwin to no avail.

Is there an easy solution for such an error?

**Comment by dimitri** [comment]
The file should be loaded within the binary at compile time, can you see if you have any compile-time errors you might have overlooked? Also, I don't think you need cygwin to compile pgloader on Windows, thanks to both CCL and SBCL being available natively for the platform.

**Comment by chdemars** [comment]
CCL and SBCL might be native, but the GNUWin32 make barfs trying to use the unix commands.


E:\software\pgloader-3.4.1>"C:\Program Files (x86)\GnuWin32\bin\make.exe" clean
rm -rf build/libs.stamp build/quicklisp build/manifest.ql build/bin/buildapp.sbc
l.exe build/bin/pgloader.exe
process_begin: CreateProcess(NULL, rm -rf build/libs.stamp build/quicklisp build
/manifest.ql build/bin/buildapp.sbcl.exe build/bin/pgloader.exe, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [clean] Error 2

E:\software\pgloader-3.4.1>"C:\Program Files (x86)\GnuWin32\bin\make.exe" pgload
er
mkdir -p build
A subdirectory or file -p already exists.
Error occurred while processing: -p.
make: *** [build/quicklisp/setup.lisp] Error 1



Yeah, I should be running this on Linux, or at least the Linux subsystem on Win10, but this is a work computer without those options available.

**Comment by dimitri** [comment]
I don't know windows well enough to help, I'll remember about cygwin being necessary. Last I tried I played with https://mobaxterm.mobatek.net instead, which provides a terminal with bash and the usual tooling without being either cygwin nor a WSL subsystem. Might help you?

Anyway, do you have compile errors related to this `/pgsql/` trick?

**Comment by chdemars** [comment]
No errors stand out. Attached is the output of a make run.

[make.txt](https://github.com/dimitri/pgloader/files/1476700/make.txt)

**Comment by chdemars** [comment]
Installed mobaxterm and accessory software (make et al).

Still the same error (and like cygwin, coping the sql file to /pgsql didn't do anything):

pgloader nhd_dbf.load
KABOOM!
FATAL error: URL "/pgsql/list-typenames-without-btree-support.sql" not found!
An unhandled error condition has been signalled:
   URL "/pgsql/list-typenames-without-btree-support.sql" not found!

**Comment by dimitri** [comment]
As you can see in the build logs, we have the following line:

```
build/bin/buildapp.sbcl.exe      --logfile /tmp/build.log
```

Can you retrieve the `/tmp/build.log` file, which should contain the interesting bits here?

**Comment by dimitri** [comment]
Nowadays it should be simpler to build pgloader for windows thanks to the `src/save.lisp` file. Try either of those commands:

``` bash
$ sbcl --noinform --no-sysinit --no-userinit --load ./src/save.lisp
$ ccl --no-init --load ./src/save.lisp
```
