### ISSUE TITLE
pgloader does not print any info why import failed

### ISSUE THREAD

**Issue by xylo** [dimitri/pgloader#674]
I wanted to import my local mysql database to my local postgres server via
`pgloader "mysql://USERNAME:PASSWORD@localhost/DBNAME" "psql:///DBNAME"
`
However, `pgloader` finished within 0.1s, but did not import anything and did not print anything on the console.  Shouldn't there be any hint telling me what I did wrong?

**Comment by xylo** [comment]
OK, I run the same command with "-d" and "-v".  Now I get at least some info:
```
sb-impl::*default-external-format* :UTF-8
tmpdir: #P"/tmp/pgloader/"
2017-11-16T14:48:04.019000Z NOTICE Starting pgloader, log system is ready.
2017-11-16T14:48:04.032000Z INFO Starting monitor
2017-11-16T14:48:04.037000Z INFO Stopping monitor
```
However, I don't see any error message here.  And I also could not find an error message in `/tmp/pgloader/pgloader.log`.

**Comment by xylo** [comment]
OK, I found another guide that used a slightly different syntax: `postgresql://` instead of `pgsql://`.  After that I got useful messages from pgsql.  However, it would be nice if pgsql could tell me that it does not know the protocol/database pgsql.  That would make things much easier.

**Comment by xylo** [comment]
pgloader version "3.4.1"
compiled with SBCL 1.3.3.debian

**Comment by dimitri** [comment]
So `PostgreSQL://` and `pgsql://` are parsed as the same thing, so it shouldn't be a difference then. About the lack of output, I need to investigate that. We have had problems with errors that occur right at the sartup of pgloader not being reported. Can you please try from the current source version?

**Comment by mjmeyer** [comment]
Any resolution to this issue? Getting the same result (er, complete lack of) with 3.4.1 installed via apt.postgresql.org on ubuntu 16.04.

Will try build from source tomorrow.

**Comment by dimitri** [comment]
Yeah, please try a build from source and tell us your findings!
