### ISSUE TITLE
Need Common Lisp Documentation or Tutorial

### ISSUE THREAD

**Issue by Symbolics** [dimitri/pgloader#675]
I only recently discovered that pgloader was written in CL. Amazing really, but a very happy coincidence. This issue is around the documentation for CL hackers, who might want to embed pgloader into an application. The documentation of the command line interface is very good, but after spending the better part of a day looking at the code I see that learning by source is a long road. Even a simple CL tutorial, e.g. How to load a CSV file from a URL would be a great start.

**Comment by dimitri** [comment]
Here's a sample use case from the SLIME REPL:

```lisp
CL-USER> (pgloader:run-commands "/Users/dim/dev/pgloader/test/csv.load" :client-min-messages :warning)
2017-11-19T16:23:40.100753+01:00 WARNING pgloader always talk to PostgreSQL in utf-8, client_encoding has been forced to 'utf8'.
2017-11-19T16:23:40.255434+01:00 LOG report summary reset
             table name     errors       rows      bytes      total time
-----------------------  ---------  ---------  ---------  --------------
                  fetch          0          0                     0.000s
            before load          0          2                     0.057s
-----------------------  ---------  ---------  ---------  --------------
                    csv          0          6     0.2 kB          0.012s
-----------------------  ---------  ---------  ---------  --------------
        Files Processed          0          1                     0.001s
COPY Threads Completion          0          2                     0.012s
-----------------------  ---------  ---------  ---------  --------------
      Total import time          ✓          6     0.2 kB          0.014s
NIL
```

Another example using the `load-data` API:

```
(pgloader:load-data :from (pgloader:parse-source-string-for-type :csv "path/to/test/data/2013_Gaz_113CDs_national.txt")
                             :into (pgloader:parse-target-string "pgsql:///pgloader")
                             :target-table-name "districts"
                             :options '(:truncate t))
```

To answer the main question about the documentation, I am now considering readthedocs.io in order to maintain a real manual rather than a single giant file. This could include CL level API documentation too, where currently you have to read the sources and doc strings.

**Comment by Symbolics** [comment]
Thank you. Do the load files have an equivalent form in S expressions? That would be a very useful way to build up load commands.

**Comment by dimitri** [comment]
They do, see `lisp-code-for-loading` that expends from the main API to a detailed CL usage, the one that is compiled by pgloader from its command at run time.

**Comment by dimitri** [comment]
Nope, it's not been written yet. I don't know when I might be able to get around to it...

**Comment by meglio** [comment]
To start with, an example of how to use `USING` with an inline lisp function declaration would do. Many thanks for your great work!
