### ISSUE TITLE
Over length / debugger invoked on a TYPE-ERROR in thread

### ISSUE THREAD

**Issue by kxjhlele** [dimitri/pgloader#677]
table :

```sql
CREATE TABLE z.cb
(
    sdate date,
    type character(3),
    uid character varying(20),
    network character varying(20),
    btime timestamp without time zone
);
```

csv :

```
1|3534050678389401|2017-11-18 23:59:26
2|013607002155040861457032658620|2017-11-18 23:59:26
3||2017-11-18 23:59:26
4|866947022686800|2017-11-18 23:59:26
```

ctl :

```
 LOAD CSV  
      FROM '/home/CB'  
      (
      uid , 
      network , 
      btime [ date format 'YYYY-MM-DD HH24:MI:SS' ] 
      )
      INTO postgresql://postgres:postgres@192.168.61.21:9700/postgres?z.cb  
      (
      sdate date using ( identity  btime ), 
      type text using "CBB", 
      uid, 
      network, 
      btime
      )
      WITH  
           fields terminated by '|';
```

error :

```
debugger invoked on a TYPE-ERROR in thread
#<THREAD "lparallel" RUNNING {100765F033}>:
  The value
    NIL
  is not of type
    NUMBER
2017-11-21T07:06:18.298000Z ERROR PostgreSQL ["citus.cb"] Database error 22001: (20)
CONTEXT: COPY cb,  2,  network: "013607002155040861457032658620"
```

**Comment by dimitri** [comment]
Here's what I have when I try to reproduce locally:

```
2017-11-22T01:31:04.117759+01:00 ERROR PostgreSQL ["t677"] Database error 22001: value too long for type character varying(20)
CONTEXT: COPY t677, line 2, column network: "013607002155040861457032658620"
2017-11-22T01:31:04.122767+01:00 LOG report summary reset
             table name     errors       rows      bytes      total time
-----------------------  ---------  ---------  ---------  --------------
                  fetch          0          0                     0.000s
            before load          0          2                     0.019s
-----------------------  ---------  ---------  ---------  --------------
                   t677          1          3     0.2 kB          0.022s
-----------------------  ---------  ---------  ---------  --------------
        Files Processed          0          1                     0.005s
COPY Threads Completion          0          2                     0.023s
-----------------------  ---------  ---------  ---------  --------------
      Total import time          1          3     0.2 kB          0.029s
```

I have used the following self-reproducing test-case, extracted from your detailed bug report:

```
 LOAD CSV  
      FROM inline
      (
          uid , 
          network , 
          btime [ date format 'YYYY-MM-DD HH24:MI:SS' ] 
      )
      INTO postgresql://localhost:5432/pgloader
      target table t677
      (
          sdate date using ( identity  btime ), 
          type text using "CBB", 
          uid, 
          network, 
          btime
      )
      WITH  
           fields terminated by '|'

      BEFORE LOAD DO
      $$ drop table if exists t677; $$,
      $$ CREATE TABLE t677
         (
             sdate date,
             type character(3),
             uid character varying(20),
             network character varying(20),
             btime timestamp without time zone
         );
      $$;


1|3534050678389401|2017-11-18 23:59:26
2|013607002155040861457032658620|2017-11-18 23:59:26
3||2017-11-18 23:59:26
4|866947022686800|2017-11-18 23:59:26
```

**Comment by kxjhlele** [comment]
sorry

debian 9:
psql (PostgreSQL) 10.1：nok

Windows:
psql (PostgreSQL) 10.0: ok
psql (PostgreSQL) 9.6.5 :ok


der version "3.4.1"
compiled with SBCL 1.3.14.debian

**Comment by kxjhlele** [comment]
Build from sources：
pgloader version "3.4.6964764"
compiled with SBCL 1.3.14.debian

Debian 9：
psql（PostgreSQL）10.1：ok 

Windows：
psql（PostgreSQL）10.1：ok 
psql（PostgreSQL）9.6.5：ok

**Comment by dimitri** [comment]
I'm not sure what to do with the information provided, now. Can you confirm SBCL versions in test cases where it works compared to where if fails? I would be quite surprised that it boils down to SBCL itself, but if you have all the installations around let's have a look. Thanks.

**Comment by kxjhlele** [comment]
root@debian:~# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.2 (stretch)
Release:        9.2
Codename:       stretch

root@debian:~# uname -a
Linux debian 4.9.0-2-amd64 #1 SMP Debian 4.9.13-1 (2017-02-27) x86_64 GNU/Linux

root@debian:~# apt-get install postgresql-9.6
root@debian:~# psql --version
psql (PostgreSQL) 9.6.6

root@debian:~# apt-get install pgloader
root@debian:~# pgloader --version
pgloader version "3.4.1"
compiled with SBCL 1.3.14.debian

root@debian:~# su - postgres
postgres@debian:~$ psql
psql (9.6.6)
postgres=# \password
new password：postgres
postgres=# \q

root@debian:~# cd /home
root@debian:/home# pgloader CB.CTL

error:
debugger invoked on a TYPE-ERROR in thread
#<THREAD "lparallel" RUNNING {1007A689C3}>:
  The value
    NIL
  is not of type
    NUMBER
2017-11-23T02:50:10.485000Z ERROR PostgreSQL ["cbb"] Database error 22001: (20)
CONTEXT: COPY cbb,  2,  network: "013607002155040861457032658620"

ctl:
 LOAD CSV  
      FROM '/home/CB'  
      (
      uid , 
      network , 
      btime [ date format 'YYYY-MM-DD HH24:MI:SS' ] 
      )
      INTO postgresql://postgres:postgres@127.0.0.1:5432/postgres?cbb  
      (
      sdate date using ( identity  btime ), 
      type text using "CBB", 
      uid, 
      network, 
      btime
      )
 
      WITH  
           fields terminated by '|'
           
                 BEFORE LOAD DO
      $$ drop table if exists cbb; $$,
      $$ CREATE TABLE cbb
         (
             sdate date,
             type character(3),
             uid character varying(20),
             network character varying(20),
             btime timestamp without time zone
         );
      $$;

csv:
1|3534050678389401|2017-11-18 23:59:26
2|013607002155040861457032658620|2017-11-18 23:59:26
3||2017-11-18 23:59:26
4|866947022686800|2017-11-18 23:59:26

**Comment by dimitri** [comment]
That's with pgloader 3.4.1 though, not a fresh build from source... so we already had that information I think...

**Comment by kxjhlele** [comment]
debian issues or SBCL issues, 
build from sources also have problems,
What version are you using（system, postgres, pgloader）?

**Comment by dimitri** [comment]
I am currently using the following version, on a MacOSX system:

```
pgloader version "3.4.d69b720"
compiled with SBCL 1.3.20
```

The error you have is not a PostgreSQL problem, it is a pgloader condition handling problem. It might be only in SBCL 1.3.14.debian. Can you build from sources with a more recent version of SBCL?

**Comment by kxjhlele** [comment]
no ok

root@debian0:/home# /root/pgloader/build/bin/pgloader --version
pgloader version "3.4.6964764"
compiled with SBCL 1.4.1
root@debian0:/home# /root/pgloader/build/bin/pgloader CB.CTL

debugger invoked on a TYPE-ERROR in thread
#<THREAD "lparallel" RUNNING {10074CE6C3}>:
  The value
    NIL
  is not of type
    NUMBER
  when binding SB-KERNEL::Y

---
root@debian0:/home# /root/pgloader/build/bin/pgloader --version
pgloader version "3.4.6964764"
compiled with SBCL 1.3.20
root@debian0:/home# /root/pgloader/build/bin/pgloader CB.CTL

debugger invoked on a TYPE-ERROR in thread
#<THREAD "lparallel" RUNNING {100765B373}>:
  The value
    NIL
  is not of type
    NUMBER
  when binding SB-KERNEL::Y

**Comment by kxjhlele** [comment]
yes， to  dim@tapoueh.org

**Comment by dimitri** [comment]
I got the expected result again, could still not reproduce. I might have to try that on a debian machine then, but that's rather strange that such an error would come to that...

```
2017-11-28T06:32:15.102000-08:00 LOG Main logs in '/private/tmp/pgloader/pgloader.log'
2017-11-28T06:32:15.126000-08:00 LOG Data errors in '/private/tmp/pgloader/'
2017-11-28T06:32:15.126000-08:00 LOG Parsing commands from file #P"/Users/dim/dev/temp/pgloader-issues/677/cb/cb.load"
2017-11-28T06:32:15.479000-08:00 ERROR PostgreSQL ["cbb"] Database error 22001: value too long for type character varying(20)
CONTEXT: COPY cbb, line 2, column network: "01360700215504f861457032658620"
2017-11-28T06:32:15.480000-08:00 ERROR PostgreSQL ["cbb"] Database error 22001: value too long for type character varying(20)
CONTEXT: COPY cbb, line 1, column network: "013607ee215504f861457032658620"
2017-11-28T06:32:15.481000-08:00 LOG report summary reset
             table name     errors       rows      bytes      total time
-----------------------  ---------  ---------  ---------  --------------
                  fetch          0          0                     0.010s
            before load          0          2                     0.037s
-----------------------  ---------  ---------  ---------  --------------
                    cbb          2          3     0.3 kB          0.045s
-----------------------  ---------  ---------  ---------  --------------
        Files Processed          0          1                     0.043s
COPY Threads Completion          0          2                     0.077s
-----------------------  ---------  ---------  ---------  --------------
      Total import time          2          3     0.3 kB          0.120s
```

**Comment by kxjhlele** [comment]
Your system version

**Comment by kxjhlele** [comment]
I'm sorry, it may be the problem of my old system.
I changed a brand new system no problem.


lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.2 (stretch)
Release:        9.2
Codename:       stretch

uname -a
Linux Pg3 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux

psql --version
psql (PostgreSQL) 10.1

pgloader --version
pgloader version "3.3.2"
compiled with SBCL 1.3.14.debian

pgloader CB.CTL
2017-11-30T09:53:55.076000Z LOG Main logs in '/tmp/pgloader/pgloader.log'
2017-11-30T09:53:55.081000Z LOG Data errors in '/tmp/pgloader/'
2017-11-30T09:53:55.081000Z LOG Parsing commands from file #P"/home/CB.CTL"
2017-11-30T09:53:56.973000Z ERROR Database error 22001: value too long for type character varying(20)
CONTEXT: COPY cbb, line 2, column network: "01360700215504f861457032658620"
2017-11-30T09:53:56.986000Z ERROR Database error 22001: value too long for type character varying(20)
CONTEXT: COPY cbb, line 1, column network: "013607ee215504f861457032658620"
             table name       read   imported     errors      total time       read      write
-----------------------  ---------  ---------  ---------  --------------  ---------  ---------
                  fetch          0          0          0          0.068s
            before load          2          2          0          0.232s
-----------------------  ---------  ---------  ---------  --------------  ---------  ---------
                    cbb          5          3          2          0.290s     0.189s    0.022s
-----------------------  ---------  ---------  ---------  --------------  ---------  ---------
        Files Processed          1          1          0          0.582s
COPY Threads Completion          3          3          0          0.095s
-----------------------  ---------  ---------  ---------  --------------  ---------  ---------
      Total import time          5          3          2          2.251s     0.189s    0.022s

**Comment by dimitri** [comment]
Thanks for letting us know, good luck with your new system then!
