### ISSUE TITLE
SQLite fails to copy all rows, fails with KABOOM!

### ISSUE THREAD

**Issue by richardkmichael** [dimitri/pgloader#681]
Hello!

I am using this loader file:

```
LOAD DATABASE
  FROM sqlite://./db/data.sqlite
  INTO postgresql:///test
  INCLUDING ONLY TABLE NAMES LIKE 'activities'
  CAST COLUMN activities.created_when TO TIMESTAMP DROP DEFAULT;
```

pgloader copies only 963 rows of the 1119 rows in the `data.sqlite`:

```
  $ sqlite3 db/data.sqlite 'SELECT count(*) FROM activities;'
1119

 $ psql test -c 'SELECT count(*) FROM activities;'
 count
-------
   963
(1 row)
```

pgloader KABOOMS! with:

```
KABOOM!
FATAL error: There is no applicable method for the generic function
               #<STANDARD-GENERIC-FUNCTION PGLOADER.CATALOG:FORMAT-TABLE-NAME (1)>
             when called with arguments
               (NIL).
Date/time: 2017-11-22-18:12An unhandled error condition has been signalled:
                              There is no applicable method for the generic function
                                #<STANDARD-GENERIC-FUNCTION PGLOADER.CATALOG:FORMAT-TABLE-NAME (1)>
                              when called with arguments
                                (NIL).
```

I have run with `--debug` and attached separate STDOUT and STDERR to this gist:

https://gist.github.com/richardkmichael/701fc413d8a1d7d6041fa961f2c2850b

Any idea what I am doing wrong?

PS. Congratulations on the book, I bought it right away. :-)

**Comment by dimitri** [comment]
It looks like a problem with foreign keys leading to tables that are not part of the selected tables of your INCLUDING clause. It should have been fixed awhile ago now, so can you please try to compile a fresh version of pgloader from sources and try again? If it still fails, please consider providing me with a SQLite database and .load file with which to reproduce the bug locally.

Thanks for the book, I hope you'll like it!

**Comment by richardkmichael** [comment]
Thanks @dimitri !  I just tried pgloader `master`, but it had the same problem.

```
$ pgloader --version
pgloader version "3.4.d69b720"
compiled with SBCL 1.4.1
```

In case there is different or new information, I created a new gist with STDOUT and STDERR: https://gist.github.com/richardkmichael/7c2095624dcdacfe959d5538bb8c30df

I'm happy to send you the SQLite database and the `.load` file.  How can I get them to you privately?

**Comment by dimitri** [comment]
Please email me the files at my email address as seen on my GitHub profile. Thanks!

**Comment by dimitri** [comment]
I believe the bug is not fixed, please try from a fresh build! If you're using verbose enough log settings you should see a line like the following:

```
2017-11-26T01:26:46.035532+01:00 INFO Incomplete Foreign Key definition on table activities(activity_type) referencing table NIL(NIL)
```

Also the SQLite table definition is missing some bits. The schema definition for the table includes `activity_type integer not null references programs_and_event_types` and then the catalogs have the following content:

```
id          seq         table                     from           to          on_update   on_delete   match     
----------  ----------  ------------------------  -------------  ----------  ----------  ----------  ----------
0           0           programs_and_event_types  activity_type              NO ACTION   NO ACTION   NONE      
```

I'm not sure what's happening here, but pgloader now protects itself against the situation.

**Comment by richardkmichael** [comment]
Thanks @dimitri, the table now loads!  pgloader has helped me find a bug in the schema and one problem in the data.  The foreign key table is incorrectly specified (`programs_..` vs. `program_...`).  SQLite is quite tolerant it seems.

The `INFO Incomplete Foreign Key` log line is very helpful, so I was experimenting with pgloader invocation to be sure I always run it with enough verboseness to see such messages.  I noticed that when I run pgloader with `--debug`, it does not always output identical information.  Some executions were missing quite a bit of information, including the missing foreign key warning.

```
$ for i in {1..10} ; do
  dropdb test ; createdb test ;
  pgloader --debug activities.load > stdout-${i}.log 2> stderr-${i}.log
done

$ find . -iname stdout-\*.log -printf '%f - %s bytes\n'
stdout-01.log - 8947 bytes
stdout-02.log - 8947 bytes
stdout-03.log - 9562 bytes
stdout-04.log - 9562 bytes
stdout-05.log - 8947 bytes
stdout-06.log - 9562 bytes
stdout-07.log - 6506 bytes
stdout-08.log - 8486 bytes
stdout-09.log - 9562 bytes
stdout-10.log - 9562 bytes
```

I compared the `stdout-01.log` with `stdout-03.log`, and noticed the difference: `-01` is missing `LOG` lines.  I can't easily diff because there is a different timestamp on every line, but comparing by removing `LOG` lines is probably close enough:

```
$ grep -v '05:00 LOG' stdout-03.log > stdout-03-no-LOG.log

$ find . -iname stdout-0[13]\*.log -printf '%f - %s bytes\n'
stdout-01.log - 8947 bytes
stdout-03-no-LOG.log - 8947 bytes
stdout-03.log - 9562 bytes

$ grep '05:00 LOG' stdout-01.log
# NO OUTPUT
```

However it is not always`LOG` lines that are missing.  In other output, the foreign key `INFO` message is missing. (Perhaps all `INFO` lines are missing, I didn't inspect the other files with different size.)

FWIW, it appears the 9562 byte file is the full output.

Any thoughts?  I can open a new issue, if it's a problem with pgloader.

**Comment by dimitri** [comment]
Yeah I think it's a problem with pgloader. Please open a new issue!
