### ISSUE TITLE
Pg table names are prefixed with mysql database

### ISSUE THREAD

**Issue by iredmedia** [dimitri/pgloader#682]
After successfully migrating, each table was prefixed with "forge." (the mysql database name), so I ended up with "forge.users", "forge.roles" etc.

I'm wondering if this is expected behaviour (and if so, why . and not _)? Would I be able to override this somehow? I couldn't find anything in the docs relating to this, or the issues here (which makes me wonder what I'm doing wrong :\!

Any help is greatly appreicated! Cheers!

**Comment by dimitri** [comment]
Yes it's expected. What MySQL names a database is a schema in the SQL standard and when using PostgreSQL. In PostgreSQL you can set your search_path to include any schema you want and then avoid typing the schema name, it's called using unqualified relation names.

In current version of pgloader (HEAD, git sources), pgloader changes the `search_path` of the target database automatically for you, though.
