### ISSUE TITLE
`pgloader --debug` output is not consistent between executions.

### ISSUE THREAD

**Issue by richardkmichael** [dimitri/pgloader#683]
(Moved from a comment on #681)

The `INFO Incomplete Foreign Key` log line is very helpful, so I was experimenting with pgloader invocation to be sure I always run it with enough verboseness to see such messages.  I noticed that when I run pgloader with `--debug`, it does not always output identical information.  Some executions were missing quite a bit of information, including the missing foreign key warning.

```
$ for i in {1..10} ; do
  dropdb test ; createdb test ;
  pgloader --debug activities.load > stdout-${i}.log 2> stderr-${i}.log
done

$ find . -iname stdout-\*.log -printf '%f - %s bytes\n'
stdout-01.log - 8947 bytes
stdout-02.log - 8947 bytes
stdout-03.log - 9562 bytes
stdout-04.log - 9562 bytes
stdout-05.log - 8947 bytes
stdout-06.log - 9562 bytes
stdout-07.log - 6506 bytes
stdout-08.log - 8486 bytes
stdout-09.log - 9562 bytes
stdout-10.log - 9562 bytes
```

I compared the `stdout-01.log` with `stdout-03.log`, and noticed the difference: `-01` is missing `LOG` lines.  I can't easily diff because there is a different timestamp on every line, but comparing by removing `LOG` lines is probably close enough:

```
$ grep -v '05:00 LOG' stdout-03.log > stdout-03-no-LOG.log

$ find . -iname stdout-0[13]\*.log -printf '%f - %s bytes\n'
stdout-01.log - 8947 bytes
stdout-03-no-LOG.log - 8947 bytes
stdout-03.log - 9562 bytes

$ grep '05:00 LOG' stdout-01.log
# NO OUTPUT
```

However it is not always`LOG` lines that are missing.  In other output, the foreign key `INFO` message is missing. (Perhaps all `INFO` lines are missing, I didn't inspect the other files with different size.)

FWIW, it appears the 9562 byte file is the full output.

**Comment by dimitri** [comment]
Is it possible to compare the standard output capture with the files that should have been created in `/tmp/pgloader`, using `--client-min-message debug --log-min-messages debug` to ensure the same log level in both? That would help me find where the problem comes from (either the log system itself, of the multi-threading layer on-top of it).

**Comment by richardkmichael** [comment]
Sure, here is a gist contains `stdout.log` and `/tmp/pgloader/pgloader.log` when I ran:

```
pgloader --debug --client-min-messages debug --log-min-messages debug activities.load > stdout.log
```


https://gist.github.com/richardkmichael/389cbe33e5814e163a39126f54b2d359

**Comment by richardkmichael** [comment]
FWIW, I'm on OSX 10.12.6 and installed using homebrew at commit `ec309929`, so the versions of quicklisp deps are here:
https://github.com/Homebrew/homebrew-core/blob/ec309929790f422/Formula/pgloader.rb#L36-L314

**Comment by dimitri** [comment]
Closing the issue now, for cleaning-up of the issues dashboard. I'm not sure if we still have the problem in the current version of pgloader or not...
