### ISSUE TITLE
MySQL to PostgreSQL "empty-string-to-null" not working

### ISSUE THREAD

**Issue by ipanousis** [dimitri/pgloader#686]
Hi dimitri,

I am migrating data from MySQL to PostgreSQL and using the configuration:

```
type enum using empty-string-to-null
```

yet I get the error:

```
INFO - 2017-11-17T04:51:06.259000Z ERROR Database error 22P02: invalid input value for enum "discussion_adType": ""
INFO - CONTEXT: COPY discussion, line 169, column adType: ""
```

on any column of any table that has a NULL value in the source record.

Any idea why that may be?

I'm using:

```
pgloader version "3.3.2"
compiled with SBCL 1.2.4.debian
```

Thanks!

**Comment by dimitri** [comment]
The function empty-string-to-null` will convert from an empty string to a NULL, not the other way round. So if you have NULL value in the source record, that function isn't going to help you.

**Comment by ipanousis** [comment]
Sorry dimitri. I further understood the issue in my source data after posting. I have NULL values but the problem doesn't lie with them. I do indeed have some empty string values (which I don't know why MySQL accepts in the first place, given they aren't part of the ENUM type definition), and they are the ones causing the problem.
