### ISSUE TITLE
( if ( string-equal  ) )  Streamline ? eg: oracle decode

### ISSUE THREAD

**Issue by kxjhlele** [dimitri/pgloader#687]
pgloader :
```
uid text using ( if ( string-equal "WLAN" uid ) "-2" ( if ( string-equal "4" uid ) "-1" ( if ( string-equal "3" uid ) "-1" ( if ( string-equal NIL uid ) "-1" uid)))) , 
```

oracle sqlldr ctl :

```
uid "decode(:network,'3',-1,'4',-1,null,-1,'6',4,'1',3,:uid)",
```

thx.

**Comment by dimitri** [comment]
What's your question?

**Comment by kxjhlele** [comment]
There are no similar to decode the wording

**Comment by dimitri** [comment]
If you actually want any kind of help, you need to describe your use case. What is your input looking like, and what is the output that you want from it. Without that, it is not possible to be of any help.

**Comment by kxjhlele** [comment]
The main purpose is data aggregation，
Different sources, different definitions，
