### ISSUE TITLE
Import hangs on DISABLE TRIGGER ALL on random tables

### ISSUE THREAD

**Issue by voidmain** [dimitri/pgloader#688]
I'm seeing an issue during an import when it gets to the stages of disabling and re-enabling triggers. I've turned on debug output and nothing jumps out. pgloader isn't using any CPU and pretty minimal memory.

Here's the latest output I have from when it hangs:

```
debugger invoked on a CL-POSTGRES-ERROR:INSUFFICIENT-PRIVILEGE in thread
#<THREAD "lparallel" RUNNING {100A39D0B3}>:
  Database error 42501: permission denied: "RI_ConstraintTrigger_a_17733" is a system trigger
QUERY: ALTER TABLE automated_content_user_actions DISABLE TRIGGER ALL;
2017-11-30T23:12:08.492000Z NOTICE SET search_path TO public;
2017-11-30T23:12:08.492000Z NOTICE ALTER TABLE automated_content_user_actions DISABLE TRIGGER ALL;
2017-11-30T23:12:08.492000Z ERROR Database error 42501: permission denied: "RI_ConstraintTrigger_a_17733" is a system trigger
QUERY: ALTER TABLE automated_content_user_actions DISABLE TRIGGER ALL;
```

This is pretty random though. Each time I run it, it hangs on different tables, but it is always on the trigger steps.

My config file looks like this

```
LOAD DATABASE
	FROM mysql://source/cleanspeak
	INTO postgresql://dest/cleanspeak

WITH include no drop, truncate, create no tables, create no indexes, no foreign keys, reset sequences, data only, disable triggers

ALTER SCHEMA 'cleanspeak' RENAME TO 'public'

CAST type binary when (= precision 16) to uuid drop typemod using sql-server-uniqueidentifier-to-uuid,
	type integer with extra auto_increment to integer keep default keep not null,
	type bit when (= precision 1) to boolean drop typemod using bits-to-boolean;
```

I'm running version 3.4.1 from the postgresql apt repository on a AWS t2.medium EC2 instance with Ubuntu Xenial.

**Comment by voidmain** [comment]
Forgot to mention that this works fine on my MacBook Pro with the same databases. Only difference seems to be the versions of MySQL and PostgreSQL running on the Linux servers and on my MBP.

**Comment by dimitri** [comment]
Can you tell me more about those PostgreSQL versions, and the connecting roles too? My bet is that one of the environments connects as superuser, not the other...

**Comment by voidmain** [comment]
PostgreSQL local is 9.6.5 and remote is 9.5.10. However, we have setup other environments with versions of 9.6 and it still hangs. 

You are probably correct though, the local user we tested with is a SUPERUSER. The one in EC2 isn't a SUPERUSER I think, but I'd have to check the permissions. Not sure why that would matter since the database and schema are owned by the user we are using and we have granted all privileges to that user on that database and schema.

We changed up our configuration file and managed to get it working though. We let pgloader create the entire schema without indexes or foreign keys and then we create them all manually (because it wasn't creating them quite right). This didn't hang and was using the same users. Not sure if that data point helps you determine the root cause, but thought I would add it.

**Comment by ye** [comment]
Older PostgreSQL versions use `RI_ConstraintTrigger_<random_string>` to do referential integrity check and ensure foreign key constraints. Anytime there is a `ALTER TABLE <table_name> DISABLE TRIGGERS ALL` statement called by a non-SUPERUSER (which *none* of the cloud hosted SQL solutions, AWS RDS, GCP CloudSQL, Azure Database as a Service, will grant you SUPERUSER privileges), that aforementioned error will occur as `RI_ConstraintTrigger_<random_string>` is owned by SUPERUSER and cannot be dropped instead will trigger the error.

This a [well-documented issue](http://kopongo.com/2008/7/25/postgres-ri_constrainttrigger-error) in the Ruby Rails community. It can be mitigated with `SET CONSTRAINTS ALL DEFERRED` and then 
`SET CONSTRAINTS ALL IMMEDIATE` in some use-cases, but it's probably much harder for `pgloader` to figure the exact solution if the commands has `disable triggers` option in it.
