### ISSUE TITLE
postgres 10 partition : pgloader found 0 target tables for name z."user":

### ISSUE THREAD

**Issue by kxjhlele** [dimitri/pgloader#690]
table:

```
CREATE TABLE z.user
(   uid text ,
    user_type numeric
) PARTITION BY RANGE (user_type) ;
CREATE TABLE z.user_2 PARTITION OF z.user FOR VALUES FROM ('-2') TO ('3');
CREATE TABLE z.user_3 PARTITION OF z.user FOR VALUES FROM ('3') TO ('4');
CREATE TABLE z.user_4 PARTITION OF z.user FOR VALUES FROM ('4') TO ('6');
```

pgloader: pgloader version "3.4.6964764" / compiled with SBCL 1.3.20

```
/root/pgloader/build/bin/pgloader -v --type csv --field "uid,user_type" /home/user_type.csv postgres://postgres:postgres@192.168.61.21:9700/postgres?z.user

2017-12-01T11:11:48.042000+08:00 NOTICE Starting pgloader, log system is ready.
KABOOM!
FATAL error: pgloader found 0 target tables for name z."user":
An unhandled error condition has been signalled:
   pgloader found 0 target tables for name z."user":

What I am doing here?

pgloader found 0 target tables for name z."user":
```

postgres copy: is ok

```
/copy z.user from '/home/user_type.csv' csv
 COPY 6231478
Query returned successfully in 23 secs.
```

user_type.csv :
```
1,-1
2,-2
3,2
4,3
5,4
6,6
```

**Comment by dimitri** [comment]
That's because in PostgreSQL 10 there's a new *relkind* introduced, as seen in https://www.postgresql.org/docs/current/static/catalog-pg-class.html : 

> r = ordinary table, i = index, S = sequence, t = TOAST table, v = view, m = materialized view, c = composite type, f = foreign table, p = partitioned table

We have the same problem with Foreign Table support in pgloader as seen in https://github.com/dimitri/pgloader/issues/587 ; which gives more details (including pgloader code pointers) about the issue.

Time for me to improve the filter on the `relkind` it seems.

**Comment by dimitri** [comment]
Partitioned tables in PostgreSQL 10 should now be supported, though I must admit I went too fast and didn't reproduce your test case here. Please compile from fresh sources and confirm that what I did is all we need here.

**Comment by kxjhlele** [comment]
thx,
relpersistence  p = permanent table, u = unlogged table, t = temporary table

Are there any plans to support temporary tables?
Temporary tables are automatically dropped at the end of a session,

can use  AFTER LOAD DO 。

**Comment by dimitri** [comment]
Currently the AFTER LOAD DO clause is run in a separate session altogether than the COPY activity, because of the way the code is organised. I could see why it'd be interesting to support that use case, though. Can you tell me more about what you intend to achieve?
