### ISSUE TITLE
How to convert  data and time  to timestamp

### ISSUE THREAD

**Issue by kxjhlele** [dimitri/pgloader#694]
```
 LOAD CSV  FROM *
(
    sdate [date format 'YYYYMMDD' ], 
    stime [date format 'HH24MISS' ]
)
      INTO *
(
      btime timestamp using (format NIL "~A~A" sdate  stime)
)
```

```
CONTEXT: COPY cb, line 1, column btime: "2017-12-02 00:00:0020:19:23"
```

**Comment by dimitri** [comment]
That's not quite enough information. Where is `start_time` coming from, for instance?

**Comment by kxjhlele** [comment]
sorry， is  stime

**Comment by kxjhlele** [comment]
Date format string are template strings modeled against the PostgreSQL to_char template strings support, 
Verify [date format 'YYYYMMDD' ] ，The result is  2017-12-01 00:00:00, not 2017-12-01
Verify [date format 'HH24MISS' ] ，The result is  12:23:24
use " btime timestamp using (format NIL "~A ~A" sdate stime) "  Can solve the date consolidation

ctl:
` LOAD CSV  FROM pg_test.csv
(
    sdate [date format 'YYYYMMDD' ], 
    stime [date format 'HH24MISS' ]
)
  INTO {{PG_DB_URI}}
  TARGET TABLE pg_test
(
      btime timestamp using (format NIL "~A ~A" sdate stime)
)
  WITH  
    fields terminated by ','

  BEFORE LOAD DO
    $$ DROP TABLE IF EXISTS pg_test; $$ ,
    $$ CREATE TABLE pg_test (
      btime timestamp
      ) ; $$ ;
`

error:
`pgloader pg_test.ctl
2017-12-11T08:27:17.305000+08:00 ERROR PostgreSQL ["pg_test"] Database error 22007: invalid input syntax for type timestamp: "2017-12-01 00:00:00 12:23:24"
CONTEXT: COPY pg_test, line 1, column btime: "2017-12-01 00:00:00 12:23:24"
2017-12-11T08:27:17.306000+08:00 ERROR PostgreSQL ["pg_test"] Database error 22007: invalid input syntax for type timestamp: "2017-12-01 00:00:00 12:23:25"
CONTEXT: COPY pg_test, line 1, column btime: "2017-12-01 00:00:00 12:23:25"
`

if ctl, not error:
` LOAD CSV  FROM pg_test.csv
(
    sdate, 
    stime
)
  INTO {{PG_DB_URI}}
  TARGET TABLE pg_test
(
      btime timestamp using (format NIL "~A ~A" sdate stime)
)
  WITH  
    fields terminated by ','

  BEFORE LOAD DO
    $$ DROP TABLE IF EXISTS pg_test; $$ ,
    $$ CREATE UNLOGGED TABLE pg_test (
      btime timestamp
      ) ; $$ ;
`

**Comment by dimitri** [comment]
Yes, `date format [...]` always return a full timestamp, even when your format string doesn't contain references to the time parts of it. This should be better documented. Will see about that, thanks for your detailed report!
