### ISSUE TITLE
There is no class named COMMON-LISP:NIL.

### ISSUE THREAD

**Issue by kxjhlele** [dimitri/pgloader#695]
pgloader --version
pgloader version "3.4.b7d87a9"
compiled with SBCL 1.3.14.debian

pgloader -S user.log user.ctl

2017-12-05T15:32:56.855000+08:00 LOG report summary reset
FATAL: Failed to start the monitor thread.

There is no class named COMMON-LISP:NIL.

**Comment by dimitri** [comment]
I'm not a magician. I need more information to be of any help. Please at least provide the full `--debug` output, and some context, such as the load command.

**Comment by kxjhlele** [comment]
table:
`CREATE TABLE z.user_type
(   uid text ,
    user_type numeric
)`

file:
`1,-1
2,-2
3,2
4,3
5,4
6,6`

run:
`pgloader -v -S user_type.log --type csv --field "uid,user_type" /home/user_type.csv postgres://postgres:postgres@192.168.61.21:9700/postgres?z.user_type`

error:
`2017-12-06T11:15:40.226000+08:00 LOG report summary reset
FATAL: Failed to start the monitor thread.

There is no class named COMMON-LISP:NIL.`

**Comment by dimitri** [comment]
Thanks. I could reproduce the problem, which has to do with using `-S user_type.log`. The summary output file extension hints pgloader into which format to use, as per the documentation:

> The format of the filename defaults to being *human readable*. It is possible to have the output in machine friendly formats such as *CSV*, *COPY* (PostgreSQL's own COPY format) or *JSON* by specifying a filename with the extension resp. `.csv`, `.copy` or `.json`.

Now, the bug happens when there's a filename given with another extension than those 3 possibilities.

**Comment by dimitri** [comment]
The bug is now fixed, please compile pgloader from fresh sources again. Here's what I get when trying to reproduce it with the fix:

```
$ ./build/bin/pgloader -S /tmp/user_type.log --type csv --field "uid,user_type" ../temp/pgloader-issues/695/user_type.csv postgres:///pgloader?z.user_type
2017-12-06T20:57:00.045000+01:00 LOG Data errors in '/private/tmp/pgloader/'
2017-12-06T20:57:00.269000+01:00 LOG report summary reset
```

And the summary file looks like:

```
$ cat /tmp/user_type.log
             table name     errors       rows      bytes      total time
-----------------------  ---------  ---------  ---------  --------------
                  fetch          0          0                     0.013s
-----------------------  ---------  ---------  ---------  --------------
            z.user_type          0          6     0.0 kB          0.028s
-----------------------  ---------  ---------  ---------  --------------
        Files Processed          0          1                     0.030s
COPY Threads Completion          0          2                     0.039s
-----------------------  ---------  ---------  ---------  --------------
      Total import time          ✓          6     0.0 kB          0.069s
```

**Comment by kxjhlele** [comment]
oh， thx

**Comment by kxjhlele** [comment]
json bug？ 
pgloader -v -S user_type.json --type csv --field "uid,user_type" /home/user_type.csv postgres://postgres:postgres@192.168.61.21:9700/postgres?z.user_type

`    "DATA": [
        [
            {
                "NAME": , 
                "READ": 622269,
                "ROWS": 622269,
`
should be
"NAME": "z.user_type",
