### ISSUE TITLE
hex to number ? and number + number ?

### ISSUE THREAD

**Issue by kxjhlele** [dimitri/pgloader#696]
ctl:

```
LOAD CSV FROM {{CSVPATH}} 
into postgres
( 
etime time using ( unix-timestamp-to-timestamptz ( + etime 28800 ) ) , 
uid integer using ( parse-integer uid :radix 16 ) 
)
file:
1512523231|183D
1512523235|18DF
1512523236|186E
1512523234|18EE
1512523236|1889
```

error:

```
While parsing SEXP-LIST. Problem:

  The production

    #\+

  does not satisfy the predicate PGLOADER.PARSER::SYMBOL-FIRST-CHARACTER-P.
```

**Comment by dimitri** [comment]
For more complex transformation processing, please consider providing an external lisp file, to load with `--load-lisp-file`. For a detailed example on how to do that, have a look at: https://github.com/dimitri/pgloader/issues/92.

The `+` expression is not parsed correctly within the small s-exp parser, and I'm not sure how to fix that. Providing your own function names will be easier to maintain in the future too.
