### ISSUE TITLE
CSV data from an HTTP compressed file error

### ISSUE THREAD

**Issue by tendres** [dimitri/pgloader#697]
Hi Dimitri,
I am trying to move a working script that uses a local csv file to one that uses streaming CSV data from an HTTP compressed file but I am getting the following error:

debugger invoked on a TYPE-ERROR in thread
#<THREAD "lparallel" RUNNING {100B5B3753}>:
  The value 1342420 is not of type (MOD 1114112).

The command:
`curl -u user:pass https://www.website/file.tbz | bzip2 -c | /usr/bin/pgloader --type csv --field "export_date,id,parent_id,name" --with truncate --with "drop indexes" --with "skip header = 34" --with "fields terminated by '0x01'" - postgresql://user:pass@127.0.0.1:5432/dbname?tablename=public.my_table`

Is it possible to add the 'curl' line into a loader script something like:
`LOAD CSV`
  `FROM curl -u user:pass https://www.website/file.tbz | bzip2 -c | /usr/bin/pgloader`
   `INTO postgresql://user:pass@127.0.0.1:5432/dbname?tablename=public.my_table
   (export_date,id,parent_id,name)`....

And by any chance is there something like --with "skip footer = xx"  available?
Thanks!

**Comment by dimitri** [comment]
Have a look at the Archive example, it might work for you too: https://github.com/dimitri/pgloader/blob/master/test/archive.load.

**Comment by tendres** [comment]
Is your archive.load example utilizing 'streaming CSV data from an HTTP compressed file' UNIX Pipes trick from the Quickstart? - that is my goal.
From the example it is a little unclear to me what is happening in a couple of the lines.

My attempt:
```
LOAD ARCHIVE
    FROM https://user:password@www.website.com/myfile.tbz
    INTO postgresql://tendres:password@127.0.0.1:5432/db_name?tablename=schema_name.table_name  
             ^-- not sure what this line is doing

    LOAD CSV
        FROM '~/file/'		<-- how/where does this decompress?
   INTO postgresql://tendres:password@127.0.0.1:5432/db_name?tablename=schema_name.table_name
        (export_date,
        id,
        parent_id,
        name)
   WITH truncate,
        skip header = 34,
        fields terminated by '0x01',
        lines terminated by '0x02'

   SET work_mem to '32MB',
          maintenance_work_mem to '64 MB';
```

**Comment by dimitri** [comment]
You're right, if you want streaming you need to read from `stdin`, and currently pgloader doesn't know how to replace the shell jobs and pipe mechanisms.

**Comment by tendres** [comment]
Thanks for the confirmation Dimitri - I'll continue to explore that option.
+1 on that wishlist :)
