### ISSUE TITLE
command line null if equivalent

### ISSUE THREAD

**Issue by tendres** [dimitri/pgloader#700]
I have several loader scripts I am converting to command line to take advantage of streaming from `stdin`.
A few scripts are failing from what I believe to be handling of null values.
What is the syntax equivalent for `field1 [ null if "" ]` from .loader when used in the following command line snippet?
`/usr/bin/pgloader --type csv --field "field1"`?
Thanks!
See #617 - looking for your fix from there in command line version.

**Comment by dimitri** [comment]
Did you try the following yet:

    pgloader --type csv --field 'field1 [ null if "" ]'

**Comment by tendres** [comment]
yes - using `--field 'field1 [ null if "" ]'` results in:
```
ERROR Could not parse --fields ("field1 [ null if  ]"):

In context OPTION-NULL-IF:

While parsing OPTION-NULL-IF. Expected:

     the character Tab
  or the character Newline
  or the character Return
  or the character Space
  or the character " (QUOTATION_MARK)
  or the character ' (APOSTROPHE)
  or the string "--"
  or the string "/*"
  or the string "blanks"

Could not parse the command line: see above.
```
Might something need to be escaped?

**Comment by dimitri** [comment]
Yeah it seems like the "" characters didn't make it, but using single quotes at the shell level should make that work. Mmm.

**Comment by tendres** [comment]
Hmmmm using `--field 'field1 [ null if '' ]'` results in the error seen in #617 :
`FATAL The value -1 is not of type SB-INT:INDEX.`
I do not understand the *trim-outer-whitespace* error you referenced, but since I am streaming, can `tr` or `sed` help in any fashion?

**Comment by dimitri** [comment]
By the way, you know you can use `stdin` as the FROM specification in a load file, and thus use

    curl | gunzip | pgloader foo.load

**Comment by tendres** [comment]
That solution fits my case perfectly as I was hoping to utilize a .load file. Thanks!
Unfortunately I am still getting an error with 3 of my 16 tables - all of which come from same source and follow very similar table designs.
` Database error 22P02: invalid input syntax for integer: ""`
Very strange - happens at end of the process and all rows appear to be ingested.
Trimming lines off the end of the file (using sed) does not appear to fix the issue.
I would like to feel a little more confident about the import but my experiments have not helped me to understand what might be happening.

**Comment by dimitri** [comment]
Consider trying the options `--debug --verbose`, then you will see each line as it's read by pgloader and sent over to PostgreSQL. Quite chatty, but very useful for advanced debugging. Also report here any oddities found!

**Comment by tendres** [comment]
Thanks or the suggestions. 
The only hints I've gathered are that my problem tables all use '[ null if "" ]' somewhere...
The only relevant information from verbose returned (which I don't understand) is the following:
```
2017-12-27T22:43:15.367000Z ERROR PostgreSQL ["schema.my_table"] Database error 22P02: invalid input syntax for integer: "
"
CONTEXT: COPY my_table, line 15895, column export_date: "
"
2017-12-27T22:43:15.368000Z INFO Entering error recovery.
2017-12-27T22:43:15.368000Z DEBUG pos: 0 ; err: 15894
2017-12-27T22:43:15.368000Z INFO error recovery at 0/15895, next error at 15894, loading 15894 rows
2017-12-27T22:43:15.368000Z DEBUG pos: 15894 ; err: 15894
2017-12-27T22:43:15.368000Z INFO error recovery at 15894/15895, processing bad row
2017-12-27T22:43:15.368000Z INFO Recovery found 1 errors in 15895 rows
2017-12-27T22:43:15.368000Z DEBUG retry-batch found 1 errors
2017-12-27T22:43:15.368000Z DEBUG copy-batch[0] my_table 15895 rows [724.8 kB] in 0.116000s
2017-12-27T22:43:15.368000Z DEBUG Writer[0] for schema.my_table is done in 268.298000s
2017-12-27T22:43:15.369000Z DEBUG Finished processing WRITER for "schema.my_table"   268.298000s
```

My loader script:
```
LOAD CSV
   FROM stdin
        (
         export_date,
         field1,
         field2     [ null if "" ],
         field3  [ null if "" ],
         field4 [ null if "" ]
        )
   INTO postgresql://user:pass@127.0.0.1:5432/dbname?tablename=eschema.my_table
        (
         export_date,
         field1,
         field2,
         field3,
         field4
        )

   WITH truncate,
        skip header = 34,
        drop indexes,
        fields not enclosed,
        keep unquoted blanks,
        fields terminated by '0x01',
        lines terminated by '0x02'

   SET work_mem to '32MB',
       maintenance_work_mem to '128MB';
```

 Example data:
```
   line# export_date  etc. 
   5153 1513159200425^A512209896^A3610150660602^AA10320WA000273271Y^A^B
   5154 1513159200425^A510277488^A853564126842^A^A2727696^B
   5155 1513159200425^A510705984^A000000132725^A^A^B
   5156 1513159200425^A509411920^A3610150604910^AA10320WA000266738D^A^B
   5157 1513159200425^A487275928^A3610150351821^AA10320WA0002348161^A^B
   5158 1513159200425^A510733400^A886788749054^A^A1268790^B
   5159 1513159200425^A511975600^A886788738522^A^A^B
   5160 1513159200425^A512076648^A3610150655516^AA10320WA0002726784^A^B
   5161 1513159200425^A484883416^A034061130529^A^A^B
   5162 1513159200425^A510246368^A887158031885^A^A2752737^B
   5163 1513159200425^A511651768^A084854299506^A^A2473294^B
   5164 1513159200425^A512060032^A3610150657619^AA10320WA0002729096^A^B
   5165 1513159200425^A510516552^A887158035050^A^A3374876^B
   5166 1513159200425^A513314160^A00802097114628^A^A2500653^B
   5167 1513159200425^A511706928^A3610150641120^AA10320WA000271122I^A^B
   5168 1513159200425^A511717376^A5016681319626^AA10320WA000270467L^A917301^B
   5169 1513159200425^A513629736^A5055532529029^A^A^B
   5170 1513159200425^A513438408^A3610150635167^AA10320WA000270491L^A^B
   5171 1513159200425^A514999248^A3610150703590^AA10320WA000278278X^A^B
```

All of the data looks solid and in the same form as data in other tables which are successful.
Any last hints appreciated on what is being seen with a 'bad row' or I guess I'll leave it be as my import looks good - just getting that weird error at the end of the run.
Thanks as always - awesome work!

**Comment by dimitri** [comment]
Do you have an empty line in the middle of your input file?

It looks like PostgreSQL is receiving a text field that includes a Newline (or Return, or both) character. It must have read that somewhere?

Otherwise closing the issue as you're mentioning you're able to proceed and happy about the result.
