### ISSUE TITLE
FATAL Failed to prepare target PostgreSQL table

### ISSUE THREAD

**Issue by ParadoxFilm** [dimitri/pgloader#702]
Hello, Dimitri!
I use next commands file:
> LOAD CSV  
> FROM 'foo.csv' WITH ENCODING utf8 
> 	HAVING FIELDS
> 	( x,y,z )
> INTO postgresql://USER_HERE:***@localhost/DB_HERE?tablename=TABLE_HERE
> 	TARGET COLUMNS
> 	( x,y,z )
> WITH
> 	 fields optionally enclosed by '''
> SET work_mem to '32 MB', maintenance_work_mem to '1024 MB';

But pgloader throw error:

> 2017-12-21T07:38:38.262000Z ERROR Database error 42P01:  "TABLE_HERE"
> QUERY: -- params: table-name
>   select nspname
>     from pg_namespace n
>     join pg_class c on n.oid = c.relnamespace
>    where c.oid = 'TABLE_HERE'::regclass;
> 2017-12-21T07:38:38.267000Z FATAL Failed to prepare target PostgreSQL table.
> 2017-12-21T07:38:38.267000Z FATAL Database error 42P01:  "TABLE_HERE"
> QUERY: -- params: table-name
>   select nspname
>     from pg_namespace n
>     join pg_class c on n.oid = c.relnamespace
>    where c.oid = 'TABLE_HERE'::regclass;
> 2017-12-21T07:38:38.267000Z LOG report summary reset
>        table name       read   imported     errors      total time
> ...

The table actually exists. What can be wrong?
I aslo use [ fields optionally enclosed by ''' ] (single-quote) - is that okay?

**Comment by dimitri** [comment]
Error 42P01 is issued when the table doesn't exists. Maybe a problem with your search_path settings? in which schema is the table to be found?

```
ERROR:  42P01: relation "table_here" does not exist
LINE 4: where c.oid = 'TABLE_HERE'::regclass;
                      ^
```

**Comment by ParadoxFilm** [comment]
Schema is [public] (standard public schema), aslo tablespace is [pg_default]. No changes to the standard configuration.
'TABLE_HERE' I certainly replace the name of my table (in my case it's 'people').

**Comment by ParadoxFilm** [comment]
The error turned out to be the following: the pgoader translated the name of the `People` table into the lower register. After renaming the table in the database itself, the error has disappeared. However, a new one has appeared: now the pgoader translates the table field names to the lower case.
