### ISSUE TITLE
quote identifiers - seems to not work properly in 3.4.1 for load from MySQL to PostgreSQL

### ISSUE THREAD

**Issue by machytkafitanalytics** [dimitri/pgloader#703]
Hello,
I would like to have a question about pgloader version 3.4.1.

Context - we use pgloader for several years to load data every day from MySQL to PostgreSQL. At the beginning MySQL db had ~3GB so things were quick and easy. But now it has ~30GB and it is not so smooth any more, it takes several hours now and I would like to optimize it a bit. But regarding pgloader we have to stay still on version 3.1.1 because newer versions do not work well for us due to problems with "quote identifiers".

I decided to test latest pgloader 3.4.1 with MySQL 5.5.58 as source and PostgreSQL 10.1 as target. But all tests were unsuccessful again - looks like problem is with "camel cases" in column names in COPY part. 

I see in log errors like this one:
2017-12-21T14:51:12.333000Z FATAL Can't init COPY to "aaaaa"."xxxxxxxxxxx" (...list of columns...)
Database error 42703: column "validsizes" of relation "xxxxxxxxxxx" does not exist

And it is true because the name of the column is "validSizes". In table structure in both MySQL and PostgreSQL I see it OK - "validSizes". But looks like COPY part does not take it into consideration - list of columns in error message does not contain any quoted columns.

Could you please look at it? I would really like to upgrade pgloader from 3.1.1....
Many thanks and Merry Christmas and a Happy New Year!

Josef Machytka
Berlin

**Comment by dimitri** [comment]
Hi Josef,

In trying to reproduce the bug here, I found another one related to Camel Case column names and queries. This time with more recent queries sent to MySQL (introduced in 3.4.1).  Please consider building pgloader from fresh sources, your bug shouldn't happen anymore. If it happens, though, please open this issue again.

Also, you should see quite some benefits to migration time, let me know!

**Comment by machytkafitanalytics** [comment]
+1

I had finally time to finish all tests. I tested version `pgloader version "3.4.07cdf3e"` built from sources. Works perfectly event with more workers and higher concurrency. 
Could you please make new release of pgloader with this repair any time soon?
Many thanks.
