### ISSUE TITLE
Progress bar with estimated time

### ISSUE THREAD

**Issue by ParadoxFilm** [dimitri/pgloader#704]
Hello, Dimitri!
How about a progress bar (with an estimated time)?
I often import large data using pgoader (about 20-50GB).
The import takes sometimes several hours. Waiting without knowing the percentage performed is very painful: (
Suddenly the pgoader will generally fall or stop responding?
I already had this after several errors of type `debugger invoked on a SIMPLE-TYPE-ERROR in thread` popped up...(CPU is loaded, however, the pgloader does not end for an extremely long time. ex: #705)
Heard, it can be done with the `pv` command , however, I did not get it (along with using the .load file).

**Comment by dimitri** [comment]
If you use `stdin` as your source file definition, then pgloader reads from standard input. See http://pgloader.readthedocs.io/en/latest/ref/csv.html#csv-source-specification-from

So then you should be able to 

    gunzip -c foo.csv.gz | pv | pgloader load-from-stdin.load

And have a progress bar.

**Comment by ParadoxFilm** [comment]
What if the file is already unpacked (.csv)?
And is not it slowing down a lot? After all, by default the pgloader can read a file in several threads.

**Comment by dimitri** [comment]
What happens when you try?

pgloader doesn't read CSV files from several threads. It would be complex to do that in the general case as we don't know where a line ends or begins before having parsed said line...

**Comment by ParadoxFilm** [comment]
I'm trying this way:
`pv "/path/to/data.csv" | pgloader cmd.load`
However, what is usually done in 20 minutes (files about 7GB), the program now predicts around 1 hour...
It seems that the process has slowed down three-fold. Could this be?
In any case, I'll wait for the end and see.
Thank you!

**Comment by ParadoxFilm** [comment]
UPD: Ended in 30 minutes 58 seconds. Its OK.
One and a half times more than the previous time.
I will continue the experiments, since the data was different.
