### ISSUE TITLE
pgloader socket error in "connect"

### ISSUE THREAD

**Issue by yeedle** [dimitri/pgloader#707]
I am following the instructions [in the docs](http://pgloader.readthedocs.io/en/latest/tutorial/tutorial.html#migrating-from-mysql-to-postgresql) on how to migrate a MySql database.

When running
```
pgloader mysql://root@localhost/f1db pgsql:///f1db
```
I get
```
KABOOM!
FATAL error: Failed to connect to pgsql at :UNIX (port 5432) as user "yeedle": Database error: Socket error in "connect": 2 (No such file or directory)
An unhandled error condition has been signalled:
   Failed to connect to pgsql at :UNIX (port 5432) as user "yeedle": Database error: Socket error in "connect": 2 (No such file or directory)




What I am doing here?

Failed to connect to pgsql at :UNIX (port 5432) as user "yeedle": Database error: Socket error in "connect": 2 (No such file or directory)


Waiting for the monitor thread to complete.
```
Any leads on what the issue might be?

**Comment by dimitri** [comment]
Can you try with psql? It might be that your PostgreSQL isn't listening on a Unix Socket...

    psql postgresql:///f1db

If that works, it might be that your unix socket isn't found in the default location for pgloader. Either try with a full specification of where the socket file is, or with localhost to use TCP/IP rather than Unix sockets:

    pgloader mysql://root@localhost/f1db pgsql://localhost/f1db

**Comment by yeedle** [comment]
Got it! I installed postgres 10 on port 5433 (because 9.6 was running on the default one). D'oh!

**Comment by topetope024** [comment]
how did you install 10 on port 5433?

**Comment by joemsak** [comment]
Had this issue while following along with Ch 5 of the book and the fix for me was to add `localhost`:

`pgloader [http source from book] pgsql://localhost/[dbname]`
