### ISSUE TITLE
Database has large size but no tables after running.

### ISSUE THREAD

**Issue by wayneeseguin** [dimitri/pgloader#710]
Hi @dimitri , I love the idea of this tool and I'm trying it out.

I ran it from a mysql database to a PostgreSQL database and for some reason after running the database has around the correct size (~300M) as shown in \l but there are no tables when I list \dt.

I ran --debug and it was connecting fine and copying rows over and the report at the end showed no errors with the correct number of tables and rows. Yet when I attach to the database there are no tables and no rows... I'm stumped.

The only thing I can think of that's a little unusual is the mysql is from the host itself and PostgreSQL is run inside a docker container.

**Comment by dimitri** [comment]
Which version of pgloader are you using? My guess is that all the tables have been automatically migrated to a PostgreSQL schema that is the name of the MySQL database, and that schema is not in the search path. Please do `\dn` and then issue the following statement.

```sql
alter database pgdb_name set search_path to mysql_dbname, public, $user;
```

This statement takes effect starting from next connection, so disconnect from psql and reconnect, then `\dt` should show you everything. See the pgloader command `alter schema mysql_dbname rename to public` if you want to change the target schema during the migration.

**Comment by wayneeseguin** [comment]
Brilliant, that was it. Thank you for this!

**Comment by wayneeseguin** [comment]
Oh, and version 3.4.1. installed via apt install.
