### ISSUE TITLE
Import subset of rows

### ISSUE THREAD

**Issue by willcodeforfoo** [dimitri/pgloader#712]
Is it possible to only import a subset of rows? My use case is "resuming" an import after some period of time has lapsed. It'd be nice to just import a subset of (e.g., `SELECT * FROM table where id > [last_id_of_previous_import]`). 

Maybe using using a view?

**Comment by dimitri** [comment]
Yeah, if your source is MySQL, use the `MATERIALIZE VIEW` command of pgloader. Otherwise, it's not been implemented yet...
