### ISSUE TITLE
failed to find schema in target catalog

### ISSUE THREAD

**Issue by richardji7** [dimitri/pgloader#713]
Hi,

I am migrating two MySQL databases to PostgreSQL.  On MySQL there are gitlab_ci_production and gitlabhq_production.  On PostgreSQL I created two target databases, gitlab_ci_test and gitlab_test respectively.

The gitlabhq_production to gitlab_test ran successfully with the following load file:

```
LOAD DATABASE
     FROM mysql://user:pwd@###.17.119.201/gitlabhq_production
     INTO postgresql://gitlab_app_test:pwd@###.17.119.201/gitlab_test

WITH include no drop, truncate, disable triggers, create no tables,
     create no indexes, preserve index names, no foreign keys,
     data only, workers = 8, concurrency = 1,
     multiple readers per thread, rows per range = 5000

;
```

The gitlab_ci_production to gitlab_ci_test failed with the following error and load file.

```
gitlab-conversion:~/git/pgloader/build/bin # ./pgloader ~/gitlabci.load 
2018-01-10T15:34:34.101000-05:00 LOG Migrating from #<MYSQL-CONNECTION mysql://rji@###.17.119.201:3306/gitlab_ci_production {1005E8C6E3}>
2018-01-10T15:34:34.105000-05:00 LOG Migrating into #<PGSQL-CONNECTION pgsql://gitlab_app_test@###.17.119.201:5432/gitlab_ci_test {1005E8E463}>
KABOOM!
FATAL error: pgloader failed to find schema "gitlab_ci_production" in target catalog
An unhandled error condition has been signalled:
   pgloader failed to find schema "gitlab_ci_production" in target catalog


LOAD DATABASE
     FROM mysql://user:pwd@###.17.119.201/gitlab_ci_production
     INTO postgresql://gitlab_app_test:pwd@###.17.119.201/gitlab_ci_test

WITH include no drop, truncate, disable triggers, create no tables,
     create no indexes, preserve index names, no foreign keys,
     data only, workers = 8, concurrency = 1,
     multiple readers per thread, rows per range = 5000

;
```

The database and schema exists in PostgreSQL.

```
gitlab_ci_test=> \list
                                               List of databases
      Name      |      Owner      | Encoding |   Collate   |    Ctype    |          Access privileges          
----------------+-----------------+----------+-------------+-------------+-------------------------------------
 gitlab_ci_test | gitlab_app_test | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =Tc/gitlab_app_test                +
                |                 |          |             |             | gitlab_app_test=CTc/gitlab_app_test
 gitlab_test    | gitlab_app_test | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =Tc/gitlab_app_test                +
                |                 |          |             |             | gitlab_app_test=CTc/gitlab_app_test
 postgres       | postgres        | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 template0      | postgres        | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres                        +
                |                 |          |             |             | postgres=CTc/postgres
 template1      | postgres        | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres                        +
                |                 |          |             |             | postgres=CTc/postgres
(5 rows)

gitlab_ci_test=> \c gitlab_ci_test
You are now connected to database "gitlab_ci_test" as user "gitlab_app_test".
gitlab_ci_test=> \dn
            List of schemas
         Name         |      Owner      
----------------------+-----------------
 gitlab_ci_production | gitlab_app_test
 public               | postgres
(2 rows)
```

So what am I missing?  Why the first one ran without error but the second one won't work?

Thanks in advance for your help.

**Comment by richardji7** [comment]
Any suggestions are appreciated.  I am hitting a wall on this.

**Comment by richardji7** [comment]
Here is more info on the PostgreSQL side.

postgres@gitlab-conversion:~> psql -U gitlab_app_test -d gitlab_ci_test
Password for user gitlab_app_test: 
psql (9.6.3)
Type "help" for help.

gitlab_ci_test=> select current_schema;
    current_schema    
----------------------
 gitlab_ci_production
(1 row)

gitlab_ci_test=> show search_path ;
     search_path      
----------------------
 gitlab_ci_production
(1 row)

gitlab_ci_test=> \dt
                           List of relations
        Schema        |         Name          | Type  |      Owner      
----------------------+-----------------------+-------+-----------------
 gitlab_ci_production | rji_dummy_dont_delete | table | gitlab_app_test
(1 row)

**Comment by dimitri** [comment]
It looks strange. Often enough in that kind of case, we're not looking at the right place. Is it possible that there would be something strange with the connection strings, and as a result you would be connected to another database server than the one you think you are targeting?

**Comment by kirill-andr** [comment]
@richardji7 
pgloader is clearly stating that you have an issue in:
```
pgloader failed to find schema "gitlab_ci_production" in target catalog
```
The only place where I see schema gitlab_ci_production is in your MySQL source DB. So why are you posting all of your Postgres schema and tables when the issue is clearly on the MySQL side?

@dimitri 
I think this is also the issue I am experiencing with the latest build:
https://github.com/dimitri/pgloader/issues/679#issuecomment-360087997

I am trying to figure out if this can be reproduced on some MySQL test DB, but have you tried this build with a MySQL database where a non-public schema needs to be migrated?

**Comment by richardji7** [comment]
@kirill-andr Because it says it can't find in the "target" catalog, not source catalog.  On MySQL, I did a show databases and it is clearly there.  The issue is resolved BTW.  As @dimitri suggested, it was something else entirely.  If I turn on debug I can see the SQL it is running on PostgreSQL.  The select statement is actually looking for not only the schema but also the objects.  And if that returns 0 rows, this error is shown.  kind of misleading message.  So I started tinkering with the "WITH" section and eventually got it working.

**Comment by dimitri** [comment]
@richardji7 Oh I understand better your situation now. Will see what I can do on that front, thanks!

**Comment by KaKi87** [comment]
@richardji7

Could you tell us how exactly did you *tinkered* your `WITH` statement ?

I'm experiencing the same issue, for the same GitLab migration.

Thanks

**Comment by richardji7** [comment]
Here is the two .load files I end up using.  See the WITH section for each of them.

gitlab-conversion:~ # cat gitlabhq.load
LOAD DATABASE
     FROM mysql://rji:rji123@172.17.119.201/gitlabhq_production
     INTO postgresql://gitlab_app_test:G1t2017@172.17.119.201/gitlab_test

WITH include no drop, truncate, disable triggers, create no tables,
     create no indexes, preserve index names, no foreign keys,
     data only, workers = 8, concurrency = 1,
     multiple readers per thread, rows per range = 5000

;
gitlab-conversion:~ # cat gitlabci.load
LOAD DATABASE
     FROM mysql://rji:rji123@172.17.119.201/gitlab_ci_production
     INTO postgresql://gitlab_app_test:G1t2017@172.17.119.201/gitlab_test

WITH include no drop, truncate, disable triggers,
     preserve index names, no foreign keys,
     workers = 8, concurrency = 1,
     multiple readers per thread, rows per range = 5000

;

**Comment by richardji7** [comment]
Here are the .load files.  See the WITH sections I end up using.

gitlab-conversion:~ # cat gitlabhq.load
LOAD DATABASE
     FROM mysql://rji:#####@172.17.119.201/gitlabhq_production
     INTO postgresql://gitlab_app_test:#####@172.17.119.201/gitlab_test

WITH include no drop, truncate, disable triggers, create no tables,
     create no indexes, preserve index names, no foreign keys,
     data only, workers = 8, concurrency = 1,
     multiple readers per thread, rows per range = 5000

;
gitlab-conversion:~ # cat gitlabci.load
LOAD DATABASE
     FROM mysql://rji:#####@172.17.119.201/gitlab_ci_production
     INTO postgresql://gitlab_app_test:#####@172.17.119.201/gitlab_test

WITH include no drop, truncate, disable triggers,
     preserve index names, no foreign keys,
     workers = 8, concurrency = 1,
     multiple readers per thread, rows per range = 5000

;
