### ISSUE TITLE
The symbol "*SYSTEM-DEFINITION-SEARCH-FUNCTIONS*" is not external in the ASDF/FIND-SYSTEM package.

### ISSUE THREAD

**Issue by ilovezfs** [dimitri/pgloader#714]
```
==> make pgloader-standalone BUILDAPP=buildapp
buildapp    --require sb-posix --require sb-bsd-sockets --require sb-rotate-byte                        \
                       --sbcl sbcl                            \
                       --load-system pgloader               \
                       --load src/hooks.lisp                   \
                       --entry pgloader:main                   \
                       --dynamic-space-size 4096         \
                       --compress-core                    \
                       --output build/bin/pgloader
Fatal INPUT-ERROR-IN-LOAD:
  READ error during LOAD:

    The symbol "*SYSTEM-DEFINITION-SEARCH-FUNCTIONS*" is not external in the ASDF/FIND-SYSTEM package.

      Line: 17, Column: 90, File-Position: 2099

      Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /private/tmp/pgloader-20180115-20756-gpt4az/dumper-2SKVI5f7.lisp" {1001970573}>
make: *** [pgloader-standalone] Error 1
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/python.rb
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: make pgloader-standalone BUILDAPP=buildapp
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 5
When you exit this shell, you will return to the menu.
```
This occurs with sbcl 1.4.3 and 1.4.2 but not 1.4.1

**Comment by antoaravinth** [comment]
Same issue, any fix for this?

**Comment by dimitri** [comment]
I can't reproduce here. How are you building pgloader? I can guess that you're using brew here, and I'm not maintaining the package. Can you try building from source instead and see if that works, so that we know if that's a brew packaging problem to fix, or something in pgloader itself?

```
$ ./build/bin/pgloader --version
pgloader version "3.4.5ecd03c"
compiled with SBCL 1.4.2
```

**Comment by ilovezfs** [comment]
@dimitri yes brew. It looks like the problem is specific to `make pgloader-standalone BUILDAPP=buildapp`. I assume you're using `make pgloader`, which works fine. Outside of brew,
```
iMac-TMP:pgloader joe$ make pgloader-standalone BUILDAPP=buildapp
buildapp    --require sb-posix --require sb-bsd-sockets --require sb-rotate-byte                        \
                       --sbcl sbcl                            \
                       --load-system pgloader               \
                       --load src/hooks.lisp                   \
                       --entry pgloader:main                   \
                       --dynamic-space-size 4096         \
                       --compress-core                    \
                       --output build/bin/pgloader
Fatal INPUT-ERROR-IN-LOAD:
  READ error during LOAD:

    The symbol "*SYSTEM-DEFINITION-SEARCH-FUNCTIONS*" is not external in the ASDF/FIND-SYSTEM package.

      Line: 17, Column: 90, File-Position: 2099

      Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /Users/joe/pgloader/pgloader/dumper-2SKVI5f7.lisp" {1001970513}>
make: *** [pgloader-standalone] Error 1
```

**Comment by Ajaxy** [comment]
Same problem here.

> This occurs with sbcl 1.4.3 and 1.4.2 but not 1.4.1

Not sure what's "sbcl", is there anything that I can tweak or change to install it on my Mac?

**Comment by jaredcwhite** [comment]
Same problem here — `brew install --HEAD pgloader` doesn't work, throws this error.

**Comment by dimitri** [comment]
As I don't maintain the brew formula, can you try installing from sources? git clone and make should be all you need really.

**Comment by ilovezfs** [comment]
@dimitri As I said above, this problem is not specific to Homebrew and is easily reproducible outside of Homebrew: https://github.com/dimitri/pgloader/issues/714#issuecomment-361079821

**Comment by ilovezfs** [comment]
@benesch I see you originally added the `make pgloader-standalone BUILDAPP=buildapp`  make target in https://github.com/dimitri/pgloader/pull/45. Would you be willing to take a look at fixing this issue?

**Comment by benesch** [comment]
Well I'm thoroughly confused about what exactly went wrong, but I have a fix, at least:

```
brew uninstall buildapp
brew install buildapp --build-from-source
```

Looks like buildapp needs to be recompiled for the new SBCL/ASDF. Opened https://github.com/Homebrew/homebrew-core/pull/24183 to address.

**Comment by jaredcwhite** [comment]
@benesch I went through your steps and now I'm getting this error:

```
Last 15 lines from /Users/jwhite/Library/Logs/Homebrew/pgloader/01.make:
  Circular dependency:
     ((#<ASDF/LISP-ACTION:LOAD-OP > . #<ASDF/SYSTEM:SYSTEM "simple-date">)
      (#<ASDF/LISP-ACTION:LOAD-OP >
       . #<ASDF/SYSTEM:SYSTEM "simple-date-postgres-glue">)
      (#<ASDF/LISP-ACTION:LOAD-OP >
       . #<ASDF/COMPONENT:MODULE "simple-date-postgres-glue" "simple-date">)
      (#<ASDF/LISP-ACTION:LOAD-OP >
       . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "simple-date-postgres-glue" "simple-date" "cl-postgres-glue">)
      (#<ASDF/LISP-ACTION:PREPARE-OP >
       . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "simple-date-postgres-glue" "simple-date" "cl-postgres-glue">)
      (#<ASDF/LISP-ACTION:PREPARE-OP >
       . #<ASDF/COMPONENT:MODULE "simple-date-postgres-glue" "simple-date">)
      (#<ASDF/LISP-ACTION:PREPARE-OP >
       . #<ASDF/SYSTEM:SYSTEM "simple-date-postgres-glue">))
make: *** [pgloader-standalone] Error 1
```

Do I need to wait until https://github.com/Homebrew/homebrew-core/pull/24183 is merged into HomeBrew before I'll be able to install pgloader?

**Comment by benesch** [comment]
> Do I need to wait until Homebrew/homebrew-core#24183 is merged into HomeBrew before I'll be able to install pgloader?

Precisely. You can apply the diff manually in the meantime (e.g., via `brew edit pgloader` or by checking out my branch in `$(brew --repo homebrew/homebrew-core)`).

**Comment by ilovezfs** [comment]
I have now shipped https://github.com/Homebrew/homebrew-core/pull/24183 so this should be fixed. Awesome work, @benesch, and thank you for the help!

**Comment by jaredcwhite** [comment]
I wasn't able to do a build again using --HEAD...kept getting a cryptic "Error: No such file or directory - pgloader.1" message. But just running brew install pgloader does seem to have done the trick and I have 3.4.1 installed now. Thanks!

**Comment by benesch** [comment]
@jaredcwhite should be fixed by https://github.com/Homebrew/homebrew-core/pull/24800.
