### ISSUE TITLE
CCL build: -S means stack-size

### ISSUE THREAD

**Issue by reist** [dimitri/pgloader#719]
For some reason, building pgloader using ccl causes -S to not work properly.

> $ pgloader -S fubar
> couldn't parse -S/--stack-size argument fubar
> $ pgloader -S
> error in program arguments                            
> usage: pgloader <options>                                  
>          where <options> are one or more of:                           
>         -R, --heap-reserve <n>: reserve <n> (default: 549755813888)                                        
>                  bytes for heap expansion                                                                        
>         -S, --stack-size <n>: set  size of initial thread's control stack to <n>
>         -Z, --thread-stack-size <n>: set default size of first (listener)  thread's stacks based on <n>
>         -b, --batch: exit when EOF on *STANDARD-INPUT*
>         --no-sigtrap : obscure option for running under GDB
>         --debug : try to ensure that kernel debugger uses a TTY for I/O
>         --avx :signal handlers preserve AVX(YMM) registers on x8664 Linux.  This the default on Linux >=3.0
>         --no-avx :signal handler don't preserve AVX(YMM) registers on x8664 Linux, This the default on Linux <3.0
>         -I, --image-name <image-name>                       
>          and <image-name> defaults to pgloader.image
>                                      
>         Any arguments following the pseudoargument "--" are    
>         not processed and are available to the application as                 
>         the value of CCL:*UNPROCESSED-COMMAND-LINE-ARGUMENTS* .

**Comment by dimitri** [comment]
The CCL kernel preempts some command line options for itself. Please use long names in your command line switches?

**Comment by reist** [comment]
I'm good with that, thanks. Is it possible to add something about what the CCL kernel does to the docs?
