### ISSUE TITLE
simplest way to import XML files

### ISSUE THREAD

**Issue by ppKrauss** [dimitri/pgloader#722]
There are a easy way to import/export XML files with pgloader?
* that solve the problem of "load as multiple lines"
* that solve the problem when save back the XML file in the file system, without changes in the SHA1.

 
------
## Examples

The folowing examples show each problem and a non-elegant workaround.

```sql
drop table ttmp;
CREATE TABLE ttmp (x text);
COPY ttmp FROM '/tmp/test.xml' ( FORMAT text ); -- breaking lines lines
COPY (SELECT x FROM ttmp) TO '/tmp/test_back.xml' (format TEXT);
```
Check:
```
sha1sum /tmp/test*.*
  570b13fb01d38e04ebf7ac1f73dfad0e1d02b027  /tmp/test_back.xml
  570b13fb01d38e04ebf7ac1f73dfad0e1d02b027  /tmp/test.xml
```
Use it to store XML:
```sql
drop table xtmp;
CREATE TABLE xtmp (x xml);
INSERT INTO  xtmp (x) 
  SELECT array_to_string(array_agg(x),E'\n')::xml FROM ttmp
;
COPY (select x::text from xtmp) FROM '/tmp/test_back2.xml' ( FORMAT text );
```
... But not works as we can check by `sha1sum /tmp/test*.*`, not produce the same result: `570473ee12797783114f798dc5ce1c36de4d2ea0  /tmp/lix_back2.xml`

The cause perhaps is only because `\n` is not espaped.
... Trying to solving:

```sql
COPY (select y  from xtmp, lateral regexp_split_to_table(x::text,E'\n') t(y) ) 
TO '/tmp/test_back2.xml' ( FORMAT text );
```
... no... trying more .... No: **so complex for a so simple problem.**

**Comment by dimitri** [comment]
Why would you load XML file on a per-line basis anyway? Other solutions exists that will consider the file as XML formatted, see e.g. http://tapoueh.org/blog/2009/02/importing-xml-content-from-file/.
