### ISSUE TITLE
ERROR Could not read input: The bounding indices 20 and 19 are bad for a sequence of length 19

### ISSUE THREAD

**Issue by marielcherkassky** [dimitri/pgloader#726]
Hi Dimitry,
In continue to the last errors that I had now I'm getting a run time error from pg_loader.

```
2018-01-22T05:21:16.585000-05:00 ERROR Error while formating a row from "radius.radius_log_temp":
:
                                                       "start_date" "end_date"
                                                       "calling_number"
                                                       "called_number" "nas_ip"
                                                       "nas_type" "nas_port"
                                                       "start_stop"
                                                       "serverend_point"
                                                       "clientend_point"
                                                       "server_auth_id"
                                                       "client_auth_id"
                                                       "rb_content_name"
                                                       "acct_input_octets"
                                                       "acct_output_octets"
                                                       "speed"
                                                       "terminate_cause"
                                                       "acct_session_time"
                                                       "event_timestamp"
                                                       "acct_authentic"
                                                       "acct_delay_time"
                                                       "acct_input_packets"
                                                       "acct_output_packets"
                                                       "framed_protocol"
                                                       "service_type" "id_no"
                                                       "term_code")
2018-01-22T05:21:16.585000-05:00 ERROR Could not read input: The bounding indices 20 and 19 are bad for a sequence of length 19.
See also:
  The ANSI Standard, Glossary entry for "bounding index designator"
  The ANSI Standard, writeup for Issue SUBSEQ-OUT-OF-BOUNDS:IS-AN-ERROR
2018-01-22T05:21:16.585000-05:00 ERROR Error while formating a row from "radius.radius_log_temp":
2018-01-22T05:21:16.586000-05:00 ERROR The value
  NIL
is not of type SIMPLE-ARRAY
```

```
pgloader --version
pgloader version "3.4.1"
compiled with SBCL 1.3.11-1.el7
```

Any idea if that is a problem with the configuration of the parameters file or something internal?

**Comment by dimitri** [comment]
To be able to help you I need more information, such as an example data file, the load file, the target table definition. A self-contained example would be best, see how to create one by having a look at the many that exist in the https://github.com/dimitri/pgloader/tree/master/test directory. Then, before I consider fixing bugs, you need to try with current version of pgloader, that is build from fresh sources --- I only fix bugs in the master's branch anyway, so you will have to build from sources to get a bug fix.

**Comment by marielcherkassky** [comment]
Hi dimitry,
I'm attaching the next files : example data file, the load file, and the target table definition. I used those examples and they look like the load file that I attached.
[Load_FILE.txt](https://github.com/dimitri/pgloader/files/1651888/Load_FILE.txt)
[table defenition.txt](https://github.com/dimitri/pgloader/files/1651889/table.defenition.txt)
[radiuslog.txt](https://github.com/dimitri/pgloader/files/1651890/radiuslog.txt)

**Comment by dimitri** [comment]
The table definition I want is for me to be able to **reproduce** the issue you are experiencing. The output of *psql* is not helpful. Please think about what you would need if you were in my shoes. Provide the SQL script that creates the table!

Also, please provide a self-contained test case, which means all in a single file, as you can see in the pgloader tests.

**Comment by marielcherkassky** [comment]
Hi,
I attached a zip that contains all the files.  
[test.zip](https://github.com/dimitri/pgloader/files/1652488/test.zip)

Thank you Dimitry, regards , Mariel.

**Comment by marielcherkassky** [comment]
Hi Dimitri,
Does the zip file satisfied you as a self contained test case ? If there any problem please tell me and I will try to provide you all the info that I got regarding the error..

**Comment by marielcherkassky** [comment]
Hi,
I installed the lastest version of pgloader 3.4.2 .
I used the same file but got the same error : 
2018-01-25T12:11:08.207000+02:00 ERROR Could not read input: The bounding indices 20 and 19 are bad for a sequence of length 19.
See also:
  The ANSI Standard, Glossary entry for "bounding index designator"
  The ANSI Standard, writeup for Issue SUBSEQ-OUT-OF-BOUNDS:IS-AN-ERROR
2018-01-25T12:11:08.207000+02:00 ERROR Error while formating a row from "radius.radius_log_temp":
2018-01-25T12:11:08.207000+02:00 ERROR The value
  NIL
is not of type
  SIMPLE-ARRAY
when binding PGLOADER.PGSQL::ROW

**Comment by dimitri** [comment]
Sorry about the error `The value NIL is not of type SIMPLE-ARRAY`, I think it's a mistake I introduced quite recently, and it should be fixed now.

Here's the error message I have when I try your test case though:

```
2018-01-25T23:48:44.096091+01:00 ERROR Could not read input: Bad interval for sequence operation on "18-01-2018 19:14:33" : start = 20, end = 19
2018-01-25T23:48:44.096599+01:00 ERROR Could not read input: Bad interval for sequence operation on "06-01-2018 23:14:32" : start = 20, end = 19
2018-01-25T23:48:44.097216+01:00 ERROR Could not read input: Bad interval for sequence operation on "11-01-2018 01:14:34" : start = 20, end = 19
```

It makes it pretty clear that your date format isn't aligned with which of your data set. I fixed it for you and using the following expression I could load your sample file:

```
                start_date [ date format 'DD-MM-YYYY HH24:MI:SS' ],
                end_date   [ date format 'DD-MM-YYYY HH24:MI:SS' ],
```

And now:

```
             table name     errors       rows      bytes      total time
-----------------------  ---------  ---------  ---------  --------------
                  fetch          0          0                     0.000s
            before load          0          2                     0.023s
-----------------------  ---------  ---------  ---------  --------------
        "public"."t726"          0          3     0.9 kB          0.018s
-----------------------  ---------  ---------  ---------  --------------
        Files Processed          0          1                     0.000s
COPY Threads Completion          0          2                     0.018s
-----------------------  ---------  ---------  ---------  --------------
      Total import time          ✓          3     0.9 kB          0.018s
```
