### ISSUE TITLE
drop indexes not working?

### ISSUE THREAD

**Issue by tendres** [dimitri/pgloader#727]
I am having an issue where the option to 'drop indexes' appears to not be working in my loader script.
The end of my script includes an AFTER LOAD DO statement to create an index but the script complains the index already exists.
Is there a naming convention that needs to be adhered to?
With Postgres 9.6x and using `tablename_field_name_idx` naming convention with different index flavors.

**Comment by dimitri** [comment]
Please consider reading the documentation, now available at http://pgloader.readthedocs.io/en/latest/ref/mysql.html#mysql-database-migration-options-with

  - drop indexes

    When this option is listed, pgloader drops the indexes in the target database before loading the data, and creates them again at the end of the data copy.

**Comment by tendres** [comment]
Thank you!
Missed that somehow.
