### ISSUE TITLE
RPM package broken - not sure who owns?

### ISSUE THREAD

**Issue by snhirsch** [dimitri/pgloader#728]
The rpm for Centos 7 is trying to dlopen /usr/lib64/libssl.so.1.0.1e, but the current version of that library is actually libssl.so.1.0.2k.  A symlink fixed the problem, but the bigger issue is that dlopen should probably be looking for 'libssl.so.1' instead of a particular subversion.

**Comment by dimitri** [comment]
Currently the RH packaging is owned by Devrim at https://yum.postgresql.org ; please open an issue / ticket / report there. Thanks for reporting though.

**Comment by snhirsch** [comment]
Unfortunately, I see no reference to this package at postgresql.org nor any means of opening a ticket.

**Comment by devrimgunduz** [comment]
Hi @snhirsch ,

Next time, you can create a ticket at https://redmine.postgresql.org/projects/pgrpms/issues/new , and you need a community account there.

That said, I fixed the issue. The new packages will sync in an hour.

Thanks for the report.

Regards, Devrim
