### ISSUE TITLE
WITH parameters are not recognized.

### ISSUE THREAD

**Issue by kirill-andr** [dimitri/pgloader#729]
I am running 
pgloader version "3.2.2"
compiled with SBCL 1.3.1.debian

And it seems that some parameter are not working or recognized. I have looked at the documentation:
http://pgloader.readthedocs.io/en/latest/ref/mysql.html

and SET PostgreSQL PARAMETERS as well as SET MySQL PARAMETERS as per example are throwing an identical error to the bellow.

```
An unhandled error condition has been signalled: At

  
  WITH include no drop, truncate, create no tables, no foreign keys, data only, rows per range = 5000
  
                                                                                ^ (Line 5, Column 78, Position 237)

In context ANOTHER-MYSQL-OPTION:

While parsing ANOTHER-MYSQL-OPTION. Expected:
```

**Comment by dimitri** [comment]
You need to upgrade to either 3.4.1 or build from sources to use those parameters. 3.2.2 is pretty old now.
