### ISSUE TITLE
Permission denied on `/tmp/pgloader/pgloader.log`

### ISSUE THREAD

**Issue by ChitHnin** [dimitri/pgloader#730]
I am getting the following error when trying to export from mysql9.6  to postgresql with pgloader `pgloader --debug mysql://root:123@localhost/test postgres:///testpsql`

```
postgres@arai-test:/home/chit$ pgloader --debug mysql://root:123@localhost/test postgres:///testpsql
sb-impl::*default-external-format* :ISO-8859-1
tmpdir: #P"/tmp/pgloader/"

debugger invoked on a SB-INT:SIMPLE-FILE-ERROR in thread
#<THREAD "lparallel" RUNNING {100975FE43}>:
  error opening #P"/tmp/pgloader/pgloader.log": Permission denied
```

**Comment by dimitri** [comment]
You just have a permission error, which is more nicely handled and output in more recent version of pgloader. It looks like the fact that's Common-Lisp isn't the usual drives people away from even trying to understand what's happening?

```
error opening #P"/tmp/pgloader/pgloader.log": Permission denied
```

**Comment by ooobii** [comment]
I know this report is rather old, but I'm having the same issue. I'm utilizing pgloader in a script where the log is needed to be read from to verify the file deposit was as expected, and to be able to report success. 
I already have the permissions on the `/tmp` directory set to read-write for all (system default):
```
$ ls -la / | grep tmp
drwxrwxrwt  13 root    root     4096 Sep 17 02:09 tmp
```

**Comment by topetope024** [comment]
I still don't get it, how to make it persmission accepted/succesfully?

**Comment by topetope024** [comment]
> I know this report is rather old, but I'm having the same issue. I'm utilizing pgloader in a script where the log is needed to be read from to verify the file deposit was as expected, and to be able to report success.
> I already have the permissions on the `/tmp` directory set to read-write for all (system default):
> 
> ```
> $ ls -la / | grep tmp
> drwxrwxrwt  13 root    root     4096 Sep 17 02:09 tmp
> ```

i tried to run this and the same outcome, just the roots is 3. Now i don't know what happened. so what is that for?
