### ISSUE TITLE
Primary Key names are not preserved

### ISSUE THREAD

**Issue by vrtareg** [dimitri/pgloader#731]
I am trying to manipulate settings to preserve index names using the `preserve index names` option from http://pgloader.readthedocs.io/en/latest/ref/mysql.html?highlight=preserve%20index%20names

So far most of the stuff is ok but primary keys are getting wrong names.

Support ticket from Atlassian:

> Hi Areg, 
> It seems that the prefix issue needs to be addressed on the constraint and primary key creation as well. As you can see in the following that the constraint supposed to be "\<table name\>pkey" while the generated constraint is named to "idex\<number\>_PRIMARY":
>
> - 	Original: 
> - 	ALTER TABLE ONLY "EVENTS"
> - 	    ADD CONSTRAINT "EVENTS_pkey" PRIMARY KEY (rev, history);
> - 	Generated: 
>
> - 	ALTER TABLE ONLY "EVENTS"
> - 	    ADD CONSTRAINT "idx_10419938_PRIMARY" PRIMARY KEY (rev, history);
>
> This is affecting all existing tables. 
> Best regards, 
> Atlassian EMEA Premier Support

Please let me know if you need any debug information.

Regards,
Areg

**Comment by vrtareg** [comment]
I think it has following the rule:

> Even when using the option preserve index names, MySQL primary key indexes named “PRIMARY” will get their names uniquified. Failing to do so would prevent the primary keys to be created again in PostgreSQL where the index names must be unique per schema.

Is it possible to somehow overwrite this?
Otherwise I will need to create custom script for this which I would like to avoid.

Regards,
Areg

**Comment by dimitri** [comment]
Can you paste here a list of table names and associated primary key index name that you want to preserve from your current MySQL schema, please?

**Comment by vrtareg** [comment]
Hi

I don't think that MySQL has primary key name.
It is PostgreSQL feature.

I will use translation script to fix that as Jira has one format and Confluence another.

Never mind.

Regards,
Areg

**Comment by dimitri** [comment]
I don't understand what you're asking for then. I though you wanted an option for pgloader to name the primary keys using the same name as in MySQL, but now you say that they don't have a name in MySQL. So what would you like pgloader to do?

**Comment by vrtareg** [comment]
Sorry that I wasn't clear. 
I have tried to export MySQL schema but was not able to see any names on primary keys except something like `PRIMARY KEY('ID')`

Also there is a mix up in names for Confluence and Jira tables primary keys.

Like for any `AO_*` table name is `TABLENAME_pkey`

For Jira other tables it is `pk_TABLENAME`

For Confluence other tables it is as AO tables `TABLENAME_pkey` format.

So now I am using SQL export for Confluence for fix like
```
SELECT FORMAT('ALTER INDEX "%s" RENAME TO "%s_pkey";', constraint_name, table_name) as pk_rename FROM information_schema.table_constraints WHERE UPPER(constraint_type) = 'PRIMARY KEY' ORDER BY table_name
```

And for Jira 
```
select pk_rename from ( SELECT table_name, FORMAT('ALTER INDEX IF EXISTS "%s" RENAME TO "%s_pkey";', constraint_name, table_name) as pk_rename FROM information_schema.table_constraints WHERE UPPER(constraint_type) = 'PRIMARY KEY' AND table_name like 'AO_%' UNION SELECT table_name, FORMAT('ALTER INDEX IF EXISTS "%s" RENAME TO "pk_%s";', constraint_name, table_name) as pk_rename FROM information_schema.table_constraints WHERE UPPER(constraint_type) = 'PRIMARY KEY' AND table_name not like 'AO_%' ) as pkeys ORDER BY table_name;
```

Not sure how to implement this in pgloader post script.

**Comment by dimitri** [comment]
Either use `AFTER LOAD DO` or `AFTER LOAD EXECUTE`, or just script around the pgloader run?

**Comment by vrtareg** [comment]
I did a last one.
Sorry for troubles.

**Comment by bounav** [comment]
Hello,

I'm trying to rename the primary keys `AFTER LOAD` and came up with the following:

I added `AFTER LOAD EXECUTE rename_pk.sql` to my _load_ file:

```
LOAD DATABASE
     FROM      mysql://user:pwd@192.168.1.10/dbName
     INTO postgresql://postgres:password@192.168.1.10:5432/dbName

 WITH include drop, create tables, create indexes, preserve index names, foreign keys, quote identifiers, reset sequences,
      workers = 8, concurrency = 1,
      multiple readers per thread, rows per range = 50000

ALTER SCHEMA 'dbName' RENAME TO 'public'

  SET PostgreSQL PARAMETERS
      maintenance_work_mem to '128MB',
      work_mem to '12MB'

  SET MySQL PARAMETERS
      net_read_timeout  = '120',
      net_write_timeout = '120'

AFTER LOAD EXECUTE rename_pk.sql;
```

The content of  `rename_pk.sql` is inspired from the response from @vrtareg above that I turned into a piece of _dynamic sql_.

```sql
DO $$

DECLARE

pk_rename text;

BEGIN

FOR pk_rename IN (
    SELECT FORMAT('ALTER INDEX IF EXISTS "%s" RENAME TO "pk_%s";', constraint_name, table_name)
    FROM information_schema.table_constraints
    WHERE UPPER(constraint_type) = 'PRIMARY KEY'
    AND constraint_name NOT LIKE('pk_%')
    ORDER BY table_name
) LOOP
    EXECUTE pk_rename;
END LOOP;

END;
$$
```

Running `psql -U postgress -h 192.168.1.10 < rename_pk.sql` runs fine and renames my primary keys after asking for the password.

When I run `pgloader dbName.load` however, it generates an error:

```
▶ pgloader ./dbName.load
2020-07-01T13:50:34.008000+01:00 LOG pgloader version "3.6.2"
KABOOM!
FATAL error: end of file on #<SB-IMPL::STRING-INPUT-STREAM {1005CD22B3}>
An unhandled error condition has been signalled:
   end of file on #<SB-IMPL::STRING-INPUT-STREAM {1005CD22B3}>

What I am doing here?

end of file on #<SB-IMPL::STRING-INPUT-STREAM {1005CD22B3}>
~                                                                                                                                                                                        ⍉
▶ 
```

According to [this issue](https://github.com/dimitri/pgloader/issues/1085) it's a problem in `rename_pk.sql` file... but I 'm confused because the SQL file executes fine on its own.

Could it be because I'm trying to run some _dynamic_ SQL?

**Comment by dimitri** [comment]
I don't think pgloader knows how to parse DO commands in a sql file, indeed. You can contribute that feature, or maybe just use a script that first runs pgloader and then your dynamic SQL command?

**Comment by estan** [comment]
A word of caution about the SQL snippet in https://github.com/dimitri/pgloader/issues/731#issuecomment-652407163 , I believe that may also rename indices in the `pg_catalog` schema which is not intended. The `SELECT` should probably have a `AND constraint_schema = '<name of your schema>'` condition.
