### ISSUE TITLE
Connection String issues when building with CCL

### ISSUE THREAD

**Issue by leezu** [dimitri/pgloader#734]
The SBCL build of pgloader happily accepts the following connection string: `build/bin/pgloader mysql://yelp:yelp@localhost/yelp_db postgresql://yelp@localhost/yelp_db`

However, when building with CCL, this fails with `Failed to connect to mysql at "localhost" (port 3306) as user "yelp": Error #<USOCKET:CONNECTION-REFUSED-ERROR #x30200123389D>`.

Things work when changing the connection string to `build/bin/pgloader mysql://yelp:yelp@127.0.0.1/yelp_db postgresql://yelp@localhost/yelp_db`.

I'm not sure why this problem occurs, but I believe CCL and SBCL compilations should behave the same. Please let me know if I could help with any further details. I'm running the latest code from master as well as 

```
$  mysql --version
mysql  Ver 15.1 Distrib 10.1.29-MariaDB, for Linux (x86_64) using readline 7.0
$  psql --version
psql (PostgreSQL) 10.1
```

**Comment by dimitri** [comment]
Hi, yes this should be solved. I'm giving it the label Corner Case though, and will see if I can fix that before the next release, which should happen soon, it's time! It might be that I'll see about this bug only after the next release, because you have an easy turnaround here.

**Comment by leezu** [comment]
Thanks!

Btw, once this issue is solved, I would be happy to hear why with CL
such radically different behaviour can occur depending on the compiler
used. It seems unintuitive to me currently.
