### ISSUE TITLE
Can't connect to database when running from docker.

### ISSUE THREAD

**Issue by timuckun** [dimitri/pgloader#736]
```bash
$docker run --rm --name pgloader --net=host dimitri/pgloader:latest pgloader mysql://root:abc123@localhost/vc postgresql://tim@127.0.0.1/vc
WARNING:
Couldn't re-execute SBCL with proper personality flags (/proc isn't mounted? setuid?)
Trying to continue anyway.
KABOOM!
FATAL error: Failed to connect to pgsql at "127.0.0.1" (port 5432) as user "tim": Database error: Socket error in "connect": ECONNREFUSED (Connection refused)
An unhandled error condition has been signalled:
   Failed to connect to pgsql at "127.0.0.1" (port 5432) as user "tim": Database error: Socket error in "connect": ECONNREFUSED (Connection refused)




What I am doing here?

Failed to connect to pgsql at "127.0.0.1" (port 5432) as user "tim": Database error: Socket error in "connect": ECONNREFUSED (Connection refused)

psql -U tim -h 127.0.0.1
psql (10.1, server 10.0)
Type "help" for help.

postgres=# \q
```

I tried it without net=host and that too failed.

How can I run this from a docker container and have to be able to connect to my databases?

**Comment by dimitri** [comment]
That's a docker networking setup problem, you need to make it so that your container is able to connect to your PostgreSQL database somehow. I'm not fluent enough with docker and tools to help you there, sorry.

**Comment by mliebelt** [comment]
@timuckun Try to do something similar (converting from Sqlite3 to Postgresql), and am stuck here as well. I have tried any reasonable combination, and I have the ports published inside the docker images running the Postgresql databases, but did not find a solution. Have you solved the problem for you?

**Comment by AndriyMulyar** [comment]
I got this solution working, essentially first create a volume mounting your sqlite database to the running container.

```bash
docker run -v <directory_of_sqlite_on_machine>:<directory_in_container> --rm --name pgloader dimitri/pgloader:latest pgloader --debug  <directory_in_container> postgresql://username:password@172.17.0.1:5432/database
```

**Comment by nomhoi** [comment]
This works under docker. Use **--network host** option.
```
docker run --rm --network host --name pgloader dimitri/pgloader:latest pgloader -v --debug mysql://root:example@localhost:3306/wordpress postgresql://postgres:postgres@localhost/postgres
```

```
version: '3.7'

services:
  db:
    image: postgres:12.1-alpine
    container_name: catchysoft_db
    volumes:
      - ./data:/data
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  mysql_db:
    image: mysql:5.6
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
    volumes:
      - ./data:/data
      - mysql_data:/var/lib/mysql      
    ports:
      - "3306:3306"

volumes:
  postgres_data:
  mysql_data:
```

**Comment by cdxf** [comment]
Here is the workaround if you are using Docker on Windows:
- Use ``--network host``
- Replace localhost with host.docker.internal
- Change auth method to md5 in your pg.hba.conf (remember to reset postgres services):
```
# "local" is for Unix domain socket connections only
local   all             all                                     md5
# IPv4 local connections:
host    all             all             0.0.0.0/0               md5
```
- If you are using MYSQL 8, need to change the auth to mysql_native_password too.
https://github.com/dimitri/pgloader/issues/782#issuecomment-502323324

Here is the final command:
```
docker run --rm -it --net=host --name pgloader dimitri/pgloader:latest pgloader mysql://username:password@host.docker.internal:port/dbname postgresql://username:password@host.docker.internal:port/dbname
```

**Comment by Standaa** [comment]
@nomhoi 's solution did not work in my case. I think there is a typo in the command, which should read: `--network=host`.
Despite fixing this, my docker container would not resolve to localhost on my Mac. What worked eventually was:

`docker run --rm --name pgloader dimitri/pgloader:latest pgloader --debug "mysql://user:password@host/db_name" "postgresql://postgres@host.docker.internal/db_name"`

> The newest version of docker (18.03) offers a built in port forwarding solution. Inside your docker container simply have the db host set to host.docker.internal. This will be forwarded to the host the docker container is running on.

**Comment by hilmiwicak** [comment]
I have both mysql and postgres inside a separate container and assigned both container inside a same network, changed pg_hba.conf auth method into md5, and then run `docker run --rm --network host -it --name pgloader dimitri/pgloader:latest pgloader "mysql://moodle:password@host.docker.internal:3306/moodle" "postgresql://postgres@host.docker.internal:5432/maib"` and it still doesn't work.
