### ISSUE TITLE
Database error 22P02: invalid input syntax for type numeric

### ISSUE THREAD

**Issue by chrisspark** [dimitri/pgloader#739]
Hi Dimitri, 

Great gem! I'm trying to migrate a SQLite3 database to Postgres, and I'm running into the following error:

```
2018-02-07T17:10:01.282000Z ERROR PostgreSQL ["earnings_events"] Database error 22P02: invalid input syntax for type numeric: "0.54d0"
CONTEXT: COPY earnings_events, line 1, column earnings_estimate: "0.54d0"
```

The column type in my SQLite3 database is "decimal". It looks like it's properly casting to the "numeric" column type in Postgres. 

Any ideas on how I would fix this? Much appreciated!

**Comment by dimitri** [comment]
You can add a custom cast rule such as the following:

```
pgloader --cast 'type decimal to numeric using float-to-string' sqlite.db pgsql://user@host/dbname
```

Or in your load command file if you have one already. Meanwhile I have also added a default casting rule for the type `decimal` in pgloader, so you could also compile from fresh sources and retry.

**Comment by chrisspark** [comment]
Amazing, thanks so much!
