### ISSUE TITLE
Unable to enclose and escape double-quote

### ISSUE THREAD

**Issue by alkbkbharath** [dimitri/pgloader#740]
Hi,

I am new to postgresql and just starting to use it. I am trying to load a file into a table and facing some issues. Sample data - the file file1.RPT contains data in the below format

```
"Bharath"|Kumar|Krishnan
 abc"|def|ghi
 qwerty|asdfgh|lkjhg
```

Below is the load script that is used

```
LOAD CSV
INTO table1
....
WITH truncate,
fields optionally enclosed by '"',
fields escaped by '"'
fields terminated by '|'
....
```

However, the above script is not working and is not loading any data into the table. I am not sure whats the issue here. My understanding is that first row data has to be successfully loaded (since I have given optionally enclosed by) and the second row also must be loaded (since I am trying to escape the double quote).

Also, when I try to specify the logfile name and the root-dir path, I am not getting any file in the path specified. I would require the logfiles and the reject.log/dat files in my own user defined path.

I have been held up with both the issues for almost two days and searching around with no real help. It would be great if i can get this sorted.

Request help in getting the same rectified.

Thank you.

**Comment by dimitri** [comment]
Welcome to PostgreSQL then!

Usually to be able to solve any issue I need to see more details than provided here, but this time it's easy enough to fill the void. Next time, please show exactly what you did, the result you got and the result you expected, otherwise you're making it next to impossible for anyone to help you.

I see the following problems in your situation:

  - you're missing a comma after the `fields escaped by` option in the WITH clause,
  - the second line of your file is not conforming to your CSV specification,
  - you're using the same character as the field enclosing and its escape character, that won't work.

Here's a fixed load command for you, that uses the INLINE specification to find the data, so that we can have a self-contained test file.

```
LOAD CSV
     FROM INLINE
     INTO postgresql://dim@localhost/pgloader
     TARGET TABLE t740

     WITH truncate,
          fields optionally enclosed by '"',
          fields escaped by '"',
          fields terminated by '|'

   BEFORE LOAD DO
    $$ drop table if exists t740; $$,
    $$ CREATE TABLE t740 (f1 text, f2 text, f3 text);
    $$;


"Bharath"|Kumar|Krishnan
 abc"|def|ghi
 qwerty|asdfgh|lkjhg
```

The result of running pgloader with this load file is as following:

```
$ ./build/bin/pgloader ../temp/pgloader-issues/740.load 
2018-02-10T16:52:01.018000+01:00 LOG Data errors in '/private/tmp/pgloader/'
2018-02-10T16:52:01.020000+01:00 LOG Parsing commands from file #P"/Users/dim/dev/temp/pgloader-issues/740.load"
2018-02-10T16:52:01.214000+01:00 ERROR we are reading non quoted csv data and found a quote at 4
 abc"|def|ghi
2018-02-10T16:52:01.229000+01:00 LOG report summary reset
             table name     errors       rows      bytes      total time
-----------------------  ---------  ---------  ---------  --------------
                  fetch          0          0                     0.006s
            before load          0          2                     0.017s
-----------------------  ---------  ---------  ---------  --------------
        "public"."t740"          1          2     0.0 kB          0.019s
-----------------------  ---------  ---------  ---------  --------------
        Files Processed          0          1                     0.017s
COPY Threads Completion          0          2                     0.028s
-----------------------  ---------  ---------  ---------  --------------
      Total import time          1          2     0.0 kB          0.045s
```

And the content of the target table is:

```
   f1    │   f2   │    f3    
═════════╪════════╪══════════
 Bharath │ Kumar  │ Krishnan
 qwerty  │ asdfgh │ lkjhg
(2 rows)
```

**Comment by alkbkbharath** [comment]
Hi Sir @dimitri,
I have taken note of the points that you have mentioned about posting the questions and shall adhere it to it from the next time.
I understand that - both escaped by and optionally enclosed by cannot use the same character (in my case double-quote). As for the second row in the CSV, that's the way I am getting the data from the source file and hence I was trying to use both the options as I have said.

Could you also let me know how to specify the logfile and root-dir options to get the reject.log/dat files. I tried both options as given below

```
-L '/dir1/dir2/mylog.txt'
-D '/dir1/dir2'
```
I tried giving these in the WITH/SET sections, but I am not able to get the files. I understand they are available in /tmp/pgloader.log and /tmp/pgloader/dir, but I would require the logs in the user specified directory.

Thank you.

**Comment by dimitri** [comment]
What version of pgloader are you using? it should work with recent enough versions, even though we used to have bugs around the -D support some while ago...

**Comment by alkbkbharath** [comment]
Hi Sir @dimitri 
The version is 9.3... I am giving below the script that I have been trying.
```
LOAD CSV
FROM file1.RPT
INTO postgresql://mydb@localhost/pgloader
     TARGET TABLE tab1

     WITH truncate,
          fields optionally enclosed by '"',
          fields escaped by '"',
          fields terminated by '|',
-L to '/dir1/dir2/mytab.log',
-D to '/dir1/dir2'

SET
.....;
```

The above code runs and the data is inserted into the table. But I am not able to find any logfile in the specified path. I understand that both the log files and the reject.log/dat files are available in the /tmp/pgloader location. However, I would want that in my own user defined path.


Thank you.

**Comment by dimitri** [comment]
The -L and -D options are meant to be used in the command line, not in the load file... and 9.3 is the version of PostgreSQL, not the version of pgloader. Issue the command `pgloader --version` to have the version of pgloader.

**Comment by alkbkbharath** [comment]
Hi Sir @dimitri 

We are unable to figure out as to how the -L and -D options can be used in a load file to create the log files. Request your advise on the same.

Thank you.

**Comment by dimitri** [comment]
Did you try reading the docs? or the `--help` output from the command line? The `-L` (or `--logfile`)and `-D` (or `--root-dir`) options are expected to be found in the command line. Not in the load file. Did you even try using them at the command line?!
