### ISSUE TITLE
Heap exhausted during garbage collection: 32768 bytes available, 92272 requested

### ISSUE THREAD

**Issue by afrique007** [dimitri/pgloader#741]
Hello Chief..

I'm using the latest version of pgLoader and using  PSQL version 9.6.5. I was able to migrate a 2gb MySQL db into postgres successfully with out any errors messages like the one below. I then tried to migrate another MySQL db that is 12gb and I got the heap exhausted issue as seen below. 

My server has more than enough memory, see mem resources in following lines. 

```
[myuser@node10] /data/bamboo-test $ free -g
              total        used        free      shared  buff/cache   available
Mem:            503          84         209           0         209         418
Swap:             0           0           0
```

How can I make use of this above huge memory to get past this heap issue.  In the one line command below, is there a way of adding min or max memory flag to it or a way to allocate more memory to it?

```
pgloader mysql://root@localhost/mydb1 postgres:///mydb1
```

I also tried the following but none of them worked

```
pgloader --with "batch rows = 1000" mysql://root@localhost/mydb1 postgres:///mydb1
pgloader --with "batch rows = 25000" mysql://root@localhost/mydb1 postgres:///mydb1
pgloader --with "batch rows = 150000" mysql://root@localhost/mydb1 postgres:///mydb1
pgloader --with "batch rows = 2000000" mysql://root@localhost/mydb1 postgres:///mydb1
```

Error Message:
```
[myuser@node10] /data/svr-test $ pgloader mysql://root@localhost/mydb1 postgres:///mydb1
2018-02-12T14:53:55.996000-05:00 WARNING PostgreSQL warning: identifier "idx_75030_fk_ao_b9daca_aotracking_result_linked_tracking_entry_id" will be truncated to "idx_75030_fk_ao_b9daca_aotracking_result_linked_tracking_entry_"
Heap exhausted during garbage collection: 32768 bytes available, 92272 requested.
 Gen StaPg UbSta LaSta LUbSt Boxed Unboxed LB   LUB  !move  Alloc  Waste   Trig    WP  GCs Mem-age
   0: 83393     0 127314     0  6599  3302   227     0    10 294991360 36882944 127522456    0   1  0.0000
   1: 127474 131070     0     0   302 11828    29   137    22 333437504 69477824 42949672  168   0  0.8521
   2: 29078 121544     0     0   349 19798    26  5512    29 701686192 139959888 42949672  341   0  0.4923
   3: 22952 120445     0     0   585 29708    40 43638    90 2128755968 295125760 42949672  536   0  0.0605
   4:  7617 10362     0     0   508  2947  2178     0   108 181772864 2809280  2000000 2529   0  0.6590
   5:     0     0     0     0     0     0     0     0     0        0     0  2000000    0   0  0.0000
   6:     0     0     0     0  2292  1066     0     0     0 110034944     0  2000000 2146   0  0.0000
   Total bytes allocated    = 3750678832
   Dynamic-space-size bytes = 4294967296
GC control variables:
   *GC-INHIBIT* = true
   *GC-PENDING* = true
   *STOP-FOR-GC-PENDING* = false
fatal error encountered in SBCL pid 38642(tid 140737254881024):
Heap exhausted, game over.

Welcome to LDB, a low-level debugger for the Lisp runtime environment.
ldb> 
```

**Comment by vrtareg** [comment]
I have been in a same situation. 
I will post my configuration tomorrow.

**Comment by dimitri** [comment]
Please post `pgloader --version` and if you're not using a build from source, then build from source. Some recent patches should help a lot with this kind of situation. Also by default pgloader is allowed 4GB of RAM only, to move that to something bigger, you can change the DYNSIZE at build time:

    make DYNSIZE=16384 pgloader

**Comment by afrique007** [comment]
[wd-bamboo@node2184] /data/bamboo-test $ pgloader --version
pgloader version "3.4.1"
compiled with SBCL 1.3.11-1.el7

**Comment by dimitri** [comment]
Yes, please build from source and try again.

**Comment by vrtareg** [comment]
I have build it with "make DYNSIZE=10240" option
and in config file used "batch rows = 5000, batch concurrency = 2"
All smooth on large MySQL DB

**Comment by dimitri** [comment]
Thanks for your feedback. My guess is that the main factor here is having compiled from sources, and that it should run fine with the default parameters. The effect of your specific setup should now be performance characteristics rather than pass or fail.

Closing the issue.

**Comment by afrique007** [comment]
Thanks Dmitri and Vrtareg. I rebuild it with 20000mb and it worked like a charm.
