### ISSUE TITLE
SQL server char(36) to Postgres UUID 

### ISSUE THREAD

**Issue by benleov** [dimitri/pgloader#742]
Hi,

I would like to migrate some char(36) columns in SQL Server to Postgres UUID's. If I have

> column mytable.id to uuid drop typemod,

It fails to create the table, with the following error from Postgres

> 
> CREATE TABLE test.mytable 
> (
>   column1         int default NULL,
>   column2 int default NULL,
>   id                  uuid not null default 'generate_uuid_v4()'
> );

What the id column should be is 

> uuid not null default uuid_generate_v4()

That is, uuid_generate_v4() instead of generate_uuid_v4(), and no quotes. 

What am I doing wrong? Can I override this behavior somehow? 

Thanks

**Comment by dimitri** [comment]
Hi,

There's no `uuid_generate_v4` that I can find in the current pgloader source tree, is it possible that it's the default value used on the MS SQL side? If that's the case, just add `drop default` to your CAST command and it should be good. You will have to re-install a default value maybe, and could do that with the `AFTER LOAD` clause of the pgloader command.

It smells like a but in the quoting of the default values, but without more information about where the value comes from I can't fix it...

**Comment by benleov** [comment]
Thanks for your quick reply Dimitri,

I've generated a dump of my entire database and I cannot find any instances of uuid_generate_v4 or generate_uuid_v4() so no idea where thats coming from.

I'm using using pgloader 3.4.1.

Heres a dump from the source table

>  CREATE TABLE [test].[mytable](
>     [column1] [int] NULL,
>     [column2] [int] NULL,
>     [id] [char](36) NOT NULL CONSTRAINT [DF_T_mytable_id]  DEFAULT (newid()),
> CONSTRAINT [PK_mytable] PRIMARY KEY CLUSTERED
> (
>     [id] ASC
> )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
> ) ON [PRIMARY]
> 
> ---------------------------------------
> 
> ALTER TABLE [test].[mytable] ADD  CONSTRAINT [DF_T_mytable_id]  DEFAULT (newid()) FOR [id]
> GO

There are other constraints but nothing I can see with default values, other than that newid() one.

Adding drop default works, so this issue can be closed as far as I'm concerned. 

Thanks again.

**Comment by dimitri** [comment]
Closing for clean-up sake then, thanks for your feedback!

**Comment by dimitri** [comment]
ahah, sorry I wasn't looking at the right place. Of course it comes from pgloader:

  https://github.com/dimitri/pgloader/blob/master/src/sources/mssql/sql/list-all-columns.sql#L14

Can you try commenting out that line, building pgloader from source, and doing the migration again? My reading of the code makes me think it should work then, because the code at https://github.com/dimitri/pgloader/blob/master/src/sources/mssql/mssql-cast-rules.lisp#L160 is handling the `newid()` case fine. Or it should. As I don't have a test environment for MS SQL, it makes changing those things a long shot for me...

**Comment by benleov** [comment]
Ok so I've never written lisp before so this is probably completely wrong but if I change those two lines to uuid_generate_v4 then update src/sources/mssql/mssql-cast-rules.lisp on line 163

> string= "newsequentialid()" default)))
>                           (string= "newsequentialid()" default)
> +                          (string= "uuid_generate_v4()" default)))

 to get rid of the quotes it goes through and creates the column as a uuid not null. This is without drop default specified, so 

> column mytable.id to uuid drop typemod,

Does this help?

**Comment by dimitri** [comment]
Your idea would have worked and is a good analysis of what's going on, but for code modularity and long term maintenance reasons I took another route here, as you can see in attached bug fix. Please compile and test, and either report success or open this issue again. Thanks!

**Comment by benleov** [comment]
Seems to work, thanks.
