### ISSUE TITLE
How to install proper version?

### ISSUE THREAD

**Issue by Ajaxy** [dimitri/pgloader#744]
Thanks for a great work.

I'd like to try the project, but it's been two days that I'm trying to install it with no luck. On the main website (which I found first) there is no information about installation, docs website at http://pgloader.readthedocs.io/en/latest/pgloader.html also doesn't give any hint. Clicking on "Fork me on GitHub" helped to find README file.

I have Mac OS, so I tried to run `brew install --HEAD pgloader`, which failed with an error. Then I tried `brew install pgloader` and it gave me version "3.4.1". Regarding to README, stable is "3.1.0". Then I tried to use my Ubuntu web server to install stable Linux version with `apt-get`, but it gave me `2.3.3~dev3` and it required some `pgloader.conf` file, which I could not find any information about either.

So, would be great to cover somewhere a bit more info about installation options besides manual building from source. Thanks.

**Comment by dimitri** [comment]
Currently I lack time to handle release engineering properly. Sometimes, I make happen a Debian release, but that's about it. If you want a version with the least number of bugs possible, build from current sources, that's what I know how to maintain.

See also https://github.com/dimitri/pgloader/blob/master/INSTALL.md.

**Comment by Ajaxy** [comment]
Ok, thanks. I finally have used one from `brew install pgloader`.
