### ISSUE TITLE
MySQL default casting rules cause warnings

### ISSUE THREAD

**Issue by cbandy** [dimitri/pgloader#746]
When using `data only, create no tables` to populate a schema built with `schema only`, PGLoader emits warnings about the float data type:

```
2018-02-15T21:53:22.319000Z WARNING Source column "raw_mysql"."matches"."probability" is casted to type "float" which is not the same as "double precision", the type of current target database column "\"raw_mysql\""."\"matches\""."probability".
```

I was able to silence this warning by adding `type float to "double precision" drop typemod` to my command.

----

Since PostgreSQL treats these [identically](https://www.postgresql.org/docs/current/static/datatype-numeric.html#DATATYPE-FLOAT):

> PostgreSQL also supports the SQL-standard notations `float` and `float(p)` for specifying inexact numeric types... `float` with no precision specified is taken to mean `double precision`.

it seems to me this default rule:

```lisp
(:source (:type "float")     :target (:type "float"    :drop-typemod t))
```

should instead be:

```lisp
(:source (:type "float") :target (:type "double precision" :drop-typemod t))
```

**Comment by dimitri** [comment]
There's another facility in pgloader source code that knows some of the type name mappings in between different spellings of the same thing. I've added _float_ and _double precision_ as synonyms on that list, so you shouldn't have a warning anymore.
