### ISSUE TITLE
pgloader available with PostgreSQL 10 ?

### ISSUE THREAD

**Issue by did16** [dimitri/pgloader#750]
Hi
I would like to install pgloader from PGDG repo packages and it seems that there is no pgloader package.
will it be fixed soon ?
Thanks in advance 
Didier ROS

**Comment by dimitri** [comment]
Are you using RPM packages from https://yum.postgresql.org or Debian package from https://wiki.postgresql.org/wiki/Apt ?

**Comment by did16** [comment]
Hi Dimitri
I am using https://yum.postgresql.org for RHEL /Centos 6 and 7 for PostgreSQL 9.6, 10 .
Best Regards
Didier

**Comment by tigerfoot** [comment]
I propose to close this ticket, pgloader is available in the el7 part (el6 doesn't have a working or enough up to date lisp)
