### ISSUE TITLE
Cannot import jabberd sqlite database

### ISSUE THREAD

**Issue by Peter2121** [dimitri/pgloader#751]
- [ ] pgloader --version
  
    ```
pgloader version "3.4.1"
compiled with Clozure Common Lisp Version 1.11  (FreebsdX8664)
    ```
  
  - [ ] did you test a fresh compile from the source tree?
    
    NO
    
  - [ ] did you search for other similar issues?

    YES
    
  - [ ] how can I reproduce the bug?

    Create an sqlite3 database, create a table with '-' in the name, for example, CREATE TABLE IF NOT EXISTS "published-roster" (
    "collection-owner" TEXT NOT NULL,
    "object-sequence" INTEGER PRIMARY KEY,
    "jid" TEXT NOT NULL,
        "group" TEXT,
    "name" TEXT,
    "to" BOOLEAN NOT NULL,
    "from" BOOLEAN NOT NULL,
    "ask" INTEGER NOT NULL );
    put some data inside the table, then try to import the database.
```
FATAL error: Could not prepare an sqlite statement.
Code ERROR: near "-": syntax error.
Database: /root/./new.db
SQL: PRAGMA table_info(roster-items)
Date/time: 2018-02-26-16:36An unhandled error condition has been signalled: Could not prepare an sqlite statement.
Code ERROR: near "-": syntax error.
Database: /root/./new.db
SQL: PRAGMA table_info(published-roster)
```
If I modify the load script to exclude tables with '-' in their names (excluding table names like '%-%') - everything works as expected.

**Comment by dimitri** [comment]
In the current pgloader source tree we use the following SQL query for getting information about a table in SQLite, and we use the backquotes:
  https://github.com/dimitri/pgloader/blob/master/src/sources/sqlite/sql/list-columns.sql

Please compile pgloader from sources to get your bug fix.
