### ISSUE TITLE
Problem with loading ipv6 ip format to DB

### ISSUE THREAD

**Issue by kornashevskiy** [dimitri/pgloader#753]
Hi.
I try execute the following command:

```
LOAD CSV
        FROM /home/alex/Загрузки/GeoIPv6.csv	WITH ENCODING iso-8859-1 HAVING FIELDS
	(
	    start, end, startIpNum, endIpNum, code, country
	)
        INTO postgresql://loot_bet:loot_bet@localhost:5432/loot_bet_test?geo_ip
	TARGET COLUMNS
             (
                ip_range ip4r using (ip-range startIpNum endIpNum),
                code
             )
        WITH truncate,
	     trim unquoted blanks,
	     fields terminated by ',',
             fields optionally enclosed by '"',
             fields escaped by double-quote
SET work_mem to '32 MB', maintenance_work_mem to '64 MB';
```

My GeoIPv6.csv file has ipv6 ip format the following exemple:

```
"2001:5::", "2001:5:ffff:ffff:ffff:ffff:ffff:ffff", "42540488558116655331872044393019998208", "42540488637344817846136381986563948543", "EU", "Europe"
```

So I have the error

```
  "ERROR Could not read line 36635: The value 58569099056893353938103487368328642560 is not of type" (UNSIGNED-BYTE 32).
```

How can I send 64 bit format that ip-range function works fine?

**Comment by dimitri** [comment]
The current implementation of the `ip-range` function in pgloader only knows to process IPv4 addresses, so 32 bits numbers. See https://github.com/dimitri/pgloader/blob/master/src/utils/transforms.lisp#L156-L184 for details.

You can write an ipv6 version of this function in your own `ipv6-range.lisp` file then use the pgloader option `--load-lisp-file` to have your code integrated into pgloader. When that works ok for you, consider contributing your solution to the project!

**Comment by kornashevskiy** [comment]
Thanks, I wrote ipv6 version of ip-range function:
(in-package :pgloader.transforms)

(defun ipv6-range (start-integer-string end-integer-string)
  "Transform a couple of integers to an IP4R ip range notation."
  (declare (optimize speed)
	   (type (or null string) start-integer-string end-integer-string))
  (when (and start-integer-string end-integer-string)
    (let ((ip-start start-integer-string) (ip-end end-integer-string))
      (concatenate 'simple-base-string ip-start "-" ip-end))))

And now everything works fine.
