### ISSUE TITLE
.pgpass file not being read

### ISSUE THREAD

**Issue by a666** [dimitri/pgloader#754]
#### pgloader --version

```
pgloader version "3.4.1"
compiled with SBCL 1.3.1.debian
on Ubuntu 16.04 from apt.postgresql.org
```
  
#### did you test a fresh compile from the source tree?

Sorry, no.
    
#### did you search for other similar issues?

Yes, [460](https://github.com/dimitri/pgloader/issues/460) and [83](https://github.com/dimitri/pgloader/issues/83).
[460](https://github.com/dimitri/pgloader/issues/460) has been closed in [d5072d11](https://github.com/dimitri/pgloader/commit/d5072d11e5d52e10b9e82301fa7f16b49fd42d08)

Documentation states:
  
When no password is found either in the connection URI nor in the environment, then pgloader looks for a .pgpass file as documented at https://www.postgresql.org/docs/current/static/libpq-pgpass.html.
The implementation is not that of libpq though. 
As with libpq you can set the environment variable PGPASSFILE to point to a .pgpass file, and pgloader defaults to ~/.pgpass on unix like systems and %APPDATA%postgresqlpgpass.conf on windows. 
Matching rules and syntax are the same as with libpq, refer to its documentation.
    
    
#### how can I reproduce the bug?

Having a ~/.pgpass
```
127.0.0.1:*:*:aaa:password
```
with these permissions
```
$ ls -la ~/.pgpass
-rw------- 1 aaa aaa 80 Mar  4 15:41 /home/aaa/.pgpass
```
And user exists
```
createuser -E -s -P aaa
```
And user can connect without password prompt
```
$ psql -U aaa -h 127.0.0.1 postgres
psql (9.6.8)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

postgres=# \q
```

Using the following bug.load    
```
LOAD CSV
     FROM INLINE with encoding 'ascii'
     INTO postgresql://aaa@127.0.0.1/pgloader?tablename=jordane

     WITH truncate,
          fields terminated by '|',
          fields not enclosed,
          fields escaped by backslash-quote

      SET work_mem to '128MB',
          standard_conforming_strings to 'on'

   BEFORE LOAD DO
    $$ drop table if exists jordane; $$,
    $$ CREATE TABLE jordane
       (
         "NOM" character(20),
         "PRENOM" character(20)
       )
    $$;

BORDET|Jordane
BORDET|Audrey
LASTNAME|"opening quote
BONNIER|testprenombe~aucouptroplong
JOURDAIN|héhé¶
```

#### pgloader output you obtain

Using 
```
$ pgloader -v -d bug.load
$ PGPASSFILE=~/.pgpass pgloader -v -d bug.load
$ export PGPASSFILE=~/.pgpass && pgloader -v -d bug.load
```

Results in (with minimal differences):

```
sb-impl::*default-external-format* :UTF-8
tmpdir: #P"/tmp/pgloader/"
2018-03-04T21:55:51.021000Z NOTICE Starting pgloader, log system is ready.
2018-03-04T21:55:51.053000Z INFO Starting monitor
KABOOM!
FATAL error: Failed to connect to pgsql at "127.0.0.1" (port 5432) as user "aaa": Server requested md5-password authentication, but no password was given.
Date/time: 2018-03-04-15:55An unhandled error condition has been signalled:
                              Failed to connect to pgsql at "127.0.0.1" (port 5432) as user "aaa": Server requested md5-password authentication, but no password was given.


Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10091D4703}>
0: ((LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX))
1: (SB-IMPL::CALL-WITH-SANE-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX) {100A34B22B}>)
2: (SB-IMPL::%WITH-STANDARD-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX) {100A34B1FB}>)
3: (PRINT-BACKTRACE :STREAM #<SB-IMPL::STRING-OUTPUT-STREAM {100A346393}> :START 0 :FROM :DEBUGGER-FRAME :COUNT 4611686018427387903 :PRINT-THREAD T :PRINT-FRAME-SOURCE NIL :METHOD-FRAME-STYLE NIL)
4: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE-TO-STREAM #<SB-IMPL::STRING-OUTPUT-STREAM {100A346393}>)
5: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE #<PGLOADER.CONNECTION:DB-CONNECTION-ERROR {100A346233}> :OUTPUT NIL :IF-EXISTS :APPEND :VERBOSE NIL)
6: ((FLET #:H0 :IN PGLOADER::MAIN) #<PGLOADER.CONNECTION:DB-CONNECTION-ERROR {100A346233}>)
7: (SIGNAL #<PGLOADER.CONNECTION:DB-CONNECTION-ERROR {100A346233}>)
8: (ERROR PGLOADER.CONNECTION:DB-CONNECTION-ERROR :MESG "Server requested md5-password authentication, but no password was given." :TYPE "pgsql" :HOST "127.0.0.1" :PORT 5432 :USER "aaa")
9: (PGLOADER.PGSQL:LIST-RESERVED-KEYWORDS #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://aaa@127.0.0.1:5432/pgloader {10097F2363}>)
10: ((LAMBDA ()))
11: (PGLOADER:RUN-COMMANDS #P"/home/aaa/bug.load" :START-LOGGER NIL :FLUSH-SUMMARY T :SUMMARY NIL :LOG-FILENAME NIL :LOG-MIN-MESSAGES NIL :CLIENT-MIN-MESSAGES NIL)
12: (PGLOADER::PROCESS-COMMAND-FILE ("bug.load") :FLUSH-SUMMARY T)
13: (PGLOADER::MAIN ("pgloader" "-v" "-d" "bug.load"))
14: ((LAMBDA NIL :IN "/build/pgloader-cLcLIO/pgloader-3.4.1+dfsg/dumper-2SKVI5f7.lisp"))
15: ((FLET #:WITHOUT-INTERRUPTS-BODY-82 :IN SAVE-LISP-AND-DIE))
16: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))



2018-03-04T21:55:51.261000Z INFO Stopping monitor

What I am doing here?

Failed to connect to pgsql at "127.0.0.1" (port 5432) as user "aaa": Server requested md5-password authentication, but no password was given.


Waiting for the monitor thread to complete.

```

Unfortunately this works...
```
$ PGPASSWORD=password pgloader bug.load
2018-03-04T22:19:38.263000Z FATAL :ASCII stream decoding error on
#<SB-SYS:FD-STREAM for "file /home/aaa/bug.load" {100BDDA643}>:
  the octet sequence #(195) cannot be decoded.
2018-03-04T22:19:38.263000Z ERROR PostgreSQL ["jordane"] Database error 22001: value too long for type character(20)
CONTEXT: COPY jordane, line 4, column PRENOM: "testprenombe~aucouptroplong"
2018-03-04T22:19:38.263000Z LOG report summary reset
             table name       read   imported     errors      total time
-----------------------  ---------  ---------  ---------  --------------
                  fetch          0          0          0          0.008s
            before load          2          2          0          0.011s
-----------------------  ---------  ---------  ---------  --------------
                jordane          4          3          2          0.015s
-----------------------  ---------  ---------  ---------  --------------
        Files Processed          1          1          0          0.020s
COPY Threads Completion          2          2          0          0.018s
-----------------------  ---------  ---------  ---------  --------------
      Total import time          4          3          2          0.268s

```
And so does changing the connection string to `postgresql://aaa:password@127.0.0.1/pgloader?tablename=jordane`.

#### data that is being loaded, if relevant
Does not seem relevant.

#### How the data is different from what you expected, if relevant
Does not seem relevant.

**Comment by dimitri** [comment]
Unfortunately pgpass support didn't make it in 3.4.1, it got committed about one month after the release. Please compile from sources to get the feature. I'll see about making a new release soon, but don't wait for it!

**Comment by a666** [comment]
Thanks mate.

**Comment by bounav** [comment]
For anyone having this issue with a recent version of pgloader to does include `pgpass` support. It's probably not a _pgloader_ problem.

In my case, I checked that psql could loads my `~/.pgpass` file OK first (and of course, it did not!).

Once I fixed some daft errors in the file (I had forgot the "database" column before the username and had a coma to separate the username and password value... ), it started working.

[This answer an stackoverflow](https://stackoverflow.com/a/50563298/2472) lists a couple of other things to check as well (e.g. file permissions etc).

**Comment by bounav** [comment]
To answer my own question:

> Is my mistake to assume the I can store passwords for connection non postgres database engine in my .pgpass? I'm assuming here as long as the host, port, database name and user name match, the password will be used?

Yes, I think I was wrong to assume the password would loaded from the file for `mysql://` (or any other non `postgres://`) connection string.

After I changed my load file to this (with the same `~/.pgpass` file)

```
LOAD DATABASE
     FROM      mysql://foo:mysql_password@192.168.10.192:3306/dbName
     INTO postgresql://postgres@192.168.10.192:5432/dbName
...
```

And pgloader was able to connect to the `postgresql://...` database using the password from the `~/.pgpass` file.

**Comment by dimitri** [comment]
Hi @bounav ; indeed the `~/.pgpass` mechanism only applies to Postgres connections. It didn't cross my mind that it could be useful for it to be used for other database sources...
