### ISSUE TITLE
Fatal CIRCULAR-DEPENDENCY while building on macOS 10.13.13 using sbcl 1.4.5

### ISSUE THREAD

**Issue by eirvandelden** [dimitri/pgloader#755]
- [x] pgloader --version
  
    ```
    3.4.1
    ```
  
  - [x] did you test a fresh compile from the source tree?
    yes    
  - [x] did you search for other similar issues?
    
  - [x] how can I reproduce the bug?

# What I did:
- download `pgloader-bundle-3.4.1.tgz`
- `brew install sbcl`
- `make`

# What I expected:
- pgloader to build

# What I got:
```
;; loading system "pgloader"
Fatal CIRCULAR-DEPENDENCY:
  Circular dependency:
     ((#<ASDF/LISP-ACTION:LOAD-OP > . #<ASDF/SYSTEM:SYSTEM "simple-date">)
      (#<ASDF/LISP-ACTION:LOAD-OP >
       . #<ASDF/SYSTEM:SYSTEM "simple-date-postgres-glue">)
      (#<ASDF/LISP-ACTION:LOAD-OP >
       . #<ASDF/COMPONENT:MODULE "simple-date-postgres-glue" "simple-date">)
      (#<ASDF/LISP-ACTION:LOAD-OP >
       . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "simple-date-postgres-glue" "simple-date" "cl-postgres-glue">)
      (#<ASDF/LISP-ACTION:PREPARE-OP >
       . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "simple-date-postgres-glue" "simple-date" "cl-postgres-glue">)
      (#<ASDF/LISP-ACTION:PREPARE-OP >
       . #<ASDF/COMPONENT:MODULE "simple-date-postgres-glue" "simple-date">)
      (#<ASDF/LISP-ACTION:PREPARE-OP >
       . #<ASDF/SYSTEM:SYSTEM "simple-date-postgres-glue">))
make: *** [bin/pgloader] Error 1
```

macOS 10.13.13

**Comment by dimitri** [comment]
It's been fixed in the postmodern upstream package and in the brew packaging too. Can you upgrade your brew formula or maybe use `--HEAD` with pgloader?

**Comment by eirvandelden** [comment]
This happen to me both using the package and using `brew install --HEAD pgloader`.

A regular old `brew install pgloader` works, but I've got a different issue in that version (it reports it did the import, complete with table and all, but my target postgres database is still empty)

**Comment by dimitri** [comment]
Check your `search_path` and your schema list, my bet is that you're not looking at the right place! Granted, pgloader 3.4.1 doesn't make it as obvious as it should be. Use `\dn` and `\dt *.` in psql to see all tables, not just the ones in the `public` schema.

**Comment by eirvandelden** [comment]
Yeah, the empty database was a missing search_path, thanks!

**Comment by archanazafin** [comment]
Hi,
I am getting the same error while building for windows. Tried building through the pgloader-bundle 3.4.1 already available. 
version : 3.4.1
command : make
Also tried taking the latest source code available, facing multiple issues in that.

Thanks
