### ISSUE TITLE
No output or errors running in Docker

### ISSUE THREAD

**Issue by mafrosis** [dimitri/pgloader#758]
Input file is mysql dump and output is valid connection string.

 - [x] pgloader --version

Use latest docker container.
  
    pgloader version "3.4.2~devel"
  
  - [x] did you test a fresh compile from the source tree?
    
No. Docker "latest" container should be latest source.
    
  - [x] did you search for other similar issues?

Yes. There are a few with no solution
    
  - [x] how can I reproduce the bug?

```
pgloader magento_data.sql 'postgres://admin:password@rds.fdhgsdjhfg.us-east-1.rds.amazonaws.com/testdb'
```

  - [x] pgloader output you obtain (with -v and --debug)
  
```
sb-impl::*default-external-format* :ANSI_X3.4-1968
tmpdir: #P"/tmp/pgloader/"
2018-03-08T22:46:08.005000Z NOTICE Starting pgloader, log system is ready.
2018-03-08T22:46:08.012000Z INFO Starting monitor
2018-03-08T22:46:08.016000Z INFO Stopping monitor
```

  - [x] data that is being loaded, if relevant

  - [x] How the data is different from what you expected, if relevant

There is no output

**Comment by dimitri** [comment]
While there should be some output and I'll see about that, I can already spot that you're trying to have pgloader work with a SQL file as input, which is not a supported operation. For that, use `psql`, the PostgreSQL dedicated tool. pgloader is about other file formats (CSV and its derivatives) and migrating from another database technology such as SQLite or MySQL.
