### ISSUE TITLE
ERROR non whitespace after quoted data

### ISSUE THREAD

**Issue by ParadoxFilm** [dimitri/pgloader#765]
Hello, @dimitri !
I catched next **error**:
```
2018-03-17T00:15:43.127000+03:00 ERROR non whitespace after quoted data #<CSV-READER LINE-IDX:28801 CHARACTER-LINE-IDX:87 CHARACTER-IDX:2756300 "{\"D\":[\"lady\\" {100E9C4403}> s
2018-03-17T00:15:43.128000+03:00 FATAL non whitespace after quoted data #<CSV-READER LINE-IDX:28801 CHARACTER-LINE-IDX:87 CHARACTER-IDX:2756300 "{\"D\":[\"lady\\" {100E9C4403}> s
```
**Problem line** (_null fields it's okay_):
```
'AAAAAA';'BBBBBB';'CCCCCC';1234567890;;;;;;;;'DDDDDD';'{"D":["lady\'s_aaaaa@gmail.com","123456@mail.com",""]}'
```
**Config file**:
```
LOAD CSV  
FROM STDIN WITH ENCODING utf8 
	HAVING FIELDS
	(  
	   "A","B","C","D","E","F","Q","W","E","R","T","Y","U"
	)  
INTO postgresql://user:***@localhost/foodb?table
	TARGET COLUMNS  
	(
	   "A","B","C","D","E","F","Q","W","E","R","T","Y","U"
	)
WITH skip header = 1,
	fields optionally enclosed by '0x27',
	fields terminated by ';',
	fields escaped by backslash-quote,
	workers = 32, concurrency = 16

SET work_mem to '256 MB', maintenance_work_mem to '4092 MB';
```
**So**:
1. Why it happened and **how fix** it?
2. Why did the pgloader **stop** after error (why is it fatal error)?

Such error throw for each line that contains something like `'foo\'bar'`. But it's just escape....
**Version**:
```
# pgloader --version
pgloader version "3.4.a7fd776"
compiled with SBCL 1.3.1.debian
```

**Comment by kxjhlele** [comment]
I also encountered

pgloader version "3.4.e4dca1a"
compiled with SBCL 1.4.5.debian

**Comment by ParadoxFilm** [comment]
@kxjhlele, use this:
`fields escaped by '\''`

**Comment by kxjhlele** [comment]
Mine is
2018-03-26T15:15:14.387000+08:00 ERROR we are reading non quoted csv data and found a quote at
#<CSV-READER LINE-IDX:7 CHARACTER-LINE-IDX:7 CHARACTER-IDX:507 "S#塸s凚" {1008B5F053}>
"
2018-03-26T15:15:14.387000+08:00 FATAL we are reading non quoted csv data and found a quote at
#<CSV-READER LINE-IDX:7 CHARACTER-LINE-IDX:7 CHARACTER-IDX:507 "S#塸s凚" {1008B5F053}>
"

Special characters

**Comment by ParadoxFilm** [comment]
I think its other mistake. Show this to @dimitri
