### ISSUE TITLE
Migration failing on foreign key constraint

### ISSUE THREAD

**Issue by Hoya** [dimitri/pgloader#766]
I'm using the latest code from the master branch. "3.4.2~devel"

I have two tables that are dependent on each other, one table being much larger than the other. The problem seems to be that one table finishes copying all data before the other table is finished copying data and breaks the foreign key constraint. 

I am using the "disable triggers" option.

This is the error when the migration job fails:

```
ERROR PostgreSQL Database error 23503: insert or update on table "message_logs" violates foreign key constraint "message_logs_batch_id_foreign"
DETAIL: Key (batch_id)=(19573259) is not present in table "message_batches".
QUERY: ALTER TABLE sgkit_load.message_logs ADD CONSTRAINT message_logs_batch_id_foreign FOREIGN KEY(batch_id) REFERENCES sgkit_load.message_batches(id) ON UPDATE RESTRICT ON DELETE RESTRICT
KABOOM!
FATAL error: Empty query sent.
```

The only solution around this I can think of is to reduce concurrency and copy one table at a time.

**Comment by dimitri** [comment]
It should be that the foreign keys are only installed when all the COPY are done, and when all the indexes are created, and ever after the primary key indexes have been installed. So there should not be any concurrency issues at this point. More probably, your source data has consistency issues, can you look into the problematic data on the source side? I guess you'll see the same error, only that the source system somehow doesn't care, or failed to notice.

**Comment by Hoya** [comment]
The source data was the first thing I actually checked and the data is fine on the source side.

MySQL -> Postgres

However, I took a look at the destination and found the discrepancy.
The error states : Key (batch_id)=(19573259) is not present in table "message_batches"

So I ran the following queries to check.

`select * from message_batches where id >= 19573259`
id is the incrementing primary key and this query results in 0 records. 
I also confirmed that all data before id 19573259 was copied successfully.

Interesting thing is that on the other table linked by the constraint has all it's data.

` select * from message_logs where batch_id = 19573259`
This query returns the data record successfully, and all records with a higher batch_id also exist.
batch_id of the message_logs table is foreign key constrained to id of the message_batches table.

Any ideas on what might actually be going on?

**Comment by Hoya** [comment]
```
KABOOM!
FATAL error: Empty query sent.
An unhandled error condition has been signalled: Empty query sent.

What I am doing here?

Empty query sent.
```

This is the additional messages I got before pgloader died

**Comment by dimitri** [comment]
I think we should see previous errors in the log, do you have the full log output? depending on what the earlier logs say, we might have to retry in `--debug` mode.

**Comment by Hoya** [comment]
I ran it again and here's the debug output

```
2018-03-21T01:41:05.621000+09:00 NOTICE Executing SQL block for after load
2018-03-21T01:41:05.742000+09:00 DEBUG CONNECTED TO #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://soomgo@dw.db.soomgo.com:5432/soomgo {100A55FC03}>
2018-03-21T01:41:05.742000+09:00 DEBUG SET client_encoding TO 'utf8'
2018-03-21T01:41:05.743000+09:00 DEBUG SET search_path TO soomgo, sgkit_load
2018-03-21T01:41:05.744000+09:00 DEBUG SET work_mem TO '1024 MB'
2018-03-21T01:41:05.744000+09:00 DEBUG SET maintenance_work_mem TO '2048 MB'
2018-03-21T01:41:05.745000+09:00 DEBUG SET application_name TO 'pgloader'
2018-03-21T01:41:05.746000+09:00 DEBUG BEGIN
2018-03-21T01:41:05.747000+09:00 SQL 
KABOOM!
FATAL error: Empty query sent.
Date/time: 2018-03-21-01:41An unhandled error condition has been signalled:
                              Empty query sent.


Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10091E44D3}>
0: ((LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX))
1: (SB-IMPL::CALL-WITH-SANE-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX) {1015AFF95B}>)
2: (SB-IMPL::%WITH-STANDARD-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX) {1015AFF92B}>)
3: (PRINT-BACKTRACE :STREAM #<SB-IMPL::STRING-OUTPUT-STREAM {1015AFD5E3}> :START 0 :FROM :DEBUGGER-FRAME :COUNT 4611686018427387903 :PRINT-THREAD T :PRINT-FRAME-SOURCE NIL :METHOD-FRAME-STYLE NIL)
4: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE-TO-STREAM #<SB-IMPL::STRING-OUTPUT-STREAM {1015AFD5E3}>)
5: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE #<SIMPLE-WARNING "Empty query sent." {1015AFD433}> :OUTPUT NIL :IF-EXISTS :APPEND :VERBOSE NIL)
6: ((FLET #:H0 :IN PGLOADER::MAIN) #<SIMPLE-WARNING "Empty query sent." {1015AFD433}>)
7: (SIGNAL #<SIMPLE-WARNING "Empty query sent." {1015AFD433}>)
8: (SB-KERNEL::%WARN "Empty query sent." NIL #<SB-KERNEL::CONDITION-CLASSOID WARNING> SIMPLE-WARNING)
9: (CL-POSTGRES::LOOK-FOR-ROW #<unavailable argument>)
10: (CL-POSTGRES::SEND-QUERY #<unavailable argument> #<unavailable argument> #<unavailable argument>)
11: ((LABELS #:G554 :IN CL-POSTGRES:EXEC-QUERY))
12: (PGLOADER.PGSQL:PGSQL-EXECUTE "" :LOG-LEVEL :SQL :CLIENT-MIN-MESSAGES :ERROR :ON-ERROR-STOP T)
13: ((LAMBDA (#:|anonymous-transaction58|) :IN #:DROP-THRU-TAG-50) #<unavailable argument>)
14: (POSTMODERN::CALL-WITH-TRANSACTION #<FUNCTION (LAMBDA (#:|anonymous-transaction58|) :IN #:DROP-THRU-TAG-50) {100928633B}>)
15: ((LAMBDA ()))
16: (PGLOADER:RUN-COMMANDS #P"/root/sgkit.load" :START-LOGGER NIL :FLUSH-SUMMARY T :SUMMARY NIL :LOG-FILENAME NIL :LOG-MIN-MESSAGES NIL :CLIENT-MIN-MESSAGES NIL)
17: (PGLOADER::PROCESS-COMMAND-FILE ("sgkit.load") :FLUSH-SUMMARY T)
18: (PGLOADER.MONITOR::CALL-WITH-MONITOR #<CLOSURE (LAMBDA NIL :IN PGLOADER::MAIN) {1009217C6B}>)
19: (PGLOADER::MAIN ("pgloader" "--debug" "sgkit.load"))
20: ((LAMBDA NIL :IN "/root/pgloader-master/dumper-2SKVI5f7.lisp"))
21: ((FLET #:WITHOUT-INTERRUPTS-BODY-82 :IN SAVE-LISP-AND-DIE))
22: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))



2018-03-21T01:41:05.753000+09:00 INFO Stopping monitor

What I am doing here?

Empty query sent.
```

**Comment by Hoya** [comment]
Note: I'm using MariaDB 10.2 as the source database

**Comment by dimitri** [comment]
You should be able to create the target schema with Django and then use the `with data only, reindex` options of pgloader to make that happen automatically for you.

**Comment by dimitri** [comment]
Closing now. If the problem still exists in the current pgloader version (3.6.1, or built from current source), please open the issue again, with relevant information.
