### ISSUE TITLE
How to change catalog or download from specific catalog.schema all tables?

### ISSUE THREAD

**Issue by zimonth** [dimitri/pgloader#769]
1. show what you did,
usecase.pgloader.conf:
```
load database
        from mssql://user:passwd@server/maindb
        into postgresql:///dbcopy;
$ pgloader usecase.pgloader.conf
```
  2. show the result you got,
```
Max connections reached, increase value of TDS_MAX_CONN
Max connections reached, increase value of TDS_MAX_CONN
2018-03-21T14:00:37.425000Z LOG report summary reset
             table name       read   imported     errors      total time
-----------------------  ---------  ---------  ---------  --------------
        fetch meta data          1          1          0          0.147s 
         Create Schemas          0          0          0          0.001s 
       Create SQL Types          0          0          0          0.004s 
          Create tables          2          2          0          0.075s 
         Set Table OIDs          1          1          0          0.006s 
-----------------------  ---------  ---------  ---------  --------------
   dbo.reporting_tables          0          0          0          0.049s 
-----------------------  ---------  ---------  ---------  --------------
COPY Threads Completion          4          4          0          0.049s 
 Index Build Completion          0          0          0          0.000s 
        Reset Sequences          0          0          0          0.018s 
           Primary Keys          0          0          0          0.000s 
    Create Foreign Keys          0          0          0          0.000s 
        Create Triggers          0          0          0          0.000s 
       Install Comments          0          0          0          0.000s 
-----------------------  ---------  ---------  ---------  --------------
      Total import time          0          0          0          0.429s 
```

  3. explain how the result is not what you expected.

It did copy some tables for metainformation from default catalog, two tables, but the tables I am interested are inside another "catalog".
https://stackoverflow.com/questions/7022755/whats-the-difference-between-a-catalog-and-a-schema-in-a-relational-database

  $ pgloader --version
    ```
pgloader version "3.4.1"
compiled with SBCL 1.4.0-1.fc27
    ```
  
  - [ ] did you test a fresh compile from the source tree?
    No. 
pgloader-3.4.1-1.f27.x86_64

  - [ ] did you search for other similar issues?
   Yes
 
  - [ ] how can I reproduce the bug?
   Would need MS SQL Server with several catalogs to try.

Using tds_fdw in postgres server, I can access the wanted tables by eg:

 CREATE FOREIGN TABLE s_mssql.exampletable (
        id_string  varchar)
 SERVER mssql_server OPTIONS (table_name 'anothercatalog.dbo.exampletable');

**Comment by dimitri** [comment]
Can you put _anothercatalog_ in the connection string of pgloader in place of the _maindb_ catalog you're currently using?

**Comment by zimonth** [comment]
I can, but it then doesn't get anything from the remote sql server:
```
$ pgloader -dv 'mssql://username:password@mssqlserver/maindb/anothercatalog' 'postgresql:///dbcopy'
sb-impl::*default-external-format* :UTF-8
tmpdir: #P"/tmp/pgloader/"
2018-03-22T20:10:14.009000Z NOTICE Starting pgloader, log system is ready.
2018-03-22T20:10:14.013000Z INFO Starting monitor
2018-03-22T20:10:14.015000Z INFO Stopping monitor
```

In PostgreSQL, the "catalog" is just like a database. But in MS SQL server it is confusing me, there is both databases and catalogs with same names, but they behave differently. I cannot connect straight to the database "anothercatalog". Or I can, but then there is not tables, nor views available. If I log in to the maindb, then the default catalog is used, unless I go to an anothercatalog manually (in DBeaver) or in tds_fdw. I also cannot give database "maindb/anothercatalog" in the tds_fdw CREATE SERVER command parameters, but have to do it in CREATE FOREIGN TABLE part.

**Comment by dimitri** [comment]
Closing for clean-up of the issues dashboard. If action is still needed, please consider opening this issue again, with more information.
