### ISSUE TITLE
Fatal error in "buildapp" : Error #<SILENT-EXIT-ERROR #x145E5626>

### ISSUE THREAD

**Issue by giminni** [dimitri/pgloader#770]
Could not compile pgloader successfully. Here my findings:

- Target: armhf
- OS: Ubuntu 16.04.4. LTS
- Kernel: Linux xu4svrp01 4.14.7+ #1 SMP PREEMPT Wed Dec 20 03:06:36 CST 2017 armv7l armv7l armv7l GNU/Linux
- CCL: Clozure Common Lisp Version 1.11.5/v1.11.5  (LinuxARM32)
- pgloader: git clone https://github.com/dimitri/pgloader.git
- make: /usr/bin/make CL=ccl DYNSIZE=256 pgloader
- Error: loading file #P"/home/rpiadmin/tmp/work/pgloader/src/hooks.lisp"
Fatal error in "buildapp" : Error #<SILENT-EXIT-ERROR #x145E5626>

Output:
```
/usr/bin/make CL=ccl DYNSIZE=256 pgloader
ccl --no-init --load build/quicklisp/setup.lisp                   \
             --eval '(push "/home/rpiadmin/tmp/work/pgloader/" ql:*local-project-directories*)' \
             --eval '(ql:quickload "pgloader")'                       \
             --eval '(quit)'
To load "pgloader":
  Load 1 ASDF system:
    pgloader
; Loading "pgloader"
...
touch build/libs.stamp
ccl --no-init --load build/quicklisp/setup.lisp                \
             --eval '(ql:write-asdf-manifest-file "build/manifest.ql")'  \
             --eval '(quit)'
mkdir -p build/bin
build/bin/buildapp.ccl      --logfile /tmp/build.log                \
                                                 \
                         --sbcl ccl                            \
                         --asdf-path .                           \
                         --asdf-tree build/quicklisp/local-projects     \
                         --manifest-file build/manifest.ql             \
                         --asdf-tree build/quicklisp/dists              \
                         --asdf-path .                           \
                         --load-system pgloader               \
                         --load src/hooks.lisp                   \
                         --entry pgloader:main                   \
                         --dynamic-space-size 256         \
                                             \
                         --output build/bin/pgloader.tmp
;; loading system "pgloader"
;; loading file #P"/home/rpiadmin/tmp/work/pgloader/src/hooks.lisp"
Fatal error in "buildapp" : Error #<SILENT-EXIT-ERROR #x145E5626>
Makefile:133: recipe for target 'build/bin/pgloader' failed
make: *** [build/bin/pgloader] Error 255
```

**Comment by dimitri** [comment]
Is it possible for you to upload the `/tmp/build.log` file contents, that's where we have the full error message.

**Comment by giminni** [comment]
Here the log output
https://gist.github.com/giminni/68a1793fd4b8b2bc5bfd4bab8af4f8bc

**Comment by dimitri** [comment]
I'm not sure what to think of that build output really :/

**Comment by giminni** [comment]
If I use sbcl 1.3.12 instead,  I could successfully build pgloader.

`$ pgloader --version`
`pgloader version "3.4.e4dca1a"`
`compiled with SBCL 1.3.12`

**Comment by dimitri** [comment]
Nice! Should we close this issue then, maybe?

**Comment by nlevitt** [comment]
Ran into a similar looking issue to my lisp-ignorant eyes (SILENT-EXIT-ERROR in buildapp). Worked around it by renaming the CCL binary to `ccl` as suggested in https://github.com/dimitri/pgloader/issues/541 that seemed to fix the problem. Although the original report at the top here has `CL=ccl`, it would appear to be a different problem.

**Comment by mrPsycho** [comment]
yep. 
first time i tried to use `make CL=/usr/local/bin/ccl64 pgloader`
but it failed.
next i did it:  `ln -s /usr/local/bin/ccl64 /bin/ccl`
and all went fine

**Comment by dimitri** [comment]
Closing the issue then, although to be fair maybe some integration / build work is still necessary. If you know how to make the build experience better please consider re-opening this issue with some clues.
