### ISSUE TITLE
Questions about setting of the concurrency parameter

### ISSUE THREAD

**Issue by Mad-Apes** [dimitri/pgloader#773]
In section 3.5 of the document, There is such a paragraph：

> The N here is setup to the concurrency parameter: with a CONCURRENCY of 2, we start (+ 1 2) = 3 concurrent tasks, with a concurrency of 4 we start (+ 1 4) = 9 concurrent tasks, of which only workers may be active simultaneously.

Questions is how Can we get result 3 and result 9?

And how shoud I set  _`workers`_ and _`concurrency`_?

Best regards, thank you.

**Comment by dimitri** [comment]
It used to be a different computation, where we would start (+ 1 4 4) tasks. Nowadays it's 5, not 9. Thanks for spotting it, it's fixed now in https://github.com/dimitri/pgloader/commit/792c0d0357659e7cceb836feb054a97830e3b7d3. The best way to setup the concurrency in pgloader is still waiting for users feedback. Can you try things and let me know your findings?
