### ISSUE TITLE
CSV import dies after 2.6 millions rows (always)

### ISSUE THREAD

**Issue by yokito99** [dimitri/pgloader#776]
Pgloader version 3.4.1 compiled with SBCL 1.4.0-1.el7
The problem occurs on a centos 7.4 box, SSD drive, 24 core, 48 GB ram running postgres server 9.4

I have a 49GB csv file (on the server) with 92 milion records, 296 columns which are sparsely populated. Regardless, what setting I change pgloader stops after about 2.6 million rows with the following error:

![screenshot from 2018-04-03 11-30-54](https://user-images.githubusercontent.com/38047234/38264734-e915dac8-3741-11e8-9d5d-06e7aa9d2ba4.png)

I have tried different batch sizes, work_mem, maintenance_work_mem settings - other than those 2.6 mill records going in slower or faster, no effect. The config on the postgres servers side is standard, but I have also tried to increase resources there without any effect.
I do not see any postgres server errors on the log other than that checkpoints are occurring too frequently. I had an index on the target table which I dropped. I have plenty space on all file systems, including tmp.

I have run out of ideas. Is there a way to take control of the python GC process? Do I even want to do that?

I'm running this as root. I have read that people are doing largish files. 

  - [ ] pgloader --version
  
    ```
    <fill pgloader version here>
    ```
  
  - [ ] did you test a fresh compile from the source tree?
    
    Compiling pgloader from sources is documented in the
    [README](https://github.com/dimitri/pgloader#build-from-sources), it's
    easy to do, and if patches are to be made to fix your bug, you're going
    to have to build from sources to get the fix anyway…
    
  - [ ] did you search for other similar issues?
    
  - [ ] how can I reproduce the bug?

    Incude a self-contained pgloader command file.

    If you're loading from a database, consider attaching a database dump to
    your issue. For MySQL, use `mysqldump`. For SQLite, just send over your
    source file, that's easy. Maybe be the one with your production data, of
    course, the one with just the sample of data that allows me to reproduce
    your bug.
    
    When using a proprietary database system as a source, consider creating
    a sample database on some Cloud service or somewhere you can then give
    me access to, and see my email address on my GitHub profile to send me
    the credentials. Still open a public issue for tracking and as
    documentation for other users.

```
--
-- EDIT THIS FILE TO MATCH YOUR BUG REPORT
--

LOAD CSV
     FROM INLINE with encoding 'ascii'
     INTO postgresql:///pgloader
     TARGET TABLE jordane

     WITH truncate,
          fields terminated by '|',
          fields not enclosed,
          fields escaped by backslash-quote

      SET work_mem to '128MB',
          standard_conforming_strings to 'on'

   BEFORE LOAD DO
    $$ drop table if exists jordane; $$,
    $$ CREATE TABLE jordane
       (
         "NOM" character(20),
         "PRENOM" character(20)
       )
    $$;

BORDET|Jordane
BORDET|Audrey
LASTNAME|"opening quote
BONNIER|testprenombe~aucouptroplong
JOURDAIN|héhé¶
```

  - [ ] pgloader output you obtain
  
```
PASTE HERE THE OUTPUT OF THE PGLOADER COMMAND
```

  - [ ] data that is being loaded, if relevant
  
```
PASTE HERE THE DATA THAT HAS BEEN LOADED
```

  - [ ] How the data is different from what you expected, if relevant

**Comment by dimitri** [comment]
I believe the current version of pgloader in git will help with your problem, or maybe even just fix it. Please give it a try with the same set of options as now, and then with the `--on-error-stop` option if needed. Compile from sources, test, then report, please!

**Comment by yokito99** [comment]
Thanks!
