### ISSUE TITLE
Can pgloader be used with Transactions?

### ISSUE THREAD

**Issue by SebAlbert** [dimitri/pgloader#778]
I see that a point in the design of pgloader is its resilience against corrupt rows. However, with "on error stop" specified, I don't see why transactions shouldn't be used.

In my use case, I have a meta-data table with one row per imported file, and the imported data table has a foreign key column referencing the row in that meta-data table. I usually use Postgres' CURRVAL on the sequence generating the IDs of the meta-data table rows for this foreign key column, and for that to be correct I need to be inside a transaction.

Does pgloader actually wrap the entire progress inside a transaction with "on error stop"? At least this is an issue regarding the documentation, please be explicit about that in the manual.

**Comment by SebAlbert** [comment]
Thanks for the clarification. So is it possible to have one single transaction by setting concurrency=0? Will this be the very same transaction that is also doing the "BEFORE LOAD" and "AFTER LOAD" SQL statements?

**Comment by dimitri** [comment]
Please review the concurrency settings documentation (athttp://pgloader.readthedocs.io/en/latest/pgloader.html#a-note-about-parallelism), I don't think setting concurrency to 0 makes sense. The BEFORE and AFTER clauses have separate connection handling, so no :/

**Comment by SebAlbert** [comment]
Ah, separate connection handling also explains why I wasn't able to work around this by using temporary tables either. Well, I think I will then resort to writing a small perl (or pure psql) script for my regular CSV imports and keep pgloader in mind for data migration rather than continuous data ingestion in production. Again, thanks for the clarification.
