### ISSUE TITLE
Heap exhausted during garbage collection (200 GB MySQL DB)

### ISSUE THREAD

**Issue by wbenny** [dimitri/pgloader#780]
- [ ] pgloader --version
  
    ```
    3.4.cb9e01f
    ```
  
  - [ ] did you test a fresh compile from the source tree?
    
    not fresh-fresh, but the commit i've built pgloader from is pretty recent and i didn't see a patch which could help me solve my problem
    
  - [ ] did you search for other similar issues?
    yes

  - [ ] how can I reproduce the bug?

    i have MySQL database which contains ~60 tables, output of mysqldump creates 200 GB sql file, the /var/lib/mysql folder has nearly 500 GB (as i use indexes extensively)
```
--
-- EDIT THIS FILE TO MATCH YOUR BUG REPORT
--

LOAD DATABASE
     FROM      mysql://redacted/db
     INTO postgresql://redacted/db

WITH drop schema,
     create tables, create indexes,
     foreign keys, reset sequences,
     workers = 20, concurrency = 20,
     multiple readers per thread, rows per range = 2500
;
```

  - [ ] pgloader output you obtain
  
```
# ./pgloader/build/bin/pgloader pg.script
2018-04-15T18:51:14.146000Z LOG Migrating from #<MYSQL-CONNECTION mysql://redacted/db {100A31FAF3}>
2018-04-15T18:51:14.152000Z LOG Migrating into #<PGSQL-CONNECTION pgsql://redacted/db {100A321693}>
Heap exhausted during garbage collection: 64 bytes available, 192 requested.
 Gen StaPg UbSta LaSta LUbSt Boxed Unboxed LB   LUB  !move  Alloc  Waste   Trig    WP  GCs Mem-age
   0:     0     0     0     0     0     0     0     0     0        0     0 171798691    0   0  0.0000
   1: 273602 460018     0     0  2575 83096     0     0    60 2792687056 14580272 1757987251    0   1  1.4195
   2: 118682 524287     0     0  8115 265165     0     0   136 8911482672 43356368 3520198275 3182   11.1078
   3: 190562 411042     0     0  2910 95782     0     0    71 3217075616 16863840 171798691    1   0  0.0000
   4:     0     0     0     0     0     0     0     0     0        0     0 171798691    0   0  0.0000
   5: 153336 153335     0     0  3406 48095 10475     0   294 2014030800 16798768  2000000 10723   0  0.0000
   6:     0     0     0     0  3461  1208     0     0     0 152993792     0  2000000 3273   0  0.0000
   Total bytes allocated    = 17088269936
   Dynamic-space-size bytes = 17179869184
GC control variables:
   *GC-INHIBIT* = true
   *GC-PENDING* = true
   *STOP-FOR-GC-PENDING* = false
fatal error encountered in SBCL pid 43647(tid 140736134706944):
Heap exhausted, game over.

Welcome to LDB, a low-level debugger for the Lisp runtime environment.
ldb> quit
Really quit? [y] y

```

  - [ ] data that is being loaded, if relevant
  

the database does not consist of anything special - just tables with varchars, texts, integers + one table with date & datetime. also foreign keys, primary keys (sometimes compound) and classic indexes

  - [ ] How the data is different from what you expected, if relevant
 i'd like to convert that huge database without errors :)

also, few notes:
- /var/lib/postgresql grows up to 250 GB of size until the error occurs
- when compiled with `make DYNSIZE=16384 pgloader`, the size of /var/lib/postgresql grew up to 322 GB. i'd love to increase it to higher amounts, but i don't have available more RAM than that. is there any other workaround?
- the process is running for ~1 hour (the /var/lib/postgresql is being filled pretty quickly!)
- i observed that if i try `no foreign keys, create no indexes` then the /var/lib/postgresql is being filled much slower (cca 5-10 orders of magnitude)

**Comment by dimitri** [comment]
Hi,

Sorry that we still have that problem, I though my recent work in the area would bring more success. Anyway, I think that the reason why your var directory doesn't fill up as quickly when `create no indexes` is active is because you have many indexes, and pgloader rebuilds them after each table data is ready.

To work around the problem, you could try to pinpoint if there's one table that is responsible for the exhausted memory situation. Or you can build pgloader with CCL as explained in the INSTALL file, or try the CCL docker image basically.

**Comment by imrantune** [comment]
@dimitri  Hi

me also facing same issue 
Heap exhausted during garbage collection: 15616 bytes available, 17280 requested

**Comment by dimitri** [comment]
Sure, it's easy to do. You have to install CCL first (see https://ccl.clozure.com) and then `make CL=ccl` usually is all you have to do. Sometimes you have to say `make CL=ccl64` to make sure you use the 64 bits version of the CCL compiler and environment, I would go as far as advising you only install that as ccl. The 32 bits series is important to have on some hardware, but maybe not for pgloader on a server (or even a laptop).

**Comment by dimitri** [comment]
@imrantune Have you seen this documentation section yet?

 https://pgloader.readthedocs.io/en/latest/ref/mysql.html#mysql-partial-migration

**Comment by imrantune** [comment]
@dimitri Thank you let me check this one

**Comment by coordt** [comment]
I hope this helps with debugging this issue:

I had a working load configuration that suddenly had an issue when I added the `pgloader` command to a Bash script.

I'm not familiar with memory usage and Bash scripts, but including it in a script seemed to cause the issue for me, and taking it out fixed it.

**Comment by m0n5t3r** [comment]
is there any way to make it like, use the available memory? I'm on a machine with 32 GB of RAM and I can't use more than ~4GB (3.5.2 installed from apt.postgresql.org in this case)

**Comment by dimitri** [comment]
@m0n5t3r this limit is set at compile time in the Lisp image, please see the DYNSIZE option to the Makefile, as detailed in https://github.com/dimitri/pgloader/blob/master/INSTALL.md#building-pgloader-for-use-in-low-ram-environments ; just use a bigger value rather than a lower one.

**Comment by geekq** [comment]
The problem is still there with the newest version @dimitri.

```
pgloader version "3.6.1"
compiled with SBCL 1.4.5.debian
```

pgloader crashes pretty reproducibly with "Heap exhausted, game over" for me, sometimes after 44GB, sometimes after 96GB

```
Heap exhausted during garbage collection: 64 bytes available, 112 requested.

Gen  Boxed Unboxed   LgBox LgUnbox  Pin       Alloc     Waste        Trig      WP GCs Mem-age
 0       0       0       0       0    0           0         0    42949672       0   0  0,0000
 1    2150   24120       0       0   11   858700192   2115168   523398744       0   1  1,3388
 2    3458   36412       0       0   21  1303644768   2815392    42949672    1010   0  1,0613
 3    2006   22731       0       0   21   808513344   2068672    42949672     893   0  0,4646
 4    2039   25510       0       0   20   901116304   1609328    42949672    1215   0  0,5418
 5    1309    8298     250       0   70   321928224   1065952     2000000     226   0  0,0000
 6    1536    1253       0       0    0    88351872   3038080     2000000    1436   0  0,0000
 7       0       0       0       0    0           0         0     2000000       0   0  0,0000
           Total bytes allocated    =    4282254704
           Dynamic-space-size bytes =    4294967296
GC control variables:
   *GC-INHIBIT* = true
   *GC-PENDING* = true
   *STOP-FOR-GC-PENDING* = false
fatal error encountered in SBCL pid 2540(tid 0x7fffed40f700):
Heap exhausted, game over.

Welcome to LDB, a low-level debugger for the Lisp runtime environment.
ldb>
```

```
load database
    from mysql://my_app@myhostname/mydb
    into postgresql://postgres:XXXX@myhostname:5432/mydb
 WITH data only
      , workers = 4
SET MySQL PARAMETERS
    net_read_timeout  = '180',
    net_write_timeout = '120'
cast type int when (= 11 precision) to integer drop typemod,
     type bigint to bigint drop typemod
;
```

Regarding reproducing/debugging. Unfortunately I can not easily provide the data since it is huge and not yet anonymized. But since I started pgloader in a screen session, I still have `ldb>` promt open and can try out whichever commands needed. Unfortunately I do not have any experience in LISP.

P.S. Just compiled 3.6.1 with CCL, will retry and tell, if it makes any difference.

**Comment by dimitri** [comment]
Hi @geekq ; the problem here is with the Garbage Collector, and the one from CCL is much better than the one from SBCL. Another way to work around the issue is to lower the memory pressure by reviewing the batch size parameters and in particular _prefetch rows_, see https://pgloader.readthedocs.io/en/latest/pgloader.html#with.

**Comment by geekq** [comment]
CCL version

    pgloader version "3.6.1"
    compiled with Clozure Common Lisp Version 1.11-r16635  (LinuxX8664)

runs (more slowly?) but for 1.5 hours successful so far. 51 GB on the postgres side.

`top` shows 513 GB virtual memory for pgloader. Is it normal? RES: 375 MB is pretty low though.

And thank you for then Plan B - if problem persists - will use a lower `prefetch rows`, like 5000? since 25000 is the default?

**Comment by geekq** [comment]
Unfortunately CCL version
1. works much slower (6 MByte/s instead of 24 MByte/s on the same VMs, network)
2. crashes too (but not on heap exhaustion) :
```
Unhandled exception 11 at 0x41d990, context->regs at #x7fee073f2678
Exception occurred while executing foreign code
 at set_n_bits + 112
received signal 11; faulting address: 0x307e3fbd5000
invalid permissions for mapped object
? for help
[17980] Clozure CL kernel debugger:
```
