### ISSUE TITLE
Missing Data after migration

### ISSUE THREAD

**Issue by tangoward** [dimitri/pgloader#781]
Hi there,

I am trying to migrate a database from MySQL to PostgreSQL. I ran pgloader and noticed that the tables were copied to my test postgresql database. However when I checked the data for each table, some of the tables have data others don't. 

My pgloader version:
pgloader version "3.2.2"
compiled with SBCL 1.3.1.debian

I tried to build from source to see if I am just getting a bug, but I am stuck at 
sbcl --noinform --no-sysinit --no-userinit --load build/quicklisp/setup.lisp                   \
             --eval '(push "/" ql:*local-project-directories*)' \
             --eval '(ql:quickload "pgloader")'                       \
             --eval '(quit)'

Any suggestions pls?

**Comment by tangoward** [comment]
This issue is now fixed by upgrading to 3.4.1 

However when I try to run the same command `pgloader mysql://root:test12345@localhost postgresql://postgres:postgres@localhost/test_db44` the tables and data are not getting migrated.

I keep on getting 
`2018-04-17T05:24:09.247000Z DEBUG pos: 15 ; err: 15
2018-04-17T05:24:09.247000Z INFO error recovery at 15/29331, processing bad row
2018-04-17T05:24:09.247000Z INFO error recovery at 16/29331, trying 29315 rows
2018-04-17T05:24:09.447000Z ERROR PostgreSQL ["dbname.table_name"] Database error 23502: null value in column "dateupdated" violates not-null constraint`

**Comment by tangoward** [comment]
Read the documentation on how to set the schema. I decided to use a load file which contains a simple code

`LOAD DATABASE
	from 	mysql://root:password12345@localhost/test_db12
	into	postgresql://postgres:postgres@localhost/test_tdc4
SET Postgresql PARAMETERS
	search_path TO 'public'
ALTER SCHEMA 'test_db12' RENAME TO 'public';`

I got an error message
`^CKABOOM!
FATAL error: Interactive interrupt at #x7FFFF71CA4D7.
An unhandled error condition has been signalled:
   Interactive interrupt at #x7FFFF71CA4D7.




What I am doing here?

Interactive interrupt at #x7FFFF71CA4D7.


Waiting for the monitor thread to complete.
`
I accessed the test_tdc4 db in postgres and noticed that the tables and data are there. I am just worried about the FATAL error message.

**Comment by dimitri** [comment]
Can you try `WITH no foreign keys` in your pgloader command? Also, I think the data is migrated into a schema that is not part of the `search_path` in PostgreSQL, and you can change that setting easily. Current versions of pgloader do that for you automatically now, so if you can compile from source that would be better.

**Comment by tangoward** [comment]
Good day Sir Dimitri,

I can't compile from source as I am still stuck in this
`I tried to build from source to see if I am just getting a bug, but I am stuck at
sbcl --noinform --no-sysinit --no-userinit --load build/quicklisp/setup.lisp
--eval '(push "/" ql:local-project-directories)'
--eval '(ql:quickload "pgloader")'
--eval '(quit)'`

I was able to upgrade anyway from 3.2.2 to 3.4.1. I also created a load file and modify the search_path in there. The tables are now in correct database in my postgres however one table has still no data migrated. Also, when I ran the command `pgloader testfile.load`,  my terminal is stuck at `2018-04-17T05:24:09.247000Z DEBUG pos: 15 ; err: 15 2018-04-17T05:24:09.247000Z INFO error recovery at 15/29331, processing bad row 2018-04-17T05:24:09.247000Z INFO error recovery at 16/29331, trying 29315 rows 2018-04-17T05:24:09.447000Z ERROR PostgreSQL ["dbname.table_name"] Database error 23502: null value in column "dateupdated" violates not-null constraint` had to press Ctrl + C after 2 hours of waiting.

**Comment by tangoward** [comment]
Tried to play around `no foreign keys include no drop truncate` but still no good.  Also is it natural for pgloader to stop on this screen `2018-04-17T05:24:09.247000Z DEBUG pos: 15 ; err: 15 2018-04-17T05:24:09.247000Z INFO error recovery at 15/29331, processing bad row 2018-04-17T05:24:09.247000Z INFO error recovery at 16/29331, trying 29315 rows 2018-04-17T05:24:09.447000Z ERROR PostgreSQL ["dbname.table_name"] Database error 23502: null value in column "dateupdated" violates not-null constraint`? 
I also tail -f the log of postgresql, basically I was expecting to see this line for the table that has missing data `2018-04-19 15:43:44 +08 [7998-81] postgres@test_mig1 STATEMENT:  
	copy public.voidreceipts ` but I didn't.

Apologies for sounding dump, I'm a newbie.

**Comment by tangoward** [comment]
All right, managed to successfully fix the issue on missing data. Now I am still facing the 21 errors which are all related to this `2018-04-17T05:24:09.247000Z DEBUG pos: 15 ; err: 15 2018-04-17T05:24:09.247000Z INFO error recovery at 15/29331, processing bad row 2018-04-17T05:24:09.247000Z INFO error recovery at 16/29331, trying 29315 rows 2018-04-17T05:24:09.447000Z ERROR PostgreSQL ["dbname.table_name"] Database error 23502: null value in column "dateupdated" violates not-null constraint`

**Comment by tangoward** [comment]
I checked the DateUpdated field in mysql and noticed that the 21 erros have default value of 0000-00-00. When I checked the documentation of 3.4.1, it says that this 
`type date when default "0000-00-00" to date drop default
using zero-dates-to-null` does this mean that it should work?

**Comment by cbandy** [comment]
> managed to successfully fix the issue on missing data.

@tangoward what did you do to get past this? I think I'm experiencing something similar.

I can see that, of 25207 total rows, 2127 rows in my table have `updated_date is null`. PGLoader emits
```
2018-04-27T19:56:56.097000Z ERROR Database error 23502: null value in column "updated_date" violates not-null constraint
```
but the summary reports zero errors and 25207 imported.

In postgres, the table is entirely empty.

```
pgloader version "3.4.ea6c91b"
compiled with SBCL 1.3.14.debian
```

**Comment by cbandy** [comment]
I was able to reproduce this on the master branch. I've opened #792 with details.
