### ISSUE TITLE
pgloader error

### ISSUE THREAD

**Issue by gkluczyn** [dimitri/pgloader#783]
HI All,
I was wondering if you could help with the following
we get an error on executing the below:

```
pgloader -v mysql://xxx:yyyy@localhost/ovol7g4iprd postgresql://zzzz:somepass@dtxlae-ovol7g4iprd-4-dtxlae.cloudapps.xxx.com:38606/ovol7g4iprd
```

error:

```
2018-04-18T08:08:40.314000Z ERROR Database error 42601: syntax error at or near "Y"
QUERY: CREATE TABLE f_sharehierarchy 
(
  cachekey               bigint not null,
  sharehierarchyid       bigint not null,
  statusaccess           text default NULL,
  sales_hierarchy_key    bigint not null,
  parentnodeid           bigint default NULL,
  node_name              text default NULL,
  node_start_date        date default NULL,
  node_end_date          date default NULL,
  sales_hierarchy_level   bigint default NULL,
  level_path_name        text default NULL,
  level_1_name           text default NULL,
  level_2_name           text default NULL,
  level_3_name           text default NULL,
  level_4_name           text default NULL,
  level_5_name           text default NULL,
  level_6_name           text default NULL,
  scms_name              text default NULL,
  sub_scms_name          text default NULL,
  country_name           text default NULL,
  cloud_offset_node_yorn   varchar(1) default NULL,
  united_states_yorn     varchar(1) default NULL,
  country_type           text default NULL,
  transformational_account_key   bigint default NULL,
  default_iso_currency_code   text default NULL,
  supergroup_key         bigint default NULL,
  sales_node_led_by      text default NULL,
  salescountrycleaned    text default NULL,
  pure_overlay           text default NULL,
  segment1               text default NULL,
  cvmarketvalue          text default NULL,
  externaltheater        text default NULL,
  donotrestate           text default NULL,
  attributeaaccessnode   text default NULL,
  node_mapping_string    text default NULL,
  lastrefreshtime        timestamptz default NULL,
  nodeownedmanager       varchar(1) not null default ''Y''
```

thanks in advance

greg

**Comment by dimitri** [comment]
Hi @gkluczyn ; which version of pgloader are you using? I think I remember about this kind of bugs, and I believe the current version (build from fresh sources) doesn't have the bug anymore.

**Comment by gkluczyn** [comment]
HI @dimitri 

thanks for the response. Our version is: \pgloader version "3.2.2"
I will upgrade to 3.4.1 and check for the error.

thanks,
greg

**Comment by gkluczyn** [comment]
I get the following 
> apt-get install pgloader
Reading package lists... Done
Building dependency tree
Reading state information... Done
pgloader is already the newest version (3.2.2+dfsg-1).
The following packages were automatically installed and are no longer required:
  linux-headers-4.4.0-116 linux-headers-4.4.0-116-generic
  linux-image-4.4.0-116-generic
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 14 not upgraded.

so cannot install 3.4.1

**Comment by gkluczyn** [comment]
HI @dimitri

Is there a way of forcing 3.4.1 installation?

thanks,
greg

**Comment by dimitri** [comment]
The easiest path forward is to compile pgloader from sources. In the case when your bug is fixed already but not packaged, you're going to have to do that anyway.
