### ISSUE TITLE
RPM build broken

### ISSUE THREAD

**Issue by snhirsch** [dimitri/pgloader#784]
Title says it.  I clone the repository today (2018-04-10), then:

- Executed bootstrap-centos7.sh
- "make rpm"

It fails because:

1. You have the wrong version in the pgloader.spec file (should be 3.4.2)
2. The pgload.md.1 file is missing

I edited the spec file to correct the version and removed 'pgload.md.1' from the doc target and it builds to completion.

You may want to address this.  Would actually be optimal if you could release 3.4.2 as an official RPM.

**Comment by dimitri** [comment]
Hi, I need to work on the next release, that's true. Can you share your improvements, maybe as a Pull Request, so that I can include them in pgloader? Thanks!

Also, about the docs, I don't know how to build a manpage from the sphinx/rest docs that I have now. Didn't think it would be important to still do that...

**Comment by snhirsch** [comment]
It may not be important to create the man page, but if it's officially eliminated, the RPM spec file (and perhaps debian control) should be updated accordingly.  

My changes were so trivial that it's not worth the effort of a development fork:

1. Change 'Version' on line 3 of pgloader.spec to agree with the version defined at the top of the Makefile.
2. Remove 'pgloader.md.1' from the '%doc' statement in pgloader.spec (line 38)

One further observation:  The binary I built from source yesterday exhibits annoying behavior in its naming of the output results directory.  The most current release (3.4.1) creates a subdirectory using the table name forced to lower case.  The latest devel build creates a subdirectory with double-quotes around the name and (from memory) files within it that also have double-quotes around their names.  I'm sure this is a simple fix, but I haven't looked at LISP since my undergraduate days 25 years ago and don't feel adventurous enough to dive in.

**Comment by dimitri** [comment]
Just dive in, you might like it and I'll be happy to merge your patches!

**Comment by snhirsch** [comment]
Heh, I have enough tasks to occupy my time at the moment.  Maybe someday.  But, seriously, that directory + file naming issue is an obvious regression and probably a quick fix for you (since you know exactly where to look in the code).
