### ISSUE TITLE
DB2 export format escape double quote issue parsing CSV

### ISSUE THREAD

**Issue by prenagha** [dimitri/pgloader#787]
DB2 CSV export with `,` as the delimiter, and `"` enclosing values, it also uses `"` as the escape character

So for example, if I export from DB2, three columns, first an integer value 0, second a string value N, and third a string value of `"SYSIBM"."BLOB"('')`    <-- the double quotes are part of the value
it gets exported by DB2 to CSV as `0,"N","""SYSIBM"".""BLOB""('')"`  <-- db2 escapes the double quotes in the value as `""`

If I try and load that with pgloader I get error `FATAL non whitespace after quoted data #<CSV-READER LINE-IDX:...`

My pgloader command is something like
```
/usr/local/bin/pgloader \
   --type csv \
   --field "counter" \
   --field "flag [trim both whitespace]"  \
   --field "default_value [trim both whitespace]"  \
   --with truncate \
   --with 'drop indexes' \
   --with "fields terminated by ','" \
   ./systables.csv \
   "${DB}?tablename=db2tables"
```

`pgloader --version / pgloader version "3.4.1" / compiled with SBCL 1.4.4`

I tried experimenting with `csv escape mode following` but that didn't seem to help

Any ideas or pointers?

**Comment by dimitri** [comment]
It seems that you're missing the CSV option `fields escaped by double-quote`, which I think is the default nowadays. See the attached patch where I updated the sample data to show that it works in your case.

**Comment by prenagha** [comment]
Hmmm, I guess I didn't try manually setting `fields escaped by double-quote` since the doc says that is the default. I will try setting it manually and seeing if that works. Thanks.
