### ISSUE TITLE
Requesting help on pgloader from shell script

### ISSUE THREAD

**Issue by ChikkySharma** [dimitri/pgloader#793]
Hi Dimitri,

I am trying to use "pgloader"(Postgres dB) instead of "sqlload"(Oracle dB) to load a CSV file (captured into pipe "pipe.dat") to the Postgres dB. This is done in shell script.

Usage of sqlload:
```
sqlload username/pswd data=$dir/data/pipe.dat 
control=$dir/ctl/bmast.ctl 
log=$dir/log/bmast.log 
bad=$dir/bad/bmast.bad
```

Could you please advise how to use "pgloader" to perform the same task.

I tried the below,

```
pgloader data=$dir/data/pipe.dat 
control=$dir/ctl/bmast.ctl 
log=$dir/log/bmast.log 
bad=$dir/bad/bmast.bad
```

But it throws me the below error,

```
FATAL error: No such file or directory: "data=$dir/data/pipe.dat"
No such file or directory: "control=$dir/ctl/bmast.ctl"
No such file or directory: "log=$dir/log/bmast.log"
No such file or directory: "bad=$dir/bad/bmast.bad"

debugger invoked on a SB-INT:SIMPLE-FILE-ERROR in thread
#<THREAD "lparallel" RUNNING {1004C00623}>:
error opening #P"/tmp/pgloader/pgloader.log": Permission denied
```

Please advise.

Thanks

**Comment by dimitri** [comment]
Did you try reading pgloader's documentation? The project has no intend to be compatible with SQLloader at all, so the usage is different, though you may obtain the same results.
