### ISSUE TITLE
The alien function "CRYPTO_num_locks" is undefined.

### ISSUE THREAD

**Issue by craig-day** [dimitri/pgloader#794]
It seems there is something wrong with the OpenSSL version being used by MacOS. This might be related to system integrity stuff in MacOS which prevents any user, even root, from modifying `/usr/bin/openssl`, so its impossible (well, very dangerous) to update the version of OpenSSL via Homebrew. 

Would it be possible to provide a compile-time flag in pgload allowing the user to specify the path to the openssl binary to use? I believe you can do this with `curl` and compile it with the `--with-ssl=/path/to/ssl/bin` option. 

  - [ ] pgloader --version
  
    ```
    pgloader version "3.4.1fe835d"
    compiled with SBCL 1.4.7
    ```
  
  - [ ] did you test a fresh compile from the source tree?
    
    yes, I compiled on MacOS with Homebrew using the `--HEAD` flag
    
  - [ ] did you search for other similar issues?

    Yes, but they were just about compiler warning, not runtime errors. 

  - [ ] how can I reproduce the bug?

This is when trying to load data into a Heroku database. Heroku requires you to enable SSL to connect from outside of their network. 

```
pgloader 
  --cast 'type int to int drop typemod' 
  --cast 'type bigint to int drop typemod' 
  --cast 'type int with extra auto_increment to serial drop typemod' 
  --dry-run 
  'mysql://root@127.0.0.1:3306/database' 
  'postgres://user:password@my.heroku.database:5432/database?sslmode=require'
```

  - [x] pgloader output you obtain
  
```
KABOOM!
FATAL error: Failed to connect to pgsql at "myserver.address" (port 5432) as user "user": The alien function "CRYPTO_num_locks" is undefined.
An unhandled error condition has been signalled:
   Failed to connect to pgsql at "myserver.address" (port 5432) as user "user": The alien function "CRYPTO_num_locks" is undefined.
```

**Comment by dimitri** [comment]
We have several other issues with openssl dynamic linking at run-time. I would like to be able to handle them better, but I don't know how to do that currently...

**Comment by BrandonZacharie** [comment]
I'm getting the same issue trying to load data into a Heroku database.

**Comment by rkhaotix** [comment]
I'm facing the same issue too.

My environment:
```openSuse Leap 15
OpenSSL 1.1.0i-fips  14 Aug 2018
SBCL 1.4.15 (compiled manually)```

**Comment by dimitri** [comment]
Hi @rkhaotix, which version of pgloader? Did you try compiling current master's from sources?

**Comment by rkhaotix** [comment]
Hi! Yeah... as you told, the commit is already on my fork. I recompiled pgloader and tried to run it again but the error about undefined function still persists. :(

**Comment by dimitri** [comment]
Closing the issue now.
