### ISSUE TITLE
SQLite auto-increment is not respected

### ISSUE THREAD

**Issue by Nihlus** [dimitri/pgloader#802]
```
pgloader version "3.4.1"
compiled with SBCL 1.3.1.debian
```
  
  - [x] did you test a fresh compile from the source tree?
    
    I did, but was unable to test it due to #800.
    
  - [x] how can I reproduce the bug?

```
load database
	from 'repro.sqlite'
	into postgresql://pgloader

with include drop, create tables, create indexes, reset sequences
set work_mem to '200MB', maintenance_work_mem to '512 MB';
```
[repro.sqlite.zip](https://github.com/dimitri/pgloader/files/2041935/repro.sqlite.zip)

  - [x] pgloader output you obtain
  
[repro.log](https://github.com/dimitri/pgloader/files/2041934/repro.log)

When attempting to import an SQLite database with auto-incremented primary keys, the auto-increment is not respected, and a sequence is not created. I've included both a database file that reproduces the issue (created via DataGrip) and the resulting database (below, dumped via pg_dump).

[repro.sql.zip](https://github.com/dimitri/pgloader/files/2041938/repro.sql.zip)

**Comment by Nihlus** [comment]
I just now realized that this extends to foreign keys as well. Indexes are transferred.

**Comment by Nihlus** [comment]
Rolling back to the 3.5.1 release has fixed most of these issues. However, no auto-increment sequences are created for empty tables.

**Comment by dimitri** [comment]
I just tried and failed to reproduce any problem here. Once migrated, the schema in PostgreSQL looks like the following:

```
pgloader# \d public.users
                            Table "public.users"
 Column │  Type  │ Collation │ Nullable │              Default              
════════╪════════╪═══════════╪══════════╪═══════════════════════════════════
 id     │ bigint │           │ not null │ nextval('users_id_seq'::regclass)
 name   │ text   │           │          │ 
Indexes:
    "idx_273650_users_id_uindex" PRIMARY KEY, btree (id)
```
