### ISSUE TITLE
mmap: Can not allocate memory

### ISSUE THREAD

**Issue by pgbtek** [dimitri/pgloader#804]
Hello,
I am using "pgloader" version 3.4.1.
My OS is CentOS 7.2 (in Virtual Machine environment).
It seems that "pgloader" needs at least 4GB of RAM to run, but I did not find any prerequisite in the reference manual. Or maybe it is already specified in LISP language.
I tested with different cases of RAM 1GB, 2GB and 3GB, and got the following error :
```
[root] # /usr/bin/pgloader --version
mmap: Can not allocate memory
fatal error encountered in SBCL pid 1285(tid 0x7ffff7fe8740):
Won't map dynamic space below immobile space
```
And finally with 4GB of RAM, it works :
```
[root] # /usr/bin/pgloader --version
pgloader version "3.4.1"
compiled with SBCL 1.4.0-1.el7
```
Is this the minimum of RAM (4GB) that I should recommend to my users for "pgloader"?
Or do I need additional Kernel configuration with less than 4GB for "pgloader"?
Regards

**Comment by dimitri** [comment]
This memory usage is configured in the makefile, and happens at build time. See https://github.com/dimitri/pgloader/blob/master/INSTALL.md#building-pgloader-for-use-in-low-ram-environments

**Comment by BitBargain** [comment]
# free -h
              total        used        free      shared  buff/cache   available
Mem:           31Gi       5.1Gi       2.4Gi       799Mi        23Gi        25Gi
Swap:         2.0Gi        14Mi       2.0Gi

mmap: Cannot allocate memory
fatal error encountered in SBCL pid 22036(tid 0x7f70b5fc92c0):
Can't allocate 0x100000000 bytes for space 1

Before the last reboot, using the simple method of pgloader mysql://x postgresql://x worked, so did using the load file. Now it just quits, citing not enough memory, sometimes citing zlib. Meanwhile there's 25G available. Am I missing something?
