### ISSUE TITLE
Undefined alien: "SSL_get_version" (and other)

### ISSUE THREAD

**Issue by rmayhue** [dimitri/pgloader#807]
- [x] pgloader --version
```
pgloader version "3.5.7220fc2"
compiled with SBCL 1.3.1.debian
```
  
  - [x] did you test a fresh compile from the source tree?
    
    Yes
    
  - [x] did you search for other similar issues?
   
    Yes - Found closed issue but decided to open a new issue.
    
  - [x] how can I reproduce the bug?
```
load database
    from mssql://<ms_user>:<ms_password>@<ms_host>/<ms_db>
    into postgresql://<pg_user>:<pg_password>@<pg_host>:5433/<pg_db>

set work_mem to '256MB', maintenance_work_mem to '512MB'

ALTER SCHEMA 'dbo' RENAME TO 'public';
```

  - [x] pgloader output you obtain
  
```
$ pgloader ./migrate.load
KABOOM!
FATAL error: Undefined alien: "SSL_get_version"
An unhandled error condition has been signalled:
   Undefined alien: "SSL_get_version"




What I am doing here?

Undefined alien: "SSL_get_version"
```
  - [x] How the data is different from what you expected, if relevant

I've built `pgloader` on ubuntu 16.04.4 LTS & 18.04 LTS with the same outcome.  Different versions of OpenSSL etc.  I've tried `pgloader-bundle-3.5.1` as well.

If I install `pgloader` via `apt install pgloader` on 16.04.4 - then I get this error:
```
$ pgloader --version
pgloader version "3.4.1"
compiled with SBCL 1.3.1.debian
```
```
$ pgloader ./migrate.load
Max connections reached, increase value of TDS_MAX_CONN
KABOOM!
FATAL error: %dbsqlexec fail
An unhandled error condition has been signalled: %dbsqlexec fail




What I am doing here?

%dbsqlexec fail


Waiting for the monitor thread to complete.
```

If I install `pgloader` via `apt install pgloader` on 18.04 - then I get this error:
```
pgloader --version
pgloader version "3.4.1"
compiled with SBCL 1.3.3.debian
```
```
$ pgloader ./migrate.load
Max connections reached, increase value of TDS_MAX_CONN
Max connections reached, increase value of TDS_MAX_CONN
Max connections reached, increase value of TDS_MAX_CONN

debugger invoked on a SIMPLE-ERROR in thread
#<THREAD "lparallel" RUNNING {100A0F6623}>:
  not supported type SYB-MSDATETIME2
```
`pgloader` will hang indefinitely at this point until ^C then outputs this:
```
^CKABOOM!
FATAL error: Interactive interrupt at #x7FFFF7121837.
An unhandled error condition has been signalled:
   Interactive interrupt at #x7FFFF7121837.




What I am doing here?

Interactive interrupt at #x7FFFF7121837.


Waiting for the monitor thread to complete.
```

I've installed `pgloader version "3.5.1~devel"` via brew on Mac OS X El Capitan and it hung until ^C as above.

As you can see I've tried multiple OSes and versions and keep hitting snags. :(

**Comment by dimitri** [comment]
The OpenSSL situation is a problem that I'm not sure how to handle. It might be possible to review the way pgloader is built entirely in order to solve it, making it so that the ssl loading happens from the ELF section of the binary itself rather than by `dlopen` later. But I still have to understand how to make that happen, and it might not be a solution after all. I need help on that point.

The message `Max connections reached, increase value of TDS_MAX_CONN` is coming from the `freetds` library and there's nothing to do about it from pgloader as far as I understand. See how to setup TDS and maybe some server-side tuneable on MS SQL would help too. You can also review your pgloader concurrency settings to make it so that pgloader does less parallel work.

Finally, the “hang” situation needs more information for me to be able to review and debug it... can you try running with the `--debug` option and see if we get something relevant to fix the issue?

**Comment by jeffreyvdhondel** [comment]
I am having the same issue with the docker from @dimitri when i try to migrate a mssql to postgress server and get the same error "Undefined alien: "SSL_get_version""

**Comment by jeffreyvdhondel** [comment]
When i use the following command in my docker.
"tsql -H 192.168.240.127 -p 1433 -U test -P test1234 -D [Removed]"

I can connect to the mssql server but when i try this with pgloader.
With the following load file.

`load database
 from mssql://test:test1234@192.168.240.127:1433/[Removed]
 INTO postgresql://DBA@192.168.240.127:5432/[Removed]

SET client_encoding to 'utf8'
SET work_mem to '16MB', maintenance_work_mem to '512 MB'

CAST type uuid to uuid   
                drop default drop not null using zero-dates-to-null,  
      type date drop not null drop default using zero-dates-to-null  

cast column Artikel.publicidentifier to uuid drop typemod

including only table names like '[Removed]' in schema 'dbo'

ALTER SCHEMA 'dbo' RENAME TO 'public'

before load do $$ drop schema if exists dbo cascade; $$;
`

I get the SSL_get_version error just like @rmayhue.

**Comment by dimitri** [comment]
@jeffreyvdhondel any information to share about how you compiled/installed pgloader?

**Comment by jeffreyvdhondel** [comment]
We used you docker container.
To migrate a mssql 2012 to postgres 9.6

**Comment by jeffreyvdhondel** [comment]
We have it working now with a docker file we made ourselfs.
The only problem it uses the apt-get pgloader version. This is version 3.4.1.

```
FROM ubuntu:18.04

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
ADD . /app

RUN apt-get update \ 
                        && apt-get install -y sbcl nano  locales    \
                        git curl wget patch unzip                   \
                        devscripts pandoc                           \
                        libsqlite3-dev                              \
                        freetds-dev freetds-bin openssl             \
                        pgloader
#     # && rm -rf /var/lib/apt/lists/* 
RUN ./install.sh
```
Install.sh script

```
#!/bin/sh
locale-gen en_US.UTF-8
export LC_ALL="en_US.UTF-8"

```

We really want to have the latest version of pgloader inside a docker.

**Comment by dimitri** [comment]
What about building from sources in your docker container?

**Comment by jeffreyvdhondel** [comment]
Used the above docker file but add make and git. 
git cloned the source and build the script

Build from source successfully --version
```
pgloader version "3.5.7220fc2"
compiled with SBCL 1.4.5.debian
```

But still the same error when trying to migrate the server.

```
KABOOM!
FATAL error: Undefined alien: "SSL_get_version"
An unhandled error condition has been signalled:
   Undefined alien: "SSL_get_version"




What I am doing here?

Undefined alien: "SSL_get_version"
```

**Comment by alex-t0** [comment]
Is any solution for Undefined alien: "SSL_get_version"?
I get same error on ubuntu 18.04 after compiling from source by instruction.

**Comment by derfloscher** [comment]
same problem inside docker sadly. We are dependent on building from scratch so any pointers would be much appreciated

**Comment by lubo** [comment]
Downgrading OpenSSL to version 0.9.8zh helped.

**Comment by devrimgunduz** [comment]
@dimitri Just a FYI: This issue occured in 3.5.2 on RHEL 7 and Fedora's, but upgrading to 3.6.0 helped.

I'll upgrade the packages to 3.6.1 as soon as you release them (I'm not updating to 3.6.0, as you marked it as a pre-release)

**Comment by dimitri** [comment]
Thanks @devrimgunduz; your comment allows me to check one more item towards making the 3.6.1 release!

**Comment by Siim** [comment]
Had the same error with Ubuntu bionic

```
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```
To fix the issue, I needed to:

1. install the cl-plus-ssl
```
apt install cl-plus-ssl
```
2. build the pgloader again

**Comment by sorix6** [comment]
Hi @Siim! What version of Pgloader did you use? I have installed cl-plus-ssl but still get the error

**Comment by Siim** [comment]
```
./pgloader-master/build/bin/pgloader -V
pgloader version "3.6.2~devel"
compiled with SBCL 1.4.5.debian
```

Compiled the code from master branch.
