### ISSUE TITLE
bad data file generation

### ISSUE THREAD

**Issue by s-kotian** [dimitri/pgloader#808]
Hello,

I am using pgloader version 3.5.1. I want to capture the bad data present in the csv file. The .dat file generated under /tmp contains quotes in the file name (  "schemaname"."tablename".dat )

Is there a way to eliminate the quotes while generating the file ?

pgloader --version
pgloader version "3.5.1"
compiled with SBCL 1.4.0-1.el7

**Comment by dimitri** [comment]
Thanks for the report, should be fine now! You can test by building from fresh sources and trying again.
