### ISSUE TITLE
Error "column c.conindid does not exist" when copying data

### ISSUE THREAD

**Issue by gitstashgithub** [dimitri/pgloader#813]
- [X] pgloader --version
  
```
    pgloader version "3.5.1~devel"
    compiled with SBCL 1.3.1.debian
 ```
  
  - [X] did you test a fresh compile from the source tree?
    
  - [X] did you search for other similar issues?
    
  - [X] how can I reproduce the bug?
I am trying to copy database data from AWS RDS to Redshift, and get this issue.

the `./build/bin/pgloader --debug schema.load` was success and all tables have been created in Redshift. But the `./build/bin/pgloader --debug data.load` doesn't work.

```
 load database
     from      mysql://
     into postgresql://

WITH data only, truncate, create no tables, downcase identifiers,
     concurrency = 1, workers = 2, prefetch rows = 50000

SET search_path to 'database'

 CAST type datetime to timestamptz
                drop default drop not null using zero-dates-to-null,
      type date drop not null drop default using zero-dates-to-null

 BEFORE LOAD DO
 $$ create schema if not exists database; $$;

```

  - [X] pgloader output you obtain
  ./build/bin/pgloader --debug data.load
```
2018-07-04T00:59:07.552000Z ERROR Database error 42703: column c.conindid does not exist
QUERY: -- params: including
--         filter-list-to-where-clause for including
--         excluding
--         filter-list-to-where-clause for excluding
  select n.nspname,
         i.relname,
         i.oid,
         rn.nspname,
         r.relname,
         indisprimary,
         indisunique,
         pg_get_indexdef(indexrelid),
         c.conname,
         pg_get_constraintdef(c.oid)
    from pg_index x
         join pg_class i ON i.oid = x.indexrelid
         join pg_class r ON r.oid = x.indrelid
         join pg_namespace n ON n.oid = i.relnamespace
         join pg_namespace rn ON rn.oid = r.relnamespace
         left join pg_constraint c ON c.conindid = i.oid
                                  and c.conrelid = r.oid
                                  -- filter out self-fkeys
                                  and c.confrelid <> r.oid
   where n.nspname !~ '^pg_' and n.nspname <> 'information_schema'
         and ((rn.nspname = 'primeuat' and r.relname ~ '^table1$')
           or (rn.nspname = 'primeuat' and r.relname ~ '^table2$')
           or (rn.nspname = 'primeuat' and r.relname ~ '^and_lots_of_tables$')

order by n.nspname, r.relname
2018-07-04T00:59:07.557000Z FATAL Failed to create the schema, see above.

```
I guess it's because Redshift's postgresql version is too low and it does't have pg_constraint.conindid column. Is there a way to get around this error? Thanks!

Gordon

**Comment by dimitri** [comment]
That's because when we do `data only`, then we need to fetch catalogs from the target database, here a Redshift instance. And the code isn't ready yet to do that, because the use case I had when developing the support for Redshift didn't exercise that part of the code. I need to work some more there...

I suppose the problem simply is that Redshift doesn't support Foreign Keys, right?

**Comment by gitstashgithub** [comment]
I just tested and found Redshift does support Foreign keys.

It made me find another issue that even schema.load file has `WITH schema only, drop schema, create indexes, foreign keys, downcase identifiers`, all the indexes and foreign keys are not created in Redshift. I can still manually create them in Redshift though.

**Comment by gitstashgithub** [comment]
Below is the Redshift pg_constraint table structure:
```
                        Table "pg_catalog.pg_constraint"
    Column     |    Type    | Modifiers | Storage  | Stats target | Description
---------------+------------+-----------+----------+--------------+-------------
 conname       | name       | not null  | plain    |              |
 connamespace  | oid        | not null  | plain    |              |
 contype       | "char"     | not null  | plain    |              |
 condeferrable | boolean    | not null  | plain    |              |
 condeferred   | boolean    | not null  | plain    |              |
 conrelid      | oid        | not null  | plain    |              |
 contypid      | oid        | not null  | plain    |              |
 confrelid     | oid        | not null  | plain    |              |
 confupdtype   | "char"     | not null  | plain    |              |
 confdeltype   | "char"     | not null  | plain    |              |
 confmatchtype | "char"     | not null  | plain    |              |
 conkey        | smallint[] |           | extended |              |
 confkey       | smallint[] |           | extended |              |
 conbin        | text       |           | extended |              |
 consrc        | text       |           | extended |              |
Indexes:
    "pg_constraint_oid_index" UNIQUE, btree (oid)
    "pg_constraint_conname_nsp_index" btree (conname, connamespace)
    "pg_constraint_conrelid_index" btree (conrelid)
    "pg_constraint_contypid_index" btree (contypid)
Replica Identity: ???
Has OIDs: yes
```

**Comment by dimitri** [comment]
What I meant is this: https://docs.aws.amazon.com/redshift/latest/dg/c_best-practices-defining-constraints.html

> Do not define primary key and foreign key constraints unless your application enforces the constraints. Amazon Redshift does not enforce unique, primary-key, and foreign-key constraints.

**Comment by tendres** [comment]
Can confirm Redshift supports but does not enforce constraints.

Not sure if this helps but I am closely following issue [#806](https://github.com/dimitri/pgloader/issues/806) and saw support for loading data into redshift.
I decided to point my successful postgres .loader script to redshift to see how far I could get and am encountering a similar issue but getting there in a different way.

Using 3.5.1~devel

```LOAD CSV
   FROM stdin
        (
        export_date,
        artist_id,
        name,
        is_actual_artist,
        view_url,
        artist_type_id
        )
   INTO postgres://user:redshift-address:5439/test_table?tablename=schema_name.artist
        (
        export_date,
        artist_id,
        name,
        is_actual_artist,
        view_url,
        artist_type_id
        )
   WITH truncate,
   	drop indexes,
        skip header = 34,
        fields not enclosed,
        keep unquoted blanks,
        fields terminated by '0x01',
        lines terminated by '0x02'
;
```
As seen above this fails with `ERROR Database error 42703: column c.conindid does not exist`.
Running the failing query back on postgres lists constraints and indexes (a PK and a GIN index in my case).
Replacing `drop indexes` with `create no indexes` fails as the latter does not appear to be recognized as a valid WITH argument when using CSVs.

feels like it is pretty close...
Could this approach ever work or will the source always need to be a postgres db?

**Comment by dimitri** [comment]
@tendres I tried the following blind fix: https://github.com/dimitri/pgloader/commit/cb633aa092e83aa95b1e0483d6d6ce731bf6bdfe ; it refrains from doing too much catalog introspection when the source/target database is a non-PGDG PostgreSQL variant. Redshift isn't a PGDG variant, so with some luck your use case is now completely covered. Wanna try and let me know?

**Comment by tendres** [comment]
@dimitri  Things look a little better but ran into the following error:
```
2018-08-20T18:54:42.865000Z ERROR Database error 42883: function regexp_match(text, "unknown") does not exist
HINT: No function matches the given name and argument types. You may need to add explicit type casts.
QUERY: -- params: table-type-name
--         including
--         filter-list-to-where-clause for including
--         excluding
--         filter-list-to-where-clause for excluding
with seqattr as...
```
Thinking this might have to do with including/excluding tables names?
Let me know if there is any more information I can provide.
Thanks!

**Comment by dimitri** [comment]
Should be better now, I hope Redshift has the `substring(... from ...)` function variant though.

**Comment by tendres** [comment]
@dimitri Still choking in that same section:
```
2018-08-24T21:59:19.337000Z ERROR Database error 42846: cannot cast type text to regclass
QUERY: -- params: table-type-name
--         including
--         filter-list-to-where-clause for including
--         excluding
--         filter-list-to-where-clause for excluding
with seqattr as...
```

Not sure if this is related but no solution provided - maybe a hint in there somewhere:
<https://stackoverflow.com/questions/48300826/redshift-schema-tableregclass-works-but-t-schema-t-nameregcla>

**Comment by dimitri** [comment]
I will need the full error message from Redshift and I think I will also need access to an environment from where I can reproduce the errors.

**Comment by tendres** [comment]
Email sent with environment credentials and error.
Let me know what else you need - thanks!

**Comment by dimitri** [comment]
Please try again with attached patch, I believe it should fix the problems now. Note that the original query was still a problem. It's the query used to introspect the list of indexes, and we join to `pg_constraint` in order to know if the index is created to support a constraint such as a PRIMARY KEY or otherwise. Using `pg_depend` now.

**Comment by silemarc** [comment]
I get the same error from linux mint 18.1 and  greenplum on db side.

**Comment by dimitri** [comment]
Hi @silemarc ; please upgrade your version of pgloader to get the bug fix. You can use https://wiki.postgresql.org/wiki/Apt or compile from sources, either a git clone or the bundle release on Github.
