### ISSUE TITLE
import into existing schema (not public) problems

### ISSUE THREAD

**Issue by didwi** [dimitri/pgloader#816]
Hello,
Actually I need to import a mysql database called "rde" into:
1) postgresql "esrde" database
2) into the already existing schema "esrde_sch" whose owner is esrde_dml (which is the role I can use).

PGLOADER tries to delete and recreate the schema every time. I don't have the rights to drop and or recreate the esrde_sch schema!  All I can do is drop objects within the esrde_sch schema, but I cannot drop the schema itself.

  - [ ] pgloader --version
  
  pgloader --version
  pgloader version "3.4.1"
  compiled with SBCL 1.3.3.debian  
  
- [ ] did you test a fresh compile from the source tree?
No, running a copy under windows 10 (ubuntu wsl)
    
    Compiling pgloader from sources is documented in the
    [README](https://github.com/dimitri/pgloader#build-from-sources), it's
    easy to do, and if patches are to be made to fix your bug, you're going
    to have to build from sources to get the fix anyway…
    
  - [ ] did you search for other similar issues?
Yes
    
  - [ ] how can I reproduce the bug?
   Here is our postgresql config which I cannot change (unfortunately):
--- THIS environment is already setup for me and I can _not_ modify or drop these settings ----
```
   create role esrde_db;
   create role esrde_dml;
   create database esrde encoding=utf8;
   revoke all on database esrde from public;
   \c esrde;
  drop schema public;
  alter database esrde owner to esrde_db;
  alter schema esrde_sch owner to esrde_dml;
  create schema esrde_sch;
  create user aaa123 login encrypted password 'xyz' in role esrde_dml;
```

I'm not a DBA so I cannot change this config !

Here is my pgloader file:

```
LOAD DATABASE
        FROM mysql://root@127.0.0.1/rde
        INTO postgresql://aaa123@192.168.100.100/esrde

WITH on error stop, include drop, create tables, create indexes, reset sequences, foreign keys,
      workers = 8, concurrency = 1,
      multiple readers per thread, rows per range = 50000

SET PostgreSQL PARAMETERS
      search_path to 'esrde_sch',
      role to 'esrde_dml',
      maintenance_work_mem to '128MB',
      work_mem to '12MB'

CAST type bigint to bigint drop typemod;
```

```
--
-- EDIT THIS FILE TO MATCH YOUR BUG REPORT
--
2018-07-23T14:55:22.024000Z NOTICE Starting pgloader, log system is ready.
2018-07-23T14:55:22.453000Z NOTICE Prepare PostgreSQL database.
2018-07-23T14:55:22.457000Z NOTICE DROP SCHEMA esrde_sch CASCADE;
2018-07-23T14:55:22.457000Z NOTICE CREATE SCHEMA esrde_sch;
2018-07-23T14:55:22.458000Z ERROR Database error 42501: permission denied for database esrde
QUERY: CREATE SCHEMA esrde_sch;
2018-07-23T14:55:22.458000Z FATAL Failed to create the schema, see above.
2018-07-23T14:55:22.459000Z LOG report summary reset
```

Why does it want to drop & recreate the schema? I even tried to remove "include drop" (but this should only impact the tables), it didn't work either.

How can I solve my problem?

I would really appreciate some help?

Many thanks for any help!
Kind regards,
Didier

**Comment by dimitri** [comment]
Can you upgrade to pgloader 3.5.1 or current head/master's git code, please? I think this bug was fixed already, but I'm not definitive because we have so many options now that getting every situation right is quite complex. This code should be simplified.

**Comment by didwi** [comment]
Thanks for replying.
I compiled the latest sources but it fails to run, as I get an ssl error (ssl is required to connect), like this issue:
https://github.com/dimitri/pgloader/issues/794
KABOOM!
FATAL error: Failed to connect to pgsql at "postgres.x.y.z" (port 5432) as user "postgres": The alien function "CRYPTO_num_locks" is undefined.
An unhandled error condition has been signalled:
   Failed to connect to pgsql at "postgres.x.y.z" (port 5432) as user "postgres": The alien function "CRYPTO_num_locks" is undefined.

**Comment by didwi** [comment]
P.S. I will try to compile the 3.5.1 version on a native ubuntu (instead of a wsl linux ubuntu on windows) or via docker container and let you know if it is fixed.
Thanks anyway!
Didier

**Comment by dimitri** [comment]
Closing this issue as part of a clean-up exercise. Please open again if this issue still needs attention.
