### ISSUE TITLE
Copy views from mssql to postgres

### ISSUE THREAD

**Issue by justjoheinz** [dimitri/pgloader#817]
We are currently evaluating pgloader to copy database content from mssql to postgres. At first we had problems that despite getting connections to both database no content was copied. 

An analysis of the queries issued by pgloader soon revealed that it is only trying to find schemas for tables of the type `BASE TABLE` whereas all our "tables" are of type `VIEW`.

I build pgloader from scratch afterwards and applied the following hack to pgloader:

```
diff --git a/src/sources/mssql/mssql-schema.lisp b/src/sources/mssql/mssql-schema.lisp
index 97d3d36..4128449 100644
--- a/src/sources/mssql/mssql-schema.lisp
+++ b/src/sources/mssql/mssql-schema.lisp
@@ -56,7 +56,7 @@
 ;;; PostgreSQL CREATE TABLE statements, and run those.
 ;;;
 
-(defvar *table-type* '((:table . "BASE TABLE")
+(defvar *table-type* '((:table . "VIEW")
                       (:view  . "VIEW"))
   "Associate internal table type symbol with what's found in MS SQL
   information_schema.tables.table_type column.")
```

I am unfortunately not proficient enough with lisp to change the function `list-all-columns` to include VIEW or BASE TABLE in the where clause. I also haven't found information in the docs how I could possibly specify this in the loader script.

**Comment by justjoheinz** [comment]
Hi @dimitri - any ideas/ views (hahaha) on this?

**Comment by dimitri** [comment]
I had a look at it seemed simple enough to do, but at the same time I would like to be able to test the changes. For that I would need access to a MS SQL system where I can play around with pgloader. Is it possible for you to give me such an access?

**Comment by justjoheinz** [comment]
Unfortunately we do not control the mssql DB - we just have access to the views. If you work on a branch I can test what I can for you.

**Comment by dimitri** [comment]
I have been given a MS SQL test environment where I could see about the MATERIALIZE VIEW support and I believe we can close this issue now.
