### ISSUE TITLE
AFTER LOAD EXECUTE: cannot insert multiple commands into a prepared statement

### ISSUE THREAD

**Issue by sha-red** [dimitri/pgloader#818]
I try to run a bunch of SQL commands for cleaning up an imported database using 

    AFTER LOAD
        EXECUTE 'after_load.sql'
    ;

I get:

    KABOOM!
    FATAL error: Database error 42601: cannot insert multiple commands into a prepared statement

with the first 25 lines of the after_load.sql file.

If I only put a single SQL statement into the after_load.sql file, the error doesn't appear.

I wasn't able to find any speficiations on what is allowed in an executed SQL file or if I need some special syntax in there. Would it be possible to slightly extend the documentation for this awesome tool?

I have no problems to run the SQL with psql *after* pgloader finished.

**Comment by dimitri** [comment]
Because of the way the PostgreSQL driver works, pgloader needs to parse the SQL file and send the commands one after another. The error you have here looks like a failure to parse the commands. Can you provide the file (either here, or at my personal email, see my profile)?

**Comment by dimitri** [comment]
Closing the issue now. If you can share the SQL script that bugs pgloader, we will work on fixing our SQL parser.
