### ISSUE TITLE
Cannot connect to an SQL Server instance

### ISSUE THREAD

**Issue by jmsmistral** [dimitri/pgloader#820]
- [x] pgloader --version
  
    ```
pgloader version "3.5.5ca3ee8"
compiled with SBCL 1.4.10
    ```
  
  - [x] did you test a fresh compile from the source tree?
No - not an issues that requires a fresh compile
    
  - [x] did you search for other similar issues?
Yes
    
  - [x] how can I reproduce the bug?
Unfortunately, you would need to be able to connect to the company's SQL Server instance, which is a no go.

```
load database
    from mssql://user@server:port/dbname
    into postgresql://sacramentoj@localhost:5432/sacramentoj

including only table names like 'product' in schema 'dim'

before load do $$ drop schema if exists dbo cascade; $$;

```

  - [x] pgloader output you obtain
  
```
2018-08-08T08:57:58.095000+02:00 LOG Migrating from #<MSSQL-CONNECTION mssql://user@server:port/dbname {1006277FE3}>
2018-08-08T08:57:58.095000+02:00 LOG Migrating into #<PGSQL-CONNECTION pgsql://sacramentoj@localhost:5432/sacramentoj {10062793C3}>
KABOOM!
FATAL error: Failed to connect to mssql at "server" (port xxx) as user "username": Connection to the database failed for an unknown reason.
An unhandled error condition has been signalled:
   Failed to connect to mssql at "server" (port xxx) as user "username": Connection to the database failed for an unknown reason.

What I am doing here?

Failed to connect to mssql at "servername" (port xxx) as user "username": Connection to the database failed for an unknown reason.
```

  - [x] How the data is different from what you expected, if relevant

Hi - I want to migrate some data from an SQL Server instance to my local Postgres server. I have FreeTDS already configured with a few DSNs. I know that these work as I use them daily with Python and unixODBC. I was wondering about the following:

FreeTDS has the 'instance' attribute when defining DSNs (see below for a sample of how my current working DSN is defined). Why am I not able to use the instance name in the mssql URI? FreeTDS allows one to put the Port or the Instance, but not both (see http://www.freetds.org/userguide/freetdsconf.htm). 
```
[sqlsrv]
   host = someservername
   instance = INS
   tds version = 8.0
```

If the instance name cannot be used directly, is there a way pgloader can use the defined DSNs directly?

Thanks a lot for reading through this!

**Comment by dimitri** [comment]
pgloader is using https://github.com/archimag/cl-mssql to connect to MS SQL, and this driver exposes FreeTDS to the Common Lisp world. In the function used to connect to a database we don't give neither the port nor the instance, so I'm not sure what to tell you. What I know is that the driver uses your FreeTDS configuration.

What happens when you use one the following connection strings, given your FreeTDS configuration example above?

```
mssql://user@ sqlsrv/dbname
mssql://user@ someservername/dbname
```

I'm just trying to guess that either the _host_ from your config or more probably the _section name_ can be used directly in our connection string here...

**Comment by g1ngerninja** [comment]
I am also having this issue.  But I have discovered that it is to do with complex passwords.
For example, we have a password (not set by us DBA/Security) of TVmz7=LF@t\U95Z and this password results in the above error message.
When we use a simpler password say Jky838oo91 this works just fine.  I've tried with a compiled version of 3.6.1 and installed version of 3.4.1 (both on Ubuntu 18) and they both result in the same error message.

I've tried using URL encoding for all the special characters, for just some of them, nothing works.
Is there an alternative way of passing in the password?

**Comment by g1ngerninja** [comment]
> I am also having this issue. But I have discovered that it is to do with complex passwords.
> For example, we have a password (not set by us DBA/Security) of TVmz7=LF@t\U95Z and this password results in the above error message.
> When we use a simpler password say Jky838oo91 this works just fine. I've tried with a compiled version of 3.6.1 and installed version of 3.4.1 (both on Ubuntu 18) and they both result in the same error message.
> 
> I've tried using URL encoding for all the special characters, for just some of them, nothing works.
> Is there an alternative way of passing in the password?

UPDATE
I have finally figured this out.
I have to enclose the password in single quotes and escape the @ symbol with another @.  Escaping the @ alone wasn't enough due to the use of \ in the password also.

Hope this helps other out with similar problems.

**Comment by itdyoderhardwoods** [comment]
> 

Could you provide a source as to how escaping needs to be done?
