### ISSUE TITLE
Migration MySQL to PostgreSQL: identifiers case and quoting.

### ISSUE THREAD

**Issue by barthalexander** [dimitri/pgloader#826]
Hi,
I'm trying to migrate an MySQL database to PostgreSQL.
The databases already exist, so only the data have to be migrate.
The problem is, that some columns in MySQL are in big letters and the corresponding tables in PostgreSQL in small letters and the other way around. The same problem is with the columns.
Is there a possibility to insert some mappings in the load script.

Thank you a lot.

**Comment by dimitri** [comment]
Please see the _quote identifiers_ option of the WITH clause in the docs at https://pgloader.readthedocs.io/en/latest/ref/mysql.html#mysql-database-migration-options-with, it should be all you need here.

**Comment by barthalexander** [comment]
Hi Dimitri, 
thank you for your answer. I have tested it with:
```
load database
     from      mysql://.....
     into postgresql://.....
WITH data only, truncate, quote identifiers

ALTER SCHEMA 'test' RENAME TO 'public'
;
```
The result is this failure: 
```
What I am doing here?

Can't init COPY to public."audit_item"("ID", "LOG_ID", "OBJECT_TYPE", "OBJECT_ID", "OBJECT_NAME", "OBJECT_PARENT_ID", "OBJECT_PARENT_NAME"):
Database error 42703: column "LOG_ID" of relation "audit_item" does not exist
```

The columns in the Postgres table `autit_item` are in small letters

**Comment by dimitri** [comment]
Did you try the option `downcast identifiers` instead of `quote identifiers`?

**Comment by Hoangpnse62077** [comment]
Hi Dimitri, I have faced to the same problem with @barthalexander.

Currently, i use 'quote identifiers' to keep column name, but data can't be imported successfully.
020-02-06T08:31:58.458000Z FATAL Can't init COPY to public."Configurations"(id, distributioncostabsorptionrate, membertopuprpointbonusrate, membertopupmiscbucketbonusrate, usdtomcoin, rpointtousd, miscbucketreferenceid, createddate, updateddate): 
Database error 42703: column "id" of relation "Configurations" does not exist
2020-02-06T08:31:58.459000Z FATAL Can't init COPY to public."PaymentGateways"(paymentgatewayid, gateway, distributioncostrate, status, createddate, updateddate): 
Database error 42703: column "paymentgatewayid" of relation "PaymentGateways" does not exist
2020-02-06T08:31:58.459000Z FATAL Can't init COPY to public."PaymentTypes"(paymenttypeid, paymenttypedescription, createddate, updateddate): 
Database error 42703: column "paymenttypeid" of relation "PaymentTypes" does not exist
2020-02-06T08:31:58.459000Z FATAL Can't init COPY to public."WalletMerchants"(merchantid, merchantname, apikey, authority, status, createddate, updateddate): 
Database error 42703: column "merchantid" of relation "WalletMerchants" does not exist
2020-02-06T08:31:58.460000Z FATAL Can't init COPY to public."WalletTypes"(wallettypeid, wallettypename, wallettypedescription, validity, createddate, updateddate): 
Database error 42703: column "wallettypeid" of relation "WalletTypes" does not exist
