### ISSUE TITLE
Issue with date format specifications

### ISSUE THREAD

**Issue by NoelJoseph94** [dimitri/pgloader#828]
I am facing issues while using the date format specification in pgloader. The expected dates from the data file can have timestamps having microseconds or not having microseconds. I want both these formats to be loaded into my target table. But when i specify the date format as '[date format "YYYY-MM-DD HH24:MI:SS.US"], the timestamps with 0 microseconds error out.

My sample load file is 
<img width="267" alt="loadfile" src="https://user-images.githubusercontent.com/43058948/45203274-3f819f00-b299-11e8-9f83-5b9ab0b2f6ca.PNG">

The sample dataset is 
![image](https://user-images.githubusercontent.com/43058948/45203332-6c35b680-b299-11e8-9b3a-e0519ad31964.png)

The output when i run the pgloader command is:

![image](https://user-images.githubusercontent.com/43058948/45215359-dc086900-b2ba-11e8-9a42-a94e6db36901.png)

The version is : 
<img width="128" alt="ver" src="https://user-images.githubusercontent.com/43058948/45203389-a99a4400-b299-11e8-859a-9555eacdf52f.PNG">

Can you please help resolve this error, even if these errors occur, i notice the bad records do not get pushed into the error/bad file.

**Comment by dimitri** [comment]
I could reproduce the problem, even though in current master's branch pgloader would handle the error and continue. It's now accepted to have missing sub-second parts in the date strings. Please compile from sources and try again.
