### ISSUE TITLE
Support for multiple MySQL schema sources.

### ISSUE THREAD

**Issue by odederner1** [dimitri/pgloader#833]
Hi,
   I have a source MySQL DB with number of Databases.
tables in DB_1 may have Foreign Keys to tables in DB_2.
I migrate each MySQL DB to be PostgreSQL schema.
As a result only FK in the same MySQL DB tables are build/generated.
In this way all the FK's between schema tables are missing.

Is there a way to generate these FK via pglaoder?
Do you might have a reverse engineer script for all possible FK (having more than one column in reference)?

Thanks very much, 
O

**Comment by dimitri** [comment]
Can you please work on a test case for me to reproduce your case easily, and I'll have a deeper look? A MySQL schema dump might be good enough. Thanks!

**Comment by odederner1** [comment]
example:
create schema db_1;
use db_1;
create table my_table1 (id int primary key,col2 varchar(100));
create table my_table3(id int primary key,col2 varchar(100));
insert into my_table1 values (1,'hello');
-- that FK will be found in PostgreSQL
alter table my_table3 add constraint fk_table3_table1 FOREIGN KEY (id) references my_table1(id);


create schema db_2;
use db_2;
create table my_table2 (id int primary key,col2 varchar(100),col3 varchar(100));
insert into  my_table2 values (1,'hello','hello2');

-- that FK will not be found in PostgreSQL
alter table db_2.my_table2 add constraint fk_table2_table1 foreign key (id) references  db_1.my_table1(id);

=======================================
It might be cause the way I migrate one MySQL DB at time to PostgreSQL schema.
I issue ./pgloader twice. a run per MySQL DB.

**Comment by dimitri** [comment]
Currently pgloader maps a MySQL schema into a single PostgreSQL database. While our internal representation of the catalogs in pgloader knows how to manipulate more than one schema at a time, there's a fair amount of MySQL specific code that assumes we only have a single schema to take care about.

At the moment, supporting multiple MySQL source schemas in the same pgloader run isn't on the roadmap. You can influence the roadmap at https://pgloader.io/roadmap/.

Baring the new feature, you will have to add a manual script that re-installs missing foreign key references. I'm closing this issue, feel free to re-open it if you're willing to sponsor the development of the feature, either spending time (and contributing a PR) or money (see the Moral Licenses options as per above link).
