### ISSUE TITLE
Advise for using regexp_replace

### ISSUE THREAD

**Issue by tigerfoot** [dimitri/pgloader#835]
pgloader version 3.5.2

I'm trying to transform some text data included in csv source to a numeric value.

Once the data is loaded this query is working for transforming 

select "TextPrice", regexp_replace(regexp_replace("TextPrice",' ', '','g'),',','.','g')::numeric(12,4) from import.csv;

With the power of pgloader, I'm pretty sure its should be possible to transform the column directly, but I didn't find example nor documentation on how to correctly write the using case ?

**Comment by dimitri** [comment]
Please give some examples of input and output. It should be possible to use http://edicl.github.io/cl-ppcre/ from within pgloader transformation expressions directly in the load command.

**Comment by tigerfoot** [comment]
Hi dimitri, the data look has below.

Input 
```
"Price"
17,48
51,5
53,35
2 5394
19 900
210 533,076
29 481,58
17 462,7960
```

output
```
"Price"
17.4800
51.5000
53.3500
25394.0000
19900.0000
210533.0760
29481.5800
17462.7960
```

I've tried to understand the http://edicl.github.io/cl-ppcre/#regex-replace-all but don't catch the lisp syntax for it.

**Comment by dimitri** [comment]
The following example works. Note that pgloader currently runs the transformation code in a kind of a sandbox, for security reasons, and this sandbox currently doesn't know how to parse the Common Lisp notation for characters. Instead of writing `#\Space` we write `(aref " " 0)`, etc.

The more common way of writing the lisp transformation expression would be:

```lisp
(remove #\Space (substitute #\. #\, "210 533,076"))
```

Anyway, here's a self-contained example that shows how to do what you're asking, and that doesn't use regular expressions at all, finally:

```
LOAD CSV
     FROM inline (price)
     INTO postgresql:///pgloader
     TARGET TABLE t835
       (
        price text using (let ((space (aref " " 0))
                               (comma (aref "," 0))
                               (point (aref "." 0)))
                            (remove space (substitute point comma "210 533,076")))
       )

     WITH truncate,
          skip header = 1,
          fields optionally enclosed by '"',
          fields escaped by double-quote,
          fields terminated by ';'

   BEFORE LOAD DO
    $$ drop table if exists t835; $$,
    $$ create table t835
       (
        id     integer generated by default as identity primary key,
        price  numeric
       );
    $$;

"Price"
17,48
51,5
53,35
2 5394
19 900
210 533,076
29 481,58
17 462,7960
```

Here's the result when we run the script:

```
pgloader# table t835;
 id │   price    
════╪════════════
  1 │      17.48
  2 │       51.5
  3 │      53.35
  4 │      25394
  5 │      19900
  6 │ 210533.076
  7 │   29481.58
  8 │ 17462.7960
(8 rows)
```

**Comment by tigerfoot** [comment]
A big kudo, for the solution. That's also serve as a perfect example how to do this kind of transformation.
