### ISSUE TITLE
Freezing on violates foreign key constraint 

### ISSUE THREAD

**Issue by lohmuller** [dimitri/pgloader#836]
- [ ] pgloader --version
    ```pgloader version "3.5.2" compiled with SBCL 1.4.5.debian``` I'm using Kubuntu 18.04 
  
  - [ ] did you test a fresh compile from the source tree?
    No, just install via apt-get, 
    
  - [ ] did you search for other similar issues?
    Yes. but no answers how fix

  - [ ] how can I reproduce the bug?
Generate a database and use this sql for tables
```sql
CREATE TABLE public.categorias_produtos (
	id_loja varchar NOT NULL,
	id_categoria varchar NOT NULL,
	descricao varchar(80) NULL DEFAULT NULL::character varying,
	id_pai varchar NULL,
	CONSTRAINT categorias_produtos_pkey PRIMARY KEY (id_loja, id_categoria)
);

CREATE TABLE public.produtos (
	id_loja varchar NOT NULL,
	id_categoria varchar NULL,
	codigo_barras_produto varchar(50) NULL DEFAULT NULL::character varying,
	id_produto varchar NOT NULL,
	desc_produto varchar(100) NULL DEFAULT NULL::character varying,
	unidade bpchar(2) NULL DEFAULT NULL::bpchar,
	CONSTRAINT produtos_pkey PRIMARY KEY (id_loja, id_produto),
	CONSTRAINT produtos_categorias_produtos_fk FOREIGN KEY (id_loja, id_categoria) REFERENCES categorias_produtos(id_loja, id_categoria)
);
```
and create a file "produtos.csv"
```csv
"001";"9999";"0000003656105";"48293";"Anador Comprimido Boehringer Compri";"CX"
```
now just try to import
```pgloader --verbose --with="quote identifiers" --type csv produtos.csv postgres://postgres:password@127.0.0.1:5432/database?tablename=produtos```

  - [ ] pgloader output you obtain
    And freezing in this error... 
```
2018-09-14T17:43:06.010000Z NOTICE Starting pgloader, log system is ready.
2018-09-14T17:43:06.098000Z WARNING Target table "\"public\".\"produtos\"" has 1 indexes defined against it.
2018-09-14T17:43:06.101000Z WARNING That could impact loading performance badly.
2018-09-14T17:43:06.101000Z WARNING Consider the option 'drop indexes'.
2018-09-14T17:43:06.112000Z NOTICE COPY "public"."produtos"
2018-09-14T17:43:06.118000Z NOTICE Opening #P"/home/mercafacil/Área de Trabalho/validacao/molicenter_03089961000102_20180822123739/produtos2.txt"
2018-09-14T17:43:06.118000Z NOTICE Guessed following CSV parameters:
  fields terminated by ';',
  fields optionally enclosed by '"',
  fields escaped by '""'

debugger invoked on a TYPE-ERROR in thread
2018-09-14T17:43:06.134000Z ERROR PostgreSQL ["\"public\".\"produtos\""] Database error 23503: insert or update on table "produtos" violates foreign key constraint "produtos_categorias_produtos_fk"
DETAIL: Key (id_loja, id_categoria)=(001, 9999) is not present in table "categorias_produtos".
#<THREAD "lparallel" RUNNING {10076D1133}>:
  The value
    NIL
  is not of type
    NUMBER
  when binding SB-KERNEL::Y
```
I  want to skip this error (and if possible show the line in the file), 
I'm using the pgloader to validate data and relationship from a csv... And i need the line and how much errors have.

My produtos.csv have a lot of items... but only this line give me a error... ( I have a 5mb of data in the categoria_produtos table... but i dont know if the error is about the data in categoria produtos...)

**Comment by veturi** [comment]
I'm currently having the exact same issue with pgloader freezing on foreign key constraint errors.
I have `on error resume next` defined but pgloader is not proceeding to the next row.

pgloader version "3.5.2~devel"
compiled with SBCL 1.3.14.debian

**Comment by dimitri** [comment]
With the attached patch pgloader should not be stuck anymore. It's not a real solution, but should help getting there, I'm now trying to see how to handle foreign key violations properly. Problem is that the error message doesn't contain the COPY line number anymore, of course.

**Comment by dimitri** [comment]
Ok I believe we should now be able to process the constraint violation cases in a better way, that is, just log them and continue.

**Comment by dimitri** [comment]
Ahah, realised while writing the summary here that I forgot about something that might be important: handling the reject data/log files. Now done. Should be good now, please test and report / re-open the issue if necessary.
