### ISSUE TITLE
Impossible to install pgloader because of firewall

### ISSUE THREAD

**Issue by did16** [dimitri/pgloader#839]
Hi Dimitri
I want to use pgloader in my firm but I can't install it because of firewall rules.
It would be nice to have an antonomous package, because in the most part of firms we can't go out to the internet. So curl, git clone ...do not work.

Please provide the following information:

  - [ ] pgloader --version
  
    ```
    3.2
    ```
  Thanks in advance
Didier ROS
EDF

**Comment by dimitri** [comment]
Hi @did16,

The release section of the GitHub project at https://github.com/dimitri/pgloader/releases contains bundle tar balls which embeds all the build time dependencies of pgloader, so that you can build pgloader without further downloads. The bundles are used to build the RPMs of pgloader.
