### ISSUE TITLE
pgloader cli schema name

### ISSUE THREAD

**Issue by lohmuller** [dimitri/pgloader#841]
I can't change the schema while importing using only cli, give me no aswer or go to backgrounnd proccess

```
pgloader --type csv ./csv//produtos.txt postgres://postgres:password123@172.17.0.1:5432/dollynho?options=--search_path%3dteste&tablename=produtos
```
return nothing...

i tried with url encode... but no luck =[ with double quote too..
```
pgloader --type csv ./csv//produtos.txt "postgres://postgres:password123@172.17.0.1:5432/dollynho?options=--search_path%3dteste&tablename=produtos"
```

Any way to give schema name while using cli only?

**Comment by dimitri** [comment]
You can use the notation schema.table in the URL. The following should work. If it does not, consider reading the docs and the test cases in https://github.com/dimitri/pgloader/tree/master/test, and re-opening this issue if needed, of course!

```
pgloader --type csv ./csv/produtos.txt 
postgres://postgres:password123@172.17.0.1:5432/dollynho?tablename=teste.produtos
```
