### ISSUE TITLE
Date Issue - When Month Name is given

### ISSUE THREAD

**Issue by NoelJoseph94** [dimitri/pgloader#842]
Hi,

When a timestamp/date field has data with the month name explicitly specified, the data is being auto converted to the month value in number .
Eg: When the data file has value 'May 20 2018' , the target table is populated as 05-20-2018.

Consider the scenario:

--Sample load file:

 
![image](https://user-images.githubusercontent.com/43058948/46061928-d00b1b00-c185-11e8-8ed6-f88c7eeceb65.png)

--Sample Data File
![image](https://user-images.githubusercontent.com/43058948/46061978-ffba2300-c185-11e8-8739-08b4bbd5b332.png)

--During pgloader run got the following output
![image](https://user-images.githubusercontent.com/43058948/46062031-28421d00-c186-11e8-8000-f30fff18b80a.png)

-- The target table data (obtained output):
![image](https://user-images.githubusercontent.com/43058948/46062065-4576eb80-c186-11e8-944b-664af90046f6.png)

--The required output in the target table:

1919 May 21 12:00:21.213

Can you please suggest a way this can be achieved.

**Comment by dimitri** [comment]
The data is correct. The formatting is not a problem for pgloader once the correct data is found in the target database. Please read the PostgreSQL documentation about date formatting, such as https://www.postgresql.org/docs/current/functions-formatting.html and https://www.postgresql.org/docs/current/datatype-datetime.html ; and https://www.postgresql.org/docs/current/runtime-config-client.html#GUC-DATESTYLE too.
