### ISSUE TITLE
SQLite to postgreSQL (Postgis) failing because of VirtualSpatialIndex

### ISSUE THREAD

**Issue by sowinski** [dimitri/pgloader#850]
- [ ] pgloader --version
  3.5.2
  
  - [ ] did you test a fresh compile from the source tree?
    No
    
  - [ ] did you search for other similar issues?
    Yes

  - [ ] how can I reproduce the bug?
`Load a spatialite file with a Point field`

  - [ ] pgloader output you obtain
 

```
postgres@dev:/tmp$ pgloader db.sqlite3 postgresql:///dev
KABOOM!
FATAL error: Could not prepare an sqlite statement.
Code ERROR: no such module: VirtualSpatialIndex.
Database: /tmp/db.sqlite3
SQL: PRAGMA table_info(`SpatialIndex`)

An unhandled error condition has been signalled:
   Could not prepare an sqlite statement.
Code ERROR: no such module: VirtualSpatialIndex.
Database: /tmp/db.sqlite3
SQL: PRAGMA table_info(`SpatialIndex`)

FATAL: Failed to start the monitor thread.

error opening #P"/tmp/pgloader/pgloader.log": Permission denied
```

Is it possible to import a SpatialLite Database file which has POINT fields with Lat/Lng values? 

If yes, what I am doing wrong?

**Comment by dimitri** [comment]
Hi @sowinski ; can you actually open your `db.sqlite3` with the sqlite tooling? the error message `Code ERROR: no such module: VirtualSpatialIndex.` does not come from pgloader, so I guess there's something strange with the SQLite libs in use here?
