### ISSUE TITLE
Docker image is not supporting spartialite

### ISSUE THREAD

**Issue by sowinski** [dimitri/pgloader#852]
Hi,

I was trying to import from SpatiaLite (Sqlite) to PostgreSQL (PostGIS). Your docker image does not support 'mod_spatialite'

Please find the problem on stackoverflow:  https://stackoverflow.com/questions/52738729/how-to-merge-from-spatiallite-to-postgis/52738996?noredirect=1#comment92404734_52738996

Thx

**Comment by dimitri** [comment]
Can you build your own docker image with the SQLite modules you need?

**Comment by sowinski** [comment]
I don't know how. Can you give me a hint where to start?

**Comment by revolunet** [comment]
[This answer](https://stackoverflow.com/a/52738996/174027) is a good start

**Comment by revolunet** [comment]
Maybe check this example : https://github.com/Legilibre/legi-postgres/blob/master/Dockerfile-pgloader
