### ISSUE TITLE
Intermittent Segmentation Fault Centos-7

### ISSUE THREAD

**Issue by shahzaibcb** [dimitri/pgloader#857]
Hi,

We compiled pgloader with ccl but after few days pgloader starts giving segmentation fault errors after which neither we can run this command nor we can re-compile pgloader. The only remedy is to reinstall OS and then compile pgloader again which again runs few days and start generating errors. Is anyone facing the same issue ?
`[root@pg1 ~]# pgloader --version`
`Segmentation fault`

**Comment by shahzaibcb** [comment]
Here is the update of the error :- 

When we execute command `pgloader` following error in kernel generates:

`Oct 26 09:55:21 pg1 kernel: traps: pgloader[26891] general protection ip:3000002131e3 sp:7f130192de50 error:62a in pgloader[300000000000+3dcd000]`

**Comment by dimitri** [comment]
Needs more information. Closing to clean-up issues dashboard. Please re-open if needed.
