### ISSUE TITLE
feature: flag to emit basename and dirname 

### ISSUE THREAD

**Issue by malcook** [dimitri/pgloader#858]
instead of or in addition to filename

as I and Ben McGough both find need for and discuss consideration/approaches in:

[Postgresql loading practices](https://github.com/fizwit/filesystem-reporting-tools/wiki/Postgresql-loading-practices)

**Comment by dimitri** [comment]
Hi @malcook ; from a quick read of your linked content, it seems like it would be possible to process the data directly in pgloader, doing the work right from the pgloader copy process. To be sure of that though, please add more information here: some sample data in the original format and the output you want to see, all with a pgloader command that does what you can achieve yourself without my help and a comment about what's missing.

You will find inspiration in the test files of pgloader, maybe https://github.com/dimitri/pgloader/blob/master/test/archive.load would help the most as it implements non-trivial data processing. You might not need the ARCHIVE source though.

**Comment by malcook** [comment]
@dimitri - my mistake for posting this to pgloader... I have repost it _downstream_ [to fizwit/filesystem-reporting-tools](https://github.com/fizwit/filesystem-reporting-tools/issues/18).   Thanks for the attention!

**Comment by malcook** [comment]
@dimitri - my mistake for posting this to pgloader... I have repost it _downstream_ [to fizwit/filesystem-reporting-tools](https://github.com/fizwit/filesystem-reporting-tools/issues/18).   Thanks for the attention!
