### ISSUE TITLE
Compile error with ccl

### ISSUE THREAD

**Issue by LennyLip** [dimitri/pgloader#862]
Last ccl https://github.com/Clozure/ccl/releases/download/v1.11.5/ccl-1.11.5-linuxx86.tar.gz

` make clean && make CL=ccl pgloader`

```
; Loading "zs3"
> Error: Error while trying to load definition for system ironclad from pathname /back/pgloader-master/build/quicklisp/dists/quicklisp/software/ironclad-v0.43/ironclad.asd: (OR (FUNCALL (INTERN "DO-TESTS" (FIND-PACKAGE "RTEST"))) (ERROR "TEST-OP failed for IRONCLAD/TESTS")) can't be destructured against the lambda list (ASDF::O ASDF::C), because it contains 3 elements, and exactly 2 are expected.

```

**Comment by LennyLip** [comment]
ccl 1.12  same here (host debian 8), packege pgloader-debian-3.5.2-2

**Comment by mrPsycho** [comment]
i've compiled it with ccl, and it worked nice. 
and, on x64 system i created link to ccl64, because it failed with ccl x32. 

how you installed ccl?

**Comment by dimitri** [comment]
Closing the issue now. Please re-open if needed. Meanwhile we have Travis and DockerHub fixed again, with builds using CCL and SBCL for each commit, and everything is fine. Try newer version of pgloader.
