### ISSUE TITLE
Column 'proisagg' does not exist

### ISSUE THREAD

**Issue by roipoussiere** [dimitri/pgloader#863]
I loaded an empty__*__ sqlite script into a pg db running on psql v11.

When I try visualize it with pgAdmin, instead of empty tables, I get the following error:

![screenshot_20181105_141442](https://user-images.githubusercontent.com/1665542/48002833-f91bb580-e10c-11e8-8bbf-998417983284.png)

__*__: yes... by mistake, but maybe this issue is still relevant.

## pgloader file

```
LOAD DATABASE
    FROM 'base.db'
    INTO pgsql://postgres:1234@localhost:5432/polarbase

WITH include drop, create tables, create indexes, reset sequences

SET work_mem to '16MB', maintenance_work_mem to '512 MB';
```

## pgloader output (nothing special)
 
```
2018-11-05T10:03:25.237000Z LOG report summary reset
             table name       read   imported     errors      total time
-----------------------  ---------  ---------  ---------  --------------
                  fetch          0          0          0          0.000s 
        fetch meta data          0          0          0          0.014s 
         Create Schemas          0          0          0          0.000s 
       Create SQL Types          0          0          0          0.005s 
          Create tables          0          0          0          0.000s 
         Set Table OIDs          0          0          0          0.000s 
-----------------------  ---------  ---------  ---------  --------------
-----------------------  ---------  ---------  ---------  --------------
COPY Threads Completion          4          4          0          0.000s 
 Index Build Completion          0          0          0          0.000s 
        Reset Sequences          0          0          0          0.006s 
           Primary Keys          0          0          0          0.000s 
    Create Foreign Keys          0          0          0          0.000s 
        Create Triggers          0          0          0          0.000s 
       Install Comments          0          0          0          0.000s 
```

## data loaded

```
(empty file)
```

## information

- pgloader version: "3.4.1", compiled with SBCL 1.3.3.debian;
- installed with apt-get;
- no similar issue;

## additional notes

- I do not get this error with the same empty sqlite file on psql v9 or v10;
- similar issues has been reported on other projects [here](https://github.com/jOOQ/jOOQ/issues/7785) and [here](https://trac.osgeo.org/postgis/ticket/4044).

**Comment by dimitri** [comment]
How do you create an empty SQLite file? I'd like to test and reproduce the situation. Thing is, I don't see any usage of proisagg in pgloader, so I don't think that's the problem. Your paste shows a problem with pgAdmin, which you might have to upgrade to a version with PG11 support.

**Comment by roipoussiere** [comment]
Indeed, sorry! It works with PGAdmin4. I close this, so.
