### ISSUE TITLE
Couldn't re-execute SBCL with proper personality flags (/proc isn't mounted? setuid?)

### ISSUE THREAD

**Issue by lohmuller** [dimitri/pgloader#864]
The new version of pgloader in docker has bug =[
i'm using Linux Mint 19 (cinnamon) with Docker version 18.06.1-ce, build e68fc7a

```
$ sudo docker run --rm dimitri/pgloader pgloader --version

WARNING:
Couldn't re-execute SBCL with proper personality flags (/proc isn't mounted? setuid?)
Trying to continue anyway.
pgloader version "3.5.2~devel"
compiled with SBCL 1.3.14.debian
```

I have a custom docker image (debian + python + pgloader) but dont import CSV and give me that warnings...

Ah! Pgloader Docker Image have only the latest tag... Is possible tag with the pgloader version (dimitri/pgloader:3.5.2)?

**Comment by dimitri** [comment]
The output looks good. The personality flags warning isn't fatal, I've seen plenty reports with that one in docker but then everything is fine. It's something that can be fixed at the SBCL level directly, not in pgloader, too. I'm closing this issue, please feel free to re-open with more information showing a problem here.

**Comment by auspex** [comment]
It would be really helpful if you kept the historical pgloader images on Docker hub. I can't compile a working version for MSSQL.
