### ISSUE TITLE
Changing certain table and column names to uppercase

### ISSUE THREAD

**Issue by dewu17** [dimitri/pgloader#867]
I am working on trying to use pgloader for a MySQL to PostgreSQL migration. Everything seems to be going well except for one issue. There hundreds of tables and columns  that start with “ao_” that are stored as small lowercase in MySQL however they need to be uppercase in order for them to work and also need to be in double quotes. I tried to do the alter table in my load files however when I do a \dt the table is still lowercase. Is there a way to setup a table/column definition so I can have these 300 tables and columns be created as uppercase. Also can any wildcards be created since it’s a good amount of tables that need to be altered?

**Comment by dimitri** [comment]
I would add a SQL script to execute after the pgloader migration that would use ALTER TABLE for you and do what you need here. A PostgreSQL catalog query to generate such a SQL script would be pretty easy to write. https://tapoueh.org/blog/2010/08/editing-constants-in-constraints/ might be a good starting point for you, and https://tapoueh.org/blog/2011/05/tables-and-views-dependencies/ shows another technique to do it too.
