### ISSUE TITLE
Questions on using pgloader with Docker

### ISSUE THREAD

**Issue by Benji410** [dimitri/pgloader#870]
So i'm trying to convert MySQL to PSQL using docker and i'm having a couple issues. 

1. docker run -it --rm alpine /sbin/ip route|awk '/default/ { print $3 }'
When I run this line, I get this error. 
**C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"C:/Program Files/Git/sbin/ip\": stat C:/Program Files/Git/sbin/ip: no such file or directory": unknown.**

2. If both the MySQL and PostgreSQL servers are running from my computer, should I use the IP Address i get from the docker command above if i can execute it? 

3. Do I also include the password after the username for the command to convert the mysql to psql using pgloader?

**Comment by dimitri** [comment]
Hi, I built the docker image as a service to people who would use that, after having been asked several times. I don't use docker much myself, and I've never used windows. Please ask docker usage related questions on a docker forum.
