### ISSUE TITLE
The value NIL is not of type PGLOADER.CATALOG:COLUMN

### ISSUE THREAD

**Issue by drouarb** [dimitri/pgloader#872]
- [x] pgloader --version
  
```
   pgloader version "3.5.ab2cadf"
   compiled with SBCL 1.3.1.debian
```
  
  - [x] did you test a fresh compile from the source tree?
    
Yes
    
  - [x] did you search for other similar issues?

Yes, nothing
    
  - [x] how can I reproduce the bug?

Load this database into a new Postgres database:
https://mega.nz/#!PQsCACQK!Dos6ndyL3ng0hBVC0Zyg9mkmjQxlzkEpAphPgP9xAD4

```
load database
     from '/sqlite/plex.db'
     into postgresql://plex:plex@192.168.1.30:5432/plex

 with include drop, create tables, create indexes, reset sequences
 excluding table names like 'spellfix_metadata_titles', 'spellfix_metadata_titles_vocab', 'spellfix_tag_titles', 'spellfix_tag_titles_vocab'

 set work_mem to '16MB', maintenance_work_mem to '512 MB';
```

  - [x] pgloader output you obtain
 
The value NIL is not of type PGLOADER.CATALOG:COLUMN

Full debug log:
https://gist.github.com/drouarb/3d1911bb5ee453dbac7ba0540b456d5c

**Comment by dimitri** [comment]
Hi, is there a way that you can send me the SQLite file by email? that would help having more information from the backtrace and being able to debug the problem here... thanks.

**Comment by drouarb** [comment]
The sqlite file is in the mega link, it's a freshly created Plex Media Server database

**Comment by dimitri** [comment]
Thanks. I could reproduce the problem and I believed I fixed it. Please try from fresh source! Use either the classic `make` or the new `make save` to produce your pgloader binary in `./build/bin/pgloader`.

**Comment by drouarb** [comment]
Now another error appeared:
```
2018-12-01T21:07:28.155000Z ERROR PostgreSQL Database error 42601: syntax error at or near "order"
QUERY: CREATE INDEX idx_61581_media_subscriptions_on_order ON media_subscriptions (order);
```

It looks like when creating an index, the column name should be quoted:.
When I do it with psql command:
```
psql (10.5, server 10.0)
Type "help" for help.

plex=# CREATE INDEX idx_61581_media_subscriptions_on_order ON media_subscriptions (order);
ERROR:  syntax error at or near "order"
LINE 1: ...media_subscriptions_on_order ON media_subscriptions (order);
                                                                ^
plex=# CREATE INDEX idx_61581_media_subscriptions_on_order ON media_subscriptions ("order");
CREATE INDEX
plex=#
```

**Comment by drouarb** [comment]
Thanks, it's perfectly working now

**Comment by josheinstein** [comment]
Just wanted to throw a comment in here in case someone comes across it in a google search. In my case, the issue was that throughout my database I have pairs of columns such as date_sent (integer) and date_sent_str (text) where the text column is generated based on the integer timestamp. pgloader doesn't migrate the generated column, and then chokes when it runs into an index which references it.

Removing the index that references a generated column fixed it for me.
