### ISSUE TITLE
Don't understand this error

### ISSUE THREAD

**Issue by Benji410** [dimitri/pgloader#875]
Converting database on MySQL (Amazon RDS) to PSQL (local)
brew installed on macOS with most recent version. 

I have no idea what this error means. Is this an error with my data?
This is my error: 

```
76 fell through ECASE expression.
             Wanted one of (2 3 4 5 6 8 9 10 11 14 15 17 20 21 23 27 28 30 31
                            32 33 35 41 42 45 46 47 48 49 50 51 52 54 55 56 60
                            61 62 63 64 65 69 72 77 78 79 82 83 87 90 92 93 94
                            95 96 97 98 101 102 103 104 105 106 107 108 109 110
                            111 112 113 114 115 116 117 118 119 120 121 122 123
                            124 128 129 130 131 132 133 134 135 136 137 138 139
                            140 141 142 143 144 145 146 147 148 149 150 151 159
                            160 161 162 163 164 165 166 167 168 169 170 171 172
                            173 174 175 176 177 178 179 180 181 182 183 192 193
                            194 195 196 197 198 199 200 201 202 203 204 205 206
                            207 208 209 210 211 212 213 214 215 223 224 225 226
                            227 228 229 230 231 232 233 234 235 236 237 238 239
                            240 241 242 243 244 245 246 247 254).
```

**Comment by dimitri** [comment]
Hi @Benji410 ; it might be at the driver level rather than at the data level, in particular when it's not properly catch I guess it comes from below and we avoid pretending we know how to deal with such oddities in the code. Can you retry with `--debug` and give more information to help debug the situation?

**Comment by Benji410** [comment]
It output all of this:

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10005905B3}>
0: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE-TO-STREAM #<SB-IMPL::STRING-OUTPUT-STREAM {1006F96C03}>)
1: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE #<SB-KERNEL:CASE-FAILURE expected-type: (MEMBER 2 3 4 5 6 8 9 10 11 14 15 17 20 21 23 27 28 30 31 32 33 35 41 42 45 46 ..) datum: 76> :OUTPUT NIL :IF-EXISTS :APPEND :VERBOSE NIL)
2: ((FLET "H0" :IN PGLOADER::MAIN) #<SB-KERNEL:CASE-FAILURE expected-type: (MEMBER 2 3 4 5 6 8 9 10 11 14 15 17 20 21 23 27 28 30 31 32 33 35 41 42 45 46 ..) datum: 76>)
3: (SB-KERNEL::%SIGNAL #<SB-KERNEL:CASE-FAILURE expected-type: (MEMBER 2 3 4 5 6 8 9 10 11 14 15 17 20 21 23 27 28 30 31 32 33 35 41 42 45 46 ..) datum: 76>)
4: (ERROR SB-KERNEL:CASE-FAILURE :NAME ECASE :DATUM 76 :EXPECTED-TYPE (MEMBER 2 3 4 5 6 8 9 10 11 14 15 17 20 21 23 27 28 30 31 32 33 35 41 42 45 46 47 48 49 50 51 52 54 55 56 60 61 62 63 64 65 69 72 77 78 79 82 83 87 90 92 93 94 95 96 97 98 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247 254) :POSSIBILITIES (2 3 4 5 6 8 9 10 11 14 15 17 20 21 23 27 28 30 31 32 33 35 41 42 45 46 47 48 49 50 51 52 54 55 56 60 61 62 63 64 65 69 72 77 78 79 82 83 87 90 92 93 94 95 96 97 98 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247 254))
5: (QMYND-IMPL::MYSQL-CS-COLL-TO-CHARACTER-ENCODING 76)
6: (QMYND-IMPL::PARSE-TEXT-PROTOCOL-RESULT-COLUMN-AS-TEXT #(105 100) #S(QMYND-IMPL::COLUMN-DEFINITION-V41-PACKET :CATALOG "def" :SCHEMA "" :TABLE "c" :ORG-TABLE "" :NAME "COLUMN_NAME" :ORG-NAME "COLUMN_NAME" :CS-COLL 76 :COLUMN-LENGTH 192 :TYPE 253 :FLAGS 1 :DECIMALS 0 :DEFAULT-VALUE NIL))
7: (QMYND-IMPL::PARSE-RESULTSET-ROW-AS-TEXT-LIST 9 #<unavailable argument>)
8: (QMYND-IMPL:PARSE-RESULTSET-ROWS 9 #(#S(QMYND-IMPL::COLUMN-DEFINITION-V41-PACKET :CATALOG "def" :SCHEMA "mysql" :TABLE "c" :ORG-TABLE "tables" :NAME "TABLE_NAME" :ORG-NAME "TABLE_NAME" :CS-COLL 83 :COLUMN-LENGTH 192 :TYPE 253 :FLAGS 4225 :DECIMALS 0 :DEFAULT-VALUE NIL) #S(QMYND-IMPL::COLUMN-DEFINITION-V41-PACKET :CATALOG "def" :SCHEMA "" :TABLE "t" :ORG-TABLE "" :NAME "TABLE_COMMENT" :ORG-NAME "TABLE_COMMENT" :CS-COLL 33 :COLUMN-LENGTH 768 :TYPE 253 :FLAGS 0 :DECIMALS 0 :DEFAULT-VALUE NIL) #S(QMYND-IMPL::COLUMN-DEFINITION-V41-PACKET :CATALOG "def" :SCHEMA "" :TABLE "c" :ORG-TABLE "" :NAME "COLUMN_NAME" :ORG-NAME "COLUMN_NAME" :CS-COLL 76 :COLUMN-LENGTH 192 :TYPE 253 :FLAGS 1 :DECIMALS 0 :DEFAULT-VALUE NIL) #S(QMYND-IMPL::COLUMN-DEFINITION-V41-PACKET :CATALOG "def" :SCHEMA "" :TABLE "c" :ORG-TABLE "" :NAME "COLUMN_COMMENT" :ORG-NAME "COLUMN_COMMENT" :CS-COLL 83 :COLUMN-LENGTH 6144 :TYPE 252 :FLAGS 145 :DECIMALS 0 :DEFAULT-VALUE NIL) #S(QMYND-IMPL::COLUMN-DEFINITION-V41-PACKET :CATALOG "def" :SCHEMA "" :TABLE "c" :ORG-TABLE "" :NAME "DATA_TYPE" :ORG-NAME "DATA_TYPE" :CS-COLL 83 :COLUMN-LENGTH 50331645 :TYPE 252 :FLAGS 145 :DECIMALS 0 :DEFAULT-VALUE NIL) #S(QMYND-IMPL::COLUMN-DEFINITION-V41-PACKET :CATALOG "def" :SCHEMA "mysql" :TABLE "c" :ORG-TABLE "columns" :NAME "COLUMN_TYPE" :ORG-NAME "COLUMN_TYPE" :CS-COLL 83 :COLUMN-LENGTH 16777215 :TYPE 252 :FLAGS 4241 :DECIMALS 0 :DEFAULT-VALUE NIL) #S(QMYND-IMPL::COLUMN-DEFINITION-V41-PACKET :CATALOG "def" :SCHEMA "mysql" :TABLE "c" :ORG-TABLE "columns" :NAME "COLUMN_DEFAULT" :ORG-NAME "COLUMN_DEFAULT" :CS-COLL 83 :COLUMN-LENGTH 65535 :TYPE 252 :FLAGS 144 :DECIMALS 0 :DEFAULT-VALUE NIL) #S(QMYND-IMPL::COLUMN-DEFINITION-V41-PACKET :CATALOG "def" :SCHEMA "" :TABLE "c" :ORG-TABLE "" :NAME "IS_NULLABLE" :ORG-NAME "IS_NULLABLE" :CS-COLL 33 :COLUMN-LENGTH 9 :TYPE 253 :FLAGS 1 :DECIMALS 0 :DEFAULT-VALUE NIL) #S(QMYND-IMPL::COLUMN-DEFINITION-V41-PACKET :CATALOG "def" :SCHEMA "" :TABLE "c" :ORG-TABLE "" :NAME "EXTRA" :ORG-NAME "EXTRA" :CS-COLL 83 :COLUMN-LENGTH 171 :TYPE 253 :FLAGS 129 :DECIMALS 0 :DEFAULT-VALUE NIL)) :AS-TEXT T :RESULT-TYPE LIST)
9: (QMYND-IMPL:SEND-COMMAND-QUERY #<(SIMPLE-BASE-STRING 647) -- params: db-name
--         table-type-name
--         only-tables
--         only-tables
--         including
--         filter-list-to-where-clause incuding
--         excluding
--         filter-... {1006E930AF}> :ROW-FN NIL :AS-TEXT T :RESULT-TYPE LIST)
10: (QMYND:MYSQL-QUERY #<QMYND-IMPL::MYSQL-INET-CONNECTION {1006926733}> #<(SIMPLE-BASE-STRING 647) -- params: db-name
--         table-type-name
--         only-tables
--         only-tables
--         including
--         filter-list-to-where-clause incuding
--         excluding
--         filter-... {1006E930AF}> :ROW-FN NIL :AS-TEXT T :RESULT-TYPE LIST)
11: (PGLOADER.SOURCE.MYSQL::LIST-ALL-COLUMNS #1=#S(PGLOADER.CATALOG:SCHEMA :SOURCE-NAME #2="paris" :NAME "paris" :CATALOG #S(PGLOADER.CATALOG:CATALOG :NAME #2# :SCHEMA-LIST (#1#) :TYPES-WITHOUT-BTREE NIL) :TABLE-LIST NIL :VIEW-LIST NIL :IN-SEARCH-PATH T) :TABLE-TYPE :TABLE :ONLY-TABLES NIL :INCLUDING NIL :EXCLUDING NIL)
12: ((:METHOD PGLOADER.SOURCES:FETCH-METADATA (PGLOADER.SOURCE.MYSQL:COPY-MYSQL PGLOADER.CATALOG:CATALOG)) #<PGLOADER.SOURCE.MYSQL:COPY-MYSQL {1006276613}> #1=#S(PGLOADER.CATALOG:CATALOG :NAME #2="paris" :SCHEMA-LIST (#S(PGLOADER.CATALOG:SCHEMA :SOURCE-NAME #2# :NAME "paris" :CATALOG #1# :TABLE-LIST NIL :VIEW-LIST NIL :IN-SEARCH-PATH T)) :TYPES-WITHOUT-BTREE NIL) :MATERIALIZE-VIEWS NIL :ONLY-TABLES NIL :CREATE-INDEXES T :FOREIGN-KEYS T :INCLUDING NIL :EXCLUDING NIL) [fast-method]
13: ((:METHOD PGLOADER.LOAD:COPY-DATABASE (PGLOADER.SOURCES:DB-COPY)) #<PGLOADER.SOURCE.MYSQL:COPY-MYSQL {1006276613}> :ON-ERROR-STOP T :WORKER-COUNT 4 :CONCURRENCY 1 :MULTIPLE-READERS NIL :MAX-PARALLEL-CREATE-INDEX NIL :TRUNCATE NIL :DISABLE-TRIGGERS NIL :DATA-ONLY NIL :SCHEMA-ONLY NIL :CREATE-SCHEMAS T :CREATE-TABLES T :INCLUDE-DROP T :DROP-SCHEMA NIL :CREATE-INDEXES T :INDEX-NAMES :UNIQUIFY :RESET-SEQUENCES T :FOREIGN-KEYS T :REINDEX NIL :ONLY-TABLES NIL :INCLUDING NIL :EXCLUDING NIL :SET-TABLE-OIDS T :ALTER-TABLE NIL :ALTER-SCHEMA NIL :MATERIALIZE-VIEWS NIL) [fast-method]
14: ((LAMBDA ()))
15: (PGLOADER:RUN-COMMANDS (LAMBDA NIL (LET* ((PGLOADER.SOURCES:*DEFAULT-CAST-RULES* (QUOTE ((:SOURCE (:TYPE #1="int" :AUTO-INCREMENT T :TYPEMOD (< PGLOADER.TRANSFORMS:PRECISION 10)) :TARGET (:TYPE #2="serial")) (:SOURCE (:TYPE #1# :AUTO-INCREMENT T :TYPEMOD (<= 10 PGLOADER.TRANSFORMS:PRECISION)) :TARGET (:TYPE #3="bigserial")) (:SOURCE (:TYPE #1# :AUTO-INCREMENT NIL :TYPEMOD (< PGLOADER.TRANSFORMS:PRECISION 10)) :TARGET (:TYPE #1#)) (:SOURCE (:TYPE #1# :AUTO-INCREMENT NIL :TYPEMOD (<= 10 PGLOADER.TRANSFORMS:PRECISION)) :TARGET (:TYPE #4="bigint")) (:SOURCE (:TYPE #5="tinyint" :AUTO-INCREMENT T) :TARGET (:TYPE #2#)) (:SOURCE (:TYPE #6="smallint" :AUTO-INCREMENT T) :TARGET (:TYPE #2#)) (:SOURCE (:TYPE #7="mediumint" :AUTO-INCREMENT T) :TARGET (:TYPE #2#)) (:SOURCE (:TYPE #4# :AUTO-INCREMENT T) :TARGET (:TYPE #3#)) (:SOURCE (:TYPE #5# :TYPEMOD (= 1 PGLOADER.TRANSFORMS:PRECISION)) :TARGET (:TYPE #8="boolean" :DROP-TYPEMOD T) :USING PGLOADER.TRANSFORMS::TINYINT-TO-BOOLEAN) (:SOURCE (:TYPE "bit" :TYPEMOD (= 1 PGLOADER.TRANSFORMS:PRECISION)) :TARGET (:TYPE #8# :DROP-TYPEMOD T) :USING PGLOADER.TRANSFORMS::BITS-TO-BOOLEAN) (:SOURCE (:TYPE #4# :TYPEMOD (< 19 PGLOADER.TRANSFORMS:PRECISION)) :TARGET (:TYPE #9="numeric" :DROP-TYPEMOD T)) (:SOURCE (:TYPE #5# :UNSIGNED T) :TARGET (:TYPE #6# :DROP-TYPEMOD T)) (:SOURCE (:TYPE #6# :UNSIGNED T) :TARGET (:TYPE #10="integer" :DROP-TYPEMOD T)) (:SOURCE (:TYPE #7# :UNSIGNED T) :TARGET (:TYPE #10# :DROP-TYPEMOD T)) (:SOURCE (:TYPE #10# :UNSIGNED T) :TARGET (:TYPE #4# :DROP-TYPEMOD T)) (:SOURCE (:TYPE #5#) :TARGET (:TYPE #6# :DROP-TYPEMOD T)) (:SOURCE (:TYPE #6#) :TARGET (:TYPE #6# :DROP-TYPEMOD T)) (:SOURCE (:TYPE #7#) :TARGET (:TYPE #10# :DROP-TYPEMOD T)) (:SOURCE (:TYPE #10#) :TARGET (:TYPE #10# :DROP-TYPEMOD T)) (:SOURCE (:TYPE #11="float") :TARGET (:TYPE #11# :DROP-TYPEMOD T)) (:SOURCE (:TYPE #4#) :TARGET (:TYPE #4# :DROP-TYPEMOD T)) (:SOURCE (:TYPE "double") :TARGET (:TYPE "double precision" :DROP-TYPEMOD T)) (:SOURCE (:TYPE #9#) :TARGET (:TYPE #9# :DROP-TYPEMOD NIL)) (:SOURCE (:TYPE #12="decimal") :TARGET (:TYPE #12# :DROP-TYPEMOD NIL)) (:SOURCE (:TYPE "tinytext") :TARGET (:TYPE #13="text") :USING PGLOADER.TRANSFORMS::REMOVE-NULL-CHARACTERS) (:SOURCE (:TYPE #13#) :TARGET (:TYPE #13#) :USING PGLOADER.TRANSFORMS::REMOVE-NULL-CHARACTERS) (:SOURCE (:TYPE "mediumtext") :TARGET (:TYPE #13#) :USING PGLOADER.TRANSFORMS::REMOVE-NULL-CHARACTERS) (:SOURCE (:TYPE "longtext") :TARGET (:TYPE #13#) :USING PGLOADER.TRANSFORMS::REMOVE-NULL-CHARACTERS) (:SOURCE (:TYPE #14="varchar") :TARGET (:TYPE #14# :DROP-TYPEMOD NIL) :USING PGLOADER.TRANSFORMS::REMOVE-NULL-CHARACTERS) (:SOURCE (:TYPE #15="char") :TARGET (:TYPE #15# :DROP-TYPEMOD NIL) :USING PGLOADER.TRANSFORMS::REMOVE-NULL-CHARACTERS) (:SOURCE (:TYPE "binary") :TARGET (:TYPE #16="bytea") :USING PGLOADER.TRANSFORMS::BYTE-VECTOR-TO-BYTEA) (:SOURCE (:TYPE "varbinary") :TARGET (:TYPE #16#) :USING PGLOADER.TRANSFORMS::BYTE-VECTOR-TO-BYTEA) (:SOURCE (:TYPE "tinyblob") :TARGET (:TYPE #16#) :USING PGLOADER.TRANSFORMS::BYTE-VECTOR-TO-BYTEA) (:SOURCE (:TYPE "blob") :TARGET (:TYPE #16#) :USING PGLOADER.TRANSFORMS::BYTE-VECTOR-TO-BYTEA) (:SOURCE (:TYPE "mediumblob") :TARGET (:TYPE #16#) :USING PGLOADER.TRANSFORMS::BYTE-VECTOR-TO-BYTEA) (:SOURCE (:TYPE "longblob") :TARGET (:TYPE #16#) :USING PGLOADER.TRANSFORMS::BYTE-VECTOR-TO-BYTEA) (:SOURCE (:TYPE #17="datetime" :DEFAULT #18="0000-00-00 00:00:00" :NOT-NULL T) :TARGET (:TYPE #19="timestamptz" :DROP-DEFAULT T :DROP-NOT-NULL T) :USING PGLOADER.TRANSFORMS::ZERO-DATES-TO-NULL) (:SOURCE (:TYPE #17# :DEFAULT #18#) :TARGET (:TYPE #19# :DROP-DEFAULT T) :USING PGLOADER.TRANSFORMS::ZERO-DATES-TO-NULL) (:SOURCE (:TYPE #17# :ON-UPDATE-CURRENT-TIMESTAMP T :NOT-NULL T) :TARGET (:TYPE #19# :DROP-DEFAULT T :DROP-NOT-NULL T) :USING PGLOADER.TRANSFORMS::ZERO-DATES-TO-NULL) (:SOURCE (:TYPE #20="timestamp" :DEFAULT #18# :NOT-NULL T) :TARGET (:TYPE #19# :DROP-DEFAULT T :DROP-NOT-NULL T) :USING PGLOADER.TRANSFORMS::ZERO-DATES-TO-NULL) (:SOURCE (:TYPE #20# :DEFAULT #18#) :TARGET (:TYPE #19# :DROP-DEFAULT T) :USING PGLOADER.TRANSFORMS::ZERO-DATES-TO-NULL) (:SOURCE (:TYPE #20# :ON-UPDATE-CURRENT-TIMESTAMP T :NOT-NULL T) :TARGET (:TYPE #19# :DROP-DEFAULT T :DROP-NOT-NULL T) :USING PGLOADER.TRANSFORMS::ZERO-DATES-TO-NULL) (:SOURCE (:TYPE #21="date" :DEFAULT "0000-00-00") :TARGET (:TYPE #21# :DROP-DEFAULT T) :USING PGLOADER.TRANSFORMS::ZERO-DATES-TO-NULL) (:SOURCE (:TYPE #21#) :TARGET (:TYPE #21#)) (:SOURCE (:TYPE "year") :TARGET (:TYPE #10# :DROP-TYPEMOD T)) (:SOURCE (:TYPE #17#) :TARGET (:TYPE #19#) :USING PGLOADER.TRANSFORMS::ZERO-DATES-TO-NULL) (:SOURCE (:TYPE #20#) :TARGET (:TYPE #19#) :USING PGLOADER.TRANSFORMS::ZERO-DATES-TO-NULL) (:SOURCE (:TYPE "enum") :TARGET (:TYPE #22=#<FUNCTION PGLOADER.SOURCE.MYSQL::ENUM-OR-SET-NAME>)) (:SOURCE (:TYPE "set") :TARGET (:TYPE #22#) :USING PGLOADER.TRANSFORMS::SET-TO-ENUM-ARRAY) (:SOURCE (:TYPE "geometry") :TARGET (:TYPE #23="point") :USING PGLOADER.TRANSFORMS::CONVERT-MYSQL-POINT) (:SOURCE (:TYPE #23#) :TARGET (:TYPE #23#) :USING PGLOADER.TRANSFORMS::CONVERT-MYSQL-POINT) (:SOURCE (:TYPE "linestring") :TARGET (:TYPE "path") :USING PGLOADER.TRANSFORMS::CONVERT-MYSQL-LINESTRING)))) (PGLOADER.SOURCES:*CAST-RULES* (QUOTE NIL)) (PGLOADER.SOURCE.MYSQL:*DECODING-AS* (QUOTE NIL)) (PGLOADER.PARAMS:*MYSQL-SETTINGS* (QUOTE NIL)) (PGLOADER.PARAMS:ON-ERROR-STOP (GETF (QUOTE NIL) :ON-ERROR-STOP T)) (PGLOADER.PARAMS:*PG-SETTINGS* (PGLOADER.PGSQL:SANITIZE-USER-GUCS (QUOTE NIL))) (PGLOADER.PARAMS:*PGSQL-RESERVED-KEYWORDS* (PGLOADER.PGSQL:LIST-RESERVED-KEYWORDS #24=#<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://BTAadmin@localhost:5432/test {1005734A73}>)) (PGLOADER.PARAMS:*COPY-BATCH-ROWS* (OR NIL PGLOADER.PARAMS:*COPY-BATCH-ROWS*)) (PGLOADER.PARAMS:*COPY-BATCH-SIZE* (OR NIL PGLOADER.PARAMS:*COPY-BATCH-SIZE*)) (PGLOADER.PARAMS:*PREFETCH-ROWS* (OR NIL PGLOADER.PARAMS:*PREFETCH-ROWS*)) (PGLOADER.PARAMS:*ROWS-PER-RANGE* (OR NIL PGLOADER.PARAMS:*ROWS-PER-RANGE*)) (PGLOADER.PARAMS:*IDENTIFIER-CASE* (OR NIL PGLOADER.PARAMS:*IDENTIFIER-CASE*)) (PGLOADER.PARSER::SOURCE (MAKE-INSTANCE (QUOTE PGLOADER.SOURCE.MYSQL:COPY-MYSQL) :TARGET-DB #24# :SOURCE-DB #<PGLOADER.SOURCE.MYSQL:MYSQL-CONNECTION mysql://masterUser@mydbinstance.cuv0bgvg64rc.us-west-1.rds.amazonaws.com:3306/paris {10055F0423}>))) NIL (PGLOADER.LOAD:COPY-DATABASE PGLOADER.PARSER::SOURCE :INCLUDING (QUOTE NIL) :EXCLUDING (QUOTE NIL) :MATERIALIZE-VIEWS (QUOTE NIL) :ALTER-TABLE (QUOTE NIL) :ALTER-SCHEMA (QUOTE NIL) :SET-TABLE-OIDS T :ON-ERROR-STOP PGLOADER.PARAMS:ON-ERROR-STOP) NIL)) :START-LOGGER NIL :FLUSH-SUMMARY T :SUMMARY NIL :LOG-FILENAME NIL :LOG-MIN-MESSAGES NIL :CLIENT-MIN-MESSAGES NIL)
16: (PGLOADER:LOAD-DATA :FROM #<PGLOADER.SOURCE.MYSQL:MYSQL-CONNECTION mysql://masterUser@mydbinstance.cuv0bgvg64rc.us-west-1.rds.amazonaws.com:3306/paris {10055F0423}> :INTO #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://BTAadmin@localhost:5432/test {1005734A73}> :ENCODING :UTF-8 :FIELDS NIL :TARGET-TABLE-NAME NIL :OPTIONS NIL :GUCS NIL :CASTS NIL :BEFORE NIL :AFTER NIL :START-LOGGER NIL :FLUSH-SUMMARY T)
17: (PGLOADER.MONITOR::CALL-WITH-MONITOR #<CLOSURE (LAMBDA NIL :IN PGLOADER::MAIN) {100530698B}>)
18: (PGLOADER::MAIN ("pgloader" "--debug" "mysql://masterUser:password@mydbinstance.cuv0bgvg64rc.us-west-1.rds.amazonaws.com/paris" "postgresql://BTAadmin@localhost/test"))
19: ((LAMBDA NIL :IN "/private/tmp/pgloader-20180705-16956-54q8li/pgloader-3.5.2/dumper-2SKVI5f7.lisp"))
20: ((FLET SB-UNIX::BODY :IN SAVE-LISP-AND-DIE))
21: ((FLET "WITHOUT-INTERRUPTS-BODY-36" :IN SAVE-LISP-AND-DIE))
22: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))

**Comment by dimitri** [comment]
So the culprit is `5: (QMYND-IMPL::MYSQL-CS-COLL-TO-CHARACTER-ENCODING 76)`, and as you can see at https://github.com/qitab/qmynd/blob/master/src/common/charsets.lisp the driver things that the character encoding 76 is not used. Can you find a source documentation explaining what this encoding number is or should be on your system?

You can use the DECODING AS clause of pgloader to force it to use a known encoding rather than the one MySQL reports.

**Comment by Benji410** [comment]
I solved the issue!
The issue is similar to -- > https://github.com/dimitri/pgloader/issues/760

It's something to do with the most recent version of MySQL. 
But I just loaded my sqldump to a MySQL 5.7 server and was able to transfer to pSQL with no problems.

**Comment by dimitri** [comment]
It would be nice to know what the 76 magic number is used for these days in MySQL, so that I could fix the driver...

**Comment by kaatt** [comment]
I was getting `MYSQL-UNSUPPORTED-AUTHENTICATION` so I added this line to `my.cnf` which fixed it:
```default-authentication-plugin=mysql_native_password```

Now I'm getting this `76 fell through ECASE expression`.

@dimitri You can reproduce this easily by using MySQL 8 instead of 5.*.

I'm gonna post some more info if I find anything.

**Comment by dimitri** [comment]
Please try to `make clean` then `make` again, and it should be good with changes added to qmynd.

**Comment by KaruguDev** [comment]
I am still having the same issue, i am using pgloader version 3.6.1

**Comment by phoe** [comment]
Does the error still occur with 3.6.2?

**Comment by KaruguDev** [comment]
No 3.6.2 addresses it thanks

**Comment by Vovan-VE** [comment]
Still reproducing this in 3.6.2.
```
pgloader version "3.6.2"
compiled with SBCL 2.0.1.debian
```

The database was migrated from MySQL 5.7 to MySQL 8 in Aug 2020 with Ubuntu upgrade 18.04 to 20.04.
The database has only `utf8mb4 COLLATE utf8mb4_unicode_ci` character set everywhere.
