### ISSUE TITLE
PGLOADER installation in centos

### ISSUE THREAD

**Issue by sampath4242** [dimitri/pgloader#876]
Hi All,
Im trying to install PGLOADER in cent os. I have followed the below steps.

```
sudo yum install -y git
git clone https://github.com/dimitri/pgloader.git
cd pgloader
chmod +x ./bootstrap-centos7.sh
sudo ./bootstrap-centos7.sh
make pgloader
```

When i run the "make pgloader" i get below  error and not able to connect to host. Please assist

```
/tmp/pgloader-master # make pgloader
make: sbcl: Command not found
mkdir -p build
curl -o build/quicklisp.lisp http://beta.quicklisp.org/quicklisp.lisp

curl: (7) couldn't connect to host
make: *** [build/quicklisp/setup.lisp] Error 7
```

**Comment by sampath4242** [comment]
hi

**Comment by dimitri** [comment]
Please use the release at 
https://github.com/dimitri/pgloader/releases/download/v3.6.0/pgloader-bundle-3.6.0.tgz so that you don't have to fetch the build-dependencies at compile time.
