### ISSUE TITLE
Way to mark an enum as being the same between multiple tables?

### ISSUE THREAD

**Issue by mzealey** [dimitri/pgloader#880]
- [x] pgloader --version
  
```
pgloader version "3.4.1"
compiled with SBCL 1.3.3.debian

```
  
  - [ ] did you test a fresh compile from the source tree?
    
  - [x] did you search for other similar issues?
    
  - [x] how can I reproduce the bug?

Let's say I have two tables, a and b with an enum column.

```
CREATE TABLE a ( col ENUM('a', 'b') not null );
CREATE TABLE b ( col ENUM('a', 'b') not null );
```

When I run this through pgloader it creates a separate enum type for both tables.

This would not normally be an issue, apart from the case when I want to move data between the two tables efficiently (ie without casting). `INSERT INTO a SELECT * FROM b` fails with an error like "ERROR:  column "col" is of type a_col but expression is of type b_col"

Is there a way to say "a and b use the same enum type" and/or do this automatically if enum maps are the same?

**Comment by dimitri** [comment]
In MySQL the enum types are declared _inline_, which means they are separate. In PostgreSQL you may create a single enum type and re-use it as you see fit of course. A solution to do that with pgloader would be to create the enum type in a `BEFORE LOAD` clause and then install a user-defined casting rule with the `CAST` clause where you target the newly created type for columns a.col and b.col:

    cast column a.col to your_enum
         column b.col to your_enum

**Comment by mzealey** [comment]
OK I resolved this now by doing a post-load conversion of the enum type like the below. It is a shame there is no way to just specify that multiple enums should be grouped by content or so though.

For reference:

```
AFTER LOAD DO
    $$ alter table stat_client_day_archive alter column db_type set default null $$,
    $$ alter table stat_client_day_archive
            alter column db_type type stat_client_day_db_type using db_type::text::stat_client_day_db_type,
            alter column db_type set default ''::stat_client_day_db_type $$,
```
