### ISSUE TITLE
Way to translate JSON column data into postgres array?

### ISSUE THREAD

**Issue by mzealey** [dimitri/pgloader#881]
- [x] pgloader --version
  
```
pgloader version "3.4.1"
compiled with SBCL 1.3.3.debian
```
  
  - [ ] did you test a fresh compile from the source tree?
    
  - [x] did you search for other similar issues?
    
  - [x] how can I reproduce the bug?

Due to no array support in mysql I was emulating this by using JSON storing a flat array. Like:

```
INSERT INTO table SET array_num = '[1,2,3]';
INSERT INTO table SET array_text = '["foo","bar"]';
```

Now that we are migrating into postgres it would be nice if there was transform function in pgloader that I can use which would change the data type to eg `int[]` or `text[]` and convert the data on import.

**Comment by dimitri** [comment]
If the input is compatible with JSON representation in PostgreSQL then I all you have to do is to install a user-defined casting rule. If not, then a transformation function is needed. What happens when you try?

**Comment by mzealey** [comment]
OK I cannot seem to find any documentation or examples in the repository of how to do a user-defined casting rule - can you point me at the right place please?

**Comment by mzealey** [comment]
Actually I have been able to do this hackily with the below:

```
AFTER LOAD DO
    $$ alter table cache alter column tags type int[] using translate(tags::text, '[]', '{}')::int[] $$,
    $$ alter table songs alter column alternative_titles  type text[] using translate(alternative_titles::text, '[]', '{}')::text[] $$,
```

**Comment by dimitri** [comment]
> OK I cannot seem to find any documentation or examples in the repository of how to do a user-defined casting rule - can you point me at the right place please?

  - https://pgloader.readthedocs.io/en/latest/ref/mysql.html#mysql-database-casting-rules
  - https://github.com/dimitri/pgloader/blob/master/test/mysql/my.load
