### ISSUE TITLE
Empty AUTOINCREMENT SQLite Sequence

### ISSUE THREAD

**Issue by drouarb** [dimitri/pgloader#882]
- [X] pgloader --version
  
```
root@810709360a55:~/pgloader# ./build/bin/pgloader  --version
WARNING:
Couldn't re-execute SBCL with proper personality flags (/proc isn't mounted? setuid?)
Trying to continue anyway.
pgloader version "3.5.b8e8cf7"
compiled with SBCL 1.3.1.debian
```
  
  - [X] did you test a fresh compile from the source tree?
Yes
  - [X] did you search for other similar issues?
Yes, an old issue is closed
https://github.com/dimitri/pgloader/issues/556

  - [X] how can I reproduce the bug?

The problem is that the AUTOINCREMENT PRIMARY KEY uses a [SQLite sequence](https://www.sqlite.org/fileformat2.html#seqtab) but this sequence isn't initialized by SQLite if there is no data in this table. When pgloader imports the data in the PostgreSQL database, it convert the sequence to PostgreSQL, but if the sequence isn't in the `sqlite_sequence` table, the autoincrement isn't copied to the PostgreSQL database.

It would also be fine if I would be able to make the primary key be a SERIAL but the following casting rule isn't working :
```
type int with extra auto_increment to serial keep typemod keep default keep not null 
```

Here is the SQLite database: https://mega.nz/#!PQsCACQK!Dos6ndyL3ng0hBVC0Zyg9mkmjQxlzkEpAphPgP9xAD4
```
LOAD database
     FROM '/workspace/bridge/plex.db'
     INTO postgresql://plex:plex@192.168.65.2:5432/plex

 WITH   include drop, create tables, create indexes, reset sequences, workers = 2

 CAST type integer when (= precision 8) to bigint drop typemod using integer-to-string,
      type integer to integer drop typemod using integer-to-string,
      type varchar to varchar

 EXCLUDING TABLE names like	'spellfix_metadata_titles',
				'spellfix_metadata_titles_vocab',
				'spellfix_tag_titles',
				'spellfix_tag_titles_vocab'


 set work_mem to '16MB', maintenance_work_mem to '512 MB';
```

  - [X] pgloader output you obtain
https://gist.github.com/drouarb/bd70681f59d20be00565c9c36d4dd5a4

  - [x] data that is being loaded, if relevant
  
```
2019-01-02T15:14:32.720000Z SQL CREATE TABLE media_part_settings
(
  id                          integer,
  account_id                  integer,
  media_part_id               integer,
  selected_audio_stream_id    integer,
  selected_subtitle_stream_id integer,
  settings                    varchar(255),
  created_at                  timestamptz,
  updated_at                  timestamptz,
  changed_at                  bigint default '0'
);
```

  - [X] How the data is different from what you expected, if relevant
In the `media_part_settings` that is loaded without data:
```
 cid |     name      |    type    | notnull | dflt_value  | pk
-----+---------------+------------+---------+-------------+----
   1 | id            | integer    |       1 |             |  1
   2 | account_id    | integer    |       0 |             |  0
   3 | media_part_id | integer    |       0 |             |  0
   9 | changed_at    | integer(8) |       0 | '0'::bigint |  0
```

The `metadata_items` that is loaded with some data:
```
 cid |          name           |     type     | notnull |                 dflt_value                 | pk
-----+-------------------------+--------------+---------+--------------------------------------------+----
   1 | id                      | integer(8)   |       1 | nextval('metadata_items_id_seq'::regclass) |  1
   2 | library_section_id      | integer      |       0 |                                            |  0
   2 | library_section_id      | integer      |       0 |                                            |  0
   3 | parent_id               | integer      |       0 |                                            |  0
   4 | metadata_type           | integer      |       0 |                                            |  0
   4 | metadata_type           | integer      |       0 |                                            |  0
   5 | guid                    | varchar(255) |       0 |                                            |  0
   7 | title                   | varchar(255) |       0 |                                            |  0
   8 | title_sort              | varchar(255) |       0 |                                            |  0
   8 | title_sort              | varchar(255) |       0 |                                            |  0
   9 | original_title          | varchar(255) |       0 |                                            |  0
  19 | index                   | integer      |       0 |                                            |  0
  20 | absolute_index          | integer      |       0 |                                            |  0
  32 | originally_available_at | datetime     |       0 |                                            |  0
  37 | added_at                | datetime     |       0 |                                            |  0
  37 | added_at                | datetime     |       0 |                                            |  0
  38 | created_at              | datetime     |       0 |                                            |  0
  40 | deleted_at              | datetime     |       0 |                                            |  0
  43 | hash                    | varchar(255) |       0 |                                            |  0
  45 | changed_at              | integer(8)   |       0 | '0'::bigint                                |  0
  46 | resources_changed_at    | integer(8)   |       0 | '0'::bigint                                |  0
```

I would like to be able to set the PRIMARY KEY to SERIAL or to initialize a sequence for each PRIMARY KEY.

**Comment by dimitri** [comment]
The problem in that case is that there's no reliable way that I can see to make the difference in SQLite catalogs in between a column that is using a sequence that has not been used yet, and a column that is not using a sequence. 

The guard expression `with extra auto_increment` only applies to columns that are known to be using a sequence in SQLite, which doesn't apply here. You could hack the schema after load, or use a per-column custom casting rule, as in the following example:

```
 CAST column media_part_settings.id to serial,
      type integer when (= precision 8)
        to bigint drop typemod using integer-to-string,
      type integer to integer drop typemod using integer-to-string,
      type varchar to varchar
```

**Comment by drouarb** [comment]
There is a way to detect this in the sqlite_master table. The second answer show a way to get all the auto-increment columns even if the sequence isn't initialized. 
https://stackoverflow.com/a/47458402

I wrote a bash script to force initialization of sequences if someone need it: https://gist.github.com/drouarb/8f628f870fbd2e65db89a6cb0cc8a4e0

**Comment by dimitri** [comment]
Please compile a fresh copy of pgloader and try again, I think this time it should be good. I had to parse the SQL statements from SQLite catalogs, which I wish I wouldn't need to: the whole idea of introspecting the catalogs of a live database is that we would avoid parsing SQL. Anyway, here we are, thanks again SQLite.

**Comment by thenik** [comment]
Hello, 

looks like that I have a simalar issue,  my pgloader version is "3.6.3~devel"

sample table in sqlite with autoincrement key
![image](https://github.com/dimitri/pgloader/assets/1731242/2316c7e9-a737-4d4a-b88c-dcff085031ed)

how it was migrated to pstgresql
![image](https://github.com/dimitri/pgloader/assets/1731242/be663602-e9f3-4719-98cd-042cb60b5451)

and here is an error that I got from the code

![image](https://github.com/dimitri/pgloader/assets/1731242/855f703e-df49-4319-ad48-27f78d30e504)

23502: null value in column "id" of relation "translations" violates not-null constraint

Any ideas how to adjust it via pgloader ?

**Comment by thenik** [comment]
**looks like I know how to reproduce that:**
If a source table does not have rows (is empty) pgloader does not migrate autoincrement key right.
