### ISSUE TITLE
Make docs a bit clearer around Docker usage (loading from CSV/ config file for example)

### ISSUE THREAD

**Issue by morganics** [dimitri/pgloader#885]
Documentation; just make a clearer example around loading data / config using Docker (as the volume has to be mounted, otherwise the file won't be found). 

e.g. 

```
docker run --rm --name pgloader -v /path/to/file:/data dimitri/pgloader:latest pgloader /data/csvToDbScript.txt
```

Similarly the same filename has to be used in the config file;

```
LOAD CSV
     FROM '/data/myfile.csv' 
     INTO postgresql://mydbip/mydb?mytable
```

**Comment by dimitri** [comment]
That's more about docker than it is about pgloader, and I'm not good at using docker. I will gladly accept a PR that improves our docs around using pgloader in docker if you feel that it would be an improvement, though!
