### ISSUE TITLE
No data 

### ISSUE THREAD

**Issue by Benji410** [dimitri/pgloader#886]
pgloader --version

pgloader version "3.5.2"
compiled with SBCL 1.4.9
MySQL version '5.7.23'
PSQL version '11.1'

I'm trying to convert a MySQL database on my amazon RDS to Postgres on my localhost

I use this command and everything seems to be fine, no errors. 

pgloader  mysql://'username':'password'@'host'/'db_name' pgsql:///'db_name'

But when I look into the database, only the relation names are copied over, there is no data inside them. 

I've looked into these issues, #654 and #655, but they're not the issue. What could be going on here?

**Comment by Benji410** [comment]
Update: checking the database again, it seems it is just one particular relation that is not migrated over. (I was only looking at this particular table when checking to see if data was migrated and assumed all the tables weren't migrated over, but it's just the one in particular) 

Is pgloader not able to migrate a table over for any reason?

**Comment by dimitri** [comment]
Can you look at the logs output from pgloader and see if there's any ERROR in there?

**Comment by dimitri** [comment]
Can you retry in `--debug` mode where we will have lots of logs and some clues to figure out what's happening?

**Comment by Benji410** [comment]
I tried the migration again and the data for that table migrated over this time.
