### ISSUE TITLE
cannot import from a mysql database on another server

### ISSUE THREAD

**Issue by azinyue** [dimitri/pgloader#887]
Hey there, I am quite new to postgres and pgloader, and I want to move my database from mariadb to postgres. However when I run the following command :

```
./bin/pgloader --debug --verbose mysql://root:vindata@192.168.1.31:3306/vindataARVMAG?sslmode=disable postgresql:///vindataARV
```
I get the error: 
```
Failed to connect to mysql at "192.168.1.31" (port 3306) as user "root": Condition USOCKET:HOST-UNREACHABLE-ERROR was signalled
```

When I add ?sslmode=disable I get the following:

```
sb-impl::*default-external-format* :UTF-8
tmpdir: #P"/tmp/pgloader/"
2019-01-14T19:33:33.046000+01:00 NOTICE Starting pgloader, log system is ready.
2019-01-14T19:33:33.077000+01:00 INFO Starting monitor
2019-01-14T19:33:33.089000+01:00 INFO Stopping monitor
```

Nothing is uploaded into the postgres database. Have gone through other posts to help find a solution to no avail. 

Using pgloader version 3.4.1   compiled from source.

Help needed. Thanks

**Comment by dimitri** [comment]
Hi @azinyue. The first error is a classic TCP/IP error where pgloader failed to connect to MySQL, please review your connection string? The other one is more strange, and before trying to understand it... can you please use a recent version of pgloader, or even a local build of the current git master's branch?

If it comes to having to fix a bug you will have to build from sources to get the fix anyway...

**Comment by azinyue** [comment]
How stupid of me... didnt see that at all. Thanks
Been able to connect and transfer my data. 
Let the learning begin.

More power to you SIR!
