### ISSUE TITLE
Incorrect line number reporting of erroneous rows

### ISSUE THREAD

**Issue by amersonl** [dimitri/pgloader#89]
Hi, 

great work on PGLoader! However, there seems to be an error in the line number reporting of erroneous rows. For example, I have a 50 row file that has an erroneous row on line 7. When I set "batch rows = 2", here is the output I see:

Database error 22P04: missing data for column "file_country_code" 

CONTEXT: COPY prof, line 1: "BAN .... Banker ..."

Would be great to have a fix soon! Thanks!

**Comment by UtterlyBGroovy** [comment]
Hi Dmitri,

I know this is closed but this is the issue I'm having.

Can pgloader report the actual error line numbers?

As pgloader is parsing the Postgres returned error messages, and presumably _could_ know the line numbers (from the original file) that it sent to be loaded, it _could_ convert the Postgres returned batch error line numbers in the actually useful original file error line numbers.

     Regards

**Comment by dimitri** [comment]
Hi @UtterlyBGroovy ; while this could be done, we need also to take into account file formats where a single row can span multiple physical lines. Still, we could attach the source line information to every row of data that we parse, but for that we would need the cooperation of the CSV parsing library that pgloader uses: https://github.com/AccelerationNet/cl-csv.

Do you want to contribute that feature?
