### ISSUE TITLE
Unable To Build In Debian

### ISSUE THREAD

**Issue by jsmith0103** [dimitri/pgloader#890]
- [x] pgloader --version
  
    ```
    Current github version - 3.5.2?
    ```
  
  - [x] did you test a fresh compile from the source tree?
    
   Issue that compiling from sources is not working in Debian.
    
  - [x] did you search for other similar issues?
    Yes
  - [x] how can I reproduce the bug?
Debian Strech, attempt to compile from source using the instructions in the ReadMe.

-- EDIT THIS FILE TO MATCH YOUR BUG REPORT
  - [x] pgloader output you obtain
  Below is bottom of command window when hangup occurs.

```
; Loading "zs3"
;;; Checking for wide character support... WARNING: Lisp implementation doesn't use UTF-16, but accepts surrogate code points.
 yes, using code points.
.
;;; Checking for wide character support... WARNING: Lisp implementation doesn't use UTF-16, but accepts surrogate code points.
 yes, using code points.
;;; Building Closure with CHARACTER RUNES
.................................................
[package runes]...................................
[package utf8-runes]..............................
[package runes-encoding]..........................
[package hax].....................................
[package cxml]....................................
[package sax].....................................
..................................................
[package cxml-xmls]...............................
[package dom].....................................
[package rune-dom]................................
[package klacks]..................................
[package domtest].................................
[package domtest-tests]...........................
[package xmlconf].....
debugger invoked on a SB-INT:SIMPLE-PROGRAM-ERROR in thread
#<THREAD "main thread" RUNNING {1001E06C53}>:
  invalid number of arguments: 5

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Retry
                                     compiling #<IRONCLAD-SOURCE-FILE "ironclad" "src" "common">.
  1: [ACCEPT                       ] Continue, treating
                                     compiling #<IRONCLAD-SOURCE-FILE "ironclad" "src" "common">
                                     as having been successful.
  2:                                 Retry ASDF operation.
  3: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  4: [ABORT                        ] Give up on "zs3"
  5:                                 Give up on "pgloader"
  6: [CONTINUE                     ] Ignore runtime option --eval "(ql:quickload \"pgloader\")".
  7:                                 Skip rest of --eval and --load options.
  8:                                 Skip to toplevel READ/EVAL/PRINT loop.
  9: [EXIT                         ] Exit SBCL (calling #'EXIT, killing the process).

(SB-X86-64-ASM::|movzx| #<SB-ASSEM:SEGMENT :TYPE :REGULAR> #<SB-C::VOP :INFO UB32REF/LE :ARGS #<SB-C:TN-REF :TN #<SB-C:TN INPUT-BLOCK1!1[RDI]> :WRITE-P NIL :VOP UB32REF/LE> :RESULTS #<SB-C:TN-REF :TN #<SB-C:TN t2[RDX]> :WRITE-P T :VOP UB32REF/LE>> (:DWORD :QWORD) #<SB-C:TN t2[RDX]> #<SB-X86-64-ASM::EA :DWORD base=#<SB-C:TN INPUT-BLOCK1!1[RDI]> index=#<SB-C:TN t3[RDX]> disp=1>) [tl,external]
0] 

```

**Comment by dimitri** [comment]
Please either update your local copy of the build dependencies by doing `make clean` then `make` again, or maybe build from the pre-release at 
https://github.com/dimitri/pgloader/releases/tag/v3.6.0

**Comment by jsmith0103** [comment]
Same error after make clean and make again; build from prerelease gave following output/error:

mkdir -p bin
sbcl --noinform --no-sysinit --no-userinit --load bundle.lisp                           \
             --eval '(asdf:load-system :buildapp)'                    \
             --eval '(buildapp:build-buildapp "bin/buildapp")'                  \
             --eval '(quit)'
; compiling file "/home/jake/Downloads/pgloader/software/buildapp-1.5.6/package.lisp" (written 07 DEC 2018 03:37:46 AM):
; compiling (DEFPACKAGE #:BUILDAPP ...)
; compiling (IN-PACKAGE #:BUILDAPP)

; /home/jake/.cache/common-lisp/sbcl-1.3.14.debian-linux-x64/home/jake/Downloads/pgloader/software/buildapp-1.5.6/package-TMP.fasl written
; compilation finished in 0:00:00.005
; compiling file "/home/jake/Downloads/pgloader/software/buildapp-1.5.6/utils.lisp" (written 07 DEC 2018 03:37:46 AM):
; compiling (IN-PACKAGE #:BUILDAPP)
; compiling (DEFUN GET-ARGS ...)
; compiling (DEFMACRO BACKTRACE-AS-LIST ...)
; compiling (DEFMACRO QUIT ...)
; compiling (DEFMACRO RUN-PROGRAM ...)
; compiling (DEFUN NATIVE-NAMESTRING ...)
; compiling (DEFPARAMETER *ALPHABET* ...)
; compiling (DEFUN RANDOM-STRING ...)
; compiling (DEFUN CALL-WITH-TEMPORARY-OPEN-FILE ...)
; compiling (DEFMACRO WITH-TEMPFILE ...)
; compiling (DEFCLASS PSEUDOSYMBOL ...)
; compiling (DEFMETHOD PRINT-OBJECT ...)
; compiling (DEFUN MAKE-PSEUDOSYMBOL ...)
; compiling (DEFCLASS DISPATCHED-ENTRY ...)
; compiling (DEFMETHOD PRINT-OBJECT ...)
; compiling (DEFINE-CONDITION MALFORMED-DISPATCH-ENTRY ...)
; compiling (DEFUN MAKE-DISPATCHED-ENTRY ...)
; compiling (DEFUN DEFAULT-ENTRY-P ...)
; compiling (DEFUN DIRECTORIZE ...)
; compiling (DEFUN ALL-ASDF-DIRECTORIES ...)
; compiling (DEFUN COPY-FILE ...)
; compiling (DEFUN FILE-LINES ...)
; compiling (DEFUN FLATTEN ...)

; /home/jake/.cache/common-lisp/sbcl-1.3.14.debian-linux-x64/home/jake/Downloads/pgloader/software/buildapp-1.5.6/utils-TMP.fasl written
; compilation finished in 0:00:00.123
; compiling file "/home/jake/Downloads/pgloader/software/buildapp-1.5.6/asdf-files.lisp" (written 07 DEC 2018 03:37:46 AM):
; compiling (IN-PACKAGE #:BUILDAPP)
; compiling (DEFUN MANIFEST-FILE-FILES ...)
; compiling (DEFUN ASDF-PATH-FILES ...)
; compiling (DEFUN ASDF-TREE-FILES ...)
; compiling (DEFUN ASDF-DIRECTIVE-FILES ...)

; /home/jake/.cache/common-lisp/sbcl-1.3.14.debian-linux-x64/home/jake/Downloads/pgloader/software/buildapp-1.5.6/asdf-files-TMP.fasl written
; compilation finished in 0:00:00.021
; compiling file "/home/jake/Downloads/pgloader/software/buildapp-1.5.6/dumper.lisp" (written 07 DEC 2018 03:37:46 AM):
; compiling (IN-PACKAGE #:BUILDAPP)
; compiling (DEFCLASS DUMPER ...)
; compiling (DEFGENERIC NEEDS-ASDF-P ...)
; compiling (DEFMETHOD PRINT-OBJECT ...)
; compiling (DEFGENERIC ASDF-SYSTEM-FILES ...)
; compiling (DEFUN DISPATCHED-ENTRY-FORM ...)
; file: /home/jake/Downloads/pgloader/software/buildapp-1.5.6/dumper.lisp
; in: DEFUN DISPATCHED-ENTRY-FORM
;     (MACROEXPAND-1 (BUILDAPP::QUIT 1))
; 
; note: The first argument never returns a value.
; 
; note: deleting unreachable code

; compiling (DEFGENERIC ENTRY-FUNCTION-FORM ...)
; compiling (DEFGENERIC ENTRY-FUNCTION-CHECK-FORM ...)
; compiling (DEFPARAMETER *DUMPABLE-FORMS* ...)
; compiling (DEFMACRO DUMPABLE ...)
; compiling (DEFUN DUMP-FORM ...)

; /home/jake/.cache/common-lisp/sbcl-1.3.14.debian-linux-x64/home/jake/Downloads/pgloader/software/buildapp-1.5.6/dumper-TMP.fasl written
; compilation finished in 0:00:00.069
; compiling file "/home/jake/Downloads/pgloader/software/buildapp-1.5.6/command-line.lisp" (written 07 DEC 2018 03:37:46 AM):
; compiling (IN-PACKAGE #:BUILDAPP)
; compiling (DEFINE-CONDITION COMMAND-LINE-ERROR ...)
; compiling (DEFINE-CONDITION ODD-NUMBER-OF-ARGUMENTS ...)
; compiling (DEFINE-CONDITION PROVIDED-ARGUMENT-ERROR ...)
; compiling (DEFINE-CONDITION REQUIRED-ARGUMENT-MISSING ...)
; compiling (DEFINE-CONDITION UNKNOWN-ARGUMENT ...)
; compiling (DEFINE-CONDITION MISSING-OUTPUT-ARGUMENT ...)
; compiling (DEFINE-CONDITION DUPLICATE-ARGUMENT ...)
; compiling (DEFINE-CONDITION DUPLICATE-DEFAULT-DISPATCHED-ENTRY ...)
; compiling (DEFINE-CONDITION ENTRY-AND-DISPATCHED-ENTRY ...)
; compiling (DEFUN ARGUMENT-KEYWORD ...)
; compiling (DEFMACRO POPFLAG ...)
; compiling (DEFUN COMMAND-LINE-DUMPER ...)

; /home/jake/.cache/common-lisp/sbcl-1.3.14.debian-linux-x64/home/jake/Downloads/pgloader/software/buildapp-1.5.6/command-line-TMP.fasl written
; compilation finished in 0:00:00.071
; compiling file "/home/jake/Downloads/pgloader/software/buildapp-1.5.6/buildapp.lisp" (written 07 DEC 2018 03:37:46 AM):
; compiling (IN-PACKAGE #:BUILDAPP)
; compiling (DEFPARAMETER *OUTPUT-TYPE-PATHNAME* ...)
; compiling (DEFPARAMETER *SHORT-USAGE* ...)
; compiling (DEFPARAMETER *USAGE* ...)
; compiling (DEFINE-CONDITION SILENT-EXIT-ERROR ...)
; compiling (DEFPARAMETER *SYSTEM-LOAD-OUTPUT* ...)
; compiling (DEFPARAMETER *LOGFILE-OUTPUT* ...)
; compiling (DUMPABLE CHECK-PSEUDOSYMBOL ...)
; compiling (DEFUN PSEUDOSYMBOL-CHECK-FORM ...)
; compiling (DUMPABLE DEBUGGER ...)
; compiling (DEFUN COMMAND-LINE-DEBUGGER ...)
; file: /home/jake/Downloads/pgloader/software/buildapp-1.5.6/buildapp.lisp
; in: DEFUN COMMAND-LINE-DEBUGGER
;     (BUILDAPP::BACKTRACE-AS-LIST)
; ==>
;   (BACKTRACE-AS-LIST)
; 
; caught STYLE-WARNING:
;   The function SB-DEBUG:BACKTRACE-AS-LIST has been deprecated as of SBCL version 1.2.15.
;   
;   Use SB-DEBUG:LIST-BACKTRACE instead.
;   
;   In future SBCL versions SB-DEBUG:BACKTRACE-AS-LIST will signal a full warning
;   at compile-time.
;   See also:
;     The SBCL Manual, Node "Deprecation Conditions"

; compiling (DUMPABLE ASDF-OPS ...)
; compiling (DUMPABLE FILE-OPS ...)
; compiling (DEFUN DUMPER-ACTION-FORMS ...)
; compiling (DEFUN INVOKE-DEBUGGER-HOOK-WRAPPER ...)
; compiling (DEFUN DUMPER-ACTION-FORM ...)
; compiling (DEFUN DUMPFILE-FORMS ...)
; compiling (DEFUN WRITE-DUMPFILE ...)
; compiling (DEFUN DUMP-TO-FILE ...)
; compiling (DEFUN MAIN ...)
; compiling (DEFUN BUILD-BUILDAPP ...)
; compiling (DEFUN BUILDAPP-INIT ...)
; compiling (PUSHNEW (QUOTE BUILDAPP-INIT) ...)

; /home/jake/.cache/common-lisp/sbcl-1.3.14.debian-linux-x64/home/jake/Downloads/pgloader/software/buildapp-1.5.6/buildapp-TMP.fasl written
; compilation finished in 0:00:00.136
WARNING:
   Lisp compilation had style-warnings while
   compiling #<CL-SOURCE-FILE "buildapp" "buildapp">
WARNING:
   Reference to deprecated function (SB-DEBUG:BACKTRACE-AS-LIST) from COMMAND-LINE-DEBUGGER
; 
; compilation unit finished
;   caught 1 STYLE-WARNING condition
;   printed 2 notes
;; loading system "buildapp"
bin/buildapp      --logfile /tmp/pgloader-bundle-build.log     \
                         --require sb-posix --require sb-bsd-sockets --require sb-rotate-byte                             \
                         --sbcl sbcl                                 \
                         --asdf-tree .                                \
                         --load-system pgloader                    \
                         --eval '(setf pgloader.params::*version-string* "3.6.0")' \
                         --load local-projects/pgloader-3.6.0/src/hooks.lisp              \
                         --entry pgloader:main                        \
                         --dynamic-space-size 4096              \
                         --compress-core                         \
                         --output bin/pgloader.tmp
;; loading system "pgloader"
Fatal SIMPLE-PROGRAM-ERROR:
  invalid number of arguments: 5
Makefile:47: recipe for target 'bin/pgloader' failed
make: *** [bin/pgloader] Error 1

**Comment by dimitri** [comment]
Can you try the new experimental version of the build process, that I think is already in 3.6.0 snapshot and available as `make save`?

**Comment by jsmith0103** [comment]
Here's the tail end of `make save`

; /home/jake/.cache/common-lisp/sbcl-1.3.14.debian-linux-x64/opt/pgloader/software/ironclad-v0.43/src/sbcl-opt/cpu-features-tmpUVEUD2ZN.fasl written
; compilation finished in 0:00:00.007
; compiling file "/opt/pgloader/software/ironclad-v0.43/src/common.lisp" (written 07 DEC 2018 03:37:53 AM):
; compiling (IN-PACKAGE :CRYPTO)
; compiling (DEFMACRO DEFCONST ...)
; compiling (DEFTYPE INDEX ...)
; compiling (DEFTYPE INDEX+1 ...)
; compiling (DEFTYPE SIMPLE-OCTET-VECTOR ...)
; compiling (DEFUN BURN-BABY-BURN ...)
; compiling (DEFUN HOLD-ME-BACK ...)
; compiling (DECLAIM (INLINE FIRST-BYTE))
; compiling (DECLAIM (FTYPE # ...))
; compiling (DEFUN FIRST-BYTE ...)
; compiling (DECLAIM (INLINE SECOND-BYTE))
; compiling (DECLAIM (FTYPE # ...))
; compiling (DEFUN SECOND-BYTE ...)
; compiling (DECLAIM (INLINE THIRD-BYTE))
; compiling (DECLAIM (FTYPE # ...))
; compiling (DEFUN THIRD-BYTE ...)
; compiling (DECLAIM (INLINE FOURTH-BYTE))
; compiling (DECLAIM (FTYPE # ...))
; compiling (DEFUN FOURTH-BYTE ...)
; compiling (DECLAIM (INLINE FIFTH-BYTE))
; compiling (DECLAIM (FTYPE # ...))
; compiling (DEFUN FIFTH-BYTE ...)
; compiling (DECLAIM (INLINE SIXTH-BYTE))
; compiling (DECLAIM (FTYPE # ...))
; compiling (DEFUN SIXTH-BYTE ...)
; compiling (DECLAIM (INLINE SEVENTH-BYTE))
; compiling (DECLAIM (FTYPE # ...))
; compiling (DEFUN SEVENTH-BYTE ...)
; compiling (DECLAIM (INLINE EIGHTH-BYTE))
; compiling (DECLAIM (FTYPE # ...))
; compiling (DEFUN EIGHTH-BYTE ...)
; compiling (DEFUN UBREF-FUN-NAME ...)
; compiling (DECLAIM (INLINE MOD32+) ...)
; compiling (DEFUN MOD32+ ...)
; compiling (DEFINE-COMPILER-MACRO MOD32+ ...)
; compiling (DECLAIM (INLINE MOD32-) ...)
; compiling (DEFUN MOD32- ...)
; compiling (DEFINE-COMPILER-MACRO MOD32- ...)
; compiling (DECLAIM (INLINE MOD32*) ...)
; compiling (DEFUN MOD32* ...)
; compiling (DEFINE-COMPILER-MACRO MOD32* ...)
; compiling (DECLAIM (INLINE MOD32ASH) ...)
; compiling (DEFUN MOD32ASH ...)
; compiling (DEFINE-COMPILER-MACRO MOD32ASH ...)
; compiling (DECLAIM (INLINE MOD32LOGNOT) ...)
; compiling (DEFUN MOD32LOGNOT ...)
; compiling (DEFINE-COMPILER-MACRO MOD32LOGNOT ...)
; compiling (DECLAIM (INLINE ROL32 ...) ...)
; compiling (DEFUN ROL32 ...)
; compiling (DEFUN ROR32 ...)
; compiling (DECLAIM (INLINE MOD64+ ...) ...)
; compiling (DEFUN MOD64+ ...)
; compiling (DEFINE-COMPILER-MACRO MOD64+ ...)
; compiling (DEFUN MOD64- ...)
; compiling (DEFINE-COMPILER-MACRO MOD64- ...)
; compiling (DEFUN MOD64* ...)
; compiling (DEFINE-COMPILER-MACRO MOD64* ...)
; compiling (DECLAIM (INLINE MOD64ASH) ...)
; compiling (DEFUN MOD64ASH ...)
; compiling (DEFINE-COMPILER-MACRO MOD64ASH ...)
; compiling (DECLAIM (INLINE MOD64LOGNOT) ...)
; compiling (DEFUN MOD64LOGNOT ...)
; compiling (DEFINE-COMPILER-MACRO MOD64LOGNOT ...)
; compiling (DECLAIM (INLINE ROL64 ...) ...)
; compiling (DEFUN ROL64 ...)
; compiling (DEFUN ROR64 ...)
; compiling (DECLAIM (INLINE %ADD-WITH-CARRY ...))
; compiling (DEFUN %ADD-WITH-CARRY ...)
; compiling (DEFUN %SUBTRACT-WITH-BORROW ...)
; compiling (DECLAIM (INLINE FILL-BLOCK-LE-UB8 ...))
; compiling (DECLAIM (INLINE COPY-TO-BUFFER))
; compiling (DEFUN COPY-TO-BUFFER ...)
; compiling (DEFUN FILL-BLOCK-UB8-LE ...)
; compiling (DEFUN FILL-BLOCK-UB8-BE ...)
; compiling (DEFUN FILL-BLOCK-UB8-LE/64 ...)
; compiling (DEFUN FILL-BLOCK-UB8-BE/64 ...)
; compiling (DEFUN XOR-BLOCK ...)While evaluating the form starting at line 10, column 0
  of #P"/opt/pgloader/./save.lisp":

debugger invoked on a SB-INT:SIMPLE-PROGRAM-ERROR in thread
#<THREAD "main thread" RUNNING {1001E06613}>:
  invalid number of arguments: 5

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Retry
                                     compiling #<IRONCLAD-SOURCE-FILE "ironclad" "src" "common">.
  1: [ACCEPT                       ] Continue, treating
                                     compiling #<IRONCLAD-SOURCE-FILE "ironclad" "src" "common">
                                     as having been successful.
  2:                                 Retry ASDF operation.
  3: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  4: [RETRY                        ] Retry EVAL of current toplevel form.
  5: [CONTINUE                     ] Ignore error and continue loading file "/opt/pgloader/./save.lisp".
  6: [ABORT                        ] Abort loading file "/opt/pgloader/./save.lisp".
  7:                                 Ignore runtime option --load "./save.lisp".
  8:                                 Skip rest of --eval and --load options.
  9:                                 Skip to toplevel READ/EVAL/PRINT loop.
 10: [EXIT                         ] Exit SBCL (calling #'EXIT, killing the process).

(SB-X86-64-ASM::|movzx| #<SB-ASSEM:SEGMENT :TYPE :REGULAR> #<SB-C::VOP :INFO UB32REF/LE :ARGS #<SB-C:TN-REF :TN #<SB-C:TN INPUT-BLOCK1!1[RDI]> :WRITE-P NIL :VOP UB32REF/LE> :RESULTS #<SB-C:TN-REF :TN #<SB-C:TN t2[RDX]> :WRITE-P T :VOP UB32REF/LE>> (:DWORD :QWORD) #<SB-C:TN t2[RDX]> #<SB-X86-64-ASM::EA :DWORD base=#<SB-C:TN INPUT-BLOCK1!1[RDI]> index=#<SB-C:TN t3[RDX]> disp=1>) [tl,external]
0]

**Comment by jsmith0103** [comment]
I was using 2:1.3.14-2+b1 (current package in Stretch/Deb9). Upgrading to the version found in Buster/Deb10 (2:1.4.15-1) seems to have resolved the issue.

Thank you for your help!
