### ISSUE TITLE
PSQL Error: Out of Shared Memory

### ISSUE THREAD

**Issue by brentleeper** [dimitri/pgloader#891]
Thanks for contributing to [pgloader](https://pgloader.io) by reporting an
issue! Reporting an issue is the only way we can solve problems, fix bugs,
and improve both the software and its user experience in general.

The best bug reports follow those 3 simple steps:

  1. My command file:

```
LOAD DATABASE
    FROM mysql://dps:@localhost/XXXXXXX
    INTO postgresql://xxxxx:xxxxx@192.168.xx.xx/XXXXXXX

WITH workers = 4, concurrency = 2;
```

  2. Results

```
Heap exhausted during garbage collection: 0 bytes available, 48 requested.
 Gen StaPg UbSta LaSta LUbSt Boxed Unboxed LB   LUB  !move  Alloc  Waste   Trig    WP  GCs Mem-age
   0:     0     0     0     0     0     0     0     0     0        0     0 42949672    0   0  0.0000
   1:     0     0     0     0     0     0     0     0     0        0     0 42949672    0   0  0.0000
   2:     0     0     0     0     0     0     0     0     0        0     0 42949672    0   0  0.0000
   3: 123995 123996     0     0 13084 73279   227     0   226 2817738000 19643120 1271620360    0   1  1.2103
   4: 130992 131071     0     0  5735 28068  6051     0     2 1295775984 10159888  2000000    0   0  0.0000
   5:     0     0     0     0     0     0     0     0     0        0     0  2000000    0   0  0.0000
   6:     0     0     0     0  3437  1191     0     0     0 151650304     0  2000000 3270   0  0.0000
   Total bytes allocated    = 4265164288
   Dynamic-space-size bytes = 4294967296
GC control variables:
   *GC-INHIBIT* = true
   *GC-PENDING* = true
   *STOP-FOR-GC-PENDING* = false
fatal error encountered in SBCL pid 2093(tid 140737042183936):
Heap exhausted, game over.

Welcome to LDB, a low-level debugger for the Lisp runtime environment.
```

Additionally, further attempts to modify the schema directly with PSQL give the following error:

```
psql (10.6 (Ubuntu 10.6-0ubuntu0.18.04.1))
Type "help" for help.

xxxxx=# DROP SCHEMA xxxxxxxxx CASCADE;
ERROR:  out of shared memory
HINT:  You might need to increase max_locks_per_transaction.
```

Additionally, further attempts to preform the load result in the following:

```
2019-01-17T20:14:35.034000Z NOTICE Starting pgloader, log system is ready.
2019-01-17T20:15:22.600000Z NOTICE Prepare PostgreSQL database.
2019-01-17T20:15:22.606000Z NOTICE DROP SCHEMA xxxxxxxxxxx CASCADE;
2019-01-17T20:15:22.807000Z ERROR Database error 53200: out of shared memory
HINT: You might need to increase max_locks_per_transaction.
QUERY: DROP SCHEMA xxxxxxxxxxxx CASCADE;
2019-01-17T20:15:22.807000Z FATAL Failed to create the schema, see above.
2019-01-17T20:15:22.807000Z LOG report summary reset
       table name       read   imported     errors      total time       read      write
-----------------  ---------  ---------  ---------  --------------  ---------  ---------
  fetch meta data       9908       9908          0         13.231s                     
   Create Schemas          0          0          0          0.000s                     
-----------------  ---------  ---------  ---------  --------------  ---------  ---------
```

  3. explain how the result is not what you expected.

I have loaded prior versions of the same schema with pgloader without error.
I would expect this schema to work the same. 

In the case of pgloader, here's the information I will need to read in your
bug report. Having all of this is a big help, and often means the bug you
reported can be fixed very efficiently as soon as I get to it.

Please provide the following information:

  - [ ] pgloader --version

pgloader version "3.4.1"
compiled with SBCL 1.3.3.debian

and 

pgloader version "3.5.2~devel"
compiled with SBCL 1.4.14

Both have the same issue
  
  - [ ] did you test a fresh compile from the source tree?
Yes
  - [ ] did you search for other similar issues?
 Yes
  - [ ] how can I reproduce the bug?
The data is propriety

**Comment by brentleeper** [comment]
I will meet with my system admin to ensure our Postgres instance is configured to handle this large transaction.
I will follow up.

**Comment by dimitri** [comment]
More information needed to make progress here. In the meanwhile I'm closing the issue. Consider re-opening if needed, with more information.
