### ISSUE TITLE
Is it possible to convert to downgraded psql version?

### ISSUE THREAD

**Issue by Benji410** [dimitri/pgloader#899]
Installed pgloader via HomeBrew on macOS

I want to convert to postgresql 9.2.24, is this possible with pgloader?
If so, how would I do this, because I reinstalled a different version of postgres (9.4.19) and i'm getting an error, but this is probably because the command is not in the right directory of pgloader. 

Is there an easy way to do this, like reinstalling pgloader with a different version of postgres?

**Comment by dimitri** [comment]
pgloader doesn't depend on a specific version of PostgreSQL. At run-time it will detect the version you're using and adjust some of the SQL queries used to introspect the catalogs, that's about it. Without you sharing more information, such as the exact output and error messages, there's nothing I can do to help.
