### ISSUE TITLE
column names not quoted in postgres -> postgres sync

### ISSUE THREAD

**Issue by m0n5t3r** [dimitri/pgloader#905]
- [x] pgloader --version
  
```
pgloader version 3.6.2~devel
compiled with SBCL 1.3.14.debian
```
  
  - [x] did you test a fresh compile from the source tree?
    ... assuming the docker is up to date, which it seems to be

  - [x] did you search for other similar issues?
    
  - [x] how can I reproduce the bug?
    attached self-contained script and load file; it uses docker, but I think the issue is obvious anyway for someone who knows where to look (I ... tried)

    [testcase.sh.txt](https://github.com/dimitri/pgloader/files/2849409/testcase.sh.txt)
    [testcase.load.txt](https://github.com/dimitri/pgloader/files/2849410/testcase.load.txt)

  - [x] pgloader output you obtain
  
```
KABOOM!
2019-02-10T21:03:07.186000Z LOG COPY INIT ERROR
FATAL error: Can't init COPY to "public"."testtable"(title, default):
Database error 42601: syntax error at or near "default"
Date/time: 2019-02-10-21:03An unhandled error condition has been signalled:
                              Can't init COPY to "public"."testtable"(title, default):
Database error 42601: syntax error at or near "default"


Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1005D9E483}>
0: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE-TO-STREAM #<SB-IMPL::STRING-OUTPUT-STREAM {1008FCC903}>)
1: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE #<PGLOADER.PGCOPY:COPY-INIT-ERROR {10093965A3}> :OUTPUT NIL :IF-EXISTS :APPEND :VERBOSE NIL)
2: ((FLET #:H0 :IN PGLOADER::MAIN) #<PGLOADER.PGCOPY:COPY-INIT-ERROR {10093965A3}>)
3: (SIGNAL #<PGLOADER.PGCOPY:COPY-INIT-ERROR {10093965A3}>)
4: (ERROR #<PGLOADER.PGCOPY:COPY-INIT-ERROR {10093965A3}>)
5: (LPARALLEL.KERNEL::UNWRAP-RESULT #<unavailable lambda list>)
6: ((:METHOD PGLOADER.LOAD:COPY-DATABASE (PGLOADER.SOURCES:DB-COPY)) #<PGLOADER.SOURCE.PGSQL:COPY-PGSQL {1007534C73}> :ON-ERROR-STOP T :WORKER-COUNT 4 :CONCURRENCY 4 :MULTIPLE-READERS NIL :MAX-PARALLEL-CREATE-INDEX NIL :TRUNCATE T :DISABLE-TRIGGERS NIL :DATA-ONLY T :SCHEMA-ONLY NIL :CREATE-SCHEMAS T :CREATE-TABLES NIL :INCLUDE-DROP T :DROP-SCHEMA NIL :CREATE-INDEXES T :INDEX-NAMES :PRESERVE :RESET-SEQUENCES T :FOREIGN-KEYS T :REINDEX T :AFTER-SCHEMA NIL :DISTRIBUTE NIL :ONLY-TABLES NIL :INCLUDING NIL :EXCLUDING NIL :SET-TABLE-OIDS T :ALTER-TABLE NIL :ALTER-SCHEMA NIL :MATERIALIZE-VIEWS NIL) [fast-method]
7: ((LAMBDA ()))
8: (PGLOADER:RUN-COMMANDS #P"/testcase/testcase.load" :START-LOGGER NIL :FLUSH-SUMMARY T :SUMMARY NIL :LOG-FILENAME NIL :LOG-MIN-MESSAGES NIL :CLIENT-MIN-MESSAGES NIL)
9: (PGLOADER::PROCESS-COMMAND-FILE ("/testcase/testcase.load") :FLUSH-SUMMARY T)
10: (PGLOADER.MONITOR::CALL-WITH-MONITOR #<CLOSURE (LAMBDA NIL :IN PGLOADER::MAIN) {1005DEC89B}>)
11: (PGLOADER::MAIN ("pgloader" "-d" "/testcase/testcase.load"))
12: ((LAMBDA NIL :IN "/opt/src/pgloader/dumper-2SKVI5f7.lisp"))
13: ((FLET #:WITHOUT-INTERRUPTS-BODY-77 :IN SAVE-LISP-AND-DIE))
14: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))



2019-02-10T21:03:07.187000Z INFO Stopping monitor

What I am doing here?

Can't init COPY to "public"."testtable"(title, default):
Database error 42601: syntax error at or near "default"
```

  - [x] data that is being loaded, if relevant
  
    included in the script

  - [x] How the data is different from what you expected, if relevant

    load fails

**Comment by m0n5t3r** [comment]
Can I have at least some pointer about where I should look, if I am to attempt a fix?

**Comment by m0n5t3r** [comment]
This change seems to fix the issue:

```
diff --git a/src/sources/pgsql/pgsql.lisp b/src/sources/pgsql/pgsql.lisp
index 1fd15fc..07a02a3 100644
--- a/src/sources/pgsql/pgsql.lisp
+++ b/src/sources/pgsql/pgsql.lisp
@@ -64,7 +64,7 @@
 
 (defmethod copy-column-list ((pgsql copy-pgsql))
   "We are sending the data in the MySQL columns ordering here."
-  (mapcar #'column-name (fields pgsql)))
+  (mapcar (lambda (colname) (format nil "\"~a\"" colname)) (mapcar #'column-name (fields pgsql))))
 
 (defmethod fetch-metadata ((pgsql copy-pgsql)
                            (catalog catalog)
```

I don't know the language well enough to express it more simply (as in, I have no idea why `(mapcar (format nil "\"~a\"" #'column-name) (fields pgsql))` didn't work, so...

**Comment by dimitri** [comment]
Hi @m0n5t3r! Thanks for your patience and for patching your local version of pgloader! I applied a fix that is mostly like yours, expect using some functions that are already in the code source (`ensure-quoted` makes it more obvious what's happening).

Another way to do it would have been to use `~s` as a format string rather than `\"~a\"`.

Also in Common Lisp the reader notation `#'` is equivalent to the operator `function`, so that `(mapcar #'column-name <list>)` is the same thing as `(mapcar (function column-name) <list>)`, which means calling the function named `column-name` on every element of the list, building a result list as you go. `mapcar` takes a function object as its first argument, not any Common Lisp expression.

If you want to play more with Common Lisp, well pgloader has quite some open issues you're very welcome to hack around ;-)
