### ISSUE TITLE
pgloader fails for windows versions of PostgreSQL

### ISSUE THREAD

**Issue by anhi** [dimitri/pgloader#908]
On Windows, PostgreSQL returns a version string like "PostgreSQL 10.6, compiled by Visual C++ build 1800, 64-bit". Regex parsing in connection.lisp fails on this string and leads to a "Control stack exhausted" (as in issue #810).

I've created a pull request (#907) that fixes it for me.

**Comment by dimitri** [comment]
Fixed in #907, closing now.
