### ISSUE TITLE
pgloader -E prints help

### ISSUE THREAD

**Issue by cgendreau** [dimitri/pgloader#909]
`pgloader -E` and `--list-encodings` are currently printing the help menu instead of the "pgloader known encodings".

  - [x] pgloader --version
    ```
    pgloader version "3.6.2~devel" but also on 3.6.1
    ```
  - [ ] did you test a fresh compile from the source tree?
    No, but I used the Docker image
  - [x] did you search for other similar issues?
    yes
  - [x] how can I reproduce the bug?
   ```
    pgloader -E
   ```

**Comment by dimitri** [comment]
Thanks for the bug report @cgendreau ; it's fixed now. Please build from sources and try again.
