### ISSUE TITLE
partitioned table

### ISSUE THREAD

**Issue by jinyuanpeng** [dimitri/pgloader#911]
I have issue to load pre-created partitioned tables from mysql, the source DB has huge non-partitioned table A, and I want to create the partitioned tables for A in postgres first, then use pgloader reading source DB (mysql) and load to the Postgres existing partitioned table.

Configure file:

```
LOAD DATABASE
~ FROM mysql://.../test
~ INTO postgresql:///test
~
WITH create no tables,create no indexes,data only,preserve index names ,
concurrency = 4, workers = 8,
prefetch rows = 25000,
multiple readers per thread, rows per range = 50000
~
INCLUDING ONLY TABLE NAMES MATCHING 'A',~/A/

ALTER SCHEMA 'test' RENAME TO 'public'
~
CAST type int with extra auto_increment when (< precision 10) to serial drop typemod keep default keep not null
```

first, I got this error:
Failed to find schema "test" in target catalog..

I did create the schema test as well as the table A in postgres as below:

``` sql
create table test."A" (id1, id2, ..) PARTITION BY RANGE (id);

CREATE TABLE test.A_part_01 PARTITION OF test.A
FOR VALUES FROM ('1') TO ('1000') WITH (parallel_workers='4');

..
CREATE TABLE test.A_part_20 PARTITION OF test.A
FOR VALUES FROM ('10000000') TO ('10000000000') WITH (parallel_workers='4');
```

I checked the document and seem I can use the "AFTER LOAD DO"

Could you please help and share some hints? if can't load data into pre-partitioned table, how should I use the DDL in the configuration file?

thanks a lot

**Comment by jinyuanpeng** [comment]
I have issue to load pre-created partitioned tables from mysql,  the source DB has huge non-partitioned table A, and I want to create the partitioned tables for A in postgres first, then use pgloader reading source DB (mysql) and load to the Postgres existing partitioned table.

Configure file:
LOAD DATABASE                                                                                                                                                                                                                             
~       FROM mysql://.../test                                              
~       INTO postgresql:///test                                                                                                                                                                   
~                                                                                                                                                                                                                                         
 WITH create no tables,create no indexes,data only,preserve index names ,                                                                                                                                                                 
      concurrency = 4, workers = 8,                                                                                                                                                                                                       
      prefetch rows = 25000,                                                                                                                                                                                                              
      multiple readers per thread, rows per range = 50000                                                                                                                                                                                 
~                                                                                                                                                                                                                                         
 INCLUDING ONLY TABLE NAMES MATCHING 'A',~/A/                                                                                                                                                       
                                                                                                                                                                                                                                          
 ALTER SCHEMA 'test' RENAME TO 'public'                                                                                                                                                                                                 
~                                                                                                                                                                                                                                         
 CAST   type int with extra auto_increment when (< precision 10) to serial drop typemod keep default keep not null

first, I got this error:
Failed to find schema "test" in target catalog..

I did create the schema test as well as the table A in postgres as below:
create table test."A" (id1, id2, ..) PARTITION BY RANGE (id);

CREATE TABLE test.A_part_01 PARTITION OF test.A
FOR VALUES FROM ('1') TO ('1000') WITH (parallel_workers='4');

..
CREATE TABLE test.A_part_20 PARTITION OF test.A
FOR VALUES FROM ('10000000') TO ('10000000000') WITH (parallel_workers='4');

I checked the document and seem I can use the "AFTER LOAD DO"

Could you please help and share some hints? if can't load data into pre-partitioned table, how should I use the DDL in the configuration file? 

thanks a lot

**Comment by dimitri** [comment]
I'm a little confused here. You're using the clause `ALTER SCHEMA 'test' RENAME TO 'public'` which is going to target the schema `public` in PostgreSQL when the MySQL source database name is `test`. Then you're creating the target tables in the schema `test`. Can you review that parts?

**Comment by jinyuanpeng** [comment]
sorry I confused you, but MYSQL DB is 'test', and my final destination for Postgres schema is 'public'. 

I guess I should ask this question:
Do pgloader support the table converting during fly?  how do I pre-create the partitioned table first? can I just straight forward to create the partitioned table 'A' under PostgreSQL schema 'public' before running the pgloader (the source data is under mysql live DB under database 'test')?

**Comment by dimitri** [comment]
If your target schema in Postgres is `public`, then why is your SQL script create target table and partitions in the schema `test` in Postgres? I think that might be your problem here.

**Comment by jinyuanpeng** [comment]
I tested this before, if I don't create the table in postgres 'test' schema, then pgloader will complaint that no 'table' found error because I load the data only. if I allow the table creation, then it's not partitioned table (the same as source).

I will try to post the result again here.

**Comment by jinyuanpeng** [comment]
I just tested it again, seems not working.

First create the table under schema test:
CREATE TABLE public.a (Id bigint NOT NULL, ...) partition by range (id);
CREATE TABLE public.a1 PARTITION OF public.a FOR VALUES FROM ('3000000000') to ('3000010000');
CREATE TABLE public.a2  PARTITION OF public.a FOR VALUES FROM ('3000010000') to ('3000030000');

configuration file:
LOAD DATABASE
	FROM mysql://../test 
	INTO postgresql://..../test

 WITH create no tables,create no indexes, data only
 INCLUDING ONLY TABLE NAMES MATCHING 'a'
;

Error show below:
An unhandled error condition has been signalled:
   pgloader failed to find anything in schema "test" in target catalog.

Now I changed the postgres schema:
alter table a set schema test;
alter table a1 set schema test;
alter table a2 set schema test;

2019-02-21T19:30:50.385000Z LOG report summary reset
             table name     errors       rows      bytes      total time
-----------------------  ---------  ---------  ---------  --------------
        fetch meta data          0          0                     0.101s
      Drop Foreign Keys          0          0                     0.000s
-----------------------  ---------  ---------  ---------  --------------
-----------------------  ---------  ---------  ---------  --------------
COPY Threads Completion          0          4                     0.000s
        Reset Sequences          0          0                     0.023s
    Create Foreign Keys          0          0                     0.000s
       Install Comments          0          0                     0.000s
-----------------------  ---------  ---------  ---------  --------------
      Total import time          ✓          0                     0.023s

No data loaded.

Again, I would like to know this question:
How can I load the table A from mysql into Postgres partitioned table A (with partitioned A1 and A2)?

Thanks a lot for your time.

**Comment by dimitri** [comment]
In the first test, you're migrating from schema test to schema public, and you install your target tables in schema test, so that pgloader can't find them, because you instructed it to search for them in schema public.

In this second test, you're migrating from schema test to schema test, and you're creating the target tables in the schema public, and pgloader can't find them, because it's setup to search for them in the schema test.

Please review your setup and make the pgloader command consistent with where you install the target table and partitions?

**Comment by dimitri** [comment]
Closing the issue now, please re-open if needed, with more information / tests.
