### ISSUE TITLE
pgloader errors do not include data value that produces error

### ISSUE THREAD

**Issue by cwmcmullen** [dimitri/pgloader#914]
Hi Dimitri,

I am using pgloader for the first time. I am trying to load CSV files that contain exported data from other databases. I've seen many errors that look like the following.

```
2019-02-21T17:59:04.724000Z ERROR Could not read input: The bounding indices 0 and 4 are bad for a sequence of length 1.
See also:
      The ANSI Standard, Glossary entry for "bounding index designator"
      The ANSI Standard, writeup for Issue SUBSEQ-OUT-OF-BOUNDS:IS-AN-ERROR
```

Could you please update your error messages to include the data value that is producing the error?  And possibly a error message that is a bit more meaningful to someone that doesn't know Lisp or pgloader internals?

I and two other engineers have been staring at the --verbose --debug output and we cannot figure out what pgloader is complaining about.

Yes, I could assemble a complete test case as you request, but if you would add this capability, then many times I/we wouldn't have to bother you with mundane difficulties like this.

Thanks Much!

**Comment by dimitri** [comment]
Hi @cwmcmullen, the test case will allow me to add both the feature you're asking for (better diagnostic) and hopefully a fix for this bug too. Without the test case it's working in the blind and it takes so much more time... please consider sending over a test case.

**Comment by dimitri** [comment]
Closing the issue for lack of information. Without being able to reproduce the problem here I won't be able to solve it. Please consider opening the issue again with more details if you can!
