### ISSUE TITLE
Where are the pgloader reject log files?

### ISSUE THREAD

**Issue by cwmcmullen** [dimitri/pgloader#915]
Hi Dimitri,

On [this page](https://pgloader.readthedocs.io/en/latest/#welcome-to-pgloader-s-documentation), it mentions the files:

* reject.dat 
* reject.log

BUT it does not mention WHERE pgloader writes these files. I have googled plenty and cannot find the answer to this question.

I even ran `sudo find / -type f -name "reject.*"` hoping to find these files, and they do not exist on my machine (a Mac).

Thanks Much!

**Comment by dimitri** [comment]
The answer is hidden in https://pgloader.readthedocs.io/en/latest/pgloader.html#general-options with the `--root-dir -D` option. That's the root directory where every reject file is to be created... I guess some more documentation on this point is in order now...
