### ISSUE TITLE
How to concatenate two fields?

### ISSUE THREAD

**Issue by denisik000** [dimitri/pgloader#916]
Import from csv having two columns comma separated.
Need to put data from both columns into the single varchar() field.
Is there some kind of transformation or something?

```
LOAD CSV
     FROM INLINE with encoding 'ascii'
     INTO postgresql:///pgloader
     TARGET TABLE jordane

     WITH truncate,
          fields terminated by ',',
          fields not enclosed,

      SET work_mem to '128MB',
          standard_conforming_strings to 'on'

   BEFORE LOAD DO
    $$ drop table if exists jordane; $$,
    $$ CREATE TABLE jordane
       (
         "NOM" character(40),
       )
    $$;

BORDET,Jordane
BORDET,Audrey
```

Output must be as

```
[NOM]
BORDETJordane
BORDETAudrey
```

**Comment by dimitri** [comment]
Please have a look at the following test command: https://github.com/dimitri/pgloader/blob/master/test/archive.load. It contains an example of doing processing of the columns:

```
   LOAD CSV
        FROM FILENAME MATCHING ~/GeoLiteCity-Location.csv/
             WITH ENCODING iso-8859-1
             (
                locId,
                country,
                region     [ null if blanks ],
                city       [ null if blanks ],
                postalCode [ null if blanks ],
                latitude,
                longitude,
                metroCode  [ null if blanks ],
                areaCode   [ null if blanks ]
             )
        INTO postgresql:///ip4r?geolite.location
             (
                locid,country,region,city,postalCode,
                location point using (format nil "(~a,~a)" longitude latitude),
                metroCode,areaCode
             )
```

In your case replace the format string with `(format nil "~a~a" last name first name)` or the column names you're using.

**Comment by denisik000** [comment]
Got:
KABOOM!
FATAL error: At

            (
             number using ( format nil "~a~a" seri
                          ^ (Line 10, Column 24, Position 191)

In context KW-USING:

While parsing KW-USING. Expected:

     the character Tab
  or the character Newline
  or the character Return
  or the character Space
  or the string "--"
  or the string "/*"
  or the string "using"
An unhandled error condition has been signalled: At

            (
             number using ( format nil "~a~a" seri
                          ^ (Line 10, Column 24, Position 191)

----------------------------source-------------------------
LOAD CSV
     FROM FILENAME MATCHING ~/shortlist.csv/
     WITH ENCODING UTF-8 
		(
		 serie, 
		 number
		)
     INTO postgresql:///blacklist?passport
          (
           number using ( format nil "~a~a" serie number)
          )

     WITH 
          skip header = 5,
          fields terminated by ',',
          no truncate,
          on error resume next


      SET 
          work_mem to '12MB'
;
-------------
pgloader -V
pgloader version "3.6.1"
compiled with SBCL 1.4.16

**Comment by denisik000** [comment]
$pgloader copy.load
` pgloader copy.load
2019-03-02T14:26:49.019000+08:00 LOG pgloader version "3.6.1"
KABOOM!
FATAL error: At

            (
             number using ( format nil "~a~a" seri
                          ^ (Line 10, Column 24, Position 191)

`
$cat copy.load
`LOAD CSV
     FROM FILENAME MATCHING ~/short.csv/
     WITH ENCODING UTF-8 
		(
		 serie, 
		 number
		)
     INTO postgresql:///blacklist?passport
          (
           number using ( format nil "~a~a" serie number)
          )

     WITH 
          skip header = 1,
          fields terminated by ',',
          no truncate,
          on error resume next


      SET 
          work_mem to '12MB'
;
`
ploader -V
pgloader version "3.6.1"
compiled with SBCL 1.4.16

**Comment by dimitri** [comment]
You're using `column expression` instead of `column type using expression` syntax. Please read the docs?
