### ISSUE TITLE
MySQL to RedShift - issues with timestamp columns

### ISSUE THREAD

**Issue by ScOut3R** [dimitri/pgloader#920]
I am trying to load a MySQL database into RedShift. 

I have columns with `timestamp` type that can be NULL and the records have `0000-00-00 00:00:00` as the value.

Pgloader correctly detects the column and sets it as `timestamptz` for RedShift, but no CASTing is happening. I tried multiple CAST rules but the data was never changes and cannot be loaded into RedShift.

CASTs I tried:
```
type timestamp to timestamp drop default using zero-dates-to-null
type timestamp to timestamptz drop default using zero-dates-to-null
type timestamp to timestamptz using zero-dates-to-null
```
I also tried to configure the default MySQL CASTs based on the documentation.

The `--debug` output does not show any CAST steps so I wonder if CASTing is not triggered.

I am using the latest Docker image.

I really appreciate your response!

  - [ ] pgloader --version
  
 ```
3.6.2~devel
```
  
  - [ ] did you test a fresh compile from the source tree? No
    
    Compiling pgloader from sources is documented in the
    [README](https://github.com/dimitri/pgloader#build-from-sources), it's
    easy to do, and if patches are to be made to fix your bug, you're going
    to have to build from sources to get the fix anyway…
    
  - [ ] did you search for other similar issues? Yes
    
  - [ ] how can I reproduce the bug?
```
LOAD DATABASE
        FROM mysql://[source]
        INTO postgresql://[target]

CAST type timestamp to timestamp drop default using zero-dates-to-null

SET timezone to 'Australia/Sydney'

SET MySQL PARAMETERS net_read_timeout = '120',
        net_write_timeout = '240'

INCLUDING ONLY TABLE NAMES MATCHING 'auspost'

ALTER SCHEMA '[source]' RENAME TO '[target]'
;
```
  - [ ] pgloader output you obtain
  
```
2019-03-07T04:15:45.165000Z ERROR Database error XX000: Load into table 'auspost' failed.  Check 'stl_load_errors' system table for details.
```

**Comment by dimitri** [comment]
I think I would need access to a setup where I can reproduce the bug and then fix it...

**Comment by dimitri** [comment]
Closing to clean-up the open issues dashboard on pgloader. Please re-open with a way for me to reproduce the bug: access to an environment where I can connect pgloader and reproduce the problem would be needed here.
