### ISSUE TITLE
Environment variables doesn't work

### ISSUE THREAD

**Issue by mrPsycho** [dimitri/pgloader#922]
just compiled pgloader, and noticed, that env variables doesn't work.

i downloaded pgloader from this repo as zip. unarchived and run `make pgloader`

after that i created file `db.migrate`: 
```
load database
   from      {{MYSQL_SRC}}
   into postgresql:///{{PSQL_DB}}
  with
   create no indexes, preserve index names, no foreign keys, data only,
   batch rows = 5000, batch concurrency = 2
  alter schema {{MYSQL_DB}} rename to 'public'
;
```
and did it
```
export MYSQL_SRC="mysql://user:pass@host:3306/db"
export PSQL_DB="db2"
export MYSQL_DB="db"
```
then i ran pgloader and see this:

```
2019-03-13T17:01:53.019000+02:00 NOTICE Starting pgloader, log system is ready.
2019-03-13T17:01:53.039000+02:00 LOG pgloader version "3.6.4ec8613"
KABOOM!
FATAL error: At

     from 
     into postgresql:///
  
          ^ (Line 6, Column 8, Position 52)

In context KW-INTO:

While parsing KW-INTO. Expected:

     the character Tab
  or the character Newline
  or the character Return
  or the character Space
  or the string "--"
  or the string "/*"
  or the string "into"
```

why?

  - [*] pgloader --version
  
    ```
    pgloader --version
pgloader version "3.6.4ec8613"
compiled with SBCL 1.4.5.debian
    ```
  
  - [ ] did you test a fresh compile from the source tree?
    
   yes
    
  - [ ] did you search for other similar issues?
   yes. #609 looks relevant... but very old

**Comment by dimitri** [comment]
Can you paste the output when using the `--debug` flag, which should cause the _mustache_ template instance with the environment variables replaced.

**Comment by mrPsycho** [comment]
it has:
```
gloader version 3.6.4ec8613
compiled with SBCL 1.4.5.debian
sb-impl::*default-external-format* :UTF-8
tmpdir: #P"/tmp/pgloader/"
2019-03-15T13:58:13.036000+02:00 NOTICE Starting pgloader, log system is ready.
2019-03-15T13:58:13.075000+02:00 INFO Starting monitor
2019-03-15T13:58:13.092000+02:00 LOG pgloader version "3.6.4ec8613"
2019-03-15T13:58:13.112000+02:00 INFO Parsed command:

load database
   from      ''
   into postgresql:///''
  with
   create no indexes, preserve index names, no foreign keys, data only,
   batch rows = 5000, batch concurrency = 2
  alter schema '' rename to 'public'
;


KABOOM!
FATAL error: At

  load database
     from      ''
  
                ^ (Line 3, Column 14, Position 29)

In context QUOTED-FILENAME:

While parsing QUOTED-FILENAME. Expected:

     anything but the character ' (APOSTROPHE)
Date/time: 2019-03-15-13:58An unhandled error condition has been signalled: At

  load database
     from      ''
  
                ^ (Line 3, Column 14, Position 29)

In context QUOTED-FILENAME:

While parsing QUOTED-FILENAME. Expected:

     anything but the character ' (APOSTROPHE)
```

and then backtrace starts.

so, it doesn't use env varisables.
but...

when i put `{{PATH}}`  - it worked. 
why it could be so?

**Comment by mrPsycho** [comment]
i figured it:
`{{MYSQLSRC}}` works
`{{MYSQL_SRC}}` doesn't!

**Comment by dimitri** [comment]
Well if you don't `export` environment variables then programs started from the shell don't inherit their values, that's how it works, and that has nothing to do with pgloader. I'm closing the issue, thanks a lot for the extra feedback!

**Comment by SamirMjs** [comment]
LOAD CSV
     FROM '/dbf/appworx/pgscript/temp_table_data.csv' (INV_ID)
     INTO postgresql://username:password@hostname:portname/dbname
     TARGET TABLE temp_inv_table

Running through shells script -

#!/bin/ksh

echo "Start"
#enviroment variable
. /xzy/DBset
 
echo "Fetching password value"

pgloader temp_table_load2.load 


How do we pass value to temp_table_load2.load file using shell or if possible how we pass directly to load file 
I am getting same above commented error.

Thanks you for help in advance
