### ISSUE TITLE
pgloader failing in 3.6.2 when db name has special characters and escaping with quotes also not working (working 3.5.2)

### ISSUE THREAD

**Issue by oo007** [dimitri/pgloader#923]
- [ ] pgloader --version
    ```
pgloader version "3.6.2~devel"
compiled with SBCL 1.4.7-1.6-suse
    ```
  
  - [ ] did you test a fresh compile from the source tree?
Yes    
    Compiling pgloader from sources is documented in the
    [README](https://github.com/dimitri/pgloader#build-from-sources), it's
    easy to do, and if patches are to be made to fix your bug, you're going
    to have to build from sources to get the fix anyway…
    
  - [ ] did you search for other similar issues?
    Yes
  - [ ] how can I reproduce the bug?

As given in the command, use '@' in the db name in 3.6.2 version of pgloader.

```
--
-- EDIT THIS FILE TO MATCH YOUR BUG REPORT
--

LOAD DATABASE  
	from   mysql://filr:novell@<mysql-server-IP>:3306/srcDBname
	into   postgresql://g@@2:n@<postgressql-server-ip>:5432/tgtDBWthSplChr@2
ALTER SCHEMA 'srcDBname' RENAME TO 'public'
WITH create no tables
EXCLUDING TABLE NAMES MATCHING 'table1', 'table2', 'table3';
```

  - [ ] pgloader output you obtain

```
In context COMMAND:

While parsing COMMAND. Problem:

  The production
  
    #\@
  
  does not satisfy the predicate ALPHA-CHAR-P.
  
```

  - [ ] data that is being loaded, if relevant
  
```
N/A
```

  - [ ] How the data is different from what you expected, if relevant
I am running the command as given above using a script file containing the following content with special charact in the target DB name. In 3.5.x version of pgloader, we were putting the db name with special characters inside single quotes and that was working fine. But with the latest update it is breaking by throwing parse errors.

**Comment by dimitri** [comment]
It should be doable with the attached patch. You still have to protect your database name inside single quotes, though.

**Comment by oo007** [comment]
Thanks dimitri for the quick reply. With this patch special chars in db name works perfectly fine.

Thanks again

**Comment by yayayahei** [comment]
Hi @dimitri @oo007 
I've encounter the same problem, but the '@' character is in mysql username, but failed parse after I add single quotes bettween username.

my load file like this:
```
load database
     from      mysql://'dev@mysql001':123123@localhost:3306/from_db
     into pgsql://postgres:123123@localhost:5442/postgres
 INCLUDING ONLY TABLE NAMES MATCHING 'test'
;
```

Could you give me an example what you've try on above?
