### ISSUE TITLE
Deleting the data from Postgresql using the csv file

### ISSUE THREAD

**Issue by RaghuveerNarala** [dimitri/pgloader#925]
Hi pgloader team,
Thanks for providing the pgloader tool, its of great help. I would like to request to have the following details in the documentation:
1.  Documentation with examples when loading data from csv. 
2. Handling specific data types, (date, Clob etc)
3. Currently i dont see any delete option from the csv file. We have a requirement to delete the data  record that got updated and include the new data record.

I have however completed addressing #1 and #2, by using alternate methods. Could you please help me with the concenr #3.

Thank you in advance.

Regards
Raghuveer

**Comment by dimitri** [comment]
1. See either https://pgloader.readthedocs.io/en/latest/ref/csv.html or the numerous CSV tests at https://github.com/dimitri/pgloader/tree/master/test
  2. any specific question here?
  3. there's no DELETE option in Pgloader, that's true, and there's no facility to UPDATE data from CSV files either; so I don't know what you're trying to achieve.

If you want to enable progress on point 3. above, please give more information to help me understand the specifications of what you want to implement.

**Comment by dimitri** [comment]
Closing the issue now. If you still need help, please provide more information so that I can try and help you better, and consider opening the issue again if needed.
