### ISSUE TITLE
[Enh?] CAST'ing columns when importing from DBF.

### ISSUE THREAD

**Issue by AnrDaemon** [dimitri/pgloader#927]
When importing from DBF I've tried to CAST some `numeric` field to int, but sadly the parser says the CAST was unexpected, expecting BEFORE, AFTER, SET or WITH.

**Comment by dimitri** [comment]
It turns out that it was easy to implement and also allows fixing issue #938, thanks to the internal _framework_ for user-defined casting rules in pgloader to install nullable columns by default.
