### ISSUE TITLE
[MSSQL] Materialized Views problem

### ISSUE THREAD

**Issue by sorix6** [dimitri/pgloader#928]
Pgloader seems to be copying all the views defined on the source database and not only the views that it creates.  Is there something that I am missing? From what I can tell, INCLUDING and EXCLUDING only apply on tables and not on views.

- [X] pgloader --version
````
pgloader version "3.6.1"
compiled with SBCL 1.4.5.debian
````
 - [X] did you test a fresh compile from the source tree?

- [X] did you search for other similar issues?

- [X] how can I reproduce the bug?
Creating a materialized view on a MSSQL database that has preexistent views
After execution, the target database will contain all views, not only the ones created by the Pgloader command

Thank you in advance, awesome work

**Comment by sorix6** [comment]
I think that a small change in the file *src/sources/mssql/mssql.lisp*, line 102
could fix our problem without any side-effects.

    (cond (view-names
                   (list-all-columns catalog
                                     :including including
                                     :excluding excluding /* add this ligne */
                                     :table-type :view))

**Comment by dimitri** [comment]
Thanks for the fix! I verified that the code still compiled, but I don't have an MS SQL environment handy to test the change on, so I'll leave that responsibility to you.

**Comment by sorix6** [comment]
Thank you @dimitri :)
I can confirm that this works
