### ISSUE TITLE
Can't load schema from PG to PG

### ISSUE THREAD

**Issue by varp** [dimitri/pgloader#934]
- [ ] pgloader --version
  
    ```
    pgloader version "3.5.2"
    compiled with SBCL 1.4.5.debian
    ```
  
  - [ ] did you test a fresh compile from the source tree?
    
  NO
    
  - [ ] how can I reproduce the bug?

    pgloader -v schema_only.load
    
  - [ ] did you search for other similar issues?
    Yes

```
load database
    from pgsql://postgres@localhost:5435/nalog
    into pgsql://postgres@localhost/nalog

    with drop indexes,
        create no indexes;

```

  - [ ] pgloader output you obtain
  
```
2019-04-09T10:29:34.039000Z LOG Migrating from #<SQLITE-CONNECTION sqlite:///nalog/pgloader/pgsql:/postgres@localhost:5435/nalog.load {1006440B83}>
2019-04-09T10:29:34.041000Z LOG Migrating into #<PGSQL-CONNECTION pgsql://postgres@localhost:5432/nalog {1006441D53}>
KABOOM!
FATAL error: Failed to open sqlite file #P"/nalog/pgloader/pgsql:/postgres@localhost:5435/nalog.load": Could not open sqlite3 database /nalog/pgloader/pgsql:/postgres@localhost:5435/nalog.load
Code CANTOPEN: no message.
An unhandled error condition has been signalled:
   Failed to open sqlite file #P"/nalog/pgloader/pgsql:/postgres@localhost:5435/nalog.load": Could not open sqlite3 database /nalog/pgloader/pgsql:/postgres@localhost:5435/nalog.load
Code CANTOPEN: no message.




What I am doing here?

Failed to open sqlite file #P"/nalog/pgloader/pgsql:/postgres@localhost:5435/nalog.load": Could not open sqlite3 database /nalog/pgloader/pgsql:/postgres@localhost:5435/nalog.load
Code CANTOPEN: no message.

```

**Comment by dimitri** [comment]
It seems to me that the error message is explicit enough. pgloader failed to parse your source database connection string and tried to open an SQLite file somewhere:

```
FATAL error: Failed to open sqlite file #P"/nalog/pgloader/pgsql:/postgres@localhost:5435/nalog.load": Could not open sqlite3 database /nalog/pgloader/pgsql:/postgres@localhost:5435/nalog.load
```

When I try parsing `pgsql://postgres@localhost:5435/nalog` locally I don't have that problem, so I guess there's a typo or some other problem in your LOAD command.

**Comment by varp** [comment]
Hmm, thx. I'll give you a feedback ASAP

**Comment by varp** [comment]
OK. What kind of problem or typo do you suspect in my load file? There is my load file:
```
LOAD DATABASE
	FROM pgsql://postgres@localhost:5435/nalog
	INTO pgsql://postgres@localhost/nalog

	WITH drop indexes,
		create no indexes
;

```

**Comment by varp** [comment]
I've retyped the load file using SublimeText 3 using TABs with a width of 4. LOAD file parses correctly except the source URL of the database, according to the error. I've tried a combination with `postgresql` instead of `pgsql`. The result is the same. 

So, I'm very confused about WHAT kind of typo I could allow.

**Comment by varp** [comment]
I've tried to do the same thing in the console. Here is the command:`pgloader pgsql://postgres@localhost:5435/nalog pgsql://postgres@localhost/nalog`. And here is the output: 
```
KABOOM!
FATAL error: The assertion (NOT (NULL PGLOADER::FUNC)) failed with
             (NULL PGLOADER::FUNC) = T.
An unhandled error condition has been signalled:
   The assertion (NOT (NULL PGLOADER::FUNC)) failed with (NULL PGLOADER::FUNC)
   = T.




What I am doing here?

The assertion (NOT (NULL PGLOADER::FUNC)) failed with (NULL PGLOADER::FUNC) = T.

```

**Comment by varp** [comment]
I've also tried to do the command fully on the command line. The cmd: `pgloader -D . -L "./logs/schema_only-$(date +%F).log" -S "./summary/schema_only-$(date +%F).log" -v -d --with create no indexes --with schema only postgresql://postgres@localhost:5435/nalog postgresql://postgres@localhost/nalog`. The result I've got:
```
sb-impl::*default-external-format* :UTF-8
tmpdir: #P"/tmp/pgloader/"
mkdir -p #P"/nalog/pgloader/summary/"
2019-04-16T10:12:28.004000Z NOTICE Starting pgloader, log system is ready.
2019-04-16T10:12:28.007000Z INFO Starting monitor
2019-04-16T10:12:28.009000Z INFO Stopping monitor
```
Exactly nothing!

Please, I'll very appreciate if you could explain to me WHAT I AM DOING WRONG!

**Comment by dimitri** [comment]
I just realise now that you're using pgloader 3.5.2, which has no support for PostgreSQL as a source, and a bug where when parsing the source string fails it then consider it a SQLite filename. Please upgrade to pgloader 3.6.1.

**Comment by varp** [comment]
Ok. I understood. Sorry, my bad!
