### ISSUE TITLE
Can't migrate MySQL OpenProject to postgresql.

### ISSUE THREAD

**Issue by VonSNAKE77** [dimitri/pgloader#935]
I have a MySQL database with data, a base operating in postgresql and next to it empty to fill in data from the MySQL database. I follow the steps as follows:
https://www.openproject.org/operations/upgrading/migrating-packaged-openproject-database-postgresql/

and at the step:

```
pgloader --verbose $MYSQL_DATABASE_URL $POSTGRES_DATABASE_URL
```

receives an error:

```
KABOOM!
FATAL error: No such file or directory: "postgres://openproject:<<pass>>@127.0.0.1:45432/openproject"
An unhandled error condition has been signalled:
   No such file or directory: "postgres://openproject:<<pass>>@127.0.0.1:45432/openproject"



2019-04-09T08:44:29.007000Z NOTICE Starting pgloader, log system is ready.

What I am doing here?

No such file or directory: "postgres://openproject:<<pass>>@127.0.0.1:45432/openproject"
```

**Comment by dimitri** [comment]
This looks like a problem parsing the target URL given in `$POSTGRES_DATABASE_URL`, but your bug report doesn't contain nearly enough information for me to be able to help you here. Please review your target Postgres URL. Hint: it should work ok when you use `psql $POSTGRES_DATABASE_URL`.

**Comment by jonbesga** [comment]
Hi, exactly the same happening to me:

The url format is:

* For MySQL: `mysql:://<user>:<password>@<host>/<database>`
* For PostgreSQL: `postgresql:://<user>:<password>@<host>/<database>`

**Comment by jonbesga** [comment]
And...I just fixed it using simple commas.
```
pgloader 'mysql://<user>:<password>@<host>/<database>' 'postgresql://<user>:<password>@<host>/<database>'
```

**Comment by dimitri** [comment]
More information at https://pgloader.readthedocs.io/en/latest/pgloader.html#connection-string and per-source database kind pages, such as https://pgloader.readthedocs.io/en/latest/ref/mysql.html#mysql-database-source-specification-from.

**Comment by alibaltschun** [comment]
> And...I just fixed it using simple commas.
> 
> ```
> pgloader 'mysql://<user>:<password>@<host>/<database>' 'postgresql://<user>:<password>@<host>/<database>'
> ```

i have tried it, error gone, just printed as ` 2019-05-02T11:04:05.024000Z LOG pgloader version "3.6.2~devel" ` . but nothing happens, i waited about 5 minutes, still nothing. do you have a solution?
