### ISSUE TITLE
How to LOAD DBF with NULL columns

### ISSUE THREAD

**Issue by steve-chavez** [dimitri/pgloader#938]
Using pgloader version "3.4.1".

I have a dbf file with some blank columns that I'd like to migrate. Following the instructions on https://pgloader.readthedocs.io/en/latest/ref/dbf.html. A table is created with the following structure:
```sql
                Table "public.my_table"
   Column   |  Type   | Collation | Nullable | Default 
------------+---------+-----------+----------+---------
 addr1      | text    |           | not null | 
 addr2      | text    |           | not null | 
 addr3      | text    |           | not null | 
 addr4      | text    |           | not null | 
 begdate    | date    |           | not null | 
```
Then, when copying the data, pgloader outputs the following errors:
```
2019-04-12T18:27:27.445000Z ERROR PostgreSQL ["my_table"] Database error 23502: null value in column "begdate" violates not-null constraint
```

Is it possible to disable NOT NULLs on table creation?

**Comment by dimitri** [comment]
The default is now reversed from _NOT NULL_ to nullable columns, so it should just work. As a benefit you can also use the CAST clause if needed.

**Comment by steve-chavez** [comment]
@dimitri Great! Thank you!

I'll await for the new release to test the new feature because I'm getting some ssl issues when trying to compile.

Thanks again :smile:.
