### ISSUE TITLE
[Docker] Potential issue with Dockerfile

### ISSUE THREAD

**Issue by AnrDaemon** [dimitri/pgloader#939]
The construction
```
RUN apt-get update \
      && apt-get install …
```
is often reported as nonfunctional for Debian based images due to error in image composition that prevent some lists from properly saving/reading.
A workaround is to ignore errors from `apt update`, f.e. `apt-get update; apt-get install …`

**Comment by dimitri** [comment]
Contributions welcome! Meanwhile we have something that works on docker hub, so I'm closing the issue here. If you think we should do something about it, consider re-opening with a Pull Request!
