### ISSUE TITLE
UNEXPECTED HTTP STATUS

### ISSUE THREAD

**Issue by efynn** [dimitri/pgloader#941]
Hello, I use mingw64 to compile Pgloader under Windows, run the make command caused some errors, should not be able to download the package, but if I copy the URL back to 403 into the browser, I can download it normally, how do I fix it? (My network is in normal condition)
![微信截图_20190418102758](https://user-images.githubusercontent.com/48084492/56333046-3c527800-61c5-11e9-982c-67261566cad7.png)

This is the package I copied the URL to the browser to download:
![微信截图_20190418103748](https://user-images.githubusercontent.com/48084492/56333248-04980000-61c6-11e9-82d7-72109b75c3ea.png)

**Comment by chensanf** [comment]
This is the version information：
![微信截图_20190418114430](https://user-images.githubusercontent.com/48084492/56335643-ea631f80-61cf-11e9-94db-106b53c55a84.png)

**Comment by dimitri** [comment]
I have no idea :/ I would say try again?

**Comment by chensanf** [comment]
Well, I think it's SBCL's problem

**Comment by chensanf** [comment]
Hello, I skipped the above error, it reminded me of "Component "cffi" not found", I found cffi is a python library, and I have installed the library is still not found, do you know what is going on? Should I specify the location of cffi when I run "make"? I'm sorry I don't know much about this. Thank you very much.
![微信截图_20190418173025](https://user-images.githubusercontent.com/48084492/56351434-adaf1c80-61ff-11e9-83e9-143b7be6934e.png)

**Comment by dimitri** [comment]
That's actually https://common-lisp.net/project/cffi/ and it should be installed automatically at build time. Can you try to build with the following command: `make save`, and if that fails: `make clones save`. Thanks.

**Comment by chensanf** [comment]
Hello, I remember the 2.x version was written in python. Is the 2.x version still applicable?How can I download it if I can?Because I have been compiling on the Windows operating system for a long time and have not compiled it (you know, Windows is not very friendly to compilation), but I must use it on Windows, may I know the support information of 2.x?Thank you for your reply.

**Comment by dimitri** [comment]
Try this method of compilation for windows, it might be easier as it doesn't rely on much of anything being around except for SBCL itself:

```
$ sbcl --load src/save.lisp
```

**Comment by chensanf** [comment]
Thank you for your reply, let me compile a lot faster! Now I have https://github.com/cl-plus-ssl/cl-plus-ssl/issues/53#issue-241485692 this problem. I have installed openssl--1.1.1a. Now I can't find two DLL files in the output. I have seen that you Shared this DLL file, but the url of the sharing link returned 404.Thank you.
<img width="1179" alt="微信图片_20190419142232" src="https://user-images.githubusercontent.com/48084492/56412114-b82bed80-62b5-11e9-971f-e7aa822d927c.png">
![微信截图_20190419150744](https://user-images.githubusercontent.com/48084492/56412123-bd893800-62b5-11e9-9810-456cd6d6e759.png)

**Comment by dimitri** [comment]
On other systems, Quicklisp installs the Common Lisp parts of the packages that are using an external DDL. I guess it's the same on windows, so that you have to install the necessary DDLs and make them available/visible by SBCL when compiling and then running pgloader. How to do that in windows? I don't know. On linux typically you need a _development_ package of OpenSSL so that you have the headers and the development DDL available on the system.

**Comment by efynn** [comment]
Hi, I downloaded these two DLLS, now where do I need to put these two files?Since I use mingw32, there is no disk symbol. This is a unix-like environment on Windows. Do I need to add the load path like CFLAGS in GCC?Now that I have these two files in the default search path of the environment, I can see the following output: "incapable to load any of the alternatives: ("libssl32.dll", "ssleay32.dll")

**Comment by efynn** [comment]
Above, by the way, I can not download package I received, now I found a way to download all of the required packages, run "make" command if received after the "ERROR" UNEXPECTED - HTTP - STATUS ", select "exit", don't run "make clean" to clean up bag, have downloaded again run "make", repeat it, you can download all of the packages, if under Windows have the same ERROR can try this method.

**Comment by chensanfeng** [comment]
I downloaded the 1.0.1 and 1.1.1 versions of openssl. I didn't get the libssl32.dll file after compiling. Is the version of openssl supported? thanks.

**Comment by efynn** [comment]
Hello, I downloaded and compiled 32-bit openssl--1.0.1.The required libssl32.dll and ssleay32.dll have been built here.And the test is available, but after I compile the pgloader and run the make command, I still get the output: "incapable to load any of the alternatives: ("libssl32.dll" "ssleay32.dll")
![微信截图_20190422103146](https://user-images.githubusercontent.com/48084492/56479805-d8dc8900-64e9-11e9-8838-19382e9347c6.png)

**Comment by dimitri** [comment]
I don't know how windows looks up for DDL files, and I don't know how SBCL or CFFI implement DDL lookup on windows either. Can you try copying the DDL file in the current directory, and when pgloader has been built, in the same directory as the resulting `pgloader.exe` file?

**Comment by dimitri** [comment]
Closing the issue now. Please consider opening again if needed.

**Comment by avodonosov** [comment]
For the record: the DLLs were not found because OpenSSL 1.1 names it differently: libssl-1_1.dll / libssl-1_1-x64.dll.

These names are now added to cl+ssl, so using cl+ssl from master or waiting for Quicklisp update will fix the issue.

As a workaround, the OP could have loaded the foreign libraries himself before loading cl+ssl:

```common-lisp
        (cffi:load-foreign-library "libssl.so.1.0.0")

        (let ((*features* (cons :cl+ssl-foreign-libs-already-loaded
                                *features*)))

          ;; load pgloader
         )
```
