### ISSUE TITLE
Travis builds broken for SBCL

### ISSUE THREAD

**Issue by phoe** [dimitri/pgloader#946]
When trying to check a PR for https://github.com/dimitri/pgloader/pull/945 I have noticed that the SBCL jobs break while compiling ironclad:

```lisp
...
[package ironclad]................................
[package ironclad-vm]...................
debugger invoked on a SB-INT:SIMPLE-PROGRAM-ERROR in thread
#<THREAD "main thread" RUNNING {1001F17393}>:
  invalid number of arguments: 5
Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.
restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Retry
                                     compiling #<IRONCLAD-SOURCE-FILE "ironclad" "src" "common">.
  1: [ACCEPT                       ] Continue, treating
                                     compiling #<IRONCLAD-SOURCE-FILE "ironclad" "src" "common">
                                     as having been successful.
  2:                                 Retry ASDF operation.
  3: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  4: [ABORT                        ] Give up on "pgloader"
  5: [CONTINUE                     ] Ignore runtime option --eval "(ql:quickload \"pgloader\")".
  6:                                 Skip rest of --eval and --load options.
  7:                                 Skip to toplevel READ/EVAL/PRINT loop.
  8: [EXIT                         ] Exit SBCL (calling #'EXIT, killing the process).
(SB-X86-64-ASM::|movzx| #<SB-ASSEM:SEGMENT :TYPE :REGULAR> #<SB-C::VOP :INFO UB32REF/LE :ARGS #<SB-C:TN-REF :TN #<SB-C:TN INPUT-BLOCK1!1[RDI]> :WRITE-P NIL :VOP UB32REF/LE> :RESULTS #<SB-C:TN-REF :TN #<SB-C:TN t2[RDX]> :WRITE-P T :VOP UB32REF/LE>> (:DWORD :QWORD) #<SB-C:TN t2[RDX]> #<SB-X86-64-ASM::EA :DWORD base=#<SB-C:TN INPUT-BLOCK1!1[RDI]> index=#<SB-C:TN t3[RDX]> disp=1>) [external]
0] 
```

Example affected jobs:
https://travis-ci.org/dimitri/pgloader/jobs/522965555
https://travis-ci.org/dimitri/pgloader/jobs/522965556

A possible fix is upgrading SBCL from 1.3.18 that is used in the Travis jobs to a more recent version. It is possible that the mainline ironclad no longer supports 1.3.18 - it is almost two years old now.

**Comment by dimitri** [comment]
Yeah, using something more recent sounds like a good idea. Do you want to try that in a dedicated PR?

**Comment by dimitri** [comment]
Fixed. in https://github.com/dimitri/pgloader/commit/ede385bce72f61228529cce0985681a121f5a1a5 then in https://github.com/dimitri/pgloader/commit/781e58681624adebecc15a9416b718c2023c8fec and finally in https://github.com/dimitri/pgloader/commit/ca92cdbf20ffa59bc6343b10576c91036525d405. Because that's how you work with Travis.

And then fixed for real in https://github.com/dimitri/pgloader/commit/351ce3faafa2853bbefae3e87bbde043c0b6be04 because actually we had a lisp problem in the middle of other problems.
