### ISSUE TITLE
Travis builds download pgloader from Quicklisp

### ISSUE THREAD

**Issue by phoe** [dimitri/pgloader#947]
When trying to check a PR for https://github.com/dimitri/pgloader/pull/945 I have noticed that the CCL jobs break while compiling ironclad:

```lisp
[package pgloader.user-symbols]..........
> Error: Lambda list of method #<STANDARD-METHOD RESET-STATE (PARSER)> 
>        is incompatible with that of the generic function RESET-STATE.
>        Method's lambda-list : (P &KEY TAGP)
>        Generic-function's   : (P)
```

Example affected jobs:
https://travis-ci.org/dimitri/pgloader/jobs/522965553
https://travis-ci.org/dimitri/pgloader/jobs/522965554

This is because pgloader is loaded twice in the build process: first, it is loaded from Quicklisp, second, it is loaded from the freshly modified source.

```lisp
ccl --no-init --load build/quicklisp/setup.lisp                   \
             --eval '(push :pgloader-image *features*)'               \
             --eval '(setf *print-circle* t *print-pretty* t)'        \
             --eval '(ql:quickload "pgloader")'                       \
             --eval '(push "/home/travis/build/dimitri/pgloader/" ql:*local-project-directories*)' \
             --eval '(ql:quickload "pgloader")'                       \
             --eval '(quit)'
```

This approach prevents any function in pgloader to be incompatibly redefined, which is the case in my patch. I do not understand why your Travis jobs load pgloader from Quicklisp at all instead of depending just on the built sources - are you testing if the mainline Quicklisp release works in Travis jobs?

**Comment by dimitri** [comment]
Well I had too many problems maintaining the Travis environment. Most failures used to be about Travis, not about pgloader source code, so I'm not even looking at it anymore. It's known to be broken, and I would welcome contributions to maintain Travis for us.

Nowadays the docker files seems to be in a much better shape and easier to maintain, so maybe we could see about using a docker environment in Travis, or even switch to Circle-CI or another OSS friendly provider of per-commit testing?

Ideally we would have a way to build that also published the resulting binary, and maybe later that supports windows. Not there yet.

**Comment by dimitri** [comment]
I've spend some time recently on fixing Travis builds again, and I think I solved that issue now. Please consider re-opening with details if that's not the case.
