### ISSUE TITLE
Does PGLOADER available for Redhat 5.11 with postgresql 9.1 Client 

### ISSUE THREAD

**Issue by sanjum080816** [dimitri/pgloader#948]
Hello Dmitri ,

Is PGLOADER available for Redhat 5.11 with postgresql 9.1 Client . 

If so could you please guide which version should be installed and the behaviour of it related to old redhat 5.11 version with postgresql 9.1 client on it .

**Comment by dimitri** [comment]
Just try the following steps:

  1. install a recente SBCL on your system, from http://www.sbcl.org
  2. get the latest release of pgloader from the releases here at GitHub, the bundle format
  3. in the bundle directory, type `make save`
  4. try `./bin/pgloader --version` and then using it for your use-case

Report problems you might have.
