### ISSUE TITLE
pgloader reports non existing table

### ISSUE THREAD

**Issue by VirtumartOz** [dimitri/pgloader#952]
```
[root@host2 ~/pgloader-bundle-3.6.1]# pgloader mysql://homestead:homestead@localhost/homestead pgsql://dbuser@localhost/exampledb
2019-04-28T00:10:26.125000-04:00 LOG Main logs in '/tmp/pgloader/pgloader.log'
2019-04-28T00:10:26.143000-04:00 LOG Data errors in '/tmp/pgloader/'
2019-04-28T00:10:28.960000-04:00 ERROR Database error 42704: type "posts_status" does not exist
QUERY: DROP TYPE "posts_status" CASCADE;
2019-04-28T00:10:28.961000-04:00 FATAL Failed to create the schema, see above.
       table name       read   imported     errors      total time       read      write
-----------------  ---------  ---------  ---------  --------------  ---------  ---------
  fetch meta data        207        207          0          1.194s
 Create SQL Types          0          0          0          0.000s
```

----------------------
hi see above, there is a posts table in old mysql database, but there's no posts_status

i tried another mysql database, similar table, it reports xxxxxxx_extension table doesn't exis, where xxxxxxx is an mysql table which exists 

pgloader version 3.3.1

```
[root@host2 ~]# pgloader --version
pgloader version "3.3.1"
compiled with SBCL 1512.-513455f
```

because i failed to compile version 3.6.0 or 3.6.1 on centos 6

**Comment by dimitri** [comment]
Hi,

My guess is that the `posts` table in MySQL has a `status` column that is an ENUM, and then pgloader has to deal with a `post_status` enum data type in PostgreSQL. Now, version 3.3.1 is old, you have to find a way to use current 3.6.1 or build from master's branch.

Given CentOS 6 you might need to download a recent version of SBCL to be able to compile from the bundle release of pgloader. See http://www.sbcl.org for details.

**Comment by dimitri** [comment]
Closing this issue now. Please re-open with more information if needed. About using 3.6.1, I cleaned-up both the Travis and DockerHub setup, so it should be easy enough to build.
