### ISSUE TITLE
Build Failed: Symbol "CLOSE-MEMO" not found in the DB3 package

### ISSUE THREAD

**Issue by JeffJankowski** [dimitri/pgloader#954]
- [x] did you test a fresh compile from the source tree?
    
    Cloned directly from master branch and ran `make`.
    
  - [x] did you search for other similar issues?
    
    [#940](https://github.com/dimitri/pgloader/issues/940), but I'm building directly from source, not the bundle.

  - [x] how can I reproduce the bug?

    Build from fresh sources under Ubuntu 18.04.

  - [x] pgloader output you obtain
  
```
[package pgloader.user-symbols]...................
..................................................
; 
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Symbol "CLOSE-MEMO" not found in the DB3 package.
;   
;       Line: 26, Column: 17, File-Position: 816
;   
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/jeff/pgloader/src/sources/db3/db3-schema.lisp" {1003290613}>

debugger invoked on a UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread
#<THREAD "main thread" RUNNING {10005E85B3}>:
  COMPILE-FILE-ERROR while
  compiling #<CL-SOURCE-FILE "pgloader" "src" "sources" "db3" "db3-schema">
```

**Comment by dimitri** [comment]
This error happens because the cl-db3 system didn't use to export the `close-memo` symbol and it now does, but your local copy isn't uptodate. To update your local copy for building pgloader, try `make clean`. Then you can `make` again.

**Comment by JeffJankowski** [comment]
I tried `make clean` as per the other thread, but it didn't change anything. I just pulled the sources today, so there wasn't anything lingering in the build folder to begin with.

**Comment by dimitri** [comment]
So the change you need is in the commit https://github.com/dimitri/cl-db3/commit/13f380d3860fa2ec7289d8d9a20e4b47b3d69248 on the cl-db3 system. Can you make sure you have that in `pgloader/build/quicklisp/local-projects/cl-db3`? BTW are you using the default `make` or the experimental `make save` facility to build the pgloader binary?

**Comment by JeffJankowski** [comment]
Forgive my ignorance, but I can't seem to get that directory to populate to check if the commit is there while the build is failing.
I am using the default `make` to build, but I tried `make save` once with no change.

**Comment by JeffJankowski** [comment]
Following the trail of [#933](https://github.com/dimitri/pgloader/issues/933), I copied the cl-db3 repo files into `pgloader/build/quicklisp/dists/quicklisp/software/cl-db3-20150302-git`, which allowed me to compile successfully. 

Unfortunately I encountered a different runtime error:
```
FATAL error: Undefined alien: "SSLeay"
Date/time: 2019-04-29-02:01An unhandled error condition has been signalled:
                              Undefined alien: "SSLeay"


Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10007385B3}>
0: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE-TO-STREAM #<SB-IMPL::STRING-OUTPUT-STREAM {100686C863}>)
1: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE #<SB-KERNEL:UNDEFINED-ALIEN-STYLE-WARNING {100686C6F3}> :OUTPUT NIL :IF-EXISTS :APPEND :VERBOSE NIL)
2: ((FLET "H0" :IN PGLOADER::MAIN) #<SB-KERNEL:UNDEFINED-ALIEN-STYLE-WARNING {100686C6F3}>)
3: (SB-KERNEL::%SIGNAL #<SB-KERNEL:UNDEFINED-ALIEN-STYLE-WARNING {100686C6F3}>)
4: ((FLET SB-KERNEL::%WARN :IN "SYS:SRC;CODE;WARM-ERROR.LISP") SB-KERNEL:UNDEFINED-ALIEN-STYLE-WARNING #<SB-KERNEL::CONDITION-CLASSOID STYLE-WARNING> SB-INT:SIMPLE-STYLE-WARNING :SYMBOL "SSLeay")
5: (SB-SYS:ENSURE-DYNAMIC-FOREIGN-SYMBOL-ADDRESS "SSLeay" NIL)
6: ((FLET SB-THREAD::WITH-RECURSIVE-SYSTEM-LOCK-THUNK :IN SB-SYS:UPDATE-LINKAGE-TABLE))
...
```

**Comment by JeffJankowski** [comment]
Upgrading to SBCL 1.5.1 solves the previous runtime crash.

@dimitri You'll probably still want to look into why `cl-db3` isn't being correctly pulled in by `make`. I appreciate all your efforts. Great tool!

**Comment by dimitri** [comment]
I don't think the `SSLeay` compilation error has anything to do with the momentary unsync of a dependency in the Quicklisp distribution, so I'm going to close that issue as it is now. The trouble with grovelling and then linking symbols from shared objects in the Common Lisp image is well known to me and I wish I knew how to solve that, but to this day that's not the case (spoiler: I didn't spend too much time and energy on that problem, I just wish someone would step up and solve it for us).
