### ISSUE TITLE
sqlite int(X) problem

### ISSUE THREAD

**Issue by rmarzocchi84** [dimitri/pgloader#957]
I try to import a sqlite DB. It give me a FATAL error 

```
CREATE TABLE jacl2_group
(
  ...
  grouptype  int(5) default '0',
  ....
);
```

The errot is

` ERROR Database error 42601: syntax error at or near "("
`
Effectively the query is not allowed by postgresql while the following query can work

```
CREATE TABLE jacl2_group
(
  ...
  grouptype  int default '0',
  ....
);
```

How can I solve the problem? I compiled the v.3.6.1 on ubuntu 18.04

**Comment by dimitri** [comment]
We don't have a default casting rule from `int` in SQLite, so you need a specific one. In your load command, add the following clause:

```
   cast type int to integer drop typemod keep default
```

**Comment by dimitri** [comment]
I'm closing this issue. If actions are needed still, please re-open with more information.
