### ISSUE TITLE
 predicate PGLOADER.PARSER::SYMBOL-FIRST-CHARACTER-P

### ISSUE THREAD

**Issue by FabyLomb** [dimitri/pgloader#965]
Hi, I've a problem with my .load file. I try to transform a string that in input has more than 1 blank character (for example 'Hello'' '' '' '' '' ''World') in a string with only one blank character (for example Hello World). 
I try with:

SOLUTION 1 : myfile1.LOAD

```
LOAD CSV FROM '/myDIR/myFile.csv'
 WITH ENCODING utf8
        HAVING FIELDS
        (
	MYSTRING [trim both whitespace]
	        )
   INTO postgresql://USER:PWD@MYDB:5432/USER_DB
        TARGET TABLE MYTABLE
        TARGET COLUMNS
        (
     MYSTRING  text using (REGEXP_REPLACE(MYSTRING ,'( ){2,}',' '))
) 
WITH fields optionally enclosed by ''', 
fields escaped by backslash-quote, 
fields terminated by '|' SET work_mem to '32 MB', 
maintenance_work_mem to '64 MB';
```

In this case I've the following errors:

```
KABOOM!
FATAL error: At

          (
        MYSTRING  text using (REGEXP_REPLACE(MYSTRING ,'( ){2,}',' '))

                                                         ^ (Line 11, Column 55, Position 233)

In context SEXP-LIST:

While parsing SEXP-LIST. Problem:

  The production

    #\)

  does not satisfy the predicate PGLOADER.PARSER::SYMBOL-FIRST-CHARACTER-P.

Expected:

     the character Tab
  or the character Newline
  or the character Return
  or the character Space
  or the character " (QUOTATION_MARK)
  or the character ( (LEFT_PARENTHESIS)
  or the string "--"
  or the string "/*"
  or the character 0 (DIGIT_ZERO)
  or the character 1 (DIGIT_ONE)
  or the character 2 (DIGIT_TWO)
  or the character 3 (DIGIT_THREE)
  or the character 4 (DIGIT_FOUR)
  or the character 5 (DIGIT_FIVE)
  or the character 6 (DIGIT_SIX)
  or the character 7 (DIGIT_SEVEN)
  or the character 8 (DIGIT_EIGHT)
  or the character 9 (DIGIT_NINE)
  or any character satisfying SYMBOL-FIRST-CHARACTER-P
```

SOLUTION 2 : myfile2.LOAD

```
LOAD CSV FROM '/myDIR/myFile.csv'
 WITH ENCODING utf8
        HAVING FIELDS
        (
	MYSTRING [trim both whitespace]
	        )
   INTO postgresql://USER:PWD@MYDB:5432/USER_DB
        TARGET TABLE MYTABLE
        TARGET COLUMNS
        (
     MYSTRING text using (let ((space (aref " " 0)))
                            (remove space (string MYSTRING)))
) 
WITH fields optionally enclosed by ''', 
fields escaped by backslash-quote, 
fields terminated by '|' SET work_mem to '32 MB', 
maintenance_work_mem to '64 MB';
```

It works but I've 'HelloWorld' instead of 'Hello World'. Can you help me please?

**Comment by dimitri** [comment]
See https://stackoverflow.com/questions/8830888/whats-the-canonical-way-to-join-strings-in-a-list for examples on how solve the problem at hand. I would try with the following code:

```
  mystring text using (format nil "~{~a~^ ~}" (split-sequence:split-sequence #\Space mystring :remove-empty-subseqs t))
```

**Comment by FabyLomb** [comment]
Thank you. I try to do this but now I've the following error:

 in: LAMBDA (PGLOADER.SOURCES::ROW)
;     (PGLOADER.USER-SYMBOLS::|SPLIT-SEQUENCE:SPLIT-SEQUENCE|
;      PGLOADER.USER-SYMBOLS::|#\\SPACE| PGLOADER.USER-SYMBOLS::mystring
;      PGLOADER.USER-SYMBOLS::|:REMOVE-EMPTY-SUBSEQS| PGLOADER.USER-SYMBOLS::T)
;
; caught WARNING:
;   undefined variable: PGLOADER.USER-SYMBOLS::|#\\SPACE|
;
; caught WARNING:
;   undefined variable: PGLOADER.USER-SYMBOLS::|:REMOVE-EMPTY-SUBSEQS|
;
; caught STYLE-WARNING:
;   undefined function: PGLOADER.USER-SYMBOLS::|SPLIT-SEQUENCE:SPLIT-SEQUENCE|
;
; caught WARNING:
;   undefined variable: PGLOADER.USER-SYMBOLS::T
;
; compilation unit finished
;   Undefined function:
;     PGLOADER.USER-SYMBOLS::|SPLIT-SEQUENCE:SPLIT-SEQUENCE|
;   Undefined variables:
;     PGLOADER.USER-SYMBOLS::|#\\SPACE| PGLOADER.USER-SYMBOLS::|:REMOVE-EMPTY-SUBSEQS| PGLOADER.USER-SYMBOLS::T
;   caught 3 WARNING conditions
;   caught 1 STYLE-WARNING condition
2019-05-14T15:43:38.205000+02:00 ERROR Could not read input: The variable PGLOADER.USER-SYMBOLS::|#\\SPACE| is unbound.

Thanks a lot!

**Comment by dimitri** [comment]
So yeah  it was a little more involved that that to make it work, so I added some support in the s-expression parser. Now you can write it this way, with the new pgloader code (build from source or use the docker image as soon as it's ready):

```
   TARGET TABLE sexp
        (
          id,
          f1 text using (format nil "~{~a~^ ~}"
                          (split-sequence #\Space f1 :remove-empty-subseqs cl:t))
        )
```

With the code you have already, you need to write a more convoluted expression, and you can't access split-sequence directly. Ah, sandboxing is useful but make some things more complex than they could be.
