### ISSUE TITLE
KABOOM!

### ISSUE THREAD

**Issue by efynn** [dimitri/pgloader#966]
Hello, when I started the migration, I got this output. Do you know what happened?

```
What I am doing here?

Control stack exhausted (no more space for function call frames).
This is probably due to heavily nested or infinitely recursive function
calls, or a tail call that SBCL cannot or has not optimized away.

PROCEED WITH CAUTION.
```

**Comment by dimitri** [comment]
Which version of pgloader are you using? it looks like a bug that has been fixed, so maybe you could try a more recent version. Compile from current sources or use one of the docker images that are built at each commit?

**Comment by efynn** [comment]
V3.6.1，I compile from source code，I'm not sure whether this: https://github.com/dimitri/pgloader/commit/4ec8613884cee74edfed7374278766b5644a9a55

**Comment by efynn** [comment]
That's it. Solved. Thank you
