### ISSUE TITLE
build error debian stretch by tutorial

### ISSUE THREAD

**Issue by WorldException** [dimitri/pgloader#969]
Stable error with same version on debian stretch

sbcl --version
SBCL 1.3.14.debian

I try on branches
- master
- v3.6.1
- v3.6.0

output
```
[package nibbles].................................
[package ironclad]................................
[package ironclad-vm]...................
debugger invoked on a SB-INT:SIMPLE-PROGRAM-ERROR in thread
#<THREAD "main thread" RUNNING {1001E06E83}>:
  invalid number of arguments: 5

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Retry
                                     compiling #<IRONCLAD-SOURCE-FILE "ironclad" "src" "common">.
  1: [ACCEPT                       ] Continue, treating
                                     compiling #<IRONCLAD-SOURCE-FILE "ironclad" "src" "common">
                                     as having been successful.
  2:                                 Retry ASDF operation.
  3: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  4: [ABORT                        ] Give up on "pgloader"
  5: [CONTINUE                     ] Ignore runtime option --eval "(ql:quickload \"pgloader\")".
  6:                                 Skip rest of --eval and --load options.
  7:                                 Skip to toplevel READ/EVAL/PRINT loop.
  8: [EXIT                         ] Exit SBCL (calling #'EXIT, killing the process).

(SB-X86-64-ASM::|movzx| #<SB-ASSEM:SEGMENT :TYPE :REGULAR> #<SB-C::VOP :INFO UB32REF/LE :ARGS #<SB-C:TN-REF :TN #<SB-C:TN INPUT-BLOCK1!1[RDI]> :WRITE-P NIL :VOP UB32REF/LE> :RESULTS #<SB-C:TN-REF :TN #<SB-C:TN t2[RDX]> :WRITE-P T :VOP UB32REF/LE>> (:DWORD :QWORD) #<SB-C:TN t2[RDX]> #<SB-X86-64-ASM::EA :DWORD base=#<SB-C:TN INPUT-BLOCK1!1[RDI]> index=#<SB-C:TN t3[RDX]> disp=1>) [tl,external]
0] 
```

**Comment by WorldException** [comment]
fixed with

apt install cl-ironclad cl-babel

but new error

[package pgloader]................................
[package pgloader.user-symbols]...................
..................................................
.............; 
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Symbol "CLOSE-MEMO" not found in the DB3 package.
;   
;       Line: 26, Column: 17, File-Position: 816
;   
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /opt/pgloader/src/sources/db3/db3-schema.lisp" {1002064D13}>

debugger invoked on a UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread
#<THREAD "main thread" RUNNING {1001E06E83}>:
  COMPILE-FILE-ERROR while
  compiling #<CL-SOURCE-FILE "pgloader" "src" "sources" "db3" "db3-schema">

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Retry
                                     compiling #<CL-SOURCE-FILE "pgloader" "src" "sources" "db3" "db3-schema">.
  1: [ACCEPT                       ] Continue, treating
                                     compiling #<CL-SOURCE-FILE "pgloader" "src" "sources" "db3" "db3-schema">
                                     as having been successful.
  2:                                 Retry ASDF operation.
  3: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  4: [ABORT                        ] Give up on "pgloader"
  5: [CONTINUE                     ] Ignore runtime option --eval "(ql:quickload \"pgloader\")".
  6:                                 Skip rest of --eval and --load options.
  7:                                 Skip to toplevel READ/EVAL/PRINT loop.
  8: [EXIT                         ] Exit SBCL (calling #'EXIT, killing the process).

(UIOP/LISP-BUILD:CHECK-LISP-COMPILE-RESULTS NIL T T "~/asdf-action::format-action/" ((#<ASDF/LISP-ACTION:COMPILE-OP > . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "pgloader" "src" "sources" "db3" "db3-schema">)))
0]

**Comment by WorldException** [comment]
apt install cl-ironclad cl-babel
git clone --depth 1 https://github.com/dimitri/cl-db3.git local-projects/cl-db3

new error

[package pgloader.user-symbols]...................
..................................................
..................................................
..................................................
.....
To load "pgloader":
  Load 1 ASDF system:
    pgloader
; Loading "pgloader"

debugger invoked on a SB-PCL::FIND-METHOD-LENGTH-MISMATCH in thread
#<THREAD "main thread" RUNNING {1001E06E83}>:
  The generic function #<STANDARD-GENERIC-FUNCTION DB3::CONVERT-FIELD (2)>
  takes 2 required arguments; was asked to find a method with specializers
  (#<SB-PCL:SYSTEM-CLASS COMMON-LISP:T> #<SB-PCL:SYSTEM-CLASS COMMON-LISP:T>
   #<SB-PCL:SYSTEM-CLASS COMMON-LISP:T>)
See also:
  The ANSI Standard, Function FIND-METHOD

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [TRY-RECOMPILING              ] Recompile db3 and try loading it again
  1: [RETRY                        ] Retry
                                     loading FASL for #<CL-SOURCE-FILE "db3" "db3">.
  2: [ACCEPT                       ] Continue, treating
                                     loading FASL for #<CL-SOURCE-FILE "db3" "db3">
                                     as having been successful.
  3:                                 Retry ASDF operation.
  4: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  5: [ABORT                        ] Give up on "pgloader"
  6: [CONTINUE                     ] Ignore runtime option --eval "(ql:quickload \"pgloader\")".
  7:                                 Skip rest of --eval and --load options.
  8:                                 Skip to toplevel READ/EVAL/PRINT loop.
  9: [EXIT                         ] Exit SBCL (calling #'EXIT, killing the process).

(SB-PCL::REAL-GET-METHOD #<STANDARD-GENERIC-FUNCTION DB3::CONVERT-FIELD (2)> NIL (#1=#<SB-PCL:SYSTEM-CLASS COMMON-LISP:T> #1# #1#) NIL T)
0] 9

**Comment by WorldException** [comment]
check 2 ACCEPT on this error continue compilation with success.

build/bin/pgloader --version
pgloader version "3.6.ee75bc4"
compiled with SBCL 1.3.14.debian

**Comment by dimitri** [comment]
The first problem is because you have a too old SBCL version. Recent ironclad depends on a recent SBCL, so you need something in the 1.5.x version I believe. Then, pgloader depend also on cl-db3 which I update recently, so you need to fetch the most recent version of it. That's easy: `make clean; make` should do that for you.
