### ISSUE TITLE
Convert from MySQL to Postgress dump file

### ISSUE THREAD

**Issue by rhoman** [dimitri/pgloader#979]
Hello guys,

I have environment where I cannot install postgress at this moment. 
Would it be possible to configure the script to read from MySQL DB and convert to postgress, but create dumpfile instead of DB?

**Comment by dimitri** [comment]
There's no support for targeting files from pgloader at the moment. The idea is to validate the data as it is being loaded, and that require actually talking to a live Postgres installation. Without doing the data validation, what good would pgloader be for you really, anyway?
