### ISSUE TITLE
Migrate partial tables

### ISSUE THREAD

**Issue by efynn** [dimitri/pgloader#980]
Hello, thanks for such a good tool, I have some questions when using, how to migrate part of the table instead of the whole database?Thank you.

**Comment by dimitri** [comment]
Have a look at the MATERIALIZE VIEWS clause of the pgloader command, for instance at https://pgloader.readthedocs.io/en/latest/ref/mysql.html#mysql-views-support ; this allows you to transform the source data in any way you want, provided that you can express the transformation in SQL. WHERE clause would be useful to migrate only a part of the table, or maybe a LIMIT clause ; but then you need to think about foreign keys maybe.
