### ISSUE TITLE
MySQL to PostgreSQL default casting rules

### ISSUE THREAD

**Issue by jakub-olczyk** [dimitri/pgloader#982]
I want to migrate a MySQL database to PostgreSQL. During migration I found some PostgreSQL errors concerning the creation of foreign keys due to referenced columns being of `numeric` type. 

As it turned out after inspecting the default casting rules for MySQL conversion I found the culprit of my problem:
```common-lisp
    ;; bigint(20) unsigned (or not, actually) does not fit into PostgreSQL
    ;; bigint (-9223372036854775808 to +9223372036854775807):
    (:source (:type "bigint" :typemod (< 19 precision))
     :target (:type "numeric" :drop-typemod t))
```
I'd argue that this isn't the full picture. True, the unsigned version in MySQL according to the [official limits][0]:

Type     | Min signed | Min unsigned | Max signed | Max unsigned
----------|----------------|------------------|-----------------|------------------
BIGINT |          -2^63 |                    0 |        2^63-1 |         2^64-1

is out of bounds for Postgres, but the signed version is exactly the same:

Type | Range
--------|---------------------------------------------------------------------
bigint | -9223372036854775808 to +9223372036854775807

according to [the official docs][1]. Or am I mistaken on this issue?

Could we perhaps change the default casting rules? I am not versed in Lisp but maybe could this work:

```common-lisp
    (:source (:type "bigint" :unsigned t)
     :target (:type "numeric" :drop-typemod t))
```
?

Also, I couldn't find any reference to this casting rule in the pgloader documentation as well. Here's the numeric types portion:
```
type int with extra auto_increment to serial when (< precision 10)
type int with extra auto_increment to bigserial when (<= 10 precision)
type int to int       when  (< precision 10)
type int to bigint    when  (>= 10 precision)
type tinyint   with extra auto_increment to serial
type smallint  with extra auto_increment to serial
type mediumint with extra auto_increment to serial
type bigint    with extra auto_increment to bigserial

type tinyint to boolean when (= 1 precision) using tinyint-to-boolean

type tinyint when unsigned to smallint   drop typemod
type smallint when unsigned to integer  drop typemod
type mediumint when unsigned to integer  drop typemod
type integer when unsigned to bigint    drop typemod

type tinyint to smallint   drop typemod
type smallint to smallint  drop typemod
type mediumint to integer  drop typemod
type integer to integer    drop typemod
type bigint to bigint      drop typemod

type float to float        drop typemod
type double to double precision drop typemod

type numeric to numeric keep typemod
type decimal to decimal keep typemod
```

pgloader --version
```shell
$ pgloader --version
pgloader version "3.6.1"
compiled with SBCL 1.4.0-1.el7
```

[0]: https://dev.mysql.com/doc/refman/5.7/en/integer-types.html
[1]: https://www.postgresql.org/docs/current/datatype-numeric.html

**Comment by jakub-olczyk** [comment]
I couldn't stop thinking about the comment in the source code and the `(< 19 precision)` and so I just wanted to add my find from the MySQL documentation for this precision parameter for numeric types:

> MySQL supports an extension for optionally specifying the **display width** of integer data types in parentheses following the base keyword for the type.[...] The display width does not constrain the range of values that can be stored in the column. Nor does it prevent values wider than the column display width from being displayed correctly.

(Emphasis mine.)
Taken from here: https://dev.mysql.com/doc/refman/5.7/en/numeric-type-attributes.html

So I undarstand that the assumption here is the same as for the string types in MySQL where the number in parenthesis actually changes the underlying storage.

Although, I can see the potential benefit for using this attribute annotation for analysing the intention behind each column type (including the numerical ones), in this case I think that it really is a potential bug (at least in the documentation side). Here is my example of configuration file that handles this case if you think that this issue is best solved in the docs:
```
LOAD DATABASE
        FROM mysql://root@localhost/test
        INTO postgresql://postgres@localhost:5432/test
CAST
        type bigint when unsigned to numeric drop typemod,
        type bigint when (= precision 20) to bigint drop typemod
```
If I understand correctly the syntax of configuration this should work around the currently default rule at least for my case where the primary keys are reported as `bigint(20)` type.

Cheers!

PS. Thank you for your amazing work on pgloader!

**Comment by dimitri** [comment]
Maybe we should add the possibility to target signed columns rather than only unsigned ones, so that you can add a user rule about signed bigint with 20 digits. I'll see about that. Meanwhile, what @jakub-olczyk says...

**Comment by dimitri** [comment]
I have patched pgloader to accept special `when signed` guard in casting rules and implement a default one for signed bigint in MySQL to target the PostgreSQL bigint. Also because things are not displayed in the same way, I'm adding how to check that the signed MySQL bigint range is the same as the PostgreSQL bigint range:

```
pgloader# select (2::numeric^63 -1)::bigint - 9223372036854775807;
 ?column? 
══════════
        0
(1 row)
```

Thanks!

**Comment by jakub-olczyk** [comment]
Thank you for solving the problem so quickly!
