### ISSUE TITLE
Dont load rows marked as deleted on DBFs

### ISSUE THREAD

**Issue by mrodal** [dimitri/pgloader#985]
- [ ] pgloader --version
  pgloader version "3.6.d8b0bd5"
compiled with SBCL 1.4.5.debian
  
  - [X] did you test a fresh compile from the source tree?
    Yes
    

  - [x] did you search for other similar issues?
    Yes
  - [ ] how can I reproduce the bug?
[test.zip](https://github.com/dimitri/pgloader/files/3269303/test.zip)
Import this file. It has a deleted row and a non deleted row, but pgloader imports both

**Comment by dimitri** [comment]
Should be ok now with the attached changes. Please build pgloader from sources and `make clean` before you do, so that you trigger a fresh download of the cl-db3 underlying project, which needs an update in its API too.
