### ISSUE TITLE
Syntax difference MS SQL - other DB

### ISSUE THREAD

**Issue by sorix6** [dimitri/pgloader#987]
According to the online documentation and my own experience with implementing migrations from MSSQL, MySQL and Postgres, the syntax for including specific tables only is not the same:

- MySQL:
 -- INCLUDING ONLY TABLE NAMES MATCHING ~/film/, 'actor'

- Postgres:
-- including only table names matching 'bits', ~/utilisateur/ in schema 'mysql'
** Also, I think this schema name should be changed in the documentation, as it is confusing

- MSSQL:
-- including only table names like 'GlobalAccount' in schema 'dbo'

Should this be updated so that MSSQL has the same syntax?

Thanks!

**Comment by dimitri** [comment]
Hi @sorix6 ! Good question!

The idea is to use the SQL engine matching operators. PostgreSQL provides regular expression matching using the `~` operator. MySQL provides regular expression matching using the `REGEXP` operator. MS SQL provides only SQL standard `LIKE` operator. 

I wanted the syntax in the pgloader command to reflect the kind of matching that is implemented in SQL, whether regex or like patterns.
