### ISSUE TITLE
UPPERCASE LETTER MATTERS

### ISSUE THREAD

**Issue by hdanet** [dimitri/pgloader#988]
Dear Dimitri,
Thank you for your great work.I am in difficulty in solving uppercase letters tablename. 
pgloader --type CSV -D /home/postgres/pgloader -L /home/postgres/pgloader/g.log --with quote identifiers --with "fields terminated by '^A'" /home/postgres/pgloader/JCXX.txt postgresql:///testb?tablename=FM.JCXX

but failed. How to correct it?I have read Issue #476, but still not success.

**Comment by dimitri** [comment]
I think you need to have `--with "quote identifiers" on the command line, and also, you need to quote the table name: `"FM"."JCXX"`. Of course, you need to do so in a way that pgloader sees the quotation marks, not just your shell. Consider writing a full command in a file such as `jcxx.load` where it's easier to deal with the quoting in the command itself.

**Comment by hdanet** [comment]
Thank you very much for your kind replay.I realized that stupid error by myself.I am very appreciated for you hints on uppercase letters.

I have another question about pgloader. My data file contains some data out of range, for example, out of range of int. I want to load into database base forcefully,Is it possible for pgloader?I checked the document without an answer.Thank you.

**Comment by dimitri** [comment]
What about having a `bigint` column to host the data that doesn't fit in an `integer` representation? Or even go as far as numeric, which offers arbitrary precision (unlimited or almost, up to 1GB of internal representation).

**Comment by hdanet** [comment]
Thank you for your replay.It is a really good solution to converting an integer to a bigint or a numeric.However,I cannot change the column.Meanwhile, the data in my file is illegal due to its out of range of integer.Is that any way to cut it to integer when loading?

**Comment by hdanet** [comment]
Furthermore, the rejected.dat file seperates fields by tab?Would you please tell me how to import the reject.dat or make the format of rejected.dat same as original file?
