### ISSUE TITLE
"Control stack exhausted (no more space for function call frames). This is probably due to heavily nested or infinitely recursive function calls, or a tail call that SBCL cannot or has not optimized away." when migrating a table from MySQL to Postgres on Google Cloud SQL

### ISSUE THREAD

**Issue by traumonaut** [dimitri/pgloader#992]
**Description:**

I encounter this error when I try to copy tables from MySQL to Postgres on **Google Cloud SQL** (Postgres server version is 9.6.11).
I wasn't able to reproduce the error locally. With a Postgres 9.6 docker container as the target everything works fine, so I assume it is somehow related to Cloud SQL. 
I am not sure how to proceed from here, because the error message is a bit generic. Do you have any idea on how to further debug this?
Looking forward to your feedback on this issue. If you need more information let me know. 

In any case thank you for your effort on the project :) 

Please provide the following information:

  - [x] pgloader --version

    I tried it both from my Mac and from Debian 

    **Mac**
    ```
    pgloader version "3.6.1" 
    compiled with SBCL 1.5.0
    ```
    **Debian Buster**
      ```
     pgloader version "3.6.1"
     compiled with SBCL 1.4.16.debian
    ```
  - [x] did you test a fresh compile from the source tree?

     I am getting an error at the moment when I try to compile the master branch. Compiling older versions work fine. I will try to figure out the problem and in case I can't fix it, I will open a separate issue for that. 

  - [x] did you search for other similar issues?
The following issues report the same error. However it didn't find a solution there. I hope I didn't miss anything?!: 

    - [Issue 800](https://github.com/dimitri/pgloader/issues/800)
    - [Issue 810](https://github.com/dimitri/pgloader/issues/810)
    - [Issue 859](https://github.com/dimitri/pgloader/issues/859)

  - [x] how can I reproduce the bug? 
     
1) Start a local MySQL source database

     ```bash
     docker run -e MYSQL_ROOT_PASSWORD=root --name=migration_test -p 3306:3306 mysql:5.7
     ```
2) Create dummy data

     ```bash
    read -d "" SQL_COMMAND << EOF

    CREATE DATABASE migration_test;

    CREATE TABLE migration_test.foo (
        id INT,
        first_name VARCHAR(255),
        birthday DATE,
        group_number INT
    ); 

    INSERT INTO migration_test.foo VALUES (1,'foo','1988-02-01',4),
                                           (2,'bar','1987-10-01',1),
                                           (3,'baz','1982-04-01',2);
    EOF

    mysql -h 127.0.0.1 -P 3306 -u root -proot -e "$SQL_COMMAND" sys 
     ```
3) Start Cloud SQL Proxy to connect to Postgres

   ```bash
    GCP_PROJECT=<YOUR_GCP_PROJECT>
    ZONE=<INSTANCE_ZOME>
    INSTANCE_NAME=<INSTANCE_NAME>
    TARGET_PORT=<LOCAL_PORT>

    cloud_sql_proxy --instances=$GCP_PROJECT:$ZONE:$INSTANCE_NAME=tcp:127.0.0.1:$TARGET_PORT
    ```
4) Run pgloader command

    ```bash
    pgloader --debug migration_test_cloud.load
    ```
My pgloader file: **migration_test_cloud.load**

    LOAD database
    FROM mysql://root:root@127.0.0.1:3306/migration_test
    INTO postgresql://<USER>:<PASSWORD>127.0.0.1:<PORT>/<DATABASE>
    WITH include drop,
        disable triggers,
        create no indexes,
        no foreign keys,
        downcase identifiers,
        quote identifiers
    INCLUDING ONLY TABLE NAMES MATCHING 'foo';

  - [x] pgloader output you obtain
  
```
pgloader version 3.6.1
sb-impl::*default-external-format* :UTF-8
tmpdir: #P"/var/folders/2s/l7x9d0fx1p7f8mktg5xlry_80000gn/T/"
2019-06-24T10:04:36.005000+01:00 NOTICE Starting pgloader, log system is ready.
2019-06-24T10:04:36.012000+01:00 INFO Starting monitor
2019-06-24T10:04:36.016000+01:00 LOG pgloader version "3.6.1"
2019-06-24T10:04:36.016000+01:00 LOG Data errors in '/private/tmp/pgloader/'
2019-06-24T10:04:36.016000+01:00 LOG Parsing commands from file #P"*********"
2019-06-24T10:04:36.055000+01:00 INFO Parsed command:
LOAD database
FROM mysql://root:root@127.0.0.1:3306/migration_test
INTO  pgsql:*****
WITH include drop,
    disable triggers,
    create no indexes,
    no foreign keys,
    downcase identifiers,
    quote identifiers
INCLUDING ONLY TABLE NAMES MATCHING 'foo';
2019-06-24T10:04:36.400000+01:00 DEBUG CONNECTED TO #<PGLOADER.PGSQL:PGSQL-CONNECTION *****
2019-06-24T10:04:36.400000+01:00 DEBUG SET client_encoding TO 'utf8'
2019-06-24T10:04:36.400000+01:00 DEBUG SET application_name TO 'pgloader'
2019-06-24T10:04:36.744000+01:00 LOG Migrating from #<MYSQL-CONNECTION mysql://root@127.0.0.1:3306/migration_test {1006552CE3}>
2019-06-24T10:04:36.745000+01:00 LOG Migrating into #<PGSQL-CONNECTION pgsql:*****
2019-06-24T10:04:36.745000+01:00 DEBUG CONNECTED TO #<MYSQL-CONNECTION mysql://root@127.0.0.1:3306/migration_test {1006552CE3}>
2019-06-24T10:04:36.745000+01:00 SQL MySQL: sending query: -- params: db-name
--         table-type-name
--         only-tables
--         only-tables
--         including
--         filter-list-to-where-clause incuding
--         excluding
--         filter-list-to-where-clause excluding
  select c.table_name, t.table_comment,
         c.column_name, c.column_comment,
         c.data_type, c.column_type, c.column_default,
         c.is_nullable, c.extra
    from information_schema.columns c
         join information_schema.tables t using(table_schema, table_name)
   where c.table_schema = 'migration_test' and t.table_type = 'BASE TABLE'
         
         and (table_name = 'foo')
         
order by table_name, ordinal_position;
2019-06-24T10:04:36.745000+01:00 INFO Processing source catalogs
2019-06-24T10:04:36.779000+01:00 NOTICE Prepare PostgreSQL database.
2019-06-24T10:04:37.015000+01:00 DEBUG CONNECTED TO #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql:*****
2019-06-24T10:04:37.016000+01:00 DEBUG SET client_encoding TO 'utf8'
2019-06-24T10:04:37.055000+01:00 DEBUG SET application_name TO 'pgloader'
KABOOM!
2019-06-24T10:04:37.296000+01:00 DEBUG BEGIN
INFO: Control stack guard page unprotected
Control stack guard page temporarily disabled: proceed with caution
2019-06-24T10:04:37.848000+01:00 INFO Stopping monitor

What I am doing here?

Control stack exhausted (no more space for function call frames).
This is probably due to heavily nested or infinitely recursive function
calls, or a tail call that SBCL cannot or has not optimized away.

PROCEED WITH CAUTION.
```

**Comment by 1player** [comment]
Same issue and stacktrace here, on Ubuntu 18.04 and latest available pgloader version from the postgresql repo:

```
pgloader version "3.5.2"
compiled with SBCL 1.4.5.debian
```

But **works as intended when compiled from source**, at tag `v3.6.1`.

Not sure if the issue has been fixed since v3.5.2 or it's an upstream repo problem.

**Comment by wyldbill** [comment]
I'm getting this when running 3.6.1 as installed via apt from postgres

**Comment by jinxiao** [comment]
i have tried 3.6.1 with docker and v3.5.2 in apt repository, the same problem in both

**Comment by benmadin** [comment]
Same here - except that as per advice, I'm using sbcl 2.0.4:

`$ docker run --name pgloader ec09571fa8ff pgloader --debug mysql://<them>@192.168.0.117/<theirdb> postgresql://<me>@192.168.0.117/<mydb>`
`mkdir -p #P"/tmp/pgloader/"`
`pgloader version 3.6.3~devel`
`compiled with SBCL 2.0.4.debian`
`sb-impl::*default-external-format* :UTF-8`
`tmpdir: #P"/tmp/pgloader/"`

and all seems to be going OK until:

`2020-05-19T01:57:03.260000Z INFO Processing source catalogs`
`2020-05-19T01:57:03.774000Z NOTICE Prepare PostgreSQL database.`
`2020-05-19T01:57:03.778000Z DEBUG CONNECTED TO #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://<me>@192.168.0.117:5432/<mydb> {1006E090A3}>`
`2020-05-19T01:57:03.778000Z DEBUG SET client_encoding TO 'utf8'`
`2020-05-19T01:57:03.780000Z DEBUG SET application_name TO 'pgloader'`
`2020-05-19T01:57:03.789000Z DEBUG BEGIN`
`KABOOM!`
`INFO: Control stack guard page unprotected`
`Control stack guard page temporarily disabled: proceed with caution`
`2020-05-19T01:57:04.086000Z INFO Stopping monitor`

`What I am doing here?`

`Control stack exhausted (no more space for function call frames).
This is probably due to heavily nested or infinitely recursive function
calls, or a tail call that SBCL cannot or has not optimized away.`

`PROCEED WITH CAUTION.`

**Comment by jinxiao** [comment]
i think i have solved this problem
use `--type mysql`
e.g.
```
docker run --name pgloader ec09571fa8ff pgloader --debug --type mysql mysql://<them>@192.168.0.117/<theirdb> postgresql://<me>@192.168.0.117/<mydb>

**Comment by danports** [comment]
I have the same problem with the latest Docker image, and `--type mysql` didn't fix it.
```
pgloader version "3.6.3~devel"
compiled with SBCL 1.4.16.debian
```

**Comment by dimitri** [comment]
It is believed that https://github.com/dimitri/pgloader/commit/ab2cadff24f58c933b2c6afd29604c5e938eb8c7 fixed this problems. Please everyone here paste your `SELECT version()` output from the target Postgres database.

**Comment by wenerme** [comment]
```
PostgreSQL 12.2
```

pg to pg

```
2020-06-01T13:25:52.015000Z LOG pgloader version "3.6.3~devel"
2020-06-01T13:25:52.017000Z LOG Parsing commands from file #P"/host/test.load"
2020-06-01T13:25:52.154000Z LOG Migrating from #<PGSQL-CONNECTION pgsql://{10068D5993}>
2020-06-01T13:25:52.154000Z LOG Migrating into #<PGSQL-CONNECTION pgsql://{10068D8493}>
KABOOM!
INFO: Control stack guard page unprotected
Control stack guard page temporarily disabled: proceed with caution

What I am doing here?

Control stack exhausted (no more space for function call frames).
This is probably due to heavily nested or infinitely recursive function
calls, or a tail call that SBCL cannot or has not optimized away.

PROCEED WITH CAUTION.
```

**Comment by danports** [comment]
```
PostgreSQL 11.2-YB-2.1.6.0-b0 on x86_64-pc-linux-gnu, compiled by gcc (Homebrew gcc 5.5.0_4) 5.5.0, 64-bit
```
(YugabyteDB running the PostgreSQL front end)

**Comment by oliviernguyenquoc** [comment]
Same issue here. Migration on Google Cloud SQL too.

Result of SELECT version(): PostgreSQL 12.1

**Comment by dimitri** [comment]
Thanks for the version strings! I made sure the samples you've provided are correctly parsed now. Will have to spend more time later maybe to understand why we have a control stack exhausted, couldn't reproduce that tonight using CCL for development.

**Comment by danports** [comment]
Thanks @dimitri! Will give the new version a try - I assume the `latest` Docker tag reflects `master`?

**Comment by oliviernguyenquoc** [comment]
Thanks @dimitri ! Works perfectly.

Quick answer, perfect fix. What a great open source project !

**Comment by danports** [comment]
Still seeing the exact same error here, no change to the `--debug` output. 😞

**Comment by danports** [comment]
Alright, I tried with the `ccl.latest` tag and it seems like pgloader is actually getting somewhere... 🤞  Although curiously the `--debug` flag doesn't seem to be working with this image.
